### ISSUE TITLE
fn to &#955;

### ISSUE THREAD

**Issue by niquola** [tonsky/FiraCode#1]
I've seen in someone emacs:

 (fn [] ... )   => (&#955; [] ...)

**Comment by alexandernst** [comment]
While at it, add `function()` => `λ()` too :)

**Comment by tonsky** [comment]
The idea is to keep width so monospace-aligned programs will look the same. Unfortunately, even fn as λ is too much width difference

**Comment by alexandernst** [comment]
`fn` are two characters, let's say 6px each one. Make `λ` occupy 12px and center it. Problem solved!
(does it work that way?)

**Comment by tonsky** [comment]
Yes, but looks unnatural. Believe me, I've tried

-----Original Message-----

**Comment by tonsky** [comment]
Ok, after couple of issues and conflicts in other languages (e.g. `||` meaning logical OR, empty list of arguments in Ruby’s closures, list comprehension in Erlang) I decided to stick to ligatures that only slightly compensate looks and spacing, without changing the look completely.

If you want (fn [] ... ) => (λ [] ...), check out https://github.com/tonsky/clojure.unicode
