### ISSUE TITLE
Misplaced descenders on Cyrillic letters U+04CB and U+04CC

### ISSUE THREAD

**Issue by dscorbett** [tonsky/FiraCode#1001]
In version 3.1, the descenders of U+04CB CYRILLIC CAPITAL LETTER KHAKASSIAN CHE and U+04CC CYRILLIC SMALL LETTER KHAKASSIAN CHE are misplaced. They should be on the left side of the vertical stroke, not the right side. I suspect this happened because of [a misinformed comment](https://github.com/tonsky/FiraCode/issues/995#issuecomment-612145729) on #995.
![Ӌӌ](https://user-images.githubusercontent.com/1124347/79370685-1cad7700-7f21-11ea-9e87-a116984ccec9.png)

**Comment by tonsky** [comment]
oops
