### ISSUE TITLE
Probably wrong description of zero set

### ISSUE THREAD

**Issue by Vampire** [tonsky/FiraCode#1003]
If you drop current version to https://fontdrop.info, the `zero` stylistic set is described as `Slashed Zero Feature` while it actually is `Dotted Zero Feature` and also called like that in the readme.
So it seems in the file there is somewhere the slashed string which should probably be dotted.

**Comment by tonsky** [comment]
I will check, but this might be the default name for the feature, not something embedded in the font. Normally fonts have O-like zero, and `zero` is slashed/dotted variant

**Comment by Vampire** [comment]
Ah, ok, I see.
No problem, just thought this might have slipped in somehow. :-)
Just close it then if that's the case.
