### ISSUE TITLE
Misplaced characters 

### ISSUE THREAD

**Issue by atifchy** [tonsky/FiraCode#1004]
![* issue](https://user-images.githubusercontent.com/42291930/79639275-ae7ce480-81ac-11ea-91be-802b8f9e8020.png)
![- issue](https://user-images.githubusercontent.com/42291930/79639278-b3419880-81ac-11ea-95ac-fb265db5f73f.png)

**Comment by tonsky** [comment]
The stars are intentional. The minus is not. Tracked in https://github.com/tonsky/FiraCode/issues/389
