### ISSUE TITLE
Misplaced descender on Cyrillic letter U+0449

### ISSUE THREAD

**Issue by ivashin** [tonsky/FiraCode#1007]
Cyrillic letter щ (U+0449 Cyrillic Small Letter Shcha) has descender in the center instead of on the right. ![image](https://user-images.githubusercontent.com/11612642/79693709-f8310200-8274-11ea-9805-7bf8e97cda8b.png) (cool symbol BTW :smile:)
Most likely introduced by https://github.com/tonsky/FiraCode/commit/bd081655edce143467c2090b788d57d08c06defc

**Comment by tonsky** [comment]
Damn, I messed up :) Thanks!
