### ISSUE TITLE
Italic "<!--" and "-->" not aligned correctly

### ISSUE THREAD

**Issue by sungvzer** [tonsky/FiraCode#1008]
So when using HTML comments ligatures, i found out that the left one is a few pixels higher than the right one. 
I'm actually using Fira Code with Ligatures, and the problem can be found only in the Italic version, as with the normal version this does not occur.
![image](https://user-images.githubusercontent.com/52582911/79760287-291a4100-8320-11ea-8940-01ac30469917.png)
Italic

![image](https://user-images.githubusercontent.com/52582911/79760440-5961df80-8320-11ea-9922-84e9c2ccf7e6.png)
Normal

**Comment by tonsky** [comment]
Should’ve been handled in #917. Please update to the latest version.

**Comment by sungvzer** [comment]
Updating to latest version fixed this.
Closing
