### ISSUE TITLE
Different interval between lines in "strict equal" symbol

### ISSUE THREAD

**Issue by aplab** [tonsky/FiraCode#1009]
Different interval between lines in "strict equal" symbol 
IDE vscode and jetbrains products, font size 12,13,17, OS Ubuntu

![2020-04-20_19-08](https://user-images.githubusercontent.com/4007240/79761163-8622f080-833a-11ea-93e0-5af661abb8b9.png)

**Comment by tonsky** [comment]
Thank you! It’s a known problem, I have no way of solving as of today. I’ll close this as duplicate https://github.com/tonsky/FiraCode/wiki/Troubleshooting#hinting-issues
