### ISSUE TITLE
Small sizes readability in Qt Creator

### ISSUE THREAD

**Issue by iamakulov** [tonsky/FiraCode#101]
Hi!

Is there a way to improve FiraCode readability in small sizes? Currently, the font size of 9 looks like follows:

![app cpp_ master _-_coursework_-_qt_creator_2016-01-01_19-30-21](https://cloud.githubusercontent.com/assets/2953267/12071439/0f42d88e-b0be-11e5-8bae-7d0b5e4e92f3.png)

Arial (on the left) seem to be much more clear and readable than Fira Code (on the right).

**Comment by tonsky** [comment]
Are you using Fira Code version 1.102? It has hinting turned on. How does Fira Mono looks under the same conditions?

**Comment by iamakulov** [comment]
Yes, version 1.102. Downloaded it just yesterday.

Fira Mono (`ttf` version) looks great:
![zr5gwsj 1](https://cloud.githubusercontent.com/assets/2953267/12074092/eb384584-b151-11e5-9644-7d50081fc2f5.png)

Fira Mono (`otf` version) looks bad:
![3tx45hf 1](https://cloud.githubusercontent.com/assets/2953267/12074101/325d9004-b152-11e5-9df1-5df6bb1d3497.png)

**Comment by tonsky** [comment]
Ok, I’ll try packing ttf into next release, let’s see if that will improve
situation

**Comment by iamakulov** [comment]
(Related to #38)

**Comment by tonsky** [comment]
@iamakulov does ttf work any better for your setup?

**Comment by iamakulov** [comment]
Yes, ttf version looks great. Thank you!

<img width="960" alt="qtcreator_2016-10-12_11-50-45" src="https://cloud.githubusercontent.com/assets/2953267/19303685/4ab7ea50-9072-11e6-8324-6843bbd1261b.png">

**Comment by tonsky** [comment]
I’m glad it solved everything!
