### ISSUE TITLE
missing glyphs sublime text 3

### ISSUE THREAD

**Issue by spewil** [tonsky/FiraCode#1010]
hi, not sure what's wrong here? i'm missing left arrows and some other things. i assume it is a problem with my settings, but it's bugging me. thanks in advance 

<img width="219" alt="Screen Shot 2020-04-24 at 12 37 10 PM" src="https://user-images.githubusercontent.com/1320478/80208745-c333ff00-8628-11ea-8acc-22c8e999b204.png">
<img width="247" alt="Screen Shot 2020-04-24 at 12 36 52 PM" src="https://user-images.githubusercontent.com/1320478/80208748-c4652c00-8628-11ea-9744-2012ac204937.png">

**Comment by tonsky** [comment]
This is probably SublimeText tokenising string before applying ligatures to them. Essentially, it shapes `<` and `==` separately. Nothing I can do on FiraCode end. Try setting syntax in that file to plain text and see if problem persists.

**Comment by spewil** [comment]
Thanks. Didn't think about this. Works in plain text. 

Would it help to make a custom syntax....?

**Comment by tonsky** [comment]
Yes. If your syntax will not split those sequences apart, they will be rendered with ligatures.
