### ISSUE TITLE
Unability to enable ligatures in VSCode

### ISSUE THREAD

**Issue by IlyasShingarov** [tonsky/FiraCode#1011]
I was unable to turn on ligatures in VSCode on windows 10. The text just looked like all spaces are deleted, and I could not find any ligatures, while I edited JSON file as was instructed.

**Comment by tonsky** [comment]
Please share your config and screenshots

**Comment by IlyasShingarov** [comment]
![image](https://user-images.githubusercontent.com/32528294/80282945-fbb50500-871c-11ea-9368-b334006ac729.png)
![image](https://user-images.githubusercontent.com/32528294/80282952-07083080-871d-11ea-9104-b6c8fac47eca.png)

**Comment by j-f1** [comment]
Try setting your `editor.fontFamily` to `Fira Code` (note the space). What you’re seeing now is Times New Roman, which indicates it couldn’t find the font.

**Comment by IlyasShingarov** [comment]
Thanks it solved the problem
