### ISSUE TITLE
I don't know how to update the font

### ISSUE THREAD

**Issue by DaveRainbowin** [tonsky/FiraCode#1012]
I have installed the new 3.1 font, but the =~ ligature doesn't work? Is this supposed to happen? I am using vscode

**Comment by DaveRainbowin** [comment]
None of the new ligature works. It didn't update?

**Comment by tonsky** [comment]
what OS are you on?

**Comment by DaveRainbowin** [comment]
Windows 10

**Comment by tonsky** [comment]
Have you restarted VS Code? Windows? Also try manually cleaning your C:\Windows\Fonts folder https://github.com/tonsky/FiraCode/wiki/Troubleshooting#corrupted-font-in-intellij-on-windows

**Comment by DaveRainbowin** [comment]
Restarted both, didn't work
How do I clean it out with the command line? I'm not good with the command line

**Comment by DaveRainbowin** [comment]
Actually, it seems it did update, other ligature works but =~ do not

**Comment by DaveRainbowin** [comment]
Nevermind, I see why
