### ISSUE TITLE
5/6 markdown #

### ISSUE THREAD

**Issue by DaveRainbowin** [tonsky/FiraCode#1014]
It would be slightly nice, it would be ok if no, just a qol suggestion.
\#### exist, so why not ##### or ######?

**Comment by tonsky** [comment]
Yeah, might be a good idea, thanks!

**Comment by DaveRainbowin** [comment]
thank you, much appreciated!

**Comment by tonsky** [comment]
Done in v4

**Comment by DaveRainbowin** [comment]
thank you :)
