### ISSUE TITLE
Add =>= and =<= Haskell comonadic composition ligatures

### ISSUE THREAD

**Issue by anon476** [tonsky/FiraCode#1016]
For binds, you already have the comonadic dual covered.
`>>=` <-> `=>>`
`=<<` <-> `<<=`
But, monadic compositions are lonely.
`>=>` <-> `=>=`
`<=<` <-> `=<=`

The latter is especially weird because the `<=` renders as less than or equal to. Please implement comonadic composition operators =>= and =<=.

**Comment by tonsky** [comment]
Thanks! Will add

**Comment by tonsky** [comment]
Done in v4
