### ISSUE TITLE
Mediawiki titles == === ==== ===== ======

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#1018]
In MediaWiki (Wikipedia) titles are marked with `== h2 ==`, `=== h3 ===`, `==== h4 ====`, `===== h5 =====` and `====== h6 ======`.
It would be nice to have support for the h4+ equals, possibly by having 4/5/6 lines.

**Comment by tonsky** [comment]
Thanks! If I figure out the way to do #346, I’ll do those as well.

**Comment by RubenVerg** [comment]
i guess the point is not having loooooong equals, but instead an equal with four lines :)

**Comment by tonsky** [comment]
Even three is considered by many as too much

**Comment by RubenVerg** [comment]
I guess, but only MW uses 4/5/6 equals afaik.

**Comment by tonsky** [comment]
Done in v4
