### ISSUE TITLE
Add U+2E3A TWO-EM DASH, U+2E3B THREE-EM DASH

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#1019]
Styling for 3EM and 2EM dashes, (at least in VSCode) they appear to be long twice/three times a normal character. Maybe they're already supported and styled to be 2/3 long, but that would be against the monospacing.

**Comment by tonsky** [comment]
U+2E3A TWO-EM DASH ⸺
U+2E3B THREE-EM DASH ⸻
I don’t think there’s a way to make those monospaced, but I can make them occupy 2 and 3 places.

**Comment by Tazshelby2016** [comment]
They would occupy two and three full widths accordingly. I will say, certain other monospace fonts ignored dash length and made many dashes one full width.
