### ISSUE TITLE
Small caps

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#1023]
```
ᴀʙᴄᴅᴇꜰɢʜɪᴊᴋʟᴍɴᴏᴘꞯʀꜱᴛᴜᴠᴡʏᴢᴁᴃᴆᴣⱻʛᵻᴌꟺᴎɶᴐᴕᴙᴚʁꭆꝶᵾᴦᴧᴨᴩᴪꭥ
```
(no X, and I can't see Q ಥ︵ಥ)

Also you can clearly see form my recent suggestions I've been using WinCompose a lot ಠ—ಠ

**Comment by RubenVerg** [comment]
???

**Comment by tonsky** [comment]
I’ll pass, thanks
