### ISSUE TITLE
Alternate !=

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#1024]
This is kind of a follow-up from people saying that `/=` could be unequality, but kept to distinguish from `!=` while still resembling unequality.
My suggestion here is that `!=` (and `!==`) are styled as a `!` striking an equal instead of a `|`. That would practically mean removing a pixel-high line from the line below the equal in `≠`, I guess.

**Comment by tonsky** [comment]
I’m fine with ≠

**Comment by RubenVerg** [comment]
:)
