### ISSUE TITLE
[Help] How to enable FFS + ligatures on VSCode?

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#1025]
In VSCode, both font feature settings are edited with the same key, `editor.fontLigatures`
I want to have both ligatures enabled and some stylistic sets selected i tried:
```json
"editor.fontLigatures": "true, 'ss01'"
---
"editor.fontLigatures": "true 'ss01'"
---
"editor.fontLigatures": true "'ss01'"
---
"editor.fontLigatures": true
"editor.fontLigatures": "'ss01'"
---
"editor.fontLigatures": "'ss01'"
"editor.fontLigatures": true
```
but none works.
The ones with 2 keys only select the last one, as JSON works so.

**Comment by RubenVerg** [comment]
The ones with tow keys only select the last one, as JSON works so.

**Comment by tonsky** [comment]
Please consulte the wiki https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets#vs-code

**Comment by RubenVerg** [comment]
I did what it says, but only setting ffs disables ligatures!

**Comment by alexeyten** [comment]
Try
`"editor.fontLigatures": "'calt' 1, 'ss01' 1"`

**Comment by tonsky** [comment]
No, 'calt' is not needed. Any non-empty value on editor.fontLigatures implies calt

**Comment by tonsky** [comment]
@RubenVerg what is `ffs` and where does it come from?

**Comment by RubenVerg** [comment]
font feature settings, the css key.

**Comment by tonsky** [comment]
the keys must be `ss01`, `ss02`, ...

**Comment by RubenVerg** [comment]
yes, that was just to not fill pu, I'll edit original issue now :0

**Comment by RubenVerg** [comment]
also side-suggestion, a separate space for help?
