### ISSUE TITLE
<--> weird?

### ISSUE THREAD

**Issue by DaveRainbowin** [tonsky/FiraCode#1029]
<--> is interpreted as < and -->. I think it should be <, --, and >.

**Comment by DaveRainbowin** [comment]
update: same with <~~>, it acts like < and ~~>

**Comment by DaveRainbowin** [comment]
additionally, it appears that +=, -=, and *= have no ligature, but /=, perhaps we could have those unless it would be weird

**Comment by DaveRainbowin** [comment]
i see there are multiple issues about += -= and *=. oops

**Comment by DaveRainbowin** [comment]
another thing: <~> the tilde is off-center

**Comment by tonsky** [comment]
Thanks, I’ll look into it

**Comment by tonsky** [comment]
Done in v4

**Comment by DaveRainbowin** [comment]
thank you again :)
