### ISSUE TITLE
Add U+1d112 or U+02BC?

### ISSUE THREAD

**Issue by DaveRainbowin** [tonsky/FiraCode#1031]
I request U+1d112 or U+02BC modifier letter apostrophe to act as a superscript comma. Why? First: unicode has no superscript comma; Second: this is for a text file where i cannot make superscript; third: it's not monospace :(
This is for chemical nomenclature btw
Thanks for a reply!

**Comment by tonsky** [comment]
Why doesn’t apostrophe work for you?

**Comment by DaveRainbowin** [comment]
⁸'⁹, here is ok, in fira code it is too high and too far

**Comment by tonsky** [comment]
If you are writing superscript maybe consider switching to an environment that supports it natively

**Comment by DaveRainbowin** [comment]
ok, i will use apostraphe and convert to markdown later, thanks for feedback :)
