### ISSUE TITLE
Common chars ❱,❰,↲ in code editors

### ISSUE THREAD

**Issue by abravalheri** [tonsky/FiraCode#1032]
Hello @tonsky, Fira Code is really amazing.

I was wondering if we could have some common codepoints that are used to display hidden chars in some editors.

Particularly, I have the following configuration in vim:

```vim
set listchars=tab:▶\ ,trail:•,extends:❱,precedes:❰,nbsp:␣,eol:↲
```
(unfortunately, Fira Code does not support U+21B2, U+2771, U+2770)

You can see that this is a common practice in:
- https://www.reddit.com/r/vim/comments/4hoa6e/what_do_you_use_for_your_listchars/

Thank you very much for the project!

**Comment by tonsky** [comment]
Sure. Shouldn’t be a problem!

**Comment by abravalheri** [comment]
Thanks a lot @tonsky. That is awesome!
