### ISSUE TITLE
IPA symbols do not show up correctly?

### ISSUE THREAD

**Issue by DaveRainbowin** [tonsky/FiraCode#1035]
There is nothing wrong with how they look, but they are in the wrong spot. ʙ̥ is where i encountered the issue. Both symbols are included, but the circle below the B here is instead to the side, like ʙ ̥ instead. I will come back later to tell you if this happens on other IPA symbols

**Comment by tonsky** [comment]
I don’t think they are included at all

**Comment by DaveRainbowin** [comment]
Well, then they must be part of monospace font then, because they are monospace... but still could you add them?

**Comment by tonsky** [comment]
Most likely not. Too much work. Sorry

**Comment by DaveRainbowin** [comment]
Alright then, it's fine :)
