### ISSUE TITLE
Lower letter "щ" is incorrect (U+0449)

### ISSUE THREAD

**Issue by DanielPancake** [tonsky/FiraCode#1037]
It should look like this:
![correct letter](https://user-images.githubusercontent.com/45727078/81905620-5f28a900-95de-11ea-8aa1-2ab2bbe255f7.png)
...not like this:
![incorrect letter](https://user-images.githubusercontent.com/45727078/81905374-0e18b500-95de-11ea-89b3-22c0ef4bc050.png)

https://en.wikipedia.org/wiki/Shcha

**Comment by kavu** [comment]
Yeah, just noticed it too. I thought it was intended 😄

**Comment by sbalyakin** [comment]
Yep, it's very strange looking

**Comment by tonsky** [comment]
I broke it in 3.1, fix coming soon in 4.0. See https://github.com/tonsky/FiraCode/commit/19fd32dc95ed813ce810b7683ee24713f0522d8a
