### ISSUE TITLE
Python byte string (\x) should be formatted like traditional hex (0x)

### ISSUE THREAD

**Issue by TheNewJavaman** [tonsky/FiraCode#1039]
In this font, the x is vertically centered for hexadecimal. The same should also be true for Python-formatted hexadecimal.
### Python 
byte_string = b"\x00\xff"
### Normal hexadecimal
0x00ff

**Comment by tonsky** [comment]
isn’t `x` here part of the escape sequence? `\x` go together, no?

**Comment by TheNewJavaman** [comment]
Correct
