### ISSUE TITLE
The += operator should have a ligature

### ISSUE THREAD

**Issue by TheNewJavaman** [tonsky/FiraCode#1041]
My suggestion is a + with a _ underneath it.

**Comment by tonsky** [comment]
I’m not sure. += is actually two operations (+ followed by a =), so unifying them might not be a best idea.

Second concern is that from the look of the ligature I must be able to say what’s in it. + with a _ would look like +-, not like +=

**Comment by RubenVerg** [comment]
three operations: get, add, set

**Comment by RubenVerg** [comment]
Also #655 seems to be **the** place for discussing `+=` etc

**Comment by TheNewJavaman** [comment]
Gotcha, nevermind
