### ISSUE TITLE
Misspelling in extras/math.png

### ISSUE THREAD

**Issue by pyproman** [tonsky/FiraCode#1045]
Hello, I just found a typo in [extras/math.png](https://github.com/tonsky/FiraCode/tree/master/extras/math.png): 
![Multiline must be instead of Miltiline](https://user-images.githubusercontent.com/45491635/82190279-7bd42200-98f9-11ea-8dd3-127c7fbad47c.png "Replace Miltiline to Multiline")

**Comment by RubenVerg** [comment]
i also did, to later forget that :(

**Comment by tonsky** [comment]
Thank you! Second time I fix that :) #1028
