### ISSUE TITLE
Box drawing characters don't correspond with minus sign

### ISSUE THREAD

**Issue by Igorgro** [tonsky/FiraCode#1046]
This is how they look in VS Code:
![изображение](https://user-images.githubusercontent.com/22894169/82334908-490d5500-99f1-11ea-99f4-38d8201514f6.png)
The left part is made of box-drawing horizontal line and the right part is made of minus symbols.

**Comment by RubenVerg** [comment]
is it just me or does this feel correct

**Comment by tonsky** [comment]
this is not perfect, but why are you trying to mix hyphens and box drawing?

**Comment by RubenVerg** [comment]
¯\_(ツ)_/¯
