### ISSUE TITLE
issues with ligature ->

### ISSUE THREAD

**Issue by hanickadot** [tonsky/FiraCode#1049]
Ligature -> is not working if it's next to [a-z] character. It's working correctly with a number, other arrow ligatures (=>) are not impacted.

<img width="152" alt="Screenshot 2020-05-21 at 12 30 29" src="https://user-images.githubusercontent.com/6557263/82550533-f9e53280-9b5e-11ea-8a95-e555d3016060.png">

I'm having the latest release (4)

**Comment by tonsky** [comment]
This is probably your editor interfering, splitting `-` and `>` into separate tokens. https://github.com/tonsky/FiraCode/wiki/Troubleshooting#some-ligatures-work-while-some-dont

Try reporting it to the editor author or to the person responsible for language grammar for your editor.

**Comment by hanickadot** [comment]
The screenshot is from MacOS Font Book, I tried TextEdit and TextMate. All with same result.

**Comment by hanickadot** [comment]
I found it on a new clean mac when I installed the font. On older mac, I just updated the font, and it didn't do the error. When I removed the font, restarted, and add the font it's doing even on the other mac.

**Comment by hanickadot** [comment]
I just tried iPhone with woff and Chrome with same result:
<img width="404" alt="Screenshot 2020-05-21 at 22 14 02" src="https://user-images.githubusercontent.com/6557263/82601883-82d88a00-9bb0-11ea-8cd2-861d73391179.png">
![IMG_2093](https://user-images.githubusercontent.com/6557263/82601900-8b30c500-9bb0-11ea-98e4-b414a370278e.png)

(I added a textarea into the example html page)

**Comment by tonsky** [comment]
Thanks, I’ve been able to reproduce it. I even think I know what the problem is. Will fix!

**Comment by DaveRainbowin** [comment]
Same happens to me in vscode when i try a->b. a ->b works as does a -> b, as long as it starts as a-> it doesn't work
