### ISSUE TITLE
Phpstorm: long combinations with '-', '=', '#' symbols  doesn't work

### ISSUE THREAD

**Issue by sabri-said** [tonsky/FiraCode#1051]
I'm on Pop!_OS and I updated Fira Code v3 to v4 but I noticed that long combinations doesn't work in Phpstorm with more of one **'-'**, more of 3 **'='**, or more of 4 **'#'** symbols.
It result than I can combines it to **'<'** or **'>'** for arrows or '|' for markdown or other stuff.
Same for **'#'**, if more of 4 are written, the symbol doesn't render anymore.

However all the symblos work well in Gedit text editor or on Atom on a simple text file and I can do infinite combinations of the symblos listed above

**Comment by tonsky** [comment]
Please report it to Phpstorm. Might be a syntax highlighting issue https://github.com/tonsky/FiraCode/wiki/Troubleshooting#some-ligatures-work-while-some-dont
