### ISSUE TITLE
Eclipse Win10: <= and >= broken since release 4

### ISSUE THREAD

**Issue by omicron81** [tonsky/FiraCode#1052]
In Eclipse 4.15.0 on Win10, since the update from FiraCode  3 to 4, `>=` and `<=` are not combined anymore. 
But `!=`, `<<` and `>>` still work as expected.

**Comment by tonsky** [comment]
Are you sure this isn’t syntax highlighting interfering? Try typing them inside a commen

**Comment by omicron81** [comment]
I've re-checked with Fira Code 3.1 now and it shows the same behavior as version 4. 
Although I could swear that I've seen >= and <= ligatures before in Eclipse, it seems that the issue has nothing to do with Fira Code changes from 3.1 to 4.

There is even an Eclipse Bug (https://bugs.eclipse.org/bugs/show_bug.cgi?id=562165) to support ligatures in Eclipse on Windows, which will be fixed in the upcoming Eclipse release 4.16. So hopefully that fixes the issue.
