### ISSUE TITLE
GX and VF variants

### ISSUE THREAD

**Issue by tormento** [tonsky/FiraCode#1054]
I am a bit confused about the differences between GX and VF and I'd like to have more information about them here or on readme.md, such as compatible editors, how to use them, etc…

Thanks!

**Comment by tonsky** [comment]
Fair enough! The only difference is how they exported, someone had problem with one of them on Windows, so I created another one but can’t remember which is which now :) Will leave one in the next version. Thanks!

**Comment by tonsky** [comment]
This one https://github.com/tonsky/FiraCode/issues/770

**Comment by tormento** [comment]
Thans, You have any hint to correctly use them in editors? Windows 10 has full support to VF, the editors a bit less.

**Comment by tonsky** [comment]
No idea, sorry

**Comment by tormento** [comment]
@tonsky the FiraCodeGX.ttf is the one working for me under Windows 10 x64 insider 19631. This one shows the major "families", the VF version shows various copies of "Regular" only.

**Comment by be5invis** [comment]
@tonsky @tormento 
`FiraCode-VF.ttf` has an empty `STAT` table, which should be the problem.
![image](https://user-images.githubusercontent.com/240091/83339111-53e0a900-a27f-11ea-9869-09dcc4a65db1.png)

`FiraCodeGX.ttf` on the other hand has a working `STAT` table.
![image](https://user-images.githubusercontent.com/240091/83339129-7ecafd00-a27f-11ea-8740-29332c514915.png)

**Comment by tormento** [comment]
I hope a unified VF will be out soon ;)
