### ISSUE TITLE
[ftrq] Circled and squared set

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#1055]
A set for ligating `/\[(.)\]/` to squared capture 0 and same for `/\((.)\)/` but circled (the same set, I'd say)
IF regex matching isn't possible on fonts, I'd say to add support for
```
a-zA-Z0-9!#$%&*-+=.:\/?~↑↓←→
```

**Comment by tonsky** [comment]
Sorry, I don’t understand what are you asking

**Comment by RubenVerg** [comment]
Making `(a)` into `ⓐ`, for example

________________________________

**Comment by RubenVerg** [comment]
Making `(a)` into `ⓐ`, for example

**Comment by tonsky** [comment]
Sorry, but this makes no sense. Fira Code ligatures are supposed to unify operators that are single entity but consist of multiple glyphs. In regexp, brackets are capture groups, but contents of the brackets have no relation to them and should be grouped.

**Comment by RubenVerg** [comment]
Capturing an a actually is a single token?


Ruben Vergani
rubenverg.com
(◠–◠)
Sent with Mail for Windows 10

________________________________

**Comment by ollicle** [comment]
@RubenVerg do you mean font variation annotation?
I read about these recently (last item on this post):
>Annotations are notational forms of glyphs (for example, glyphs placed in open or solid circles, squares, parentheses, diamonds, rounded boxes. etc.).
https://www.jonathan-harrell.com/blog/better-typography-with-font-variants/

**Comment by RubenVerg** [comment]
it appears, yes.
