### ISSUE TITLE
Did something changed with v4? Can't get a clean font look in Windows 10. Glitches.

### ISSUE THREAD

**Issue by gremo** [tonsky/FiraCode#1057]
I'm using Fira Code since version 2. It was absolutely stunning and I used it everywhere  (Mintty, Visual Studio Code, Windows Terminal, etc.) and I thank you for that.

Yesterday I formatted my workstation, thus installing v4 (using Chocolatey package manager). Now, Fira Code doesn't look like it was. An example it Mintty:

![fira](https://user-images.githubusercontent.com/1532616/82836859-baed0f00-9ec7-11ea-86f7-84b2b968a7d8.png)

Look at (150% zoom) the strange glitches above/below the `o`, `a` and `c` letters:

![fira2](https://user-images.githubusercontent.com/1532616/82836963-0bfd0300-9ec8-11ea-9212-dc6ffb1e17e4.png)

Is this something with my setup? What do you think?

**Comment by gremo** [comment]
... ends up that Chocolatey package install the OFT, not TTF.

I manually installed TTF and it look stunning and beautiful as always.

**Comment by tonsky** [comment]
Glad this is resolved! Windows should always install TTF, not sure why Chocolatey ships OTF. I have plans to remove OTF to avoid confusion https://github.com/tonsky/FiraCode/issues/939

**Comment by gremo** [comment]
Chocolatey ships OTF because the creator of the package did that. He's not answering to people request and suggestions. It's a shame that a good package manager like that have so poor quality packages.

Anyways, keep up the good work!
