### ISSUE TITLE
--> does not work as expected in v4

### ISSUE THREAD

**Issue by JacobDB** [tonsky/FiraCode#1059]
It's not combining both dashes, it just combines the last `->`.

![image](https://user-images.githubusercontent.com/1123997/83036002-c2173880-9fff-11ea-8eda-1cc772e1857c.png)

**Comment by JacobDB** [comment]
Strangely, it's working for one particular comment here...

![image](https://user-images.githubusercontent.com/1123997/83036461-3fdb4400-a000-11ea-91f3-718ed4369595.png)

**Comment by tonsky** [comment]
Thanks. It’s already been reported as #1049, will fix in next version. This happens because of lowercase/uppercase hyphen adjustment

**Comment by JacobDB** [comment]
Oh cool, didn't see that one. Thanks!
