### ISSUE TITLE
Sublime Text regression with Medium v4

### ISSUE THREAD

**Issue by Nindaleth** [tonsky/FiraCode#1060]
After the update some of the ligatures are broken on my setup.

System: Fedora 32
Package source: official Fedora `@updates` repo
Package version: fira-code-fonts-4-1.fc32.noarch

Sublime Text version: 3dev, Build 3210
Sublime Text settings:
```
	"font_face": "Fira Code Medium",
	"font_options":
	[
		"gray_antialias",
		"no_italic",
	],
	"font_size": 9,
```

(1) This is how Medium looks like with those settings (font sizes 8-10 provide the same result):
![st3_medium_9](https://user-images.githubusercontent.com/6383928/83127088-0545da00-a0da-11ea-9ca6-0c6c65d6539d.png)

(2) Medium, changing `font_options` to `"subpixel_antialias"`:
![st3_medium_subpixelaa_9](https://user-images.githubusercontent.com/6383928/83127511-89985d00-a0da-11ea-9a41-1945b22c7d8c.png)

(3) Reference in Regular (regardless of `font_options`):
![st3_regular_9](https://user-images.githubusercontent.com/6383928/83127077-024ae980-a0da-11ea-9c68-86cc0ee0b1db.png)

I experimented with `font_options` and as long as `"subpixel_antialias"` is gone and `"gray_antialias"` is present, I get (1). As long as `"subpixel_antialias"` is present (even with `"gray_antialias"` present too), I get (2).

If any more information is needed, please let me know, I'll gladly add it if I can.

**Comment by tonsky** [comment]
I guess it’s something with Sublime, Linux or the combination of both. The only advice I can give is try downloading & installing fonts directly from github, and maybe make sure you’re using TTF, not OTF. If that doesn’t help, try reporting this to Sublime and/or Linux

**Comment by Nindaleth** [comment]
Started my work laptop today with the same config and there are no issues any longer, interesting. Sorry about the noise, seems like a transient issue somewhere deeper than Fira Code.
