### ISSUE TITLE
Suggestion: align colons in `:>:` and `:<:`

### ISSUE THREAD

**Issue by JonasHoefer** [tonsky/FiraCode#1061]
The set of ligatures which aligns `:` and `<`/`>` (`<:`, `:<`, `:>`, `>:`) sadly does not include three character sequences (related #980). In Haskell, code its quite common to wrap operators between two `:` (starting with a `:` allows you to use them as a constructor). In `:>:` and `:<:` the two colons do not align, which is a bit annoying, because it breaks the symmetry.

**Comment by tonsky** [comment]
thanks, will do!
