### ISSUE TITLE
Suggestion: JSON ligatures

### ISSUE THREAD

**Issue by AskAlice** [tonsky/FiraCode#1062]
ligatures for 
({
([
])
})
}}
}]
[{

**Comment by tonsky** [comment]
Thanks for the suggestion! The idea of Fira Code is to only join characters that are part of one logical operation. Parents/brackets in JSON are independent and better not be joined. It’s possible to slightly adjust how they look together but I don’t think it’s needed too.

**Comment by RubenVerg** [comment]
Is it just me, or I write

[
   {
        …
   }
]

**Comment by AskAlice** [comment]
well, if i were to fork and do this myself, could anyone give me some pointers on where to get started? the src of this is really confusing to me

**Comment by tonsky** [comment]
I use Glyphs.app, I also have some details shared at my patreon https://www.patreon.com/tonsky/posts?filters%5Btag%5D=Fira%20Code

I wouldn’t recommend getting into my particular setup in this repo, I have some things automated but they are mostly Fira Code-specific. `Fira Code.glyphs` is all you need
