### ISSUE TITLE
Progress bars in QTerminal/Konsole

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#1064]
This still happens on progress bars of some command-line programs. Can it be fixed in any way?

For example this is a progress bar that appears when loading a docker image with `docker load`:

![image](https://user-images.githubusercontent.com/1224006/83395919-68e24700-a3fb-11ea-8935-858ddbaa8da2.png)

_Originally posted by @nilp0inter in https://github.com/tonsky/FiraCode/issues/968#issuecomment-636737125_

**Comment by nilp0inter** [comment]
Continuing with the conversation in #968, I tested the font in the suggested code editors and it works as expected:

In **Sublime** it works in the text editor as well as in the Terminus plugin.

![image](https://user-images.githubusercontent.com/1224006/83638959-46426080-a5aa-11ea-92f1-42aa9882a6bf.png)

In **VSCode** ligatures work in the editor but not in the terminal (although maybe I am missing some configuration option)

![image](https://user-images.githubusercontent.com/1224006/83641459-d9c96080-a5ad-11ea-9020-41c1cad1ab23.png)

**Comment by nilp0inter** [comment]
`kitty` works!

![image](https://user-images.githubusercontent.com/1224006/83642122-b94dd600-a5ae-11ea-8ebe-533f33a7c33c.png)

**Comment by nilp0inter** [comment]
Patched `st` works too.

![image](https://user-images.githubusercontent.com/1224006/83647199-ef8e5400-a5b4-11ea-9db1-bbd6b0251110.png)

I am afraid I can't check more terminals in my setup easily.

Given the results I suspect the bug is maybe related to Qt?

**Comment by wopian** [comment]
> but not in the [vscode] terminal (although maybe I am missing some configuration option)

Current terminal rendering system used (xterm.js) doesn't support ligatures - https://github.com/microsoft/vscode/issues/34103. 

Although this reminded me to check my bookmarked issues for this and ligatures may be back in the vscode terminal soon (ligatures back in xterm.js as of May)

**Comment by nilp0inter** [comment]
I'll do, thank you!

**Comment by nilp0inter** [comment]
Here are the issue reports in case anybody ends here:

- Konsole: https://bugs.kde.org/show_bug.cgi?id=422431
- QTerminal: https://github.com/lxqt/qterminal/issues/684

**Comment by nilp0inter** [comment]
Hi again,

a new piece of information has been added by one of QTerminal developers here: https://github.com/lxqt/qterminal/issues/684#issuecomment-674494932

Both bugs appears to be related to Qt not classifying FiraCode as a monospace font. Maybe some metadata is missing in FiraCode?
