### ISSUE TITLE
Stylistic sets not working in VSCode

### ISSUE THREAD

**Issue by MithicSpirit** [tonsky/FiraCode#1065]
Ever since I updated from v2 or v3 (can't recall) to v4, none of the stylistic sets are working anymore in VSCode (although the font and regular ligatures look fine). The relevant settings currently are:
```json
{
  "editor.fontFamily": "'Fira Code', Hasklig, 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
  "editor.fontLigatures": "'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07' 'zero'"
}
```

**Comment by tonsky** [comment]
maybe that’s because of the missed comma just before 'zero'?

**Comment by MithicSpirit** [comment]
yup, that fixed it... sry lol
