### ISSUE TITLE
Add ligature for /\ and \/

### ISSUE THREAD

**Issue by xmha97** [tonsky/FiraCode#1069]
Hello,
Please add ligature for `/\` and `\/`

**Comment by tonsky** [comment]
Hi! They are already in the font.

**Comment by RubenVerg** [comment]
Isn’t it already there?

________________________________

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/84055117-9dd93580-a9c9-11ea-80b7-6a4c4cfd40b3.png)

OK, Thanks.
I did not enable ligature.
❤
