### ISSUE TITLE
Alternate design for ##, ###, ...?

### ISSUE THREAD

**Issue by coreh** [tonsky/FiraCode#107]
Right now a sequence like `##` is rendered as:

<img width="60" src="https://cloud.githubusercontent.com/assets/418473/12204084/3b184e2a-b619-11e5-803d-5cbe959424dd.png">

While technically correct (since it's essentially two `#` characters joined by the horizontal bars), on a quick glance it looks like there are three `#` signs, instead of two, because an extra `#` is visible in the middle.

I'd like to propose that the following alternative design be used for the `##` sequence, with a joined vertical/diagonal bar in the middle:

<img width="60" src="https://cloud.githubusercontent.com/assets/418473/12204176/ccd72188-b619-11e5-82d3-4183f93c1e1d.png">

I believe the longer sequences, like `###` and `####` would also greatly benefit from this design change, since right now (IMO) it's really hard to make up the number of `#` symbols on them at a glance:

<img width="122" src="https://cloud.githubusercontent.com/assets/418473/12204300/81ba59ee-b61a-11e5-96a8-7a3f8aead66c.png">

Thoughts?

**Edit:** For reference, here's what their rendering would look like:

<img width="122" src="https://cloud.githubusercontent.com/assets/418473/12204444/66f5d704-b61b-11e5-9f65-7d2a8fe8e9fc.png">

_(I understand some adjustments need to be done to accommodate for the width, these are just crude mock ups)_

**Comment by MadcapJake** [comment]
:+1:  Definitely more readable!

**Comment by tonsky** [comment]
Actually, quite a nice idea. I’ll try to include it to the next build

**Comment by vyp** [comment]
It's good because you can just "count the number of boxes" to determine the number of hash characters.

**Comment by coreh** [comment]
Thanks for considering this :smile:
