### ISSUE TITLE
Add the Creative Commons license characters

### ISSUE THREAD

**Issue by Tazshelby2016** [tonsky/FiraCode#1070]
In Unicode 13.0, Unicode defined many of Creative Commons licensing symbols as the following characters:
- U0229C
- U1F10D
- U1F10E
- U1F10F
- U1F16D
- U1F16E
- U1F16F

Currently, few non-specialty fonts support all these characters, meaning that one still cannot use them when mentioning their work or verify that an OS can even support them.

**Comment by tonsky** [comment]
Thanks! I’ll look into it.

<img width="559" alt="Screenshot 2020-06-08 at 23 48 10" src="https://user-images.githubusercontent.com/285292/84083758-8c505780-a9e2-11ea-8208-2173b594c379.png">

https://www.unicode.org/charts/PDF/Unicode-13.0/U130-1F100.pdf

<img width="705" alt="Screenshot 2020-06-08 at 23 53 26" src="https://user-images.githubusercontent.com/285292/84084185-43e56980-a9e3-11ea-9ecf-fc29e3bda09e.png">

https://www.compart.com/en/unicode/U+229C

**Comment by RubenVerg** [comment]
I don’t think M is a license

________________________________

**Comment by wopian** [comment]
24C2 is a regular circled M

https://www.compart.com/en/unicode/U+24C2

Unicode 13 added 1F1AD that is also a circled M, but is the symbol for Mask Work (intellectual property protection for integrated circuit layouts)

https://en.wikipedia.org/wiki/Integrated_circuit_layout_design_protection

**Comment by RubenVerg** [comment]
Oh that’s interesting

________________________________

**Comment by Tazshelby2016** [comment]
The first image uses a delta chart for version 13, not the standard chart. Delta charts show changes between versions of Unicode. A yellow highlighted background on a code slot means a new character.
