### ISSUE TITLE
All icons are showing except for folders

### ISSUE THREAD

**Issue by dataexcess** [tonsky/FiraCode#1071]
Hello,

I am pimping my Terminal (Hyper) by following this tutorial https://medium.com/better-programming/5-steps-to-a-beautiful-terminal-that-youll-love-using-9e94ecb4191b

After downloading and installing the FIra Code font (by following this tutorial: https://tjay.dev/howto-my-terminal-shell-setup-hyper-js-zsh-starship/)

everything is looking the same as in the first tutorial except for folders and files... 
So I see the git-branch icon, the version number box, even npm version icon.
But when I do 'ls' all the folder and file icons are just squares.

Can anybody help me? Thank you.

Running macOS Catalina, Hyper, ZSH, Starship.

**Comment by tonsky** [comment]
The first tutorial clearly states you need FuraCode Nerd Font. I suspect that’s because that font has all those icons built in. Fira Code does not have them, as they are not standard in any way.

**Comment by dataexcess** [comment]
@tonsky Ok I had to restart my computer for the Fura Font code to be propperly installed somehow. It is working now! Thank you.
