### ISSUE TITLE
Add /= (not equal in Elm & Haskell)

### ISSUE THREAD

**Issue by emilyaviva** [tonsky/FiraCode#1072]
Elm and Haskell use the sequence `/=` for inequality; it would be nice if this resolved to the same `≠` ligature as `!=` does in other languages.

**Comment by mfocko** [comment]
Could represent short-hand operator too...
`a /= b` ~ `a = a / b`

**Comment by tonsky** [comment]
Yes. Tracked in #125. Will make a stylistic set for it. Thanks!
