### ISSUE TITLE
FiraCode 5.1 looks broken at 11pt

### ISSUE THREAD

**Issue by CheloXL** [tonsky/FiraCode#1075]
I just updated to 5.1. Using the "Retina" variant, at 11px (in Visual Studio), I'm getting the following:

![image](https://user-images.githubusercontent.com/201414/84325782-ee7b9a80-ab51-11ea-827b-78984ac79e91.png)

This doesn't happens on 5.

**Comment by tigerinus** [comment]
Also looks broken at 9pt under Windows Terminal:

![image](https://user-images.githubusercontent.com/7172560/84352194-76fc4880-abef-11ea-8672-6cba59893e10.png)
![image](https://user-images.githubusercontent.com/7172560/84352220-85e2fb00-abef-11ea-9ada-f993c9f6fcca.png)

**Comment by RubenVerg** [comment]
I’m starting to feel all those problems are because I requested two- and three- em dashes :worried:

**Comment by tonsky** [comment]
@CheloXL @tigerinus can you try this build? Does it make things better?
[Fira_Code_v5.1.glyphs.zip](https://github.com/tonsky/FiraCode/files/4765240/Fira_Code_v5.1.glyphs.zip)

**Comment by tonsky** [comment]
And this one too please. These are just the different ways to export the same source. They all look identical on Mac, but apparently on Windows one way is better than the other. Thanks!

[Fira_Code_v5.1.no_compat.zip](https://github.com/tonsky/FiraCode/files/4765257/Fira_Code_v5.1.no_compat.zip)

**Comment by CheloXL** [comment]
@tonsky **Glyphs** looks great, **no_compat** looks worst than the original 5.1

**Comment by tonsky** [comment]
I did my own bit of testing. no_compat renders `m` too low, for some reason:

![Annotation 2020-06-11 165259](https://user-images.githubusercontent.com/285292/84404479-27c21200-ac07-11ea-98c1-a2091347eaec.png)

Glyphs is mostly fine, but `//=//` got butchered:

![Annotation 2020-06-11 165554](https://user-images.githubusercontent.com/285292/84404532-3c9ea580-ac07-11ea-96de-3f4e5137d42f.png)

@CheloXL can you provide a screenshot how no_compat looks for you? Just curious.

I think I’ll wait for @tigerinus to respond, but most likely I’ll stick with Glyphs from now on.

**Comment by CheloXL** [comment]
@tonsky Here you have:
![image](https://user-images.githubusercontent.com/201414/84408846-064f2f00-abe3-11ea-9b73-ce45e94d6fc4.png)
Also, on MY machine on VS, //=// shows just fine.

**Comment by tigerinus** [comment]
with `no_compat` fonts, the problem seems to be better but not completely gone:

![image](https://user-images.githubusercontent.com/7172560/84460297-27c02180-ac9c-11ea-8902-1bc84840e452.png)
![image](https://user-images.githubusercontent.com/7172560/84460324-3a3a5b00-ac9c-11ea-93b9-c59fd03d2ff0.png)

with 'glyphs' fonts, the problem is completely gone:

![image](https://user-images.githubusercontent.com/7172560/84460404-69e96300-ac9c-11ea-9519-5e11d90ee20f.png)
![image](https://user-images.githubusercontent.com/7172560/84460412-71107100-ac9c-11ea-8768-bc28ff009037.png)

**Comment by tonsky** [comment]
Ok thanks, I’ll stick with the Glyphs export from now on. Sorry for the hiccup
