### ISSUE TITLE
Fix install instruction

### ISSUE THREAD

**Issue by MDHD-Yee** [tonsky/FiraCode#1077]
https://github.com/tonsky/FiraCode/wiki/Installing

> Use chocolatey: `choco install firacode-ttf`

`firacode-ttf` is [deprecated](https://chocolatey.org/packages/FiraCode-ttf).

Change to `choco install firacode`

**Comment by tonsky** [comment]
Thank you!

**Comment by dboyaca** [comment]
Ty. After two days trying the first option
