### ISSUE TITLE
Suboptimal ligature in `ls` output

### ISSUE THREAD

**Issue by miniBill** [tonsky/FiraCode#1079]
Example output from `ls`:
```
drwx------ 60 ...
```

## What did I expect?
Either the `-`s are all ligated or none are

## What happens
The last 5 `-`s have a ligature, the first hasn't.

## How bad is it?
🤷‍♂️ could be worse, doesn't impact readability nor makes the text ambiguous

**Comment by tonsky** [comment]
Was fixed in v5. You must be having an old version

**Comment by miniBill** [comment]
Yupp, I realized I still had v4 on the second account
