### ISSUE TITLE
Some powerline symbols broken

### ISSUE THREAD

**Issue by MithicSpirit** [tonsky/FiraCode#1084]
Not really sure what their unicode number is but here is a list of some of them:
```
 - round separator (right)
 - round separator (left)
 - slanted edge (right)
 - slanted edge (left)
 - rounded edge (right)
 - rounded edge (right)
```

Here's how they look in fira code:
![image](https://user-images.githubusercontent.com/24192522/84685684-ad480980-af08-11ea-92ca-2dcc8af889ae.png)

Here's how they look in another powerline font ([MesloLGS NF](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k)):
![image](https://user-images.githubusercontent.com/24192522/84685989-20ea1680-af09-11ea-93b8-6d2f46a6c8b5.png)

There might be more broken symbols but these are the only ones I found in [powerlevel10k](https://github.com/romkatv/powerlevel10k).

**Comment by RubenVerg** [comment]
They only appear in NF (Nerd Fonts) They are not powerline symbols, they are Powerline _extra_ symbols. https://github.com/ryanoasis/powerline-extra-symbols

**Comment by MithicSpirit** [comment]
Ah ok. Sorry

**Comment by tonsky** [comment]
Hi @MithicSpirit, thanks for the suggestion. The symbols are in private use area (non-standard) and do not look like very well thought-out or widespread. I think it’s better if those live in patched fonts.
