### ISSUE TITLE
add ligature for `-

### ISSUE THREAD

**Issue by CozyPenguin** [tonsky/FiraCode#1087]
htop uses `- to display trees, I think it would be nice to make it connect.

**Comment by tonsky** [comment]
I think there’s also a proper box-drawing mode?

![tree-view-htop-command](https://user-images.githubusercontent.com/285292/85030072-4e3efa80-b17d-11ea-8b00-7444b9b6c058.png)

**Comment by wopian** [comment]
This would conflict with template strings / formatted string literals in several languages  that use `` as strings.
