### ISSUE TITLE
Instructions to install on WSL2 in Windows10

### ISSUE THREAD

**Issue by stuartdd** [tonsky/FiraCode#1088]
Hi

This is briliant..

Are there installation instructions to use FiraCode in Windows10 and WSL2. 

I am a little vague, do I install the Windows version or the Linux version or both! 

I would really like to use Starship cross platform prompt in a WSL2 shell and it requires a Powerline font. It reccomends FiraCode.

https://www.linuxuprising.com/2019/09/starship-is-minimal-and-fast-shell.html

I would like to get the bash shell to use the new font.

I would like to get VSCode to use the font for local code editing and remote.

**Comment by wopian** [comment]
You need to download and set the font in Windows.

For VSCode, set the font family and integrated terminal font family to "Fira Code".

**Comment by stuartdd** [comment]
Thanks I will give it a try.
