### ISSUE TITLE
<- and -> ligature only works with reserverd keyword in golang

### ISSUE THREAD

**Issue by numToStr** [tonsky/FiraCode#1089]
Hi @tonsky, thank you for making this lovely font.

I am doing some golang lately and found this annoying when <- and -> doesn't work. It only works with the reserved keywords in golang.

Actual code screenshot:
- Working
![Screenshot_20200620_163106](https://user-images.githubusercontent.com/24727447/85200293-d48d4500-b313-11ea-913f-008fa5daf26e.png)

- Not working
![Screenshot_20200620_163225](https://user-images.githubusercontent.com/24727447/85200288-cfc89100-b313-11ea-9cba-8145263c8f1e.png)

More example:
![Screenshot_20200620_163738](https://user-images.githubusercontent.com/24727447/85200362-67c67a80-b314-11ea-8ff8-18536acbd798.png)

**Comment by j-f1** [comment]
Do you have the latest version installed? I think this issue was fixed in a recent update.

**Comment by numToStr** [comment]
I have v4. I guess my OS packages are not updated.

**Comment by tonsky** [comment]
If it works sometimes, that means that editor it tokenizing `<-` wrong. Most probably syntax highlighting identifies `<` and `-` in some cases. You should report it to the syntax highlighter author or the editor author.

**Comment by numToStr** [comment]
This issue is also present in the vim. I don't know if the issue is in the editor. But, anyway thanks for letting me know.
