### ISSUE TITLE
Add support for U+2245 (≅) and U+2243 (≃)

### ISSUE THREAD

**Issue by JakobBruenker** [tonsky/FiraCode#1090]
These two characters are sometimes used to represent isomorphisms (for an example, see <https://plfa.github.io/Isomorphism/#isomorphism>), and AFAICT aren't currently part of Fira Code.

(They're wider in my terminal than regular characters - I believe that means it's using a fallback font?)

**Comment by tonsky** [comment]
I’ll look into it, thanks!
