### ISSUE TITLE
What about ligatures for multiplication and division?

### ISSUE THREAD

**Issue by djalbat** [tonsky/FiraCode#1092]
It's difficult to think of combinations, however. The best I can think of are:

```
./.  `/.
```
The first for division `÷`, the second for multiplication `×`.

I don't mind the first, I think it's acceptable. Not sure about the second!

The logical operators `/\` and `\/` are great, by the way. Many thanks!

**Comment by tonsky** [comment]
I think this is backwards. Fira Code improves presentation for existing languages, with already existing combination. If you just need multiplication/division in text, insert unicode ones: × ÷

**Comment by jecs-imperial** [comment]
Okay, no problem.
