### ISSUE TITLE
Installation notes for Archlinux

### ISSUE THREAD

**Issue by alcohol** [tonsky/FiraCode#1093]
Readme says a package exists (which indeed used to be true), but this no longer seems to be the case :disappointed: 
Unclear why the package no longer exists though.

https://www.archlinux.org/packages/community/any/otf-fira-code/

**Comment by alcohol** [comment]
Actually, I guess that is because of #939

Readme should just be updated :-)

**Comment by alcohol** [comment]
Strange, I downloaded the zip for 5.2 but the readme did not contain this change:

https://github.com/tonsky/FiraCode/commit/66ce8c3c571c086d397426e65a9ba7320ab585c6

**Comment by tonsky** [comment]
Thanks for reporting! That’s unfortunate. Will be fixed in the next version.
