### ISSUE TITLE
Vertical ligatures?

### ISSUE THREAD

**Issue by sataset** [tonsky/FiraCode#1094]
Vertical ligatures? 🤔🤔🤔

It is hard to see, but bottom brackets got disconnected after adding a new line. Is that some kind of a vertical ligature feature (I have not encountered them before) or that is a bug?

- version: FiraCode 5
- IDE: VSCode

![connected](https://user-images.githubusercontent.com/28687456/85545445-3e5f6480-b61c-11ea-842d-ed0123d1ca8a.jpg)
![disconnected](https://user-images.githubusercontent.com/28687456/85545447-3f909180-b61c-11ea-8995-8e0c6278e626.jpg)

More examples:
```
⎧ ⎡ ⎧ ⎤ |
⎨ | | | |
⎩ ⎣ ⎩ ⎦ |
```
![image](https://user-images.githubusercontent.com/28687456/85548218-03126500-b61f-11ea-8cd4-0e13d8e9c897.png)

```
⎧ |
| |
⎨ ⎨
| |
⎩ |
```
![image](https://user-images.githubusercontent.com/28687456/85548251-0c9bcd00-b61f-11ea-9a42-b409fa9385e7.png)

**Comment by tonsky** [comment]
What you show is very strange. There’s no vertical ligatures, that’s impossible. Are you on Windows by any chance?

**Comment by sataset** [comment]
> What you show is very strange. There’s no vertical ligatures, that’s impossible. Are you on Windows by any chance?

That what I have been thinking of too. Was not expecting that it is even possible.

Sorry I forgot to mention that in the beginning.

OS: macOS High Sierra 10.13.6

**Comment by sataset** [comment]
I have checked now these configurations with same results:
- Windows (VSCode)
- macOS (Sublime Text 3)

Have you invented a vertical ligatures by mistake? 😅

**Comment by tonsky** [comment]
Font size? Line height?

**Comment by sataset** [comment]
Windows 10 (VSCode)
- `fontSize`: 14
- `lineHeight` : default (19)

I will check it on other OS later and will update this comment.

**Comment by sataset** [comment]
Windows 10 — VSCode
```json
"editor.fontSize": 14,
"editor.lineHeight": 0, // is equal to 19
```

macOS — VScode
```json
"editor.fontSize": 14,
"editor.lineHeight": 0, // is equal to 21
```

macOS — Sublime Text 3
```json
"line_padding_top": 0,
"line_padding_bottom": 0,
```

I do not know why line height differs on different machines (description says that it depends on font size only). Here's more information: 
- Windows machine (1920x1080, 125% scaling)
- macOS machine (2560x1080, no scaling)

**Comment by tonsky** [comment]
You seems to be using U+007C VERTICAL LINE `|`
You should use U+239C LEFT PARENTHESIS EXTENSION `⎜` and U+239F RIGHT PARENTHESIS EXTENSION `⎟`

**Comment by sataset** [comment]
Thank you for all responses. True, my bad.

Actually it looks really good. Though there's a small spacing between them which is normal I suppose because it is not compensated by ligature but height of those symbols?

Is it even possible to implement vertical ligatures?

![image](https://user-images.githubusercontent.com/28687456/85627776-5dd3ad00-b66f-11ea-9206-8f408c60d8c1.png)

**Comment by tonsky** [comment]
It’s not possible. The spacing is because editors round up font height to the closest integer pixel I guess
