### ISSUE TITLE
When ligatures are enabled in VSCode, spaces are too small

### ISSUE THREAD

**Issue by NickHeiner** [tonsky/FiraCode#1095]
I'm not sure if this is a VSCode problem or a FiraCode issue, but I thought I'd start here.

![image](https://user-images.githubusercontent.com/829827/85642970-ba22d680-b647-11ea-8783-de582d09d2b6.png)

I'm using FiraCode 5.2.

VSCode version info:

```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (1 wk ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

If I use the `FiraCode Nerd Font Mono`, which I got from [Nerd Fonts](https://www.nerdfonts.com/), then I don't have this problem.

**Comment by tonsky** [comment]
<img width="301" alt="Screenshot 2020-06-25 at 15 49 06" src="https://user-images.githubusercontent.com/285292/85732137-6a9de280-b6fb-11ea-8dfb-6babd263e2d2.png">

probably something with extensions, or vs code itself. I can’t reproduce

**Comment by NickHeiner** [comment]
Hmm, now I can't repro either. Bizarre.
