### ISSUE TITLE
Official auto update utility

### ISSUE THREAD

**Issue by yedhrab** [tonsky/FiraCode#1098]
Can can you make simple auto update tool to install updated fonts

**Comment by tonsky** [comment]
What platform are you on? How did you installed them in the first place?

**Comment by yedhrab** [comment]
Platform: Windows 10
Installed via: GitHub Releases

**Comment by tonsky** [comment]
On this wiki page: https://github.com/tonsky/FiraCode/wiki/Installing#windows there are two Windows package managers. They should be able to update fonts for you

**Comment by yedhrab** [comment]
Thank you, and sorry for it :)

**Comment by tonsky** [comment]
No worries, hope this help!
