### ISSUE TITLE
rendering of `!!!!!!`

### ISSUE THREAD

**Issue by xcambar** [tonsky/FiraCode#110]
Rendering `!!!!!!` (6 exclamation marks with no space) renders as follows:

<img width="59" alt="screen shot 2016-01-13 at 15 16 46" src="https://cloud.githubusercontent.com/assets/657654/12296572/d2c40fdc-ba08-11e5-9c73-a170a53f06ad.png">

There's a clear impression of two groups of 3 spaces, when it's one group of 6.

Note that this effect works for any group of exclamation marks > 3 characters.

**Comment by MadcapJake** [comment]
There's only a ligature for three exclamation marks.

**Comment by tonsky** [comment]
i'll address that in next version

**Comment by federicobond** [comment]
This group by 3 behavior is also present in dashes.

The case of equals signs, commonly used to underline Markdown headings is actually worse, because 3 consecutive equals turn into a symbol with 3 horizontal lines instead of two.

<img width="326" alt="captura de pantalla 2016-03-03 a las 3 40 39 p m" src="https://cloud.githubusercontent.com/assets/138426/13505420/dc17358e-e157-11e5-9f6f-5fab3e695885.png">

**Comment by curio77** [comment]
Long sequences of slashes (“///////////////////…”, used by some as visual delimiters in source code) also get rendered as groups of three, not sure if anything can be done about this?

**Comment by tonsky** [comment]
Yes, I can block sequences longer than 3 slashes or exclamations marks from
forming a ligature altogether. I’m planning this for the next version.

**Comment by curio77** [comment]
That's great! And I very much enjoy working with Fira Code within both Atom and Android Studio/IntelliJ IDEA, so many thanks for it! :-)

**Comment by stephencelis** [comment]
Please do the same for `...`! A lot of test runners use dots to denote passing test cases.

**Comment by engelfrost** [comment]
I think this behavior is wanted for all sequences of identical characters.

**Comment by Kovensky** [comment]
Indeed. Sequences of `w` are another fun case:
![](http://puu.sh/nJC4i/88c8ea87f7.png)

Though one might question my decision of using Fira Code as an IRC font.
