### ISSUE TITLE
Spacing issues with TMUX and Vim

### ISSUE THREAD

**Issue by reisnobre** [tonsky/FiraCode#1101]
Hi, I used to use this font when I coded with Atom when I switched to vim I noticed a small problem as shown below.

![Screen Shot 2020-07-19 at 13 03 15](https://user-images.githubusercontent.com/12832066/87879306-36e36f00-c9c0-11ea-9df1-0d4bbd84ee19.png)

There's some type of spacing issue only while using your font. Can you guys give me some help?

**Comment by wopian** [comment]
Possibly https://github.com/macvim-dev/macvim/issues/977
