### ISSUE TITLE
.- ligature looks strange in the middle of words

### ISSUE THREAD

**Issue by michaelkuhn** [tonsky/FiraCode#1103]
In German, we really like hyphenated words. They sometimes also contain periods because they contain abbreviations or numbers, which looks strange (see attached screenshot taken with Fira Code 5.2).

Would it make sense to only enable the .- ligature if it is surrounded by whitespace?

![Bildschirmfoto von 2020-07-26 22-38-28](https://user-images.githubusercontent.com/4062614/88488911-03d94680-cf91-11ea-934c-a342f636b395.png)

**Comment by tonsky** [comment]
Space won’t work, but it was originally intended for Clojure. Maybe it’s not worth keeping—looks strange anyways

**Comment by tomyun** [comment]
FYI, it also kinda conflicts with Julia where `.-` indicates minus operator with [syntactic loop fusion](https://julialang.org/blog/2017/01/moredots/).

**Comment by clason** [comment]
I don't know how much work this is, but would it be a compromise to turn this ligature into a stylistic set? (Since, at least anecdotally, it seems to be annoying in more situations than it is useful, it's probably better disabled by default, but either choice would be a strict improvement.)

**Comment by RubenVerg** [comment]
In scala, there are no operators. All "operators" are just functions that use inline operator syntax, so `a.fn(b)` becomes `a fn b`. `3 - 3` can be written as `3.-(3)`. If the ligature applies, and it becomes `3·-(3)`, it's hard to read.

**Comment by pjentsch0** [comment]
FWIW I like it in Julia

**Comment by clason** [comment]
@pjentsch0 Really? Doesn't it bug you that it's only for `.-`, so `a .= α.*b .+ c .- d` is not consistent?

(What would be perfect would be a stylistic set that aligned `.` + 'operator' consistently, but how would you choose which operators to include?)

**Comment by pjentsch0** [comment]
@clason It does, and I agree that a set is better, but I'd prefer to only have a ligature for `.-` than no ligatures.

Could we not align `.` and `+-=/` ? Of course you can broadcast almost anything in Julia, but I think that covers a lot of the common use cases.  Usually I use the `@.` macro for long broadcast chains. 

I'm not sure what a stylistic set is, I assume it's like a set of ligatures that can be enabled/disabled?

**Comment by clason** [comment]
> @clason It does, and I agree that a set is better, but I'd prefer to only have a ligature for .- than no ligatures.

Interesting.

> Could we not align . and +-=/ ?

That would be a reasonable default, yes, but I'd add `*`.

>  Usually I use the @. macro for long broadcast chains.

That works (unless there are enough operations that are _not_ supposed to be broadcasted (but that is getting beside the point here).

> I'm not sure what a stylistic set is, I assume it's like a set of ligatures that can be enabled/disabled?

https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

**Comment by pjentsch0** [comment]
> That would be a reasonable default, yes, but I'd add `*`.
Definitely, I forgot that one.

> 
> https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets
cool, thanks

**Comment by eins78** [comment]
Another (real-world) example: `MwSt.-Nr.`
<img width="114" alt="Screenshot 2020-09-16 at 21 46 20" src="https://user-images.githubusercontent.com/134942/93385134-16238280-f866-11ea-94d3-ee5187c9f940.png">

**Comment by tonsky** [comment]
Will be disabled in v6 by default. Linked: #860
