### ISSUE TITLE
Context-aware punctuation and fine-tuned letter pairs working inconsistently

### ISSUE THREAD

**Issue by NanoExplorer** [tonsky/FiraCode#1106]
Hello! I have been using Fira Code for a while now, and it's really cool! 
I recently installed it on a new computer and was looking at the Readme here. I had never noticed the fine-tuned letter pairs or context-aware punctuation, but thought it was a really cool idea, so I thought I'd test it out. 

I use Fira code in Firefox (Jupyter notebook) and Sublime text. First I tried it out in firefox, and the fine-tuned letter pairs worked! It looks good. But the context-aware punctuation doesn't seem to work (except `:`, which actually does work). Firefox is listed as supported, so maybe this is just a settings issue on my end?

Sublime text doesn't render either the punctuation or the letter pairs. Again, it's listed as supported, and I followed the instructions in the wiki for setting it up correctly. Maybe I missed a step? Any help would be appreciated.

All the other features I've tested work in both editors, such as `==`, etc.

Here is a screenshot with firefox on the left and Sublime text on the right:
![Screenshot 2020-07-29 17 16 08](https://user-images.githubusercontent.com/4166159/88854619-8cd5c500-d1bf-11ea-80f2-17ec97b5be70.png)

These behaviors are consistent on both my Windows system and my Linux system.

**Comment by RubenVerg** [comment]
As a Sublime features, ligatures only work with a subset of symbols. Letters aren’t part of that.


Ruben Vergani
rubenverg.com
(◠–◠)
Sent with Mail for Windows 10

**Comment by tonsky** [comment]
Some editors or web pages might do syntax highlighting that breaks context-aware features. E.g. if plus sign between two numbers is highlighted in a different color, the plus will be rendered separately, with no way to know about its surroundings. In that case context-aware features do not kick in.

Sublime only supports a limited set of features and ligatures, mostly not involving letters. See also this comment https://github.com/tonsky/FiraCode/issues/1096#issuecomment-653285052
