### ISSUE TITLE
Abnormal behaviour in some apps

### ISSUE THREAD

**Issue by aystic** [tonsky/FiraCode#1107]
I am currently running windows 10 64 bit, The font is behaving strangely in android studio version 4 and also in the menu bars of scilab all versions. Please have a look.
![2020-08-01 23_30_58-Android Studio Setup Wizard](https://user-images.githubusercontent.com/54324845/89107598-cae91800-d44f-11ea-9965-3753975667ab.png)

**Comment by tonsky** [comment]
Try this https://github.com/tonsky/FiraCode/wiki/Troubleshooting#corrupted-font-in-intellij-on-windows
