### ISSUE TITLE
Doesn't show FireCode style in Rstudio  1.2.5042 

### ISSUE THREAD

**Issue by barja8** [tonsky/FiraCode#1109]
Hi everyone ! 
These day, I have been using the  **FireCode style** in my routing of  scripting , However, from the update, my  system operative to Ubuntu 20.04 doesn't show it in rstudio 1.2.5042 with R 4.0.2. 
Here, I described the steps that I followed  to change the style in Rstudio.
I hope someone can help me :crying_cat_face: 
Thanks!
```
sudo apt update
sudo apt install fonts-firacode
```

![p1](https://user-images.githubusercontent.com/23284899/89139915-d565e900-d505-11ea-96d2-ac41e2cf8215.png)
![p2](https://user-images.githubusercontent.com/23284899/89139922-d9920680-d505-11ea-97f7-a662fe761fc9.png)

**Comment by tonsky** [comment]
Have you restarted it after install? Have you tried restarting your machine maybe?

**Comment by barja8** [comment]
Hi @tonsky , I appreciate your time in answer me, well I have been trying restarted my laptop, but the error continue show me.
I don't know if is  my version of Rstudio o perhaps my last release of ubuntu 20.04.

**Comment by wilfredom** [comment]
I also have this issue, on Manjaro 20.1 and latest versions of everything (R, RStudio, ttf-fira-code) in the Official repos. Looking at the font configuration, this is where the font is installed:

`/home/wilfredo/.cache/.fr-PjBVQj/FiraCode-master/distr/ttf/FiraCode-Regular.ttf`

**Comment by tonsky** [comment]
Fira Code is double-width right now, which might cause the incompatibility with RStudio. If you are willing to wait until v6, it should be strict monospace and might improve your situation

**Comment by wilfredom** [comment]
Thanks, Nikita. I think I was also having this issue with one of the
terminal emulators; I can see how that could be causing both.

Is there an ETA for v6?

**Comment by tonsky** [comment]
Hope to get something out in September

**Comment by wilfredom** [comment]
Amazing—thanks so much!

**Comment by tonsky** [comment]
@barja8 I’d appreciate if you can test this build https://github.com/tonsky/FiraCode/issues/1073#issuecomment-705525033

**Comment by barja8** [comment]
@tonsky  thanks a lot for trust, now is avaliable for Rstudio in Ubuntu 20.04, here steps 👇 :nerd_face: 

* [Fira_Code_v6](https://github.com/tonsky/FiraCode/files/5347630/Fira_Code_v6.zip)
*  `sudo rm -rf /usr/share/fonts-firacode/`
*  `sudo cp *.ttf /usr/share/fonts/truetype/`
* `fc-cache`
* `fc-list -v "Fira Code" | grep spacing`

![Captura de pantalla de 2020-10-11 00-47-38](https://user-images.githubusercontent.com/23284899/95671339-689d4980-0b5b-11eb-9290-a5922ab18e2b.png)

**Comment by tonsky** [comment]
Great, thanks! Hope when v6 comes out it’ll stay this way
