### ISSUE TITLE
Question: How are the features/*.fea files included?

### ISSUE THREAD

**Issue by coolbluewater** [tonsky/FiraCode#1110]
How do the files in the features/ subdirectory get included into the main FiraCode.glyphs file? There is no include statement in the latter. Also, the code for all features seems to be directly incorporated in the glyphs file.

I'm new to the Glyphs app, sorry if this is a n00b question :)

**Comment by tonsky** [comment]
This is what my Clojure code does. It just reads all the features and writes them into glyphs file. Calt feature is generated by the same code.

**Comment by tonsky** [comment]
This https://github.com/tonsky/FiraCode/tree/master/clojure/fira_code

**Comment by coolbluewater** [comment]
Thanks - how is this code invoked? I'm using the build steps listed in README, and script/build does not appear to call the clojure code.

**Comment by tonsky** [comment]
That is true, I invoke it manually, because it requires me to close/open file in Glyphs before/after that. Use this command:

```
./script/update_glyphs
```

You will need clojure installed:

```
brew install clojure
```
