### ISSUE TITLE
Center consecutive equals signs (U+2A75/6)

### ISSUE THREAD

**Issue by tomyun** [tonsky/FiraCode#1113]
These equals signs do not seem to align in the vertical center.

⩵ : [TWO CONSECUTIVE EQUALS SIGNS](https://www.fileformat.info/info/unicode/char/2a75/index.htm)
⩶ : [THREE CONSECUTIVE EQUALS SIGNS](https://www.fileformat.info/info/unicode/char/2a76/index.htm)

Here is an image of `⩵ ⩶ = == ===` rendered together:

<img width="127" alt="Screen Shot 2020-08-19 at 4 18 08 PM" src="https://user-images.githubusercontent.com/906626/90699239-9b9c1e80-e237-11ea-8be7-2572c1f4cdb7.png">

EDIT: or maybe they are missing glyphs?

**Comment by tonsky** [comment]
Those are missing, yes. I don’t feel compelled to add those to the font either. Is there any reason why one would prefer to use those instead of just literally two or three equal signs in a row? Unicode can be a strange place sometimes

**Comment by tomyun** [comment]
I agree with you that these are not something that we use often, but there are times you want to have operators looking similar but with distinct semantics.

For example, in symbolic algebra supported by [SymPy.jl](https://github.com/JuliaPy/SymPy.jl), a normal `==` compares two Equation objects returning true/false whereas a unicode `⩵` returns a new Equation object based on equality relation. Inded SymPy.jl makes use of [five special unicode symbols](https://github.com/JuliaPy/SymPy.jl/blob/66d8ebffd473469968034f62f18f321a029c6263/src/numbers.jl#L332) as below:

≪ : [MUCH LESS-THAN](http://www.fileformat.info/info/unicode/char/226A/index.htm) (U+226A)
≦ : [LESS-THAN OVER EQUAL TO](https://www.fileformat.info/info/unicode/char/2266/index.htm) (U+2266)
⩵ : [TWO CONSECUTIVE EQUALS SIGNS](https://www.fileformat.info/info/unicode/char/2a75/index.htm) (U+2A75)
≧ : [GREATER-THAN OVER EQUAL TO](https://www.fileformat.info/info/unicode/char/2267/index.htm) (U+2267)
≫ : [MUCH GREATER-THAN](https://www.fileformat.info/info/unicode/char/226b/index.htm) (U+226B)

Of course, there are many more symbols that supposed to look similar/same as Fire Code ligatures. In my opinion, it'd be nice if Fira Code fill in these missing glyphs as we already have many of them as a form of ligature. If they look identical, it may be confusing sometimes, but as you said, they're not used very often and at least can be distinguished in a text editor when you trying to edit/delete them.

I also think it's a good place to reuse alternative glyphs (ss08) for `==` and `===`.

**Comment by tonsky** [comment]
I think it’s actually a bad thing to have those symbols in the font, for the reason they might be confused with the two equality signs. Sorry

**Comment by wopian** [comment]
I feel they should still have the same vertical alignment as the other maths symbols (and equal signs) for consistency. Just don't join them like the `==` and `===` ligatures.

Right now the different fallback fonts results in wildly different character heights compared to Fira Code:
- Noto Sans is roughly the same but on a lower baseline ![image](https://user-images.githubusercontent.com/3440094/91003171-896c0880-e5c8-11ea-8d80-a8c2bd7f79cd.png)

- The font in the image has much shorter glpyhs and a lower baseline
