### ISSUE TITLE
Add support for ∎ (U+220E END OF PROOF)

### ISSUE THREAD

**Issue by JakobBruenker** [tonsky/FiraCode#1115]
This would fit right in with other mathematical characters like ∴ (U+2234 THEREFORE) and is in certain contexts used in some proof assistants like agda to indicate the end of a proof, see for example [this answer to a stackoverflow question](https://stackoverflow.com/a/47660848).

**Comment by tonsky** [comment]
Yes, if it is actually used, I am happy to add it
