### ISSUE TITLE
❌  emoji seems to not be supported

### ISSUE THREAD

**Issue by lexicalunit** [tonsky/FiraCode#1118]
For some reason the red x from Emoji Version 1.0 seems to render as a `X`. I tried a few other emoji and they all seem to work fine so it's something to do with ❌  specifically I think.

![Screen Shot 2020-09-06 at 12 40 35 PM](https://user-images.githubusercontent.com/1903876/92333934-2bb2d400-f03e-11ea-81d0-eedd58c0bc2d.png)

**Comment by tonsky** [comment]
Most likely a fallback font kicking in. Does it render as X if you change to another font?

**Comment by lexicalunit** [comment]
Yep, that was it!
