### ISSUE TITLE
Unicode-2507 not aligned with other characters

### ISSUE THREAD

**Issue by AItheHuman** [tonsky/FiraCode#1119]
Hi! I like to use this U-2507 (three boxes) as a symbol for a type of note in my knowledge base, but I find that it doesn't align with other characters. I use Fira with Emacs (hlissner/doom-emacs).
![example1](https://user-images.githubusercontent.com/62635784/92340506-7a2c9680-f06f-11ea-8b94-c07ed5be158c.png)

**Comment by wopian** [comment]
What version of Fira Code are you using?

┇is a box drawing character that was added to Fira Code in version 2, it looks like this (2nd line) on version 5.2:

![image](https://user-images.githubusercontent.com/3440094/92341043-6bb49e00-f0b4-11ea-9cec-33e34de13b5e.png)

```
│
┇
@
```

**Comment by AItheHuman** [comment]
Ah! I didn't realize I was using such an old version (1.204). Thanks for clearing that up haha ^^;

**Comment by wopian** [comment]
No problem 😊
