### ISSUE TITLE
fi ligature is enabled and it looks bad

### ISSUE THREAD

**Issue by svipas** [tonsky/FiraCode#1120]
Hi, I'm using latest Fira Code version and VS Code. With enabled ligatures if I type `fi` I see this. I guess it's a bug?

![Screen Shot 2020-09-07 at 14 56 51](https://user-images.githubusercontent.com/10441177/92385404-83bf0880-f11a-11ea-8572-026f35a041e8.png)

Take a look at `final` and `fi`.

**Comment by wopian** [comment]
The stem of the `i` is slightly lower to align with the middle bar of the `f`

![image](https://user-images.githubusercontent.com/3440094/92403016-89bbe600-f128-11ea-9945-cb1f847843e8.png)

**Comment by svipas** [comment]
Oh, so this is intentional. I guess in this case issue could be closed? @tonsky
