### ISSUE TITLE
[Support] Does Fira Code have a stable subset?

### ISSUE THREAD

**Issue by carlsmith** [tonsky/FiraCode#1121]
Many modern programming languages are defined using a subset of ASCII, but use Unicode files, and permit Unicode characters in string literals and comments, and a popular programming language that uses Unicode operators is not unimaginable.

Some Unicode characters (Latin letters with accents, for example) are fairly safe, but many will mess up monospaced text pretty badly. It depends on the font.

If a language existed that generally assumed it was written using Fira Code (though never absolutely required it), just as programming languages generally assume a monospaced font (but never absolutely require it), is there a stable subset of the font's features that could be relied upon long-term?

Ideally, the outcome would be a canonical list of single Unicode characters and multi-character operators (defined using the same character set) that a language (or some other tool) could depend on working correctly long-term.

The canon could be tweaked and bug-fixed, and could be expanded over time, but would strive to always maintain backwards compatibility, especially regarding features that are actually depended on by real projects with active users et cetera.

**Comment by carlsmith** [comment]
To clarify: This doesn't require that the characters are never used in new ligatures. Only that the characters in the set will always render correctly in a monospaced environment, and will always support (at least) the defined set of stable ligatures.

**Comment by clason** [comment]
> a popular programming language that uses Unicode operators is not unimaginable.

Depending on your definition of "popular", this would be https://github.com/JuliaLang/julia. In my experience, single-width Unicode chars are safe, but ambiwidth and composite characters should be avoided (even if the language supports them).

**Comment by RubenVerg** [comment]
Also Scala.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tonsky** [comment]
Unicode coverage almost strictly expands. Seems safe to rely on it. Ligatures, unfortunately, might come and go, because new use-cases and conflicts are discovered all the time. If, for example, a new language will be invented and rise to popularity in the next five years, that has a conflict with the current default ligatures set (e.g. `<=` means arrow instead of less or equal), I might need to remove this ligature

**Comment by carlsmith** [comment]
Thank you for taking the time to explain. Your point about Unicode coverage never really regressing is something I hadn't considered.

I also understand if you don't want to maintain a safe set that would slowly deviate from the main set over time. Cool.

**Comment by mtrimolet** [comment]
> [...] If, for example, a new language will be invented and rise to popularity in the next five years, that has a conflict with the current default ligatures set (e.g. `<=` means arrow instead of less or equal), I might need to remove this ligature

I think this precise time could be near : PureScript makes use of `<=` for the SuperClass pattern.
Is there already a way to tell editor to use cv20, maybe like subsets ?
