### ISSUE TITLE
Can you provide a version of FiraCode without ligatures?

### ISSUE THREAD

**Issue by mahnac** [tonsky/FiraCode#1122]
I am using a MacBook with a Retina display and love the Fira Code Retina font. However, I use Eclipse for programming and I cannot disable the ligatures in Eclipse (There is no option to disable ligatures in Eclipse).

I hope you can help! :D

**Comment by dnedrow** [comment]
Wouldn't this be a better question for the Eclipse team? The whole point of FiraCode is ligatures.

**Comment by tonsky** [comment]
Try Fira Mono. Fira Code was once based on Fira Mono and added ligatures. Now there are couple of bugs fixed and couple of Unicode chars added, but most of the stuff is still exactly as it was in Fira Mono. https://bboxtype.com/typefaces/FiraMono/#!layout=specimen

**Comment by mahnac** [comment]
> Wouldn't this be a better question for the Eclipse team? The whole point of FiraCode is ligatures.

**Comment by mahnac** [comment]
> Try Fira Mono. Fira Code was once based on Fira Mono and added ligatures. Now there are couple of bugs fixed and couple of Unicode chars added, but most of the stuff is still exactly as it was in Fira Mono. https://bboxtype.com/typefaces/FiraMono/#!layout=specimen

I will try out Fira Mono. Thank you for your reply.
