### ISSUE TITLE
why my linux machine doesn't recognize this font as monospace font?

### ISSUE THREAD

**Issue by AtifChy** [tonsky/FiraCode#1123]

**Comment by tonsky** [comment]
Fira Code is double-width right now. If you are willing to wait until v6, it should be strict monospace and might improve your situation

**Comment by alexeyten** [comment]
You could try to _fix_ this in fontsconfig

Put this to `~/.fonts.conf` or `~/.config/fontconfig/conf.d/fira-core.conf`
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="scan">
        <test name="family" compare="eq">
            <string>Fira Code</string>
        </test>
        <edit name="spacing" mode="assign_replace">
            <const>mono</const>
        </edit>
    </match>
</fontconfig>

```

**Comment by tonsky** [comment]
@AtifChy can you please check that this build works for you?

[Fira_Code_v6.zip](https://github.com/tonsky/FiraCode/files/5347630/Fira_Code_v6.zip)

**Comment by tonsky** [comment]
Awesome, thanks!
