### ISSUE TITLE
add git for windows to the incompatibility list

### ISSUE THREAD

**Issue by hackaholic5069** [tonsky/FiraCode#1124]
it doesn't support ligatures as far as i can tell

**Comment by wopian** [comment]
Git for Windows uses MinTTY, which has [partial ligature support](https://github.com/tonsky/FiraCode#terminal-compatibility-list)

Git for Windows with MinTTY 3.2.0:

![image](https://user-images.githubusercontent.com/3440094/93000033-7f7d5b80-f51d-11ea-9d80-decd2fe850fb.png)
