### ISSUE TITLE
Arrow ligatures not preceded by space not working in certain terminals

### ISSUE THREAD

**Issue by colatkinson** [tonsky/FiraCode#1125]
First off, please let me know if I should file a bug with the terminals themselves. I'm filing here only because I saw the same behavior in multiple terminals.

I'm running the `ttf-fira-code` package from Arch Linux, version 5.2-1.

Essentially, in both Kitty and QTerminal, arrow ligatures will only work if they are preceded by a space. However, this behavior is not reproducible in VS Code.

This behavior doesn't affect some other ligatures, such as `***`, or `==`.

Not working in Kitty:

![image](https://user-images.githubusercontent.com/6528368/93169748-c329be00-f6f3-11ea-89a7-6c5ba4b7c955.png)

Not working in QTerminal:

![image](https://user-images.githubusercontent.com/6528368/93169765-cde45300-f6f3-11ea-86c2-a7e8af3e809a.png)

Working in VS Code:

![image](https://user-images.githubusercontent.com/6528368/93169777-d63c8e00-f6f3-11ea-8a81-bcab80a6fb21.png)

A smattering of other ligatures in Kitty, in case it's helpful:

![image](https://user-images.githubusercontent.com/6528368/93169832-fec48800-f6f3-11ea-9259-5f9c01c19dd5.png)

Let me know if there's any other information that would be helpful. And as a side note, awesome work on the font!

**Comment by tonsky** [comment]
Probably because `a-` changes `hyphen` to `hyphel.lc` and that doesn’t trigger a ligature with `>`. This is not supposed to happen because `->` substitution should happen before `a-` (and it does almost everywhere else), but somehow Kitty does it in the wrong order. Would be interesting to get to bottom of it, maybe open issue at Kitty and let’s see what they have to say?

**Comment by colatkinson** [comment]
So embarassingly enough, this appears to have been an instance of PEBKAC.

I seem to have had two packages installed `otf-fira-code==4-1` and `ttf-fira-code==5.2-1`. As I understand it, the former is no longer supported. After uninstalling the OTF variant, everything works as expected.

I'll close this out. Thanks for the help anyway!
