### ISSUE TITLE
Block Characters weird?

### ISSUE THREAD

**Issue by iMplode-nZ** [tonsky/FiraCode#1127]
![image](https://user-images.githubusercontent.com/31631663/93268115-88f70580-f761-11ea-965c-7281bae31d19.png)
I think that there shouldn't be gaps between the block characters.

**Comment by nelson6e65** [comment]
Also, some blocks are wider than other characters:

```
8765432
⣿⣷⣶⣦⣤⣄⣀
```

![imagen](https://user-images.githubusercontent.com/9272498/93281702-3bdf5780-f792-11ea-8b82-10b331da69b7.png)

**Comment by tonsky** [comment]
@iMplode-nZ there should not! But it is impossible to solve at the font level, because editors round up letter width, and this rounding adds a different gap at different font sizes. Nothing I can do about it, unfortunately

**Comment by iMplode-nZ** [comment]
@tonsky this happens to be a webpage, not an editor; it seems that you managed to have the line drawing characters protrude out of the size of the character a bit, could you do that with the block characters as well?

**Comment by tonsky** [comment]
That might not be a good idea because with block character you don’t know from which side they will be connected.
