### ISSUE TITLE
Brew no longer finds the original fira code font

### ISSUE THREAD

**Issue by ephimoff** [tonsky/FiraCode#1129]
I am trying to re-install the font and can't find it:
```
~ brew cask install font-fira-code
Error: Cask 'font-fira-code' is unavailable: No Cask with this name exists. Did you mean “font-fira-code-nerd-font”?
```
When I search for that
```
~ brew search fira  
```
I get this:
```
==> Casks
font-fira-code-nerd-font                font-fira-mono-nerd-font                font-firago
```

Not sure that I want to install something with a different name

**Comment by tonsky** [comment]
Seems to be in place https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-fira-code.rb

Did you `brew tap homebrew/cask-fonts`?

**Comment by ephimoff** [comment]
Yes, I did. I use a Brewfile and this tap is there. 
Just checked and the cask is there 🤷‍♂️
