### ISSUE TITLE
Downwards Arrow with Tip Rightwards 

### ISSUE THREAD

**Issue by ShalokShalom** [tonsky/FiraCode#1131]
![Screenshot_2020-09-29-11-25-41-64](https://user-images.githubusercontent.com/6344099/94540639-f79a8f80-0246-11eb-943f-d6a7a084aae3.jpg)

Does this symbol exist?
Pipes are usually being used in a way, that indicates their usage as such. 

```
let expectString expectedString =
    expectedString
    |> stringToCharList
    |> List.map expectChar
    |> sequenceParsers
    |> mapParser charListAsString
```
Instead of |>, does the community of a new language think about using |_ or something similar and doing that with the intention to use your font, with a downwards arrow, that directs with the tip to the right 👉

**Comment by tonsky** [comment]
Yes it’s in the font already

<img width="518" alt="Screenshot 2020-09-29 at 12 53 51" src="https://user-images.githubusercontent.com/285292/94549658-d93a9100-0252-11eb-8cf2-ad53b4438240.png">

**Comment by ShalokShalom** [comment]
And how do I call it? Which combination of characters is it?
The |_ I mentioned?

**Comment by tonsky** [comment]
No, just the unicode codepoint U+21B3

**Comment by ShalokShalom** [comment]
Yeah, I am asking for such a character combination
The unicode screenshot is just for you, so that you know what I mean.

**Comment by tonsky** [comment]
Ah, no, I don’t want to add ligature that is not widely used already
