### ISSUE TITLE
Unicode Asterisk (∗)

### ISSUE THREAD

**Issue by bordaigorl** [tonsky/FiraCode#1134]
Would be cool to have the unicode asterisk operator ∗ (U+2217) handled with the same nuance as the normal * symbol.
In particular, the same ligatures should be supported (e.g. `-∗` and `=∗`).
It is for example used in maths for some operators, for example for the separating conjunction in separation logics, where the normal asterisk is reserved for normal multiplication.

**Comment by tonsky** [comment]
Should it look distinguishably different?

**Comment by bordaigorl** [comment]
In the other fonts that support it normal asterisk is pentagonal, while the asterisk operator is exagonal. I think that would be a good way to keep them distinct but blend with the ligatures in a similar way

**Comment by tonsky** [comment]
Ok, about ligatures. Currently `*` has those: `**` `***` `/*` `*/` `<*` `*>` `<*>`. Seems like none of those are related to the math usage you are talking about? `-∗` and `=∗` are not supported at the moment, where might those occur?

**Comment by RubenVerg** [comment]
Pretty sure they're talking about height variations

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tonsky** [comment]
Will be in v6 as `cv16`

**Comment by bordaigorl** [comment]
> -∗ and =∗ are not supported at the moment, where might those occur?

maybe I got it wrong by saying "ligatures", I just care that the asterisk looks vertically centered with - or =.
The `-*` is called "magic wand" in separation logics and is similar to "lollipop" `-o` in linear logic.
The variations with `=` and the symmetric `*-` and `*-*` are for derived connectives.

**Comment by tonsky** [comment]
Ok I see. Will be handled in #655
