### ISSUE TITLE
Wrong symbols

### ISSUE THREAD

**Issue by Windslab** [tonsky/FiraCode#1135]
![image](https://user-images.githubusercontent.com/60715874/95666006-32ad9480-0b5e-11eb-8840-0dce245fa18c.png)

Could please you tell where I douing wrong? I have only Fira Code.

.Xresources
```
URxvt.font:           xft:Fira Code Retina:size=13
URxvt.boldFont:       xft:Fira Code Bold:size=13
URxvt.italicFont:     xft:Fira Code Retina:size=13
URxvt.boldItalicFont: xft:Fira Code Bold:size=13
```

**Comment by tonsky** [comment]
Seems like Fira Code? I don’t see what’s wrong

**Comment by alexeyten** [comment]
I guess that author means blank boxes on left and right. Probably there should be other symbols but it’s hard to guess without real string and/or screenshot with “proper” glyphs

**Comment by Windslab** [comment]
@alexeyten Yes. That's oh-my-zsh shell.

**Comment by tonsky** [comment]
What used to be there? Can you send a screenshot of it working with another font? Also copy-paste the whole string from terminal so I can have a chance to figure out which unicode characters did you use

**Comment by Windslab** [comment]
@tonsky For example this one symbols have no in terminal: ☕ and this ❄️

**Comment by tonsky** [comment]
Yes, you need a separate font emoji, just like with any other font. No font includes emoji as far as I know, everyone relies on a system fallback.

**Comment by Windslab** [comment]
@tonsky Unfotunally is not working:

```
URxvt.font:           xft:Fira Code Retina:size=13,xft:Noto Color Emoji
URxvt.boldFont:       xft:Fira Code Bold:size=13,xft:Noto Color Emoji
URxvt.italicFont:     xft:Fira Code Retina:size=13,xft:Noto Color Emoji
URxvt.boldItalicFont: xft:Fira Code Bold:size=13,xft:Noto Color Emoji
```
Emoji:
https://github.com/sethfl/linux-apple-emojis

**Comment by alexeyten** [comment]
Urxvt terminal doesn’t support emoji
https://www.reddit.com/r/archlinux/comments/9u681d/how_to_use_emoji_fonts_with_urxvtunicode/

**Comment by Windslab** [comment]
Not good :(
