### ISSUE TITLE
Qt has problems with dual spaced fonts

### ISSUE THREAD

**Issue by erazor-de** [tonsky/FiraCode#1138]
Hello,

Fira Code is one of few programming ligature fonts that has font spacing "dual" defined instead of "mono" (Iosevka being the only other one known to me). QFontDialog of the Qt framework does not support such fonts when only monospaced fonts are allowed for selection: [Bug report](https://bugreports.qt.io/browse/QTBUG-67612).

I'm sure there's a reason this font is defined as "dual" and wouldn't want it to be changed forcibly to "mono" then, would instead a monospaced variant be feasible to use Fira Code in such cases?

At the moment I use the reasonably similar Hasklig font as alternative.

**Comment by wopian** [comment]
Should be fixed in the upcoming v6 release.

See https://github.com/tonsky/FiraCode/issues/1073, https://github.com/tonsky/FiraCode/issues/1109, https://github.com/tonsky/FiraCode/issues/1000
