### ISSUE TITLE
[asking] Download Image - raw picture

### ISSUE THREAD

**Issue by Windslab** [tonsky/FiraCode#1139]
Dear developers, I like your style and apriciate font.

Please, could you give me this one picture for my repo?

![image](https://user-images.githubusercontent.com/60715874/96026099-bd440b80-0e5e-11eb-8800-e9e3c581fbe7.png)

I'll change a color and do a button for Arch Linux VMware Workstation image.

My repo(Read about Proxmark3 device, if you did't know what is this): https://github.com/Windslab/ArchSpace

**Comment by tonsky** [comment]
Here’s an SVG version:

[download.svg.zip](https://github.com/tonsky/FiraCode/files/5384785/download.svg.zip)
