### ISSUE TITLE
fira code width went wrong

### ISSUE THREAD

**Issue by Hocnonsense** [tonsky/FiraCode#1142]
![image](https://user-images.githubusercontent.com/48747984/96360761-6dad5a80-1152-11eb-8ed5-5586eab9380f.png)
as you can see...
Can this problem be fixed?

After all, thanks for your **GREAT Fira Code**!

**Comment by tonsky** [comment]
Sure. What editor is this, what OS, which version of FiraCode do you have installed?

**Comment by Hocnonsense** [comment]
OK, I'm using vscode on windows
version:
```
版本: 1.50.1 (system setup)
提交: d2e414d9e4239a252d1ab117bd7067f125afd80a
日期: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```
system: windows 10 2004. I have 2 computers and a CentOS in vmware. When using vscode remote ssh to connect to CentOS, the font width is also uncorrect.
FiraCode version: v5.2, modifed on 2020/6/12

**Comment by tonsky** [comment]
Thank you! Two more questions that might help me reproduce the issue: what color scheme is on the screenshot and what language syntax is active in this file? Thank you!

**Comment by RubenVerg** [comment]
Looks like default dark in VSCode in a Markdown file.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Hocnonsense** [comment]
Yes, this is a markdown file and the theme is Default Dark+.

additional:
```
{
    "editor.fontFamily": "Fira Code Retina, Microsoft YaHei mono, monospace",
    "editor.fontLigatures": true,
}
```

**Comment by Hocnonsense** [comment]
Thanks... I'v got it.

`Fira Code Retina` is thinner than `fira code`

Sorry to waste your time.

**Comment by tonsky** [comment]
Weird, it‘s not supposed to be. There were quite a few complications with it because of the non-standard name. When I get ahold of Windows machine, I’ll take a closer look, thanks for reporting!

**Comment by wopian** [comment]
I also use 5.2 Retina on Windows and never really noticed it happening at the time, but I can replicate it using the above characters and looking back at a few README/markdown files, I've spotted several with misalignments.

Fira Code Regular & Bold
![image](https://user-images.githubusercontent.com/3440094/96479004-475dec80-1230-11eb-8ffa-c707ad00c3b6.png)

Fira Code Retina & Bold
![image](https://user-images.githubusercontent.com/3440094/96479050-55ac0880-1230-11eb-80e8-071fbb70203d.png)

```markdown
`**12345678901234567890**>===!=$><=<=>=>!=<=`
`**12345678901234567890**>===!=$><=<=>=>!=<=*
`**12345678901234567890-->===!=$><=<=>=>!=<=**

`---|---|---|`**///////*..........|
`***|***|***|`**|||||||...........|
`---|---|---|`**|||||||**.........|
`...|...|...|`**|||||||...........|
```

---

`Light`, `Medium`, `SemiBold` and `Bold` are correct. Using the Retina weight and adding `"editor.fontWeight": "bold"` to `settings.json` results in the top section aligning, but even worse misalignments in the bottom section:

![image](https://user-images.githubusercontent.com/3440094/96480644-6fe6e600-1232-11eb-8922-8787ce8bae66.png)

**Comment by philippnurullin** [comment]
Seems like VS Code is applying synthetic Bold because it cant find the `Retina Bold` weight.

**Comment by Hocnonsense** [comment]
https://github.com/microsoft/vscode/issues/136189
> It looks like the bold variant of the font was not installed, and the font rendering stack from Chromium decides to "simulate" boldness by making the glyphs wider.
