### ISSUE TITLE
Add different-looking font for Italics (for code comments, like Consolas)

### ISSUE THREAD

**Issue by SFM61319** [tonsky/FiraCode#1144]
Basically what the title says. It would look great and more readable if the font looked different in italics (useful for code comments and documentation). Just like *`Consolas`*.  
  
This is just a feature request tho.

**Comment by tonsky** [comment]
Thank you for this request! This is a long-standing issue that many people have raised. I’d be happy to, one day, if I find enough time, to do it. So far, let’s track progress in #513
