### ISSUE TITLE
`::<` looks weird

### ISSUE THREAD

**Issue by Veykril** [tonsky/FiraCode#1145]
In Rust there is a so called `turbofish` operator which is used by generic function calls which makes use of the character sequence `::<`. Unfortunately FiraCode causes this sequence to look a bit weird due to the font ligatures moving the middle colon up a bit:
![grafik](https://user-images.githubusercontent.com/3757771/97550163-998dd300-19d1-11eb-82dc-0afba611bd34.png)
I imagine this is due to the fact that `:<` is considered a ligature in the `other` category, but I wonder if it would be possible to have this behaviour reset for the `::<` character case given that the two colons are just scoping operators here, assuming this is possible.

**Comment by tonsky** [comment]
Thank you for reporting, I’ll take a look!

**Comment by aaronbell** [comment]
I found this yesterday too. I think it can be solved fairly easily by adding in an extra ignore to the `center` lookup (line 731):
`    ignore sub colon colon' [less greater]; # ignores the ::< case `

**Comment by jhpratt** [comment]
@tonsky Any plans for a new release? It's a shame this patch has been merged for a few months and it's not out yet. No big deal either way, just curious.

**Comment by tonsky** [comment]
Yes, new release will come shortly

**Comment by jhpratt** [comment]
Awesome. Thanks for the quick response!

**Comment by dtolnay** [comment]
Released in https://github.com/tonsky/FiraCode/releases/tag/6.
