### ISSUE TITLE
PHP open tag

### ISSUE THREAD

**Issue by RajcsanyiZ** [tonsky/FiraCode#1147]
I think the php close tag is not important, but the opening tag is very cool this way:

![image](https://user-images.githubusercontent.com/1152691/97812297-b439a380-1c80-11eb-8e6d-941052630e1a.png)

_Originally posted by @RajcsanyiZ in https://github.com/tonsky/FiraCode/issues/75#issuecomment-720138943_

**Comment by RajcsanyiZ** [comment]
Ok, my first suggestion is not so popular. What do you think about this new conception!?

![image](https://user-images.githubusercontent.com/1152691/98029354-a8301c00-1e0f-11eb-8996-9c8b47975666.png)

**Comment by RajcsanyiZ** [comment]
And the short version of PHP code tag is work similar design (I think):

![image](https://user-images.githubusercontent.com/1152691/98030519-6c965180-1e11-11eb-995b-f52c938f01cd.png)

**Comment by RajcsanyiZ** [comment]
I don't know this is good or not, but the $this and the self:: expressions is special in PHP. Maybe the compact format is better, but please vote or devote this idea.

![image](https://user-images.githubusercontent.com/1152691/98045366-b3437600-1e28-11eb-8730-e87374a01210.png)

**Comment by wopian** [comment]
Ligatures need to be the same length as the individual characters, otherwise its no longer a monospaced font.

**Comment by RajcsanyiZ** [comment]
> Ligatures need to be the same length as the individual characters, otherwise its no longer a monospaced font

I see. So the $this-> and self:: logic is not acceptable, but the other suggestions I think OK. What do you think redesign the plans to follow the monospace logic or it is good in this form?

**Comment by RajcsanyiZ** [comment]
Maybe it is useable:

![image](https://user-images.githubusercontent.com/1152691/98250225-7a65e700-1f77-11eb-9424-b9908d433b11.png)

![image](https://user-images.githubusercontent.com/1152691/98250263-83ef4f00-1f77-11eb-94ea-a001fda8cccb.png)
