### ISSUE TITLE
PHP Docblock

### ISSUE THREAD

**Issue by RajcsanyiZ** [tonsky/FiraCode#1149]
I think the PHP docblock is more readable that way, but I don't know what think the others. Please vote/devote it...

![image](https://user-images.githubusercontent.com/1152691/98049389-dde4fd00-1e2f-11eb-9727-9bf29111a4a4.png)

**Comment by RajcsanyiZ** [comment]
Variation - b.

![image](https://user-images.githubusercontent.com/1152691/98050198-76c84800-1e31-11eb-9a08-62a0b9dbe17c.png)

**Comment by RajcsanyiZ** [comment]
Variation - c.
![image](https://user-images.githubusercontent.com/1152691/98050498-1f76a780-1e32-11eb-9cb2-7ddae6b8ac1b.png)

**Comment by RajcsanyiZ** [comment]
Variation - d. 
![image](https://user-images.githubusercontent.com/1152691/98050921-09b5b200-1e33-11eb-992e-d593e8cfd864.png)

**Comment by RajcsanyiZ** [comment]
And lastly (at this time), with FiraCode's star (Variation - e.)

![image](https://user-images.githubusercontent.com/1152691/98051187-9b252400-1e33-11eb-907d-3dac24199348.png)

**Comment by tonsky** [comment]
Looks cool, but there’s no way to make ligatures vertical on a font level
