### ISSUE TITLE
suggestion about rounded font or Soft 

### ISSUE THREAD

**Issue by nerdpanda-ir** [tonsky/FiraCode#1150]
hi 
first i thanks for created this Font 
please release rounded font version . 
now this font  is  very sharp  
![Screenshot_2020-11-04_10-55-50](https://user-images.githubusercontent.com/39291525/98082086-6940ab80-1e8d-11eb-8f27-a02cf420a424.png)

**Comment by tonsky** [comment]
Hi @nerdpanda-ir, thank you for your suggestion!

This is a very nice suggestion, although I am afraid it will require too much work, almost as much as creating a new font from scratch. And I am not a professional font designer.

Thank you again!

**Comment by RubenVerg** [comment]
You could take Fira Sans and add the ligatures
I was about to suggest this myself.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
