### ISSUE TITLE
PHP self and $this keywords

### ISSUE THREAD

**Issue by RajcsanyiZ** [tonsky/FiraCode#1151]
Please vote or devote it!

![image](https://user-images.githubusercontent.com/1152691/98251773-720eab80-1f79-11eb-853f-7c4252dd67c2.png)

![image](https://user-images.githubusercontent.com/1152691/98252577-68397800-1f7a-11eb-92f7-9ae7b9964744.png)

**Comment by tonsky** [comment]
This makes it look like there is an extra space, and does not bring any benefits to readability. Sorry

**Comment by RajcsanyiZ** [comment]
Ok, you are right. (I think)
