### ISSUE TITLE
PHP and PHP shorthand tags.

### ISSUE THREAD

**Issue by RajcsanyiZ** [tonsky/FiraCode#1152]
Please vote or devote it!

![image](https://user-images.githubusercontent.com/1152691/98253059-e0a03900-1f7a-11eb-94b0-0c65cf1db78a.png)

**Comment by tonsky** [comment]
I don’t think there’s a meaningful improvement to `<?` or `?>`

**Comment by RajcsanyiZ** [comment]
I think this format is much more readable mainly if you write template type codes,  because

open tag: <?=   
expression: ...
close tag ?>

because there are three blocks 

The original format doesn't show these blocks.

**Comment by RajcsanyiZ** [comment]
I think the second variation is clearly better readable.

![image](https://user-images.githubusercontent.com/1152691/98302860-76f54e80-1fbd-11eb-811c-764eca3fd71e.png)

**Comment by j-f1** [comment]
`<?= $var ?>`?

**Comment by tonsky** [comment]
If it reads better, just add whitespace. This is not something that should be solved at ligature level.

**Comment by RajcsanyiZ** [comment]
Ok, and what is the border the ligature level and the whitespace level!? Could you suggest me some documentation about this topic to understand that?

**Comment by RajcsanyiZ** [comment]
I used this syntax <? $var ?> format before, because it was ok, but I write this topic to discuss this possibility.

**Comment by iammikek** [comment]
I don’t see any advantage making a change which switches away from standard php.

If you want to give focus, use long hand 
```
<?php echo $var; $>
```
You are trying to solve a problem that doesn’t exist.

**Comment by RajcsanyiZ** [comment]
> I don’t see any advantage making a change which switches away from standard php.
> 
> If you want to give focus, use long hand
> 
> ```
> <?php echo $var; $>
> ```
> 
> You are trying to solve a problem that doesn’t exist.
> 
> ```
> <?=
> ```
> 
> Is shorthand to use for echoing a variable. If you give space it makes it gives developer suggestion that it’s just a php open tag and you can do any php command after. Which it doesn’t.

I think, the

**Comment by RajcsanyiZ** [comment]
I can write this expressen some different way:

```php
<?php echo $var; ?>
<?=$var?>
<?= $var ?>
<?php echo("{$var}"?>
<?="{$var}"
```
But!

The essense this expresssion the:
```$var```

Every other information is unimportant, I think.

If we use ligatures and a difference is only liddle, but it is exists.

I can use spaces, I can use lot of type of sparation, but the ligature can develop and focus, and smartify the PHP code.

If you are think it is not important, I can say the ligatures and the FiraCode is not so important. But someone needs this features why doesn't important that issue!?
