### ISSUE TITLE
No having all powerline symbols on Mac+Alacritty

### ISSUE THREAD

**Issue by svanharmelen** [tonsky/FiraCode#1154]
I'm a little puzzled why I don't see all powerline symbols when using Alacritty. I don't know all the codes, but this already shows the issue I think:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/4171547/98463203-e9cb1900-21b9-11eb-9e86-815d7d0ac39d.png">

Using the default Terminal app it does seem to work as expected:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/4171547/98463242-33b3ff00-21ba-11eb-902d-b1751c028d3a.png">

I know Alacritty doesn't support ligatures, but I'm fine with that. I still love the way this fonts looks like and would like to use it in my setup. Is there anything I can do or config to get the powerline symbols to show up?

Will ask on the Alacritty repo as well... Not sure were the issue originates. Thanks!

**Comment by tonsky** [comment]
Fira Code is on the bottom, right? Which characters are missing?

**Comment by svanharmelen** [comment]
Both are FiraCode. The first one is in Alacritty the second one in the Terminal app.

**Comment by tonsky** [comment]
Judging by the look of `9`, first one seem to be something different

**Comment by svanharmelen** [comment]
Wow... Sharp eye! And you were, of course, completely correct 😏

Turned out I made a typo and I guess Alacritty used some kind of fallback fonts, not being Fira Code.

Thanks for the quick feedback/help!
