### ISSUE TITLE
backslach overhiding circumflex accent (caret)

### ISSUE THREAD

**Issue by dizz-y** [tonsky/FiraCode#1163]
I found this when writing a regex with JS in VS Code.

If you type /^\d{5}/ you'll see that the backslash overlaps the caret.

(this accent mark doesn't exist in English (only in languages related to Latim, I guess), so I don't know if I am spelling it right.)

**Comment by tonsky** [comment]
Not sure what you mean, can you attach a screenshot? This is my VS Code:

<img width="139" alt="Screen Shot 2020-12-06 at 23 30 41" src="https://user-images.githubusercontent.com/285292/101294990-14d97480-381b-11eb-83f3-1207b5196920.png">

**Comment by dizz-y** [comment]
Oh, fuck. Sorry to bother you. Now that I have realized that it is a problem related to the theme I am using (matherial theme).
![image](https://user-images.githubusercontent.com/55499252/101296328-8f959600-3801-11eb-9915-2b5316ae1850.png)
