### ISSUE TITLE
Not monospace in Xcode 12.2 (12B45b)

### ISSUE THREAD

**Issue by marzvrover** [tonsky/FiraCode#1168]
When using `Xcode 12.2 (12B45b)` Fira Code is _not_ monospaced.
Architecture: `Intel`
OS: `macOS 11.0.1 (20B29) Big Sur`

**Comment by tonsky** [comment]
Please provide a screenshot

**Comment by marzvrover** [comment]
<img width="551" alt="FiraCode" src="https://user-images.githubusercontent.com/6617862/102152896-022af500-3e44-11eb-9d8b-a010d8185194.png">
<img width="751" alt="sf_mono" src="https://user-images.githubusercontent.com/6617862/102152897-02c38b80-3e44-11eb-9286-5ccf009f7c71.png">

**Comment by tonsky** [comment]
This is not just Fira Code on the top screenshot. You have a mix of fonts and sizes there. I guess SF Mono / Fira Code

**Comment by marzvrover** [comment]
Thank you for the timely help with this. If anyone finds this issue in the future make sure you have all the items selected in `Xcode Preferences > Themes > Source Editor` before changing the font.
