### ISSUE TITLE
alternative <= & >=

### ISSUE THREAD

**Issue by tomByrer** [tonsky/FiraCode#117]
Like all your math Ligatures, I appreciate their conciseness & help my mind group symbols.  But at smaller resolutions,  `<=` & `>=` are harder to read.  Can you change or make an alternative so the bottom line is either thicker or horizontal to be more legible please?

**Comment by tomByrer** [comment]
If you want to lift another font maker's system for stylistic sets, maybe [Iosevka](https://github.com/be5invis/Iosevka#weights-variants-and-opentype-features) can help you out?

**Comment by garycourt** [comment]
I too am having trouble reading these symbols. Would very much like to see the equal part of the symbol horizontal with a thicker line. Like the unicode example:
![lessthan_or_equal_to](https://cloud.githubusercontent.com/assets/158942/14569439/01144776-02fc-11e6-9416-5054eb9e154d.png)![greaterthan_or_equal_to](https://cloud.githubusercontent.com/assets/158942/14569460/2daa9c86-02fc-11e6-8a89-b0bb2c40223b.png)

**Comment by j6k4m8** [comment]
Sorry about the dup comment on #13, but... Just wanted to voice my interest in this same thing as above: Horizontal bottom line would dramatically improve readability at small scale.

**Comment by tonsky** [comment]
I’ve increased spacing between two bottom lines by the factor or 1.8. Hope that makes them more readable.
