### ISSUE TITLE
Lua inequality ~= rendered counter-intuitive

### ISSUE THREAD

**Issue by tsafin** [tonsky/FiraCode#1171]
Lua uses `~=` for inequality, and it looks counter-intuitive if ligatures enabled. I don't see any language where it would be meaning approximately equal, so it makes no much sense (IMVHO) to render it this way, and we would rather see something very similar to how `!=` is rendered.

![image](https://user-images.githubusercontent.com/4956130/102780880-c1812d80-43a7-11eb-8eef-c544aee76fcb.png)

**Comment by tonsky** [comment]
According to changelog, it was removed in v 3.0 #381. Maybe you need to update?

**Comment by tsafin** [comment]
I'll check, thanks!

**Comment by tsafin** [comment]
I'm confused - Windows Fonts applet does show that there is no such ligature in the selected font set. But vscode still insists on older rendering. Looks like vscode specific issues (or taking into account that Windows Terminal experiences the same problems - gdi+ specific issue. Will check how it will persist after restart?..

![image](https://user-images.githubusercontent.com/4956130/102825767-86efb300-43f0-11eb-8f79-f365925c3086.png)

**Comment by tsafin** [comment]
Yup, vscode ligatures have been fixed with restart (though Windows Terminal have not). You could close this issue though.

Much thanks!

**Comment by tonsky** [comment]
We also have this note about cleaning up fonts on Windows. Might not be relevant, but it’s something you can try:

https://github.com/tonsky/FiraCode/wiki/Troubleshooting#corrupted-font-in-intellij-on-windows
