### ISSUE TITLE
Box drawing characters U+2575 and U+2577 are swapped

### ISSUE THREAD

**Issue by xandris** [tonsky/FiraCode#1174]
Here's what they look like on Mac OS 11.1:

![image](https://user-images.githubusercontent.com/1970616/102935741-97894300-445b-11eb-836f-9b1a63e1bc96.png)

And how they're supposed to look:

![image](https://user-images.githubusercontent.com/1970616/102936086-55accc80-445c-11eb-906f-e314f07886bf.png)

And Unicode's diagram of these:

![image](https://user-images.githubusercontent.com/1970616/102935884-da4b1b00-445b-11eb-9d0c-9a4e8b07c280.png)

Source: https://www.unicode.org/charts/PDF/U2500.pdf

These are the light "half up" and "half down" characters. The other half-line characters don't seem to be affected.

**Comment by tonsky** [comment]
This is what it looks like to me on v 5.2:

<img width="327" alt="Screenshot 2020-12-23 at 02 31 34" src="https://user-images.githubusercontent.com/285292/102948792-0354c580-44c7-11eb-8e0e-71609aec679a.png">

Seems correct?

**Comment by xandris** [comment]
I must have screwed up updating the fonts. 🤦‍♀️ 
Oh, reinstalling them doesn't do anything, awesome. I had to remove and reinstall the fonts. Sorry for the trouble.

**Comment by tonsky** [comment]
No worries — happy to help!
