### ISSUE TITLE
FYI: Atom (& perhaps other editors) need font names with spaces to be quoted.

### ISSUE THREAD

**Issue by tomByrer** [tonsky/FiraCode#118]
Like so:
![atom-font-change-quoted](https://cloud.githubusercontent.com/assets/1308419/12472464/b0dae1da-bfc5-11e5-9047-6d1bfd98c220.gif)

**Comment by tomByrer** [comment]
Just wanted to host the image for [wiki/Atom-instructions](https://github.com/tonsky/FiraCode/wiki/Atom-instructions).

**Comment by MadcapJake** [comment]
Mine isn't quoted and it works fine.

**Comment by davidcelis** [comment]
Same; I entered `FiraCode-Light` and no quotes were needed.
