### ISSUE TITLE
Problem with condition < and >=

### ISSUE THREAD

**Issue by KozerG17** [tonsky/FiraCode#1180]
This problem happens when I use in some if-conditions like **if (a < 5 || b >= 10)**. It may turn into this:
![Untitled](https://user-images.githubusercontent.com/74275726/103460397-73294280-4d48-11eb-9903-81c516b5240a.png)
Its ligature seems weird to me.

**Comment by KozerG17** [comment]
I've tried it on Notepad and it works properly. But I'm using Sublime Text 3.

**Comment by tonsky** [comment]
I guess syntax highlighting is preventing ligature from forming. For some reason your formatter thinks that > and = are separate tokens. I suggest you report this to the highlighter autor

**Comment by KozerG17** [comment]
Oh. You're right. Conflict with C++ syntax made that wrong. I'm not sure what to do now since operator <> is an part of template in C++, but not in this case.

**Comment by tonsky** [comment]
Report here? https://github.com/sublimehq/sublime_text
