### ISSUE TITLE
Some way to draw decent progress bars

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#1182]
Placed in private use area `U+EE00` .. `U+EE05`

Doesn’t seem to conflict with:

- Powerline (`U+E0A**` .. `U+E0B**`)
- [Powerline-extra-symbols](https://github.com/ryanoasis/powerline-extra-symbols) (`U+E0A**` .. `U+E0D**`) 
- [Awesome terminal fonts](https://github.com/gabrielelana/awesome-terminal-fonts/blob/master/build/devicons-regular.sh) (`U+E6**`) 
- [PragmataPro](https://fsd.it/pragmatapro/All_chars.png) (`U+E00**` .. `U+E0D**`, `U+F0**` .. `U+F8**`)

<img width="627" alt="Screenshot 2021-01-16 at 16 14 31" src="https://user-images.githubusercontent.com/285292/104815614-f0a78500-5815-11eb-931c-669a4f18b9f5.png">

<img width="338" alt="Screenshot 2021-01-16 at 16 20 31" src="https://user-images.githubusercontent.com/285292/104815762-d28e5480-5816-11eb-87f8-171a71999582.png">

**Comment by tonsky** [comment]
Placed in private use area `U+E000` .. `U+F8FF` at `U+EE**`

Doesn’t seem to conflict with PragmataPro (`U+E00**` .. `U+E0D**`) https://fsd.it/pragmatapro/All_chars.png
Powerline (`U+E0A**` .. `U+E0B**`)
Powerline-extra-symbols (`U+E0A**` .. `U+E0D**`) https://github.com/ryanoasis/powerline-extra-symbols
Awesome terminal fonts (`U+E6**`) https://github.com/gabrielelana/awesome-terminal-fonts/blob/master/build/devicons-regular.sh

<img width="627" alt="Screenshot 2021-01-16 at 16 14 31" src="https://user-images.githubusercontent.com/285292/104815614-f0a78500-5815-11eb-931c-669a4f18b9f5.png">

<img width="166" alt="Screenshot 2021-01-16 at 15 57 58" src="https://user-images.githubusercontent.com/285292/104815608-e4232c80-5815-11eb-8a4b-d697111fcbb6.png">

**Comment by Vampire** [comment]
The release notes somehow made me think that the ASCII progress bars will be replaced automatically with the FC progress bar, is that wrong?
How is this supposed to be used then?
A software drawing a progress bar does not know which font is used to draw.
So would it need some configuration switch to tell it to use those characters to draw the progress bar, or how would this work?

**Comment by tonsky** [comment]
I hope other font will adopt this convention and eventually we’ll be able to show progressbars this way in any font

**Comment by Vampire** [comment]
So indeed the application would need to use those characters explicitly, right?
I thought you might automatically replace them like you replace arbitrary length arrows now and so on.

Which btw. looks a little bit strange for Gradle progress bars now :-D
![image](https://user-images.githubusercontent.com/325196/234903408-923ac686-2dfe-46bc-825f-a260bb478724.png)

**Comment by qm3ster** [comment]
A bit unexpected you didn't go with sub-character sizes to increase progress bar resolution.
