### ISSUE TITLE
Make --- a line ligature

### ISSUE THREAD

**Issue by IlanCosman** [tonsky/FiraCode#1190]
Four dashes gets turned into a line ligature in Fira Code. However, in Markdown, 3 dashes is enough to create a break like so:

---

**Comment by tonsky** [comment]
I wonder if `---` is an operator anywhere else or is it just Markdown thing?

**Comment by IlanCosman** [comment]
After some brief research, it seems possible in some languages, yet vastly unlikely that anyone would ever do so:
https://stackoverflow.com/questions/13874179/can-you-have-a-triple-minus-signs-in-c-programming-what-does-it-mean

As the number one comment on the post says: "You can if you know how to survive the wrath of your teammates."

**Comment by tonsky** [comment]
Looks like Haskell doesn’t use it either (it uses `+++` and `***` but not `---`). So maybe it is worth turning into a line, thank you!

**Comment by pxeger** [comment]
Elixir has `---`, but it is not implemented by default in any standard libraries: https://hexdocs.pm/elixir/operators.html#custom-and-overridden-operators

**Comment by tonsky** [comment]
@pxeger what do you mean by “has, but not implemented”?

**Comment by RubenVerg** [comment]
> what do you mean by “has, but not implemented”

Elixir supports a limited set of operators, some of which have no definition in the standard library

**Comment by tonsky** [comment]
So, like, libraries can redefine `---` because it’s reserved, but they can’t invent their own operators like “-?->”?

**Comment by RubenVerg** [comment]
If I understand that documentation correctly, yes

**Comment by pxeger** [comment]
Yes.

I think, on balance, it's better to have it as a line ligature, but I thought I should mention it anyway
