### ISSUE TITLE
How about curved parenthesis like Monaco?

### ISSUE THREAD

**Issue by pamu** [tonsky/FiraCode#1198]
![Screenshot 2021-02-02 at 20 15 29](https://user-images.githubusercontent.com/4508686/106650654-70ae4880-6593-11eb-924b-77c79fbfffcd.png)
![Screenshot 2021-02-02 at 20 15 06](https://user-images.githubusercontent.com/4508686/106650714-83c11880-6593-11eb-9f38-39c1c7158027.png)

I think Monaco has by far the best curved parenthesis, how about making parenthesis more curved or as curved as Monaco?

**Comment by tonsky** [comment]
Maybe as a character variant, sure
