### ISSUE TITLE
How to enable open type features in Sublime/Atom

### ISSUE THREAD

**Issue by oskarrough** [tonsky/FiraCode#12]
On OS X I've specified the font family in Atom and Sublime 3 as 'FiraCode-regular' which enables the font but I'm not seeing any ligatures before I add `text-rendering: optimizeLegibility;` to my theme.

Are there any recommendations to enable open type features with FiraCode in Atom or Sublime?

**Comment by alexandernst** [comment]
Related  https://github.com/atom/atom/issues/6921

**Comment by tonsky** [comment]
Atom ligatures support is buggy (https://github.com/atom/atom/issues/6055), Sublime is not supported (http://sublimetext.userecho.com/topic/433445-opentype-support-ligatures-curly-quotes-contextual-and-alternate-symbols/)
