### ISSUE TITLE
Font width

### ISSUE THREAD

**Issue by BigfootN** [tonsky/FiraCode#1206]
Hello,

First I would like to precise that I am not sure whether my question is relevant or not, I am aware.

I would like to know if it would be possible to have a thinner, in terms of width, font style (like a condensed variant) ?

Thank you very much in advance for any response.

**Comment by tonsky** [comment]
Unfortunately, it’s too hard. I’ll have to re-draw every glyph in the font, there’s no easy way to do so.

**Comment by BigfootN** [comment]
Thank you for your response. I understand.
