### ISSUE TITLE
Can calt do differenciate strings and functions?

### ISSUE THREAD

**Issue by ShalokShalom** [tonsky/FiraCode#1207]
Hi there :)

I am currently rooting for [\ becoming the lambda symbol](https://github.com/i-tu/Hasklig/issues/124)  in Haskling. 

They are using your calt code, so I thought you are a great address to tell us something about its capabilities.

Is it possible to differentiate between functions and strings, as mentioned in the Haskling issue?

Thanks!

**Comment by RubenVerg** [comment]
The issue doesn't mention calts and no, it's not for most cases (or at least for what I know)
________________________________

**Comment by ShalokShalom** [comment]
The issue questions if the differentiation can be made and the backlog from version 1.1 speaks about calt. 

https://github.com/i-tu/Hasklig/releases/tag/1.1

**Comment by tonsky** [comment]
No, it can’t be differentiated from the font. You need syntax highlighting in the editor that can apply different features to different regions. I think you can have something like that in Atom/VS Code

**Comment by ShalokShalom** [comment]
So the syntax highlighting does report change the character ultimately to the ligature then?

**Comment by ShalokShalom** [comment]
Ah, wonderful
