### ISSUE TITLE
atom fonts package

### ISSUE THREAD

**Issue by orlin** [tonsky/FiraCode#121]
I saw the Atom install wiki page got improved so I tried and got no FiraCode again, and then I remembered I had installed the `fonts` package...  The font selected in its settings overrides whatever font is configured through Atom's Editor Settings.  Maybe that should be mentioned as a warning or recommendation, (because on Mac OS X at least) picking FiraCode from that package works better (seems to solve the rendering issues I have seen people complain about) as compared to "Fira Code" in Atom's own settings with the package disabled.  The only downside is the package not offering the latest FiraCode (from what I can tell by trying "www").  Personally I prefer the font coming through a package, as long as it's kept up to date - less manual installation...

**Comment by tonsky** [comment]
I can’t maintain package for editors, there’s just too many of them. Maybe issues of keeping package up to date and installation caveats should be addressed to package maintainer?
