### ISSUE TITLE
Rider and Italics

### ISSUE THREAD

**Issue by RaptorCZ** [tonsky/FiraCode#1212]
I found that FiraCode doesn't support Italics (yet). I'm using Rider and Rider Dark skin. But it uses italics for comment. Because of missing support all comment looks ugly with shifted lines. So you should mention this in editor compatibility list. Well, or maybe add italics?

**Comment by j-f1** [comment]
See #172

**Comment by tonsky** [comment]
I wish I could, but it’s too much work. Rider uses fake italics that are mechanically generated from regular style. If they look out of place, try opening an issue with them?
