### ISSUE TITLE
Fira Code looks so blurry on Windows 10

### ISSUE THREAD

**Issue by victorbombella** [tonsky/FiraCode#1213]
Hi everyone!

First of all thanks for this great font. My problem comes with Windows 10 and the majority of the applications, for example Visual Studio Code, Eclipse, OneNote and many more... The font looks pretty blurry and I don't know why... I've changed the Antialiasing settings in Windows in many ways and the problem persists...

Anyway, there are many other fonts that looks ok, for example Fira Mono, Consolas, Source Code Pro... My question is why Fira Code looks blurry?

Here are two examples on how "Fira Mono" looks vs how "Fira Code" looks in Visual Studio Code and Eclipse IDE:

**Eclipse Fira Mono:**
![FiraMonoEclipse](https://user-images.githubusercontent.com/77814145/110670942-8f57be80-8193-11eb-9431-b8055390968b.png)

**Eclipse Fira Code:**
![FiraCodeEclipse](https://user-images.githubusercontent.com/77814145/110670966-97aff980-8193-11eb-9aad-14c9384f54ee.png)

**Visual Studio Code Fira Mono:**
![FiraMonoVSC](https://user-images.githubusercontent.com/77814145/110670987-a1396180-8193-11eb-94b4-8d5410d3078c.png)

**Visual Studio Code Fira Code:**
![FiraCodeVSC](https://user-images.githubusercontent.com/77814145/110671017-a7c7d900-8193-11eb-9f5a-a8ff945c0961.png)

Thanks for reading and hope there'll be a solution soon...

Regards!

**Comment by tonsky** [comment]
Hi @victorbombella! Are you using TTF files or OTF ones?

**Comment by victorbombella** [comment]
Hi @tonsky I'm using TTF files

**Comment by tonsky** [comment]
Can you check how e.g. 1.207 looks like? Be sure to use TTFs too, and uninstall currently installed version. Thank you! https://github.com/tonsky/FiraCode/releases/tag/1.207

**Comment by victorbombella** [comment]
:O That version looks very well! Actually looks like Fira Mono but with the ligatures! Thank you! 

I see that version is from 2019, it may be some ligatures and symbols missing... It could be an update of this specific version (1.207) with the new ligatures?

Really really, thank you!

**Comment by tonsky** [comment]
Okay, can you try this please? This is from master, but with ppem restored to original Fira Mono value. I want to make sure this is the actual reason. Thanks!

[ttf.zip](https://github.com/tonsky/FiraCode/files/6119135/ttf.zip)

**Comment by victorbombella** [comment]
This last one looks great:

![NewFiraCode](https://user-images.githubusercontent.com/77814145/110707849-8250c480-81bf-11eb-92a1-ac4f6c178d7d.png)

**Comment by victorbombella** [comment]
The issue was solved. Thank you

**Comment by djimenezweb** [comment]
I was having the same problem and it seems solved after updating my graphic card drivers.
