### ISSUE TITLE
Requesting the inclusion of two Unicode symbols: ∀ and ∷

### ISSUE THREAD

**Issue by kurtmilam** [tonsky/FiraCode#1219]
Great font! I really enjoy using it in VSCode. The only issue I have with the font at this time is that the `∀` and `∷` symbols don't seem to be included. I believe that's the case because, when using dark mode in VSCode, the following code:

`runMem ∷ ∀ a s. Mem s a → s → Tuple a s`

Looks like this with Fira Code enabled:

![image](https://user-images.githubusercontent.com/385695/112229681-b6060280-8c33-11eb-846e-a42c8459826a.png)

I've read that VSCode (among other applications) has issues correctly styling (including applying colors) symbols that aren't included in the active font. If I switch from Fira to Menlo, for instance, I see the following:

![image](https://user-images.githubusercontent.com/385695/112229903-1c8b2080-8c34-11eb-866e-648c9859b39c.png)

As you can see, in Menlo, the symbols are nicely styled with enough contrast to be easily visible.

**Comment by tonsky** [comment]
You are right, they are not in the font. Will add, thanks!

**Comment by kurtmilam** [comment]
For context, the language is [PureScript](https://www.purescript.org/), a Haskell-like language that compiles to JavaScript (and other languages).

PureScript recognizes a number of Unicode symbols in source.

**Comment by tonsky** [comment]
Actually U+2200 is in the font since v3:

<img width="405" alt="Screenshot 2021-04-18 at 01 42 37" src="https://user-images.githubusercontent.com/285292/115129563-5f4bd880-9fe7-11eb-8809-f1bd9f53b80f.png">

U+2237 will be in v6.
