### ISSUE TITLE
Greek letters not distinguishable

### ISSUE THREAD

**Issue by baggepinnen** [tonsky/FiraCode#122]
There are several issues with greek letters, for instance nu looks like v, gamma looks like y
v ν
y γ
This is an issue when programming in e.g. Julia or in tex with unicode input.

**Comment by tonsky** [comment]
You should probably report that to [Fira Mono repo](https://github.com/mozilla/Fira) instead. In Fira Code I’m only working with ligatures and keep rest of the font intact
