### ISSUE TITLE
Markdown syntax for italic bold (the embracing *** symbol) has 3rd asterisk misaligned (left-side symbol only)

### ISSUE THREAD

**Issue by PedanticHacker** [tonsky/FiraCode#1226]
![image](https://user-images.githubusercontent.com/14254085/114253341-1e7e0f00-99aa-11eb-83a8-4cdced02200d.png)

See line 51 in the image above where it shows `***python-chess***` and notice how the 3rd asterisk (of the left-side symbol) is misaligned. This is bad.

**Comment by tonsky** [comment]
Your editor seems to apply fake italics (Fira Code has no italics). This can’t be handled by font

**Comment by PedanticHacker** [comment]
I see. But Fira Code could make italic through shearing, right?

**Comment by PedanticHacker** [comment]
I have solved my issue. The solution was to write my bold italic text in the format `**_text_**`  instead of `***text***`. Now Sublime Text 3 lints Markdown syntax correctly. Sorry for reporting a false-positive.

**Comment by tonsky** [comment]
No worries, glad this is resolved
