### ISSUE TITLE
Some Unicode characters are too wide

### ISSUE THREAD

**Issue by hmarthinsen** [tonsky/FiraCode#123]
Some Unicode characters are wider than they should be, breaking the natural alignment of the font. This applies to e.g. ∈ and ≔. I use both of these in LaTeX code with Unicode math. Here is a screenshot of how it looks in the Atom editor:
![untitled](https://cloud.githubusercontent.com/assets/6989581/12547706/2de9f302-c352-11e5-8506-de27e23de8da.png)

**Comment by tonsky** [comment]
I bet these character are not even in the font, so Atom uses selected another default one to render them. Also see #98
