### ISSUE TITLE
Full list of every ligature?

### ISSUE THREAD

**Issue by pxeger** [tonsky/FiraCode#1232]
Would it be possible to add an exhaustive list of every ligature in the font to the documentation, for comparison with other fonts or to easily check if a particular glyph is implemented?

I'm not sure if it's possible or reasonable to do automatically because it might include some partial ligatures (I don't really know how the font works), so it might have to be maintained manually. In this case I could try to get it started with a PR but I don't think I would get all of them first try

**Comment by tonsky** [comment]
Images from the README should contain most of them. There’s also a text version https://github.com/tonsky/FiraCode/blob/master/extras/showcases.txt

Is that enough or are you looking for something different?

**Comment by pxeger** [comment]
Yes, `showcases.txt` is what I was looking for, thanks!
