### ISSUE TITLE
Add .otf back in for KDE users who want gamma-corrected rendering

### ISSUE THREAD

**Issue by taprobane99** [tonsky/FiraCode#1233]
KDE qt5 does gamma-corrected rendering of fonts, but only .otf.

On my system I have font hinting turned off completely.

Can you add .otf back in to the release, so that I can have proper gamma-corrected Fira Code on my desktop?

More info:

TTF (e.g. Noto Sans, Ubuntu)

No stem darkening and no gamma corrected alpha blending

Fonts appear too thin on dark backgrounds (e.g. dark themes, terminal applications)

Fonts appear too bold on light backgrounds

Prone to color fringing when using subpixel antialiasing

OTF (e.g. Cantarell)

Stem darkening and gamma corrected alpha blending (this is how it is done on macOS and Windows)

Fonts look nice on both light and dark backgrounds

Color fringing is not an issue.

**Comment by tonsky** [comment]
Interesting! Do you have any docs that confirm that the file extension is the primary cause of this?

**Comment by taprobane99** [comment]
This is the doc from the qt foundation confirming that only otf's are treated this way

"Enabled stem-darkening and gamma-correction on OpenType fonts on platforms that use FreeType, if supported."

https://doc.qt.io/qt-5/whatsnew59.html

I am not an expert, but my understanding is that a .otf file can contain .ttf or .otf, but not the reverse. It's not the extension that's important, but that the font has to be OpenType in the first place. Is Fira Code an otf font?

**Comment by taprobane99** [comment]
Also "The correct way of rendering a glyph image on a surface is to alpha blend it onto the surface in linear space and then apply gamma correction to translate the linear coverage map to something that is correct for our screens.1 No toolkit in the Linux ecosystem does it by default, even though Qt5 and Skia can and will do it on other platforms. Windows and Mac OS X do it natively. "

https://www.freetype.org/freetype2/docs/text-rendering-general.html

I think it is turned on in more recent versions of KDE Plasma.

**Comment by tonsky** [comment]
I am confused as well, but according to this: https://github.com/tonsky/FiraCode/issues/939#issuecomment-640757377 yes, .ttf has opentype font, but truetype outlines and truetype container.

Can you confirm that when you switch between otf/ttf from e.g. https://github.com/tonsky/FiraCode/releases/tag/4 it turns gamma correction on/off? Maybe attach some screenshots?

**Comment by taprobane99** [comment]
Hi. Yes a definite difference. Tested with v4. Look how much darker the .ttf is [2nd image]!

![otf](https://user-images.githubusercontent.com/57266492/117288965-fdeb8c80-ae63-11eb-8e7a-4926c930184c.png)
![ttf](https://user-images.githubusercontent.com/57266492/117288970-ff1cb980-ae63-11eb-90ff-f028fb0c7ff2.png)

**Comment by taprobane99** [comment]
![otf](https://user-images.githubusercontent.com/57266492/117289721-d77a2100-ae64-11eb-8a7a-7243714ac1e6.png)
![ttf](https://user-images.githubusercontent.com/57266492/117289726-d8ab4e00-ae64-11eb-9935-99ac9761f7a4.png)

zoomed in. ttf second

**Comment by tonsky** [comment]
Interesting! Can you try it on the latest version too, please (attached)? Just to confirm that file extension is the trick

[Fira Code v6.zip](https://github.com/tonsky/FiraCode/files/6435813/Fira.Code.v6.zip)

**Comment by taprobane99** [comment]
![otf2](https://user-images.githubusercontent.com/57266492/117340367-b4696480-ae98-11eb-8347-8e0e70458051.png)
![ttf2](https://user-images.githubusercontent.com/57266492/117340373-b59a9180-ae98-11eb-8341-950f90dfd43d.png)

ttf 2nd. same thing. blacker/harsher blending with .ttf

**Comment by kenmcd** [comment]
FiraCode OTF-TT files have extensive hinting.
Of course they look darker than some Freetype canned rendering for OTF-PS files.
There is no "defect" in FiraCode fonts which needs to be fixed here.
It is just different. Just like the rendering on the Mac is just different.
Your personal preference for the minor differences resulting from a different rendering engine is not a reason to resurrect the OTF-PS files - and all of the other baggage that comes with it.

**Comment by taprobane99** [comment]
I have hinting turned off so there is no auto-hinting above. It is darker because it is incorrectly blended to the background.

Alpha blended and gamma corrected rendering is the correct method. It is used in Windows and OS X for both .ttf and .otf. Especially if you have a non-white background, or non-white text, then you just end up with an uneven mess without it. Unfortunately Linux support is limited to .otf

Screenshots are a poor way of showing what I am talking about, but there is a definite difference switching between the two formats. I attach photos of my 4K screen with a solarised background theme. It will be even worse on a 1080p screen.

I'm sure many Linux users will be using Fira Code with coloured or black background, in which case they are currently experiencing an inferior rendering of it. Look at the details lost in the letters i , r, and g in the ttf.

![otf](https://user-images.githubusercontent.com/57266492/117361826-6cefd200-aeb2-11eb-9ac3-5365779411e5.jpg)

![ttf](https://user-images.githubusercontent.com/57266492/117361835-6feac280-aeb2-11eb-846c-8375ef3e6c18.jpg)

It will be shame if you cannot fix this.

**Comment by tonsky** [comment]
Ok, (hopefully) last thing so that we get to bottom of this. Can you compare these two for me? I turned off hinting in both, so that we can make sure it’s the file format and not anything else

[Fira Code v6 unhinted.zip](https://github.com/tonsky/FiraCode/files/6442272/Fira.Code.v6.unhinted.zip)

P.S. is your primary problem with TTF its width? Have you tried Retina weight? Does it work better for you?

**Comment by taprobane99** [comment]
![otfunhinted](https://user-images.githubusercontent.com/57266492/117550213-fa5c2f00-b036-11eb-96b8-478d58183143.jpg)
![ttfunhinted](https://user-images.githubusercontent.com/57266492/117550218-fd571f80-b036-11eb-97c8-0a2cf4947780.jpg)

Photos of unhinted font (ttf second). Again the .ttf is generally less evenly rendered and there is a loss of small details. It's hard to convey this in photos, but it is obvious when viewing directly. It doesn't get better with other weights.

None of this is surprising. It's just that Freetype currently uses Adobe's CFF high quality rendering engine for .otf which includes the features mentioned earlier, and a less sophisticated engine for .ttf.

**Comment by HanabishiRecca** [comment]
> so that we can make sure it’s the file format and not anything else

This is called Stem Darkening, a FreeType feature which work only with OpenType/CFF (.otf).
https://freetype.org/freetype2/docs/hinting/text-rendering-general.html

**Comment by AchillesBoi** [comment]
> This is called Stem Darkening, a FreeType feature which work only with OpenType/CFF (.otf) fonts.
> https://freetype.org/freetype2/docs/hinting/text-rendering-general.html
> 
> One of the reasons why otf is preferred on Linux.

Hi there @HanabishiRecca, stranger passing by. I believe stem darkening is also available for TTF through AutoFitter. I have an environment variable that enables stem darkening system-wide for all fonts including OTF and TTF and it works:

`FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0"`

Add this to `/etc/environment` and restart the computer.

**Comment by cdock1029** [comment]
> Interesting! Can you try it on the latest version too, please (attached)? Just to confirm that file extension is the trick
> 
> [Fira Code v6.zip](https://github.com/tonsky/FiraCode/files/6435813/Fira.Code.v6.zip)
@tonsky 
Just to add feedback, @taprobane99  insights on this has led me to try to replace as many .ttf fonts with .otf on KDE as I can. To me, .otf looks much better:

TTF
![.ttf](https://github.com/tonsky/FiraCode/assets/802586/becc6905-3cf4-4c71-987b-cd1b0f991206)

OTF
![.otf](https://github.com/tonsky/FiraCode/assets/802586/ef205c6f-387b-4da7-afa3-6a05699f4ff2)

**Comment by tonsky** [comment]
@cdock1029 this must be two different weights. No way TTF and OTF look that different

**Comment by HanabishiRecca** [comment]
> No way TTF and OTF look that different

They do, as already was shown multiple times in previous comments. End result depends on values from [`cff:darkening-parameters`](https://freetype.org/freetype2/docs/reference/ft2-properties.html#darkening-parameters).

But the main point here was that **freetype's stem darkening does not work with TTF at all**. So OTF variants can be useful for users.

**Comment by tonsky** [comment]
Okay I see

**Comment by cdock1029** [comment]
> @cdock1029 this must be two different weights. No way TTF and OTF look that different

It's surprising isn't it? Makes you wonder why this isn't more understood and why at least for say hiDPI setups OTF font's aren't made available within repos for KDE distros. It's rather annoying honestly given how divergent the rendering is.

openSUSE switched Noto to OTF and many hated it as it was blurry for low dpi so they reverted. Would be nice to have choice of either without having to override all the default package fonts. Probably there are some tweaks or subtle details here but for my setup I like the OTF better.

https://www.reddit.com/r/openSUSE/comments/uxphgr/after_the_update_the_notosans_font_became_bolder/ 

https://bugzilla.opensuse.org/show_bug.cgi?id=1199938

**Comment by HanabishiRecca** [comment]
> for KDE distros

Btw, I don't know why this topic is so fixated on KDE. This is a whole Linux-wide issue. Basically everything on Linux uses FreeType for font rendering.

**Comment by tonsky** [comment]
Wait these links suggest that .otf is blurry and lacks hinting, but ttf was good. Fira Code has TTF (good one)

**Comment by cdock1029** [comment]
> Wait these links suggest that .otf is blurry and lacks hinting, but ttf was good. Fira Code has TTF (good one)

For low dpi screens that require strong hinting. If you use a 4k or better screen OTF will be better.

**Comment by HanabishiRecca** [comment]
This is a matter of preference. Stem darkening generally makes fonts softer and bolder.
Again, consider reading the actual technical info instead of random rants: https://freetype.org/freetype2/docs/hinting/text-rendering-general.html
(The link I already posted above back in 2022, which seemingly you did no bother to read.)

Btw, this is a Mac feature initially. They also disable hinting and use grayscale antialiasing (instead of subpixel). Which does look blurry on regular low res monitors (FullHD and below), but looks great on HiDPI monitors.

But again, matter of preference.

**Comment by cdock1029** [comment]
Agree don't take my word for it or anyone else's.. and as evidenced, technical arguments maybe aren't convincing, best to just try it yourself and see.

**Comment by HanabishiRecca** [comment]
Btw, for anyone who wants to convert arbitrary fonts from TTF to OTF, you could do the following:

1. Install **FontForge** (usually it is a `fontforge` package in your distro's repo).
2. Place your `.ttf` fontset into a directory and run this script in it:

```sh
for f in *.ttf; do
    fontforge -lang=ff -c 'Open($1); Generate($2); Close();' "${f}" "${f%.ttf}.otf"
done
```

That's it. You will get `.otf` copy of every font in the directory.

**Comment by HanabishiRecca** [comment]
> Is there nothing lost in translation with this technique, same as building OTF by itself?

Well, that's complicated. TTF and OTF have major format differences.
But I think it is not so different from building OTF directly. Especially if you disable hinting. At least I can't spot any difference with a naked eye.

**Comment by tonsky** [comment]
So

- TTF does hinting, but not stem darkening, best for low-dpi screens
- OTF does no hinting, but does stem darkening, best for hi-dpi screens

Is that an accurate summary?

**Comment by HanabishiRecca** [comment]
No. OTF do support hinting. And stem darkening can be disabled globally for everyone who does not like it.

**Comment by HanabishiRecca** [comment]
Well yeah, TrueType is definitely preferred for Windows as it is a Microsoft's own technology. I won't be surprised if OTF rasterizer in Windows is an afterthought.

So there are no reasons not to provide all TTF/OTF/WOFF(2) as it is kinda a standard. See [Source Code Pro](https://github.com/adobe-fonts/source-code-pro/releases) for example.

**Comment by xalt7x** [comment]
@HanabishiRecca 
> >> This is called Stem Darkening, a FreeType feature which work only with OpenType/CFF (.otf) fonts.
>>I believe stem darkening is also available for TTF through AutoFitter. I have an environment variable that enables stem darkening system-wide for all fonts including OTF and TTF and it works:
> >
> `FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0"`
>> 
>> Add this to `/etc/environment` and restart the computer.
>
> Unfortunately it does not work for me. With the variable set, difference is still very noticable:
> 
> ![ttf](https://user-images.githubusercontent.com/13597663/226713771-3ac57ed4-4de0-4c2f-a674-ca97890d0759.png) - TTF ![otf](https://user-images.githubusercontent.com/13597663/226713794-73e621f0-996e-4cd9-9e9d-08d8e3b5137b.png) - OTF

Well, according to the FreeType [documentation](https://freetype.org/freetype2/docs/reference/ft2-auto_hinter.html):
> auto-hinter's module name is ‘autofitter’ for historical reasons.

So I guess, autohint need to be explicitly enabled to see results with stem-darkening.
The quick way to test is to apply globally
`sudo ln -s /usr/share/fontconfig/conf.avail/10-autohint.conf /etc/fonts/conf.d`

In case that works well, consider removing file (because it will likely bring regressions for other fonts/applications)
`sudo rm  /etc/fonts/conf.d/10-autohint.conf`

and creating a [separate font config](https://fedoraproject.org/wiki/Features/FontconfigEnableAutohinting#Detailed_Description) 
`sudo nano  /etc/fonts/conf.d/99-fira-code.conf`
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
   <match target="font">
     <test name="family" compare="eq" ignore-blanks="true"><string>Fira Code</string></test>
     <edit name="autohint" mode="assign"><bool>true</bool></edit>
   </match>
</fontconfig>
```

**Comment by HanabishiRecca** [comment]
> So, I guess, "autohint" needs to be explicitly enabled to have "stem-darkening" with TTF.

Can you guys actually test your advices yourself instead of guessing? I tried that all already - it does not work.

> The quick way to test is to apply globally

I'm fully aware how to deal with fontconfig.

**Comment by HanabishiRecca** [comment]
Here is the test setup.

`fonts.conf`:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <match target="font">
        <edit name="hinting" mode="assign">
            <bool>true</bool>
        </edit>
        <edit name="hintstyle" mode="assign">
            <const>hintslight</const>
        </edit>
        <edit name="autohint" mode="assign">
            <bool>true</bool>
        </edit>
    </match>
</fontconfig>

```

Freetype environment settings:
(set for all modules just in case, intentionally high values to pronounce the effect)
```
export FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0 cff:darkening-parameters=0,500,0,500,0,500,0,500 autofitter:darkening-parameters=0,500,0,500,0,500,0,500 type1:darkening-parameters=0,500,0,500,0,500,0,500 t1cid:darkening-parameters=0,500,0,500,0,500,0,500"
```

Results:

**TTF**
![FiraCode-ttf](https://github.com/tonsky/FiraCode/assets/13597663/744b121b-ca82-4407-aca9-521de79f61ec)

**OTF**
![FiraCode-otf](https://github.com/tonsky/FiraCode/assets/13597663/1ae2e2f1-e925-42de-bad4-97c1a813ff74)

**YES** - this is the same font with the same weight - Fira Code Regular.
