### ISSUE TITLE
Arbitrary-long arrows not working

### ISSUE THREAD

**Issue by YouMe2** [tonsky/FiraCode#1234]
Arrows and other ligatures of length 2 to 3 work. However, nothing longer does in Atom (or Gedit) on Ubuntu 20.04

Example:
![image](https://user-images.githubusercontent.com/23223308/117446807-ec29e800-af3c-11eb-8230-9d022d693ca7.png)

Might be conected to or be part of the larger issue #259 ?

**Comment by wopian** [comment]
What editor are they not working in?

If it's Visual Studio (not VSC), then the bug preventing these ligatures from being rendered is still unresolved.

**Comment by YouMe2** [comment]
Atom and Gedit were the ones. (Ubuntu 20.04)

**Comment by tonsky** [comment]
Atom:

<img width="363" alt="Screenshot 2021-05-07 at 16 16 27" src="https://user-images.githubusercontent.com/285292/117463106-99a5f700-af4f-11eb-93c2-08ee1dca8348.png">

It’s most likely that syntax highlighting prevents these ligatures from forming.

As for GEdit, I can’t test it, but consider reporting to their repo

**Comment by doomgutt** [comment]
Hey all, sorry to necromance an issue, I'm also not getting arbitrary long arrows. I'm running Ubuntu 20.04 and I've install Fira Code via `sudo apt install fonts-firacode`. I've tried this on gedit, VSCode and Obsidian. I get ligature arrows of length 2 and 3 but no more.

Thanks!

Screenshot:
[Obsidian top left, VSCode right, Gedit bottom]
![image](https://user-images.githubusercontent.com/67280562/177425179-8446c0c1-2787-4321-ac59-6d9e6719f182.png)

**Comment by tonsky** [comment]
Check font version?

**Comment by doomgutt** [comment]
Hey, think you're might be right, it might be a version problem. But I'm not sure what I did wrong in the installation. I'll look into it some more.

### 1
with `sudo apt-get upgrade fonts-firacode`

![image](https://user-images.githubusercontent.com/67280562/177529950-c96921a8-7f81-4ea4-99f6-4db1766a9037.png)

### 2
![image](https://user-images.githubusercontent.com/67280562/177530001-b95aab81-93e6-4ac2-8528-d712c5ae1bd8.png)

**Comment by doomgutt** [comment]
Gotcha, thanks a lot!
