### ISSUE TITLE
Adding terminology to supported/nonsupported terminals list in README.md

### ISSUE THREAD

**Issue by juippis** [tonsky/FiraCode#1236]
Hey, 

how can I confirm whether terminology, https://www.enlightenment.org/about-terminology, works or not with this font? If I compare (some) glyphs with gnome-terminal, terminology resizes them correctly to match your font size, while gnome-terminal doesn't. 

(I'd also appreciate if someone else more knowledgeable about it could test it).

I can make a PR adding it if someone explains a simple procedure to test it.

**Comment by alexeyten** [comment]
No, it doesn’t 
https://phab.enlightenment.org/T8232
