### ISSUE TITLE
FiraCode Regular not display fully on Windows

### ISSUE THREAD

**Issue by xubury** [tonsky/FiraCode#1240]
Using FiraCode Mono, some characters are not rendered fully like the 'd' in 'end'. And it only happens on windows.
Windows:
![微信截图_20210514114431](https://user-images.githubusercontent.com/46261364/118218587-534e1c00-b4aa-11eb-8484-58b892751101.png)
Linux:
![Screenshot_20210514_105550](https://user-images.githubusercontent.com/46261364/118218583-51845880-b4aa-11eb-9d2f-23548717f7d3.png)

**Comment by tonsky** [comment]
I wish I could help you there, but it’s an editor issue most likely. Fira Code does not have italics, so what you see is editor-generated. Try reporting to their bug tracker
