### ISSUE TITLE
Wrong character in Greek keyboard

### ISSUE THREAD

**Issue by MrKyr** [tonsky/FiraCode#1248]
The font is working well with Greek keyboard except letter `π`.
![firacode-fix-letter](https://user-images.githubusercontent.com/15102189/120532612-82401980-c3e8-11eb-918f-8e5754afffbd.png)

**Comment by tonsky** [comment]
Weird, should look like this:

<img width="1242" alt="Screenshot 2021-06-03 at 13 28 49" src="https://user-images.githubusercontent.com/285292/120637874-bad70600-c46f-11eb-80c6-1ace91b0c784.png">

<img width="1533" alt="Screenshot 2021-06-03 at 13 29 16" src="https://user-images.githubusercontent.com/285292/120637919-c4606e00-c46f-11eb-8bf1-8155fa43e51f.png">

Either you are not using Fira Code, or your editor replaces pi with a different font for an unknown reason

**Comment by MrKyr** [comment]
Problem seems to relies on _xterm_,  
`π` is rendered incorectly as a graphical symbol with other fonts too, not only _Fira Code_

But it is correctly rendered with _DejaVu Sans Mono_ as an example.

This bug report [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931305 ) describes the problem thoroughly
which in mine case does not solve the problem.

Eventually I can't understand where the problem relies, _xterm_ or in some specific fonts like _Fira Code_
