### ISSUE TITLE
Request for /= vs !=

### ISSUE THREAD

**Issue by Fresheyeball** [tonsky/FiraCode#125]
So in Fira Code `!=` gets you the not equals ligature, but in many of my favorite languages `/=` means not equals. And while there is a nice ligature for `/=`, it would be nice to get the not equals ligature for `/=`.

**Comment by weavejester** [comment]
Isn't `/=` used a lot to mean "divide and assign"?

**Comment by Fresheyeball** [comment]
In most languages, yes != is "divide and assign", but in some its "not equal to". IE Haskell, which already has great Fira support.

**Comment by weavejester** [comment]
Right, but that means that in those languages, a `/=` would be indistinguishable from `!=`.

**Comment by Fresheyeball** [comment]
I'm not sure what options are really possible. But one I know for sure, would be to release an alternative version of Fira with ligature configurations relative to the meaning of some languages. There are actually several languages that use `/=` to mean not equals.

**Comment by bootmii** [comment]
The /= ligature is ambiguous about its purpose and distinguishes it from !=. Let's keep it that way.

**Comment by HolgerPeters** [comment]
Indeed, ambiguity must be avoided at all costs. I think in C `a /= b != c` is a valid statement, it would be terrible if `/=` was rendered as `!=` (and semantically wrong).

A similar case could be made for `<>` which also is "not-equal" in some languages.

**Comment by Fresheyeball** [comment]
If the `/=` ligature is to stay the same because its ambiguous, I'd argue that `!=` should NOT be a not-equals sign, as it may have another meaning. I further would argue that the not-equals ligature is the **only** ligature in fira that has the problem as the result has a semantic meaning.

**Comment by weavejester** [comment]
> I'd argue that `!=` should NOT be a not-equals sign, as it may have another meaning.

If it does, no-one has yet raised an issue about it.

Having a FiraCode with different versions for different languages would of course be ideal, but that also sounds like a lot of work!

**Comment by Fresheyeball** [comment]
Is it really? Is it hard to make alternative builds? The glyphs already exist. Can't this be done with just config (some manifest from glyphs to utf8 or something)?

**Comment by weavejester** [comment]
It might be easier than I think. Maybe try your hand at it and open a PR?

**Comment by Fresheyeball** [comment]
Fair enough, if I can do the work. Would you mind pointing me in the right direction? How is fira built? What tooks will I need?

**Comment by tomByrer** [comment]
? [gen_calt.clj](https://github.com/tonsky/FiraCode/blob/master/gen_calt.clj)

**Comment by tonsky** [comment]
Fira is built with Glyphs 2 app. I’m working on stylistic sets for next
version, so this problem will be sovled by proper configuration in
style.css of your editor

**Comment by Fresheyeball** [comment]
Well shut my mouth can call me a series of mildly derogatory names. Thats great news! I'm going to close this issue, since the desired behavior is already on the roadmap!

**Comment by Fresheyeball** [comment]
Any progress on this?
