### ISSUE TITLE
r glyph stands out as a sore thumb

### ISSUE THREAD

**Issue by hramrach** [tonsky/FiraCode#1250]
After reading how FiraCode aligns letters nicely seeing this is real turn off. I understand that this is the result of the base font chosen and it is unlikely to be fixed here but it sucks all the same.

![term2](https://user-images.githubusercontent.com/787652/121493513-30932280-c9d8-11eb-80c4-43223a50195a.png)
![term](https://user-images.githubusercontent.com/787652/121493532-36890380-c9d8-11eb-99a9-db8920d1c829.png)

**Comment by hramrach** [comment]
FTR the baseline comparison I use is Deja Vu Sans Mono which was the first usable monospace vector font for Linux.

It is still very usable today and while many fonts may be better for a specific use case I have not found anything that matches its clarity and balance for general use.

**Comment by wopian** [comment]
You can change the `r` to a typical sans-serif `r` with a stylistic set - `ss01`

https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

**Comment by hramrach** [comment]
Thanks for the answer. Using stylistic set I can get sane r glyph and nicer @ and & glyphs but then ligatures don't work for some reason.

Also while the @ and & alternate glyphs might be a matter of preference the r glyph is clearly out of place. For a font that aims at tuning glyphs to fit together this does not look like an acceptable default to me.

**Comment by RubenVerg** [comment]
If you're using VSCode, then for some reason stylistic sets and ligatures are mutually exclusive, since they use the same setting key.

**Comment by alexeyten** [comment]
> If you're using VSCode, then for some reason stylistic sets and ligatures are mutually exclusive, since they use the same setting key.

Thats strange. Works for me

![image](https://user-images.githubusercontent.com/44377/121514962-495e0100-c9f5-11eb-97e0-a2dd88ad9cf3.png)

**Comment by tonsky** [comment]
`r` is that shape because otherwise it’s too similar to `i`, this was decision made in way back in Fira Mono. Fira Code has stylistic set with more traditional `r` for that case
