### ISSUE TITLE
Ligatures in Sublime 4107 only work in Plain Text

### ISSUE THREAD

**Issue by Guatama** [tonsky/FiraCode#1257]
It's kinda weird. For now on Sublime 4107, ligatures doesn't work in Python and SQL syntax (in many other and in plain text - everything ok).

Pref - nothing fancy. It's very annoying, because Py and SQL my main tools at work...
`{
    "font_face": "Fira Code",
	"font_options":
	[
		"subpixel_antialias",
		"gray_antialias"
	],
    "indent_guide_options": [ "draw_normal", "draw_active"],
	"font_size": 17,
	"ignored_packages":
	[
		"Vintage",
	],
	"color_scheme": "Packages/Materialize/schemes/Material Solarized Light.tmTheme",
	"theme": "Material Solarized Light.sublime-theme",
}
`

**Comment by Guatama** [comment]
UPD: some ligatures like >=, <= works. But others - ===, =>, -> and etc don't

**Comment by tonsky** [comment]
Please report to Sublime
