### ISSUE TITLE
.= ligature makes dot invisible in smaller sizes

### ISSUE THREAD

**Issue by NiklasBr** [tonsky/FiraCode#1259]
On smaller sizes in Firefox 89:

![image](https://user-images.githubusercontent.com/279826/123272263-e47ccd80-d501-11eb-960b-dc7a71d2da86.png)

Zoomed one step:

![image](https://user-images.githubusercontent.com/279826/123272424-0413f600-d502-11eb-8e67-69190aedc419.png)

**Comment by tonsky** [comment]
Thanks! Probably caused by autohinting

**Comment by tonsky** [comment]
Moved it to cv32 in v6, disabled by default
