### ISSUE TITLE
Wrong ligatures

### ISSUE THREAD

**Issue by uninhm** [tonsky/FiraCode#1265]
I get wrong ligatures for: `>>=`, `=<<` and `<=>`

Expected (FiraCode example, any other ligature would be acceptable):
![image](https://user-images.githubusercontent.com/62044675/126875189-32a7e378-e903-4bcc-9304-b53fc2b408e2.png)

Behavior:
![image](https://user-images.githubusercontent.com/62044675/126875203-5ea3efcf-916c-4446-b76b-27027947df29.png)

The last one is the worst, because it's really confusing

**Comment by tonsky** [comment]
Might be syntax highlighting interferring. Try setting syntax to Plain Text?

**Comment by uninhm** [comment]
@tonsky I get the same

**Comment by tonsky** [comment]
What editor/OS are you using?

**Comment by uninhm** [comment]
> What editor/OS are you using?

OMG I'm dumb, nevermind, I mixed up repos, the issue wasn't here. I'm really sorry.
