### ISSUE TITLE
Swap "Leftwards" with "Rightwards" labels in README arrows image

### ISSUE THREAD

**Issue by jaysonvirissimo** [tonsky/FiraCode#1267]
It currently appears like these sections are mislabelled:
![Screen Shot 2021-07-27 at 12 49 23 PM](https://user-images.githubusercontent.com/1292454/127219190-4e77d439-c63f-47cc-ac02-92c3e9ad46ab.png)
That image is linked from the README [here](https://github.com/tonsky/FiraCode/blame/master/README.md#L37).

**Comment by tonsky** [comment]
Haha thank you! Will fix
