### ISSUE TITLE
Add Ligature For Other Arrows

### ISSUE THREAD

**Issue by noorwachid** [tonsky/FiraCode#1268]
```
>>-->
>>->
-->
```
I made a markup language that has a bunch of arrows. you can check it here: [Gularen](https://github.com/NoorWachid/Gularen)
Rejection is fine but please reply.

**Comment by tonsky** [comment]
They should be already in the font:

<img width="115" alt="Screenshot 2021-08-03 at 11 50 47" src="https://user-images.githubusercontent.com/285292/127995912-7c26c35b-0c64-4971-a02d-512c3524fa22.png">
