### ISSUE TITLE
Konsole and Kate on KDE4

### ISSUE THREAD

**Issue by iandoug** [tonsky/FiraCode#127]
hi
Just to report that Fira Code works fine for me on KDE 4, in both Konsole and Kate ....
Thanks for the font :-)

**Comment by tonsky** [comment]
Thanks for reporting! Updated the README

**Comment by iandoug** [comment]
Hi
Sorry... looks like I was wrong. The ligatures certainly work in the version I had before, but since installing current 1.102, they no longer work. I don't know if it is fixable ... should be, surely?
As tested in Kate.

**Comment by tonsky** [comment]
@iandoug can I ask to you to fix the Readme in a PR? It’s hard for me to reconstruct context of what works where with all these reports coming in different places.

**Comment by iandoug** [comment]
On Monday 14 March 2016 01:44:53 Nikita Prokopov wrote:

> @iandoug can I ask to you to fix the Readme in a PR? It’s hard for me to
> reconstruct context of what works where with all these reports coming in
> different places.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tonsky/FiraCode/issues/127#issuecomment-196206489

Sorry for long delay in replying ... I switched to KDE Plasma (aka KDE 5) as 4 
was deprecated by upstream.

Current version of Fira Code and Plasma does not seem to work (in Kate editor 
and Terminal). Pity.

Also Plasma has some issue installing/deleting fonts, I need to reboot between 
attempts because the font installer hangs.

Will see if I can run a test with the old version of Fira Code and Plasma.

Will then update the Readme.

Cheers, Ian

-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by iandoug** [comment]
On Monday 14 March 2016 01:44:53 Nikita Prokopov wrote:

> @iandoug can I ask to you to fix the Readme in a PR? It’s hard for me to
> reconstruct context of what works where with all these reports coming in
> different places.

If I give you this, can you determine which version? Or is there a way for me 
to determince version?

131848 Oct 18  2015 FiraCode-Regular.otf

thanks, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by tonsky** [comment]
There’s usually font version in font file, if you can open it with something that shows font properties.
