### ISSUE TITLE
Does the newest version of FiraCode support Emoji which version is 13.1?

### ISSUE THREAD

**Issue by jiangjianshan** [tonsky/FiraCode#1278]
Hello, 

I'm using FiraCode for my laptop. Does the newest version of FiraCode support Emoji which is 13.1, where you can found them on http://www.unicode.org/emoji/charts/full-emoji-list.html?

**Comment by RubenVerg** [comment]
there is no emoji support afaik, it will just fall back to the system emoji font (for example Segoe UI Emoji/Symbol on recent Windows)

**Comment by tonsky** [comment]
@RubenVerg is correct. Emoji are not usually included in the font, instead, a separate system-wide font is used.
