### ISSUE TITLE
Confusing weight name: "Retina" font weight

### ISSUE THREAD

**Issue by soc** [tonsky/FiraCode#128]
The weight "Retina" seems to be between Regular and Medium, shouldn't this weight therefore be called "Regular", and Regular should be renamed to "Book"?

**Comment by tonsky** [comment]
Well, Regular comes straight from Fira Mono, I don’t want to change that. Also, “Book” sounds old-fashioned for a font which main purpose is to be used on a computer screen writing code. Does that causes any problems, or it’s just unusual for a typographic eye?

**Comment by soc** [comment]
Hi @tonsky, I think it's unusual ... whenever I heard "Retina" in a technical context before, it was related to those displays from Apple. I wondered whether the Retina weight was maybe twice the size or something in the beginning.

I don't think it's such a big deal, don't want to waste more of your time ...

**Comment by tonsky** [comment]
Well there’s no pre-existing convention but the issue is more or less
known, e.g. https://ia.net/know-how/responsive-typography TL;DR because of
better precision regular weight looks slightly thinner on hi-res screens.
