### ISSUE TITLE
Symbol "g"

### ISSUE THREAD

**Issue by FantastPro** [tonsky/FiraCode#1280]
Hi. Sorry if this is a stupid question but can i change the symbol "g" to another without tail ? I was looking for how to change this, but I didn't find an answer
![g](https://user-images.githubusercontent.com/53366412/130328243-180b8be9-a8a2-4485-9300-89aaa20c576c.png)

**Comment by tonsky** [comment]
Will be customizable in v6

**Comment by tonsky** [comment]
You can now use cv02

<img width="325" alt="Screenshot 2021-11-29 at 15 41 21" src="https://user-images.githubusercontent.com/285292/143887897-b321e0fb-8d14-4d69-bdde-a1c513931ab8.png">
