### ISSUE TITLE
Fira Code in Google Fonts is not the latest version

### ISSUE THREAD

**Issue by wags-1314** [tonsky/FiraCode#1287]
I was trying to use Fira Code in Google Docs, as I wanted some of the ligatures. Some of the newer ligatures like the infinite arrows, and the logic ligatures do not seem to exist in the version hosted in Google Fonts.
![image](https://user-images.githubusercontent.com/19219106/132286060-914e0f11-58cd-491c-95c1-3fa8b613e28e.png)

**Comment by tonsky** [comment]
I think they have an old version, will have to check

**Comment by tonsky** [comment]
Closing in favor of #1141
