### ISSUE TITLE
Documentation: installation doesn't work on Big Sur

### ISSUE THREAD

**Issue by jpriebe** [tonsky/FiraCode#1289]
I tried following the instructions to install Fira Code on Big Sur.  I used the "select in finder, right click, and open" technique, since I don't have homebrew installed (and don't want to install homebrew just to install a font).

Font Book opened, and I was able to click the "Install Font" button.  A progress bar zipped by, and no error messages were provided.  But the font did not show up in Font Book and was not usable inside of VS Code.

I looked in ~/Library/Fonts, and the files were there.  But they just weren't usable.  I configured VS Code before I realized that the installation didn't work.  It started using some sort of Times Roman font.

I copied the files to /Library/Fonts, and both Font Book and VS Code immediately detected the fonts; Font Book added it to the list of installed fonts, and VS Code started using Fira Code without even having to restart them.  That was cool.  But something is wrong with the "Install Font" action in Font Book. 

Documentation should be updated, probably by somebody more knowledgable than I about the right way to do this.  Surely you shouldn't have to run `sudo cp *.ttf /Library/Fonts` to install a font on Big Sur?

**Comment by tonsky** [comment]
Thank you for reporting this, Jason! This sounds serious, if Install Font is broken it should be reported to Apple. I’d like anyone else on Big Sur to confirm this first, before we update the instruction

**Comment by NimbleArchitect** [comment]
I just installed it on Big Sur without any issues, the install font button worked ok for me
