### ISSUE TITLE
'->' is not ligaturized in Visual Studio 2019

### ISSUE THREAD

**Issue by TENX-S** [tonsky/FiraCode#1294]
![image](https://user-images.githubusercontent.com/40336192/134620736-b657af4e-9a7b-41ac-a249-226caaffd0fd.png)

I have read issue #112 , but restart does not work.

**Comment by TENX-S** [comment]
vscode is fine:
![image](https://user-images.githubusercontent.com/40336192/134621081-2025227a-40e6-4446-90a4-772ffce312d5.png)

**Comment by tonsky** [comment]
Could be syntax highlighting. Try commenting the line with `->`, see if it helps. Either way, a bug like this is better reported to the software that causes the problem
