### ISSUE TITLE
Cursive font it's cut (just a little)

### ISSUE THREAD

**Issue by victorbombella** [tonsky/FiraCode#1296]
I've notice that in some cases, when the editor uses cursive font, the last letter gets cut (well, just a little):

![firacode_cursive](https://user-images.githubusercontent.com/77814145/135146542-3372d61a-5b47-493d-bb2f-b10e0532852c.png)
#

As you can see, the last "n" in "main" seems to be cut by the left bracket.

**Comment by tonsky** [comment]
Fira Code does not include italics, so editor have to fake it by transforming existing letters. The rendering is an artifact of that. Better report this to the editor in question
