### ISSUE TITLE
Solid line antialiasing artifacts

### ISSUE THREAD

**Issue by mikehdt** [tonsky/FiraCode#1298]
Hi, using Fira 5.2 with VScode on MacOS 10.15 (Catalina), I notice that lines made from multiple hyphens seem to have some strange possible overlap which creates these little rhythmic "bumps" in the anti-aliasing. This image has been scaled up 4x to emphasise the detail so it's a little blurry. However, you can see where the issues occur:
![fira-aa](https://user-images.githubusercontent.com/4432939/135782911-c3387e3b-8af5-4fc9-810f-2e648d43f215.png)

Not sure if that's just going to be a fussy system font renderer issue, although it may well be so.

**Comment by tonsky** [comment]
This is an artifact of font rendering not being perfect. Letter widths are not exact pixels, so there’ll always be either overlap or a gap. In Fira Code, we went for overlap.

**Comment by mikehdt** [comment]
Heh, figured as much. Fighting the good fight against myriad fussy font renderers (and even with MacOS choosing to inexplicably go with greyscale by default now). Will close this out, thanks 😄
