### ISSUE TITLE
Add support for ↪ character (mirror ↩)

### ISSUE THREAD

**Issue by depsterr** [tonsky/FiraCode#1307]
Hi! Really nice font but unfortunately I've ran into issues when using both the ↪ and ↩ characters in my code since firacode only supports '↩' the '↪' is drawn with a backup font which doesn't have the same character width, resulting in unaligned lines. Anyway I assume the fix is trivial as all you have to do is mirror the already drawn '↩' character.

**Comment by tonsky** [comment]
Thanks! I’ll take a look

**Comment by depsterr** [comment]
Cheers!
