### ISSUE TITLE
Is it possible to patch Fira Code Ligatures with different fonts ??

### ISSUE THREAD

**Issue by KunalTanwar** [tonsky/FiraCode#1309]
Is it possible to patch these ligatures with different fonts !? And, If yes **How can I do that?**

**Comment by tonsky** [comment]
Ligatures are drawn for the specific font to match glyph shapes, dimensions. I doubt same ligatures will fit other font

**Comment by alexeyten** [comment]
But technically it is possible.

**Comment by KunalTanwar** [comment]
they 

> But technically it is possible.
> 
> E.g. https://github.com/gaplo917/Ligatured-Hack
> 
> UPD: https://github.com/ToxicFrog/Ligaturizer

But they only support Fira Code ligatures to **v3** after **v3** @tonsky changed the entire method of drawing ligatures!!

**Comment by KunalTanwar** [comment]
> Ligatures are drawn for the specific font to match glyph shapes, dimensions. I doubt same ligatures will fit other font

I wanted to tweak the same with SF Mono. 😅
