### ISSUE TITLE
Better power/airline alignment in iTerm2?

### ISSUE THREAD

**Issue by landaire** [tonsky/FiraCode#131]
I started using vim-airline recently and after tinkering with the vertical alignment and sizes with the font I finally got the `>` block on the left aligned pretty well but the `<` block on the right is not aligned as wanted.

Here's a picture of the issue
<img width="564" alt="screen shot 2016-02-09 at 12 27 30" src="https://cloud.githubusercontent.com/assets/1313522/12929647/bd4e9eee-cf28-11e5-8bde-4e94713cbab5.png">

Is there any way to fix this? To achieve this I had to set my ASCII font to Fira Code Retina size 11, my non-ascii font to Fira Code Retina size 13 and adjust the vertical alignment to about 1.15:

![screen shot 2016-02-09 at 12 30 41](https://cloud.githubusercontent.com/assets/1313522/12929685/f19d0f1e-cf28-11e5-862f-af92d0d4bb69.png)

**Comment by tonsky** [comment]
Looks like no, no easy way to fix it. Powerline is a hack, so expect it to behave like a hack

Related: https://github.com/powerline/fonts/issues/31

> There's just too many factors (different ways of calculating font metrics, different operating systems, different antialiasing technologies, different fonts) to reliably patch a font for every single combination of these factors. You can patch it manually in fontforge or ignore the issue until a fix is found

**Comment by pencilcheck** [comment]
Hack has a long thread of correcting the arrow bit by bit. Reference: https://github.com/chrissimpkins/Hack/issues/33

Whereas Fantasque Sans Mono has perfectly aligned arrow:
https://github.com/belluzj/fantasque-sans

If Fira Code can do the same, that would be really awesome!

**Comment by tonsky** [comment]
The problem is, you can fix it for one specific OS / terminal combination but it might still be wrong for all the others. There’s no reliable way to do this properly. E.g. this is how Fantasque looks for me (OS X, Terminal.app):

<img width="675" alt="screen shot 2017-04-06 at 14 17 27" src="https://cloud.githubusercontent.com/assets/285292/24742302/f421933e-1ad3-11e7-8aa0-1dd29450856c.png">

**Comment by pencilcheck** [comment]
True, but that doesn't mean there is no way we can't make it so the at least it is adjustable to look as close as aligned properly as close as possible. FiraCode right now doesn't seems to be able to can't make it look at least ok (without gap or able to align it close to the center) even by adjusting the spacing.

Fantasque font works fine almost out of box on iTerm2 though.

I also noticed that PragmataPro with powerline patch looks pretty good on Terminal.app out of box, it look fine after minor spacing adjustment on iTerm2.

Perhaps you should look into PragmataPro and see how they made it so it look good on both iterm2 and terminal

**Comment by pencilcheck** [comment]
And btw, here is another font that the arrow looks aligned on both terminal.app and iterm out of box.

https://github.com/be5invis/Iosevka

**Comment by tonsky** [comment]
I wouldn’t be so sure...

<img width="747" alt="screen shot 2017-04-06 at 19 58 19" src="https://cloud.githubusercontent.com/assets/285292/24755188/6de042ae-1b03-11e7-91fd-9cd6037d7e31.png">

**Comment by pencilcheck** [comment]
Looks like that happen only in Terminal.app when you have font size smaller than 18.

It looks fine on iTerm
<img width="761" alt="screen shot 2017-04-06 at 10 39 30 am" src="https://cloud.githubusercontent.com/assets/116532/24767882/7a1aed06-1ab5-11e7-9e4e-8d904e8dd24d.png">
