### ISSUE TITLE
Why did you choose Fira Mono??

### ISSUE THREAD

**Issue by KunalTanwar** [tonsky/FiraCode#1311]
It is not an issue or a bug. Just want to ask you why did you choose `Fira Mono`. I mean there are dozens of open source `monospaced` or `programming fonts`.

**Comment by tonsky** [comment]
I liked the shape of the letters. I was a big fan of Meta back then, and then Fira came along which was very similar in spirit and also had monospaced variant. I used it for coding and when decided to add ligatures there were no question which font to use.

These days I would also consider IBM Plex Mono
