### ISSUE TITLE
Ligatures Code is not working in VSCode

### ISSUE THREAD

**Issue by KunalTanwar** [tonsky/FiraCode#1314]
First of all thank you so much for releasing **v6**. 🎉

**Settings.json**

```json
"editor.fontLigatures": "'cv01', 'cv02', 'cv10', 'cv13', 'cv18', 'cv19', 'cv20', 'cv21', 'cv22', 'cv24', 'cv23', 'cv25', 'cv28', 'cv31', 'cv32', 'ss01', 'ss02', 'ss07', 'ss08', 'ss09', 'ss10'",
```

![image](https://user-images.githubusercontent.com/77537933/143901525-09203b19-51c3-429d-b3e5-83ade94fd338.png)

and many more.

**Comment by tonsky** [comment]
Works for me 🤷‍♂️

<img width="799" alt="Screenshot 2021-11-29 at 17 24 39" src="https://user-images.githubusercontent.com/285292/143905017-0b2030ba-edc9-459a-ae78-deafa1dc4f81.png">

<img width="799" alt="Screenshot 2021-11-29 at 17 24 51" src="https://user-images.githubusercontent.com/285292/143905041-952643ca-875d-4ec5-a6a5-949090e3b235.png">

<img width="799" alt="Screenshot 2021-11-29 at 17 25 10" src="https://user-images.githubusercontent.com/285292/143905091-d2943523-fd48-43c8-ae4b-59238f2c49a1.png">

Maybe try reinstalling, reopening, rebooting? See https://github.com/tonsky/FiraCode/wiki/Troubleshooting#corrupted-font-in-intellij-on-windows

**Comment by KunalTanwar** [comment]
### Tried uninstalling the font using command line and even after reinstalling nothing changed.

![image](https://user-images.githubusercontent.com/77537933/144032368-3d28e747-1477-43cf-b1db-76f9bf37b4fa.png)

**Comment by tonsky** [comment]
Try changing syntax to plaintext?

**Comment by KunalTanwar** [comment]
**Plain Text** 

![image](https://user-images.githubusercontent.com/77537933/144039235-a45897a0-3928-44c0-bb3a-c1b35fed4a59.png)

**Comment by tonsky** [comment]
Try disabling letterSpacing?

**Comment by KunalTanwar** [comment]
> Try disabling letterSpacing?

it worked!! But why can't we enable them with letter spacing??

**Comment by tonsky** [comment]
I guess is you add extra space between letters it’s not clear what should happen to ligature which replaces multiple letters but is drawn as a single glyph

**Comment by KunalTanwar** [comment]
That means I need to remove letter spacing! 🙁 But do remember to add support for letter spacing in the next update (whenever you are going to release it) 😝
