### ISSUE TITLE
Version 6.0 on windows doesn´t looks right

### ISSUE THREAD

**Issue by CheloXL** [tonsky/FiraCode#1315]
Installed v6 on windows, the following is a screenshoot of VS (using FiraCode at point 11).
![image](https://user-images.githubusercontent.com/201414/144048041-c2ee1f16-021f-4a54-bda6-cc1058877ef4.png)

Version 5 looks fine. Seems related to https://github.com/tonsky/FiraCode/issues/1075

**Comment by tonsky** [comment]
So I don’t lose it: https://forum.glyphsapp.com/t/ttfautohint-settings-to-match-glyphs-export/20891/2

**Comment by tonsky** [comment]
@CheloXL @tigerinus can you check this version please?

[Fira_Code_v6_no_info_ignore_restrictions.zip](https://github.com/tonsky/FiraCode/files/7650641/Fira_Code_v6_no_info_ignore_restrictions.zip)

**Comment by CheloXL** [comment]
@tonsky Now it looks perfect!

**Comment by tonsky** [comment]
Ok, published as https://github.com/tonsky/FiraCode/releases/tag/6.1. Glad this is resolved!
