### ISSUE TITLE
Missing release note: Retina weight removed from FiraCode-VF.ttf

### ISSUE THREAD

**Issue by TBBle** [tonsky/FiraCode#1318]
I noticed when upgrading my Windows 10 boxes to Fira Code 6, the Retina instance (weight 450) disappeared.

This appears to be [intentional](https://github.com/tonsky/FiraCode/commit/6bf3854628f8fd0450cb65a141350b991cdd3ed3#diff-3742363f7fdde2532bcc5dadf01df3392409d29b0f5ba350d14c1dcb1e12db76) but I don't see any mention of this change in the Release notes, and the commit itself only has "fixed variable + Retina" so it's not clear what problem was being solved by removing it.

**Comment by Songkeys** [comment]
My 'FiraCode-Retina' font got messed up after upgrading to v6. Thanks for this information. After setting it to 'FiraCode', everything works fine. I think this should be stated in the changelog.

![image](https://user-images.githubusercontent.com/22665058/144227947-7384e4f5-b77c-475b-95f9-96fe642ab1b0.png)

**Comment by tonsky** [comment]
Yeah sorry about that. Something about build pipeline really didn’t like non-standard instances in variable font, so I had to remove it. Technically, the retina weight is still there (wght=450), only the name for it is missing

**Comment by TBBle** [comment]
That makes sense. I think I'd already moved from "Fira Code Retina" to "Fira Code" + `font_weight=450` at some point, but I probably have old/legacy stuff lying around that wont' find the font.

@Songkeys I _strongly_ suspect your problem is different. Were you actually using the variable font TTF, or did you install the set of individual font files, which includes FiraCode-Retina.TTF? I certainly haven't seen any issues with weight 450 in Visual Studio Code (Windows x64) since installing v6.
![image](https://user-images.githubusercontent.com/138397/144394036-cd547d3a-c6c9-4153-8465-bdf597ad5a9e.png) 
![image](https://user-images.githubusercontent.com/138397/144394119-db767edd-17da-4b90-9dbf-9f8b9bea45b0.png)

Another thought, have you actually restarted VS Code since updating the fonts?

**Comment by Songkeys** [comment]
@TBBle 

I set my font to `'FiraCode-Retina'`. After upgrading to v6, it turned a mess. I tried **reloading vscode window** but it did not work. But thank you for your hint. I **restarted the whole vscode application** just now and it worked.

Thank you!

**Comment by tonsky** [comment]
Added to release notes, thanks!

**Comment by gigitux** [comment]
Hi,
I just updated to FiraCode Retina and I found this bug. I seem to understand that the `FiraCode-Retina` is completely removed (so we should use FiraCode + font-weight 450).

If I understand well, can I update the README? Thanks!

**Comment by tonsky** [comment]
No, it’s not removed. Here it is:

<img width="351" alt="Screenshot 2022-01-04 at 20 57 38" src="https://user-images.githubusercontent.com/285292/148116397-b188408a-bf56-49d6-9d8a-c02c1b9aea0a.png">

**Comment by gigitux** [comment]
Oh, ok!

If I try to set Fira Code Retina on VSCode, it doesn't load the font. I'm using the last version installed with brew.

**Comment by TBBle** [comment]
It's kind-of a bug that `FiraCode-Retina` ever worked as a font family name in VSCode, e.g., as seen in 
[this workaround for VSCode on Mac OS](https://github.com/Microsoft/vscode/issues/381#issuecomment-163356103) from before the `fontWeight` setting existed in VSCode at all.

So maybe the VS Code developers or Electron developers (or something in the OS X font-support) have fixed that bug now, and the current [VS Code Instructions](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions) don't work?

Those instructions on the Wiki page [were added in 2018](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions/_compare/574aa4b8bb635eeb103d31b4a58c797abb7a0dd6...ad843e1002804f27ef6eb80a2d2ac9ef76d83564) well _before_ [arbitrary numeric `fontWeight` support was added to VSCode in August 2020](https://code.visualstudio.com/updates/v1_49#_numeric-fontweight-values).

On Windows 10, using the Firacode-VF.ttf font file, 450 and 400 are clearly different:
![image](https://user-images.githubusercontent.com/138397/148217941-6105606e-b938-4000-8f0a-1b1b32dbaeea.png)

@gigitux, if you can confirm `fontWeight: 450` works correctly on OS X, and it seems to be working with separate TTF files, then it makes sense to update the Wiki, since it's working for me on Windows 10 with the single variable-weight file, so presumably we don't need this font-name workaround anymore.

**Comment by tonsky** [comment]
@TBBle I guess it depends on which files you have installed. If you install normal TTFs, FiraCode-Retina still works
<img width="891" alt="Screenshot 2022-01-05 at 16 06 14" src="https://user-images.githubusercontent.com/285292/148240346-13728ed8-bdcc-4c00-8323-710d0724d1d8.png">
<img width="891" alt="Screenshot 2022-01-05 at 16 06 21" src="https://user-images.githubusercontent.com/285292/148240360-700044c8-4772-47b8-ac5d-5624f61490ae.png">
<img width="302" alt="Screenshot 2022-01-05 at 16 05 51" src="https://user-images.githubusercontent.com/285292/148240372-f1bce76d-6b67-4143-a5b5-5824303c96a1.png">

**Comment by TBBle** [comment]
But does `fontWeight: 450` work with separate files on OS X? If it does, I think it would be better to have that in the instructions, so that the instructions work for both separate files and the variable-weight font file; and also to be consistent with the other weights on the page.

**Comment by tonsky** [comment]
> But does fontWeight: 450 work with separate files on OS X?

No.

> If it does, I think it would be better to have that in the instructions, so that the instructions work for both separate files and the variable-weight font file; and also to be consistent with the other weights on the page.

Which instruction are you referring to? This https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions seems to explain that already.

Also, I think no instruction ever suggested to install variable font. Variable was meant for advanced users who know why they need it and how to handle it (as far as I know, variable font support is not great in general yet)

**Comment by TBBle** [comment]
Those instructions don't say that `fontWeight: 450` will work with the variable-weight font, that's what I was referring to. But if that doesn't work with separated font files, and using the font instance name as `fontFamily` doesn't work with the variable font (any more), then we can't unify the instructions to cover both cases after all.

**Comment by gigitux** [comment]
>I guess it depends on which files you have installed. If you install normal TTFs, FiraCode-Retina still works

First of all thanks for your great answers. To be honest, what I did, it is just upgrade the package with brew. After the upgrade I can't use anymore FiraCode-Retina on VSCode on OSX. So for now, I'm using FiraCode with font-weight 450.§

[The VSCode instruction](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions) doesn't have this information. I think that it can be useful to other users.

**Comment by TBBle** [comment]
And as it turns out, the `brew` install _does_ use the variable-weight font since https://github.com/Homebrew/homebrew-cask-fonts/pull/5211 (slightly after the Fira Code 6 release). So that's probably the _actual_ change that bit @gigatux.

@tonsky You might want to follow up with that change, and suggest they revert it, if you do not feel it's ready-to-go for general consumption.

**Comment by gigatux** [comment]
@gigitux I think the above comment from @TBBle was meant for you.

**Comment by TBBle** [comment]
Ooops, thank you. >_<
