### ISSUE TITLE
Fedora repository in distr/README.txt

### ISSUE THREAD

**Issue by Martin1887** [tonsky/FiraCode#1319]
In the `README.txt` file of the zip it is specified a COPR repository to install in Fedora but the font is available as `fira-code-fonts.noarch` in the official Fedora repository (version 5.2.3 currently but I guess it will be updated soon).

Regards.

**Comment by tonsky** [comment]
This is what it says right now:

```
A Fedora copr repository is available: https://copr.fedorainfracloud.org/coprs/evana/fira-code-fonts/. Package sources https://gitlab.com/evana11/fira-code-fonts-fedora.

To install, perform the following commands:

    dnf copr enable evana/fira-code-fonts
    dnf install fira-code-fonts
```

What should it be saying? Thanks!

**Comment by Tokariew** [comment]
For Fedora should be now only single command, similiar to Void or Gentoo:
```
dnf install fira-code-fonts
```
