### ISSUE TITLE
Please add Javascript strict comparator: !==

### ISSUE THREAD

**Issue by sladiri** [tonsky/FiraCode#132]
I like the idea to see === as a ligature in Javascript since this is the recommended method for comparison.
It would be great if there was a ligature for the strict not comparator !== as well. The current === ligature crossed out should be nice.

**Comment by tonsky** [comment]
It is there. Maybe your editor does tokenization wrong, splitting `!==` into two tokens?

**Comment by sladiri** [comment]
Thanks, my editor is VSCode, this is solved then :)
