### ISSUE TITLE
How to trigger the new shiny progress bars?

### ISSUE THREAD

**Issue by agilesteel** [tonsky/FiraCode#1324]
Hi,

I've been a Fira Code user for years so I'm not a noob. I downloaded the latest release and tried typing sth. like `[##..]` to see the new shiny progress bars but couldn't get them to work.

What are the exact requirements for it to work?

I'm on win10, vs code, fira code 6.1

PS

Fira Code is awesome!
Thanks for the hard work!

**Comment by wopian** [comment]
The program outputting the progress bars needs to use the private-range unicode characters in this picture:

![image](https://user-images.githubusercontent.com/3440094/144696997-c9a6383c-7c7c-4786-8f56-3f385b3f850a.png)

**Comment by agilesteel** [comment]
Oh, these seem to be rare though. I've seen several progress bars today which use the "regular" brackets `[`, `]`. Of course they won't render beautifully. I wonder why it was constrained as such. 😞

**Comment by agilesteel** [comment]
I just realized that you are talking about the outputting program. Well I tried vs code and windows terminal. Both didn't work. Is there a list of programs which work?

**Comment by tonsky** [comment]
These are not automatically enabled anywhere. I will try to ligaturize existing progress bars in #1183 where possible.

What v6 brings are few new characters that could be used to draw progress bars. Unlike `[##..]`, these are specifically designed for that purpose.

You can write your own program that outputs these and see them if using Fira Code. Hopefully, other fonts will join and it becomes a standard, kind of like powerline did. Then you might expect those being used in the wild.

**Comment by alexeyten** [comment]
> Hopefully, other fonts will join and it becomes a standard, kind of like powerline did.

https://github.com/be5invis/Iosevka/releases/tag/v11.2.0

> Add Fira Code V6's progress bar symbols.

:+1:

**Comment by agilesteel** [comment]
Oh I see. I guess this issue can be closed in this case. Thanks again for the hard work!
