### ISSUE TITLE
After update terminal doesn't use font

### ISSUE THREAD

**Issue by LamprosPitsillos** [tonsky/FiraCode#1325]
```
❯ fc-list | rg "Fira"        
/usr/share/fonts/TTF/FiraMono-Bold.ttf: Fira Mono:style=Bold
/usr/share/fonts/TTF/FiraCode-SemiBold.ttf: Fira Code,Fira Code SemiBold:style=SemiBold,Regular
/usr/share/fonts/TTF/FiraMono-Regular.ttf: Fira Mono:style=Regular
/usr/share/fonts/TTF/FiraCode-Retina.ttf: Fira Code,Fira Code Retina:style=Retina,Regular
/usr/share/fonts/TTF/FiraCode-Bold.ttf: Fira Code:style=Bold
/usr/share/fonts/TTF/FiraCode-Light.ttf: Fira Code,Fira Code Light:style=Light,Regular
/usr/share/fonts/TTF/FiraCode-Medium.ttf: Fira Code,Fira Code Medium:style=Medium,Regular
/usr/share/fonts/TTF/FiraMono-Medium.ttf: Fira Mono,Fira Mono Medium:style=Medium,Regular
/usr/share/fonts/TTF/FiraCode-Regular.ttf: Fira Code:style=Regular
```
```conf
#: Fonts {{{

#: kitty has very powerful font management. You can configure
#: individual font faces and even specify special fonts for particular
#: characters.

 font_family      Fira Code Retina
 bold_font        auto
 italic_font      JetBrains Mono SemiBold Italic
 bold_italic_font auto

``` 
Terminal: Kitty version  0.23.1

**Comment by Arthur-Stewart** [comment]
Same issue on Arch Linux after upgrading to [ttf-fira-code 6.1-1](https://archlinux.org/packages/community/any/ttf-fira-code/). When I ran kitty-list fonts under the Fira Code section I only saw 2 font options.

Fira Code Bold
Fira Code Light

The other four font options (medium, regular, retina, semibold) were missing.

Downgrade to 5.2.1 still works.

kitty 0.23.1

**Comment by tonsky** [comment]
Anyone has ideas why is this happening? Is there a kitty ticket?

**Comment by idest** [comment]
@tonsky this is similar to #840 #1000 and #1073, I was able to fix it with the workaround detailed in https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

**Comment by oeyoews** [comment]
@idest I try it, but it's no effect for me. so, i downgrade  it's verson to 5.2. it's goog.

**Comment by nikatar** [comment]
@idest, thank you, it's work

**Comment by morne** [comment]
I had the same issue as @Arthur-Stewart , also on Arch Linux. Downgrading to 5.2.1 works.

**Comment by kjerstadius** [comment]
I've also encountered this issue after upgrading to Fira Code 6.1 on Arch Linux. After reading the kitty faq article linked above I decided to compare the spacing detected by fontconfig for 5.2 and 6.1.

5.2
```
fc-list : family spacing outline scalable | rg Fira
Fira Code:spacing=90:outline=True:scalable=True
Fira Code,Fira Code Retina:spacing=90:outline=True:scalable=True
Fira Code,Fira Code Medium:spacing=90:outline=True:scalable=True
Fira Code,Fira Code Light:spacing=90:outline=True:scalable=True
Fira Code,Fira Code SemiBold:spacing=90:outline=True:scalable=True
```

6.1
```
fc-list : family spacing outline scalable | rg Fira
Fira Code:spacing=100:outline=True:scalable=True
Fira Code:outline=True:scalable=True
Fira Code,Fira Code Retina:outline=True:scalable=True
Fira Code,Fira Code Medium:outline=True:scalable=True
Fira Code,Fira Code Light:spacing=100:outline=True:scalable=True
Fira Code,Fira Code SemiBold:outline=True:scalable=True
```

As can be seen several variants are missing the spacing value in 6.1 and I'd bet that's why kitty doesn't pick up (for example) the Retina variant. @tonsky Any idea why this would be?

**Comment by tonsky** [comment]
Hopefully fixed in 6.2, please check. Somehow Glyphs keeps changing random glyphs widths even if I don’t touch them. Added extra check before release

**Comment by BigMikeM** [comment]
I had the same issue; 6.2 fixed it for me! Thank you!

**Comment by kjerstadius** [comment]
@tonsky Thanks for the quick turnaround on the fix!
