### ISSUE TITLE
Fine-tuned letter pairs do not work in ST4

### ISSUE THREAD

**Issue by lieskjur** [tonsky/FiraCode#1328]
Hi, the "fined-tuned letter pairs" don't seem to be working in sublime text 4 with fira-code version 6.1-1 installed from the AUR.
These are my font settings:
```"font_face": "Fira Code", "font_options": ["ss01","ss02","ss07"], ```
and this is how the example renders:
![image](https://user-images.githubusercontent.com/61360439/145724617-17fe63a8-ea40-4940-9c3a-589ca5275bb3.png)

Any ideas on how to fix the issue will be appreciated

**Comment by tonsky** [comment]
This is Sublime Text problem. They only apply ligatures to limited subset of symbols. Letters are not among them :(

**Comment by lieskjur** [comment]
Unfortunate
