### ISSUE TITLE
Something for `[x]`

### ISSUE THREAD

**Issue by amirmasoudabdol** [tonsky/FiraCode#133]
I really like the box instead of `[ ]`. I think it would be nice if we have something for `[x]`. This would add an extra feature for writing a task list.

**Comment by sushruth** [comment]
:+1:

**Comment by MadcapJake** [comment]
My only fear is that what if you're accessing a hash/array and the key/index is the `x` variable.  This might not be a problem though because the brackets and the variable should be separate syntactic elements.

**Comment by sushruth** [comment]
what about using `[*]` instead of `[x]` ?

**Comment by amirmasoudabdol** [comment]
@MadcapJake that's actually good point, I haven't thought of it. I was only thinking about it's use on Markdown.

**Comment by joffrey-bion** [comment]
The problem is that ligatures are defined in a language-agnostic way. This is a font, not a language, and I think we should be careful about whether a ligature is a good idea for *most* use cases or just isolated languages.
In this particular one, I personally think that using `x` as variable name for an array index is not uncommon, and the result of making `[x]` look like a nicer checkbox would compromise the visual in most programming languages for `myArray[x]`.

**Comment by Crissov** [comment]
In GFM task lists, the check box needs to be preceded by a list marker and a space, i.e. `- [ ]`, `* [ ]`, `+ [ ]` (and perhaps `. [ ]`). I don't know any programming language where these sequences with a fixed length of 5 characters would appear regularly.

**Comment by dhouck** [comment]
Python can have both `+ [ ]` and `* [ ]` as legal sequences, although I don’t know why I’d use either of them. The checked versions, `+ [x]` and `* [x]`, would both be more common.

**Comment by long-lazuli** [comment]
I also think ligatures for GFM markdown checkboxes would be nice :
don't forget the checked boxes ...
`- [ ]`,  `- [x]`, `* [ ]` & `* [x]`

**Comment by sushruth** [comment]
Just floating the idea of using `[*]` again.. any takers?

**Comment by Tekl** [comment]
PragmataPro has this already as a feature set.

**Comment by dhouck** [comment]
FiraCode now makes it easier to control individual ligatures IIRC, so my main objection is gone as long as this is disabled by default (places where you'd be writing GFM are more likely to support OpenType features than places where you'd write programming languages where `[x]` is relevant is an array or index, I expect).

**Comment by tonsky** [comment]
Just curious, what GFM stands for?

**Comment by jdreesen** [comment]
[GitHub Flavored Markdown](https://github.github.com/gfm/), I suppose.

**Comment by tonsky** [comment]
Will track progress in #993
