### ISSUE TITLE
Terminal font garbled zoom in/out

### ISSUE THREAD

**Issue by lyctw** [tonsky/FiraCode#1330]
Hi there

My font will be garbled when I zoom in/out the terminal. As the pic below, I typed abcdefg.
![image](https://user-images.githubusercontent.com/12937401/146130337-97a28fac-7cd0-484c-b3dd-c59ead2a147c.png)

I installed fira code on Manjaro `sudo pacman -S  ttf-fira-code` and use [Terminator](https://gnome-terminator.org/) as my terminal. 
How can I fix this problem.

Thanks.

**Comment by alexeyten** [comment]
Have you restarted terminal after installing font?

**Comment by tonsky** [comment]
Does font works in other apps? Try reporting this issue to the Terminator

**Comment by lyctw** [comment]
yeah.. It's not a FiraCode issue, I will report there. Thanks.
