### ISSUE TITLE
Italic variant

### ISSUE THREAD

**Issue by danielmunoz** [tonsky/FiraCode#134]
Is there hope to see a italic variant in the future? Code editors would benefit from this.

Greetings!

**Comment by tonsky** [comment]
I can’t draw italics for the whole font — I’m not a font designer. Follow
Mozilla’s Fira repo if they decide to implement that

**Comment by lencioni** [comment]
Here's the issue to follow if you are interested in this: https://github.com/mozilla/Fira/issues/38

**Comment by UnaiM** [comment]
Just in case someone hasn’t seen this yet, there is a Fira fork with italics for Mono: [https://github.com/mozilla/Fira/issues/38#issuecomment-136099951](url)

**Comment by dhouck** [comment]
That appears to be a dead link.

**Comment by j-f1** [comment]
This one should work: https://github.com/mozilla/Fira/issues/38#issuecomment-136099951

**Comment by UnaiM** [comment]
Thanks for noticing. I fixed it :)

**Comment by brainplot** [comment]
I know that this isn't from the original Fira Mono repo but can you base the Italic variant of Fira Code on this version?
https://github.com/zwaldowski/Fira/tree/zwaldowski/mod-new/otf
Maybe the italic version of Fira Mono will be released in the future but in the meanwhile we could settle for this.

**Comment by EvanCarroll** [comment]
Perhaps we could rebase off of this fork , rather than Mozilla's fork? Then we would have italics.. https://github.com/Avi-D-coder/fira-mono-italic As suggested on that above linked Mozilla issue.

**Comment by AdamBD** [comment]
is the PR from Losangelosgenetics repo going to be merged?

**Comment by tonsky** [comment]
Which PR?

**Comment by davidvmckay** [comment]
Upstream Fira appears to be dead; It is based on work by Carrois, which no longer lists Fira as a project.  No commits have been made to mozilla/fira since mid 2019.

We should consider creating our own fork of Fira for the FiraCode community, or inlining the relevant sources and severing the upstream dependency.

**Comment by tonsky** [comment]
Not sure what do you mean by inlining, but there's no live dependency between this repo and any of the Fira ones. I used their sources when I started but they have diverged massively since then

**Comment by ron-wolf** [comment]
Does [the fork+rebase](https://github.com/Avi-D-coder/fira-mono-italic) @EvanCarroll linked to contain italicized ligatures, or just slanted ligatures? I plan on checking myself, just busy with work rn.

**Comment by ShadiestGoat** [comment]
As a recap, why can't we use [the fork?](https://github.com/Avi-D-coder/fira-mono-italic)
