### ISSUE TITLE
Or ( || ) operator in C++ looks like forward-slash ( / )

### ISSUE THREAD

**Issue by isayakmondal** [tonsky/FiraCode#1354]
![image](https://user-images.githubusercontent.com/51121313/149939402-14c20bae-ab3d-4b44-b0ba-73ae8df6bc72.png)
So the Or ( || ) operator in C++ looks like forward-slash ( / ). I think it's happening because it's being italicized but I don't want this particular character to be italicized cause it almost looks indistinguishable from forward-slash.
Please take a look at it.

**Comment by RubenVerg** [comment]
that's up to the style you're using in the editor, not the font

**Comment by isayakmondal** [comment]
> that's up to the style you're using in the editor, not the font

I'm sorry but I didn't get what do you mean by style? Could you elaborate? As far as I remember I'm using default settings with Fira Code and Ligatures enabled.

**Comment by tonsky** [comment]
@isayakmondal there is no italics in Fira Code (too much an effort for non-designer like me). In the absence of italics, your editor draws “fake italics”, which it gets by mechanically transforming all the glyphs. If there were real italics in Fira Code, this problem wouldn’t exist, but here we are. Not much I can do about it, unfortunately. My advice is to disable fake italics, they look bad anyways

**Comment by isayakmondal** [comment]
@tonsky  Alright, I got the issue. I use a font called **Monokai Vibrant**  which was causing the issue, but it's written in their Github repo that this is optional for other fonts, and I don't know why it's on by default and sadly there is no guide in their repo about how to turn it off. Any idea about how to turn that off? Here's the github repo - https://github.com/dylantmarsh/monokai-vibrant
![image](https://user-images.githubusercontent.com/51121313/150077787-069fe337-8273-4b53-b7d6-d1fcbd783016.png)

**Comment by mfocko** [comment]
@isayakmondal looking at the theme, something like this should work:

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "name": "Monokai Vibrant - remove italics",
            "scope": [
                "comment",
                "string.comment",
                "variable.language",
                "keyword",
                "keyword.operator.logical",
                "keyword.operator.constructor",
                "keyword.operator",
                "storage",
                "variable.parameter",
                "markup.italic",
                "markup.italic.markdown"
            ],
            "settings": {
                "fontStyle": ""
            }
        }
    ]
},
```
↑ it goes to the user settings

**Comment by isayakmondal** [comment]
@mfocko thanks, it worked. :)
