### ISSUE TITLE
[Idea/Enhancement] ){ and (stretching here) ++){

### ISSUE THREAD

**Issue by bootmii** [tonsky/FiraCode#137]
`){` and maybe `++){` appear very commonly in C-like code. Ligatures for these are feasible and would be understandable if included.

**Comment by tomByrer** [comment]
`){` & it's beautified version `} (` is *very* common in JavaScript & GoLang as well.
But how to make each char still distinguishable?  One of the main reasons why I looked for alternative coding typefaces is to distinguish between [{(})].

**Comment by tonsky** [comment]
I understand that these combinations of character often appear together. But I would argue that they shouldn’t be in a ligature because semantically they’re parts of different semantic groups. Uniting them would hint wrong ideas, a connection where there should be no connection
