### ISSUE TITLE
Enabling Fira Code variants on macOS

### ISSUE THREAD

**Issue by danielyli** [tonsky/FiraCode#1372]
Apologies if this isn’t strictly Fira Code specific —

How does one use the font variants on a Mac? I’m specifically trying to use the legacy-style long pipe (`|`) in `cv30`, but I can’t find for the life of me how to enable it…

**Comment by tonsky** [comment]
It’s not everywhere but if you are lucky then https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

**Comment by danielyli** [comment]
Thank you
