### ISSUE TITLE
FiraCode-Retina is missing from FiraCode-VF.ttf

### ISSUE THREAD

**Issue by rexbinary** [tonsky/FiraCode#1379]
It seems FiraCode-Retina is missing from FiraCode-VF.ttf. Homebrew installs fonts using the variable font file when available. So when FiraCode is installed using brew FiraCode-Retina is not being installed.

**Comment by kenmcd** [comment]
Missing release note: Retina weight removed from FiraCode-VF.ttf #1318

**Comment by tonsky** [comment]
Next version of Fira Code will rename variable font so that two don’t compete. Hopefully it’ll make situation around it clearer #1332
