### ISSUE TITLE
Please add slashed zero variant

### ISSUE THREAD

**Issue by mbirth** [tonsky/FiraCode#138]
It would be awesome if you could add a Fira Code with slashed zero variant.

**Comment by tonsky** [comment]
You mean, instead of dotted zero? Why?

**Comment by mbirth** [comment]
I think it comes down to personal preference. I think a slashed zero is easier to distinguish from the uppercase "O" vs. the dotted "0".

Also, the dot looks a bit off for me:
![firecodezero](https://cloud.githubusercontent.com/assets/130302/13177327/b8968e14-d718-11e5-9aed-942eb579aa70.png)

**Comment by tonsky** [comment]
What’s your setup? Editor, OS, font rendening settings?

**Comment by mbirth** [comment]
Windows 7, Notepad++, Font size 11, normal.
System text size is set to 100%, ClearType enabled.

Also happens in Sublime Text 3:
![firasublime](https://cloud.githubusercontent.com/assets/130302/13178894/7a1833be-d721-11e5-8e74-b0328724dc24.png)

and in the notepad.exe (Fire Code, Regular, 11):
![firanotepad](https://cloud.githubusercontent.com/assets/130302/13178919/a152769c-d721-11e5-9779-34b946c23740.png)

Looks better in PowerShell ISE (size 14):
![fireise](https://cloud.githubusercontent.com/assets/130302/13178949/c2c3e3e2-d721-11e5-92b3-efcbde6057ae.png)

**Comment by tonsky** [comment]
In fact, it’s already there. Feature name is `"zero"`, so you can enable it e.g. in Atom by specifying
```
-webkit-font-feature-settings: "zero" 1;
```
in editor stylesheet
<img width="546" alt="screen shot 2016-02-22 at 17 49 28" src="https://cloud.githubusercontent.com/assets/285292/13217456/4ddcc908-d984-11e5-9be5-7e4d9db0e1f8.png">

**Comment by mbirth** [comment]
But how do I enable this in apps NOT atom.io? Other fonts usually have a separate TTF file, like "Meslo LG DZ" for their dotted zero variant (the normal one, with slashed zero, is called "Meslo LG").

**Comment by tonsky** [comment]
That would require hosting on-demand font builder like
http://input.fontbureau.com/download/ . I’m not against the idea per se,
maybe at some point I’ll build something like that.

**Comment by vyp** [comment]
@tonsky Is there free (as in freedom) software do these ourselves, so you don't have to host it?

**Comment by tonsky** [comment]
You can try FontForge. I won’t open source files (these are in Glyphs 2
format), but should be able to open OTF

**Comment by dmitriyK1** [comment]
I created a slashed zero variant:
https://github.com/dmitriyK1/FiraCodeSlashedZero

**Comment by italoservio** [comment]
In VSCode's Settings (JSON) you can add this kay value:
`"editor.fontLigatures": "'zero'",`
