### ISSUE TITLE
Haskell Ligature >>= (bind) is broken, was working before

### ISSUE THREAD

**Issue by shamansir** [tonsky/FiraCode#1386]
<img width="191" alt="Screenshot 2022-03-07 at 18 55 19" src="https://user-images.githubusercontent.com/110920/157090504-15c376d7-67b5-4c48-be49-61c4074e16db.png">

**Comment by shamansir** [comment]
Could be related to these changes in 6.0:

![image](https://user-images.githubusercontent.com/110920/157091097-022617cf-4df6-4f9a-a11a-f7f14caaf01c.png)

Works in 5.2:

<img width="177" alt="Screenshot 2022-03-07 at 19 00 25" src="https://user-images.githubusercontent.com/110920/157091318-fe0e2b5c-fd7c-464c-bf1e-d1319fee27a9.png">

**Comment by wopian** [comment]
It was removed as a default ligature due to conflicts. It can be enabled with the `ss09` stylistic setting
