### ISSUE TITLE
xfce4-terminal (0.6.3) - whitespace instead of ligatures and characters

### ISSUE THREAD

**Issue by elegantandrogyne** [tonsky/FiraCode#139]
Ligatures and characters they consist of are not displayed correctly in xfce4-terminal:
1. open xfce4-terminal, then Edit > Preferences > Appearance
2. choose font: Fira Code e.g. Regular 12 - apply changes
3. enter =, <, >, =>, != etc. in the terminal - whitespace instead of character/ligature

Found under Debian stretch/sid amd64.

**Comment by tonsky** [comment]
Added to non-supported list — thanks!
