### ISSUE TITLE
Character heights are different

### ISSUE THREAD

**Issue by KunalTanwar** [tonsky/FiraCode#1395]
I don't know it is a bug or you left it untouched on purpose. But my eyes are just not ready to ignore the fact!!

![IMG_20220324_180247.jpg](https://user-images.githubusercontent.com/77537933/159917257-9c2f573b-2a1c-44a7-b743-1a66cc0fff4e.jpg)

As you can see in the above image **capitalise** characters have less height than the lowercase characters.

![IMG_20220324_180304.jpg](https://user-images.githubusercontent.com/77537933/159917489-3733b334-7fa7-461c-a3aa-1c1e665303dc.jpg)

And also the letter `l` is different of all.

Also the slanted cut on letter `t`, `d`, `h` could be straight. ☹️

**Comment by tonsky** [comment]
That is intentional. It helps you tell characters apart when reading

**Comment by KunalTanwar** [comment]
> That is intentional. It helps you tell characters apart when reading

Don't you think this is bit👌 ugly?

**Comment by tonsky** [comment]
> Don't you think this is bit👌 ugly?

No, I don’t think so

> I know it is alot to ask but can you make a variant of same height characters like you made “Retina”??

I prefer not to make versions of Fira Code, one version for everyone keeps a lot of things simple
