### ISSUE TITLE
Add known support for Wez's Terminal

### ISSUE THREAD

**Issue by wespiard** [tonsky/FiraCode#1397]
Wez's terminal supports ligatures as well as stylistic sets. On this page they specifically show instructions for FiraCode: https://wezfurlong.org/wezterm/config/font-shaping.html

Requesting that the instructions be added to this Wiki page: https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

The sets can be specified as follows: 

```lua
harfbuzz_features = {"zero", "cv04", "cv02", "ss05", "ss04"},
```

Note that this should be in the return{} statement in the `wezterm.lua` config file, e.g., 

```lua
return {
  harfbuzz_features = {"zero", "cv04", "cv02", "ss05", "ss04"},
}

```

**Comment by tonsky** [comment]
Thanks! Done
