### ISSUE TITLE
Fira Code Symbols

### ISSUE THREAD

**Issue by TheEccentricDuck** [tonsky/FiraCode#1401]
Can Fira Code add font ligatures which will convert things typed like "$pi" to the actual mathematical symbol. I'm trying to find a font that does this that is not LaTEX but haven't been able to find one, and since Fira Code it my favourite programming font, I just want to know if it's possible. I'm not very experienced to font design so I don't know if this will be a good user experience. Please let me know if this is a bad idea. Thank you very much.

**Comment by tonsky** [comment]
Not Fira Code (we try to keep ligatures look similar to the actual text), but technically it’s possible

**Comment by TheEccentricDuck** [comment]
Alright, thank you very much for the response and the advice. I'm glad that you didn't just close the issue without  response, which is what happened to me before. :)
