### ISSUE TITLE
[Suggestion] Lua ~= operator ligature

### ISSUE THREAD

**Issue by dinispimentel** [tonsky/FiraCode#1415]
Just wanted to propose the same ligature of `!=` combo (or a new design) to the `~=` combo, because in Lua the **not equal operator** is `~=`.

I know it is not a major change, but I would appreciate it. Please let me know if it can be implemented.

Thanks in advance.

**Comment by rikkimax** [comment]
D uses ``~=`` for appending to an array.

**Comment by wopian** [comment]
Duplicate of https://github.com/tonsky/FiraCode/issues/1186

**Comment by tonsky** [comment]
Will close as duplicate
