### ISSUE TITLE
wiki is editable publicly

### ISSUE THREAD

**Issue by alvinzhengq** [tonsky/FiraCode#1416]
FiraCode wiki seems to be editable by anyone with a Github account, and someone changed the download link of the latest font for Windows on the page [OS Install instructions](https://github.com/tonsky/FiraCode/wiki/Installing/952d56e860030be8167a04e0788b9ea89d8cf840) to a piece of malware (I changed it back).

Please fix this soon, as I almost ran the malware on my system after downloading what I assumed to be a legitimate zip file.

**Comment by DeepCoreSystem** [comment]
I have reported the user that put the malware link in the wiki. It seems that he did it also on other repositories...

**Comment by tonsky** [comment]
Thanks! Restricted editing to collaborators only

**Comment by alexeyten** [comment]
Он там успел напоследок нагадить
https://github.com/tonsky/FiraCode/wiki/Installing/_compare/fc1b779%5E...fc1b779

**Comment by DeepCoreSystem** [comment]
The user has been banned
