### ISSUE TITLE
Setting up FiraCode-Retina in VS-Code

### ISSUE THREAD

**Issue by m6fukumoto** [tonsky/FiraCode#1419]
Hello. 
I recently knew that font-weight can be set to Retina.
Is this the correct setting for FiraCode-Retina in VS-Code?

setting.json   "editor.fontFamily": "'FiraCode-Retina', Consolas, 'Courier New', monospace",
<img width="599" alt="screen shot 1" src="https://user-images.githubusercontent.com/83090192/171226029-631bc142-6cd6-4826-9543-b96db8cf05e3.png">

I did not install the FiraCode-VF.ttf in the Variable_ttf folder, only the one in the ttf folder.

<img width="599" alt="screen shot 2" src="https://user-images.githubusercontent.com/83090192/171226033-f7879c78-2726-4d53-9841-451413672fe3.png">

**Comment by tonsky** [comment]
Seems correct

**Comment by m6fukumoto** [comment]
Thanks!
