### ISSUE TITLE
Some unicodes from you other project?

### ISSUE THREAD

**Issue by aadrian** [tonsky/FiraCode#142]
Hi,

Any plans to add some of the unicodes from https://github.com/tonsky/clojure.unicode   ?

It would be nicer if the two were synced, and there would be unicode symbols only 
when a ligature does not look better, e.g. 

```clojure
(def ^:macro ↠ #'->>)
(def ^:macro → #'->)
```

**Comment by tonsky** [comment]
No plans, no. You don’t have to use unicode symbols at all, so if ligature looks better, just don’t use unicode.

**Comment by aadrian** [comment]
> You don’t have to use unicode symbols at all

Well it would be nice if the two projects would be consistent :).

**Comment by tonsky** [comment]
Not sure what do you mean by consistent. You want something from unicode here or something from here in unicode?

Also please remember that Fira Code is not a font for Clojure coding, it’s universal and aims to cover as much languages out there as possible

**Comment by aadrian** [comment]
> Not sure what do you mean by consistent. You want something from unicode here or something from here in unicode?

Yes:
 - recommend for clojure.unicode FiraCode as default
 - remove from clojure.unicode the elements that are better readable with FiraCode ligatures
 - improve the rendering of some clojure.unicode elements in FiraCode.

**Comment by tonsky** [comment]
No, I don’t want to do that. I don’t want clojure.unicode to be tied to Fira Code. People should be able to choose their favorite font.
