### ISSUE TITLE
Half Joking Stylistic Set Request: Intercal spot variables.

### ISSUE THREAD

**Issue by oshaboy** [tonsky/FiraCode#1423]
Variables in Intercal must be of the form `[.:,;][0-9]+`. Those are considered 1 token so the font should represent them accordingly. 

Furthermore some operations on those variables are done using `[.:,;](&|V|\?|¥)[0-9]+`.

These should be a stylistic set to not cause problems with reals in other programming languages (`2.3` for example. It is valid in CLC, but it's parsed as `(2 .3)`)

Me and the greater Intercal programming community would appreciate such an addition. The work you do is great. Please abstain from giving up.

**Comment by tonsky** [comment]
Funny, but esoteric, so no :)
