### ISSUE TITLE
[Doc] missing href link in the `Installing` part of wiki

### ISSUE THREAD

**Issue by katsusan** [tonsky/FiraCode#1434]
**URL**: https://github.com/tonsky/FiraCode/wiki/Installing#windows.

**Description**: the href link of download url in this capture is missing.

![image](https://user-images.githubusercontent.com/11537821/177346738-dffdd53e-6fda-4640-8c73-d48b47674ef9.png)

**Corresponding html**:
```HTML
<a href="">https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip</a>
```

**Comment by tonsky** [comment]
Thanks, fixed
