### ISSUE TITLE
add vietnamese characters??

### ISSUE THREAD

**Issue by kg2714** [tonsky/FiraCode#1437]
can you add vietnamese letter?
here are all vietnamese letter i/we need:
a á à ã ả ạ
â ấ ầ ẫ ẩ ậ
ă ắ ằ ẵ ẵ ặ
e é è ẽ ẻ ẹ
ê ế ề ễ ể ệ
i í ì ỉ ĩ ị
o ó ò ỏ õ ọ
ô ố ồ ổ ỗ ộ
ơ ớ ờ ở ỡ ợ
u ú ù ủ ũ ụ
ư ứ ừ ử ữ ự
y ý ỳ ỷ ỹ ỵ
I know that need so many effort so you can ignore if you want.
Thank you!

**Comment by wopian** [comment]
https://github.com/tonsky/FiraCode/issues/185#issue-153450600

**Comment by wopian** [comment]
https://github.com/tonsky/FiraCode/issues/185 and https://github.com/tonsky/FiraCode/issues/1112

**Comment by tonsky** [comment]
I’ll close as duplicate
