### ISSUE TITLE
Breaking existing workflow, wrongly updated image and missing documentation

### ISSUE THREAD

**Issue by ShalokShalom** [tonsky/FiraCode#1439]
I use Fira Code since years. Today, I install it again on my laptop and see that some of my beloved characters don`t render as usual. I look it up and expect it to be a mistake. 

When I look at the current state of the README, it even got an updated screenshot for version 6. 
According to it, my character is supposed to render just fine. 

Then, I look into the release notes, and see, that for whatever reason, characters got changed who worked fine for years and it got basically omitted from most channels. 

[The screenshot is false and misleading](https://github.com/tonsky/FiraCode#whats-in-the-box), the backlog does mention it in reference to C, but not Haskell (where it breaks basic combinations of operators) and it looks quite rushed, altogether. 

Obviously, my character is now meant to be optionally enabled as a variant. 
No link, no documentation, no word how to do that. 

Wonderful

**Comment by wopian** [comment]
> Obviously, my character is now meant to be optionally enabled as a variant.
> No link, no documentation, no word how to do that.

A link to instructions on how to enable stylistic sets (and previews of the stylistic sets available, that renable ligatures that are disabled by default to avoid conflicts) are right there on the README below the screenshot you're referencing.

**Comment by ShalokShalom** [comment]
The main imagine shows, incorrectly, the Haskell "now-variants" suggestively as "what you get". 

There is **no notion** of variants at this point, until significantly more down the README.
