### ISSUE TITLE
Italics, sprinkled with small additions like Consolas idea

### ISSUE THREAD

**Issue by J3Rik0** [tonsky/FiraCode#145]
First of all, I am grateful of this project, the font is just perfect (for me at least), perfect weight, perfect proportions, perfect everything.

I am curious tho' if there is a plan for italics any time soon and as an idea if you can add some sugar to the mix so that the italics stand out by having some additions similar to how Consolas has, the lowercase f is a very good example of this.

**Comment by tonsky** [comment]
Please open a feature request at https://github.com/Mozilla/Fira, the original from where I took all the letterforms. They have qualification and resources to do it, I don’t
