### ISSUE TITLE
Enabling font ligatures for Visual Studio Code on macOS

### ISSUE THREAD

**Issue by m-rcussilva** [tonsky/FiraCode#1450]
Hello folks! 

This is just a tip. After you have done this in your `settings.json`:

```
"editor.fontFamily": "'Fira Code'",
"editor.fontLigatures": true,
```
and the font ligatures it's still disabled, change `Fira Code` to `FiraCode Nerd Font Mono` and see if the problem is solved. This work for me.

ps:  forgive me if I am posting this in the wrong place.

**Comment by tonsky** [comment]
This seems irrelevant to Fira Code, you are enabling different font instead

**Comment by m-rcussilva** [comment]
That's interesting.

Do you have any idea why using `FiraCode Nerd Font Mono` instead of `Fira Code` solved my problem? I unzipped the folder and pastes the files into: ~/Library/Fonts/ [here]

Maybe this is the wrong path?

**Comment by tonsky** [comment]
Which folder did you unzipped? Looks like you have FiraCode Nerd Font Mono installed but not Fira Code

**Comment by m-rcussilva** [comment]
You are right. I downloaded FiraCode Nerd Font from this website https:// www.nerdfonts.com/font-downloads

Now everything make sense.

My bad. 🤦🏻‍♂️

**Comment by m-rcussilva** [comment]
I will uninstall FiraCode Nerd Font Mono and install Fira Core correctly https://github.com/tonsky/FiraCode/wiki/Installing. 

Thank you for responding.
