### ISSUE TITLE
Add a Cursive Font

### ISSUE THREAD

**Issue by EndriTuma** [tonsky/FiraCode#1458]
Idk how to add pull requests so im just putting it on issues.
So, tonsky why dont you add a cursive font?
Yes, I do know the **Fira Code IScript** font but i dont like how they made it.
So can you make a cursive font please?
And try to make it how **Cascadia Code** does

**Comment by tonsky** [comment]
I like the idea, but it’s too much effort for me

**Comment by EndriTuma** [comment]
Basic Cursive would do

**Comment by alexeyten** [comment]
There is custom italic variant #513
