### ISSUE TITLE
U+218A and U+218B

### ISSUE THREAD

**Issue by iandoug** [tonsky/FiraCode#146]
hi

Possible to add these please? They're just 2 and 3 rotated 180. 
I did that in fontforge here and it seems to work okay "as is" (no other fiddling done), but never contributed to a font before so not sure of the process...

http://www.fileformat.info/info/unicode/char/218a/index.htm
http://www.fileformat.info/info/unicode/char/218b/index.htm

Thanks, Ian

**Comment by tomByrer** [comment]
What are they used for?

**Comment by iandoug** [comment]
They are used in dozenal (duodecimal / base 12) for 10 and 11. Various characters have been suggested and used over the years, but the Unicode people have now made those two glyphs the "official" characters to use.
http://z13.invisionfree.com/DozensOnline/index.php?showtopic=1324

http://www.dozenalsociety.org.uk/
(original clock is here: http://dozenal.ae-web.ca/ )

http://www.dozenal.org/

Symbola has added them, but Symbola is a serif font, and I use Fire Code in my editor... :-)

Thanks, Ian

**Comment by tonsky** [comment]
I can add them in next version. There’s no contribution process at the
moment

**Comment by iandoug** [comment]
That would be great, thanks :-)

**Comment by iandoug** [comment]
Thanks :-)
