### ISSUE TITLE
Misspelling of Haskell in Spanish README

### ISSUE THREAD

**Issue by Itay123TheKing** [tonsky/FiraCode#1463]
in [`ligatures_es.png`](https://github.com/tonsky/FiraCode/blob/master/extras/ligatures_es.png) near the bottom the Haskell language is spelled as "Haskel" - missing an l.

![ligatures_es](https://raw.githubusercontent.com/tonsky/FiraCode/master/extras/ligatures_es.png)

**Comment by tonsky** [comment]
Thanks!
