### ISSUE TITLE
Ligature Request: </>

### ISSUE THREAD

**Issue by Fresheyeball** [tonsky/FiraCode#147]
Right now `</>` appears with the `</` ligature and `>`, but I feel that `</>` is a single symbol.

**Comment by MadcapJake** [comment]
What language utilizes this as syntax?

**Comment by Fresheyeball** [comment]
</> is path append in Haskell, Elm and PuresScript, probably others.

**Comment by tonsky** [comment]
Nice — will add

**Comment by Fresheyeball** [comment]
Woot!

**Comment by mcepl** [comment]
> Nice — will add

Won't all people editing XML hate you?

**Comment by tonsky** [comment]
@mcepl why? Will it cause conflicts?

**Comment by mcepl** [comment]
``</>`` is an universal end of any element in SGML (remember, XML is a subset of SGML).

**Comment by tonsky** [comment]
They should praise me for that ligature instead (b/c right now </> renders as two chars, will be as one—which it is)
