### ISSUE TITLE
How to disable ligatures but use stylistic sets in vscode

### ISSUE THREAD

**Issue by Firestar-Reimu** [tonsky/FiraCode#1473]
I want to use these

`"'cv16', 'ss03', 'ss05', 'zero'",`

because I do not like/am not used to Fire Code's `@` and `&`, etc.

but I don't want ligatures due to #1468 

how can I set them in vscode?

**Comment by tonsky** [comment]
"editor.fontLigatures": "'calt' 0, 'cv16', 'ss03', 'ss05', 'zero'",

**Comment by Firestar-Reimu** [comment]
thanks, so what does `calt` mean
