### ISSUE TITLE
Wiki update for BBEdit support

### ISSUE THREAD

**Issue by jceaser** [tonsky/FiraCode#1484]
The wiki page https://github.com/tonsky/FiraCode/wiki/BBEdit-instructions should be updated to reflect that BBEdit 14.6 now supports FiraCode. I would do it myself but I don't have rights. Can I have rights or can someone with rights do the update?

https://www.barebones.com/support/bbedit/notes-14.6.html, search for "ligatures".

**Comment by tonsky** [comment]
Thanks, fixed
