### ISSUE TITLE
GTK

### ISSUE THREAD

**Issue by handicraftsman** [tonsky/FiraCode#149]
Ligatures are fully supported by GTK. So, it will work with all editors with GTK.

**Comment by handicraftsman** [comment]
Also, it not works on VTE terminals (like GNOME terminal)

**Comment by tonsky** [comment]
Can you make it into PR for README.md file?

**Comment by mcepl** [comment]
One should mention https://bugzilla.gnome.org/show_bug.cgi?id=584160 here.

**Comment by mcepl** [comment]
Actually, it is https://gitlab.gnome.org/GNOME/vte/issues/192 now.
