### ISSUE TITLE
Ligature for "0x"

### ISSUE THREAD

**Issue by nkoder** [tonsky/FiraCode#15]
Hi

I think "0x" is good candidate for ligature. Is is used for example in Java in hax constants. For example:
```java
int hexNumber = 0x200; // same as 512
```

On the other hand:
* I guess it is not so common notation
* would it corrupt another phrases? (eg. some numbers followed by `x` like `"Your equation is 10x20. The result is 200"`)

**Comment by tonsky** [comment]
Interesting idea. But downside you’ve mentioned is serious enough not to consider this as a ligature though. Sorry

**Comment by tonsky** [comment]
Giving it second thought, I’ve added that in 1.000. Thanks for the idea!
