### ISSUE TITLE
MacVim Slowly Scrolling Down

### ISSUE THREAD

**Issue by samedson** [tonsky/FiraCode#150]
When scrolling down, MacVim seems to hiccup a bit, but when I scroll up it is very smooth. When I do not `set macligatures` it scrolls fine (but doesn't show the cool characters). I am testing the scroll speed using my touchpad and jk keys and my key repeat is set at 1 which is 15ms.

Doing some dumb testing against Activity Monitor, it looks like the CPU load when I scroll down is much lower (~%60) than when I scroll up (150-200%), so the downscrolling seems to be inhibiting the scroll rather than taking on a huge CPU load and causing framerate hiccups.

OSX 10.11, MacbookPro Retina

Followed the instructions to 
```
set macligatures
set guifont=Fira\ Code:h12
```

Looking around for some possibly related topics:
[Guy with the same issue (Scroll to Amadeus Demarzi)](http://blog.gmane.org/gmane.editors.vim.mac/page=11)
[thread related to listchars](https://github.com/tpope/vim-sensible/issues/57)

**Comment by flying-sheep** [comment]
why do you think that’s a bug anywhere but in MacVim?

**Comment by refried** [comment]
Scroll is also painfully slow in IntelliJ with Fira and ligatures enabled.  Not slow in IntelliJ with another font (Hack, Menlo, Courier) and ligatures enabled.

**Comment by AndreasDahl** [comment]
@flying-sheep It is not completely unthinkable that anything can be done on the font side. https://github.com/tonsky/FiraCode/issues/96#issuecomment-174157799

Though i agree that is is probably mostly an issue in the applications end.

**Comment by flying-sheep** [comment]
that’s what i’m saying. my reasoning is that

1. few code editors are likely built with ligature performance in mind: after all, it’s not a common feature in monospace fonts. therefore the improvement potential is likely high there
2. there’s only so many things that can be changed in how fonts can approach something. after all they’re data, not code.

sure, if there’s something the font can do, let’s do it. but there can be done infinitely more on the rendering side (including doing the font’s optimization automatically by not being naïve)

**Comment by tonsky** [comment]
E.g. IDEA has terrible perf issues just because of the amount of ligatures
I have in the font. It’s not even the amount of ligatures actually
displayed on the screen. Say I can drop some ligatures, and maybe if
there’s some potential to rewrite existing ones to use less rules, if
that’s 2× improvement, it still would be terrible. We should look for
editors to fix the performance (we know it’s possible, e.g. Atom has no
problem rendering Fira Code)

**Comment by flying-sheep** [comment]
heh, yes, because it’s based on chrome, and browsers used to render that shit long ago.

font rendering components for text editors not so much, and that’s where work has to start.

@samedson did you file an issue in MacVim? @refried did you file one in IntelliJ IDEA?

**Comment by samedson** [comment]
Just opened the [issue with MacVim](https://github.com/macvim-dev/macvim/issues/254).

**Comment by refried** [comment]
https://youtrack.jetbrains.com/issue/IDEA-127539

**Comment by rusnasonov** [comment]
Iterm2 slowly too. https://www.iterm2.com/documentation-fonts.html

> Some fonts, such as FiraCode, support ligatures if enabled in iTerm2. You can enable ligatures in Prefs > Profiles > Text. Ligatures are rendered using CoreText, which is significantly slower than Core Graphics. NOTE: Ligatures are not supported by the GPU renderer and will reduce performance.
