### ISSUE TITLE
Stylistic settings impact the Chinese font variant.

### ISSUE THREAD

**Issue by yola-0316** [tonsky/FiraCode#1502]
Background: I use the Simplified Chinese font.

Previous: Chinese font display as simplified.

Now: Chinese font display as traditional when fontLigatures include 'cv10'. 
It's show simplified font before several weeks, may be affected by VS Code update?

With 'cv10'
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/4338052/215481253-ef103014-c0fc-4403-a70b-9dbdee05d646.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/4338052/215481316-3e0003c8-1e8b-4655-8135-8fc8e68e7813.png">

Without 'cv10'
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/4338052/215481422-e94c2b00-8514-43da-bf7c-81f3d8b3db45.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/4338052/215481456-64feed35-21ea-4c3f-b029-085a65471109.png">

Environment:
OS: macOS 13.1 (22C65)
Editor: VS Code Version: 1.74.3 (Universal)
Text encoding: UTF-8
Settings:
```json
"editor.fontFamily": "Fira Code, MesloLGS NF, PingFang SC, monospace",
"editor.fontLigatures": "'cv01', 'cv02', 'cv06', 'cv09', 'cv12', 'cv14', 'ss04', 'cv30', 'cv31', 'ss02', 'ss08', 'cv24', 'ss06'",
```

**Comment by tonsky** [comment]
I doubt Fira Code is the issue here. Maybe one of your fallback fonts was updated? Fira Code includes no chinese characters, so other font is used to display them
