### ISSUE TITLE
I can't get ligatures to work in Tilix on Arch

### ISSUE THREAD

**Issue by SteveDevOps** [tonsky/FiraCode#1506]
I installed FiraCode ttf font set using pacman -S ttf-fira-code
font is displaying in tilix but not symbols/ligatures. 

I'm using Tilix 1.9.5 on Aarch and I have specified FiraCode Regular 12 as custom font in Tilix.
`fc-list | grep -i fira               
/usr/share/fonts/TTF/FiraCode-SemiBold.ttf: Fira Code,Fira Code SemiBold:style=SemiBold,Regular
/usr/share/fonts/TTF/FiraCode-Retina.ttf: Fira Code,Fira Code Retina:style=Retina,Regular
/usr/share/fonts/TTF/FiraCode-Bold.ttf: Fira Code:style=Bold
/usr/share/fonts/TTF/FiraCode-Light.ttf: Fira Code,Fira Code Light:style=Light,Regular
/usr/share/fonts/TTF/FiraCode-Medium.ttf: Fira Code,Fira Code Medium:style=Medium,Regular
/usr/share/fonts/TTF/FiraCode-Regular.ttf: Fira Code:style=Regular`

I am using Starship prompt. I installed Starship via pacman as well.
I can't copy paste symbols via vim to steup starship.toml and they won't display correctly in other things like bat, cat, etc.
symbols not working in prompt or vim.

Kernel: 6.1.12-arch1-1 
Shell: zsh 5.9 
DE: Xfce 4.18 
WM: Xfwm4 
starship 1.12.0-3

**Comment by tonsky** [comment]
Thanks! Added it to the README

**Comment by SteveDevOps** [comment]
ehm.. I ended up having to use this pkg instead: https://archlinux.org/packages/community/any/ttf-firacode-nerd/
