### ISSUE TITLE
Fira code ligatures won't work at all

### ISSUE THREAD

**Issue by SaulKriheli** [tonsky/FiraCode#1507]
I have Fira code installed, and it shows up as my font, I have also set the .json file to support ligatures but it still doesn't work.

here is my full settings config.

{
  "editor.tabSize": 2,
  "editor.fontSize": 15,
  "editor.minimap.enabled": false,
  "editor.fontFamily": "fira code,",
  "editor.fontLigatures": true,
  "liveServer.settings.CustomBrowser": "firefox",
  "liveServer.settings.donotShowInfoMsg": true,
  "liveServer.settings.port": 0,
  "editor.formatOnSave": true,
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 1,
  "security.workspace.trust.untrustedFiles": "open",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.cursorBlinking": "phase",
  "workbench.iconTheme": "vscode-great-icons",
  "workbench.colorTheme": "Bear Theme"
}

**Comment by tonsky** [comment]
Try ` "editor.fontFamily": "Fira Code",`

**Comment by SaulKriheli** [comment]
> Try ` "editor.fontFamily": "Fira Code",`

It worked, thanks.
