### ISSUE TITLE
Messy rendering in IntelliJ IDEA, OS X, non-retina

### ISSUE THREAD

**Issue by refried** [tonsky/FiraCode#151]
Not sure this issue can be resolved within Fira, but maybe it can, and alternative solutions are welcome as well!

I was trying to figure out which terrible weight of Fira IntelliJ was using, so I could uninstall it, but found that what I was seeing in IntelliJ didn't correspond to any of the Fira styles.  

In the attached screenshot you can see 10pt and 14pt examples of FontBook Fira samples alongside IntelliJ rendering at the same size.  To be clear, I think what's shown in Fontbook is legible and what's in IntelliJ is not.

![10-pt](https://cloud.githubusercontent.com/assets/538571/13681564/c75d8afc-e6cb-11e5-9cbd-8a59082fd52e.png)

![14-pt](https://cloud.githubusercontent.com/assets/538571/13681571/cec02138-e6cb-11e5-929a-688b0b329bc8.png)

**Comment by refried** [comment]
On the other hand, other fonts look ok in IntelliJ on the default settings, so maybe it *is* something that can be addressed in Fira.

**Comment by tonsky** [comment]
What version of IDEA are you using? I think that should be fixed in latest
16 EAP/preview.

**Comment by refried** [comment]
This was 15, and not the "Light" issue that is said to be fixed in 16 EAP (you can see in the screenshot that the way the font is rendered in IntelliJ doesn't match Light or any of the other well-rendered options.

I tried 16 EAP and interestingly enough the font looks decent until ligatures are enabled; see the attached screenshots:

![screen shot 2016-03-13 at 8 57 13 pm](https://cloud.githubusercontent.com/assets/538571/13732681/45981d08-e95e-11e5-80b0-db5a5ad2a5fb.png)
![screen shot 2016-03-13 at 8 57 03 pm](https://cloud.githubusercontent.com/assets/538571/13732679/414b3f6e-e95e-11e5-952e-90cdd0c594cb.png)

Weird, huh.
