### ISSUE TITLE
Glyphs for the shavian alphabet

### ISSUE THREAD

**Issue by Solver42** [tonsky/FiraCode#1511]
Range: 10450–1047F

𐑐 𐑑 𐑒 𐑓 𐑔 𐑕 𐑖 𐑗 𐑘 𐑙 𐑚 𐑛 𐑜 𐑝 𐑞 𐑟
𐑠 𐑡 𐑢 𐑣 𐑤 𐑥 𐑦 𐑧 𐑨 𐑩 𐑪 𐑫 𐑬 𐑭 𐑮 𐑯
𐑰 𐑱 𐑲 𐑳 𐑴 𐑵 𐑶 𐑷 𐑸 𐑹 𐑺 𐑻 𐑼 𐑽 𐑾 𐑿

**Comment by tonsky** [comment]
It’s a fun idea, but realistically probably ain’t gonna happen. Thanks for the suggestion though, I learned about shavian alphabet today!
