### ISSUE TITLE
support termite?

### ISSUE THREAD

**Issue by PaBLoX-CL** [tonsky/FiraCode#152]
Awesome font, it doesn't work with termite though :(, it's based on the vte gtk widget (same for almost every damn terminal emulator around)...

is there any way to help so we can enjoy this awesome font too ( : ?

**Comment by tonsky** [comment]
I think you should talk to them :)

**Comment by PaBLoX-CL** [comment]
Oh, I thought the problem on the fonts end. I'll speak with them, thanks :)
