### ISSUE TITLE
About 0

### ISSUE THREAD

**Issue by 736mo** [tonsky/FiraCode#1521]
![image](https://user-images.githubusercontent.com/106133518/230705938-80805587-4c86-4ccd-ad8f-11232ab19db9.png)
Why isn't `0` like that?
![image](https://user-images.githubusercontent.com/106133518/230705995-7557d103-eb77-496e-a09c-f3065d297e19.png)

**Comment by alexeyten** [comment]
Either you have a really old version of the font or you have enabled stylistic set with dotted zero.

**Comment by 736mo** [comment]
> 要么您有一个非常旧版本的字体，要么您启用了带有虚线零的样式集。

The version is v6, In sublime text4 setting about font is
```json
"font_face":"Fira Code",
```

**Comment by 736mo** [comment]
It's OK now.Delete it and reinstall it.

**Comment by RuochenFu21** [comment]
You probably need to close this issue
