### ISSUE TITLE
Baking in stylistic sets during build does not fully work

### ISSUE THREAD

**Issue by Vampire** [tonsky/FiraCode#1524]
I used the great new functionality to bake-in sytlistic sets - thanks -, and built my preferred Fira Code variant using
```bash
docker run --rm -v "${PWD}":/opt tonsky/firacode:latest ./script/build.sh -f "ss02,ss03,ss04,ss05,ss06,ss07"
```
I installed it, and it works fine in IntelliJ, it works fine in Firefox, it works fine in Chrome.

As a terminal on Windows I use ConEmu where I have also configured Fira Code.
I know it does not support ligatures yet and I live with that.

But with my variant of Fira Code even the single characters that should be replaced are not.
While with the enabled sets they should show like
![image](https://user-images.githubusercontent.com/325196/234713478-66e15da3-c7f3-4b66-a9bd-fee6774254ab.png)
they show in ConEmu still like
![image](https://user-images.githubusercontent.com/325196/234713529-5328fcd8-8c36-4a42-b581-f43f0f1be233.png)
and greatly hurt my eyes :-(

**Comment by tonsky** [comment]
It probably doesn’t support open type features at all. Switch to a different terminal?

**Comment by wopian** [comment]
Windows Terminal fully supports OpenType features and integrates with any shell runtime (and most of the other features I would have used ConEmu for before WT released)

**Comment by Vampire** [comment]
I'll maybe give it a try, I'm mostly not happy with Microsoft apps. :-D

But actually, ConEmu is not the only place where it does not properly work.
It also does not properly work in Chrome in some places. :-/
I have a UserScript that enforces the browsers configured monospace font in certain places to have my beautiful Fira Code everywhere I read code.
<details>
<summary>What it does is this</summary>

```javascript
// ==UserScript==
// @name          Configured Monospace Font Everywhere
// @description	  Uses the configured monospace font everywhere
// @author        Vampire
// @version       1.0
// @match         *://*/*
// ==/UserScript==
(function() {var css = [
    // General tags
    "pre, code, samp, tt, kbd:not(.badmono), ",
    // ViewVC
    ".vc_file_line_number, .vc_file_line_text, .vc_diff_chunk_extra, .vc_diff_add, .vc_diff_remove, .vc_diff_change, .vc_diff_nochange, .vc_diff_line_number, .vc_idiff_add, .vc_idiff_change, .vc_idiff_remove, ",
    // GitHub
    ".blob-code-inner, .blob-num, ",
    // Ace Text Editor
    ".ace_editor",
    "{",
    "    font-family: monospace !important;",
    "}",
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
  }
}
})();
```
</details>

If you then for example go to https://www.jdoodle.com/execute-groovy-online/ and paste in
```
<= >= & $ @ \\ \ \n && <$ <$> $> ?: =~ ==~ !~
```
it works properly on both,
Firefox ![image](https://user-images.githubusercontent.com/325196/235128894-70e35e11-4b2b-438d-ae41-0b2ecb2cabaf.png)
and Chrome ![image](https://user-images.githubusercontent.com/325196/235128994-1137dafd-1a07-4006-8202-818f3e5b50e8.png)

But if you go to https://docs.gradle.org/current/userguide/custom_gradle_types.html#mutable_managed_properties and use the browser dev tools to insert the same string into the example code, it only works
in Firefox ![image](https://user-images.githubusercontent.com/325196/235129238-e0b62beb-84ec-4acb-bd65-53f715810fc0.png)
but not in Chrome: ![image](https://user-images.githubusercontent.com/325196/235129301-ef856f7a-a392-4df5-a3ac-6dbcf4a4a132.png)

:-(

**Comment by Vampire** [comment]
Ah, in that case it is because the site's CSS says `text-rendering: optimizeSpeed` for `<pre>` and `<code>` and Firefox seems to not disable ligatures in that case while Chrome does. 
Adding `text-rendering: auto !important;` fixes that one.

**Comment by Vampire** [comment]
But yeah, then it is in ConEmu most probably also because of the missing ligature and so on support
