### ISSUE TITLE
Disabling ligatures excluding those in stylistic set

### ISSUE THREAD

**Issue by Darth-Arrush** [tonsky/FiraCode#1527]
Hi,

I'm using Fira Code 6.2 on VS Code. I would like to use the `"'zero'"` and `"'ss03'"` stylistic sets (dotted zero and conventional ampersand) but at the same time, disable other ligatures. For now, ligatures like `...`, `->`, `/*`, and `*/`. still work. How to disable these but retain the dotted zero and conventional ampersand? I have tried using only `"'zero'"`, only `"'ss03'"`, and both in `"editor.fontLigatures"`, but these set `"editor.fontLigatures"` to true as well.

Thanks in advance

**Comment by wopian** [comment]
I believe adding `-calt` would do what you're looking for

**Comment by Darth-Arrush** [comment]
"editor.fontLigatures": "'calt', 'zero', 'ss03'" This is the closest to `"editor.fontLigatures": "'calt', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'zero', 'onum'"` as in the VSCode instructions, and doesn't work.
How to add -calt?

**Comment by j-f1** [comment]
`'call' off`

**Comment by Darth-Arrush** [comment]
Thank you. This worked.

**Comment by oliviercailloux** [comment]
For those reaching here as I did: https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
