### ISSUE TITLE
U+25FC and U+25FB cannot be colored.

### ISSUE THREAD

**Issue by mikahosh1no** [tonsky/FiraCode#1528]
I came from this issue https://github.com/gpakosz/.tmux/issues/652

When I configure my terminal Alacritty to use the Fira Code font, the colors of characters U+25FC and U+25FB cannot be displayed correctly.

Please pay attention to the color of the battery bar at the bottom of the video.

https://github.com/tonsky/FiraCode/assets/131941394/f315e349-c500-4273-a3b6-2e5abecbbbbd

**Comment by tonsky** [comment]
I don’t think these characters are in the font. Even though, that should not affect colors anyways
