### ISSUE TITLE
Compatibility List Updates

### ISSUE THREAD

**Issue by jim-p** [tonsky/FiraCode#1532]
I've tried out a few different editors and terminals this week and have a few updates for compatibility:

Editors:

 Works:
* UltraEdit for Linux (UEX)

Doesn't work:
* UltraEdit for Windows
   * This is already listed but needs clarified that where it doesn't work on Windows

Terminals:

Works:
* Tabby

Doesn't work:
* Asbru Connection Manager
* SecureCRT

**Comment by tonsky** [comment]
Great! Please make a PR
