### ISSUE TITLE
The capital letter horizontal lines aren't quite aligned

### ISSUE THREAD

**Issue by Moosems** [tonsky/FiraCode#1538]
<img width="913" alt="Screen Shot 2023-07-11 at 7 45 26 PM" src="https://github.com/tonsky/FiraCode/assets/95927277/088d3a48-23c7-48ed-9bc4-3a9ad37a71fc">

The G in particular is super close to the rest but isn't quite aligned and the A might deserve an exception.

**Comment by kenmcd** [comment]
What makes you think that these should be "aligned"?

**Comment by Moosems** [comment]
My friend, I refer you to this readme image:

https://github.com/tonsky/FiraCode/blob/master/extras/typographics.png

**Comment by Moosems** [comment]
Why are just the tops aligned for capital letters?
