### ISSUE TITLE
Curvy Brackets '{' and '}' are very different

### ISSUE THREAD

**Issue by niahoo** [tonsky/FiraCode#154]
The closing one feels serifish … Is that on purpose ?

Thanks

**Comment by tonsky** [comment]
A screenshot? They look identical to me

**Comment by niahoo** [comment]
Sure.

![2016-03-11_15h03_28](https://cloud.githubusercontent.com/assets/380825/13704095/6eb4c436-e79a-11e5-8c86-fd906c76d4c0.png)

**Comment by tonsky** [comment]
And OS/editor?

**Comment by niahoo** [comment]
Well it's actually the anti-aliasing thing that causes the differences. On certain sizes the styles are inverted (it the right-hand one that has straight vertical lines).

It seems to be only in the windows default notepad so I think you can forget this one :) Sorry !
