### ISSUE TITLE
Emojis are not monospace

### ISSUE THREAD

**Issue by parzhitsky** [tonsky/FiraCode#1542]
I've noticed that emojis aren't aligned with other characters, which means that they aren't monospace, as other characters are. I hope, these images show what I mean:

<img width="91" alt="image" src="https://github.com/tonsky/FiraCode/assets/59528510/2d16a55f-6f7c-4416-958b-63e2f53562a5">
<img width="88" alt="image" src="https://github.com/tonsky/FiraCode/assets/59528510/59a1534a-066f-464b-a472-4ad448f6e0d3">

But is it possible at all to align or otherwise manipulate them given https://github.com/tonsky/FiraCode/issues/1278#issuecomment-898896626?

**Comment by cormullion** [comment]
This is more of a terminal issue rather than anything to do with the font. Have a look at [this](https://github.com/wez/wezterm/issues/342) issue for example.

**Comment by tonsky** [comment]
Emoji come from a different font, they are not part of Fira Code. Nothing we can do about it
