### ISSUE TITLE
The display of the “&” symbols is not very clear and not clear enough, which makes it feel unfriendly for programming

### ISSUE THREAD

**Issue by jetlong** [tonsky/FiraCode#1545]
The display of the “&” symbols is not very clear and not clear enough, which makes it feel unfriendly for programming

![image](https://github.com/tonsky/FiraCode/assets/6326231/50eac20e-a7f1-4d00-8f83-3642f8addff7)
![image](https://github.com/tonsky/FiraCode/assets/6326231/f1093e0f-d0e7-41ef-9409-8b29c7ad2f7f)

**Comment by tonsky** [comment]
Use ss03 https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets

**Comment by jetlong** [comment]
Thinks
