### ISSUE TITLE
How to Modify character(&) display style？

### ISSUE THREAD

**Issue by bestv5** [tonsky/FiraCode#1546]
For the characters  '&' ,  I am more accustomed to the original style (& or picture 1 style), but not very accustomed to our current style(picture 2).
Can you support it? Or tell me how to modify it ？

picture 1:
<img width="45" alt="image" src="https://github.com/tonsky/FiraCode/assets/15650275/737540af-b228-41ec-9f85-e33cb6d119ea">

picture 2:
<img width="251" alt="image" src="https://github.com/tonsky/FiraCode/assets/15650275/39aeee3b-4962-431c-85a8-b6298678f38b">

**Comment by tonsky** [comment]
Turn on ss03 https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets
