### ISSUE TITLE
wiki: recommended VS Code extension is dangerous

### ISSUE THREAD

**Issue by garymm** [tonsky/FiraCode#1551]
The [wiki recommends](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions#useful-extensions) the ligatures-limited extension, but that extension basically breaks VS Code for me in a way that was very hard to diagnose. [Multiple other users have reported similar issues](https://github.com/kshetline/ligatures-limited/issues). Please stop recommending it.

Many thanks for the awesome font!

**Comment by tonsky** [comment]
Shouldn’t it be resolved through store rating or repo issues? Seems like it works for some people, so it’s at least useful for them?

**Comment by garymm** [comment]
There are plenty of issues on that repo that have gone unaddressed for ~3 years. I have rated it on the store.
At least for me the recommendation here resulted in me spending hours tracking down why my VS Code was not working well, so I wish the recommendation were gone.
Feel free to leave it if you think that's best.
Thanks again!

**Comment by tonsky** [comment]
Ok, added a note about the issues, thanks for bringing this up!
