### ISSUE TITLE
Problem with == in python code if no brackets

### ISSUE THREAD

**Issue by GomZik** [tonsky/FiraCode#156]
See screenshots for example

http://i.imgur.com/XWWFMxA.png
http://i.imgur.com/qTWDHMF.png

Brackets in most cases in python is not "pythonic-way" to write conditions

**Comment by engelfrost** [comment]
This looks like an editor issue. See #59 for example.

**Comment by tonsky** [comment]
That’s tokenization issue in editor, can’t be addressed at font level
