### ISSUE TITLE
Possible OF Licence violation by another party?

### ISSUE THREAD

**Issue by SlySven** [tonsky/FiraCode#1564]
I was just checking on another font and spotted that this repository:  https://github.com/fontmgr/FiraCode *seems* to be offering your font under a GPL 3.0 licence - however as far as I can tell (**I A N**ot **A** **L**awyer!) your choice of the OFL-1.1 licence says:
> ... The OFL allows the licensed fonts to be used, studied, modified and
redistributed freely as long as they are not sold by themselves. The
fonts, including any derivative works, can be bundled, embedded,
redistributed and/or sold with any software provided that any reserved
names are not used by derivative works. The fonts and derivatives,
however, cannot be released under any other type of license...

and required that project to continue to use your choice of license for your work.

**Comment by tonsky** [comment]
Thanks! https://github.com/fontmgr/FiraCode/issues/1
