### ISSUE TITLE
Neither HTML comments work in VS2015 SP1

### ISSUE THREAD

**Issue by aloshka** [tonsky/FiraCode#157]
Neither opening  comments work as ligatures in Visual Studio 2015. Everything else works. 

Have the latest version. 

![2016-03-16 22_46_03-sfcadmin - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/17893887/13836636/05362d3c-ebc9-11e5-8fe2-e004e9df9b57.png)

**Comment by aloshka** [comment]
Wanted to add, that also ~-, <- doesn't work either. I think pretty much everything with hyphens doesn't work at all. Thoughts?

**Comment by tonsky** [comment]
Can’t help you there—that’s editor’s tokenization issue, can’t be addressed
on font level
