### ISSUE TITLE
Language-specific: PHP

### ISSUE THREAD

**Issue by RivGames** [tonsky/FiraCode#1575]
How can I help to add PHP ligatures to `README.md` image? I mean, I wanna see in `README.md` in '**Language-specific**' section the PHP, how can I assist with this? I can name ligatures which is frequently used in PHP.

**Comment by tonsky** [comment]
If you send me a code example that is small enough (10-ish lines) and has many ligatures used, I’ll add it

**Comment by RivGames** [comment]
aha, I see it in "How does it look?" section. But why there are no it in "What’s in the box?" section?) Okay I got it. Sorry for disturbing you.

**Comment by tonsky** [comment]
Got it. Yeah I can add it
