### ISSUE TITLE
Fixed-width emoji and symbols

### ISSUE THREAD

**Issue by craxal** [tonsky/FiraCode#1586]
Emoji (and other symbols) are very useful for conveying information in a compact way, such as in a table. Unfortunately, these emoji and symbols aren't fixed-width characters. Multiline text containing these characters does not line up cleanly. This is most apparent, for example, when creating tables in Markdown:

```
| Column 1 | Column 2 | Column 3 |
|----------|----------|----------|
| I'm OK   | 👎 Boo   | Misalign |
```

I'm not a font expert, but surely something can be done to ensure the width of these characters is fixed or at least aligned (such as spanning the width of two characters) without redesigning every character.

**Comment by kenmcd** [comment]
Fira Code does not contain those emojis, so that is a back-up font - which appears to have a different width.

**Comment by craxal** [comment]
@kenmcd Yes, I know the font itself does not contain emoji. I only wonder if there's a way for the font (or fonts in general) to instruct the system to "pad" non-aligned characters so that they are aligned with the rest of the font.

**Comment by kenmcd** [comment]
I do not know of any way to force characters to be fixed space using the operating system.
You may want to take a look at Nerd Fonts.
https://github.com/ryanoasis/nerd-fonts
They make versions of monospace fonts with icons and symbols already merged into them.
Including Fira Mono. 
So take a look there first; it may be useful to you.

Merging color emojis is kind of a minefield.
Nerd Fonts has tools to do font merging.
[fonttools](https://github.com/googlefonts/fonttools) and [nanoemoji](https://github.com/googlefonts/nanoemoji/) also have tools to merge fonts.
I have seen this discussed before in both of those projects, so perhaps someone has already done it.

**Comment by tonsky** [comment]
> if there's a way for the font (or fonts in general) to instruct the system to "pad" non-aligned characters so that they are aligned with the rest of the font

No way. The only solution here is if the app that does text rendering does that. I _think_ some terminals force emoji to character grid, although I’m not sure which ones

**Comment by alexeyten** [comment]
I think almost all terminals do that. But not text editors.
