### ISSUE TITLE
Progress Bar in VSCode

### ISSUE THREAD

**Issue by taamtera** [tonsky/FiraCode#1595]
Built-in progress bar character rendering issue in VSCode Terminal:
![image](https://github.com/tonsky/FiraCode/assets/26496842/5aa6516a-a404-451d-8822-8212c4694d23)

as you can see tiny single pixel lines exist between the bars compared to uni-code "█" fills space properly
![image](https://github.com/tonsky/FiraCode/assets/26496842/89c12c3a-cd54-44af-8983-4e3fab5b83f4)

**Comment by mfocko** [comment]
IIRC this is related to the rounding of the dimensions by the terminal, Kitty “hacks” around this by handling these characters specially; You can try to minimize the rounding error by changing the font size, but it's not an error on the font side.

**Comment by tonsky** [comment]
That's correct. That's unfortunately how fonts work. Nothing I can do here
