### ISSUE TITLE
C/C++ bitwise xor similar to logical and

### ISSUE THREAD

**Issue by ltlollo** [tonsky/FiraCode#16]
Hi, really enjoy the font, but i recently noticed that the logical and (&&) and the bitwise xor (^) are indistinguishable.
This is what you would see in a C program:

    a ∧ b // a and b
    a ^ b // a xor b

I guess this is less problematic, but c++ uses && to denote rvalue references, eg:

    auto fun(Type&& value);

**Comment by tonsky** [comment]
Ok, this is serious. Gotta turn it off then

**Comment by killercup** [comment]
Like `&&` is used in C++ for references, `||` is used in other languages like Ruby or Rust for closures without arguments. I'm not sure there exists a way to distinguish those cases from "or" (except based on editor support).

**Comment by krono** [comment]
Also, in Smalltalk `||` can be a different thing from 'or', namely an empty list of arguments.

**Comment by tonsky** [comment]
You all are right. Reverted them in 0.4 to more traditional look.
