### ISSUE TITLE
Notepad++ instructions should reference Default Font, not Global Override

### ISSUE THREAD

**Issue by pryrt** [tonsky/FiraCode#1607]
re: https://github.com/tonsky/FiraCode/wiki/Notepad-Plus-Plus-instructions

**Settings > Style Configurator > Global Styles> Global Override** is the wrong way to set the default font in Notepad++ -- it will break other features of Notepad++.  The right way is using **Settings > Style Configurator > Global Styles > Default font**.  Please fix your wiki's instructions.

**Comment by tonsky** [comment]
Thanks! Updated
