### ISSUE TITLE
Suggestion to wiki page

### ISSUE THREAD

**Issue by createyourpersonalaccount** [tonsky/FiraCode#1621]
I could not figure out how to make the edit myself. On <https://github.com/tonsky/FiraCode/wiki/LaTeX-instructions> you can add the suggestion that if
```
\setmonofont{Fira Code}
```
does not work, then
```
\setmonofont{FiraCode-Regular.ttf}
```
might work. I had this issue on Debian 12 with the `fonts-firacode` apt package, where `xdvipdfmx` complained it could not find `~/.local/share/fonts/woff/FiraCode-Regular.woff`.

**Comment by tonsky** [comment]
Thanks! Added
