### ISSUE TITLE
[BUG (major)]  "A" instead of ZWNJ

### ISSUE THREAD

**Issue by salarmehr** [tonsky/FiraCode#164]
The font display "A" instead of ZWNJ character. 
As a bounce, if you provide a simple tiny visible glyph, the programmer can find it easier. Here is some sample glyph: http://www.utf8icons.com/character/8204/zero-width-non-joiner
In that page code2000 and GNU Unifont glyph are far more proper for ZWNJ. If you add that FiraCode will be the hero coding font in Languages that use ZWNJ. Currently, it's makes a lot trouble in text processing.

**Comment by tonsky** [comment]
Do you have zero-width space printed ok? ZWS is in the font, ZWNJ is not, you probably have it substituted from some other font. What’s your setup (editor/os)? What font does A comes from?

**Comment by salarmehr** [comment]
I use phpstorm.

**Comment by tonsky** [comment]
This is probably a bug of IDEA, and it’s somehow related to ligatures handling. I have similar problem with Hasklig as well. Please report an issue here: https://youtrack.jetbrains.com/issue/IDEA-127539

**Comment by tonsky** [comment]
Sorry, IDEA has no problem rendering zero-width joiners in Hasklig in lastest 2016.1.1 build

**Comment by tonsky** [comment]
In fact, just reported it myself https://youtrack.jetbrains.com/issue/IDEA-127539#comment=27-1409192
