### ISSUE TITLE
[IDEA 💡] Providing a symbol for common special purpose invisible characters

### ISSUE THREAD

**Issue by salarmehr** [tonsky/FiraCode#165]
Providing a distinct symbol for the  invisible characters (BOM, Combining Grapheme Joiner, Left-to-right mark / Right-to-left mark, Soft hyphen Word joiner, Zero-width joiner, Zero-width non-joiner, Zero-width space)  is really useful while creating UI and processing text.  (https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Special-purpose_characters) 

https://www.microsoft.com/typography/otfntdev/glyphs.htm
https://commons.wikimedia.org/wiki/Category:IEC_60417_symbols

When you are coding you want to see such character. They are needed to be invisible only for the end-user only. Similar to clicking on ¶ when you are authoring a document in MS word or other text-editors. e.g.  run this in js console: ‍‍`"OK"=="O‌K" `. It returns false for me. Do you know why? 
The advantages of seeing invisible characters are specially clear for me and whose their writing system use such characters frequently (Persian, German, Hebrew, …). 

There not many invisible special purpose characters. these should be enough to be included: 
![bgh2t 1](https://cloud.githubusercontent.com/assets/2582036/14582496/c2a54e4c-041b-11e6-9a6e-79f48c367ca1.png)

Please consider seeing the links provided on the first post.   

Take ZWNJ as an example, If you provide a simple tiny visible glyph, the programmer can find it easier. Here are some sample glyphs: http://www.utf8icons.com/character/8204/zero-width-non-joiner
In that page code2000 and GNU Unifont glyph are far more proper for ZWNJ. If you this is done, this code will be the hero programming font in the languages that use ZWNJ. Currently, it's invisibility makes a lot of trouble in text processing.

**Comment by tonsky** [comment]
I thought the idea of invisible characters was for them to stay invisible? What’s the point in making them visible?

**Comment by salarmehr** [comment]
When you are coding use want see them. They are needed to be invisible for the end-user only. Similar to clicking on ¶ when you are authoring a document in MS word or other text-editors.

**Comment by tonsky** [comment]
Why do you need invisible characters in code?

**Comment by salarmehr** [comment]
copy and run this in js console: ‍‍`"1"=="1‌" `. It return false for me. Do you know why?

**Comment by tonsky** [comment]
What about my question? In what situations would you need to be able to see invisible characters?

Thinking this through, shouldn’t it be a feature of the editor? There’s probably a huge range of these, putting them all into font doesn’t seem like a future-proof solution. E.g. my LightTable prints a red dot for each invsible character:

<img width="143" alt="screen shot 2016-04-08 at 14 31 43" src="https://cloud.githubusercontent.com/assets/285292/14378427/0d92ce58-fd9f-11e5-868d-9a04f67ee97d.png">

**Comment by tomByrer** [comment]
> Thinking this through, shouldn’t it be a feature of the editor?

For Atom, Brackets, & Notepad++ it is, & sometimes I use it.

There have been times I thought an unique character would be nice for 'visible' space, like a less wide underscore, but very low priority for me.

**Comment by salarmehr** [comment]
@tonsky  There are a lot of such scenarios, in particular in text-processing settings. For example testing RegExp can be far less tricky when you can see all characters. 

Actually there not many invisible special purpose characters. these should be enough to be included: 

![bgh2t 1](https://cloud.githubusercontent.com/assets/2582036/14582496/c2a54e4c-041b-11e6-9a6e-79f48c367ca1.png)

Please consider seeing the links provided on the first post.
