### ISSUE TITLE
Was working with kdevelop but does not anymore

### ISSUE THREAD

**Issue by MalcolmMielle** [tonsky/FiraCode#166]
Hello,

So the latest version of FiraCode do not work with Kdevelop but the version 0.6 do. I tried version 1 and it does not work again. Weirdly, version 0.5 does not work. Only version 0.6 do.

That would be nice if every version could work with Kdevelop. I don't know what's special about version 0.6 that makes it works

**Comment by tonsky** [comment]
Me neither. And I don’t have linux to test it out. Were you using TTF file
format from 0.6 or OTF?

**Comment by MalcolmMielle** [comment]
I'm using the OTF file

**Comment by iandoug** [comment]
This is basically the issue I'm having ... it's not just KDevelop (which, AFAIK, uses embedded Kate for the editor), but other apps too. Something changed between versions of Fira Code that broke the compatibility.

**Comment by MalcolmMielle** [comment]
I ask on the KDE forum and they indeed use the Kate editor. But weirdly, other version of FiraCode do work on Kate

**Comment by MalcolmMielle** [comment]
Adding some info here :)

The lastest version seems to be working in kdevelop5
