### ISSUE TITLE
Please add #!/,  (), and }) ligs

### ISSUE THREAD

**Issue by easyaspi314** [tonsky/FiraCode#169]
`#!/` is used in shell scripts, like:

``` shell
#!/system/bin/sh
echo "Hello, world!"
```

`()` and `)}` is used in many languages as well, such as after a Java interface override. Both are used commonly, especially `()`. This one should be a given, especially since we have a box for `[]`.

``` java
myButton.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {
        FragmentManager manager = getActivity().getFragmentManager();
        FragmentTransaction transaction = manager.beginTransaction();
        MyFragment myFragment = MyFragment.newInstance();
        myFragment.setArguments(getActivity().getIntent().getExtras());
        transaction = transaction.replace(android.R.id.content, myFragment);
        transaction.commit();
    }
});
```

In Fira Code:
![screen shot 2016-04-12 at 6 40 52 pm](https://cloud.githubusercontent.com/assets/6258309/14477872/d3d82198-00de-11e6-823e-37b8b61a42cb.png)

**Comment by easyaspi314** [comment]
@tonsky how about this for an idea? 

![double parenthesis](https://cloud.githubusercontent.com/assets/6258309/14494499/20923ec2-0159-11e6-8be4-3ecc65e32ec0.png)

**Comment by tonsky** [comment]
@easyaspi314 Not sure about that. Don’t like uneven spacing, and you would never guess all the contexts where this combination might pop up

**Comment by easyaspi314** [comment]
Well what about the ); ?

**Comment by tonsky** [comment]
I can tune the spacing, but I don’t see it as an improvement. You see, idea
of Fira Code was to make sequences that are one logical operator look like
one symbol. In this case, semicolon and closing paren are not part of the
same sequence. In fact, they’re part of different constructs. I don’t think
I should move them closer together.

**Comment by easyaspi314** [comment]
OK. Do you think you can do anything with `#!` and `#!/`?

**Comment by tonsky** [comment]
#! makes sense, yes. But slash in #!/ is, again, not part of that logical
sequence

**Comment by easyaspi314** [comment]
OK.
