### ISSUE TITLE
Unligature request: >=<

### ISSUE THREAD

**Issue by achpru** [tonsky/FiraCode#171]
When >= is immediately followed by a <, it's hardly a greater-than-or-equal operator
![capture](https://cloud.githubusercontent.com/assets/18448091/14503819/5d4c247a-01ba-11e6-8f35-332a1b3d0c82.PNG)

**Comment by MadcapJake** [comment]
If you're using Atom, you can turn off ligatures inside of strings. Check [here](https://github.com/tonsky/FiraCode/wiki/Atom-instructions) for how to achieve this.

**Comment by miniBill** [comment]
@tonsky Isn't this fixed?

**Comment by tonsky** [comment]
Yes, thanks! Fixed in 1.206 issue #548
