### ISSUE TITLE
Glyph request: ∆ 'INCREMENT' (U+2206)

### ISSUE THREAD

**Issue by jdelkins** [tonsky/FiraCode#174]
This is a pretty common symbol which I find many mono fonts support. [fileformat.info link](http://www.fileformat.info/info/unicode/char/2206/index.htm).

**Comment by tonsky** [comment]
Shouldn’t be a problem. How is it different from capital delta? http://www.fileformat.info/info/unicode/char/0394/index.htm

**Comment by jdelkins** [comment]
For some fonts, the glyph is slightly different at high point sizes, but they are essentially the same. I don't care about any distinction: for my purposes, I'd be happy to have the U+2206 code point linked to the U+0394 glyph (or copy/paste, whatever works). Thanks!

**Comment by tonsky** [comment]
I'm wondering, if I want to make them more distinguishable, what should I
emphasise?

**Comment by jdelkins** [comment]
The top-to-bottom-right leg is slightly bolder in U+2206
