### ISSUE TITLE
Please add git merge conflict ligature

### ISSUE THREAD

**Issue by adinvadim** [tonsky/FiraCode#176]
```
<<<<<<< HEAD
    <link type="text/css" rel="stylesheet" media="all" href="style.css" />
=======
    <!-- no style -->
>>>>>>> master
```
Now it's looks not so good
https://www.dropbox.com/s/gkbddo1r50vyhg3/Screenshot%202016-04-20%2019.53.21.png?dl=0

**Comment by suy** [comment]
This is a duplicate of #49.

**Comment by surma** [comment]
@adinvadim Can you close this in favor of #49?
