### ISSUE TITLE
Not displayed correctly in XFCE terminal

### ISSUE THREAD

**Issue by Rudloff** [tonsky/FiraCode#178]
The font is not displayed correctly in xfce4-terminal 0.6.3:
![capture d ecran - 22042016 - 11 05 28](https://cloud.githubusercontent.com/assets/840125/14737029/4f9a6884-087a-11e6-9abd-20bf7bf098a4.png)

The same thing with DejaVu:
![capture d ecran - 22042016 - 11 06 20](https://cloud.githubusercontent.com/assets/840125/14737039/55e16e7c-087a-11e6-98fb-e89f3be4f9fc.png)

**Comment by tonsky** [comment]
Yep, but it’s already reported as “doesn’t working” on README page
