### ISSUE TITLE
Java <~> is a half ligature

### ISSUE THREAD

**Issue by rickmark** [tonsky/FiraCode#179]
Font combines <~ but the > is not connected appearing strange

**Comment by tonsky** [comment]
Wow, what does this thing mean in Java?

**Comment by MadcapJake** [comment]
I don't believe there is a `<~>` operator in Java.  `~` is bitwise complement.

**Comment by madisp** [comment]
IntelliJ collapses type parameters into `<~>`, example:

https://www.dropbox.com/s/13iildrlpuohwan/Screenshot%202016-06-02%2009.38.30.png

**Comment by tonsky** [comment]
related https://youtrack.jetbrains.com/issue/IDEA-157022

**Comment by tzm41** [comment]
Nice job. `<~>` is also used in Swift a lot of times as custom two-way mapping operators.
