### ISSUE TITLE
Patched versions for powerline

### ISSUE THREAD

**Issue by light2yellow** [tonsky/FiraCode#180]
I use [zsh](http://www.zsh.org/) with [grml-zsh-config](https://grml.org/zsh/) and [agnoster](https://gist.github.com/agnoster/3712874). On the screenshot, the last character of the prompt is rendered kind of "separately", which is not the desired behaviour (although on the second screenshot it is only slightly visible). You can find character codes on agnoster's gist page.

![screenshot_2016-04-24_16-53-24](https://cloud.githubusercontent.com/assets/10786469/14768253/227927f4-0a3d-11e6-9d8b-24aa4e459304.png)

![screenshot_2016-04-24_17-12-55](https://cloud.githubusercontent.com/assets/10786469/14768340/cdf96592-0a3f-11e6-8c58-5d98a6aee784.png)

**Comment by light2yellow** [comment]
By this time I figured out that the font must be compatible with powerline. @tonsky Is it possible to add them into this repository? Also it would be to see them in bohoomil's infinality-bundle-fonts repo.

**Comment by tonsky** [comment]
It’s impossible to achieve perfect rendering of powerline that will work in all terminals. If I fix one, another one will break. Sorry
