### ISSUE TITLE
[VS 2015] Not all ligatures work

### ISSUE THREAD

**Issue by lokki** [tonsky/FiraCode#181]
For me, looks like all ligatures that contain "-" do not work in VS 2015:

http://prntscr.com/axfczm

Is it just me?

**Comment by tonsky** [comment]
Nope, it’s VS tokenization issue. See

- https://github.com/tonsky/FiraCode/issues/43
- https://github.com/tonsky/FiraCode/issues/32
- https://github.com/tonsky/FiraCode/issues/157
