### ISSUE TITLE
Fix <!-- www --> preview in screenshot

### ISSUE THREAD

**Issue by MrMitch** [tonsky/FiraCode#186]
`<!-- www -->` is rendered ![right](https://cloud.githubusercontent.com/assets/576772/15392404/2f33ecb6-1dc7-11e6-9f2f-d73c856800cf.png) 

when it's showcased as ![wrong](https://cloud.githubusercontent.com/assets/576772/15392409/3c00191a-1dc7-11e6-96a5-1c8dee651746.png) in the image included in the README

**Comment by tonsky** [comment]
Thanks for spotting this! I was using another version of the font to render these pictures. Updated with 1.102

**Comment by MrMitch** [comment]
:100:
