### ISSUE TITLE
=== feels "bulkier" than the other glyphs

### ISSUE THREAD

**Issue by JobLeonard** [tonsky/FiraCode#187]
First, I fully acknowledge that this is my subjective experience. Second, I really enjoy the font as a whole and happily use it in my code editor, so don't take this the wrong way.

I think giving the `===` and `!==` glyphs three lines to make it more distinct from `==`, `!=` and `=\=` is a great choice. However, combined with the fact that it fills three character spaces, the glyph becomes more.. I dunno, like a filled in block, which makes it visually dominant.

Not sure how one would fix that though - perhaps making the lines a bit shorter, although might create issues with creating too much empty space with surrounding characters.

**Comment by nick4fake** [comment]
Maybe === sign may just take less height?

**Comment by tonsky** [comment]
Fixed in 5.0 along with #383. Enable with `ss08`
