### ISSUE TITLE
[question] Do you also use ligatures to even out the kerning of regular characters?

### ISSUE THREAD

**Issue by JobLeonard** [tonsky/FiraCode#188]
If you look at the [monoid website](http://larsenwork.com/monoid/) and switch the ligatures on and off, you will notice that the ligatures don't just add symbolic support, they also even out spacing of characters within words. It almost makes it look like a proportional font sometimes!

I was wondering if Fira Code also does this, and if not, if it would be doable to add it (I can imagine it being a _lot_ of work to fix all the character combinations!)

**Comment by tonsky** [comment]
No, I probably won’t do it. Too much work :)

**Comment by JobLeonard** [comment]
I don't blame you :)

Maybe we could convince the Fira Mono people to implement it upstream?
