### ISSUE TITLE
The 'Haskell' code example in the readme is actually Livescript.

### ISSUE THREAD

**Issue by 98devin** [tonsky/FiraCode#189]
For reference, this is the code in question:
```livescript
take = (n, [x, ...xs]:list) -->
  | n <= 0     => []
  | empty list => []
  | otherwise  => [x] ++ take n - 1, xs

last-three = reverse >> take-three >> reverse
```
This is not valid Haskell, but it IS valid Livescript; perhaps that is what you meant? The commas
and parentheses in function calls and definitions, as well as the hyphens in identifiers give it away as not being Haskell. I would also suggest replacing `take-three` with `take 3` since it's otherwise undefined.

A literal translation into Haskell of the above code to use instead if you want:
```haskell
take :: Int -> [a] -> [a]
take n list@(x:xs)
  | n <= 0     => []
  | list == [] => []
  | otherwise  => [x] ++ take (n - 1) xs

lastThree :: [a] -> [a]
lastThree = reverse . take 3 . reverse
```

However, it may be more idiomatic to use pattern matching here instead:
```haskell
take :: Int -> [a] -> [a]
take 0 _      = []
take _ []     = []
take n (x:xs) = [x] ++ take (n - 1) xs
{- etc -}
```

Hopefully this is helpful. I would submit a pull request, but I can't render the text in the same way that you have.

**Comment by tonsky** [comment]
Thanks for the heads-up. I decided to go with LiveScript version because it shows more of Fira Code features. If you can come up with a nice small Haskell examples, preferably showing some other ligatures, I can add it too
