### ISSUE TITLE
Disjunction ligatures

### ISSUE THREAD

**Issue by channingwalton** [tonsky/FiraCode#191]
Hi,
it would be great to support \/ as something like ∨

Thanks,

Channing

**Comment by engelfrost** [comment]
What does it mean? 

I can only come up with regular expressions, but it would do more harm than good there...

`var re = /\/path\//;`

**Comment by channingwalton** [comment]
It is a symbol that represents disjunction (logical OR), (see the truth table here https://en.wikipedia.org/wiki/Logical_disjunction). It appears in a widely used scala library.

I agree it would be completely wrong in regex.

**Comment by tonsky** [comment]
Dupe of #738
