### ISSUE TITLE
Ligature -> does not work in Visual Studio 2015

### ISSUE THREAD

**Issue by asibahi** [tonsky/FiraCode#196]
Can't figure out what the problem is. All the other ligatures I can think of (except `<-`) work fine. See image.

<img width="882" alt="capture" src="https://cloud.githubusercontent.com/assets/17417266/15930745/2a11e31a-2e1a-11e6-9448-4df3a83e0614.PNG">

**Comment by toburger** [comment]
This is a known problem and the Visual Studio team is reviewing the issue: https://connect.microsoft.com/VisualStudio/feedback/details/2504318/hyphens-not-supported-for-ligatures

**Comment by asibahi** [comment]
Hmm. It is weird. I noticed the other day that in VS Code with the OCaml extension it is selective about which ligatures it renders and which it doesn't.

**Comment by tonsky** [comment]
Closing as I can’t do anything about it. Open an issue on MS bugtracker
