### ISSUE TITLE
Using FiraCode in Atom hides line numbers 

### ISSUE THREAD

**Issue by joshwalsh** [tonsky/FiraCode#197]
I'm using Atom 1.8.0 with FiraCode per the instructions.  Everything works fine in editor as far as I can tell, but line numbers are hidden.  By swapping Fira Code font for the default (blank) line numbers come back.

**Comment by MadcapJake** [comment]
I use Atom (1.8.0) and Fira Code and I don't have this issue.

**Comment by tonsky** [comment]
@joshwalsh what OS are you on? Font size? Fira Code version? Any plugins?
