### ISSUE TITLE
Doesn't work in QtCreator while Hasklig works

### ISSUE THREAD

**Issue by firegurafiku** [tonsky/FiraCode#2]
I've just downloaded FiraCode 0.1 and Hasklig 0.4, and tested them in QtCreator 3.2.2 on Fedora Linux 20 x64. It seems that FiraCode doesn't do any ligature substitution, unlike Hasklig, which works fine. What could I've done wrong?

**Comment by Zhigalin** [comment]
Same problem

**Comment by tonsky** [comment]
Guys, I’d like to fix this, but have no idea what the reason is. I don’t even have linux to check this out. If somebody could figure it out and fix, he/she would help a lot of people.

**Comment by firegurafiku** [comment]
In updated Qt Creator 3.3.1 on Fedora Linux 21 x64 the *same* font file now works. Seems like a QtCreator's problem.

**Comment by Lazin** [comment]
Yep. It works in 3.0, it was broken in 3.2 and works again in 3.3.2.

**Comment by tonsky** [comment]
Cool :)
