### ISSUE TITLE
garbled font in gvim but not in terminal or vim

### ISSUE THREAD

**Issue by 2vek** [tonsky/FiraCode#20]
After setting font in `gvimrc` using `set gfn=FiraCode\ 9`, I opened gvim, I got this 
![screenshot from 2015-05-25 19 01 29](https://cloud.githubusercontent.com/assets/2778313/7797989/74c87188-0311-11e5-9203-9ee6f8d8ac88.png)

I set the terminal font to FiraCode, fonts in vim are showing as expected
![screenshot from 2015-05-25 19 03 09](https://cloud.githubusercontent.com/assets/2778313/7797990/74d0f042-0311-11e5-9112-ed7f4cb3cedf.png)

I rebuilt system font cache using `fc-cache -fv` just to be sure. I am on debian(8/jessie) linux.

This issue is only specific to gvim and with this font only, reproducible everytime. I tried this font with firefox, gedit, system ui font, everywhere it is working as expected. Previously, I was using `Ubuntu mono` with gvim, which was working normally.

**Comment by jscappini** [comment]
I have the same issue. It happens only with this font on gVim. I'm using this font in the terminal also but without issues.

OS is Debian Jessie also.

**Comment by tonsky** [comment]
It’s a known problem with gvim. Sorry.
https://groups.google.com/forum/#!topic/vim_dev/0sETSAwe5Wo
