### ISSUE TITLE
windows installer not signed when building on mac

### ISSUE THREAD

**Issue by symbyte** [tonsky/FiraCode#202]
Expected behavior: 

When building on local mac dev machine with a valid code signing identity using the `build -ow` command to build for both windows and mac, generate signed mac application and signed Squirrel.Windows installer. 

Actual behavior:

Only the mac application is signed using valid code signing identity, windows installer gives warning of unknown publisher on installation. 

Have I misunderstood what code signing is supported on mac development machine?

**Comment by symbyte** [comment]
Wrong repo.

**Comment by tonsky** [comment]
You got me worried for a couple of seconds :))))

**Comment by symbyte** [comment]
Yeah, sorry about that! I was in the middle of writing an issue for another repo when one of my coworkers linked me this repo and told me to check out its awesomeness. This font is awesome! Sorry for the scare!

**Comment by tonsky** [comment]
No problem! Glad you liked it!
