### ISSUE TITLE
Ampersands look like the number "6"

### ISSUE THREAD

**Issue by broady** [tonsky/FiraCode#209]
![cnv2afwumaaspdt](https://cloud.githubusercontent.com/assets/24982/16851452/887b6142-49b8-11e6-9be6-f0f91bcf3e05.jpg)

**Comment by tonsky** [comment]
Looks more like number 8 for me

**Comment by MadcapJake** [comment]
That's how the ampersand looks in Fira Mono

**Comment by aaaxx** [comment]
Ampersand itself is already a ligature (how ironic) of the Latin word “et”, meaning “and”. Some font designs reflect that, making it look like a recognizable “Et”.

**Comment by pforhan** [comment]
I understand it's based off the original, but I concur, this is lower in readability than other fonts, the opposite of what's desired.

**Comment by derekschinke** [comment]
Yeah, there's already a code point for "🙲" instead of "&". Not sure why Fira Mono decided to go with the older version that can be mixed up with other characters.

**Comment by wopian** [comment]
I'd say the modern sans ampersand looks even closer to the number 8 than the traditional ligature used by Mono does.

**Comment by RubenVerg** [comment]
I really love FC also because of the ampersand looking like a 6.

________________________________
