### ISSUE TITLE
Slightly more elongated variant of the font

### ISSUE THREAD

**Issue by brigadier** [tonsky/FiraCode#213]
Hi, 
It would be nice to have somewhen in teh future slightly more elongated variant of the font, for example based on Bitstream Vera Sans Mono. The Fira Code characters look a bit too square and less articulated and having too much free space than Bitstream Vera ones for me. Maybe just a matter of habit though.

Screenshot of Bitstream Vera Sans Mono vs FIraCode in IntelliJ Pycharm 2016 http://i.imgur.com/3wsldds.png

**Comment by tonsky** [comment]
I doubt I’d do that for Fira Code (I don’t draw basic characters themselves, they’re taken from Mozilla’s Fira Mono). Maybe only if Carrois did Fira Mono Condensed

**Comment by tonsky** [comment]
You can try any of alternatives, maybe they’ll suit you better (see README for the list)
