### ISSUE TITLE
Add "null conditional operator" ?.

### ISSUE THREAD

**Issue by JamesFaix** [tonsky/FiraCode#215]
C# 6 and VB 14 have a new operator called the "null conditional operator", represented as **?.** or **?[**. https://msdn.microsoft.com/en-us/library/dn986595.aspx

The **?.** version is used when trying to dereference a member of an object that may be null.  For example, 
`var name = someObject?.Name;` 
assigns to the variable `name` either the name of `someObject`, or `null` if `someObject` is `null`.

The **?[** version is used when trying to access an array element of an array that may be null.  For example,
`var item = someArray?[3];`
assigns to the variable `item` either the item at index in `someArray`, or `null` if `someArray` is `null`.

I would really love a ligature for **?.**.  I think the period should ideally be spaced the same as the bottom of the 2nd question mark in the **??** ligature.  

A ligature for **?[** should probably be added for symmetry.

**Comment by krux02** [comment]
I would say yes to `?.` but no to `?[`. I just don't see what a ligature can improve on the appearance. But also concider, this operator is implemneted differently in different programming languages:

Ruby: `&.`
Perl6: `.?`

https://en.wikipedia.org/wiki/Safe_navigation_operator

**Comment by JamesFaix** [comment]
@krux02 I agree that **?[** would not be improved much by ligaturization.  I also did not know how widely such an operator was available, thanks for the link.  "Safe navigation" is a way better name than "null conditional" also.  Microsoft naming..ugh.

**Comment by kosiakk** [comment]
Certainly, dots in Elvis operator `?:` and in Pirate Elvis operator `?.` should all be of the same size. Currently they aren't, so my Kotlin code looks less perfect.

**Comment by kosiakk** [comment]
The first line is the current version, 1.201 rendered in Idea.
![image](https://cloud.githubusercontent.com/assets/368248/18330201/804aabf2-7557-11e6-948c-79a9b8ff2c48.png)



The second line is my suggestion:

1. Original version: dots are different and not aligned

2. Two dots under `?.` are copied directly from `..` ligature, including the spacing. 
Semicolon dots are made bigger (ugly)

3. Minimal change - just the spacing is adjusted. All glyphs are original.
Smaller dot highlights the secondary role of `?` in this ligature.

4. All dots are taken from the question mark and are too small.

5. I guess, the best would be take the dot from `:` glyph - its size fits perfectly in between.
Cons: the importance of `.` is lost a bit, and it might look misaligned in the `long().chainOf()?.calls()`
