### ISSUE TITLE
F# -> and <- in Visual Studio - is there a trick?

### ISSUE THREAD

**Issue by danieljsummers** [tonsky/FiraCode#220]
I'm using 1.200 on Windows 10 using Visual Studio Community 2015.  The font is great - I **love** the way it cleans up the display!

Nearly all of the ligatures are rendered properly.  In the attached screenshot, you'll see `<|` rendered as the left-pointing triangle.  F# uses `->` to indicate the beginning of a function, or to delineate types in a signature; it uses `<-` to represent variable assignment (`=` is always a boolean operator unless you're explicitly initializing a variable).  Neither of these arrows are being converted to their corresponding ligatures.  I've tried some of the other arrows ( `<==` , `<=<` , etc.) and they work; it's just these two that don't.

Is there a setting I'm missing, or have I stumbled on a bug?

![example](https://cloud.githubusercontent.com/assets/880348/16936382/ccb66b4c-4d2b-11e6-8809-10c29681ed7d.png)

**Comment by stuart-lang** [comment]
@danieljsummers It's not you, it's a bug with VS, ligatures with a ```-``` do not work.

See here:
https://connect.microsoft.com/VisualStudio/Feedback/Details/2415273
https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/12983895-fix-ligatures

I hope they fix it

**Comment by tonsky** [comment]
A lot of editors suffer one form or another of this. Some ligatures don’t work in Atom in certain syntaxes, for example. This is related to how “fair” tokenization for syntax highlight is implemented. I suspect some grammars “cheat” by highlighting `-` and `>` as separate tokens. You can’t notice it in a regular font, but that split has a bad effect on ligatures. This should be filed to VS bugtracker, if they have one
