### ISSUE TITLE
Handle lots of consecutive slashes ///////////

### ISSUE THREAD

**Issue by Offirmo** [tonsky/FiraCode#225]
With all their ligatures, consecutives slashes used as spacer /////////// don't look good :
![screen_20160722-00h57_24001](https://cloud.githubusercontent.com/assets/603503/17041589/475908d2-4fa7-11e6-863c-6d35b0e1f293.png)

**Comment by cciotti** [comment]
What editor are you using? I don't see this in IntelliJ 2016.2 or on a webpage with Chrome (Version 54.0.2803.0 canary) - both on a mac.

**Comment by tonsky** [comment]
This was fixed in latest font version 1.200. Try updating

**Comment by Offirmo** [comment]
Using Webstorm 2016.2 latest on Windows 10, latest font downloaded yesterday.

**Comment by jdreesen** [comment]
It works correctly for me in PhpStorm 2016.2 on Windows 7 with FiraCode 1.200.

**Comment by tonsky** [comment]
@Offirmo please make sure the version of the font is 1.200. E.g. you should see `</>` as a single glyph; plus sign `+` should be large, about the height of lowercase letter. If you are sure, the report it to JetBrains issue tracker.
