### ISSUE TITLE
Broken "mm" ligature

### ISSUE THREAD

**Issue by jmsfwk** [tonsky/FiraCode#227]
When I use the letters "mm" together they are shifted to the right, overlapping with the characters there and leaving a large space to the left.

<img width="281" alt="broker 'mm' example" src="https://cloud.githubusercontent.com/assets/9892048/17078717/2f509e5c-50f2-11e6-9c64-9f9180d5e6b3.png">

**Comment by tonsky** [comment]
That's not a Fira on screenshot

**Comment by jmsfwk** [comment]
Sorry. It was Monoisome.
