### ISSUE TITLE
Some characters does not showing properly in ubuntu 

### ISSUE THREAD

**Issue by absiddiqueLive** [tonsky/FiraCode#228]
I faced problem with <, >, =, etc [< & = just disappears & > replace by => ]
I faced the problem on [Terminator](http://gmacario.github.io/howto/install/ubuntu/terminal/2015/11/15/installing-terminator-on-ubuntu-1404.html) 

# By FiraCode with error
![fira probelm](https://cloud.githubusercontent.com/assets/11833526/17086797/1d036adc-521d-11e6-8e82-d252c272a18b.png)
![fira problem 2](https://cloud.githubusercontent.com/assets/11833526/17086796/1cffe344-521d-11e6-8c09-5c28812e644e.png)

# By monospace normal view
![original view](https://cloud.githubusercontent.com/assets/11833526/17086798/1d0408c0-521d-11e6-98d0-d9029e539f61.png)
![original view 2](https://cloud.githubusercontent.com/assets/11833526/17086799/1d0a84f2-521d-11e6-844a-ff885133445b.png)

**Comment by tonsky** [comment]
That’s why Terminator is on “unsupported” list in Fira’s README. Here’s related bug report https://bugs.launchpad.net/terminator/+bug/1604861

**Comment by absiddiqueLive** [comment]
Thanks @tonsky 
Is there any terminal that support FiraCode best ? 
Like terminator.
![terminator](https://cloud.githubusercontent.com/assets/11833526/17131571/dedd06ea-533f-11e6-9121-1f22b024ded9.png)

**Comment by tonsky** [comment]
Consult the readme. They are all listed there
