### ISSUE TITLE
C# Doc Comments

### ISSUE THREAD

**Issue by mysteriouspants** [tonsky/FiraCode#23]
By default C# (or at least the Visual Studio autocompletion) uses three slashes to mark a documentation comment before a type or method:

    /// <summary>
    /// This class does the things with the stuff.
    /// </summary>
    public class Widget
    {
      // ...
    }

On Visual Studio Community 2013, Fira Code 0.3, this renders in a rather unfortunate way (in my opinion):

![font rendering](https://cloud.githubusercontent.com/assets/278804/7805123/85c52520-0321-11e5-8aa2-2fe9deba2a08.PNG)

Is there a way to scoot that third slash closer to the others?

**Comment by tonsky** [comment]
Fixed in 0.5

**Comment by mysteriouspants** [comment]
Awesome, thanks!
