### ISSUE TITLE
atom. whereis "Menu -> Open your stylesheet" ?

### ISSUE THREAD

**Issue by jt3k** [tonsky/FiraCode#230]
in this wiki https://github.com/tonsky/FiraCode/wiki/Atom-instructions you  write  "Open your stylesheet"  but i not have this item in menu.

![](https://i.imgur.com/TDRxNSi.png)

**Comment by ice5050** [comment]
Search for "Toggle Command Palette" and then "Open your stylesheet"
![image](https://cloud.githubusercontent.com/assets/2921893/17141923/50091b28-5378-11e6-8a4d-d14c8d865129.png)
![image](https://cloud.githubusercontent.com/assets/2921893/17141964/7c165c30-5378-11e6-9394-7ff468c56488.png)

**Comment by tonsky** [comment]
File > Stylesheet...

**Comment by jt3k** [comment]
thanx for all.  i am fix wiki yesterday
