### ISSUE TITLE
Redesign >= and <= ligatures

### ISSUE THREAD

**Issue by jbellsey** [tonsky/FiraCode#231]
Most of the ligatures are excellent at reducing noise, but these in particular are hard to read. The extra line is too tight to the angle:

![image](https://cloud.githubusercontent.com/assets/1831399/17152055/01a9936a-532b-11e6-88dd-3a662bf34109.png)

I'd prefer either adding a bit more air between the angle and the "equals" line, or making the "equals" line horizontal (rather than angled). Either would let your brain process the symbol more easily.

**Comment by tonsky** [comment]
I fixed that in 1.200, please update
