### ISSUE TITLE
Broken ligatures containing -

### ISSUE THREAD

**Issue by jasoncrump** [tonsky/FiraCode#233]
It looks like ligatures containing the a '-' character are not working correctly. The image below shows the working and broken ligatures (in VS2015) as far as I could tell (sorted in the same order as your example images)

![firacodeligaturebug](https://cloud.githubusercontent.com/assets/6718193/17223070/3eb7254a-54b8-11e6-969a-debf44a9cd8e.png)

**Comment by tonsky** [comment]
Please open a bug on VS issue tracked, it's a problem in how they handle syntax parsing, not a problem of a font
