### ISSUE TITLE
</ renders as normal Fira Mono on empty html tags

### ISSUE THREAD

**Issue by blaqbern** [tonsky/FiraCode#235]
See selected text in the screenshot below; this use case is pretty common in this era of js frameworks: give me an empty div that I can plop my app into.

![screen shot 2016-07-30 at 2 42 55 pm]
(https://cloud.githubusercontent.com/assets/10851286/17272435/03b563c8-5664-11e6-97d7-0a1153cd5308.png)

This only happens when the opening and closing tags are on the same line.

![screen shot 2016-07-30 at 2 50 01 pm](https://cloud.githubusercontent.com/assets/10851286/17272505/c7761fe0-5665-11e6-9790-7fb811a60c87.png)

Thank you for creating this awesome font.

**Comment by jdreesen** [comment]
Strange... it seems to work correctly on line 9 and 10!?

**Comment by weavejester** [comment]
What editor are you using? I'm seeing this problem on Atom, but only if the syntax is set to HTML. This implies that the problem is not with FiraCode, but with how Atom's HTML syntax highlighter is tokenizing the text.

**Comment by blaqbern** [comment]
Looks like you're right @weavejester. This is a problem with the language-html package on Atom.

@jdreesen, great catch. I didn't even see this. This also has to do with how language-html handles script tags. For some reason ` src="..."></script` is considered embedded javascript, and somehow that sidesteps the error seen in other tags like the div in the screenshot. Strange indeed.
