### ISSUE TITLE
What font-weight for Retina?

### ISSUE THREAD

**Issue by reinh** [tonsky/FiraCode#236]
Which font-weight setting do I use to select the Retina weight using CSS? I guessed 500, since [normal is equivalent to 400](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Values) and Retina is ["just slightly heavier than Regular"](https://github.com/tonsky/FiraCode#1000). Is this correct?  (NB: I am not using the webfont so the Retina weight should be available.)

**Comment by tonsky** [comment]
450. Not sure you can reference it from the CSS though

**Comment by reinh** [comment]
@tonsky Would you please edit your comment? I assume that you started it with a number followed by a period, but markdown has interpreted this as a numbered list item so I can't see what the number was.

**Comment by tonsky** [comment]
Ha, it changed `450. ` in the beginning of the line to the list marker. Sorry about that

**Comment by AndyFang36** [comment]
Thanks.👍
