### ISSUE TITLE
File paths with globs look uneven

### ISSUE THREAD

**Issue by johnsoft** [tonsky/FiraCode#238]
This is a bit of a nitpick, but:

![](http://i.imgur.com/d8m23OJ.png)

The `/*` and `/**` ligatures can cause file paths to have slightly wonky spacing. It might be a good idea to turn those ligatures off for `/*/` and `/**/` (and perhaps `/*.`)

**Comment by maddes** [comment]
This is already closed, but in my opinion, that `wonky spacing` looks awesome and conveys meaning. `/**` means any subfolder and `/*` means any filename.
But hey… I'm too late.

**Comment by antoligy** [comment]
But doesn't this also muck up documentation blocks in code?

**Comment by maddes** [comment]
@antoligy Yeah, I didn't had an issue with that but I recognise others did.
That could maybe have been solved moving the ligature to the right, aligning the first asterisk to it's original position.
