### ISSUE TITLE
<3

### ISSUE THREAD

**Issue by dantiel** [tonsky/FiraCode#239]
`<<=<3=<<`

**Comment by thany** [comment]
`<<=❤=<<`

So you want ligatures that produce emoji? 🙂

**Comment by dantiel** [comment]
EXACTLY
or just saying thanks for this gorgeous font.
+ i want reverse smiley support (-:

maybe "&&&" (used by haskell could be nice too)
aswell ligature for @$ (used in coffeescript with jquery)

**Comment by krux02** [comment]
since this is a programmer font, not a chat font. I would reject emoji ligatures. And `&&&` `@$` should if they are really a good idea be in their own issue. But they don't appear to be suitable for a ligature.

**Comment by dantiel** [comment]
yeah, emojis should (if -- at all) be an optional extension. 
well, for `&&` there is already a (slight) ligature, and although it iss a library method in haskell, its an infix operator like `&&`
for `@$` being in use for writing query plugins in coffee script (admitting that this is limited) and as it could be suited by connecting the end of the `@` arm to the tail of the `$`, resulting in a wave line.

**Comment by kilobyte** [comment]
```
[~/linux](stable-4.7)$ git grep '<3'|wc -l
9962
```
Way, way, WAY too many false positives.

**Comment by DJgamer98** [comment]
It could be done, but I have to agree with @dantiel. This should be a optional extension or a fork.

**Comment by quat1024** [comment]
`if (x<3) {`

`if (x♥) {`

bad idea.

**Comment by tonsky** [comment]
Thanks for the compliment, but, as mentioned, that would only lead to confusion
