### ISSUE TITLE
Issues in xcode 8 beta 4/5

### ISSUE THREAD

**Issue by jordibruin** [tonsky/FiraCode#241]
Because the font changes how text is displayed while you are typing, it can lead to weird behaviour in xcode 8 beta 4 & 5.
- The editor will jump up about 30 lines after typing some code
- Random lines will show on the wrong lines.

Is anyone else experiencing this?

**Comment by jordibruin** [comment]
Here's a gif that shows the editor jumping after typing some text. This only happens when the Debug Area is open.

![firacode xcode jump bug](https://cloud.githubusercontent.com/assets/170948/17561105/dbffda60-5f24-11e6-8f4a-cc122514eccf.gif)

**Comment by snej** [comment]
Oh! I've been experiencing this too, but assumed it was a regression in Xcode — didn't think it was related to my switching to Fira Code.

I suspect this is related to the fact that the bold weight has a different line height/leading than the other weights. This might be causing Xcode to glitch as it updates line heights based on changing syntax highlighting.

**Comment by tonsky** [comment]
Should be fixed in v2
