### ISSUE TITLE
Add += and -= ligatures

### ISSUE THREAD

**Issue by thany** [tonsky/FiraCode#242]
I'm not sure what these might look like, but so many languages have these `+=` and `-=` symbols, so maybe it's a nice idea to ligature-ize them in some way?

**Comment by looperhacks** [comment]
See https://github.com/tonsky/FiraCode/issues/173

**Comment by thany** [comment]
Sorry, I didn't see that one. It's quite hard to search issues for symbols as well :)

**Comment by tonsky** [comment]
Closing as duplicate for #173
