### ISSUE TITLE
"{-" sequence looks weird

### ISSUE THREAD

**Issue by narqo** [tonsky/FiraCode#248]
While most of the ligatures are great, the sequence of characters `{-` looks weird for my taste. 

A typical case in Go language is to specify the content of a slice/array/map within a single line. But if a slice of integers starts with a negative number, it turned into a mess of characters.

For example, here is how a slice `{-25, -160}` looks like in IDEA:

<img width="276" alt="screen shot 2016-08-21 at 20 54 53" src="https://cloud.githubusercontent.com/assets/88045/17838915/8defd4b8-67e1-11e6-91df-df687dd97348.png">

I use IDEA 2016.x with FiraCode 1.102.

**Comment by tonsky** [comment]
Yep. Initially it's a Haskell comment ligature (I think). I think I'd
better remove it or move to stylistic set

**Comment by DylanRJohnston** [comment]
Is there some way we can choose which ligatures we want on / off? I write in Haskell and quite like the `[]` and `{-` `-}` ligatures.

**Comment by tonsky** [comment]
Not yet, but I think something like that is needed

**Comment by maddes** [comment]
Maybe creating variants?
Like FiraCodeHaskell, FiraCodeJs, etc…
New ligatures an improvements could be added to all and then removed as requested :P
So if I work on a particular IDE for PHP, I use FiraCodePHP, for Haskell some other and such.
Even maybe a FiraCodeConsole variant would ease some of the problems.

**Comment by maddes** [comment]
And then the ultimate feature would be to be able to select the font for each type of file with `.editorconfig`.
Obviously not on your scope.

**Comment by patkar** [comment]
Oh sad, that would have looked nice in Twig, where `{{- variable name -}}` is used for whitespace control (compared to `{{ variable_name }}` without whitespace control.

**Comment by dhouck** [comment]
Your other issue, #408, is probably better; whether or not `{-` is a ligature, `{{-` can be, and it is used less often (though not never) in non-template code.
