### ISSUE TITLE
Doesn't work with Cmder/ConEmu/PuTTY

### ISSUE THREAD

**Issue by thany** [tonsky/FiraCode#249]
I can confirm this font doesn't work with Cmder/ConEmu, a command prompt alternative on Windows. The font looks good, but ligatures aren't applied. It also doesn't work (in the same way) in PuTTY, the go-to SSH client on Windows.

Perhaps a good idea to add this to the readme :)

**Comment by JCMais** [comment]
Related issue: https://github.com/cmderdev/cmder/issues/1036

**Comment by JackDMF** [comment]
Also related: Maximus5/ConEmu#703

**Comment by StephaneAdeso** [comment]
Hi. Any update on this issue? ligatures and stylistics still not work on 2023.

**Comment by wopian** [comment]
> Hi. Any update on this issue? ligatures and stylistics still not work on 2023.

See https://github.com/Maximus5/ConEmu/issues/703. There's nothing Fira Code can do about it until ConEmu adds ligature support unfortunately

**Comment by thany** [comment]
Yeah this issue just exists to request adding it to the readme, and to confirm that ligatures don't work (or perhaps in the future, prove that they do).
