### ISSUE TITLE
Need ligature to match HTML close comment

### ISSUE THREAD

**Issue by selfagency** [tonsky/FiraCode#25]
The HTML code for open comment `<!--` should have a ligature since its counterpart `-->` comes out as an arrow.

![screenshot 2015-05-27 19 41 14](https://cloud.githubusercontent.com/assets/2541728/7849889/a292159a-04a8-11e5-8ba7-ac1a8f81f2fc.png)

**Comment by iamstarkov** [comment]
👍

**Comment by tonsky** [comment]
Check out [version 0.6](https://github.com/tonsky/FiraCode/releases/tag/0.6)
