### ISSUE TITLE
In xCode @  seems weird

### ISSUE THREAD

**Issue by BaihaoTian** [tonsky/FiraCode#250]

**Comment by BaihaoTian** [comment]
![image](https://cloud.githubusercontent.com/assets/13565684/17964697/122be7e0-6aed-11e6-97f0-898a394350ac.png)

**Comment by BaihaoTian** [comment]
![image](https://cloud.githubusercontent.com/assets/13565684/17964710/1b3e1d62-6aed-11e6-8b42-aa102c34bd9f.png)

**Comment by pirminis** [comment]
what is weird about it?

**Comment by BaihaoTian** [comment]
I have already submit a picture .

**Comment by jmcs** [comment]
It's supposed to look like that.

**Comment by pirminis** [comment]
yes you did. but it seems rendered perfectly fine. again, please explain what is wrong with @ character @BaihaoTian

**Comment by BaihaoTian** [comment]
...... embarrassing,I just thought there are some part of @ were missing.Forgive my stupidity      @pirminis @jmcs

**Comment by oscar-broman** [comment]
Would it be fairly easy to replace this glyph and compile the font myself? It looks particularly terrible when underlined.
