### ISSUE TITLE
brackets does not have same height

### ISSUE THREAD

**Issue by at-hatran** [tonsky/FiraCode#251]
with font size 10.5pt in sublime text

![screenshot from 2016-08-25 22-41-11](https://cloud.githubusercontent.com/assets/19985350/17975804/4e9c38ce-6b15-11e6-86c0-ccc078ce0169.png)

**Comment by tonsky** [comment]
Which OS do you use? What's the sublime version?

**Comment by at-hatv** [comment]
I'm using Ubuntu 16.04, Sublime Text 3 Build 3114, it also happens in Atom too (font-size 14.5)

**Comment by JayAndCatchFire** [comment]
I can confirm this is also happening in Ubuntu 16.04 with VSCode 1.9.1 with font size 14.

**Comment by wopian** [comment]
Working fine on VSC 1.9.1 on W10, so could just be a system font rendering issue? Tested with 10.5, 14 and 14.5

**Comment by JayAndCatchFire** [comment]
@wopian, strangely enough, it renders okay on my setup if I change the font size to 14.5.

**Comment by tonsky** [comment]
Linked: https://github.com/tonsky/FiraCode/issues/251

**Comment by j-f1** [comment]
@tonsky That’s the same issue as this one.

**Comment by tonsky** [comment]
Ha-ha, silly me :) I was meant to link https://github.com/tonsky/FiraCode/issues/332

**Comment by evenfrost** [comment]
Same here on Ubuntu 16.10 with Sublime Text 3143. With font size 11 there's too much space between letters, and I'm using 10.5 because of that.

**Comment by tonsky** [comment]
I’m pretty sure it was fixed at some point, but I can’t find the exact issue. Please reopen if it’s still a problem
