### ISSUE TITLE
Bold weight has greater line height; causes glitches in Xcode editor

### ISSUE THREAD

**Issue by snej** [tonsky/FiraCode#252]
For some reason the bold weight has a slightly higher line height (maybe it's the leading?) than the other weights. See screenshot (the app is plain old TextEdit on Mac OS X.)
![fira code linespacing](https://cloud.githubusercontent.com/assets/43241/17980624/0a4576e6-6ab5-11e6-9e7f-342e61b2fea6.png)

In editors that take this into account (such as Xcode), this results in uneven linespacing if some syntax styles use bold. Worse, I suspect this is triggering the already-reported scrolling glitch in Xcode 8 (#241) — as you type, when Xcode is updating the syntax coloring of text up above in the file, it can also be changing its line height, causing text below to move up or down.

Unfortunately there's no way I know of to tell Xcode to use fixed linespacing. The only workaround is to avoid the bold weight, which is a shame because it's great for keywords and doc-comments.

**Comment by ddfreyne** [comment]
This also happens in Fira Mono (see mozilla/Fira#168).

**Comment by tonsky** [comment]
Should be fixed in v2
