### ISSUE TITLE
Ligatures not working in column 100 (VS)

### ISSUE THREAD

**Issue by kentcb** [tonsky/FiraCode#255]
OK, this is bizarre. In Visual Studio 2015, I'm seeing ligatures not rendering on column 100, but only if there is at least one non-whitespace character beforehand :/

I know you don't believe me, so here's a screen (I promise it's not photoshopped!)

![image](https://cloud.githubusercontent.com/assets/1901832/18024653/f486823c-6c4e-11e6-927d-16c2a57ada1f.png)

**Comment by tonsky** [comment]
Well... I believe you, but there's so much I can do. It's a VS issue, they probably have some tokenization/word boundary inserted there only under these bizarre conditions.
