### ISSUE TITLE
Elvis operator in groovy (?:)

### ISSUE THREAD

**Issue by denisfalqueto** [tonsky/FiraCode#256]
Groovy has a very nice operator which is a shortcut for the conditional C operator. Instead of using

a != null ? a : "sorry, a is null"

One can use:

a ?: "Sorry, a is null"

It would be great if FiraCode could have a ligature for ?:

**Comment by weavejester** [comment]
Might want to take a look at #61.

**Comment by denisfalqueto** [comment]
Oh, thank you. I skimmed through open issues, but didn't find any, so I opened this one. I'll close it now.

**Comment by tonsky** [comment]
Yeah, that one didn’t end up particularly well :( I’m now more focused on
ligatures that have natural visual form, instead of forcing something that
doesn’t stand together very well
