### ISSUE TITLE
Ruby ||=

### ISSUE THREAD

**Issue by kyledecot** [tonsky/FiraCode#26]
Just a suggestion but I think we could make the `||=` look a little better for Ruby

__Current__

![screen shot 2015-05-28 at 12 31 12 am](https://cloud.githubusercontent.com/assets/192464/7852769/fa8ef024-04d0-11e5-982e-c6e58a2a5dfe.png)

**Comment by tonsky** [comment]
Check out [version 0.6](https://github.com/tonsky/FiraCode/releases/tag/0.6)
