### ISSUE TITLE
=> & == swapped in latest release 1.201

### ISSUE THREAD

**Issue by Delagen** [tonsky/FiraCode#262]
if i wrote => I see != and vice versa

**Comment by jdreesen** [comment]
I can't confirm this. For me it works as it should.

**Comment by Delagen** [comment]
May be it Webstorm issue 2016.3 EAP
Writing TS code ()=>{} see as ()!={}

**Comment by dkunzler** [comment]
I have the same problem with IntelliJ. I closed IJ, installed the new version (overwrite the older version) and started IJ again. For me many more symbols were wrong. No work possible.
I went back to 1.200 and everything is fine. Could it be that windows has to be restarted or some caches have to get deleted when installing a new version?

**Comment by Delagen** [comment]
![2016-09-01 11 07 35](https://cloud.githubusercontent.com/assets/783335/18160178/cc912658-7034-11e6-94a4-775d7e861ecb.png)

**Comment by tonsky** [comment]
OS & IntelliJ version please

**Comment by tonsky** [comment]
And which font format do you use (ttf/otf)? Can you check with another one? Does both versions behave the same?

**Comment by dkunzler** [comment]
I used Windows 8.1 and IntelliJ 2016.2.2 with the ttf font.
I saw exactly what @Delagen shows in his screenshot.

I can't test another font type at the moment because I'm working and need my IDE. Perhaps later. Sorry.

**Comment by jdreesen** [comment]
Have you tried uninstalling the font before installing the new version?

**Comment by tonsky** [comment]
Both TTF and OTF versions seems fine on OS X WebStorm 2016.3 EAP. Might be an IntelliJ issue

**Comment by dkunzler** [comment]
@jdreesen Yep I tried that too. Close IntelliJ, uninstall FiraCode, install new FiraCode, open IntelliJ. Same output.

**Comment by Delagen** [comment]
@tonsky Why 1.2.200 version works fine?

**Comment by tonsky** [comment]
It doesn’t, not for everybody https://github.com/tonsky/FiraCode/issues/246

**Comment by tonsky** [comment]
https://youtrack.jetbrains.com/issue/IDEA-159901

**Comment by Delagen** [comment]
@tonsky Thanks. Cleaning Windows/Fonts folder from FiraCode* and install again helps.
