### ISSUE TITLE
Improve ligature of equals operator "=="

### ISSUE THREAD

**Issue by barmic** [tonsky/FiraCode#265]
The ligature of equals operator is a long equals… It's look likes an assign operator.

In some langages like C or C++, the assign statement is a valid test. So with fira code ligature, it's difficult to see the difference between:
![fira](https://cloud.githubusercontent.com/assets/179264/18199967/f192fce6-7102-11e6-85e1-0340fe38ca99.png)

For fix, it I think it's possible to :

- replace the ligature of assign by a <-
- replace the equals opertor by other sign (but I don't know what)

**Comment by cpavlina** [comment]
> replace the ligature of assign by a <-

er... assignment in these languages is `=`. you'd replace `=` with `<-` ?

**Comment by flying-sheep** [comment]
i think looks great like it is and never confused it with assignment.

**Comment by barmic** [comment]
> i think looks great like it is and never confused it with assignment.

Maybe but anothers developers can have this problem (and it's can a big bug https://freedom-to-tinker.com/blog/felten/the-linux-backdoor-attempt-of-2003/).

Reduce the difference between equals and assign seems to be a bad idea IMHO.  My everyday language don't have this problems but I don't want have a bad habit.

> er... assignment in these languages is =. you'd replace = with <- ?

I want have a big difference between assignment and equals because in some languages, the confusion can have pretty bad consequences.

**Comment by flying-sheep** [comment]
it’s twice as wide and the unified look of the comparison operators are a major reason why i love this font.

please don’t take that away from me.

**Comment by barmic** [comment]
I understand your opinion but it's a too problem for me. I check others fonts with code's ligature and it make same as Fira. I will continue with DejaVu.

I close my issue.

**Comment by flying-sheep** [comment]
well, maybe we should wait for @tonsky to weigh in

**Comment by tonsky** [comment]
Yeah, this isn’t first discussion about difference between `=` and `==`. In fact, they make 3× times difference in width, and, working in a language where `=` and `==` mean different things, it never became real issue. In theory, you might think they look similar, in practice, you’re always fully aware which one you see. If I figure out one day how to make Fira Code customizable there’ll be an option to turn it off. Before that, `==` will stay

**Comment by barmic** [comment]
> Yeah, this isn’t first discussion about difference between = and ==.

Sorry I search in open issues only.

>  In theory, you might think they look similar, in practice, you’re always fully aware which one you see.

When you code, yes. But during a review it's not as clear as that.

Thank you for your response.
