### ISSUE TITLE
Add => ligature for JS arrow functions

### ISSUE THREAD

**Issue by langri-sha** [tonsky/FiraCode#267]
JavaScript has expressions for [arrow functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) that are in the form `() => {}`.

**Comment by tonsky** [comment]
It’s there. Maybe your editor just prevents it from displaying. There’re closed issues about that you might want to look

**Comment by langri-sha** [comment]
D'oh, sorry, I double-checked the issues! You're right, it's Atom and only in certain contexts.
