### ISSUE TITLE
Font issues on PHPStorm

### ISSUE THREAD

**Issue by pedrowebcomum** [tonsky/FiraCode#268]
So today i decided to update the previous version of Fira code to its latest release and i got an unpleasant surprise when i saw that it wasn't properly working on my PHPStorm 2016.2.1.

I had no solution but to return to the older version i had of the font.

Could you guys look into it? Thanks!
![print](https://cloud.githubusercontent.com/assets/12413929/18270117/3dcbbe18-7423-11e6-88cd-c7725657babf.png)

**Comment by jdreesen** [comment]
Does this help https://github.com/tonsky/FiraCode/issues/246#issuecomment-244089963 ?

**Comment by pedrowebcomum** [comment]
It worked! thanks a lot!

**Comment by tonsky** [comment]
Don’t really know what to do with it. It’s reported to JetBrains [here](https://youtrack.jetbrains.com/issue/IDEA-159901), will close this one

**Comment by tonsky** [comment]
Added to wiki too https://github.com/tonsky/FiraCode/wiki/IntelliJ-products-instructions
