### ISSUE TITLE
It seems Github is doing A/B testing with FiraCode 🎉

### ISSUE THREAD

**Issue by oriSomething** [tonsky/FiraCode#270]
<img width="500" alt="screen shot 2016-09-10 at 12 47 52" src="https://cloud.githubusercontent.com/assets/2685242/18409638/ec696176-7754-11e6-8b20-b5690ec97c79.png">

***
EDIT: On incognito it shows different font

**Comment by tonsky** [comment]
Are you sure you aren’t using https://github.com/sindresorhus/refined-github?

**Comment by oriSomething** [comment]
You right and I really feel stupid right now 😳
Maybe, since I've used a browser without the extension for a while until yesterday.
I hope, github will used it for real somewhere in the near future

**Comment by jdreesen** [comment]
New version of Refined GitHub with [support for Fira Code](https://github.com/sindresorhus/refined-github/pull/295) was released just yesterday ;)
