### ISSUE TITLE
The font is/will be compatible with sublime text?

### ISSUE THREAD

**Issue by John-Luke** [tonsky/FiraCode#272]
I really need to know if yes, because I really would love to use this font in my sublime text 3

**Comment by jdreesen** [comment]
[According to the readme](https://github.com/tonsky/FiraCode#editor-support) it doesn't work. 
So you should vote for support here: http://sublimetext.userecho.com/topics/4719-does-sublimetext-support-programming-ligatures-fontlike-fira-code/

**Comment by tonsky** [comment]
Depends on SublimeText, not me. Let’s hope so, I love ST3 as well
