### ISSUE TITLE
C arrow "->" is not showing with ligatures in Visual Studio 2015

### ISSUE THREAD

**Issue by Djeefther** [tonsky/FiraCode#273]
The arrow -> are not working here with ligatures, even others non c-like arrows are working. Attached there is an image of this.
![git_bug](https://cloud.githubusercontent.com/assets/4177168/18588536/3d9051c0-7bfd-11e6-8599-83f15f1332ec.png)

**Comment by tonsky** [comment]
Yep, that’s a know, much wider issue of WPF. Read here https://github.com/tonsky/FiraCode/issues/259

**Comment by MarcSigrist** [comment]
FWIW, -> and similar ligatures are rendered correctly in Visual Studio Code.

**Comment by tonsky** [comment]
Sure. VS and VS Code are two completely different products. VS Code is Chrome-based and works flawlessly
