### ISSUE TITLE
tab + period renders repeated periods in BBEdit

### ISSUE THREAD

**Issue by ollicle** [tonsky/FiraCode#274]
This snippet:
`.
TAB.
TABTAB.

SPACE.
SPACESPACE.`
is rendering for me with the periods that follow tab characters repeated. Once after a single tab or twice after two tabs.
See screenshot comparing the same snippet in Monaco:
![tab-period](https://cloud.githubusercontent.com/assets/63586/18631777/159c08c2-7eb3-11e6-8586-84a7a566424b.png)

In this screenshot I have “Show invisibles” selected which normally causes tab characters to be displayed with a unicode △ (or similar character). In the example rendered with FiraCode this character is rendered incorrectly [?].

Note it is not necessary to enable “Show invisibles” for the periods to be repeated ellipsis-like.

This is in BBEdit version 11.6.1
Running on Mac OS 10.11.6

The previous version of FireCode I had installed did not display this behaviour. Sorry, although it was recent, I have yet to determine the exact version.

BTW I prefer tabs :) _ducks_

**Comment by ollicle** [comment]
Stepping back through versions of Fire-code the first to display this issue was version 1.200.

Although the duplicated punctuation issue is not present in version 1.102 – the “missing unicode character” rendering of tab characters is (see additional screenshot below). So perhaps these are separate issues. 

![fire-code-v1 102-bbedit-tabs](https://cloud.githubusercontent.com/assets/63586/19228929/3188cef8-8f11-11e6-9e0c-b6e4db0a5692.png)

I’m happy to raise this with Barebones support if there is any specific questions regarding their implementation that would help isolate the cause?

**Comment by johansolve** [comment]
I can confirm this. Periods after tabs are doubled (after one tab) or tripled (after two tabs). This is regardless of "show invisibles" setting. 

Also the missing delta character used by BBEdit for tabs when "show invisibles" is enabled, making it render as a generic square with question mark.

**Comment by ollicle** [comment]
After consulting with BareBones support I have made a separate issue #298 for the “show invisibles” TAB.

Also confirmed that the duplicated characters issue described above can also be observed TextWrangler (the free sibling to BBEdit).
