### ISSUE TITLE
Document Visual Studio support

### ISSUE THREAD

**Issue by clipperhouse** [tonsky/FiraCode#275]
I am using Fira Code with Visual Studio (2015 Update 3) and the ligatures are there! I don't know if that's new, I recall that this used to not be the case?

Anyway, the instructions (once the font is installed on the Windows system):

Tools (menu) --> Options (menu item) --> Environment --> Fonts and Colors --> Show settings for: Text editor (pull-down). Font pull-down is directly below that.

![image](https://cloud.githubusercontent.com/assets/216057/18643465/36bdac26-7e73-11e6-9d42-12b202bfd17c.png)

**Comment by tonsky** [comment]
VS is on supported list already, thanks for confirming

**Comment by clipperhouse** [comment]
@tonsky Hi, I should have been more specific, I don't see it here: https://github.com/tonsky/FiraCode/wiki

(VS Code is a different product.)

**Comment by tonsky** [comment]
That’s intentional — there’s nothing special required to enable ligatures except just selecting the font. I’ve added a paragraph about that to the wiki

**Comment by strandloper** [comment]
Do the ligatures only work from a certain update of VS2015? I am still using Update 1, just heard about and tried Fira Code and am not seeing the ligatures.

**Comment by mateuszlewko** [comment]
I'm using VS 2017, I've selected FiraCode in settings and I still don't see ligatures (I've restarted VS)
Do you know what's wrong?

**Comment by tonsky** [comment]
Not all editors show all the ligatures. Sometimes internally editor split ligature into different tokes because of how its syntax parser is written. Try testing the same ligature in plain text file or inside a comment

**Comment by jbaumbach** [comment]
In case it helps someone: on VS 2017, when you select the font you can see that it changed, but the ligatures won't work until it's restarted.
