### ISSUE TITLE
Precedence of != over =< in !=<

### ISSUE THREAD

**Issue by DivineDominion** [tonsky/FiraCode#276]
As seen on the screenshot, Swift code for operator definitions (`!=`) followed by generic constraints (<T>) render oddly:

![screen shot 2016-09-20 at 15 24 17](https://cloud.githubusercontent.com/assets/59080/18672009/902df35a-7f46-11e6-817c-c302d544104d.png)

**Comment by CAD97** [comment]
See also #305
