### ISSUE TITLE
!!} that comes after {!! does not format correctly

### ISSUE THREAD

**Issue by alesf** [tonsky/FiraCode#278]
When written like this `{!! words !!}` the `!!}` is formatted incorrectly.
But when standing alone, without `{!!`, the `!!}` formats correctly.

See attached image.

![screen shot 2016-09-23 at 11 41 52](https://cloud.githubusercontent.com/assets/1148574/18781596/c7d44d34-8182-11e6-895f-773c3c5958af.png)

**Comment by alesf** [comment]
P.S.: I'm using Atom 1.10.2 on OS X with Laravel Blade highlighter.

When I tried it in plain text it was fine.
![screen shot 2016-09-23 at 11 54 16](https://cloud.githubusercontent.com/assets/1148574/18782058/c38a01f4-8184-11e6-98b5-5ae171b6c226.png)

But in php PHP highlighter none of the exclamation marks were properly formatted.
They were OK only on lines with comments.
![screen shot 2016-09-23 at 11 54 39](https://cloud.githubusercontent.com/assets/1148574/18782061/c893c8f6-8184-11e6-8cf5-16d1e40f6e43.png)

**Comment by tonsky** [comment]
There’s nothing to fix on a font side — what you see is an editor splitting
symbol pairs into tokens incorrectly.
