### ISSUE TITLE
Spurious whitespace being inserted

### ISSUE THREAD

**Issue by ianp** [tonsky/FiraCode#28]
Any line which has ligatures in will end up with additional whitespace being inserted near the end of the line. As an extreme example the following line of Scala code:

```scala
private val dateTimePattern = """(\d\d\d\d)-(\d\d)-(\d\d)T(\d\d?):(\d\d?):(\d\d?)(?:\.(\d{1,3}))?(?:Z|[+-](\d\d)(?::?(\d\d))?)?""".r
```

Appears to have about 3 extra spaces before the closing quote marks. The cursor position is also thrown off by this which makes it hard to edit lines with ligatures.

It sure looks pretty though! ;-)

I'm viewing this in Atom 0.206 on OS X Yosemite in case that helps/is related to the issue. I've attached a screenshot of the problem.

![screen shot 2015-06-05 at 10 17 26](https://cloud.githubusercontent.com/assets/103420/8003063/22d54cbc-0b6c-11e5-873f-717ae15c32cb.png)

**Comment by tonsky** [comment]
Atom doesn’t work with ligatures, sorry. Check out issues here or on Atom repo for more details

**Comment by ianp** [comment]
Yup. In case anybody else wanders this was the relevant Atom issue is atom/atom#2880.
