### ISSUE TITLE
Kerning problem with some italic chars

### ISSUE THREAD

**Issue by ewirch** [tonsky/FiraCode#281]
![image](https://cloud.githubusercontent.com/assets/1880345/18864287/f0c660b8-8495-11e6-98db-bedbcaed9029.png)
See colliding "C>" and nearly colliding "r<". Screenshot made in IntelliJ. Is this a font problem, or IntelliJ problem?

**Comment by tonsky** [comment]
There’re no real italics in the font. IntelliJ tries to emulate them programmatically
