### ISSUE TITLE
Proper ligature for <~> or disable ligature for ~> in case of <~>

### ISSUE THREAD

**Issue by emergie** [tonsky/FiraCode#282]
![selection_295](https://cloud.githubusercontent.com/assets/2456881/18990738/3f13436e-8714-11e6-9bf9-2cebed38dafd.png)
<~> is used in IDEA to hide a type qualification, which can be inferred:

![selection_296](https://cloud.githubusercontent.com/assets/2456881/18990748/4e09eca6-8714-11e6-888a-5e81bc4deca1.png)

**Comment by tonsky** [comment]
Duplicate of #179
