### ISSUE TITLE
Lowercase 'r' has serif?

### ISSUE THREAD

**Issue by kiliman** [tonsky/FiraCode#283]
I searched the existing issues to see if this was already addressed, but didn't find anything.

I was just wondering what the reason was to include serifs on the lowercase 'r' .

Overall, I'm very impressed with the font and have it setup in VS 2015, Android Studio, and added Stylish support for GitHub and StackOverflow.

**Comment by tonsky** [comment]
https://github.com/mozilla/Fira/issues/49
