### ISSUE TITLE
Strange behavior with <<=

### ISSUE THREAD

**Issue by jbilcke** [tonsky/FiraCode#285]
Hi,

I don't know if this is related to Atom or FiraCode (please tell me if I'm wrong so I can submit an issue someplace else), but  `<<=` renders differently when on a normal line or a comment line:

<img width="301" alt="screen shot 2016-10-10 at 12 20 51" src="https://cloud.githubusercontent.com/assets/136294/19233204/59242af2-8ee4-11e6-8ea1-80fda6dc6133.png">

(note that I disabled ligatures on purpose on strings, to show the original) 

My guess is that the `<<=` pattern is mostly used in DSL-friendly languages such as Scala, so maybe it should always show as the double spike arrow?

(I believe the alternative `< ≤` isn't used by other programming languages, as it doesn't make much sense)

**Comment by tonsky** [comment]
It’s Atom’s problem with how it splits sequences into tokens (often incorrectly). Try changing your syntax to plain text (no tokenization) and you’ll see everything is fine with the font. Fix there might be a PR to language grammar you use, with correct tokenization.
