### ISSUE TITLE
Fira code works on 	Cmder then why it is listed as Doesn’t work

### ISSUE THREAD

**Issue by MandarSant** [tonsky/FiraCode#288]
Fira code works on  Cmder then why it is listed as **_Doesn’t work_**

**Comment by tonsky** [comment]
Can you provide a screenshot with ligatures working? Also see https://github.com/tonsky/FiraCode/issues/249

**Comment by mandar262** [comment]
@tonsky here is the image
![capture](https://cloud.githubusercontent.com/assets/20091634/19624105/b8485510-9904-11e6-89d5-b840353e8fdb.JPG)

**Comment by tonsky** [comment]
Can you make a screenshot with any of the ligatures? (-> ->> != will do)

**Comment by Esgariot** [comment]
Just checked, ligatures are not working.
![firacode_cmder](https://cloud.githubusercontent.com/assets/6072243/21082050/5f9292dc-bfd3-11e6-9b0c-756a138464e3.png)

**Comment by tonsky** [comment]
Thanks @Esgariot !
