### ISSUE TITLE
Powerline support

### ISSUE THREAD

**Issue by crepererum** [tonsky/FiraCode#29]
Powerline + ligatures seems to be the perfect programming font. Sure you can [patch the font yourself](https://github.com/powerline/fontpatcher), but builtin support will result in way more beautiful results. 

This is more a feature request / wishlist than a real issue. Feel free to close the issue if it is out of scope. Thanks and keep going :+1:

**Comment by kirang89** [comment]
+1

**Comment by jstnjns** [comment]
+1

**Comment by rcdilorenzo** [comment]
+1

**Comment by ApfelUser** [comment]
+1

**Comment by mrap** [comment]
+1!

**Comment by myzone** [comment]
+1

**Comment by jaggy** [comment]
+1

**Comment by tonsky** [comment]
Check out [version 0.6](https://github.com/tonsky/FiraCode/releases/tag/0.6)

**Comment by Quantlyx** [comment]
+1
