### ISSUE TITLE
Ligature Request: && and ||

### ISSUE THREAD

**Issue by jeanetienne** [tonsky/FiraCode#290]
I think a lot of `if` statements in C flavoured languages use `&&` for the boolean AND, and `||` for the boolean OR.

I think the notation looks like ∧ for AND, and ∨ for OR.

I don't know if that's something you thought of including, but I believe this would make a lot of logical statements easier and quicker to read.

Thanks!

**Comment by krux02** [comment]
I agree that ¬∨∧ for logical operations does increase readability, but this strong visual change would exceed the freedom I would allow in ligatures.

**Comment by jeanetienne** [comment]
Ok, thanks for the response, and thanks for this awesome type :)

**Comment by tonsky** [comment]
These exact ligatures were in font at some point in time. People doesn’t seem to like it that much. If I ever figure out to make font builder (build-your-own-set-of-ligs), I’ll return them as an opt-in feature

**Comment by jeanetienne** [comment]
That would be awesome!
