### ISSUE TITLE
Does not work on new version VSCode (higher than Version 1.6.0)

### ISSUE THREAD

**Issue by Kongsea** [tonsky/FiraCode#291]
The font worked well on VSCode lower than version 1.6.0. But when the VSCode was upgraded to higher version, some features of the font do not work anymore. For example, the signs ==, !=, ==>, and so on, do not convert automatically.

**Comment by vilinski** [comment]
Can't confirm with 1.6.1 - all listed signs are displayed as expected

**Comment by looperhacks** [comment]
Can't confirm either

![](https://i.imgur.com/JYy1M1F.png)

**Comment by tonsky** [comment]
@Kongsea please share a screenshot, OS version, your config, and language in which these symbols don’t work (it might be a syntax highlighting issue, when highlighting splits ligatures into multiple tokens, e.g. atom has a lot of those)

**Comment by Kongsea** [comment]
I use Python on Ubuntu 14.04 and my VSCode version is 1.6.1.

The screenshot is as bellow.

![selection_008](https://cloud.githubusercontent.com/assets/4168984/19513770/b2bb2b38-9623-11e6-9178-df59763d774c.png)


And my configuration of VSCode is as bellow. It seems there is no special.

![selection_009](https://cloud.githubusercontent.com/assets/4168984/19513790/c68b1d6c-9623-11e6-8603-de32f82432fc.png)

If there are any questions, please tell me. I will do my best to help you confirm it. Thank you.

**Comment by looperhacks** [comment]
The line that enables ligatures is commented. Ligatures are not enabled in your config.

**Comment by Kongsea** [comment]
@looperhacks Thank you. It works now.
