### ISSUE TITLE
Doesn't work in Kate while Hasklig works 

### ISSUE THREAD

**Issue by nowm** [tonsky/FiraCode#3]
Tested this font in Kate (Kubuntu 14.04 [x64]). It doesn't do any any ligature substitution, unlike Hasklig, which works fine.

I think you need your own list of [tested] supported programs instead of referring to the Hasklig's list.

**Comment by Zhigalin** [comment]
Doesn't work in kate/kubuntu 14.04 x86

**Comment by Zhigalin** [comment]
@tonsky

**Comment by gadevoi** [comment]
Doesn't work in kate/ubuntu 14.04 x64

**Comment by tonsky** [comment]
Any suggestions how to fix this? What causes the problem? I don’t have ubuntu :(

**Comment by nowm** [comment]
@tonsky In whole, I think it is not an issue, «it's not working in Ubuntu». It's the issue, «list of supported programs is created without actual testing these programs».

If you will limit the list to reflect actual supported programs/platforms, you will not have such issues at all.

**Comment by tonsky** [comment]
@nowm can you test [version 0.6](https://github.com/tonsky/FiraCode/releases/tag/0.6) please? I built it using different tools, closer to what Fira Mono authors are using

**Comment by gadevoi** [comment]
It works for me! ![kate](https://cloud.githubusercontent.com/assets/9862576/9156954/62233656-3eeb-11e5-9f08-947d1c55880e.png)

**Comment by tonsky** [comment]
Thanks @gadevoi, I think I can close that now
