### ISSUE TITLE
On windows it's full of bugs...

### ISSUE THREAD

**Issue by Tomicapo** [tonsky/FiraCode#30]
First, copying the theme foder to the packages folder generated an endless cascade of error massages. Had to restart my computer.
After adding and renaming the folder with Sublime closed, things appeared to be better until tabs and other things started to turn completely black (foreground + background) so things were still there but invisible. That happened with tabs, the left sidebar and the search bar at the bottom.
Then I simply uninstalled and went back to the nice "blackboard" color scheme.

**Comment by tonsky** [comment]
Sorry, is it a problem with a font or with a theme?

**Comment by Tomicapo** [comment]
Thanks for your quick reply. Please give me a couple of days to respond properly. I'll try to make a video to show you the errors I encountered.

**Comment by klingtnet** [comment]
@Tomicapo What are you talking about? FiraCode is a font and not a SublimeText Theme.

**Comment by Tomicapo** [comment]
Damn me... Sorry! I posted this in the wrong place!
