### ISSUE TITLE
Different fonts for same ligatures?

### ISSUE THREAD

**Issue by batjko** [tonsky/FiraCode#301]
Hi there,

I really like the symbol ligatures of this font and would like to use it in my main editor. But I find all the alphanumerical characters themselves rather less readable (and codable) than most other monospaced fonts.

For example, I have been using Source Code Pro for years now, and it's gorgeous in terms of letters and numbers etc. Very clear, immediately accessible, no unnecessary swings and swirls etc:
![selection_005](https://cloud.githubusercontent.com/assets/7287076/20062365/5acd886c-a4fb-11e6-970f-04fb6d9de185.png)

Compared to that, this is just not clean enough:
![selection_006](https://cloud.githubusercontent.com/assets/7287076/20062424/9c5d546a-a4fb-11e6-99d1-5ee9e3a5b3a3.png)
e.f. the 'r' to point at a specific example. But also the spacing between letters etc.

So I would love to see a version of Fira Code that adds the ligature symbols to a clean font like Source Code Pro or similar.
Has something like this thought of?

**Comment by sainaen** [comment]
You may want to check a [list of alternatives](https://github.com/tonsky/FiraCode#alternatives) in the readme for some of the existing fonts with ligatures. Specifically, there's a fork of Source Code Pro you may want to check out called [Hasklig](https://github.com/i-tu/Hasklig).

**Comment by batjko** [comment]
Ah, excellent! Thanks for pointing that out, @sainaen! :+1:
