### ISSUE TITLE
Should we disable the ligature of "=<" ?

### ISSUE THREAD

**Issue by liweitianux** [tonsky/FiraCode#305]
Thanks for the great work!

In a CLI tool's help or a configuration file, it is common to come across the notation:

```
--config=<value>    # CLI tool help message
config=<value>      # e.g., in a sample configuration file
```

However, the ``=<`` is turned into the **less or equal to** sign as ``⩽``, which causes significant confusions.  In addition, the both ``=<`` and ``<=`` have the same ligature, which is also a bit confusing.

Should we disable the ligature of ``=<``, or there are better reasons to have this ligature?

Thanks!

**Comment by higankanshi** [comment]
Maybe we can change the '=<' and '⩽' to ' =< ' and ' ⩽ '.

**Comment by Lawri-van-Buel** [comment]
I would say to not use this font in your terminal for this reason and others. As for the sample configure file yes it's slightly confusing but since you (a programmer) know this happens not a real issue. Just use a different editor or add a space inveteeen the '=' and '<' to see it.

**Comment by aschrab** [comment]
Other than the occurrences of this pairing noted in the original report I've been quite liking this as a terminal font.

Another issue with this ligature is that it makes it impossible to visually distinguish between `<=` and `=<`, even though many languages will treat those very differently. This could make it very difficult to spot typos.

I also don't recall ever seeing (and definitely haven't used) `=<` intending the meaning conveyed by the resulting glyph.
