### ISSUE TITLE
At Sign (@) getting chopped

### ISSUE THREAD

**Issue by fabianhjr** [tonsky/FiraCode#307]
![screenshot from 2016-11-14 20-58-24](https://cloud.githubusercontent.com/assets/303897/20291651/4b5b3750-aaad-11e6-8d01-eda7b909fbee.png)
(It happens in chrome and emacs too)

Font being used are:
 - Fira Code - Bold 12pt
 - Fira Code - Retina 12pt

Some system info:
```
Linux 4.8.7-1-ARCH x86_64
---
Name            : gedit
Version         : 3.22.0+4+g2c70ccb-1
Description     : A text editor for GNOME
---
Name            : otf-fira-code
Version         : 1.204-1
---
Name            : ttf-fira-code
Version         : 1.204-1
```

**Comment by jdreesen** [comment]
It should look exactly like it does on your picture. Have you read #250?

**Comment by tonsky** [comment]
Yep, that’s the way it looks, all fine here

**Comment by fabianhjr** [comment]
Sorry about the dup, wasnt able to find the #250 trough Google nor Github.
