### ISSUE TITLE
=~ is confusing in Bash

### ISSUE THREAD

**Issue by lastorset** [tonsky/FiraCode#309]
In Bash scripting, we occasionally refer to the user's home directory, like this:

```bash
LOCKFILE=~/copy-the-internet
lockfile-create ${LOCKFILE}
```

With Fira Code, this turns into

```bash
LOCKFILE≂/copy-the-internet
```

I spent a good while trying to figure out what the `=~` operator does in Bash before realizing I was tokenizing it wrong mentally…because of the visual presentation. :)

For Bash use this is definitely confusing and would be better removed. But if the `=~` operator is used in some other language I understand if you can't justify removing it.

**Comment by curio77** [comment]
`=~` is Perl's pattern matching operator.

**Comment by lastorset** [comment]
Indeed, thanks! I am guilty of not trying the latest code.

**Comment by rparree** [comment]
has `=~` been re-added? I still have this problem with the  [1.205](https://github.com/tonsky/FiraCode/releases/tag/1.205)  version
