### ISSUE TITLE
IntelliJ FiraCode only does ligature inside String?

### ISSUE THREAD

**Issue by danvim** [tonsky/FiraCode#311]
I doubt this issue relates to the developing of the font, but referring to the [instructions](https://github.com/tonsky/FiraCode/wiki/Intellij-products-instructions) , I don't see FiraCode ligatures outside Strings
![capture](https://cloud.githubusercontent.com/assets/5255292/20422683/c76eeb10-ada6-11e6-9edc-3395030141ba.PNG)

The screenshot above is in Haskell, but improper behavior is the same in Java in IntelliJ.

I:

- am using the community edition of IntelliJ and build is 2016.2.5
- have installed the otf versions of the font
- on my Windows 10.

Should I report this on IntelliJ's site and should the [instructions](https://github.com/tonsky/FiraCode/wiki/Intellij-products-instructions) be updated (if I'm not alone)?

**Comment by tonsky** [comment]
Yes, please report to IntelliJ or plugin author (if that’s not built-in)

**Comment by danvim** [comment]
@tonsky I'd like to add that another ligature font Iosevka displays ligatures properly in IntelliJ

**Comment by danvim** [comment]
Nevermind, I did a bad installation. Sorry :(
