### ISSUE TITLE
Prettify-symbols config for emacs 

### ISSUE THREAD

**Issue by To1ne** [tonsky/FiraCode#312]
The methods for Emacs currently explained on the [wiki](https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs) are not really working for me. I would like to facilitate emacs `prettify-symbols-mode` instead (as suggested by [@siegebell](https://github.com/tonsky/FiraCode/issues/211#issuecomment-238432036)).

This is what I've got at the moment:

Enable prettify symbols globally:
```emacs-lisp
(global-prettify-symbols-mode 1)
```

Un-prettify symbols at point for easier editing (one of the reasons why I want to use this method):
```emacs-lisp
(setq prettify-symbols-unprettify-at-point t)
```

Define prettify symbols:
```emacs-lisp
  (add-hook 'prog-mode-hook
            (lambda ()
              (push '("<=" . ?≤) prettify-symbols-alist)))
```

For this last piece of config I need your help. I like to have the full list of symbol combo's (e.g. `<=`) with their ligature (e.g. `≤`). So I would appreciate you would share it with us.

**Comment by tonsky** [comment]
I’m not sure how best to address this. Ligatures are named glyphs in font file, but they don’t have unicode code or anything. They have names (e.g. `greater_greater_hyphen.liga`), but I’m not sure to what it is translated in OTF/TTF files.

**Comment by To1ne** [comment]
Owkey, thanks I did not understand this correctly. Too bad, because the `unprettify-at-point` is pretty useful. See the screenshot below, when the cursor is on the ligature, it _unprettifies_ it.

![screen shot 2016-11-21 at 15 54 25](https://cloud.githubusercontent.com/assets/121621/20487229/d6ad0b4e-b002-11e6-9f7e-c0734fe1532d.png)

I'll check and see if I can accomplish this with the FiraCode-Regular-Symbol font posted in #211.

**Comment by To1ne** [comment]
So how does Pragmata Pro do this? https://gist.github.com/kwf/dea7bc51101083acb95c875140e2a96d

**Comment by tonsky** [comment]
They map ligatures to Unicode private use area. E.g. !! is mapped to U+E720. Looks like there’s a way to that,  actually, https://glyphsapp.com/tutorials/roll-your-own-glyph-data/. I’ll try to do that in the next version

**Comment by fabianhjr** [comment]
@To1ne this is what I was using, however it currently broken. (used to work, something weird is happening now and that's why I came here; found it somwhere on the web/here)

```lisp
  (custom-set-variables '(haskell-font-lock-symbols t)
                        '(haskell-font-lock-symbols-alist
                          (and (fboundp 'decode-char)
                               (list (cons "&&" (decode-char 'ucs #XE100))
                                     (cons "***" (decode-char 'ucs #XE101))
                                     (cons "*>" (decode-char 'ucs #XE102))
                                     (cons "\\\\" (decode-char 'ucs #XE103))
                                     (cons "||" (decode-char 'ucs #XE104))
                                     (cons "|>" (decode-char 'ucs #XE105))
                                     (cons "::" (decode-char 'ucs #XE106))
                                     (cons "==" (decode-char 'ucs #XE107))
                                     (cons "===" (decode-char 'ucs #XE108))
                                     (cons "==>" (decode-char 'ucs #XE109))
                                     (cons "=>" (decode-char 'ucs #XE10A))
                                     (cons "=<<" (decode-char 'ucs #XE10B))
                                     (cons "!!" (decode-char 'ucs #XE10C))
                                     (cons ">>" (decode-char 'ucs #XE10D))
                                     (cons ">>=" (decode-char 'ucs #XE10E))
                                     (cons ">>>" (decode-char 'ucs #XE10F))
                                     (cons ">>-" (decode-char 'ucs #XE110))
                                     (cons ">-" (decode-char 'ucs #XE111))
                                     (cons "->" (decode-char 'ucs #XE112))
                                     (cons "-<" (decode-char 'ucs #XE113))
                                     (cons "-<<" (decode-char 'ucs #XE114))
                                     (cons "<*" (decode-char 'ucs #XE115))
                                     (cons "<*>" (decode-char 'ucs #XE116))
                                     (cons "<|" (decode-char 'ucs #XE117))
                                     (cons "<|>" (decode-char 'ucs #XE118))
                                     (cons "<$>" (decode-char 'ucs #XE119))
                                     (cons "<>" (decode-char 'ucs #XE11A))
                                     (cons "<-" (decode-char 'ucs #XE11B))
                                     (cons "<<" (decode-char 'ucs #XE11C))
                                     (cons "<<<" (decode-char 'ucs #XE11D))
                                     (cons "<+>" (decode-char 'ucs #XE11E))
                                     (cons ".." (decode-char 'ucs #XE11F))
                                     (cons "..." (decode-char 'ucs #XE120))
                                     (cons "++" (decode-char 'ucs #XE121))
                                     (cons "+++" (decode-char 'ucs #XE122))
                                     (cons "/=" (decode-char 'ucs #XE123))))))
```

**Comment by To1ne** [comment]
@fabianhjr It seems to me you need the [FiraCode-Regular-Symbol](https://github.com/tonsky/FiraCode/files/412440/FiraCode-Regular-Symbol.zip) font, see [this comment](https://github.com/tonsky/FiraCode/issues/211#issuecomment-239058632).

**Comment by howdoicomputer** [comment]
Ah, this would be pretty neat; the suggested workaround currently breaks helm for me in Emacs.

**Comment by PhilArmstrong** [comment]
> I’m not sure how best to address this. Ligatures are named glyphs in font file, but they don’t have unicode code or anything. They have names (e.g. greater_greater_hyphen.liga), but I’m not sure to what it is translated in OTF/TTF files.

According to https://forum.glyphsapp.com/t/how-to-add-a-glyph-and-assign-it-a-custom-unicode-hex-value-like-font-awesome/900/6

You can give a glyph it’s own unicode number by doing the following: 

> "you can check "Use custom naming" in Font info > other settings (temporarily). Then the unicode field in the info box in the lower left of the font view will become editable. So that you can add your own values. The you can define the glyph names and the unicodes independently. "

So you could do that, assign the ligatures unicode numbers in the private range (0xE000 upwards) and then emacs users will be able to use the glyphs in the fonts you ship directly by putting appropriate mappings in prettify-symbols-alist.

That still leaves the overlap problem - I’m not quite sure why apps that display the glyphs just fine (like gedit for example) aren’t doing this too. It may a disagreement over where the ligature 0 bound should sit between different applications. I’ve tried changing the ligatures so that the char boundary is at the left end of the glyph & that seems to make emacs behave, but it probably not a change you want to make.

Looking at the code for prettify-symbols, it should be possible to tell it that a sequence of characters is being replaced by a bunch of new ones in sequence, but the format is really weird & at the moment I can’t get it to work at all. If I get it working I’ll let you know.

**Comment by PhilArmstrong** [comment]
OK. I’ve fixed the printing of the extra spaces in prettify-symbols-alist, but that just leads to more rendering errors in emacs - looks like emacs really doesn’t like the layout of these ligatures.

For reference, you can do something like the following to insert the requisite extra spaces:

````
(defun pretty-symbols ()
  "make some word or string show as pretty Unicode symbols"
  (setq prettify-symbols-alist
        '(
	  ("**" . (?\s (Br . Bl) ?\uE004) )
	  ("***" . (?\s (Br . Bl) ?\s (Br . Bl) ?\uE005) )
	  )
	)
  (prettify-symbols-mode)
;  (setq prettify-symbols-unprettify-at-point t)
  )

(add-hook 'prog-mode-hook 'pretty-symbols)
````

(I’ve mapped ** and *** to U+E004 and U+E005 respectively in my quick custom version of FiraCode-Medium)

This works fine as you type the symbol, but as soon as you type anything *after* the symbol, emacs goes back and overwrites the two characters to the left of the new ligature with extra spaces! It looks like it isn’t taking account of the full width of the ligature when rendering it initially, but then is including it afterwards, so either way you get rendering errors with FiraCode as currently designed :(

**Comment by PhilArmstrong** [comment]
OK, so editing the font so that the ligature starts at offset 0 (well, a small positive offset in fact) instead of -1000 or so means that emacs seems to work just fine, without any need for the extra spaces. Is there some reason the ligatures have this negative offset? I’ve had a look at the ligatures for things like ffi / ffl in other fonts & they don’t seem to need it.

**Comment by PhilArmstrong** [comment]
OK. So I got hold of a copy of Pragmata Pro for testing purposes only & have discovered that it’s ligatures are defined with the leftmost part of the ligature starting at a positive offset from 0. ie, no part of the ligature is to the left of the origin.

So the free monospace coding fonts with multi-character ligatures (Hasklig, FiraCode) differ from Pragmata Pro in this respect.

**Comment by PhilArmstrong** [comment]
(Can confirm that emacs works perfectly with PragmataPro & a custom pretty-symbols-alist btw. I may hack FiraCode & change all the ligatures to have their origin on the left. Will see if I have the tuits.)

**Comment by tonsky** [comment]
@PhilArmstrong this is done so that editors would let you “step into” ligature. This feels more natural when editing the code. Without it, e.g. `<->` would be rendered as a single glyph and you won’t be able to position your cursor inside and e.g. remove the dash

**Comment by tonsky** [comment]
I’ll leave this picture here (it’s code table from PragmataPro so it won’t get lost)

![ligatures](https://cloud.githubusercontent.com/assets/285292/21645206/b42c6932-d2c3-11e6-8990-03170329c371.jpg)

**Comment by PhilArmstrong** [comment]
@tonsky I can step into the PragmataPro ligatures just fine in the editors I have available to me (not including emacs). Eg I can type ***, get the three asterisk ligature, step back one character into the ligature, see the caret displayed between the second & third *s, delete the middle * and end up with the two asterisk ligature. (This using geany, which is IIRC a GTK3 based editor).

Which editors require these left shifting ligatures?

Ignoring the placement issue, it would be great if FiraCode assigned unicode private space codepoints to the ligatures!

Thanks for all your work on FiraCode.

**Comment by PhilArmstrong** [comment]
(You can also mark caret points in ligatures, which should let editors automatically backstep into them in a natural fashion, although poking at the PragmataPro ttf in fontforge it doesn’t look like it’s using that feature. It might be an OpenType-only feature?)

**Comment by tonsky** [comment]
Atom and CodeMirror require it, IntelliJ IDEA does not. I’ll explore if I can make use of caret points, that would be a great help, actually.

**Comment by PhilArmstrong** [comment]
IntelliJ is (presumably) using the HarfBuzz layout engine as that’s what (IIRC) all the Java runtimes use & it’s also the backend behind most of the Linux text rendering libraries, so it makes sense that Java & GTK3 / Qt - based editors would share the same behaviour.

**Comment by PhilArmstrong** [comment]
(It’s also why FiraCode doesn’t work in the Gnome Terminal - it doesn’t use a layout engine to paint the glyphs, so no ligatures.)

**Comment by tonsky** [comment]
Unfortunately, Atom doesn’t seem to understand caret positions. Also, Terminal.app (OS X) doesn’t show normal ligatures (`liga`) or `dlig`, but does show `calt`. So I think I’ll stick with that technique. I’ll see what can be done for Emacs, maybe I’ll just copy same ligatures but fix the offset for duplicates and assign Unicode codes to that

**Comment by PhilArmstrong** [comment]
After some poking, it turns out that CodeMirror works just fine in firefox, but not in Chrome, which suggests that it’s the Chrome font rendering that’s at fault in Atom. How annoying!

**Comment by PhilArmstrong** [comment]
(Atom being based on electron which is, IIRC, a packaged up Chrome browser.)

**Comment by Profpatsch** [comment]
So, after reading documentation for a bit, especially for how `compose-region` works (which is used by `prettify-symbols-mode`), I was able to create a full solution for Hasklig code points: https://github.com/i-tu/Hasklig/issues/84#issuecomment-298803495

If https://github.com/tonsky/FiraCode/issues/211#issuecomment-239087391 gets implemented and each combined glyph gets a code point, this is easily translated for FiraCode.

**Comment by Triavanicus** [comment]
So this?
```emacs-lisp
(defun fira-code-mode--make-alist (list)
  "Generate prettify-symbols alist from LIST."
  (let ((idx -1))
    (mapcar
     (lambda (s)
       (setq idx (1+ idx))
       (let* ((code (+ #Xe100 idx))
	      (width (string-width s))
	      (prefix ())
	      (suffix '(?\s (Br . Br)))
	      (n 1))
	 (while (< n width)
	   (setq prefix (append prefix '(?\s (Br . Bl))))
	   (setq n (1+ n)))
	 (cons s (append prefix suffix (list (decode-char 'ucs code))))))
     list)))

(defconst fira-code-mode--ligatures
  '("www" "**" "***" "**/" "*>" "*/" "\\\\" "\\\\\\"
    "{-" "[]" "::" ":::" ":=" "!!" "!=" "!==" "-}"
    "--" "---" "-->" "->" "->>" "-<" "-<<" "-~"
    "#{" "#[" "##" "###" "####" "#(" "#?" "#_" "#_("
    ".-" ".=" ".." "..<" "..." "?=" "??" ";;" "/*"
    "/**" "/=" "/==" "/>" "//" "///" "&&" "||" "||="
    "|=" "|>" "^=" "$>" "++" "+++" "+>" "=:=" "=="
    "===" "==>" "=>" "=>>" "<=" "=<<" "=/=" ">-" ">="
    ">=>" ">>" ">>-" ">>=" ">>>" "<*" "<*>" "<|" "<|>"
    "<$" "<$>" "<!--" "<-" "<--" "<->" "<+" "<+>" "<="
    "<==" "<=>" "<=<" "<>" "<<" "<<-" "<<=" "<<<" "<~"
    "<~~" "</" "</>" "~@" "~-" "~=" "~>" "~~" "~~>" "%%"
    "x" ":" "+" "+" "*"))



(defvar fira-code-mode--old-prettify-alist)

(defun fira-code-mode--enable ()
  "Enable Fira Code ligatures in current buffer."
  (setq-local fira-code-mode--old-prettify-alist prettify-symbols-alist)
  (setq-local prettify-symbols-alist (append (fira-code-mode--make-alist fira-code-mode--ligatures) fira-code-mode--old-prettify-alist))
  (prettify-symbols-mode t))

(defun fira-code-mode--disable ()
  "Disable Fira Code ligatures in current buffer."
  (setq-local prettify-symbols-alist fira-code-mode--old-prettify-alist)
  (prettify-symbols-mode -1))

(define-minor-mode fira-code-mode
  "Fira Code ligatures minor mode"
  :lighter " Fira Code"
  (setq-local prettify-symbols-unprettify-at-point 'right-edge)
  (if fira-code-mode
      (fira-code-mode--enable)
    (fira-code-mode--disable)))

;(provide 'fira-code-mode)

```

**Comment by radrow** [comment]
> So this?
> 
> ```emacs-lisp
> (defun fira-code-mode--make-alist (list)
>   "Generate prettify-symbols alist from LIST."
>   (let ((idx -1))
>     (mapcar
>      (lambda (s)
>        (setq idx (1+ idx))
>        (let* ((code (+ #Xe100 idx))
> 	      (width (string-width s))
> 	      (prefix ())
> 	      (suffix '(?\s (Br . Br)))
> 	      (n 1))
> 	 (while (< n width)
> 	   (setq prefix (append prefix '(?\s (Br . Bl))))
> 	   (setq n (1+ n)))
> 	 (cons s (append prefix suffix (list (decode-char 'ucs code))))))
>      list)))
> 
> (defconst fira-code-mode--ligatures
>   '("www" "**" "***" "**/" "*>" "*/" "\\\\" "\\\\\\"
>     "{-" "[]" "::" ":::" ":=" "!!" "!=" "!==" "-}"
>     "--" "---" "-->" "->" "->>" "-<" "-<<" "-~"
>     "#{" "#[" "##" "###" "####" "#(" "#?" "#_" "#_("
>     ".-" ".=" ".." "..<" "..." "?=" "??" ";;" "/*"
>     "/**" "/=" "/==" "/>" "//" "///" "&&" "||" "||="
>     "|=" "|>" "^=" "$>" "++" "+++" "+>" "=:=" "=="
>     "===" "==>" "=>" "=>>" "<=" "=<<" "=/=" ">-" ">="
>     ">=>" ">>" ">>-" ">>=" ">>>" "<*" "<*>" "<|" "<|>"
>     "<$" "<$>" "<!--" "<-" "<--" "<->" "<+" "<+>" "<="
>     "<==" "<=>" "<=<" "<>" "<<" "<<-" "<<=" "<<<" "<~"
>     "<~~" "</" "</>" "~@" "~-" "~=" "~>" "~~" "~~>" "%%"
>     "x" ":" "+" "+" "*"))
> 
> 
> 
> (defvar fira-code-mode--old-prettify-alist)
> 
> (defun fira-code-mode--enable ()
>   "Enable Fira Code ligatures in current buffer."
>   (setq-local fira-code-mode--old-prettify-alist prettify-symbols-alist)
>   (setq-local prettify-symbols-alist (append (fira-code-mode--make-alist fira-code-mode--ligatures) fira-code-mode--old-prettify-alist))
>   (prettify-symbols-mode t))
> 
> (defun fira-code-mode--disable ()
>   "Disable Fira Code ligatures in current buffer."
>   (setq-local prettify-symbols-alist fira-code-mode--old-prettify-alist)
>   (prettify-symbols-mode -1))
> 
> (define-minor-mode fira-code-mode
>   "Fira Code ligatures minor mode"
>   :lighter " Fira Code"
>   (setq-local prettify-symbols-unprettify-at-point 'right-edge)
>   (if fira-code-mode
>       (fira-code-mode--enable)
>     (fira-code-mode--disable)))
> 
> ;(provide 'fira-code-mode)
> ```

It did not work for me. Instead I got strange characters and below
![_screenshot](https://user-images.githubusercontent.com/35342116/48772537-f9977d00-ecc4-11e8-9e99-6ce739c96f87.jpg)

**Comment by wedens** [comment]
@radrow  Do you have "Fira Code Symbol" font installed (not just plain Fira Code)?

Also you'll need to set the font for the character range: `(set-fontset-font t '(#Xe100 . #Xe16f) "Fira Code Symbol")`. For some reason this is not included in the snippet above.

**Comment by Triavanicus** [comment]
I updated the snippit, and put it in the ```(fira-code-mode--setup)``` function

**Comment by radrow** [comment]
Strange. Which version of emacs are you testing this on? I am using emacs 26.1 with spacemacs and putting snippet in `user-init` (before packages load)

**Comment by Profpatsch** [comment]
> It did not work for me. Instead I got strange characters and below

Have you restarted Emacs lor rebooted? That’s sometimes required to make font caches update.

**Comment by radrow** [comment]
Rebooted, no difference

**Comment by To1ne** [comment]
Thanks everyone. Especially @Triavanicus.

I've restructured the [wiki page](https://github.com/tonsky/FiraCode/wiki/Emacs-instructions) with all findings. It should be easy now for other to find them. So I'm closing this issue.

**Comment by To1ne** [comment]
@radrow I think the Fira Code Symbol font you have is not good. It seems characters have switched places. I hope we can some time soon have an official font with the symbols in the private Unicode area, but I'm leaving that to https://github.com/tonsky/FiraCode/issues/211.

But at the moment the wiki is suggesting the one from: https://github.com/tonsky/FiraCode/issues/211#issuecomment-239058632 The symbol map is included, so you can see if the error is an offset problem, or actually a swap of symbols?

If you see an offset issue, something odd happens with the generation of the `prettify-symbols-alist`. Can you please post the content of `prettify-symbols-alist` here?

**Comment by radrow** [comment]
@To1ne Sorry for late reply, but that's it:

```
(("www" 32 #1=(Br . Bl)
  32 #1# 32 #2=(Br . Br)
  57600)
 ("**" 32 #1# 32 #2# 57601)
 ("***" 32 #1# 32 #1# 32 #2# 57602)
 ("**/" 32 #1# 32 #1# 32 #2# 57603)
 ("*>" 32 #1# 32 #2# 57604)
 ("*/" 32 #1# 32 #2# 57605)
 ("\\\\" 32 #1# 32 #2# 57606)
 ("\\\\\\" 32 #1# 32 #1# 32 #2# 57607)
 ("{-" 32 #1# 32 #2# 57608)
 ("[]" 32 #1# 32 #2# 57609)
 ("::" 32 #1# 32 #2# 57610)
 (":::" 32 #1# 32 #1# 32 #2# 57611)
 (":=" 32 #1# 32 #2# 57612)
 ("!!" 32 #1# 32 #2# 57613)
 ("!=" 32 #1# 32 #2# 57614)
 ("!==" 32 #1# 32 #1# 32 #2# 57615)
 ("-}" 32 #1# 32 #2# 57616)
 ("--" 32 #1# 32 #2# 57617)
 ("---" 32 #1# 32 #1# 32 #2# 57618)
 ("-->" 32 #1# 32 #1# 32 #2# 57619)
 ("->" 32 #1# 32 #2# 57620)
 ("->>" 32 #1# 32 #1# 32 #2# 57621)
 ("-<" 32 #1# 32 #2# 57622)
 ("-<<" 32 #1# 32 #1# 32 #2# 57623)
 ("-~" 32 #1# 32 #2# 57624)
 ("#{" 32 #1# 32 #2# 57625)
 ("#[" 32 #1# 32 #2# 57626)
 ("##" 32 #1# 32 #2# 57627)
 ("###" 32 #1# 32 #1# 32 #2# 57628)
 ("####" 32 #1# 32 #1# 32 #1# 32 #2# 57629)
 ("#(" 32 #1# 32 #2# 57630)
 ("#?" 32 #1# 32 #2# 57631)
 ("#_" 32 #1# 32 #2# 57632)
 ("#_(" 32 #1# 32 #1# 32 #2# 57633)
 (".-" 32 #1# 32 #2# 57634)
 (".=" 32 #1# 32 #2# 57635)
 (".." 32 #1# 32 #2# 57636)
 ("..<" 32 #1# 32 #1# 32 #2# 57637)
 ("..." 32 #1# 32 #1# 32 #2# 57638)
 ("?=" 32 #1# 32 #2# 57639)
 ("??" 32 #1# 32 #2# 57640)
 (";;" 32 #1# 32 #2# 57641)
 ("/*" 32 #1# 32 #2# 57642)
 ("/**" 32 #1# 32 #1# 32 #2# 57643)
 ("/=" 32 #1# 32 #2# 57644)
 ("/==" 32 #1# 32 #1# 32 #2# 57645)
 ("/>" 32 #1# 32 #2# 57646)
 ("//" 32 #1# 32 #2# 57647)
 ("///" 32 #1# 32 #1# 32 #2# 57648)
 ("&&" 32 #1# 32 #2# 57649)
 ("||" 32 #1# 32 #2# 57650)
 ("||=" 32 #1# 32 #1# 32 #2# 57651)
 ("|=" 32 #1# 32 #2# 57652)
 ("|>" 32 #1# 32 #2# 57653)
 ("^=" 32 #1# 32 #2# 57654)
 ("$>" 32 #1# 32 #2# 57655)
 ("++" 32 #1# 32 #2# 57656)
 ("+++" 32 #1# 32 #1# 32 #2# 57657)
 ("+>" 32 #1# 32 #2# 57658)
 ("=:=" 32 #1# 32 #1# 32 #2# 57659)
 ("==" 32 #1# 32 #2# 57660)
 ("===" 32 #1# 32 #1# 32 #2# 57661)
 ("==>" 32 #1# 32 #1# 32 #2# 57662)
 ("=>" 32 #1# 32 #2# 57663)
 ("=>>" 32 #1# 32 #1# 32 #2# 57664)
 ("<=" 32 #1# 32 #2# 57665)
 ("=<<" 32 #1# 32 #1# 32 #2# 57666)
 ("=/=" 32 #1# 32 #1# 32 #2# 57667)
 (">-" 32 #1# 32 #2# 57668)
 (">=" 32 #1# 32 #2# 57669)
 (">=>" 32 #1# 32 #1# 32 #2# 57670)
 (">>" 32 #1# 32 #2# 57671)
 (">>-" 32 #1# 32 #1# 32 #2# 57672)
 (">>=" 32 #1# 32 #1# 32 #2# 57673)
 (">>>" 32 #1# 32 #1# 32 #2# 57674)
 ("<*" 32 #1# 32 #2# 57675)
 ("<*>" 32 #1# 32 #1# 32 #2# 57676)
 ("<|" 32 #1# 32 #2# 57677)
 ("<|>" 32 #1# 32 #1# 32 #2# 57678)
 ("<$" 32 #1# 32 #2# 57679)
 ("<$>" 32 #1# 32 #1# 32 #2# 57680)
 ("<!--" 32 #1# 32 #1# 32 #1# 32 #2# 57681)
 ("<-" 32 #1# 32 #2# 57682)
 ("<--" 32 #1# 32 #1# 32 #2# 57683)
 ("<->" 32 #1# 32 #1# 32 #2# 57684)
 ("<+" 32 #1# 32 #2# 57685)
 ("<+>" 32 #1# 32 #1# 32 #2# 57686)
 ("<=" 32 #1# 32 #2# 57687)
 ("<==" 32 #1# 32 #1# 32 #2# 57688)
 ("<=>" 32 #1# 32 #1# 32 #2# 57689)
 ("<=<" 32 #1# 32 #1# 32 #2# 57690)
 ("<>" 32 #1# 32 #2# 57691)
 ("<<" 32 #1# 32 #2# 57692)
 ("<<-" 32 #1# 32 #1# 32 #2# 57693)
 ("<<=" 32 #1# 32 #1# 32 #2# 57694)
 ("<<<" 32 #1# 32 #1# 32 #2# 57695)
 ("<~" 32 #1# 32 #2# 57696)
 ("<~~" 32 #1# 32 #1# 32 #2# 57697)
 ("</" 32 #1# 32 #2# 57698)
 ("</>" 32 #1# 32 #1# 32 #2# 57699)
 ("~@" 32 #1# 32 #2# 57700)
 ("~-" 32 #1# 32 #2# 57701)
 ("~=" 32 #1# 32 #2# 57702)
 ("~>" 32 #1# 32 #2# 57703)
 ("~~" 32 #1# 32 #2# 57704)
 ("~~>" 32 #1# 32 #1# 32 #2# 57705)
 ("%%" 32 #1# 32 #2# 57706)
 ("x" 32 #2# 57707)
 (":" 32 #2# 57708)
 ("+" 32 #2# 57709)
 ("+" 32 #2# 57710)
 ("*" 32 #2# 57711))
```

**Comment by Triavanicus** [comment]
I have it in my settings.org file which is called by my initial.el then I
call the setup function, and add the hook function to prog-mode

**Comment by ezmiller** [comment]
@Triavanicus so far I've just dropped it into my `.spacemacs` file. I didn't realize that to get this to work you need to activate the mode. I tested this by just doing it in the editor: `C-M 'fira-code-mode`.

That showed some progress, but when I activated the mode I was getting odd symbols with numbers, e.g.

![image](https://user-images.githubusercontent.com/772738/50389305-c21e5500-06f6-11e9-8778-611df120bdfd.png)

Any idea why this may be happening? Thanks for the help!

**Comment by Triavanicus** [comment]
Do you have the Fira code Symbols font installed from
https://github.com/tonsky/FiraCode/issues/211#issuecomment-239058632

**Comment by ezmiller** [comment]
I downloaded that, installed it using the "Font Book" app on mac, and then added this to the font settings in my `.spacemacs` file:

```
   dotspacemacs-default-font '(("Fira Code"
                                :size 16
                                :weight normal
                                :width normal
                                :powerline-scale 1.2)
                               ("Fira Code Symbol"
                                :size 16
                                :weight normal
                                :width normal
                                :powerline-scale 1.2))

```

**Comment by ezmiller** [comment]
Hi, I posted the entirety of the snippet above into the `.spacemacs` file, below everything else. My understanding was that the snippet above enables that mode such that I was able to activate it in the editor.

I haven't tried that method you referenced as I was trying to avoid installing the alternate mac port of emacs.

**Comment by Triavanicus** [comment]
@ezmiller 
which, at least for me, it does so long as do the following. Also reading some more into the issue, you might have to reset your fontconfig cache (which if you know how to do, it will save you a reboot, otherwise, you will have to reboot :( ) 
```emacs-lisp
(fira-code-mode--setup)
(fira-code-mode)
```
other than that, I don't know what your issue could be.

**Comment by ejmg** [comment]
@Triavanicus I really appreciate your solution that you added to the wiki. I think it works a lot better than the previous hack I had used.

I have just one question, if you don't mind?

How can I disable the ligature rendering for `"x"` from the prettify-symbols list without messing up the character encoding? Based on the way you enumerate the font character codes, if I were to remove "x" from `fira-code-mode--ligatures`, every ligature after that is offset by -1, meaning `:` renders as `x`, `+` renders as `:` and so forth.

I don't fully understand what `fira-code-mode--make-alist` is doing (or how fonts work on emacs, for that matter), and have tried to skip over/ignore adding the encoding for `"x"` to no avail. Is there any easy/obvious way to "unset" or skip over the `"x"` ligature provided by siegebell's FiraCode-Regular-Symbol pack?

**Comment by Triavanicus** [comment]
You should be able to just delete everything after the "x" i.e.
```emacs-lisp

(defconst fira-code-mode--ligatures
  '("www" "**" "***" "**/" "*>" "*/" "\\\\" "\\\\\\"
    "{-" "[]" "::" ":::" ":=" "!!" "!=" "!==" "-}"
    "--" "---" "-->" "->" "->>" "-<" "-<<" "-~"
    "#{" "#[" "##" "###" "####" "#(" "#?" "#_" "#_("
    ".-" ".=" ".." "..<" "..." "?=" "??" ";;" "/*"
    "/**" "/=" "/==" "/>" "//" "///" "&&" "||" "||="
    "|=" "|>" "^=" "$>" "++" "+++" "+>" "=:=" "=="
    "===" "==>" "=>" "=>>" "<=" "=<<" "=/=" ">-" ">="
    ">=>" ">>" ">>-" ">>=" ">>>" "<*" "<*>" "<|" "<|>"
    "<$" "<$>" "<!--" "<-" "<--" "<->" "<+" "<+>" "<="
    "<==" "<=>" "<=<" "<>" "<<" "<<-" "<<=" "<<<" "<~"
    "<~~" "</" "</>" "~@" "~-" "~=" "~>" "~~" "~~>" "%%"))

```

**Comment by soraros** [comment]
This one is easy. Replace `fira-code-mode--make-alist` with the following and pass in only the list of symbols you want to enable.
```lisp
(defun fira-code-mode--make-alist (lat)
  "Generate prettify-symbols alist from LIST."
  (let ((alist (cl-mapcar #'cons
                          fira-code-mode--ligatures
                          (number-sequence 0 (- (length fira-code-mode--ligatures) 1)))))
    (mapcar
     (lambda (s)
       (let* ((idx (cdr (assoc s alist)))
              (code (+ #Xe100 idx))
              (width (string-width s))
              (prefix ())
              (suffix '(?\s (Br . Br)))
              (n 1))
         (while (< n width)
           (setq prefix (append prefix '(?\s (Br . Bl))))
           (setq n (1+ n)))
         (cons s (append prefix suffix (list (decode-char 'ucs code))))))
     lat)))
```

**Comment by GaussianWonder** [comment]
> The methods for Emacs currently explained on the [wiki](https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs) are not really working for me. I would like to facilitate emacs `prettify-symbols-mode` instead (as suggested by [@siegebell](https://github.com/tonsky/FiraCode/issues/211#issuecomment-238432036)).
> 
> This is what I've got at the moment:
> 
> Enable prettify symbols globally:
> 
> ```emacs-lisp
> (global-prettify-symbols-mode 1)
> ```
> 
> Un-prettify symbols at point for easier editing (one of the reasons why I want to use this method):
> 
> ```emacs-lisp
> (setq prettify-symbols-unprettify-at-point t)
> ```
> 
> Define prettify symbols:
> 
> ```emacs-lisp
>   (add-hook 'prog-mode-hook
>             (lambda ()
>               (push '("<=" . ?≤) prettify-symbols-alist)))
> ```
> 
> For this last piece of config I need your help. I like to have the full list of symbol combo's (e.g. `<=`) with their ligature (e.g. `≤`). So I would appreciate you would share it with us.

i know this is suuuuuper late but this might help
https://www.copypastecharacter.com/all-characters. Just copy paste them, seems to work :))

**Comment by hyiltiz** [comment]
Does the wiki on Emacs support need an update now that HarfBuzz based font rendering is in Emacs?
