### ISSUE TITLE
<~> renders in a confusing way

### ISSUE THREAD

**Issue by jkcclemens** [tonsky/FiraCode#313]
In some IDEs, such as IntelliJ IDEA, `<~>` is used to hide explicit generic type parameters when they can be inferred.

![example](http://i.imgur.com/pPa1dYi.png)

`~>` rendering in such a way is acceptable, but `<~>` is confusing.

**Comment by tonsky** [comment]
I’ve fixed that in Fira Code 1.204. Please update. Related #179
