### ISSUE TITLE
The font is too thin (at least on HiDPI screens)

### ISSUE THREAD

**Issue by magicgoose** [tonsky/FiraCode#316]
I think it should at least have an alternate variant which is thicker (has bigger minimum line thickness). That would be easier on eyes for those who have some vision problems…

Right now it looks like this (OS X, HiDPI screen, IntelliJ IDEA, font size = 15):
![screen shot 2016-11-23 at 10 56 58 pm-fs8](https://cloud.githubusercontent.com/assets/1442206/20578752/980dfb0c-b1d1-11e6-8b47-b761fb19bc20.png)

I think it'd be better if it looked like this:
![screen shot 2016-11-23 at 10 56 58 pm_bolder-fs8](https://cloud.githubusercontent.com/assets/1442206/20578779/b6030f30-b1d1-11e6-9074-0b598d002537.png)
(this is obviously just a rough approximation done in raster image editor, but you get the idea)

For comparison, the same text in Menlo font:
![screen shot 2016-11-23 at 11 11 50 pm-fs8](https://cloud.githubusercontent.com/assets/1442206/20578916/540e3132-b1d2-11e6-8b19-d675965225bf.png)

**Comment by tonsky** [comment]
Try Retina weight

**Comment by sp-1234** [comment]
what is "Retina weight"?

**Comment by jdreesen** [comment]
For `otf` and `ttf` versions there is a `Fira Code Retina` version.

**Comment by omouse** [comment]
^ can we get a link so we know how to install it?

I'm working on OS X and while the font looks good on the retina laptop it looks awful on a 1080p 27" screen.

**Comment by tonsky** [comment]
@omouse instructions are here https://github.com/tonsky/FiraCode/wiki#installing-font

**Comment by omouse** [comment]
awesome! thank you! 😄
