### ISSUE TITLE
-> ligature doesn't seem to work on VS2013 / Windows 7

### ISSUE THREAD

**Issue by ryani** [tonsky/FiraCode#32]
Repro steps:

Download font from https://github.com/tonsky/FiraCode/releases/download/0.5/FiraCode-Regular.otf
Open Control Panel > Fonts
Drag font from download into font window
Open Visual Studio Express 2013
Tools > Options > Environment > Fonts and Colors
Select Fira Code 9 pt and click OK
The >>= ligature works as do all the other ones I tested, except the -> ligature doesn't work

Any idea what's going on here?  Is VS overriding that ligature?  Or is the font bugged?

**Comment by tonsky** [comment]
No idea. IDE might mess up with ligatures rendering, though. E.g. in
LightTable, if color scheme has different colors for `#` and `()` in `#()`,
then `#(` would not be rendered as a ligature. Essentially tokenization of
text might be an obstacle for some ligatures.

**Comment by kxepal** [comment]
Confirm the same behaviour for Geany with 0.5 version: `->` ligature works for Python syntax, but not for Erlang. Seems like editor tokenization issue indeed. But this is the only rendering issue so far.

**Comment by tonsky** [comment]
Closing as I can’t do anything about it. Thanks for reporting

**Comment by oriSomething** [comment]
might related to the way `glyphs` export fonts. it's known there are some export problems with OT features on windows' engines (GDI+ / DirectWrite).
