### ISSUE TITLE
Bold and italic version seems to have a different width to a non-bold version in IDEA

### ISSUE THREAD

**Issue by mnn** [tonsky/FiraCode#320]
In following pictures is exactly same region of code.

Different font:
![](http://i.imgur.com/IiCN1lh.png)

FiraCode:
![](http://i.imgur.com/j7Bw51M.png)

Any idea how to setup IDEA to not break characters grid? Or is the font broken?

**Comment by tonsky** [comment]
Fira Code does not provide italics. Idea uses its own algorithms to generate italisized characters on the fly. I recommend reporting the issue to their bugtracker

**Comment by mnn** [comment]
It [doesn't seem](https://youtrack.jetbrains.com/issue/IDEA-161774) IDEA guys can solve it on their end. Any plans on adding support for italics and bold variants?

**Comment by tonsky** [comment]
@mnn this is a different kind of problem. They can’t to much about how italisized characters end up looking, but changing glyphs width from monospased to non-monospased is a different type of problem. You should probably create a new issue, they might want to look into that.

As of adding italics, I can’t do it on my own, but if the guys at Carrois decide to add it I’ll be happy to copy it over. BTW bold weight is already in the font

**Comment by tonsky** [comment]
Those are proportional versions. Fira Code is based on Fira Mono, a monospaced one suitable for programming
