### ISSUE TITLE
Font not Working on VS 2017 RC

### ISSUE THREAD

**Issue by WoozChucky** [tonsky/FiraCode#324]
Hey, as the title says, the font is not working correctly on Visual Studio 2017 RC.

In the text editor, doesnt display at all. But for example in the output window it does, without Ligatures.

Could be a Visual Studio problem only ?

**Comment by tonsky** [comment]
It could be VS problem or OS problem or many other things. Are you positive
that exact same version of Fira Code worked before on the same machine in
VS 2016?

**Comment by vilinski** [comment]
not surprising, 2017 is otherwise very buggy. so I would just wait for more stable version

**Comment by WoozChucky** [comment]
On the same machine (Win 10 Pro 64Bit), VS 2016 works with the font. And VS 2017RC doesn't. So i'de say its a VS problem.

**Comment by ciel** [comment]
Yeah, this doesn't work in VS2017, but was fine in 2015. Pretty sure this is a problem with Visual Studio
