### ISSUE TITLE
Arrows don't seem to work in Atom

### ISSUE THREAD

**Issue by ElectricCoffee** [tonsky/FiraCode#328]
For whatever reason, the arrows don't render correctly for me in Atom: 
<img width="387" alt="screen shot 2016-12-11 at 11 45 37" src="https://cloud.githubusercontent.com/assets/1515791/21079623/87b6959c-bf97-11e6-9b44-366b5dde0e16.png">
While the exact same code renders just fine in the terminal:
<img width="318" alt="screen shot 2016-12-11 at 11 46 06" src="https://cloud.githubusercontent.com/assets/1515791/21079628/9813100a-bf97-11e6-8642-f5f6723109c5.png">

Equality and inequality operators render just fine, but the arrows seem to mess up for some reason.

**Comment by tonsky** [comment]
Yeah, that’s the problem with syntax highlight tokenizer. Open issue in
Atom repo or where the highlighter is implemented
