### ISSUE TITLE
Separate []

### ISSUE THREAD

**Issue by rafalkrupinski** [tonsky/FiraCode#329]
Characters '[' immediately followed by ']' look like a square. Is it just me or is it confusing?

Can someone explain how a square is meaningful in context of arrays/lists/slices? Is it meaningful in some contexts in languages not in C family?

Besides, square is often used to represent unknown UTF code.

**Comment by jdreesen** [comment]
No it doesn't! Use the latest version. It was fixed in [1.201](https://github.com/tonsky/FiraCode/releases/tag/1.201) months ago.
And please search the (closed) issues before opening new ones. (#92, #218, #224, #315)

**Comment by rafalkrupinski** [comment]
I'm using the latest version and it does. IntelliJ 16.3 on Ubuntu Linux 16.10.

No need to yell.

BTW github search seems to ignore [] characters.

**Comment by LFalch** [comment]
Commit 8cecc3c1f23c7f441a05ed337ee2ca616842af47 removed that ligature.

**Comment by jdreesen** [comment]
Are you sure you are using the latest version? Because IntelliJ has Fira Code bundled, but I'm not sure which version they use. Maybe try in another editor to be sure?

Sorry for yelling. I know that GitHub's search fails for many of the issues in this repository. But a quick look in the list of closed issues would have helped. A similar issue is among the first 5 in the list ;)

**Comment by rafalkrupinski** [comment]
OK It seems that it's an old version bundled with intellij. I just checked with gedit and it's fixed there.
Unfortunately old version in Intellij overrides newer one installed in system.

I just searched for [] in issues. There was no warnings and no results so I just assumed that's the design. Hence the "is it just me?". My bad, I could've thought that some special characters may be ignored.

Developing fonts must be a frustrating task...

Regards.

**Comment by jdreesen** [comment]
Well, since you're not the first that stumbled upon the outdated version that's bundled in JetBrains IDE's maybe @tonsky should add a warning somewhere.

Would the [wiki](https://github.com/tonsky/FiraCode/wiki/Intellij-products-instructions) be the right place for this?

**Comment by rafalkrupinski** [comment]
@jdreesen please see the update to the previous comment, Still a note could be useful.

**Comment by tonsky** [comment]
I’ve updated wiki https://github.com/tonsky/FiraCode/wiki/IntelliJ-products-instructions
