### ISSUE TITLE
Does not work on Mac OS X 10.10

### ISSUE THREAD

**Issue by iyerland** [tonsky/FiraCode#33]
The ligatures are not being rendered correctly (or rendered at all, in the manner shown). Looks exactly like Fira Mono!

**Comment by ricogallo** [comment]
Same here

**Comment by tonsky** [comment]
What editor are you using?

**Comment by iyerland** [comment]
Atom Editor. https://atom.io/

**Comment by tonsky** [comment]
Atom does not support ligatures, see https://github.com/atom/atom/issues/6055
