### ISSUE TITLE
Parenthesis inner padding is too wide.

### ISSUE THREAD

**Issue by TeffenEllis** [tonsky/FiraCode#331]
I'm on macOS Sierra using VSCode and FiraCode has an unusual amount of distance inside of parenthesis. 

<img width="884" alt="screen shot 2016-12-15 at 3 21 18 pm" src="https://cloud.githubusercontent.com/assets/592134/21245975/996ff5bc-c2da-11e6-97d6-428ef18211cc.png">

Cheers

**Comment by tonsky** [comment]
How do you mean? What proper padding should look like?

**Comment by timelesshaze** [comment]
It looks bad, but it has nothing to do with the font itself.
The syntax highlighter is mixing normal and italic fonts for function definitions.
Function calls don't use italics.

* parseInput definition: LHS space too wide, RHS space to narrow
* getDelimiter call: LHS space = RHS space, narrow and looks fine

**Comment by TeffenEllis** [comment]
@tonsky,  

@timelesshaze's description was a big help 🙂  
I was able to reduce the extra padding by configuring my theme to not use italics in function call arguments.

<img width="792" alt="screen shot 2016-12-16 at 2 53 39 pm" src="https://cloud.githubusercontent.com/assets/592134/21281180/966d3a80-c39f-11e6-99bd-990e876a0bb9.png">

Is it possible to bring parenthesis closer to letters and numbers?

Cheers

**Comment by tonsky** [comment]
It is possible, but I don’t see a problem with the current spacing either
