### ISSUE TITLE
the square brackets shown at different heights

### ISSUE THREAD

**Issue by BorzdeG** [tonsky/FiraCode#332]
font size 12 and 13 - bad
font size 14 - good

problem is bold font

screenshot 0: https://youtrack.jetbrains.com/_persistent/Screenshot_20161209_145420.png?file=74-368256
screenshot 1: https://youtrack.jetbrains.com/_persistent/Screenshot_20161209_145345.png?file=74-368257

YouTrack issue: https://youtrack.jetbrains.com/issue/IDEA-165277

**Comment by tonsky** [comment]
I’m pretty sure it was fixed at some point, but I can’t find the exact issue. Please reopen if it’s still a problem
