### ISSUE TITLE
Extending FiraCode for Jetbrains

### ISSUE THREAD

**Issue by jblouirelink** [tonsky/FiraCode#341]
I know this is probably not the best place to put this but barring a lack of comments section on github and the zero available information on the internet for this subject.

Is it possible to extend FiraCode with new ligatures for different character combinations?  Such as "f u n c t i o n"?  Does it require some jetbrains special functionality or should it work out of the box by just using the font?  I have tried to modify the FiraCode font files with no success.

Again sorry for asking this here, but this is like the only place that might be able to solve this problem.

Thanks!

**Comment by tonsky** [comment]
> Does it require some jetbrains special functionality or should it work out of the box by just using the font?

Jetbrains products just render font ligatures, pretty much as any other editor out there. It’s a property of a font, there’s no special cases for any of the editors

> Is it possible to extend FiraCode with new ligatures for different character combinations? 

Yes, it is possible. Currently, I’m using Glyphs.app to work with Fira Code. But you can also open OTF file in pretty much any font editor out there and modify to your taste

**Comment by jblouirelink** [comment]
Oh my gosh!  Thank you so much for responding!  I guess I dont fully understand how ligatures work in fonts, I was going to use the Glyphs.app but it seems like its Mac only, I might try FontForge next.  Thank you!
