### ISSUE TITLE
Switch to slashed zero by default

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#342]
It looks less like 8

**Comment by chillum** [comment]
err, I just got a 1.205 Fira Code and I reverted it to 1.204, it really has a better zero IMO (and never confused it with 8). I understand it correctly that if I want an old, dotted zero, I should stick to 1.204 and not update further?

**Comment by tonsky** [comment]
Yes. If you have control over OpenType features (e.g. in web-based editors via CSS), try enabling `zero` feature flag. E.g. in CSS

```css
... { font-feature-settings: "zero"; }
```

**Comment by chillum** [comment]
in my case I have the OTF font in Mac and I use it in Terminal. not sure if I can tweak this.

**Comment by RobertBoganKang** [comment]
The new slashed 0 are great theoretically (angle and its thickness), however when I first look at it, I thought it looks ugly. The slash is so thin that it looks lack of unity.

**Comment by DL6AKU** [comment]
How can I get back the old dotted zero? Slashed zeros looks uneven when you have a lot of zeros next to each other (as often happens).

**Comment by tonsky** [comment]
Use [1.204 version](https://github.com/tonsky/FiraCode/releases/tag/1.204)

**Comment by DL6AKU** [comment]
Are you saying "legacy" users who are used to working with your font for months or years are basically out of luck and we can't use a new version of your font ever again?

Or are there plans for a reasonable way to have dotted and slashed zeros coexist? Like a "compile time switch" (I don't know if there's something like that for fonts) or a seperate git branch? Or maybe a variant like you did for Retina? I would wager there's more people that want a dotted zero than there are people with Retina displays.

**Comment by tonsky** [comment]
Retina is just another weight, nothing special about it (except the name). If I figure out eventually how to do per-user customization, I’ll bring zero back as an option

**Comment by DL6AKU** [comment]
Thank you, that is great news! It is very good to hear that you have something planned for long term users. I am looking forward to hop back on to the master branch again to get your new goodies. Very excited for new features usually.
