### ISSUE TITLE
Arbitrary-length arrows

### ISSUE THREAD

**Issue by be5invis** [tonsky/FiraCode#346]
To support LONG arrows like `<-----------------------` and `---------------------->`
The current Iosevka implementation is:

Leftward : A chaining substitution like `sub hyphen.cont hyphen' by hyphen.cont`
Rightward : A Reverse Chained Single Substitution table like `reversesub hyphen' hyphen.cont by hyphen.cont`. See [here](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#5.h).

NOTE: FontForge cannot export Reverse Subs.

**Comment by tonsky** [comment]
it’s actually not a bad idea

**Comment by wopian** [comment]
This is it in action for reference:

![](http://i.imgur.com/OWIvmKp.png)

**Comment by tonsky** [comment]
@wopian what font is that on the screenshot?

**Comment by alexeyten** [comment]
Iosevka, I guess
https://typeof.net/Iosevka/

**Comment by wopian** [comment]
> @wopian what font is that on the screenshot?

https://github.com/be5invis/Iosevka/blob/master/README.md#ligations

**Comment by tonsky** [comment]
Thanks! I checked it but missed the point that not all arrows are enabled by default. Also double arrows looked differently in 2017.

BTW it’s iosevka, not Losevka (although I was wondering the same question every time I saw the name. I went and checked to be sure just now. The importance of using the proper font :)

**Comment by wopian** [comment]
> BTW it’s iosevka, not Losevka (although I was wondering the same question every time I saw the name. I went and checked to be sure just now. The importance of using the proper font :)

The downside of most repositories being all-lowercase and `I` being identical to `l` 😞

**Comment by tonsky** [comment]
Done in v4
