### ISSUE TITLE
Box drawing light glyphs don't quite line up

### ISSUE THREAD

**Issue by codahale** [tonsky/FiraCode#349]
Spacemacs has this in its main screen:

```
╭─
│
```

(That's `U+256D` and `U+2500` on the first line, `U+2502` on the second.)

It renders like this:

<img width="49" alt="screen shot 2017-01-20 at 18 39 31" src="https://cloud.githubusercontent.com/assets/207/22171324/d7373ef6-df3f-11e6-94c8-b118b7257f91.png">

**Comment by tonsky** [comment]
These glyphs are not in the font yet. I guess Spacemacs uses some another
font to render them. Although I think they must be in the programming font,
so eventually I’ll add them

**Comment by FHTheron** [comment]
These round corner glyphs are also used in `tig` (optional, but best, graph drawing mode) and in mintty on Windows it is misaligned. In the basic console (cmd.exe) it's just a `?` character instead of the round corner. In VS Code on Windows it looks almost OK, but not quite aligned.

**Comment by tonsky** [comment]
Fixed in v2
