### ISSUE TITLE
Forward pipe operator |> (F# and Elixir) 

### ISSUE THREAD

**Issue by leikind** [tonsky/FiraCode#35]
A forward pipe operator is a nice syntax sugar present in F# and Elixir (and maybe in some other languages) which allows to rewrite 

```elixir
odd? = fn(v) -> rem(v, 2) != 0 end
Enum.sum(Stream.filter(Stream.map(1..100_000, &(&1 * 3)), odd?))
```

as

```elixir
odd? = fn(v) -> rem(v, 2) != 0 end
1..100_000  |> Stream.map(&(&1 * 3))  |> Stream.filter(odd?) |> Enum.sum
```

or on multiple lines:

```elixir
1..100_000 
 |> Stream.map(&(&1 * 3)) 
 |> Stream.filter(odd?) 
 |> Enum.sum
```

This is an awesome operator as it makes it very visible that FP is all about a flow of transformations of data.

Would you consider including it into FiraCode? To be honest  I have a very vague idea what symbol it should be, as all nice arrows have already been used

**Comment by tonsky** [comment]
Well, good idea, I’ll look into it. Does `<|` operator exists anywhere?

**Comment by leikind** [comment]
Yes,  it does exist in F#, and it is called a backwards pipe operator. 

http://stackoverflow.com/questions/5443805/why-use-a-backward-pipe-operator-instead-of-function-chaining

Initially I wanted to include it in this issue but for some reason decided not to :)

**Comment by gusaiani** [comment]
+1

**Comment by tonsky** [comment]
Check out [version 0.6](https://github.com/tonsky/FiraCode/releases/tag/0.6)
