### ISSUE TITLE
Request: enhancement the @ and & characters

### ISSUE THREAD

**Issue by duongphuhiep** [tonsky/FiraCode#352]
It is very subjective, I think that FiraCode fonts is the most beautiful mono-fonts out there. 

However I found that the "@" and "&" are a little bit confusing. 

I got 2 problems with them: 

![image](https://cloud.githubusercontent.com/assets/1638594/22203510/bddf5af8-e16d-11e6-89b1-a55b9586de99.png)

1) they are not as distinguishable with the normal 'o' as other mono-fonts.

2) they stand-out too much, for example: when I read "@to_refund", I should concentrate more on the "to_refund" part, because the "@" is only a side character. But in FiraCode, the '@' usually captures my attention more than necessary. 
 * because I should put some effort to make sure it is not the "o"
 * or because the character '@' is just "too pretty" in FiraCode

As I said, it is very subjective, maybe I'm the only one annoying with these 2 characters, and I might get used to them with time. I tried many other fonts, but I still think FiraCode is the best 

Thank you for reading

**Comment by wopian** [comment]
I find Fira Mono to have the easiest (and cleanest) & and @ symbols, fitting the rest of the font's style, The & used in Consolas looks way out of place.

**Comment by duongphuhiep** [comment]
@wopian I completely agree with you.

These 2 characters are pretties and so well blends in with other normal characters.

It is why it makes (my) codes more difficult to read.

The & and @ of consolas are standing out of place so I could easily distinguish and ignore them to concentrate on the important parts of the codes.

it is like reading a black text on a white background is easier than reading a gray-text on a white background.

Though, many websites put the bright color texts in bright background. It might looks nice, but not for persons with bad eyesight who want to read the text content.

**Comment by nemesit** [comment]
the @ in fira is ridiculously ugly it's basically a dealbreaker. It should be like menlo's @ not this half broken character

**Comment by jdreesen** [comment]
I think these changes should be requested at the [Fira repository](https://github.com/mozilla/Fira) directly.

**Comment by tonsky** [comment]
I like how `@` and `&` look in Fira Code. Unless there’re serious legibility reasons I don’t want to change those.

**Comment by nemesit** [comment]
& is fine but @ is basically a completely different symbol

**Comment by nemesit** [comment]
I guess FF_DIN has the best @ but basically all fonts except fira keep the fully circled @
<img width="544" alt="comparison" src="https://cloud.githubusercontent.com/assets/554205/26645834/cbaa40ea-4639-11e7-8242-e66222bf4916.png">

**Comment by tonsky** [comment]
Yes but you’ll be using Fira Code on a daily basis. Sure you can learn to recognize it?

**Comment by nemesit** [comment]
I believe it does indeed reduce readability as it blends in a little too well with the rest of the text

<img width="1440" alt="finding" src="https://cloud.githubusercontent.com/assets/554205/26646256/36e37d26-463b-11e7-896f-1bf215a72069.png">

Also it destroys an otherwise awesome font's design ;-p

**Comment by dhouck** [comment]
I believe this is one of the places where different people see different amounts of legibility concerns. I dislike both the `&` and `@`, especially the `@`, but I think I can get used to it.

If there were alternate characters available as an OpenType feature, I would use a more standard-looking `@` and `&` in a heartbeat (and disable the `www` ligature, but that’s literally a different issue). In general I love this font, but there are some small things like that which do really bug me.

**Comment by nemesit** [comment]
Here are a few alternate @s in combination with fira mono (including fira mono's @)

<img width="328" alt="screen shot 2017-05-31 at 20 10 26" src="https://cloud.githubusercontent.com/assets/554205/26646788/4222f5e8-463d-11e7-954e-64a846614dab.png">

the & could be improved a little but overall is far away from being as bad as the @ symbol ;-p, the www ligature is also a bit weird yeah xD

**Comment by dhouck** [comment]
I like the `@and` version best in that, and either the `@scrambled` or `@it` worst. What do other people think?

And yeah, when I said it was literally a different issue, I meant #253, which is an anagram of this issue’s number but is not the same one.

**Comment by tonsky** [comment]
Well I like `@it` most out of these five. I guess everybody has different tastes

**Comment by nemesit** [comment]
lets all just agree that we dislike the @scrambled version ;-p

**Comment by j-f1** [comment]
I think that `@type` and `@and` are too detailed — the symbol should be really simple, like `@it`.

**Comment by dhouck** [comment]
How is `@type` more detailed than `@gallery`?

And if we switched from `@scrambled` to `@it`, that wouldn’t make things worse from my perspective and it seems like other people would like it better, so it seems like the switch might be a good idea. Although I would still prefer some sort of character variant option for a more traditional at-sign.

**Comment by j-f1** [comment]
@dhouck It is a little smaller and harder to read.

**Comment by wopian** [comment]
Prefer `@scrambled` by a long shot.

**Comment by nemesit** [comment]
@scrambled is not an @ it's just some random symbol (@it too but it still resembles the main ideas of the @ symbol)

**Comment by dhouck** [comment]
It depends on what you mean by “the main idea of the @ symbol”. I’d describe it as a lowercase a with a long tail curving up and over, coming almost full circle. Both `@scrambled` and `@it` (when you put those not in backticks you spam somebody) don’t have that; `@it` doesn’t have the lower-case a and `@scrambled` doesn’t have a long enough tail.

This is why I dislike those more than the others, and also why I like `@and` best (the others, instead of using the tail, use the top of the a; this is particularly obvious in PT_MONO 24pt). I don’t mind this as much because at a quick glance it just makes the character look weird instead of hard to recognize.

**Comment by nemesit** [comment]
remember that my examples are from existing fonts so none of them have to be used exactly as they are now. plus here are some more. I think something like the last one would be the most fitting as it could be realized as a ligature with other characters.

<img width="371" alt="screen shot 2017-05-31 at 23 23 26" src="https://cloud.githubusercontent.com/assets/554205/26654759/46104b40-4658-11e7-82f5-0ce7c851b7d6.png">

**Comment by nemesit** [comment]
obviously it should still stand out in order to be easily identifed in text

**Comment by dhouck** [comment]
Of those, I like `@to` and `@specimen` the best, or `@mono` if it is made to ligature where appropriate (which I think might involve more work than would be worth it, if the ligature needs to be made separately for each letter). Despite my description of what I like in an `@`, I don’t like `@table` because the gap between the start and end of the tail is difficult to distinguish, making it hard to read.

(Obviously when I said lower-case a, I meant the single-story version, not the double-story version.)

**Comment by duongphuhiep** [comment]
as @jdreesen suggestion:
https://github.com/mozilla/Fira/issues/207

thanks

**Comment by mh-firouzjaah** [comment]
> I like how `@` and `&` look in Fira Code. Unless there’re serious legibility reasons I don’t want to change those.

hi, but there is really a problem with '@' in fira, it will be worse if '~'become before '@' and in that case it seems this are joined together and its one character itself! a handsome '@' ;)
