### ISSUE TITLE
HTML self-closing tag ligatures not fully supported with void elements.

### ISSUE THREAD

**Issue by edward-shen** [tonsky/FiraCode#353]
All HTML void tags and how FiraCode interacts with them are shown below.

![Imgur](http://i.imgur.com/glTte2Z.png)

Although some void tags such as `<base />` and `<img />` have proper self-closing ligatures, other tags such as `<hr />` and `<embed />`are not properly supported.

FiraCode Version: 1.204
Behavior can be seen on Atom 1.13.1 ia32.

**Comment by wopian** [comment]
All of those listed work fine on core Atom 1.13.1 ia32 (and VS2017/VSC) with FiraCode 1.204

![](https://i.imgur.com/sh7mO3Z.png)

(also `/` should be omitted on self-closing tags in HTML5)

**Comment by wopian** [comment]
This seems to be specific specific to Atom (1.13.1)

The ligatures display fine on *VS 2017 RC* 4.6, *VS Code* 1.8.1 & *Sublime 3* 3126

**Comment by tonsky** [comment]
It’s obvious from screenshot that it’s syntax highlighter issue. `/` and `>` are highlighted as differnt tokens. If that bothers you, open an issue in Atom repo
