### ISSUE TITLE
>= is not being replaced by a ligature

### ISSUE THREAD

**Issue by felipebelluco** [tonsky/FiraCode#361]
As it can be seen in the evidence below, >= is not being replaced by a ligature. Is that correct?

![screen shot 2017-02-05 at 12 15 46](https://cloud.githubusercontent.com/assets/1903259/22626796/f70177a6-eb9c-11e6-8ca2-e5bf8313d829.png)

**Comment by wopian** [comment]
what are you using it in & what version of FiraCode do you have?

**Comment by teoulas** [comment]
I just noticed the same problem on Android Studio. Here's what I get:

![android-studio-ligatures](https://cloud.githubusercontent.com/assets/53618/23281561/745ab644-fa26-11e6-84cb-7b83f7ac8953.png)

**Comment by tonsky** [comment]
Please open the issue in the corresponding editor’s issue tracker. There’s a problem with how they parse and render text, not with the font itself. Thanks!
