### ISSUE TITLE
How to enable this font in PHPstorm and Sublime Text 3 on Mac(Sierra 10.12.3)

### ISSUE THREAD

**Issue by stingzou** [tonsky/FiraCode#364]
In Clion, I found this configure:Enable font ligatures, so Clion can use FiraCode.
But I can't found this configure in Sublime Text 3 and PHPstorm, so it can't work well in them.
How to solve it?

**Comment by looperhacks** [comment]
See here: https://github.com/tonsky/FiraCode#editor-support Sublime Text doesn't support ligatures. For PHPStorm (and other IntelliJ products, including CLion), see: https://github.com/tonsky/FiraCode/wiki/Intellij-products-instructions

**Comment by stingzou** [comment]
But, on my Mac, I can't find this directory:
~/Library/Preferences/IntelliJIdeaXX or ~/Library/Preferences/IdeaICXX

**Comment by looperhacks** [comment]
If you use the current version of PHPStorm, you shouldn't have to edit the file manually. Just follow the instructions for version 2016.2 and later.

If that doesn't work, the directory for PHPStorm is ~/Library/Preferences/PhpStormXX or ~/Library/Preferences/WebIdeXX

**Comment by stingzou** [comment]
Yes, I found this directory:~/Library/Preferences/WebIde100, and I solved it, thanks!
