### ISSUE TITLE
Display SHY (Unicode U+00AD)

### ISSUE THREAD

**Issue by mcepl** [tonsky/FiraCode#365]
When I insert U+00AD into text, it shows in Fira only as a space.
![screenshot from 2017-02-17 01-13-39](https://cloud.githubusercontent.com/assets/198999/23047196/81550c00-f4ae-11e6-8e1f-fe4fc6782e48.png)
(there is this character between ``če`` and ``kala``).

**Comment by wopian** [comment]
<s>Imo, soft hypens should use the expected behaviour of them acting as a zero-width whitespace character and only showing a hypen when word wrapped.

I.e no visible space between `če` and `kala`

`če&#173;kala`
če&#173;kala</s>

This seems to be the editor incorrectly rendering the character and not FiraCode - works as expected in VSC & Atom

**Comment by mrackwitz** [comment]
Would it be possible to force `U+00AD` to always show up, as some kind of a dash or special character? This seems like it would be super useful.

**Comment by tonsky** [comment]
It’s supposed to be invisible, no?

**Comment by RubenVerg** [comment]
https://www.fileformat.info/info/unicode/char/00ad/index.htm shows it as a dash, but it doesn't explain usage or anything

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tonsky** [comment]
fileformat normally doesn’t explain anything. It’s just a catalogue of names and codes

https://en.wikipedia.org/wiki/Soft_hyphen

**Comment by RubenVerg** [comment]
It was the only result for "u00ad" that made sense in the context

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RubenVerg** [comment]
Oh, so it's like a non-breaking space but specifically for splitting hypenation of words? Makes sense to keep it invisible

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kenmcd** [comment]
> https://www.fileformat.info/info/unicode/char/00ad/index.htm shows it as a dash, but it doesn't explain usage or anything Get Outlook for Android<https://aka.ms/ghei36>
> […](#)
> ________________________________ From: Nikita Prokopov <notifications@github.com> Sent: Thursday, February 4, 2021 1:36:16 PM To: tonsky/FiraCode <FiraCode@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [tonsky/FiraCode] Display SHY (Unicode U+00AD) (#365) It’s supposed to be invisible, no? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftonsky%2FFiraCode%2Fissues%2F365%23issuecomment-773273691&data=04%7C01%7C%7Cc47c54db5f92427e12f408d8c909778f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637480389790210633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G2ZdtMB%2FA3%2F4T1Nk0AflVwL8amWEm%2BCe%2BM3NNgI7e7M%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMRJI3HNJLIR7KMATDKMRUDS5KIEBANCNFSM4DAO3VKQ&data=04%7C01%7C%7Cc47c54db5f92427e12f408d8c909778f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637480389790210633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iQGjPhaKVqmYByerFXyh%2BDcGCTrT%2FQZwFbeoSbDZ1QI%3D&reserved=0>.

SPAMMER.
Stop posting useless posts just to include your spam link.
This is not the first time and if there were an easy way to report your multiple posts I would.
But from now on every time I see you post some useless post just to post your spam link, this is going to be posted in response.

**Comment by mrackwitz** [comment]
Yeah, it is normally supposed to be invisible, which makes it tricky to use when working with code.

But maybe it helps to understand my use-case: localization. Languages with long words like German need like breaking by hyphenation to be displayed flexible at different font sizes. To achieve this, you often need to add soft hyphens at appropriate places, as a lot of text renderers don't know where syllables start and end automatically.

In fact a few localization softwares do in fact render soft hyphens as special characters.

**Comment by kenmcd** [comment]
> Yeah, it is normally supposed to be invisible, which makes it tricky to use when working with code.

Sorry, my comment was not aimed at you.
I accidentally posted my reply after clicking the more link. So your post got included. I edited it out, but I guess you got notified. My apologies.

**Comment by RubenVerg** [comment]
“Yeah, it is normally supposed to be invisible, which makes it tricky to use when working with code.” (sorry for not using Markdown’s quoting, am via email)

I’ve seen lots of people complaining that “code should show how text is encoded, not how it should be shown” and want ZWSP to be visible or whatever. Either it’s made a stylistical set (one I’ll never use) or I’ll stand in the idea that text code should be a realistic preview of what I’m going to see in my render.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RubenVerg** [comment]
> > https://www.fileformat.info/info/unicode/char/00ad/index.htm shows it as a dash, but it doesn't explain usage or anything Get Outlook for Androidhttps://aka.ms/ghei36
> > […](#)
> 
> SPAMMER.
> Stop posting useless posts just to include your spam link.
> This is not the first time and if there were an easy way to report your multiple posts I would.
> But from now on every time I see you post some useless post just to post your spam link, this is going to be posted in response.

which link the file format one (just the first google result, no spam) or the Outlook for Android (the default signature I'm too lazy to change) one?

(cc @kenmcd )

**Comment by tonsky** [comment]
@mrackwitz I think this should be solved at editor level, kind of how some code editors can make whitespace/tabs visible

**Comment by kenmcd** [comment]
> or the Outlook for Android (the default signature I'm too lazy to change) one?

It's SPAM.
You're posting it.
You're posting SPAM.

**Comment by RubenVerg** [comment]
> > or the Outlook for Android (the default signature I'm too lazy to change) one?
> 
> It's SPAM.
> You're posting it.
> You're posting SPAM.

do you actually want me to change it? just ask nicely

**Comment by RubenVerg** [comment]
![image](https://user-images.githubusercontent.com/52597868/106916741-cdcb0b00-6707-11eb-9903-9d126e11a4a3.png)
happy now?

**Comment by RubenVerg** [comment]
> But from now on every time I see you post some useless post just to post your spam link, this is going to be posted in response.
That's the definition of spam, you don't fight (made up) spam with other spam

**Comment by tonsky** [comment]
Thanks @RubenVerg that’s much better

**Comment by RubenVerg** [comment]
Wow, I never thought this could be an issue.
