### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by mlajtos** [tonsky/FiraCode#366]
Hello

Do you plan to publish FiraCode on NPM?

Thank you.

**Comment by tonsky** [comment]
Why? What do you expect it to contain?

**Comment by mlajtos** [comment]
If somebody would want to use FiraCode in their project, they could do just ```npm install fira-code``` and they are ready to go. It is very convenient way to use 3rd party modules.

**Comment by tonsky** [comment]
Yes but Fira Code is a font. You should link it from CDN, I guess, not put in into your project? I’m just not familiar with JS ecosystem.

Or may you could suggest how the package should be structured, what it should contain and how do you see people would you “use it in a project” after installing it? I assume you’re asking about woff versions anyways, right?

**Comment by looperhacks** [comment]
There are [other](https://www.npmjs.com/package/npm-font-open-sans) [fonts](https://www.npmjs.com/package/lato-font) available on NPM, too. This is for use cases where you don't want to link to a cdn (an offline app built with Electron or internal solutions behind a firewall come to mind).
