### ISSUE TITLE
CTAN (LaTeX) package?

### ISSUE THREAD

**Issue by ZaneHannanAU** [tonsky/FiraCode#368]
https://www.ctan.org/pkg/fira

If possible, type1/etc?

Thanks :-)

**Comment by tonsky** [comment]
Please elaborate. I have no idea what that is and how to upload and how should the package be structured

**Comment by ZaneHannanAU** [comment]
I don't know either, but https://en.wikibooks.org/wiki/LaTeX/Fonts#Useful_websites can probably be of use.

it'd probably get in the way, sorry; thank you though, ligatures are always awesome!
