### ISSUE TITLE
FiraCode (.otf) is too bold

### ISSUE THREAD

**Issue by aolko** [tonsky/FiraCode#370]
(Only .otfs were installed)
Hardly readable
![image](https://cloud.githubusercontent.com/assets/581458/23200718/f6e815de-f8e6-11e6-9307-07ce911cdeeb.png)

**Comment by tonsky** [comment]
You can stop using Bold font in your syntax theme then

**Comment by joaoevangelista** [comment]
.otf plays really weird on IntelliJ products (maybe because of Oracle's Java, Azul & Open JDK has better rendering) use .ttf instead for better rendering

**Comment by xasx** [comment]
Just in case someone stumbles upon this - I am encountering this on Windows - here's what I did to finally get the same font weight as I do under Linux.

Just extract all the `ttf` files to your installation's `jre/fonts` subdirectory, e.g. `C:\Program Files\JetBrains\IntelliJ IDEA 181.3494.3\jre64\lib\fonts`
