### ISSUE TITLE
->> strange behavior

### ISSUE THREAD

**Issue by josser** [tonsky/FiraCode#372]
Hi! 
Here is example of code which for some reason not always shown correct in VSCode. 
not sure, it's issue in vs code or in font. 

```javascript
const query = [`with tag_offers as (
      offer->>'price_list', offer->>'price_net', offer->>'price_used', offer->>'price_rent', offer->>'price_buyback',`];
```

Here is screenshot of wrong rendering: 

![2017-02-24 19 15 31](https://cloud.githubusercontent.com/assets/103639/23313284/c7690e18-fac5-11e6-903c-098d656cd512.png)

Thank you!

**Comment by josser** [comment]
It's Visual Studio Code and Fira version 1.204

**Comment by wopian** [comment]
Can't replicate this on 1.9.1 with 1.204 on Windows 10

![](https://i.imgur.com/IfSqhfR.png)

**Comment by josser** [comment]
@wopian Maybe mac-specific.

**Comment by tonsky** [comment]
What syntax is that file in?

пт, 24 февр. 2017 г., 20:28 Dmitry Chirkin <notifications@github.com>:

**Comment by josser** [comment]
@tonsky it's javascript
It worth to say that there are two parsers for js in vscode, regular which is included in vscode and additional 'babel-based'. Most users like babel-version but I'm using regular.

**Comment by tonsky** [comment]
Reproduced it. Looks like there’s some hard break at column 100. Works in any syntax:

<img width="1032" alt="screen shot 2017-02-27 at 11 33 43" src="https://cloud.githubusercontent.com/assets/285292/23354114/bb47ea2e-fce0-11e6-9a8e-f312da411a2e.png">

Please report that to VS Code team. Clearly it’s not a Fira Code issue
