### ISSUE TITLE
Looks weird on VSCode

### ISSUE THREAD

**Issue by vedhavyas** [tonsky/FiraCode#373]
Did add the following settings after installing the fonts and adding required settings
<img width="707" alt="screen shot 2017-02-25 at 8 45 16 pm" src="https://cloud.githubusercontent.com/assets/7549475/23332174/61ac4726-fb9b-11e6-814e-df8eb6f780f2.png">

**Comment by tonsky** [comment]
This is not Fira Code, this is some fallback font I suspect. Can you screenshot your settings?

**Comment by wilomgfx** [comment]
Indeed this is not Fira Code.

**Comment by vedhavyas** [comment]
sorry guys, uninstalled VSCode and went back to my old editor.

But only settings I had were these

```
"editor.fontFamily": "Fira Code",
"editor.fontSize": 14,
"editor.fontLigatures": true```

**Comment by wopian** [comment]
Only way those settings would show the fallback font is if Fira Code (Regular?) wasn't installed as a system font.

**Comment by aviraldg** [comment]
@vedhavyas I have Fira Code working on VSCode with the following (weirdly double quoted) config:

    "editor.fontFamily": "'Fira Code', 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'",

**Comment by wavebeem** [comment]
Yeah, you have to quote it inside the config because it's a CSS font configuration, and that's how they work :\

**Comment by vedhavyas** [comment]
@aviraldg yup, it worked

**Comment by PJUllrich** [comment]
Just so you won't feel as dumb as I do right now: Make sure to **actually install** the font on your system ;-) How-to can be found [here](https://github.com/tonsky/FiraCode/wiki#installing-font)

**Comment by bigr339** [comment]
Sorry guys to comment on a closed isssue but Fira Code my VSCode editor looks bold. I have tried all the font weights, it just doesn't change its weight. The only way to make it work for me is to uninstall the bold and regular font. Other editors show it correctly.

![image](https://user-images.githubusercontent.com/51700848/92197646-088bf700-ee7b-11ea-87e5-cb249d2542cd.png)
