### ISSUE TITLE
Draw pipe symbol as vertical line on italic version

### ISSUE THREAD

**Issue by Strate** [tonsky/FiraCode#375]
Thank you for this font!
I suggest you to draw pipe character (`|`) always vertical, even in italic mode. Because it could be mixed up with slash (`/`) characted. Many programming fonts do this, for example Hasklig. Also look to screens.

FiraCode:
![image](https://cloud.githubusercontent.com/assets/392644/23608820/33acb558-027c-11e7-8288-ccdb68b5bcd6.png)

Hasklig:
![image](https://cloud.githubusercontent.com/assets/392644/23608826/37f44dce-027c-11e7-8aff-c97a77201c22.png)

**Comment by sainaen** [comment]
Hasklig is based on [Source Code Pro], that has an italic variant, while Fira Code's base ([Fira Mono]) does not. So it's actually your editor/text rendering engine that makes pipe symbol appear slanted.

I'm afraid it's not something that could be easily fixed within font itself.

[Source Code Pro]: http://adobe-fonts.github.io/source-code-pro/
[Fira Mono]: https://mozilla.github.io/Fira/

**Comment by tonsky** [comment]
@sainaen is right, I just want to add that this sort of thing _should_ be fixed in the font, by providing the proper italics. Unfortunately, it’s like developing the whole new font: it’s out of my reach.
