### ISSUE TITLE
Indices do not have the same size

### ISSUE THREAD

**Issue by zsoerenm** [tonsky/FiraCode#376]
In atom indices do not have the same size. Here is a picture:

![indices](https://cloud.githubusercontent.com/assets/375486/23622901/aeb47e4c-02a0-11e7-89f2-082112794e1e.png)

Shouldn't those have the same size?

**Comment by tonsky** [comment]
How do you get those indices?

**Comment by zsoerenm** [comment]
There are several subscripts like:
U+01D62, U+01D63, U+01D64, U+01D65, U+02090, U+02091, U+02092, U+02093, U+02095....

**Comment by tonsky** [comment]
Yeah, those are not in the font. 2080-2089 are though, if it helps (0-9 subscript)
