### ISSUE TITLE
Markdown heading underlines

### ISSUE THREAD

**Issue by fson** [tonsky/FiraCode#378]
It would be cool if FiraCode had ligatures for the underline style headings in Markdown. Currently they get rendered as multiple `===`/`---`. A continuous line would look nicer, especially when the length isn't a multiple of 2 or 3 (see screenshot below). Could we add some longer ligatures to cover the cases where `=` or `-` is repeated 4-80 times?

<img width="419" src="https://cloud.githubusercontent.com/assets/497214/23657120/44150926-0345-11e7-8115-9464eb45eb82.png">

**Comment by tonsky** [comment]
Latest version of Fira Code solves this by turning off ligatures for sequences of 4+ symbols. You might consider updating

**Comment by fson** [comment]
Ah, thanks, that helps. Looks much better with the latest version.
