### ISSUE TITLE
No TTF in 0.6

### ISSUE THREAD

**Issue by henrikhodne** [tonsky/FiraCode#38]
It looks like there's no longer a TTF file as of 0.6, was this intentional?

**Comment by tonsky** [comment]
Yes, I don’t know if it was useful or not. Windows support OTF, Mac too, so I was wondering of what use TTF is?

**Comment by henrikhodne** [comment]
I was mainly asking because I maintain [otf-fira-code](https://aur.archlinux.org/packages/otf-fira-code/) and [ttf-fira-code](https://aur.archlinux.org/packages/ttf-fira-code/) on AUR and I was updating them with 0.6. If TTF is no longer available, I'll just mark the ttf package as no longer being updated and point people to the otf version instead.

**Comment by tonsky** [comment]
I’m thinking to add a pipeline to build web fonts, and ttf might be there
as well. I’ll see what tools are there for it, haven’t looked into it yet.
For 0.6 there’s no ttf
