### ISSUE TITLE
Remove/change ~= ?

### ISSUE THREAD

**Issue by daurnimator** [tonsky/FiraCode#381]
FiraCode renders the `~=` ligature like asymptotically equal to (U+2243: ≃).

In lua and MATLAB, `~=` is not equal to.
Historical context: I believe `~` was chosen as it is the closest ascii character to the not sign (U+00AC: ¬)

**Comment by roryokane** [comment]
I wondered if this change would affect the Perl/Ruby regex match operator, but [that’s `=~`](https://ruby-doc.org/core-2.4.1/String.html#method-i-3D-7E), not `~=`.

**Comment by dhouck** [comment]
Is there any language where `~=` means ≃?

**Comment by mcepl** [comment]
Which way the duplicate goes? Is this duplicate of #293 or vice versa?

**Comment by dhouck** [comment]
No; that’s about `=~` and this is about `~=`.

**Comment by MadcapJake** [comment]
Also Dylan, Smalltalk, and BCPL use `~=` to mean `not equal to`. Perl 6 uses [`=~=`](https://docs.perl6.org/language/operators.html#infix_=~=) for the approx-equal operator.

**Comment by daurnimator** [comment]
*bump*, should someone send a PR removing it?

**Comment by tonsky** [comment]
I’ll remove it from the next release

**Comment by Lixquid** [comment]
Now that stylistic sets are supported, it'd be great to see this as a stylistic set!
