### ISSUE TITLE
Distinguish single-equals and double-equals more

### ISSUE THREAD

**Issue by dhouck** [tonsky/FiraCode#383]
In many languages, there is a huge difference between `x = y` and `x == y`. However, they are not as easy to distinguish in Fira Code (or most other ligature programming fonts) as I think they should be.

The only programming font I’ve seen that does this well is Pragmata Pro, which puts a little notch on the `==` ligature so that even though it’s a single symbol it’s still easy to tell it’s a double equal sign.

Alternately, of course, this can be a variant once you have those.

EDIT: This can also be done like with `--`, where they get closer but don’t actually connect.

**Comment by dhouck** [comment]
In the issues closed as duplicates of this you say that once variants exist you’ll do this. Well, Fira Code now has stylistic sets; can you please do this one?

**Comment by tonsky** [comment]
Yes, this is a good opportunity and one of the most requested features. Thanks!
