### ISSUE TITLE
Some unicode characters are too small in comparsion with alphanumerics

### ISSUE THREAD

**Issue by msva** [tonsky/FiraCode#385]
Hi there! I've found, that some characters are too small, so it is almost impossible to distinguish what's that character with fontsize about 8-9-10 pt, but general font usage (alphanumeric, ligatures) is fine at this size.
Here is a screenshot of font preview app, where I marked "small ranges" with red line.
![](https://i.imgur.com/Q4B3snj.png)

All of that characters are so small at 9pt (at least with my DPI and in my terminal), that it is impossible to distinguish between them in their group.

P.S.: Also, I'm not sure, if will be right move, but how about removing "emojis" (☺,☹) from the FiraCode, to  give user a way to configure some emoji font to handle all of them? :)

**Comment by msva** [comment]
By the way, subs, sup and fractions is also unreadable at 9pt.

**Comment by tonsky** [comment]
Fira Code is best on bigger font sizes. If you want to use font in such small size and see subs/sups/fractions clearly, consider using another font (I doubt such a font exists, though)

**Comment by msva** [comment]
Not that "subs/sups/fractions" was a main issue.
Main issue is about `>`,`<`, `<=` (unicode, not ligature), `>=` and so on. All of them is much smaller than another symbols in the font.
And, say, `>=` and `<=` has "normal sized" ligature versions, so why don't use same glyphs for unicode versions?

And also, some characters, like `☠`, `☺`,`♀`,`♂`,`♫` (and so on) is both very small (in comparsion with another symbols), and some of them is present in "emoji" fonts, but will not fallback there, because it is present in FiraCode.

Excluding that issue, firacode is pretty useful in terminal. But because of that issue it looks like this:

![](https://i.imgur.com/kc3PXQo.png)

And yes, setting font size to 13, makes them visible, but also makes terminal to fit 1.5x less lines of text/code (and becomes not that larger than text-mode 80x24 tty).

By the way, PragmataPro have all that symbols same size as another symbols in the font, if any.

**Comment by triclops200** [comment]
I'm having the same issue. It's not sups or subs, but rather things like ∅ are way too small on fira. unless the size is greater than 10, which takes up too line length. Look at the screenshot he provided: I'm having the same issue.

**Comment by dhouck** [comment]
The issue with `≤` and `≥` being the same size as Unicode as in the ligature is that the ligature version *must* take up two columns while the one-character version *must* take up only one column. Perhaps they could be made bigger anyway, but not by as much as the ligatures.

**Comment by triclops200** [comment]
Doing a bit of research it's related to Fira Code not getting a good fallback font: it was using a really crappy bitmap fallback.

**Comment by refaelsh** [comment]
> Doing a bit of research it's related to Fira Code not getting a good fallback font: it was using a really crappy bitmap fallback.

I have the same issue. I've been googling for days now. And your comment seems interesting. Can you please explain what do you mean `fallback font`?
