### ISSUE TITLE
LaTeX instructions

### ISSUE THREAD

**Issue by chris-martin** [tonsky/FiraCode#388]
I've set Fira Code as the monospace font in a document build with LuaLaTeX, but I haven't figured out how to enable the ligatures. A "LaTeX instructions" page on the wiki would be great if anyone gets this working.

**Comment by wopian** [comment]
This is whats needed for XeLaTeX and should also work for LuaLaTeX:

```latex
\usepackage{fontspec}
\setmonofont[Ligatures=TeX]{FIRACODE-RETINA_0.TTF}
```

**Comment by chris-martin** [comment]
`Ligatures=TeX` doesn't seem to have any effect.

[This approach](https://tex.stackexchange.com/questions/294362/use-fira-code-font-with-ligatures-in-code-listings) seems to work a little:

    \setmonofont[Contextuals={Alternate}]{Fira Code}

But doesn't seem to affect verbatim or lstlisting environments.

**Comment by beojan** [comment]
That approach seems to work, but I can't get the hyphen ones working in `\texttt`.

**Comment by RuixiZhang42** [comment]
I hope I understand this post correctly:

> We wish to use the (awesome-looking) ligatures in Fira Code to *list source code* in our LaTeX documents.

To properly use Fira Code in LaTeX, the compile engine must be XeLaTeX or LuaLaTeX of course. But more are needed to enable ligatures in the `verbatim` and `lstlisting` environments.

## Activate the `calt` feature

Many ligatures of Fira Code are under the OpenType feature `calt`, so we first need to activate this feature as @chris-martin mentioned:

    \setmonofont{Fira Code}[Contextuals=Alternate]

## The `verbatim` environment: Empty the “no ligature” token list

The LaTeX kernel purposely suppresses *almost all* ligatures in the `verbatim` environment. The tokens involved in forming ligatures are specified in the list `\verbatim@nolig@list`. So we should redefine this list to be empty:

    % !TeX program = XeLaTeX/LuaLaTeX
    \documentclass{article}
    \usepackage{fontspec}
    \setmonofont{Fira Code}[Contextuals=Alternate]
    \makeatletter
    \renewcommand*\verbatim@nolig@list{}
    \makeatother
    \begin{document}
    \begin{verbatim}
    a!==b<-c~@d>->e Voilà!
    \end{verbatim}
    \end{document}

Output:

![fira](https://user-images.githubusercontent.com/39968857/50038576-995bd880-ffef-11e8-8273-ce51f316e128.png)

## The `lstlisting` environment: Define `literate` personal style

*The following solution is still a work in progress. It does NOT behave well with syntax coloring/highlighting.*

The `listings` package has a *very* different way handling its input. We need to specify all ligatures *in the correct order* with the `literate` key-value option, literally (pun intended). But setting up ligatures this way could prevent the `listings` syntax coloring and highlighting mechanism.

I would be more than happy to offer my contributions :). But I need guidance on *how* I can contribute.

Output first:

![firalst](https://user-images.githubusercontent.com/39968857/50038753-839be280-fff2-11e8-935c-6cada36f266e.png)

MWE:

    % !TeX program = XeLaTeX/LuaLaTeX
    \documentclass{article}
    \usepackage{fontspec}
    \setmonofont{Fira Code}[Contextuals=Alternate] % v1.206
    
    \usepackage{listings}
    \lstdefinestyle{MyStyle}{
      basicstyle=\ttfamily,
      literate=
        {www}{{www}}3
        {**}{{**}}2
        {***}{{***}}3
        {**/}{{**/}}3
        {*>}{{*>}}2
        {*/}{{*/}}2
        {\\\\}{{\textbackslash\textbackslash}}2
        {\\\\\\}{{\textbackslash\textbackslash\textbackslash}}3
        {\{-}{{\{-}}2
        {[]}{{[]}}2
        {::}{{::}}2
        {:::}{{:::}}3
        {:=}{{:=}}2
        {!!}{{!!}}2
        {!!!}{{!!!}}3
        {!=}{{!=}}2
        {!==}{{!==}}3
        {-\}}{{-\}}}2
        {--}{{--}}2
        {---}{{---}}3
        {-->}{{-->}}3
        {->}{{->}}2
        {->>}{{->>}}3
        {-<}{{-<}}2
        {-<<}{{-<<}}3
        {-~}{{-\textasciitilde}}2
        {\#\{}{{\#\{}}2
        {\#[}{{\#[}}2
        {\#\#}{{\#\#}}2
        {\#\#\#}{{\#\#\#}}3
        {\#\#\#\#}{{\#\#\#\#}}4
        {\#(}{{\#(}}2
        {\#?}{{\#?}}2
        {\#\_}{{\#\_}}2
        {\#\_(}{{\#\_(}}3
        {.-}{{.-}}2
        {.=}{{.=}}2
        {..}{{..}}2
        {..<}{{..<}}3
        {...}{{...}}3
        {?=}{{?=}}2
        {??}{{??}}2
        {???}{{???}}3
        {;;}{{;;}}2
        {;;;}{{;;;}}3
        {/*}{{/*}}2
        {/**}{{/**}}3
        {/=}{{/=}}2
        {/==}{{/==}}3
        {/>}{{/>}}2
        {//}{{//}}2
        {///}{{///}}3
        {\&\&}{{\&\&}}2
        {\&\&\&}{{\&\&\&}}3
        {||}{{||}}2
        {|||}{{|||}}3
        {||=}{{||=}}3
        {|=}{{|=}}2
        {|>}{{|>}}2
        {^=}{{\textasciicircum=}}2
        {\$>}{{\$>}}2
        {++}{{++}}2
        {+>}{{+>}}2
        {=:=}{{=:=}}3
        {==}{{==}}2
        {===}{{===}}3
        {==>}{{==>}}3
        {=>}{{=>}}2
        {=>>}{{=>>}}3
        {=<}{{=<}}2
        {=<<}{{=<<}}3
        {=~}{{=\textasciitilde}}2
        {=/=}{{=/=}}3
        {>-}{{>-}}2
        {>=}{{>=}}2
        {>=>}{{>=>}}3
        {>>}{{>>}}2
        {>>-}{{>>-}}3
        {>>=}{{>>=}}3
        {>>>}{{>>>}}3
        {<*}{{<*}}2
        {<*>}{{<*>}}3
        {<|}{{<|}}2
        {<|>}{{<|>}}3
        {<\$}{{<\$}}2
        {<\$>}{{<\$>}}3
        { ->> >->
    <=< <<= <==    <=> => ==> =>> >=>
        >>= >>- >- <~> -< -<< =<<
            <~~ <~     ~> ~~>
       {. {| [| <:     :> |] |} .}
                <$ <$> $>
                <+ <+> +>
                <* <*> *>
          </  />
          ;; :: ::: !! ?? %% && 
         || .. ... ..< .? ?. ?:
          -- --- ++ +++ ** ***
              ~= ~- -~ ~@
              ^= ?= /= /==
            -| _|_ |- |= ||=
            #! #= ## ### ####
          #{ #[ ]# #( #? #_ #_(
    \end{lstlisting}
    \end{document}

**Comment by j-f1** [comment]
Do you want to add that to [the wiki](https://github.com/tonsky/FiraCode/wiki) @RuixiZhang42?

**Comment by RuixiZhang42** [comment]
@j-f1 Yes, of course. But my code had some errors/typos. I am working on it.

**Comment by RuixiZhang42** [comment]
I am pleased to announce that my new package [`lstfiracode`](https://ctan.org/pkg/lstfiracode) v0.1a is now available on major TeX distributions: TeX Live and MiKTeX.

The wiki on LaTeX instructions is also available now: https://github.com/tonsky/FiraCode/wiki/LaTeX-instructions

Note that v0.1b is already in development in my repo (documentation corrections, implementation improvements, etc).

**Comment by ZanderBrown** [comment]
This actually works with `minted` as well (`minted` is implemented with `verbatim`)

**Comment by RuixiZhang42** [comment]
@ZanderBrown Good to know! I’ve never worked with `minted` and cannot test with `lstfiracode` right now. AFAICT, `\renewcommand*\verbatim@nolig@list{}` suffices for `verbatim`, but `\ActivateVerbatimLigatures` from `lstfiracode` is slightly more sophisticated.

The minimum edit to the [LaTeX Wiki](https://github.com/tonsky/FiraCode/wiki/LaTeX-instructions) is perhaps to change the title *Activate ligatures in `verbatim`* to *Activate ligatures in `verbatim` and `minted`*, and then provide a short example each with `lstfiracode` and without `lstfiracode`. Please feel free to do so if the two methods really work.

**Comment by yves-chevallier** [comment]
I don't know in 2020, but it seems the Ligatures are always enable, and I don't know how to disable them... 

I just have this and it enables the ligatures: `\setmonofont{Fira Code}`

**Comment by RuixiZhang42** [comment]
@yves-chevallier It depends on the font itself (almost).

When you say `\setmonofont{Fira Code}`, the default [`fontspec` configuration file](https://github.com/wspr/fontspec/blob/master/fontspec.cfg) adds options `WordSpace={1,0,0}`, `HyphenChar=None`, `PunctuationSpace=WordSpace` to the `\ttfamily`. So, whether ligatures and/or contextual alternates are turned on or turned off is really a property of the font itself.

If you want to load Fira Code *without* ligatures, you can try `\setmonofont{Fira Code}[Ligatures=CommonOff]`. But then, what’s the point of using Fira Code in the first place? Just use `\setmonofont{Fira Mono}` if you don’t want ligatures at all.

**Comment by wopian** [comment]
> But then, what’s the point of using Fira Code in the first place? Just use `\setmonofont{Fira Mono}` if you don’t want ligatures at all.

It's a reasonable use case. Fira Code has a _lot_ of single-character symbols and letters not present in Fira Mono.

**Comment by yves-chevallier** [comment]
Well, it is not really working... 

```latex
\documentclass{article}
\usepackage{fontspec}
\usepackage{listings}
\usepackage{lstfiracode}

\setmonofont{Fira Code}[Ligatures=CommonOff]

\lstset{
    language=C,
    style=FiraCodeStyle,
    basicstyle=\ttfamily
}

\begin{document}

\begin{lstlisting}
a == b === c ==> d
\end{lstlisting}

{\ttfamily a == b === c ==> d}

\end{document}

\end{document}
```

I still get the ligatures on:

![image](https://user-images.githubusercontent.com/52489316/89740707-6c451f00-da8b-11ea-9923-6f6d1bd17856.png)


Anyway, I am mostly using Fira Code because I don't know how to use Fira Mono on LaTeX neither how to install it.

**Comment by yves-chevallier** [comment]
My mistake... Removing `style=FiraCodeStyle,` did the trick!

**Comment by RuixiZhang42** [comment]
@wopian 

> Fira Code has a _lot_ of single-character symbols and letters not present in Fira Mono.

Good point!

---

@yves-chevallier 

> My mistake... Removing `style=FiraCodeStyle,` did the trick!

You didn’t mention that you wanted to disable ligatures in the `lstlisting` environment, and I misinterpreted that you wanted to do this in regular `\ttfamily` declaration.
- For disabling ligatures in `lstlisting`, you’re right about removing `style=FiraCodeStyle` (this means you are *not* applying the predefined ligature style in the package).
- For disabling ligatures in `\verb|...|` or the `verbatim` environment, you need to declare `\DeactivateVerbatimLigatures`, otherwise you still get some ligatures here and there. See `lstfiracode` doc *3.1&nbsp;Package option and user commands*.
- **For disabling ligatures in all `\ttfamily`-related places**, you can do `\setmonofont{Fira Code}[Contextuals=AlternateOff]` when you load the font. **This method also works with the former two scenarios**.

```latex
\documentclass{article}
\usepackage{fontspec}
\setmonofont{Fira Code}[Contextuals=AlternateOff]
\begin{document}
{\ttfamily a == b === c ==> d}
\end{document}
```
