### ISSUE TITLE
Ligature Request: ---

### ISSUE THREAD

**Issue by DWSR** [tonsky/FiraCode#390]
I'd love to see a ligature for --- (for example, at the top of YML files).

Just a solid line

**Comment by dhouck** [comment]
It already is a ligature; it makes the dashes closer together. Making it a solid line would make it harder to distinguish the exact length, and making `--` also a solid line would be really bad for code where that means “decrement”. I already have an issue out, #383, to make `==` *not* be just two solid lines.

**Comment by DWSR** [comment]
Ah, it's a fairly subtle change so I didn't notice it. I would love to see `---` as a solid bar still, leaving the `--` ligature alone.
