### ISSUE TITLE
additional font weights

### ISSUE THREAD

**Issue by dch** [tonsky/FiraCode#391]
[upstream fira](http://mozilla.github.io/Fira/) now has `hair` and `ultralight` weights. I'd love to see these available in FiraCode too - it's much easier on the eyes.

**Comment by sainaen** [comment]
Upstream for Fira Code is Fira Mono, not Fira Sans. And that one unfortunately doesn't even have the italics/slanted variant.

**Comment by tonsky** [comment]
You can’t use it for coding, can you? You need at least 40px font size for it to be readable. Why then?

**Comment by dch** [comment]
@saienen you're right - my bad. linking the upstream https://github.com/mozilla/Fira/issues/12 for others looking in future.
@tonsky absolutely it works for coding - depending on your screen size, OS, and preferred editor. Anyway until there's an upstream, this is moot.

Thanks heaps for FiraCode its a beautiful piece of work.
