### ISSUE TITLE
 ligatures not working 

### ISSUE THREAD

**Issue by MandarSant** [tonsky/FiraCode#393]
ligatures not working in newest version of brackets 1.9

![cvxcvxvxvxcv](https://cloud.githubusercontent.com/assets/20091634/24319912/f622ef9e-114f-11e7-9dd4-9eba74107daf.png)

preference file

![capture](https://cloud.githubusercontent.com/assets/20091634/24319926/533d5fac-1150-11e7-8055-2a5a150fa576.JPG)

**Comment by tonsky** [comment]
That’s no Fira Code on your screenshots. Maybe try `"fonts.fontFamily": "'Fira Code'"` (case and quotes)

<img width="799" alt="screen shot 2017-03-25 at 19 38 49" src="https://cloud.githubusercontent.com/assets/285292/24324189/c8bbc48e-1192-11e7-9aed-15d455d862b9.png">

**Comment by MandarSant** [comment]
@tonsky  still not working

![capture](https://cloud.githubusercontent.com/assets/20091634/24328361/42bb66e6-1205-11e7-915f-d5cb0318511a.JPG)

**Comment by MandarSant** [comment]
@tonsky  thanks it worked problem was due to case sensitivity .

**Comment by MandarSant** [comment]
@tonsky  still not working 


![capture](https://cloud.githubusercontent.com/assets/20091634/24328393/313d7782-1206-11e7-9dc4-9029b083b26e.JPG)

**Comment by tonsky** [comment]
Do you have it installed? Can you use it in other apps (e.g. Atom?)

**Comment by MandarSant** [comment]
@tonsky yes its working in other editors but not in **# Brackets**

# **vscode:-**
![vscode](https://cloud.githubusercontent.com/assets/20091634/24331572/67a847e0-1254-11e7-9129-0834edf764c2.JPG)

# **Atom:-**

![capture](https://cloud.githubusercontent.com/assets/20091634/24331589/d6d4e060-1254-11e7-962a-5d5ae410d544.JPG)

# **Notepad:-**

![capture](https://cloud.githubusercontent.com/assets/20091634/24331608/3d7fd0ea-1255-11e7-83f1-fa2f9602a58e.JPG)

**Comment by tonsky** [comment]
Hmm, there seems to be a bug in Brackets. When I change font line, it applies the changes and shows everything in Fira Code. But when I restart Brackets it starts in default font. Please open an issue in their bugtracker

![default](https://cloud.githubusercontent.com/assets/285292/24346961/58bb9ee0-12df-11e7-8044-760356cc2db7.png)
