### ISSUE TITLE
Ellipsis renders incorrectly depending on its position in line

### ISSUE THREAD

**Issue by sirIrishman** [tonsky/FiraCode#397]
Hi,

I'm using the latest FiraCode 1.204 in the VS Code 1.10.2 and in the Visual Studio 2015/2017 (Windows 10). I've noticed that sometimes an ellipsis renders as `. ..` or `.. .` depending on it's position in line. I've reproduced the issue in both editors:
- VS Code: 
![Imgur](http://i.imgur.com/FjCEanH.png)
- VS 2015: 
![Imgur](http://i.imgur.com/4V2fMG7.png)

**Comment by tonsky** [comment]
See https://github.com/tonsky/FiraCode/issues/372
Please report it to VS issue tracker, clearly it’s their problem :)
Thanks!

**Comment by dhouck** [comment]
This was already reported in Microsoft/vscode#21476 and seems to have been fixed in Microsoft/vscode@2355666 two days ago, which is after the most recent release. I wouldn’t re-open an issue there unless you still observe it on their latest code.

**Comment by sirIrishman** [comment]
I see. Thank you!
