### ISSUE TITLE
phpstorm 2017.1 corrupted text

### ISSUE THREAD

**Issue by OzoneRPC** [tonsky/FiraCode#398]
![image](https://cloud.githubusercontent.com/assets/11834194/24447873/0f902a22-147b-11e7-8f35-ac409e1888c0.png)

The problem in subpixel anti-aliasing. Greyscale - works. Font ligatures enabled. Once this font works correctly, but after system reboot his broke again.

Installed ttf font.

Phpstorm 2017.1
Windows 10. 
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)

**Comment by tonsky** [comment]
See this https://youtrack.jetbrains.com/issue/IDEA-159901
If it doesn’t help, open an issue in JetBrains tracker. This is IDE problem, not Fira Code.
