### ISSUE TITLE
Add Bold and Italic variations to Retina subset

### ISSUE THREAD

**Issue by babichss** [tonsky/FiraCode#399]

**Comment by tonsky** [comment]
What do you mean, Bold to Retina. And there’s no italics, sorry

**Comment by babichss** [comment]
@tonsky for regular FiraCode font there are plenty of font variations like Italic, Black, Medium. Retina is just one of these variations, so it lacks at least Bold and Italic variations which are present in regular font.

Is it possible to move Retina font to separate font family and extend it with Bold and Italic like regular one is?

**Comment by tonsky** [comment]
There is just Light, Regular, Retina, Medium, Bold weights in Fira Code. No italics or Black weight. Retina is just another weight, not a separate font family. It’s slightly heavier than Regular, because Regular is too thin on high-dpi screens.

**Comment by dhouck** [comment]
As for italic, that is not provided by this font (I hope someday, I assume after Fira Mono gets it at the earliest); it is emulated by the font rendering library in your OS. What program and OS are you using, where you can only choose italic for one of the weights?

**Comment by DivineDominion** [comment]
@babichss maybe the original designer will pick up the italic Mono font now that Mozilla has abandoned the project: https://github.com/carrois/Fira/issues/11
