### ISSUE TITLE
Add Ruby hash rocket operator =>

### ISSUE THREAD

**Issue by schrockwell** [tonsky/FiraCode#40]
There is one notable Ruby operator missing: the "hash rocket" `=>`. It could look like `==>`, but a little shorter.

**Comment by tonsky** [comment]
There’s `=>` since version 0.1

**Comment by schrockwell** [comment]
Sorry, I did not realize that because it's not in the preview image. Maybe it could be added?

**Comment by tonsky** [comment]
It’s now on the preview. Thanks!
