### ISSUE TITLE
Add cloud9.io to supported IDEs

### ISSUE THREAD

**Issue by Thefirsh** [tonsky/FiraCode#400]
I just had to install the font and tell cloud9 to use it, then it worked right away (after restarting the browser).

[https://i.snag.gy/i9t1Lz.jpg](https://i.snag.gy/i9t1Lz.jpg)

**Comment by acz13** [comment]
BTW Cloud9 uses it's own editor (**A**jax.org **C**loud9 **E**ditor) which can be embedded in other places
