### ISSUE TITLE
Support for unicode symbols

### ISSUE THREAD

**Issue by iwex** [tonsky/FiraCode#404]
Hello. 

![image](https://cloud.githubusercontent.com/assets/4510068/24653693/9262bb4a-193f-11e7-83ef-a38cbb349c6c.png)
 This is lambda :)

**Comment by tonsky** [comment]
Maybe something is wrong with your editor. Lambda (0x03BB) is definitely in the font. What editor/OS do you use?

**Comment by iwex** [comment]
@tonsky Ubuntu 16.04/PHPStorm

**Comment by tonsky** [comment]
Works for me in Idea 2017.2 / OS X
- Can you see lambda if you set another font?
- Try reporting to Intellij issue tracker
