### ISSUE TITLE
Generic Swift func !=<T> doesn't render correctly

### ISSUE THREAD

**Issue by BenLeggiero** [tonsky/FiraCode#406]
Function declaration should render as `func ≠<T : RawRepre...`, but renders as `func !≤T : RawRepre...`

<img width="169" alt="screen shot 2017-04-06 at 13 26 00" src="https://cloud.githubusercontent.com/assets/10189808/24767403/d5c87846-1acc-11e7-945c-61aa9ae1f835.png">

**Comment by dhouck** [comment]
I think this is another reason to get rid of `=<` as per #355 

(and did you mean it should render as `func ≠<T`? That’s what it would render as without the `=<` ligature or if `!=` had priority, but that’s not what you listed.

**Comment by BenLeggiero** [comment]
@dhouck You got it!
And I have no opinion on `=<` becoming `≤` or not; I imagine someone somewhere uses that but I've never seen it used.

Also, I think I worded it right... I was trying to match my screenshot, so I included the `RawReprese` :P

**Comment by dhouck** [comment]
The symbol you used is U+2244, NOT ASYMPTOTICALLY EQUAL TO. I would expect `!=` to ligature to U+2260 NOT EQUAL TO, which is what it should be doing.

(The difference is the top bar of the equal sign; is it straight or a tilde?)

**Comment by BenLeggiero** [comment]
Oops, that was just a typo. I originally meant to type `≠<T`, not `≄<T`. Sorry about the confusion :)

**Comment by pakLebah** [comment]
Yes… the most common usage for `≤` is `<=` not `=<`.
