### ISSUE TITLE
Odd/Wrong ligature for `{.`

### ISSUE THREAD

**Issue by bobrocke** [tonsky/FiraCode#409]
Using the character combination `{.` (curly bracket period) results in an odd/wrong/inappropriate ligature that looks like this:

![ligature](https://cloud.githubusercontent.com/assets/2962426/25005100/809c01cc-2025-11e7-9daf-d760864995cb.jpeg)

**Comment by MilesManners** [comment]
`{.` and `.}` are Nim pragmas #279 
They were removed in [1.202](https://github.com/tonsky/FiraCode/releases/tag/1.202)
They were returned in [1.204](https://github.com/tonsky/FiraCode/releases/tag/1.204)

**Comment by tonsky** [comment]
Will be removed again in 1.206. See #635
