### ISSUE TITLE
Add an export of the font source in an open format like UFO

### ISSUE THREAD

**Issue by dhouck** [tonsky/FiraCode#411]
I do not know much about font editing and do not have a copy of Glyphs 2. There are some small changes I have wanted to try to make in my own copy (and maybe even open a PR for if I can make the changes at a high enough quality, although that might not be possible if the conversion between glyphs file format and UFO isn’t reversible), and currently that’s not possible.

As I said, I don’t know much about font editing, so an export might not actually help me that much, but it’s certainly more likely I can make the changes if I have the font in a format I can use than if I don’t.

**Comment by tonsky** [comment]
In my experience, opening OTF directly works much better than UFO. Have you tried that?

**Comment by dhouck** [comment]
I have, but I wasn’t able to do much with it. I wasn’t sure how much of that was not knowing what I’m doing and how much was not using a file format designed for editing. If you say that OTF editing works better in general I’ll assume it’s just the first one.

**Comment by tonsky** [comment]
I’m attaching UFOs, check if those work better for you

[Fira Code UFOs.zip](https://github.com/tonsky/FiraCode/files/927854/Fira.Code.UFOs.zip)

**Comment by dhouck** [comment]
Thank you. I’ll take a look at them at some point and see if they work any better, although I won’t be able to check until this weekend at the earliest.
