### ISSUE TITLE
Bug with iTerm2 rendering <!-- 

### ISSUE THREAD

**Issue by benjamin-rood** [tonsky/FiraCode#425]
![Example](https://thumbs.gfycat.com/FelineJoyousAegeancat-size_restricted.gif)

Hey, just letting you know that inside iTerm2 `<!---` has a weird bug where pressing space results in `<!-- ` becoming `<-i `.

In the gif above you can see if you type `<!--a_` for example you get `<-ia_` (where `_` is to represent the space character).

**Comment by tonsky** [comment]
You should try reporting this to iTerm bugtracker
