### ISSUE TITLE
Powerline characters too small

### ISSUE THREAD

**Issue by soleera** [tonsky/FiraCode#426]
Powerline characters are consistently too small across multiple terminal emulators and programs, including qterminal and konsole. I've compared FiraCode to Hack, which has more appropriately sized powerline symbols.

**FiraCode in Konsole:**
![fira](https://cloud.githubusercontent.com/assets/25336289/26525669/169aa7e0-43b3-11e7-92ee-622663e32905.jpg)

**Hack in Konsole:**
![hack](https://cloud.githubusercontent.com/assets/25336289/26525673/1b24db82-43b3-11e7-9bda-e0eeab3333cb.jpg)

**Comparison in Fontforge:**
![compare](https://cloud.githubusercontent.com/assets/25336289/26525674/1f63a32c-43b3-11e7-8fec-ed04dd3f6111.jpg)

**Comment by tonsky** [comment]
It’s not possible to fix it once and for all. If you fix it for one terminal/OS it’ll break it for something else. See discussion here https://github.com/tonsky/FiraCode/issues/44#issuecomment-187305276
