### ISSUE TITLE
'−' U+2212 MINUS SIGN is less wide than U+2D '-' HYPHEN MINUS

### ISSUE THREAD

**Issue by samcv** [tonsky/FiraCode#428]
The minus sign should be wider than the hyphen minus sign.

Currently the hyphen minus is actually slightly wider than the minus. And at normal size it becomes almost impossible to tell the two apart when programming.

**Comment by tonsky** [comment]
This is a tricky to deal with in a monospaced font. How do you deal with it in other fonts? In what possible context is it important to tell one from another?

**Comment by samcv** [comment]
Well, almost every font the minus sign is slightly wider than the hyphen minus sign. I can see that the M-dash is quite wide with Fira Code, so there is room to make it slightly wider.

Here is a picture of different fonts:

![screenshot_20170531_023325](https://cloud.githubusercontent.com/assets/20145557/26625640/988ab900-45a9-11e7-933c-beb142a1cea1.png)

Fira is the only one where the hyphen minus and the minus sign are shown almost identical. As you can see Fira *does* show every other dash distinctly except the minus sign, where it appears identical to the hyphen minus.

As to why it is important to tell one from another, It is useful because they are not the same codepoint, and as a programming font it is important to be able to easily distinguish different characters. Programming languages that use the minus sign is not usable in all the locations a hyphen minus is.

I would look at how Noto Mono renders it. Which I think is in the proper location vertically for this symbol, which achieves showing it is not the same as an n-dash.

If you took the n-dash glyph and moved it upward that would have the correct and expected visual appearance for the minus sign.

**Comment by dhouck** [comment]
This should probably be reported to the base mozilla/Fira repository.

**Comment by tonsky** [comment]
I’ve actually already enlargened minus sign, along with plus sign. They are bigger then in Fira Mono. Still too close to dash, though. One option is to make dash smaller. But then most of the code that uses dashes will look worse. Given that 99,9% people use dashes and never use Unicode minuses, I doubt it’s worth it.

**Comment by dhouck** [comment]
Dashes are different than the hyphen-minus character, the minus character, or the hyphen character U+2010 `‐`. In general a lot of people use “dash” or “hyphen” to mean any of them, especially on the command line where almost everybody specifies options with “dash”, in a context like this it is useful to keep them separate.

**Comment by samcv** [comment]
I think Fira code should just use the n-dash glyph but move it just a tad higher and use that for the minus sign. Then it would be perfect. And yes what I said is slightly wrong in that the *minus sign* is actually less wide in `Fira Code` than the *hyphen minus*, which is the opposite it should be. Whereas in Fira Mono the *hyphen minus* is the same size as the *minus sign*.

**Comment by samcv** [comment]
@tonsky why was this closed?

**Comment by tonsky** [comment]
I don’t plan to do anything to address this
