### ISSUE TITLE
Visual studio 2015 doesn't render glyph for ->

### ISSUE THREAD

**Issue by galkk** [tonsky/FiraCode#43]

**Comment by galkk** [comment]
At least in F# editor

**Comment by tonsky** [comment]
What about other glyphs? What about other editors? It might be a tokenization issue. See https://github.com/tonsky/FiraCode/issues/32

**Comment by galkk** [comment]
Yeah, the issue that you've mentioned is the same as I had.
Other glyphs were working.

**Comment by tonsky** [comment]
Ok, closing this because I can’t do a thing about it :(
