### ISSUE TITLE
'r' has serifs.

### ISSUE THREAD

**Issue by Jhonyrod** [tonsky/FiraCode#430]
I can see that the base font has serifs on the 'r' character, however this is not in line with the rest of the font.

**Comment by jdreesen** [comment]
The 'i' has serifs, too.

Anyway, I think this should be reported on the [Fira repository](https://github.com/mozilla/Fira) itself because it's the way how they look in Fira Mono and I doubt @tonsky is going to change this.

**Comment by tonsky** [comment]
They changed it because `r` used to look like `i` at small sizes. I didn’t liked it at first too but got used to it. Discussion: https://github.com/mozilla/Fira/issues/49

**Comment by Jhonyrod** [comment]
Before I posted the issue I looked into forking and/or modifying the font myself, sadly Glyphs is only available on Mac.
Is there any other alternative?

**Comment by tonsky** [comment]
> Is there any other alternative?

Robofont, FontForge can both open and modify OTF versions I believe. Not Glyphs masters, but good enough for quick-and-dirty hack
