### ISSUE TITLE
cmd.exe support

### ISSUE THREAD

**Issue by j2ghz** [tonsky/FiraCode#431]
Is windows command line supported? It's not in the list https://github.com/tonsky/FiraCode#terminal-support on either side. I was able to change the font but the ligatures don't work.

**Comment by tonsky** [comment]
Well the font itself would work anywhere. Supported list is for ligatures only. I’ll add Fira Code to “Not supported” column, thanks!

**Comment by ackvf** [comment]
Fira Code works in new Windows Terminal https://github.com/microsoft/terminal

![image](https://user-images.githubusercontent.com/2313018/73473194-9c995b80-438c-11ea-8401-727dc50b311e.png)


However, why does `Fira Code Light` not work with ligatures?

**Comment by tonsky** [comment]
> However, why does Fira Code Light not work with ligatures?

@ackvf can you expand on it in a separate issue?
