### ISSUE TITLE
inclusive range operator `..=`

### ISSUE THREAD

**Issue by CAD97** [tonsky/FiraCode#433]
[It's being added to Rust.](https://github.com/rust-lang/rust/issues/28237)

Proposal: add a `..=` ligature.
This should parallel the existing `..` ligature and exclusive range `..<` ligature.

The Rust language team admits that `..=` isn't a pretty sequence of characters. And currently, because Fira Code displays `..=` as `..` `=`, it pops out as even more wonky.

<sub>Honestly I didn't mind `...` much at all this font does a good job making `..` and `...` distinct</sub>
<sub>This is why my language will have mathematical open/closed range declarations /grumble</sub>

**Comment by timvisee** [comment]
An addition for this would be brilliant.

I'd be interested in a ligature like `.=`, with an additional dot in front of course. Although it might be inconsistent with the `..` ligature.

**Comment by pakLebah** [comment]
+1

I also want this ligature as well.
