### ISSUE TITLE
Inconsistent period between words

### ISSUE THREAD

**Issue by wayneashleyberry** [tonsky/FiraCode#434]
I've been doing some templating using Hugo and noticed some weird behaviour with periods between words.

`{{.Foo}}` renders as `{{·Foo}}` which is nice.

`{{.Foo.}}` renders as `{{·Foo·}}` as expected.

Then it changes if you add another words, so `{{.Foo.Bar}}` renders as `{{·Foo.bar}}` which feels wrong.

Here's a screenshot using VSCode.

![screen shot 2017-06-08 at 4 08 56 pm](https://user-images.githubusercontent.com/727262/26932766-ce693738-4c64-11e7-8fe3-5c670afff3d5.png)

**Comment by dhouck** [comment]
As far as I know, characters changing based on context is local; it can’t look at a lot of surroundings.

Assuming I’m right about that, there’s no way to tell the difference between `{{.foo.bar}}` and `document.foo.bar` from the point of view of the dot between an `o` and a `b`.

**Comment by tonsky** [comment]
yeah @dhouck is right. No way to alter that inner dot. Only way to deal with that is to disable `{.` `.}` ligatures altogether
