### ISSUE TITLE
ligature request "_(" and "__("

### ISSUE THREAD

**Issue by avshyz** [tonsky/FiraCode#436]
Coding in python, you'd often see function names ending with a dunder (__) or an underscore (_). After seeing the beautiful "#_(" ligature from the clojure sample I was thinking a similar, yet simpler, ligature could make my python scripts look exponentially badass-er.

What do you think?

**Comment by tonsky** [comment]
Sure. Sounds good, I’ll look if that stands visually too

**Comment by avshyz** [comment]
Great, keep us posted :-)

**Comment by dhouck** [comment]
I don’t think I’d like this. The underscore or double underscore is part of the function name, not the parenthesis; connecting it to the parenthesis makes the visual tokenization wrong. It’s `__init__` `(`, not `__init` `__(`.

**Comment by tonsky** [comment]
I actually agree with @dhouck. I haven’t thought about that in the context. Maybe it’s best to leave as it is

**Comment by avshyz** [comment]
@dhouck good point, I stand corrected.
