### ISSUE TITLE
Longer pipe |

### ISSUE THREAD

**Issue by Crissov** [tonsky/FiraCode#438]
In Markdown pipe tables, it would be useful if the Vertical Line character U+007C `|` extended all the way from the top to the bottom of the character box in order to have continuous column separators (unless an editor adds additional leading between lines). This *might* be useful behavior for its use as an _or_ operator in many programming languages and regular expressions as well. For Markdown, this alternate glyph could be restricted to places where `|` is preceded and succeeded either by whitespace, another pipe, a hyphen-minus `-` or a colon `:`.

PS: I'm not sure whether or where forward and backward slashes `/` and `\` should also be longer.

**Comment by dhouck** [comment]
I’m not sure that making | look like the box-drawing character │ (U+2502) would help in most cases, but I’m not sure how much it would hurt either.

**Comment by tonsky** [comment]
You can’t win this battle and I’ve tried to fight it for powerline already. You can’t rely on any font metrics to be the actual line-height. Different terminals and different editors use different values. Although you can fine-tune your font for something specific, it’ll mean it’ll break in many others.

Another issue is, of course, that you can’t reliably identify markdown source and pipe is already heavily-used in programming languages.

With that said, unfortunately I don’t think there’s a way to make it work in Fira Code.

**Comment by Crissov** [comment]
`cv##` then?

**Comment by tonsky** [comment]
@Crissov how do you mean?

**Comment by Crissov** [comment]
I mean an alternative glyph that could be accessed from a _character variant_ OT feature.

**Comment by tonsky** [comment]
How would you use that?

**Comment by Crissov** [comment]
Not in most editors, but e.g. in code samples on the web. CSS has properties for that.
