### ISSUE TITLE
Markdown fenced code blocks (tilde ~~~ or backtick ```)

### ISSUE THREAD

**Issue by Crissov** [tonsky/FiraCode#439]
Fenced code blocks in Commonmark, the standardized Markdown flavor, are preceded by a line that starts with three or more consecutive tildes `~~~` or backticks ```` ``` ````. While there is a ligature for a double tilde `~~` already, longer runs appear as separate characters. Also note that Mediawiki uses 3 or 4 consecutive tildes to insert a signature. Multiple backticks are always separated and I'm not really sure how they could be improved.

**Comment by tonsky** [comment]
Yeah I used to have triple tilda (see https://github.com/tonsky/FiraCode/blob/master/CHANGELOG.md). Starting with three, it becomes really hard to tell how many tildas are there. I believe that was the reason I got rid of it.
