### ISSUE TITLE
Powerline support in 0.6

### ISSUE THREAD

**Issue by msva** [tonsky/FiraCode#44]
Hi there!
You've announced Powerline support in the 0.6 version, but it seems, they've added a bit buggy:

Also, I've noticed a little offset to the right side for ± symbol (and bottom part of + seems like cutted), and, somewhy, coloured circles (at the right side, which, actually, using same symbol in all three cases) has some positional offsets (yellow one looks like a bit divided at the left side, and red one looks smaller than yellow). I think, that is somehow related to not-really-monospaced nature of the ligatures for that symbols in the font. Maybe, due to some bug during powerline-patching, or so. How do you think?

![firacode_artefacts](https://cloud.githubusercontent.com/assets/268102/9699235/5389833e-53f4-11e5-96eb-c62777d759b4.png)

**Comment by tonsky** [comment]
± and circles should come from the font, I didn’t draw them. BTW what terminal are you using? Mine ± looks like this:

<img width="69" alt="screen shot 2015-09-06 at 00 07 26" src="https://cloud.githubusercontent.com/assets/285292/9700631/2da5f7ae-5423-11e5-8e7e-399f67ad6b86.png">

**Comment by msva** [comment]
I'm using Konsole (at least, it is Konsole on the screenshot).

**Comment by alfredbez** [comment]
Same issue here (last character - arrow):
![bildschirmfoto vom 2016-02-01 15-47-54](https://cloud.githubusercontent.com/assets/1001186/12720461/563925cc-c8fb-11e5-9ad3-d0cd87940509.png)

```
$ konsole --version
Qt: 5.4.2
KDE Frameworks: 5.15.0
Konsole: 15.08.0
$ uname -r
4.2.0-25-generic
$ lsb_release -a                                                                                                      !10024
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

**Comment by tonsky** [comment]
Looks like there’s no easy way to fix it. Powerline is a hack, so expect it to behave like a hack.

Related: https://github.com/powerline/fonts/issues/31

> There's just too many factors (different ways of calculating font metrics, different operating systems, different antialiasing technologies, different fonts) to reliably patch a font for every single combination of these factors. You can patch it manually in fontforge or ignore the issue until a fix is found

**Comment by msva** [comment]
Powerline itself, as idea, yes, a hacky thing.
Although, they recommends to do a pretty working thing: take the symbols, open FontForge (or any tool you like) and add/fix symbols there.

So, TL;DR: Powerline can brake things when autopatched, but it is possible to just add few symbols of specified look directly into the font (like it done in PragmataPro). Although, yes, it will take few hours or so to do that (in case of FontForge and ttf fonts. And, talking on Fira* — I, actually, have no idea how to edit it under GNU.

**Comment by tonsky** [comment]
The problem is with triangles only. Fonts in general are not well suited
for pseudographics. E.g. height of the glyph and height of the line are two
different things which are not necessary the same. Problem of powerline is
that they expect that triangle height is equal to line height. You just can
gurantee that. Different systems, terminals, font sizes and font rendering
settings will lead to different line heights/symbols heights proportions.
If I was in charge of powerline I would drop triangles, everything else is
pretty doable and does not create any troubles. Or, if you’re willing to do
so, you can fine tune their height for your specific OS/terminal/font size.
