### ISSUE TITLE
Font ligatures not working in vs code

### ISSUE THREAD

**Issue by MandarSant** [tonsky/FiraCode#440]
check this issue -> [#28598](https://github.com/Microsoft/vscode/issues/28598)
 working in other (Atom,Notepade) but not vscode

**Comment by tonsky** [comment]
Please go through [troubleshooting](https://github.com/tonsky/FiraCode/wiki#troubleshooting) section and see if you enabled everything that needs to be enabled

**Comment by MAChitgarha** [comment]
As described [here](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions), you should go to Visual Studio Code settings (the JSON settings file), and add the following line to its end (or edit existing if exists):

```json
"editor.fontLigatures": true
```

**Comment by andrey-furman** [comment]
Enable font ligatures in settings.json with this line:
"editor.fontLigatures": true
And remove accessibility support by:
  "editor.accessibilitySupport": "off",

**Comment by Valerii-Synenko** [comment]
> As described [here](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions), you should go to Visual Studio Code settings (the JSON settings file), and add the following line to its end (or edit existing if exists):
> 
> ```json
> "editor.fontLigatures": true
> ```

I have the same settings but it does not work. (ubuntu)

**Comment by mfocko** [comment]
I'm running the Insider version of VSCode and they're working fine

**Comment by mr-infinitehawk** [comment]
> Enable font ligatures in settings.json with this line:
> "editor.fontLigatures": true
> And remove accessibility support by:
> "editor.accessibilitySupport": "off",

thx dude

**Comment by garte** [comment]
> > As described [here](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions), you should go to Visual Studio Code settings (the JSON settings file), and add the following line to its end (or edit existing if exists):
> > ```json
> > "editor.fontLigatures": true
> > ```
> 
> I have the same settings but it does not works. (ubuntu)

Same here, running VS Code 1.56.2 on Ubuntu 20.04 with the following settings.json:

```
{
    "workbench.colorTheme": "Gruvbox Light Soft",
    "editor.fontFamily": "'Fira Code'",
    "editor.fontLigatures": true,
    "editor.accessibilitySupport": "off",
    "editor.minimap.enabled": false,
    "elixirLS.dialyzerEnabled": false,
    "files.autoSave": "onFocusChange",
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "workbench.editor.wrapTabs": true,
    "liveshare.presence": false
}
```
Ligatures working in PHPStorm.

**Comment by garte** [comment]
> > As described [here](https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions), you should go to Visual Studio Code settings (the JSON settings file), and add the following line to its end (or edit existing if exists):
> > ```json
> > "editor.fontLigatures": true
> > ```
> 
> I have the same settings but it does not works. (ubuntu)

Manually deleting and re-installing the current version (5.x) fixed the issue for me.

**Comment by AndrewLaganaro** [comment]
> Enable font ligatures in settings.json with this line: "editor.fontLigatures": true And remove accessibility support by: "editor.accessibilitySupport": "off",

My sir, you're a hero. Fira Code didn't work for like one year+ and I didn't know why, just learned to live with it since the font in general is pleasing to see.

Removing this accessibility config and restarting vscode made it work on every file for the first time for me since I saw the font. Thanks!
