### ISSUE TITLE
Small hiccup in Emacs support, add to documentation

### ISSUE THREAD

**Issue by nicholas-miklaucic** [tonsky/FiraCode#441]
Hopefully this is the right way to do this: I'm not sure.

The Emacs support is in a good place right now, working almost perfectly for me when I use the second half of the current documentation that was inspired by [this issue #211 ](https://github.com/tonsky/FiraCode/issues/211). However, there was one problem I had that I managed to figure out finally, and because it's a simple fix that would otherwise impede the ability to set it up I think it should be included in the documentation. It's a pretty noob error, but it stumped me for a while.

I was having a problem where, only in some programming modes (`python-mode` in particular, but `c-mode` and a lot of other ones didn't work either, but `emacs-lisp-mode` was fine), `==` would not display properly as the codepoint `\ue13c`, as it should using the Fira Code Symbol workaround. It would just display a blank character instead of the double equals sign.

The fix for this is to include the two lines 

    (set-language-environment "UTF-8")
    (set-default-coding-systems 'utf-8)

in the init file. If you do that, everything works fine. 

For the record, I'm using Emacs 25.2.1 on Fedora 25. Thanks to everyone who made this font work, it's been super nice to have this working so well.

**Comment by tonsky** [comment]
I don’t have Emacs and has no idea what current setup is. Do you suggest that we just add these two lines to [this wiki page](https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs)?

**Comment by nicholas-miklaucic** [comment]
Yeah, something like this at the bottom:

On some systems, `==` will appear incorrectly as a blank space unless you add the following lines to your init file:

    (set-language-environment "UTF-8")
    (set-default-coding-systems 'utf-8)

**Comment by tonsky** [comment]
Done. Thanks!
