### ISSUE TITLE
PowerShell(ISE): ligatures not working with dashes

### ISSUE THREAD

**Issue by TheIncorrigible1** [tonsky/FiraCode#444]
The -> ->> etc ligatures (including multi-dashes together: ---) do not form into ligatures in the PowerShell CLI or the ISE.  I have not found this to be the case with the rest of the ligatures.

**Comment by j-f1** [comment]
Already tracked in #259.

**Comment by tonsky** [comment]
I’m going to close this as a duplicate. Nothing I can do about it
