### ISSUE TITLE
Ligatures not working in Delphi IDE

### ISSUE THREAD

**Issue by Serraniel** [tonsky/FiraCode#445]
Hi, I tried installing FiraCode into my Delphi IDE (Delphi 2010 and Delphi XE 10) but ligatures seem not to work if you just change the font to FiraCode, while other tools instantly worked fine. 
Are their any known issues with Delphi or known workarounds to get ligatures working in Delphi IDE? I was unable to either find it in support or unsupported IDE list and also didn´t find any issues regarding Delphi so far.

**Comment by tonsky** [comment]
It’s probably just not supported. I’ll add it to the list

**Comment by Basti-Fantasti** [comment]
Tested today on latest Delphi Version (11.3) - still not supported

**Comment by Serraniel** [comment]
> Tested today on latest Delphi Version (11.3) - still not supported

Yes. It's also reported to Embarcadero since Delphi 10.2 and still open: https://quality.embarcadero.com/browse/RSP-21325
