### ISSUE TITLE
Feature request for linear arrow "-o"

### ISSUE THREAD

**Issue by varosi** [tonsky/FiraCode#451]
It'll be great if linear arrow could be represented with a symbol. 
Inspired from https://ghc.haskell.org/trac/ghc/wiki/LinearTypes

**Comment by j-f1** [comment]
What about the `-o` flag in command-line programs?

**Comment by tonsky** [comment]
I’m afraid it’ll be impossible to distinct it from normal usage inside words (big-o for example :)

**Comment by varosi** [comment]
It could check if there is a space before, for example " -o".

**Comment by tonsky** [comment]
Then it wouldn’t work in Haskell :)

**Comment by varosi** [comment]
It'll because most Haskell code written well have spaces between types, like:
```haskell
myfunc :: A -> B -o C
```

**Comment by tonsky** [comment]
Well I don’t want to support only Haskell code written well. I want to either solve the problem for all situations or, it that’s not possible, at least not increase the confusion by only applying ligature to some situations but not to others

**Comment by varosi** [comment]
Okay, thanks!

**Comment by tonsky** [comment]
Thanks for the contribution! I’m holding on a bunch of great ideas, many of which are mine, that cannot be implemented cleanly, unfortunately

**Comment by varosi** [comment]
Font is great! So keep going

**Comment by aantron** [comment]
[Dex](https://github.com/google-research/dex-lang/) uses a `--o` lolly. For example, see [here](https://google-research.github.io/dex-lang/prelude.html). Perhaps this is a candidate for a ligature?

**Comment by j-f1** [comment]
Same thing for `--output`
