### ISSUE TITLE
Single arrow inside " " doesn't render out

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [tonsky/FiraCode#452]
<img width="672" alt="screen shot 2017-07-19 at 10 24 48" src="https://user-images.githubusercontent.com/14138559/28388285-7fda420e-6cd2-11e7-9af6-8c31f8c2c0ff.png">

If there are tokens inside quotes, the arrow doesn't render

**Comment by j-f1** [comment]
This looks like an issue with your editor’s syntax highlighting, rather than an issue with Fira Code. Which editor is this?

**Comment by FrencisAlreadyInUse** [comment]
hi sir, I use Atom

**Comment by j-f1** [comment]
I would report this issue to the syntax theme and/or PHP grammar repositories, since I am unable to reproduce it with the Atom Light theme and the built-in PHP grammar.

**Comment by FrencisAlreadyInUse** [comment]
For some reason atom thinks it's nog PHP but HACK. My PC is of right now, but i'll test this tomorrow with the PHP syntax

**Comment by FrencisAlreadyInUse** [comment]
@j-f1 Hi :) Just tested it on the PHP-syntax and I have the same issue as the provided screenshot

**Comment by tonsky** [comment]
Please open an issue in PHP/Hack syntax package for Atom. This is a parsing issue https://github.com/tonsky/FiraCode/wiki#some-ligatures-work-while-some-dont
