### ISSUE TITLE
Redefined hexadecimal x doesn't fire if hex values have _ underscores

### ISSUE THREAD

**Issue by shanselman** [tonsky/FiraCode#454]
Interesting one here. C#7 added the ability for a _ to be an ignored spacer for 0xABCDEF hex literals, so you can now 0xAB_CD_EF for readability.

Result:
![image](https://user-images.githubusercontent.com/2892/28439819-76e3dc42-6d58-11e7-9555-d4a208458668.png)
 
Expected (I removed the _'s myself)
![image](https://user-images.githubusercontent.com/2892/28439800-5e415db8-6d58-11e7-95b2-6812aeaa2769.png)

Thanks for all your work! Big fan.

**Comment by j-f1** [comment]
That looks like a syntax highlighting issue that can’t be fixed in the font.

**Comment by shanselman** [comment]
Ah, my bad. That's interesting. I will file with VS Code then.
