### ISSUE TITLE
Update Linux install instructions

### ISSUE THREAD

**Issue by sainaen** [tonsky/FiraCode#456]
Continuing discussion from the #4.

Summary: let's update Linux installation instruction to describe how install Fira Code from standard package repositories, at least for latest Debian, Ubuntu and, possibly, Arch.

> [@sainaen:](https://github.com/tonsky/FiraCode/issues/4#issuecomment-317075542)
> @tonsky
> Now that both Stretch and Zesty are released, would it be ok if I add instructions for them to the _“Installing font”_ section? It's trivial, just `apt install fonts-firacode`, but you have to remember to enable `contrib`/`universe` repositories first; plus currently wiki seem to suggest that there's only manual installation for Linux users which isn't true anymore.
> 
> <details>
> <summary>Something like this:</summary>
> 
> ```diff
> -Linux: 
> +Linux — Debian 9 / Ubuntu 17.04 or newer:
> +
> +- make sure that `contrib` (for Debian) or `universe` (Ubuntu) repository is enabled (enabling `non-free` / `multiverse` isn't required)
> +- install `fonts-firacode` package, with either `apt` (`sudo apt install fonts-firacode`) or other package manager
> +
> +Linux — Manual installation:
> +
>  - in the ttf folder, double-click each font file, click “Install font”
> ```
> </details>

<br>

> [@dhouck:](https://github.com/tonsky/FiraCode/issues/4#issuecomment-317082089)
> Would you also want to add AUR instructions for Arch? It might be better to have a list of distributions where it’s available through usual package management channels which could look like:
>
>  * Debian (in the `contrib` repository)
>  * Ubuntu (in the `universe` repository)
>  * Arch (available [in the AUR](https://aur.archlinux.org/packages/otf-fira-code-git/))

**Comment by sainaen** [comment]
@dhouck 
Sure, if Nikita's ok with this. But now I think it may be more future-proof (in case other distributions add this font to their repos) just reorder the lines in “Installing font” and put details on already existing “Linux Instructions“ page
<details>
<summary>Like so:</summary>

```diff
-Linux: 
-- in the ttf folder, double-click each font file, click “Install font”
-- if double-clicking doesn’t work, see [this page](https://github.com/tonsky/FiraCode/wiki/Linux-instructions)
+Linux:
+
+- use package available for your distribution, see [this page](https://github.com/tonsky/FiraCode/wiki/Linux-instructions)
+- or manually double-click each font file in the ttf folder and click “Install font”; if this doesn't work see [Manual install on Linux](https://github.com/tonsky/FiraCode/wiki/Linux-instructions#Manual-install-on-Linux)
```
</details>
<br>

By the way, I don't know much about AUR. Am I right to think it's something like Ubuntu's PPAs? It seems to have outdated version right now. Should we add _“not official, may be outdated”_ notice for it or can I (you?) ping some one to get it up to date?

UPD: Oh, found these two: [`otf-fira-code`](https://aur.archlinux.org/packages/otf-fira-code/) and [`ttf-fira-code`](https://aur.archlinux.org/packages/ttf-fira-code/). They have current version and, if I understand correctly, are more popular. Should we use these instead?

**Comment by dhouck** [comment]
Yes, those links would be better, but the one I linked isn’t as out-of-date as it seems. It is a `-git` package, which means that it automatically grabs the latest version from GitHub and installs that.

Arch packages are built from `PKGBUILD`s. The AUR is a collection of `PKGBUILD`s you can build yourself (with tools in the main repositories), for packages which the Arch maintainers don’t want to provide themselves. They’re in general easier to work with than installing software from source yourself, even though they aren’t as easy to work with as any official or unofficial repositories. I’m not familiar with Ubuntu PPAs, but as if I understand correctly, from the user’s point of view, you enable the PPA and then it acts like any other repository. Arch supports unofficial repositories too, and they are easier to use, but many Arch users would prefer the AUR (for example, if they don’t trust whoever maintains the unofficial repository and would rather be able to inspect the package themselves) and I don’t know any community-maintained repositories with these packages.

**Comment by sainaen** [comment]
Thanks, @dhouck, for the explanation! In the end I decided [to just list](https://github.com/tonsky/FiraCode/wiki/Linux-instructions#arch-linux) all three packages assuming Arch users are savvy enough to know the difference between them. :)

I just went ahead and updated the wiki. 🎉 Feel free to edit, if missed something or you'd like to improve the wording.

Closing the issue.

**Comment by tonsky** [comment]
Thanks for taking initiative and writing this up, @sainaen!

**Comment by sainaen** [comment]
No problem! Thank you for your work on the font. 💚
