### ISSUE TITLE
Ligatures work in latest release of Eclipse

### ISSUE THREAD

**Issue by twwwt** [tonsky/FiraCode#458]
The table in which (un-)supported editors are listed mentions Eclipse as unsupported on OS X (and Windows). I can confirm that ligatures work in Eclipse Oxygen (4.7.0), at least using OS X 10.12.5. Note that I did not had to tweak anything other than selecting Fira Code as the font.

<img width="256" alt="sbi_-_ccc-war-helvetia-tools_src_main_resources_print_ass_ppl_docdef_xml_-_eclipse" src="https://user-images.githubusercontent.com/143208/28491109-c15fe5a2-6eea-11e7-8eb7-58e477798c5b.png">

<img width="456" alt="sbi_-_atlas-core_src_main_java_ch_sbi_atlas_promos_symbol_symbol_java_-_eclipse" src="https://user-images.githubusercontent.com/143208/28491128-3856c932-6eeb-11e7-91b3-5d37e546d397.png">

You might want to update the documentation.

**Comment by tonsky** [comment]
thanks!

**Comment by MartyBeGood** [comment]
SOME Ligatures also work on Windows. WWW, ***, .., .., Equality signs work.
Greater/smaller than, Arrows, XML Tag stuff etc. doesn't.
Incomplete lists, I haven't had the time to test all the ligatures

**Comment by tonsky** [comment]
Interesting, I’ll have to check. Thanks @MartyBeGood. It might mean they got them working but syntax breaks some sequences

**Comment by Martin1887** [comment]
@tonsky, in the last release of Eclipse (Photon) all ligatures seem to work (for instance, now `<=` ligature works).

However, they fail randomly (at least in Windows). For example:

1. Open eclipse. They don't work.
2. Close eclipse.
3. Open eclipse. They don't work.
4. Close eclipse.
5. Open eclipse. Now they work.
6. Close eclipse.
7. Again they don't work.

It's an annoying bug, but I have not found any opened issue.


Regards.

**Comment by egold555** [comment]
None of ligatures work for me in eclipse oxygen 4.7.3a (Most up to date version when writing this)

**Comment by Martin1887** [comment]
The latest version is Eclipse Photon (4.8), released on June. However, it is not in Fedora (and the most distros) repositories yet, but you can download from the official web page: https://www.eclipse.org/downloads/packages/ (I have tested it on Windows and works as described).
