### ISSUE TITLE
Fira Code not working OSX 10.12.5 Atom 1.18

### ISSUE THREAD

**Issue by leon-yum** [tonsky/FiraCode#460]
Installed the ttf fonts via Font Bank and Brew

<img width="322" alt="screen shot 2017-07-22 at 2 06 55 pm" src="https://user-images.githubusercontent.com/30158970/28494005-3581104a-6ee7-11e7-8f93-61a6d4ab05b7.png">
 

<img width="492" alt="screen shot 2017-07-22 at 2 06 59 pm" src="https://user-images.githubusercontent.com/30158970/28494008-387316a4-6ee7-11e7-92d3-16623d0a49f7.png">

**Comment by tonsky** [comment]
I see long `==`, it’s a ligature and it’s working
If you expected to see `==>` as a single character, the problem is probably in your syntax highlighter. Open an issue in their repo. This is quite common, see https://github.com/tonsky/FiraCode/wiki#some-ligatures-work-while-some-dont
