### ISSUE TITLE
Selecting FiraCode in OS Terminal.app selects Helvetica

### ISSUE THREAD

**Issue by shoeffner** [tonsky/FiraCode#464]
Until yesterday I was using FiraCode installed via `brew cask` just fine. Today I checked out some other (system only) fonts by selected one after the other. When I decided I wanted to stay with FiraCode and selected it, the font changed to Helvetica automatically (even though FiraCode stays selected!):

![](https://user-images.githubusercontent.com/1836815/28664752-b849fce8-72c1-11e7-8a50-0a1899b932c5.png)

I tried:
* Uninstall + Reinstall using brew cask
* Uninstall + Reinstall manually
* Restarting between uninstalling and reinstalling
* Restarting with FiraCode selected while it was installed using either of the two methods above.
* Enabling/Disabling `Antialias text`
* Selecting different typefaces

When I close the "Profiles" window (see screenshot above) and reopen it, Helvetica is properly selected instead of FiraCode – however, I am still not able to select FiraCode.

I am using Mac OS 10.12.5, Terminal.app 2.7.2 (388.1).

Do you have any ideas how to fix this?

**Comment by tonsky** [comment]
No idea, sorry. Works fine for me (same setup)

**Comment by shoeffner** [comment]
The simple solution: Deleting the profile and creating a new one with the same settings solved the problem.
