### ISSUE TITLE
New Ligatures: M-Dash

### ISSUE THREAD

**Issue by jacoby** [tonsky/FiraCode#465]
It is common to use -- as mdash; but it doesn't look like an m-dash ("–") but rather like two normal dashes together.

I like infixing protocol into arrows, like scratch --samba--> local, and the arrow looks good and transformed, but the tail still looks like --.

I'm loving FiraCode in most places I use mono fonts.

**Comment by jacoby** [comment]
I honestly had forgotten decrement, which is stupid of me. Fair enough.

**Comment by tonsky** [comment]
Not much I can do because I want decrement to look like two minuses. But it’s a great idea, definetely deserves to be done in more traditional fonts.
