### ISSUE TITLE
Windows Clock: the colon is a box when setting system default font to Fira Code

### ISSUE THREAD

**Issue by taigrr** [tonsky/FiraCode#466]
![image](https://user-images.githubusercontent.com/8261498/28680358-f4a46a28-72aa-11e7-83aa-07797e39e1a7.png)

Tried rebooting; restarting explorer.exe, it errors out. Can provide more details if necessary.

Typing 9:06 into something else has no errors.

**Comment by tonsky** [comment]
Well, I can only suggest to contact windows team somehow :) Or using a font without ligatures
