### ISSUE TITLE
Keeping track of ligature character patterns

### ISSUE THREAD

**Issue by ollicle** [tonsky/FiraCode#467]
Naturally it is a very common issue to request new character combination to form a new ligatures or problems associated with an existing combination. Seems there is room for a tool or reference to help folks check their pet ligature and what past decisions it may conflict with.

Is showcases.txt a complete reference for existing ligatures?

**Comment by tonsky** [comment]
Right now CHANGELOG.md keeps track of ligatures added and ligatures removed, with links to corresponding issues. I agree that more complete track of every combination ever _evaluated_ would be useful as well.

showcases.txt is more or less complete, yes

**Comment by tonsky** [comment]
JFYI I started to collect a list of all ligatures (past, present and proposed) here https://docs.google.com/spreadsheets/d/1T19dtqd5pqzmUX3epbaGwuVvPIiReCwsd_XDfVhTqW0/edit?usp=sharing
