### ISSUE TITLE
Distinguish "<=" and "=<"

### ISSUE THREAD

**Issue by miniBill** [tonsky/FiraCode#468]
I think the ligatures for <= and =< should be different. Otherwise there is not way of telling them apart

**Comment by tonsky** [comment]
AFAIK there’s no language that uses both. I understand that in theory you can type in the wrong thing and wouldn’t be able to see the mistake, but in practice I doubt it ever happens

**Comment by dhouck** [comment]
This is a duplicate of #424 and #305, both of which appear to have overwhelming support based on reaction counts. If we ever get variants I agree it would be useful to have it then, but in the meantime this is more confusing than useful, possibly even for Prolog programmers who seem to be the main group who benefit.

**Comment by miniBill** [comment]
@dhouck I guess I hadn't searched hard enough

**Comment by BenLeggiero** [comment]
@tonsky Swift allows both `<=` and `=<` as valid `operator`s.
