### ISSUE TITLE
Odd/Wrong ligature for `{-`

### ISSUE THREAD

**Issue by andyherbert** [tonsky/FiraCode#474]
Using the character combination {- (curly bracket hyphon) results in an odd/wrong/inappropriate ligature that looks like this:
<img width="262" alt="screen shot 2017-08-16 at 18 20 47" src="https://user-images.githubusercontent.com/25620/29376241-ce2b5874-82af-11e7-960a-ca2cdceac088.png">

**Comment by dhouck** [comment]
Where is this useful? I know where `{{-` (#408) would be useful, but not the single-`{` version.

**Comment by narqo** [comment]
I thought it was fixed with #248 (see https://github.com/tonsky/FiraCode/releases/tag/1.201)

**Comment by tonsky** [comment]
@andyherbert just update to the latest version
