### ISSUE TITLE
Elixir's `.(` shorthand syntax?

### ISSUE THREAD

**Issue by Qwerp-Derp** [tonsky/FiraCode#476]
The `.` in `.(` for anonymous functions isn't really readable - the `.` is often not visible. Maybe make the `.` aligned to the centre?

**Comment by tonsky** [comment]
I learned that it’s generally a bad idea to play with such common combinations of such widely-used characters. Too many conflicts/unexpected situations

**Comment by dhouck** [comment]
I can’t think of when a dot would follow an open parenthesis in any other language, but it would be impossible to google that and I suppose “better safe than sorry” is a reasonable attitude.

I don’t have any problem seeing the `.` when I type that; do you use a particularly small font size?
