### ISSUE TITLE
Update documentation -- ligatures don't work in Notepad++

### ISSUE THREAD

**Issue by alis0nc** [tonsky/FiraCode#48]
Ligatures don't work in Notepad++ (probably nothing else that uses the Scintilla editor component either). The documentation should be updated to reflect this.
![ligaturesnpp](https://cloud.githubusercontent.com/assets/4296609/9764598/ea6b1d8a-56dd-11e5-8da5-a1e2353420f1.png)

**Comment by tonsky** [comment]
thanks!

**Comment by wolfheart** [comment]
Got a work around in the Notepad++ community: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2287

**Comment by nelson6e65** [comment]
I added instrictions to the Wiki:
https://github.com/tonsky/FiraCode/wiki/Notepad-Plus-Plus-instructions
