### ISSUE TITLE
alignment "***"

### ISSUE THREAD

**Issue by BorzdeG** [tonsky/FiraCode#480]
![](https://habrastorage.org/web/77a/b23/c09/77ab23c093a740d8b8cb4f52825f1b96.png)

**Comment by tonsky** [comment]
That’s how `***` looks by design

**Comment by dhouck** [comment]
It’s to make the triple asterisk more visible. The last line is different because it ends in four asterisks instead of three.

**Comment by jonhermansen** [comment]
This looks quite awkward after I type in the third character of my password when unlocking my GPG key...

**Comment by MadcapJake** [comment]
Just add one more `*` and the ligature is gone. Remember that Fira Code is designed for programming languages. There's bound to be some strange accidental ligatures if you use it as your terminal font.

**Comment by oati** [comment]
Could an option to disable this be added to stylistic sets?

**Comment by tonsky** [comment]
@oati please open separate issue, I won’t be able to track it here
