### ISSUE TITLE
Ligature Request: subscript and superscript

### ISSUE THREAD

**Issue by anandogc** [tonsky/FiraCode#482]
Kindly add ligature support for subscript and superscript such as

x**2 , and x^2 .

**Comment by tonsky** [comment]
where does this notation comes from?

**Comment by anandogc** [comment]
in FORTRAN and Python

**Comment by tonsky** [comment]
Right. So `**` isn’t really superscript, it’s rather power of. And `x_2` is, I guess, just a convention someone uses?

Anyways, I’m afraid you can’t have that implemented through ligatures, see this comment https://github.com/tonsky/FiraCode/issues/350#issuecomment-280109652

**Comment by anandogc** [comment]
But since square and cube are most common powers, may be we can have ligatures for square and cube only.

**Comment by tonsky** [comment]
I’m afraid it wouldn’t work in terms of spacing — `**2` takes 3 places, so `²` should take 3 as well. It’s one of Fira Code prinicples — never alter sequences widths.

The other problem is that if it will work for ² and ³ only it’ll be confusing why other powers are not displayed in the same way. It’ll make things inconsistent, and I want to keep them as consistent as possible. I don’t want to increase the mess
