### ISSUE TITLE
The ≤ and ≥ ligature is too tall.

### ISSUE THREAD

**Issue by pakLebah** [tonsky/FiraCode#483]
Please, make the `>` `≥` `<` `≤` size equal and look good. Now the `≤` and `≥` are too tall compare to their counterpart `<` and `>`. Here's a screenshot for the comparison (using XCode 8).

![firacode_ _and_ _is_too_tall](https://user-images.githubusercontent.com/11470932/29869905-15efc2bc-8daf-11e7-8ddf-37b89b7f8f21.png)

Thank you.

**Comment by tonsky** [comment]
if I make `<=` smaller then `<` part of it will be of different size than in pure `<`

**Comment by pakLebah** [comment]
Yes… perhaps I should have said "proportional" instead of "equal". In current size, they already have had different size anyway. To me, they don't look nice. One of them looks bigger/smaller over the other. The main point of using font ligature is to have our code looks good, right?

Well, to be fair, in my opinion, the original Unicode size of those ligatures aren't proportional too.
