### ISSUE TITLE
Spaces bordered by non-space characters on less than 2 sides are half as wide as spaces bordered by non-space characters on both sides

### ISSUE THREAD

**Issue by nickiaconis** [tonsky/FiraCode#487]
## What is the current behavior?

Spaces bordered by non-space characters on less than two sides are half as wide as spaces bordered by non-space characters on both sides.

In the following code/comment snippet, the column of asterisks is expected to align directly beneath the first asterisk of the first line.

```javascript
  /**
   * Binding from the yielded control.skipback component
   *
   * @private
   */
```

Instead, the lower asterisks align midway between the forward slash and the first asterisk.

![screen shot 2017-09-08 at 11 50 36](https://user-images.githubusercontent.com/1056681/30226739-fa84784a-948b-11e7-9b23-1bfaf479f7b4.png)

Adding any non-(white?)space character at the third character position of the second line causes the third space on the second line to expand to full width. This makes the asterisk of the second line align with the second asterisk of the first line as would be expected.

```javascript
  /**
  a * Binding from the yielded control.skipback component
   *
   * @private
   */
```

![screen shot 2017-09-08 at 11 56 41](https://user-images.githubusercontent.com/1056681/30227038-04db7b4e-948d-11e7-990f-538c1e6b34bc.png)

This is also demonstrated by `* B` and `* @` in the first example.

## What is the expected behavior?

All spaces are the same width, regardless of what characters surround them.

**Comment by sainaen** [comment]
Pretty sure this isn't a fault of the font. Here's your example looking ok on my machine (added 'www' to prove that it's Fira Code and ligatures are enabled):

![screenshot from 2017-09-08 22-32-53](https://user-images.githubusercontent.com/2400185/30228281-b05b2c6e-94e5-11e7-9bb2-d8397064f290.png)

What's your editor? Does this happen with syntax highlighting turned off?

**Comment by dhouck** [comment]
There are some slight alignment issues visible in @sainaen’s screenshot because of ligatures, but nowhere near the issues you see. What editor/OS are you using? Do other fonts, or other ligature-based fonts, work correctly?

**Comment by nickiaconis** [comment]
Hi @sainaen & @dhouck, thanks for responding. I'm using vscode 1.16.0 on OS X 12.6. Fira Code is the first/only ligature-based font I've tried, so I have no comparison to report.

Switching to plain text file type (the closest I can get to turning off syntax highlighting AFAIK) doesn't affect the alignment.

**Comment by tonsky** [comment]
Interesting. This is what I get on 1.16 and OS X 10.11.6:

<img width="469" alt="screen shot 2017-09-11 at 19 09 10" src="https://user-images.githubusercontent.com/285292/30284835-bdd8b438-9724-11e7-8d37-918ac84ad134.png">

@nickiaconis can I ask you to paste your full VS Code config? I see you have

```
    "editor.renderWhitespace": "all",
    "editor.renderIndentGuides": true,
```

enabled, but maybe there’re another options that are affecting rendering. I also assume you’re using Java syntax? Any plugins?

**Comment by mlajtos** [comment]
I believe [this issue](https://github.com/Microsoft/monaco-editor/issues/836) is related...
