### ISSUE TITLE
Fails to setup FiraCode in emacs 25.3 on Windows 10

### ISSUE THREAD

**Issue by n179911** [tonsky/FiraCode#490]
Hi, 

I have installed emacs 25.3 on Windows 10 and I run the following steps in setting up FiraCode on windows emacs:
https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs

But I don't see fontLigatures works.
For example, I enter "==>" and "www", I see them have gap between each character.

**Comment by tonsky** [comment]
I’m no expert in Emacs, and that wiki page was community contribution. Maybe try looking into other issues? https://github.com/tonsky/FiraCode/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20emacs

**Comment by rcdilorenzo** [comment]
@n179911 I don't know if you're using spacemacs but I think this is a known issue at this point: https://github.com/syl20bnr/spacemacs/issues/6468
