### ISSUE TITLE
[BUG] Display error in some characters.

### ISSUE THREAD

**Issue by Hypnoes** [tonsky/FiraCode#492]
See the picture, in red box:
![default](https://user-images.githubusercontent.com/13956546/30775345-0edaa690-a0c4-11e7-94a9-61f5dc208760.PNG)

**Comment by tonsky** [comment]
Seems like you’re using 1.203 or earlier. Please upgrade to 1.204 version of the font

**Comment by Hypnoes** [comment]
@tonsky Thanks, It's alright now.
