### ISSUE TITLE
Thin bold variation of font in Intellij-Based IDEs since 2017.1 update

### ISSUE THREAD

**Issue by stylerkov** [tonsky/FiraCode#493]
Hello Tonsky, I like your font and use it in all my Intellij-Based IDEs like PyCharm, Intellij Idea and Webstorm on macOS. But after 2017.1 update in all ides bold words became thinner than it should be. For example I'm attaching two pictures, first now with Fira Mono (same as FiraCode in old IDE versions), second with Fira Code now.
![image](https://user-images.githubusercontent.com/19329525/30806054-cce5bf0e-a226-11e7-9b2f-96af00a73639.png)
![image](https://user-images.githubusercontent.com/19329525/30806090-e8f1be28-a226-11e7-8b59-b0153877ab1f.png)

**Comment by tonsky** [comment]
Seems like Idea can’t find bold version. Please report to IDEA bugtracker
