### ISSUE TITLE
Ligature requests for turnstile |-, double turnstile |=, and bottom _|_

### ISSUE THREAD

**Issue by ace-wu** [tonsky/FiraCode#494]
I'd like to propose following ligatures
- `|-` as [turnstile](https://en.wikipedia.org/wiki/Turnstile_(symbol))
- `|=` as [double turnstile](https://en.wikipedia.org/wiki/Double_turnstile)
- `_|_` as [bottom](https://en.wikipedia.org/wiki/Up_tack)

They are often shown in [math document](https://en.wikipedia.org/wiki/Logical_consequence) and sometimes used in [Haskell](https://en.wikibooks.org/wiki/Haskell/Denotational_semantics#Bottom_and_Partial_Functions)

**Comment by tonsky** [comment]
Well, `|=` is also a “Bitwise OR assignment” in C-like languages. But I guess they won’t mind having that displayed as a ligature. The rest should not conflict with anything, at least at the first glance. Thanks for the suggestion!

**Comment by j-f1** [comment]
`|-` might conflict with bitwise or: `b = a|-1`. `_|_` might conflict with `my_private_var_|_other_private_var`, although these may not actually occur in the wild.

**Comment by FauxFaux** [comment]
Thank the Lord that someone had raised this issue already! I was really suffering with my unreadable endianness swapping code:

![image](https://user-images.githubusercontent.com/328180/30975343-f6f1b650-a469-11e7-88f8-804050a14f06.png)

**Comment by RoyTinker** [comment]
`|=` is already a supported ligature.

**Comment by chharvey** [comment]
if **bottom** is going to have a ligature, [**top**](https://en.wikipedia.org/wiki/Tee_(symbol)) may as well

**Comment by j-f1** [comment]
How would that be represented in code @chharvey?

**Comment by chharvey** [comment]
@j-f1 good question. Although I suppose at this point you could use Unicode and scratch the ligatures altogether.

name | Unicode | LaTeX | ascii | symbol | also known as
--- | --- | --- | --- | --- | ---
right tack | 22a2 | `\vdash` | `\|-` | `⊢` | 'turnstyle'
left tack | 22a3 | `\dashv` | `-\|` | `⊣` |
down tack | 22a4 | `\top` | ? | `⊤` | 'tee', 'top'
up tack | 22a5 | `\bot` | `_\|_` |`⊥` | 'bottom'
