### ISSUE TITLE
RStudio ligature suport for superassignment

### ISSUE THREAD

**Issue by konradedgar** [tonsky/FiraCode#498]
The ligature **`->>`** does not seem to be correctly represented in RStudio #496 for [superassignmemt](https://cran.r-project.org/doc/manuals/R-intro.html#Assignment-within-functions).

<img width="352" alt="screen shot 2017-10-03 at 21 45 57" src="https://user-images.githubusercontent.com/7386756/31148379-725983e0-a884-11e7-9892-420abc2e255c.png">

It should be
```r
w ->> w
```

which I reckon matches:

<img width="55" alt="screen shot 2017-10-03 at 21 52 48" src="https://user-images.githubusercontent.com/7386756/31148644-3eddf6f8-a885-11e7-9acb-55d251980475.png">

**Comment by tonsky** [comment]
Please report to RStudio bug tracker
