### ISSUE TITLE
How to add ligatures like these to Monaco font?

### ISSUE THREAD

**Issue by pamu** [tonsky/FiraCode#499]

**Comment by pamu** [comment]
I like Firacode with ligatures. Thank you so much for the work. It would be great to have Monaco with these ligatures. How to get ligatures with Monaco font?

**Comment by tonsky** [comment]
Get yourself a font editor (I use Glyphs 2, there’re also FontLab, RoboFont, many others) and draw them (or copy from Fira Code)

**Comment by pamu** [comment]
Thanks for the help. Could you please tell me what to copy? is that FiraCode.glyphs?

**Comment by tonsky** [comment]
If you own Glyphs 2, you can open .glyphs file. Otherwise, open .otf ones. You need to copy ligatures themselves and calt code

**Comment by pamu** [comment]
I opened . glyphs file. I do not know how to copy calt code and ligatures. In case I copy how to apply them to Monaco font. I found this after opening the . glyphs file using glyphs 2
<img width="869" alt="screen shot 2017-10-06 at 17 59 08" src="https://user-images.githubusercontent.com/4508686/31284109-49eeef92-aac0-11e7-8ea7-c213bd1427ec.png">

**Comment by tonsky** [comment]
You’ll need everything named `*.liga` and `_part.*` You can use search field at the bottom to filter by part of file name. After than, select, Cmd+C, Cmd+V should work. The only gotcha might be that Monaco font probably have different glyphs dimensions. You’ll have alter every glyph manually to match those.

To get to the `calt` table, go to Font Info (Cmd+I) → Features → Calt

**Comment by NiavlysB** [comment]
I hope it's not a problem to comment on a closed issue, but for anyone who's having trouble adding Fira Code's ligatures to another font, here's a great script I found: https://github.com/ToxicFrog/Ligaturizer (look up issue 30 if the command doesn't work)

Thank you FiraCode for bringing ligatures to monospaced fonts!

**Comment by eduardonunesp** [comment]
@pamu any update about ligatures on monaco font ?

**Comment by yograf** [comment]
https://github.com/GianCastle/FiraMonaco

**Comment by iPzard** [comment]
That's for the sharing yograf, very cool!
