### ISSUE TITLE
Bold version?

### ISSUE THREAD

**Issue by mklingen** [tonsky/FiraCode#5]
Is it possible to get bold/italic versions of the font included alongside the regular version? Right now, editors have to fake bold/italic, which breaks the monospaceness.

**Comment by tonsky** [comment]
Theoretically nothing stops from having it, although I don’t know when I’ll get my hands on it. Eventually, maybe

**Comment by mklingen** [comment]
Cool, not a big deal. Maybe its possible for me to use regular Fira for bold and FiraCode for non-bold...

**Comment by jasonlong** [comment]
+1 would :heart: to have a bold version.

**Comment by nightcoding** [comment]
+1 as I want to use it in my ZSH.

**Comment by 13h3r** [comment]
+1

**Comment by WorldMaker** [comment]
:+1: Bold and italic are increasingly used in good syntax themes and it would be great to see the full gamut supported.

**Comment by 5310** [comment]
:+1: Yes please?

**Comment by kirang89** [comment]
+1

**Comment by nightcoding** [comment]
+1

**Comment by tonsky** [comment]
There’re now Bold, Medium and Retina (slightly heavier than Regular) weights in addition to Regular.
