### ISSUE TITLE
kde support

### ISSUE THREAD

**Issue by ltlollo** [tonsky/FiraCode#50]
I see that kate/kwrite/konsole are listed as 'should work'.
While they didn't in kde4, but they definitely work in plasma/kde 5
![snapshot12](https://cloud.githubusercontent.com/assets/7858791/9825759/d76cb546-58d5-11e5-8d66-a0eaff8ab7c0.png)

**Comment by simcop2387** [comment]
I know this has been closed, but I had them working in kde4 in debian fine.  I wonder if it's possible that not all distros have something setup correctly for kde4 to use them?

**Comment by ltlollo** [comment]
wild guess, but it could be that people (like me) who had it broken on kde4 was due to compose cache.

**Comment by ltlollo** [comment]
Ok, I tested on a debian jessie machine with kde4 and it ligatures are properly displayed
