### ISSUE TITLE
Ligature request for Smalltalk

### ISSUE THREAD

**Issue by amiracam** [tonsky/FiraCode#500]
so assignment is the original Smalltalk was  like so : 

a <-  'hello'

well actually it was actually a left pointing arrow.

In code assignment is:

a := 'hello'

It would be melancholic and very cool if I could have a font ligature for ":=" that would indeed show up as an left pointing arrow.

greatly appreciated, or if could simply be shown how to actually accomplish that

thanks

**Comment by tonsky** [comment]
We already have ligature for `:=`, but it’s not rendered as left-pointing arrow. It’ll be against Fira Code principles: do not confuse. I understand that it might make sense for Smalltalk but not for everybody else using Fira Code
