### ISSUE TITLE
Sublime 3146 and newer supports ligatures

### ISSUE THREAD

**Issue by DmitrySkripkin** [tonsky/FiraCode#505]
New dev version of Sublime Text now supports ligatures. No additional plugins or workarounds needed just install the font and add this line to your settings:
`"font_face": "Fira Code",`

Is it right time to update readme? Or we need stable version?

**Comment by tonsky** [comment]
See #502

**Comment by hanoii** [comment]
@DmitrySkripkin do you know how to select the retina sub family on sublime text?

**Comment by ajoy39** [comment]
@hanoii 
```
"font_face": "Fira Code Retina"
```

**Comment by gudata** [comment]
@ajoy39  
with 
```
"font_face": "Fira Code Retina"
```
I do not see any change from "Monospace"

If I do I get:
```
>>> view.settings().get('font_face')
'Fira Code Retina'
```

font is installed, I see also the normal fira code

**Comment by ajoy39** [comment]
@gudata did you already restart sublime? My font didn't change until I restarted.

**Comment by tonsky** [comment]
it’s `"font_face": "FiraCode-Retina"` for mac

**Comment by gudata** [comment]
nice, thanks!
