### ISSUE TITLE
Font adds to VSCode while symbols dont get fusioned

### ISSUE THREAD

**Issue by ShalokShalom** [tonsky/FiraCode#507]
See this: 

![screenshot_20171011_131922](https://user-images.githubusercontent.com/6344099/31437832-f30b8670-ae86-11e7-8943-860e328f4704.png)

As you can see, the font is active, while the |> down there still looks the same. :)

**Comment by tonsky** [comment]
Font is not active :) There’s probably some problem with installation

**Comment by ShalokShalom** [comment]
Restart was missing :)

**Comment by ShalokShalom** [comment]
Thanks a lot, it looks astonishing ^-^
