### ISSUE TITLE
What are your settings for your screenshots?

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [tonsky/FiraCode#509]
I use manjaro linux (based on arch linux) and I downloaded one of the suggested font sources in the AUR (`otf-fira-code`). However my font looks rather thin compared to your screenshots. Do you have any suggestions?

I have these settings on emacs 
`(when (member "Fira Code" (font-family-list))
  (set-face-attribute 'default nil
		      :font "Fira Code"
		      :weight 'medium
		      :width 'normal
		      :height 120))`

Looking at your screenshots compared to mine (for example the javascript screenshot) it seems your letters are closer together and bolder.

![firacode2](https://user-images.githubusercontent.com/30783193/31635282-356abe80-b294-11e7-8e7e-5923ad0a59c2.png)

**Comment by tonsky** [comment]
The glyphs are certainly Fira Code. I’m on a Mac, screenshots are rendered in Sketch. I’m using Normal font weight. Linux font rendering is infamous for its overall bad quality, not sure it’s fixable without switching to Mac or Windows
