### ISSUE TITLE
Lots of glyphs are replaced with placeholders

### ISSUE THREAD

**Issue by KOLANICH** [tonsky/FiraCode#510]
For example U+2126 (ohm sign) and others. Since they are also replaced in Fira Mono how about removing the placeholders and allowing the OS to take the most appropriate glyph from the fonts installed on PC? Or how about taking these glyphs from other fonts like Noto, Hack and Inconsolata?

**Comment by tonsky** [comment]
There are no placeholders in the font. U+2126 is not in Fira Code. Whatever you use to render the font failed to render fallback font
