### ISSUE TITLE
Your font workflow

### ISSUE THREAD

**Issue by ihodev** [tonsky/FiraCode#511]
Hello, @tonsky ! I need your help :wink: I want to add ligatures support to my favorite font, however I'm not a font designer. Can you tell me what software did you use to add ligatures support to Fira Mono? It would be great to see some short recommendations or information about your approach.

In any case, thank you a lot for your hard work on this project :heart:

**Comment by jdreesen** [comment]
Maybe you want to have a look at #499

**Comment by ihodev** [comment]
Wow, I did not find that :disappointed:  That issue is exactly what I want to see, thanks :wink:
