### ISSUE TITLE
Missing Powerline glyphs macOS Sierra/iTerm2

### ISSUE THREAD

**Issue by jkarsrud** [tonsky/FiraCode#514]
I'm having a hard time getting all the powerline glyphs working in iTerm2. I'm using the 'agnoster' theme in my zsh, with the following unicode addresses: 

```sh
SEGMENT_SEPARATOR="\ue0b0"
PLUSMINUS="\u00b1"
BRANCH="\ue0a0"
DETACHED="\u27a6"
CROSS="\u2718"
LIGHTNING="\u26a1"
GEAR="\u2699"
```

Running `echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"` yields the following result;

![image](https://user-images.githubusercontent.com/185357/31896551-5a2fed28-b814-11e7-9d71-f7760d7b591d.png)

This is what it *should* look like 
![image](https://user-images.githubusercontent.com/185357/31897195-ec47ed22-b815-11e7-82f1-f5d810b8ea19.png)

I'm not sure why I'm not seeing all the symbols, as they appear to be present in the glyphs.

**Comment by tonsky** [comment]
Well, since glyphs are definitely in the font, it’s either iTerm or your font not being set up properly

**Comment by jkarsrud** [comment]
@tonsky This was a false alarm that was fixed by a restart of iTerm and a reboot. Don't ask me what happened, but it work now. Sorry about the noise! :)

**Comment by tonsky** [comment]
No worries. Happy it all resolved itself
