### ISSUE TITLE
Ligature request: [| |]

### ISSUE THREAD

**Issue by magnus-madsen** [tonsky/FiraCode#516]
In ReasonML arrays are written as: 

```reasonml
let myArray = [|"hello", "world", "how are you"|];
```

It would be nice to have ligatures for `[|` and `|]`

**Comment by tonsky** [comment]
I’ll see what I can do. When I made a ligature for `[]` many people were not happy. Have to be careful with something so basic. Thanks for the suggestion!

**Comment by j-f1** [comment]
How about ligating `[|` to ` ⟦` and `|]` to `⟧ `?

**Comment by tonsky** [comment]
yeah that make sense, thanks
