### ISSUE TITLE
New terminal with ligature support

### ISSUE THREAD

**Issue by kovidgoyal** [tonsky/FiraCode#519]
FYI, kitty https://github.com/kovidgoyal/kitty just landed support for ligatures. https://github.com/kovidgoyal/kitty/issues/50

I used FiraCode in my testing and have included a copy in the kitty test data, I hope that is OK. If not, let me know and I will remove it.

**Comment by tonsky** [comment]
I wasn’t able to get ligatures working. Is there a setting I need to enable?

<img width="751" alt="screen shot 2017-11-13 at 14 02 54" src="https://user-images.githubusercontent.com/285292/32722596-6cc29220-c87b-11e7-920a-3c337ab461a9.png">

**Comment by kovidgoyal** [comment]
It's not released as yet, so you have to build from master. Here's a screenshot of what it looks like (on linux)
![screenshot_20171113_164848](https://user-images.githubusercontent.com/1308621/32723186-8f04e51a-c892-11e7-9aac-1bbb834d75f2.png)

**Comment by tonsky** [comment]
Ah, I see. I’ll update the README as soon as new version is available then. Please let me know

**Comment by vxid** [comment]
Just a heads up, ligatures are now working when using the [kitty-git](https://aur.archlinux.org/packages/kitty-git/) package from the AUR.

**Comment by kovidgoyal** [comment]
version 0.5.0 with ligature support has been released.

**Comment by tonsky** [comment]
Awesome! Great work, thanks! Added it to the support table

**Comment by BangL** [comment]
so.. kitty != KiTTY, huh?
pretty confusing.. i was thinking of the putty fork: http://www.9bis.net/kitty/
took my a while to realize that this kitty is a complete different thing.
