### ISSUE TITLE
=== display strange when font size 13

### ISSUE THREAD

**Issue by nuintun** [tonsky/FiraCode#521]
Screen: 1920*1080
Font-size: 13px
IDE: vscode

![_20171117142405](https://user-images.githubusercontent.com/1730277/32932607-7ccb2a94-cba3-11e7-9eb8-a75aaf1a5215.png)

**Comment by tonsky** [comment]
Yep. It’s a well-known hinting issue on Windows. More issues here: https://github.com/tonsky/FiraCode/wiki#hinting-issues. I’ll close this one as a duplicate. Unfortunately, so far the only solution is to adjust font size
