### ISSUE TITLE
Ligature Request: Path traversal "./" and "../"

### ISSUE THREAD

**Issue by AaronAsAChimp** [tonsky/FiraCode#523]
Currently the ".." ligature is used and leaves gaps on either side of the slashes. It would be nice if "./" and "../" formed ligatures or had their spacing tweaked. They're very commonly used when programming and on the command line.

Its worth also considering with Windows paths the slashes are reversed, ".\\" and "..\\" respectively.

Fira Code:
![path-traversal-ligature](https://user-images.githubusercontent.com/60481/33135937-e6a38480-cf71-11e7-8399-63b028ec73ef.PNG)

Consolas:
![path-traversal-no-ligature](https://user-images.githubusercontent.com/60481/33136729-f64fb532-cf73-11e7-93b0-b2875ac49de9.PNG)

**Comment by kosiakk** [comment]
That's quite okay, IMHO.
`..` is actually a single entity, so current behaviour is even correct.
I agree, `./` should probably get similar spacing and dot size, but I wouldn't change anything in `../`
