### ISSUE TITLE
Eclipse/Neon/XUbuntu can't use some of font type

### ISSUE THREAD

**Issue by stayprivates** [tonsky/FiraCode#524]
Hi, 

With Eclipse/Neon/Darkest Theme/Xubuntu 17.10,can't select some of the fonts type:
- Medium
- Light
- Retina

Nothing happens, when I do, the preview section will show "Fire Code". .  If I select other types that do work the preview window will reflect it "Fire Code Bold" etc.

Eclipse log file is silent.

Regards,

**Comment by tonsky** [comment]
Please report that to Eclipse

**Comment by stayprivates** [comment]
Done thanks:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=527634
