### ISSUE TITLE
`<:` ligature

### ISSUE THREAD

**Issue by gdkrmr** [tonsky/FiraCode#525]
The `julia` language uses `<:` quite a bit, `x <: Type` means that variable `x` is of subtype of `Type`

**Comment by tonsky** [comment]
ok, thanks for the suggestion!

**Comment by gdkrmr** [comment]
`x::T` declares a variable `x` of type `T`
`x<:T` is subtype. So the `<:` ligature should probably match the `::` ligature somehow.

**Comment by tonsky** [comment]
The only thing I can do with it is to align dots properly, I guess. Similar to what I did with `:=`

**Comment by gdkrmr** [comment]
It currently looks like this
![screenshot_2017-11-29_09-42-34](https://user-images.githubusercontent.com/12512930/33365955-2a3cc2f6-d4ea-11e7-80c8-763fa5f13b9f.png)
The `::` looks very nice, like a single symbol, so maybe also center everything a little bit.

**Comment by gdkrmr** [comment]
looks great, thanks!
