### ISSUE TITLE
Disable ligatures on repeating characters

### ISSUE THREAD

**Issue by mission712** [tonsky/FiraCode#526]
When characters like `=`, `#`, `~`, `.` etc are used to create lines or progress bars (ncurses applications, apt, npm etc.), the ligatures make it look weird and ugly. Maybe you can create ligatures that return them to their normal states if there are more than the maximum amount they become ligatures? (4 for ####, 3 for ...)

**Comment by tonsky** [comment]
This is solved since the version https://github.com/tonsky/FiraCode/blob/master/CHANGELOG.md#1200-july-18-2016. You might be using old font version

**Comment by mission712** [comment]
Hm... I'll ask the Termux dev to update his font version. Thanks.
