### ISSUE TITLE
Atom editor setup

### ISSUE THREAD

**Issue by csholmq** [tonsky/FiraCode#53]
Once the subpixel rendering issue (https://github.com/atom/atom/issues/6055) is sorted I look forward to start using both FiraCode and Monoid in the Atom editor.

Here's a short tip for enabling ligatures, but not on the current line or in the Find and replace window. I pulled it off https://gist.github.com/larsenwork/255432b5101093fb07bc and modified it a bit.

`styles.less`

```
* {
  -webkit-font-smoothing: antialiased;
  -webkit-font-feature-settings: "liga" on, "calt" on;
}

atom-text-editor::shadow .cursor-line {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}

div.find-and-replace atom-text-editor::shadow .line {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```

**Comment by ioquatix** [comment]
I also found this was helpful 

```
atom-text-editor::shadow .string.quoted {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```

It avoids ligatures in quoted string constants.

**Comment by csholmq** [comment]
Nice! Also, subpixel rendering appears to be fixed now!

**Comment by tonsky** [comment]
Closing as this is probably not needed anymore. Atom renders and navigates through ligatures just fine
