### ISSUE TITLE
Ligatures not working in Bbedit 12.x

### ISSUE THREAD

**Issue by weitzner** [tonsky/FiraCode#530]
I am running Bbedit v12.0.2 on macOS 10.13.2. I have issued `defaults write com.barebones.bbedit "EnableFontLigatures_Fira Code" -bool YES` on the command line and restarted the editor and it does not produce ligatures.

**Comment by tonsky** [comment]
Yeah, seems like they broke it in v12

**Comment by ollicle** [comment]
FiraCode is working for me in BBEdit 12.0.2
Notably though, I am running macOS 10.12.6

**Comment by weitzner** [comment]
Fascinating.

**Comment by ollicle** [comment]
Confirmed. 
I updated to High Sierra (10.13.02) just now. 
The FiraCode ligatures are no longer appear in BBEdit 12.0.2

**Comment by ollicle** [comment]
I wrote to BareBones support about this issue. The reply is not bad news for any editor reliant on the system for text rendering:
>macOS 10.13 does not support font ligatures; we have reported this to Apple and they have replied that they have no intention of fixing it.
😩

**Comment by weitzner** [comment]
But… the ligatures work in RStudio?
