### ISSUE TITLE
feature request: visually distinct curly quote

### ISSUE THREAD

**Issue by tristanisme** [tonsky/FiraCode#532]
There's nothing worse than a sneaky [curly quote](https://practicaltypography.com/straight-and-curly-quotes.html) to ruin your day. It'd be good if FiraCode made them more visually distinct from quote marks used to surround strings.

Of course syntax highlighting will usually make them obvious, but there are various reasons why this isn't always available. Eg, you open a script in some language that you don't usually use and therefore don't have full support for.

**Comment by tonsky** [comment]
Wait, more visually distinct than this? How do you imagine it?

<img width="86" alt="screen shot 2017-12-20 at 11 06 55" src="https://user-images.githubusercontent.com/285292/34197064-e8513858-e575-11e7-9f57-55cb299d4719.png">

**Comment by bwiernik** [comment]
Adding something like an underline to the curly quotes would seem reasonable as an indicator that it is in most cases the wrong character.

**Comment by j-f1** [comment]
Perhaps make them more curly (for example, [Merriweather](https://fonts.google.com/specimen/Merriweather))?

**Comment by tristanisme** [comment]
I guess it also depends on how much you want this font to be for a specialised purpose vs general use, but what about setting the curly quote on fire? It'll be visually jarring, but that's the point.
![image](https://user-images.githubusercontent.com/7495099/40478007-3b67991c-5f8b-11e8-8206-5dc46b90ceb9.png)
