### ISSUE TITLE
Ligature request ///

### ISSUE THREAD

**Issue by prog-rajkamal** [tonsky/FiraCode#533]
This is for tripple slash comments '///'

'//' is used for comments in multiple programming languages. However '///' is used to distinguish comments.

In C#, we often use '///' for Function Documentation comments.

eg:

```csharp
/// <summary>
///  Docs for function
/// </summary>
/// <returns></returns>

// normal comment
// <summary> 
// no highlighting here 
//</summary>
```

**Comment by j-f1** [comment]
TypeScript also uses `///` comments:

```ts
///<reference types="foo" />
```

as does Objective-C:

```objc
/// Short doc comment
- (void)someMethod: (id)withArg {
  // ...
}
```

**Comment by tonsky** [comment]
You’ve got it :)

**Comment by tonsky** [comment]
In fact, it’s already ligatured since v. 0.5
