### ISSUE TITLE
Ligature request =<<

### ISSUE THREAD

**Issue by Pastafarianist** [tonsky/FiraCode#534]
In Haskell, [`=<<`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Prelude.html#v:-61--60--60-) is used all over the place as `>>=` with the order of the arguments reversed. I presume it should be fairly easy to add, since there is already a ligature for `>>=`.

**Comment by j-f1** [comment]
This seems to be supported ([since v0.1](https://github.com/tonsky/FiraCode/blob/master/CHANGELOG.md#01)).

**Comment by Pastafarianist** [comment]
Under Sublime Text 3156 I see this:

![image](https://user-images.githubusercontent.com/1315874/34541788-b26fa992-f0ea-11e7-8bbe-caffe35fa2f2.png)

Perhaps this is a bug in Sublime?

**Comment by j-f1** [comment]
It’s probably a bug in either your Haskell grammar plugin or Sublime.

**Comment by Pastafarianist** [comment]
This is most likely a bug with SublimeHaskell. I have tried switching to the vanilla Haskell theme (menu in the right-hand bottom corner → Haskell → Haskell) and now the ligature renders correctly. Furthermore, it renders correctly even after switching back to the SublimeHaskell theme. I will forward this to the author of SublimeHaskell.
