### ISSUE TITLE
My VS code doesn't work

### ISSUE THREAD

**Issue by CGQAQ** [tonsky/FiraCode#535]
VS Code ver: 1.19.1

Both 
 "editor.fontFamily": "Fira Code",
 "editor.fontLigatures": true
and
 "editor.fontFamily": "'Fira Code'",
 "editor.fontLigatures": true
are not work

vs code terminal font became so weird, and font ligature just not work

**Comment by tonsky** [comment]
```
"editor.fontFamily": "Fira Code",
"editor.fontLigatures": true
```

should work. What OS do you have? Are you sure you have Fira Code properly installed? Does it work in other apps? What do you mean by “terminal font became weird”? Any screenshots?

**Comment by CGQAQ** [comment]
I'm using Windows 10, my intellij Idea works well, I'll send screenshots later :)

**Comment by CGQAQ** [comment]
Btw, according to your wiki, you just say need config two lines code above, still need install font?  If need how to install it=_=

**Comment by tonsky** [comment]
https://github.com/tonsky/FiraCode/wiki#installing-font

**Comment by CGQAQ** [comment]
Oh, I'm sorry! I just Google how to use font ligature in vs code. And Google takes me straight to the VS Code Instructions part ,So I hadn't seen install part

**Comment by CGQAQ** [comment]
Good jobs, I love your font^_^
