### ISSUE TITLE
doesn't work in vscode

### ISSUE THREAD

**Issue by chenyeah** [tonsky/FiraCode#537]
![image](https://user-images.githubusercontent.com/22478003/34667526-52b8f144-f4a4-11e7-9ec6-afc22a0a0e98.png)

![image](https://user-images.githubusercontent.com/22478003/34667601-aa450c54-f4a4-11e7-8cc4-4e5a451aa9de.png)

No conversion

**Comment by sainaen** [comment]
Do you have `editor.fontLigatures` set to `true`?

**Comment by chenyeah** [comment]
@sainaen  thanks, i forget set this

**Comment by sainaen** [comment]
@chenyeah no problem!
could you close the issue if it's now resolved, please?

**Comment by mcepl** [comment]
@tonsky ??? This could be probably closed.
