### ISSUE TITLE
Sublime Text indent markers (Level 3+)

### ISSUE THREAD

**Issue by romanzipp** [tonsky/FiraCode#538]
I am not sore if it's an issue with sublime or the font itself.

All indent marker of level 3 & up (line 18 on screenshot) are not interrupted. This is not the case with other languages like Consolas.

I am using Sublime 3 Build 3143. (Don't need ligatures, the font itself is awesome)

![](https://user-images.githubusercontent.com/11266773/34936875-2a94c4ba-f9e3-11e7-8ac4-997bde377ac5.png)

**Comment by tonsky** [comment]
I don’t think they are drawn through font. I think ST draws them directly as lines

**Comment by romanzipp** [comment]
This is a reference screenshot with Consolas. As seen, line 18+ gets interrupted.

![](https://user-images.githubusercontent.com/11266773/34937455-39a2f704-f9e5-11e7-84e0-927da644b8bd.png)

**Comment by tonsky** [comment]
I still feel you should report it to ST authors, not me

**Comment by romanzipp** [comment]
Fixed in 3.1
