### ISSUE TITLE
Ligature request:  ::=

### ISSUE THREAD

**Issue by GeertBosch** [tonsky/FiraCode#539]
#BNF notation is often used to indicate syntax descriptions:

    <expr> ::= <term>|<expr><addop><term>

We have a nice ligatures for `:=`, but `::=` really is inconsistent in comparison, as the `::` ligature visually breaks up `::=` into `::` and `=` parts. They should really be like the `:=` ligature, but with the left two dots repeated to form a square, and probably the equals sign part extended a bit more.

<img width="166" alt="example of := vs ::=" src="https://user-images.githubusercontent.com/7277117/34952896-3c8424f8-f9e9-11e7-973b-81d0dbdf60d5.png">

This would look better something like:
<img width="166" alt="screen shot 2018-01-15 at 11 39 37 am" src="https://user-images.githubusercontent.com/7277117/34954070-0b85a972-f9ed-11e7-827b-0549f7667c8c.png">

**Comment by tonsky** [comment]
will do, thanks!

**Comment by GeertBosch** [comment]
Thanks for the super quick response! I've really enjoyed using Fira Code so far with a variety of different languages.
