### ISSUE TITLE
Different weights have different ligatures?

### ISSUE THREAD

**Issue by ToxicFrog** [tonsky/FiraCode#540]
I ran into this when experimenting with the `ligaturize` script -- different weights of Fira Code seem to have different sets of ligatures included! `ligaturize` is written for Fira Code Medium, but if you run it on Regular or Bold the wheels come off, because it's looking for ligatures that don't exist.

I got these lists by diffing the OTFs, and confirmed them with the OS font previewer:

Ligatures in Medium not in Regular:
```
ampersand_ampersand_ampersand.liga
asciitilde_asciitilde_asciitilde.liga
asterisk_asterisk_slash.liga
backslash_backslash.liga
bar_bar_bar.liga
braceleft_hyphen.liga
bracketleft_bracketright.liga
caseasterisk_asterisk.liga
equal_asciitilde.liga
equal_slash_equal.liga
exclam_exclam_exclam.liga
hyphen_braceright.liga
percent_percent_percent.liga
question_question_question.liga
semicolon_semicolon_semicolon.liga
slash_asterisk_asterisk.liga
```

Ligatures in Regular not in Medium:
```
asterisk_asterisk.liga
bar_bar_bar_greater.liga
bar_bar_greater.liga
bracketright_numbersign.liga
casebackslash_backslash.liga
greater_hyphen_greater.liga
less_asciitilde_greater.liga
less_bar_bar_bar.liga
less_bar_bar.liga
less_hyphen_less.liga
less_slash_greater.liga
numbersign_exclam.liga
period_question.liga
question_colon.liga
question_period.liga
shadeequal_slash_equal.liga
underscore_underscore.liga
```

**Comment by tonsky** [comment]
You’ve probably have files from different versions of Fira Code. Here are `numbersign_exclam.liga` followed by `equal_slash_equal.liga`, in both weights

<img width="206" alt="screen shot 2018-01-17 at 18 36 40" src="https://user-images.githubusercontent.com/285292/35051066-6e89fc66-fbb5-11e7-807b-4a9813c335af.png">
<img width="186" alt="screen shot 2018-01-17 at 18 36 33" src="https://user-images.githubusercontent.com/285292/35051067-6ea7601c-fbb5-11e7-90da-d11c8d2d0741.png">

**Comment by ToxicFrog** [comment]
These are all from the /distr/otf/ directory in this repo at master; sha1sums:

```
dd0f6d85ed3c2cea6f9dfd69cc64140304460c64  FiraCode-Bold.otf
371e154b8876ac4fb703b763ddf4ae2399904a5c  FiraCode-Light.otf
8d37890598d0b96d3695aed0bdcb72006e13c15f  FiraCode-Medium.otf
dfc0efc56ae7cc74a1d07248504a5e957d754c33  FiraCode-Regular.otf
```

**Comment by ToxicFrog** [comment]
If you want two that I'm absolutely certain don't appear in all weights, `equal_asciitilde` and `slash_asterisk_asterisk` appear in Medium but not in Regular or Bold, based on the OTFs at master.

**Comment by tonsky** [comment]
`=~` was removed in 1.200, `/**` was removed in 1.201. Current version is 1.204

**Comment by ToxicFrog** [comment]
Looks like user error on my end -- the up to date FiraCode-Medium got downloaded to the wrong place. The correct one has sha1sum `5f1ce157ae91533bb421f3bf42315685ef49846a`.
