### ISSUE TITLE
hope can have ligatures only version or a little small version

### ISSUE THREAD

**Issue by bluelovers** [tonsky/FiraCode#542]
i like this, but FiraCode make font a little bigger when use 12 ( and i can't set font-size because i have use chiniese too, if i change it , chinese font size will looks very bad)

so hope can have ligatures only version or a little small font-size version

![2018-01-27-17-15-44-3](https://user-images.githubusercontent.com/167966/35470516-f90ff2aa-0385-11e8-9d71-aa8430bcf929.jpg)
![2018-01-27-17-06-46-1](https://user-images.githubusercontent.com/167966/35470515-f8e6a896-0385-11e8-9efb-0dba0af7c4d8.jpg)

![2018-01-27-17-18-49-4](https://user-images.githubusercontent.com/167966/35470528-2bfa33d8-0386-11e8-8ea9-5d8162274d20.jpg)

**Comment by tonsky** [comment]
sorry, but what are you asking about?

**Comment by bluelovers** [comment]
when font-size 12 faircode is a little bigger height, 
hope it can release a zoom-in small height version

or a only have ligatures version font

**Comment by tonsky** [comment]
bigger height than what? what are you comparing to?

**Comment by bluelovers** [comment]
consolas

**Comment by tonsky** [comment]
So what’s your setup? Why are you comparing to Consolas specifically?
