### ISSUE TITLE
add monospace attribute for retina version

### ISSUE THREAD

**Issue by xiongdahu** [tonsky/FiraCode#543]
would you please add monospace attribute on fira code retina.ttf? so that it can be identified by some IDE

**Comment by tonsky** [comment]
there’s no monospace attribute. Retina is just an unconventional weight (traditionally there’s nothing in between Regular and Medium), so that’s might be the reason your editor doesn’t show it. What editor is it btw?

**Comment by xiongdahu** [comment]
@tonsky I think you are right, AFAIK, only jetbrain's IDEs have an option 'show monospace font only'

**Comment by xiongdahu** [comment]
thank you for created so great font especially retina version
