### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by danielyli** [tonsky/FiraCode#544]
Hey— any plans for a new release?  Latest one was 1+ years ago; looks like at least 45 new PRs have been merged to master since then.

**Comment by tonsky** [comment]
These are just readme updates. Are you waiting for something particular?

**Comment by danielyli** [comment]
Oh, ok. Good to know!

**Comment by tonsky** [comment]
There’s been lot of good ideas and proposals in the issues, I just need to find time. No particular plans on when it’ll happen yet
