### ISSUE TITLE
Projectile-ag  `error in process filter: Attempt to shape unibyte text`

### ISSUE THREAD

**Issue by jmayaalv** [tonsky/FiraCode#545]
On Emacs the Projectile-ag search is throwing  `error in process filter: Attempt to shape unibyte text` .

After commenting `;;    (94 . ".\\(?:=\\)") `  `projectile-ag` works. It might be good to add it to the emacs installation docs. 

Let me know if i should create a new PR

**Comment by tonsky** [comment]
Just add it. I’m not writing Emacs instructions myself, it’s all people contribution

**Comment by jmayaalv** [comment]
In case somebody has a similar issue with emacs, i had to use a different font in the minibuffer because i kept having problems with `projectile-ag`.

This is what i did
```
      (defun my-minibuffer-setup ()
       (set (make-local-variable 'face-remapping-alist)
          '((default :family "Menlo"))))

     (add-hook 'minibuffer-setup-hook 'my-minibuffer-setup)
```

Updated the wiki with this instructions.
