### ISSUE TITLE
MathML/XML can have `>` followed by `=`

### ISSUE THREAD

**Issue by mooniker** [tonsky/FiraCode#548]
​​​​​... as in the contents of an element could be an equals sign, and it shouldn't be ligaturized, e.g.:
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" alttext="e=mc^2">​​​​​
​​​​​  <mi>e</mi>​​​​​
​​​​​  <mo>=</mo>​​​​​
​​​​​  <mi>m</mi>​​​​​
​​​​​  <msup>​​​​​
​​​​​    <mi>c</mi>​​​​​
​​​​​    <mn>2</mn>​​​​​
​​​​​  </msup>​​​​​
​​​​​</math>​​​​​
```

**Comment by tonsky** [comment]
Yes, it’s a compromise. I figured `>=` as greater or equal is more common than this particular case

**Comment by mooniker** [comment]
Ah, ok. That makes sense. Just putting this small issue out there FYI.

**Comment by j-f1** [comment]
Or even just `>=<`.

**Comment by tonsky** [comment]
yes, that would make sense, thanks
