### ISSUE TITLE
Ligature Request: Git Merge Markers

### ISSUE THREAD

**Issue by rhysforyou** [tonsky/FiraCode#549]
Currently when I go to edit a file with git merge conflicts, the markers git inserts to delimit them look like so:

<img width="591" alt="screen shot 2018-02-09 at 3 11 43 pm" src="https://user-images.githubusercontent.com/320910/36011487-ae14b094-0dab-11e8-87a9-daa5d7a8aaff.png">

It'd be nice to have a specialised ligature for these cases, specifically for these particular character sequences:

- `<<<<<<<`
- `=======`
- `>>>>>>>`

**Comment by tonsky** [comment]
It’s already fixed (not with a ligature, but with turning off ligatures). Just update your font

**Comment by rhysforyou** [comment]
ah thanks!
