### ISSUE TITLE
PHPStorm Ligature SUpport

### ISSUE THREAD

**Issue by rwagner00** [tonsky/FiraCode#55]
The font works, but ligatures do not in PHPStorm. Tested on Linux version 9.1.

**Comment by tonsky** [comment]
Sure, it’s IDEA-based, they all share the same foundation

**Comment by tonsky** [comment]
Updated Readme to list all Intellij products explicitly

**Comment by MightyPork** [comment]
Might be worth a note in the readme, that the ligatures can cause extreme lag in PHPStorm, when enabled. Maybe needs a gaming pc to use them, this is an older thinkpad.

Had scrolling at like 1 fps, after disabling ligatures it went to normal.

**Comment by k1ng440** [comment]
i have a gaming computer worth more than 6k and still its freezes. so hard to type

**Comment by rwagner00** [comment]
Even without ligatures the font causes latency for me, also on a fairly powerful gaming rig.
