### ISSUE TITLE
'=<' is treated the same as '>='

### ISSUE THREAD

**Issue by leesah** [tonsky/FiraCode#550]
It is a common convention to document a command line argument as `--key=<value>` where `<value>` is a placeholder and supposed to be replaced when actually running the command.

On the other hand, "greater than or equal to" is usually defined as `>=` in programming languages, instead of `=>`. Actually, I am not aware of any language uses the latter.

So I would like to suggest not to ligate `=>` but leave it as is.

**Comment by j-f1** [comment]
> So I would like to suggest not to ligate `=>` but leave it as is.

That’s used in JS for arrow functions: `user => user.name` and in Ruby for hashes: `{ 'foo' => 'bar' }`.

**Comment by wopian** [comment]
Duplicate of #424

**Comment by leesah** [comment]
Guess I need a coffee. I wrote it all wrong... Should've been `<=` and "less than or equal to", instead of `>=` and "greater than or equal to" in the original text.
But not need to update, this is duplicate to #424 .
