### ISSUE TITLE
Building a PHP GET Link in a link shows ligature

### ISSUE THREAD

**Issue by TheRealGitCub** [tonsky/FiraCode#553]
Being unfamiliar with how ligatures work, this may not be possible to fix, but when building an HTML link with a PHP echo as a query string parameter, FiraCode displays the `=<` ligature and it looks weird. 

![](https://i.imgur.com/1Hp9aIN.png)

If it's possible to fix it, I would find it ideal to display the `=<` without the ligature when followed by `?php`

**Comment by willpower232** [comment]
Duplicate of https://github.com/tonsky/FiraCode/issues/424 but an interesting take at least!

Unfortunately the only immediate solution is to turn off ligatures in your editor of choice.

**Comment by TheRealGitCub** [comment]
Oh I searched but didn't find that topic. Thanks!
