### ISSUE TITLE
Feature request: Interrobang support

### ISSUE THREAD

**Issue by Sneezor** [tonsky/FiraCode#554]
Hello, I'd like to request support for the interrobang character for this font.

Expected input: ?! or !?
Expected output: ‽

I'm sorry if this is the wrong place to put it, or if it's not supported, I'm not familiar with GitHub.

**Comment by tonsky** [comment]
No, no, this is the right place. I’d be happy to add it but the font must stay monospaced, that means, if input sequence took up 2 character places, the output should as well

**Comment by Sneezor** [comment]
You could make it 2-characters wide, is that possible?

I believe I can't make it work with the current font, but it would go along the lines of...
FOO!?BAR
FOO‽ BAR

**Comment by tonsky** [comment]
Yes, but that will create lots of confusing space around. What’s wrong with !? anyways?

**Comment by Sneezor** [comment]
Every custom sign was fine without the ligature too. == means exactly the same as the 2-space sign, but the ligature version is easier to read. Just like that, the interrobang expresses no more and no less than !?, but it makes sense in its own.

All in all, I think anyone who uses this font would expect to turn their combinations of different signs into the unit that makes sense for them, some of them are a direct improvement, like >= turns into ≥ for readability, others are just slight visuals like := moves the dots a bit higher. This is no more than just another combination that makes sense on its own, but if you feel like it's not worth it we may discard it.

**Comment by tonsky** [comment]
If good visual solution existed I’d be happy to add it. But with increased spacing it’ll create more confusion, and I can’t create it too wide.

Where are combinations like `!?` and `?!` used? What meaning do you see they have?

**Comment by Sneezor** [comment]
If that's the case, I doubt anything can be done. The sign is the combination of 2 symbols in 1 place and simply means those 2 symbols at once... not much more to say.

I guess this is it, thanks for your time.

**Comment by tonsky** [comment]
Thanks for the idea anyways! If you have more and we can figure out how to apply them I’d love to hear them
