### ISSUE TITLE
Ligature request: More distinct ==

### ISSUE THREAD

**Issue by DesiQuintans** [tonsky/FiraCode#557]
Ever since I started using Fira Code, I've begun making a LOT of errors where I use = instead of == because the glyphs for both are so similar. Would you consider changing the ligature to add a hairline separation in the middle of it?

**Comment by wopian** [comment]
Duplicate of https://github.com/tonsky/FiraCode/issues/265#issuecomment-244985439 and https://github.com/tonsky/FiraCode/issues/383

**Comment by DesiQuintans** [comment]
Sorry about that, I searched the issues using the query "==" and in hindsight, that is not the best query!

**Comment by tonsky** [comment]
If I ever get to build fira code variants, there’ll be definitely be a variant with split equals sign
