### ISSUE TITLE
Empty Mathematica Association literal rendered akwardly.

### ISSUE THREAD

**Issue by pavelbraginskiy** [tonsky/FiraCode#558]
In Mathematica, an Association literal (known as a Dictionary in other languages) looks like `<|a -> x, b -> y, c -> z|>`. This looks nice with the `<|` and `|>` ligatures. An empty Association is represented by `<||>`, however Fira Code renders this with `<` followed by the ligature for `||>`. 

I cannot think of any context in which `<||>` should be rendered with the `||>` ligature and not `<|` followed by `|>`.

![image](https://user-images.githubusercontent.com/29113974/36581012-0c9146a6-1828-11e8-8fc0-1c64ea4fae64.png)

**Comment by tonsky** [comment]
Hmm, ||> is another ligature, not sure from where. But you’re right, with < before them it should render differently. Need to tune priorities

**Comment by pavelbraginskiy** [comment]
`||>` is an F# double-pipe. The `<` symbol before it will always be a syntax error.

**Comment by tonsky** [comment]
Will be rendered as `<` `||` `>` in 1.206 (see #621)
