### ISSUE TITLE
Arrows ambiguity with Unicode arrows

### ISSUE THREAD

**Issue by stevengj** [tonsky/FiraCode#559]
Copied from https://discourse.julialang.org/t/fira-code-font-and-ligatures-for-julia/9367/13?u=stevengj:

`-> => → ⇒ ⟶ ⟹` are all distinct operators in Julia. It seems like your ligatures make the first two look very similar to some of the latter ones, which is problematic:

![image](https://user-images.githubusercontent.com/2913679/36791161-04868926-1c65-11e8-9696-42eda5294ea9.png)

This illustrates the general danger of mixing fancy ligatures with a language that supports both ASCII and Unicode operators.  (Something like `<=` looking like `≤` is probably okay, because any language like Julia that supports `≤` directly will certainly have it mean the same thing as `<=`.)   Please be conservative about ligatures that make some combination of ASCII characters closely resemble a completely unrelated Unicode character.

**Comment by j-f1** [comment]
A difference here is that the ligature for `->` is two characters wide, whereas `→` is one character wide.

**Comment by tonsky** [comment]
Fira Code is for languages that don’t support Unicode and resort to ASCII pseudo-graphics instead, for historical or other reasons. If you can use full Unicode range, I definitely recommend that (I believe that’s the future) and you probably don’t need something like Fira Code
