### ISSUE TITLE
Missinterpreted symbols in comments since v1.205

### ISSUE THREAD

**Issue by BramVer** [tonsky/FiraCode#562]
Running Arch Linux and using the [otf-fira-code](https://aur.archlinux.org/packages/otf-fira-code/) package from AUR.
I use Fira Code Light in both Firefox 59.0b13 and Sublime Text Build 3157.

I have a strange issue since updating to the latest version this morning, where the symbols in comment blocks and in markdown are drawn as different symbols.
So far this only happens with < and > where they are represented as - and +.
I added screenshots at the bottom to show what I mean.

At first I thought it was a strange behaviour in some addon I installed in Firefox, but this persisted when everything got shut off.
Same with Sublime Text, since I thought it very strange for a font to know when it was in a comment context.
Any idea what could have caused this?

**Screenshot from Sublime Text:**
![image](https://user-images.githubusercontent.com/16743200/36895136-16d6f066-1e0e-11e8-8f9f-f1cab9634b29.png) 
versus Droid Sans 
![image](https://user-images.githubusercontent.com/16743200/36895150-2ce5c27e-1e0e-11e8-928f-92ae01219bc3.png)
**Screenshot from FireFox:**
![image](https://user-images.githubusercontent.com/16743200/36895165-3c2e9788-1e0e-11e8-9758-481b748f46f2.png)

**Comment by tonsky** [comment]
There’s definitely a bug somewhere, but I doubt it’s in the font. It’s hard to make a bug in the font as it’s just pictures of letters. So it’s either Sublime, Firefox, Linux or otf-fira-code package. Try TTF maybe?

**Comment by BramVer** [comment]
Uninstalling the OTF and installing the TTF version fixed it for me, thanks.
Strange issue, but at least the Fira Code update isn't to blame :+1:
