### ISSUE TITLE
<% %> tags within quotation marks VSCode

### ISSUE THREAD

**Issue by DrummerSi** [tonsky/FiraCode#563]
Classic ASP (and some javascript templates) use the delimiters <% and %> for templating.

This causes incorrect characters to appear within the quotes.

For example, I expect to see:
```
<a href="/process?id=<%=quote.id %>">Process</a>
```

But instead see:
![capture](https://user-images.githubusercontent.com/1278476/36897330-0c09e792-1e0e-11e8-906e-cabb24444aa4.PNG)

Notice the LASS THAN sign.

**Comment by j-f1** [comment]
Here’s what I see in the latest version of Fira Code, where `=<` got removed:

<img width="668" alt="screen shot 2018-03-02 at 07 09 42" src="https://user-images.githubusercontent.com/25517624/36898496-1367c362-1de9-11e8-9663-41c875fad5f3.png">

**Comment by tonsky** [comment]
Just update. It was fixed in the latest version (1.205) 3 days ago
