### ISSUE TITLE
<= versus =<

### ISSUE THREAD

**Issue by kand** [tonsky/FiraCode#565]
I ran into an invalid left-hand assignment compilation error in JS that was obscured by the same ligature being used for `<=` and `=<`. Perhaps these symbols could generate different ligatures to make the difference in ordering obvious?

**Comment by j-f1** [comment]
The `=<` ligature was removed in version 1.205, which was just released a few days ago. Make sure you have the latest version installed, and don’t forget to restart your editor after updating.

**Comment by robsonsobral** [comment]
But I think we could have a ligature for `=<`, just different from `<=`. Is that possible?

**Comment by tonsky** [comment]
it conflicts with pretty common combinations like `x=<...>`

**Comment by robsonsobral** [comment]
(There's no sad reaction. Imagine one here.)

Thank you, @tonsky .
