### ISSUE TITLE
Hexadecimal x not forming ligature

### ISSUE THREAD

**Issue by MarcelloNicoletti** [tonsky/FiraCode#567]
The x in hexadecimal numbers should be a ligature showing up as the times symbol instead. It doesn't appear that way for me currently.

ps: The www ligature also doesn't appear to be working for me.

<img width="441" alt="lig" src="https://user-images.githubusercontent.com/1910383/36961448-ac374182-2008-11e8-9d8a-60e0f2ed3afa.png">

------

OS: macOS 10.13.3
product: iTerm2 3.1.5, ligatures enabled, same font for ascii & non-ascii, zsh 5.4.2 w/syntax highlighting addon
FiraCode: v1.205

**Comment by tonsky** [comment]
I can reproduce, but I believe you  have to report that to iTerm. Nothing special about these ligatures in the font
