### ISSUE TITLE
Add ligature for =!=

### ISSUE THREAD

**Issue by kthompson** [tonsky/FiraCode#569]
Some languages use `=!=` for inequality and it currently shows up as 
![capture](https://user-images.githubusercontent.com/15068/37228758-891eb45a-2396-11e8-98f4-5ec62fe1b5f1.PNG)

**Comment by j-f1** [comment]
@kthompson This was added in the most recent release; make sure you have the latest version installed.

**Comment by kthompson** [comment]
Oh awesome thanks! 👍
