### ISSUE TITLE
Works with neovim-gtk as well

### ISSUE THREAD

**Issue by mcepl** [tonsky/FiraCode#571]
![fira-nvim-gtk](https://user-images.githubusercontent.com/198999/37287069-266577d4-2604-11e8-8b3f-c31e2614b1dc.png)
[neovim-gtk](https://github.com/daa84/neovim-gtk) je Gnome neovim GUI frontend written in Rust.

**Comment by anson2416** [comment]
Halo, can anybody share the vim config for Neovim running in windowns 10?

i use below setup and nvim is displaying very ugly font. 
`set guifont=Fira\ Code:h12`

![default](https://user-images.githubusercontent.com/16176918/48981677-af265e00-f113-11e8-9f49-c1475a689c22.png)
