### ISSUE TITLE
? and ?? seem to have too much spacing

### ISSUE THREAD

**Issue by ceeK** [tonsky/FiraCode#572]
Not sure if this is related to my editor or the font, so apologies.

Single question mark seems too far right:
<img width="44" alt="screen shot 2018-03-12 at 15 58 05" src="https://user-images.githubusercontent.com/1478253/37294917-da53886c-260e-11e8-80c6-1b72c166d3d3.png">

Double question mark seems too far left:
<img width="41" alt="screen shot 2018-03-12 at 15 59 33" src="https://user-images.githubusercontent.com/1478253/37294937-e55370ba-260e-11e8-85a0-950a201b5db2.png">

Three question marks seem fine:
<img width="109" alt="screen shot 2018-03-12 at 15 59 18" src="https://user-images.githubusercontent.com/1478253/37294961-ecef2a8a-260e-11e8-9c0e-2347437d51e9.png">

I thought I'd input an extra space by accident in the first 2 examples.

**Comment by tonsky** [comment]
that’s how ligature for `??` looks like. Two question marks closer together

**Comment by ceeK** [comment]
@tonsky Yeh I get that, but the kerning feels wrong to me:

<img width="176" alt="screen shot 2018-03-12 at 15 58 05" src="https://user-images.githubusercontent.com/1478253/37302518-ac7b4afa-2623-11e8-9fbe-0cce399eb8ca.png">

How come there is such a large space to the left of a `?`?

**Comment by tonsky** [comment]
It’s a monospaced font so I had to make compromises. No matter how little I want to draw in e.g. `?.` it has to take two character spaces

**Comment by ceeK** [comment]
Ahh I see that makes sense!
