### ISSUE TITLE
Reserved Font Name

### ISSUE THREAD

**Issue by davelab6** [tonsky/FiraCode#573]
The upstream https://github.com/mozilla/Fira/blob/master/LICENSE has only "Fira" as a reserved font name, but in this repo there is 3 rfn. Why is that?

The requirement of the rfn is to either rename a fork to not use the reserved name in whole or in part, or to get permission from the rights holders to use the name. 

Where is the permission statement from Mozilla and Telefonica to use the rfn?

**Comment by tonsky** [comment]
> The requirement of the rfn is to either rename a fork to not use the reserved name in whole or in part 

where are you getting this from?

**Comment by davelab6** [comment]
The ofl FAQ and years of correspondence with sil themselves

**Comment by tonsky** [comment]
No, I mean, which line in the license file requires that?

**Comment by davelab6** [comment]
There are 3 parts of the license file that form this requirement:


Digitized data copyright (c) 2012-2015, The Mozilla Foundation and
Telefonica S.A.
with Reserved Font Name < Fira >,


"Reserved Font Name" refers to any names specified as such after the
copyright statement(s).


3) No Modified Version of the Font Software may use the Reserved Font
Name(s) unless explicit written permission is granted by the corresponding
Copyright Holder.




Note that the reserved word is Fira, and the definition is "any" so even if
it was "Fira Sans" (which it's not) then 3 would still apply to you.

**Comment by tonsky** [comment]
Hmm. That’s interesting. If you actually open [the license in my repo](https://github.com/tonsky/FiraCode/blob/master/LICENSE) it says

```
Copyright (c) 2014, Mozilla Foundation https://mozilla.org/
with Reserved Font Name Fira Sans.

Copyright (c) 2014, Mozilla Foundation https://mozilla.org/
with Reserved Font Name Fira Mono.
```

That’s because I copied it with along with everything else. I guess they changed the license after (link: https://github.com/mozilla/Fira/commit/7e14c60ee00e49320e7b3b165d94bc0853446c29#diff-9879d6db96fd29134fc802214163b95a).

I suppose terms of the original license (at the moment of forking) apply, since I don’t pull updates from the upstream? License change was made March 2015, Fira Code 0.1 published Nov 2014

**Comment by davelab6** [comment]
Ah, thanks for clarifying that. Indeed the history of the file in the
upstream repo is interesting, as it indicates that Telefonica didn't have
an interest in declaring the RFN.

Still, as I said, even though the reserved names at the time of your fork
were "Fira Sans" and "Fira Mono", because the RFN definition is "any", then
the terms of section 3 requiring permission from Mozilla to use the name
still apply.

http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ofl-faq_web#60735680
says

> Question: 5.5 So what should I, as an author, identify as Reserved Font
Names?
>
> Answer: Original authors are encouraged to name their fonts using clear,
distinct names, and only declare the unique parts of the name as Reserved
Font Names. For example, the author of a font called "Foobar Sans" would
declare "Foobar" as a Reserved Font Name, but not "Sans", as that is a
common typographical term, and may be a useful word to use in a derivative
font name. Reserved Font Names should also be single words for simplicity
and legibility. A font called "Flowing River" should have Reserved Font
Names "Flowing" and "River", not "Flowing River". You also need to be very
careful about reserving font names which are already linked to trademarks
(whether registered or not) which you do not own.

**Comment by davelab6** [comment]
Its a bit of a tortuous path, but this issue depends on https://github.com/mozilla/Fira/issues/218 which depends on https://github.com/mozilla/Fira/pull/219 which depends on _someone_ at Mozilla merging that PR :D 

However, the actual underlying legal issue **was** solved, so I believe you can remove the RFN from this repo.
