### ISSUE TITLE
Not consistent rendering for ligatures <= and >=

### ISSUE THREAD

**Issue by mishadoff** [tonsky/FiraCode#574]
When using FiraCode for Clojure I observed such inconsistency

<img width="319" alt="screenshot 2018-03-15 17 30 31" src="https://user-images.githubusercontent.com/814799/37473349-db95e408-2876-11e8-8299-7b5d1d750700.png">

Probably `:>=` conflicting with some other ligature

**Comment by tonsky** [comment]
Yep. With `:>`. Thanks!
