### ISSUE TITLE
Error when install firacode with choco

### ISSUE THREAD

**Issue by krisnantobiyuh** [tonsky/FiraCode#575]
Hay can help me, everybody. I received an error while running `choco install firacode`. this is my mistake

`ERROR: Checksum for 'C:\Users\HEWLETT PACKARD'\AppData\Local\Temp\chocolatey\FiraCode\1.205\FiraCode_1.205.zip' did not meet '85B2A6DE92B71EF0F7715CCA32D394484221EC978CB21E5228DC99978A7B7D8D' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of firacode was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\FiraCode\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - firacode (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\FiraCode\tools\chocolateyInstall.ps1'.
 See log for details.`

I am confused to solve this problem. what i did for this error?

**Comment by tonsky** [comment]
It’s probably fine. I guess the person who updated the package specified the wrong checksum. Better resolve with him/her
