### ISSUE TITLE
where to set "Fira Code Medium" in pycharm?

### ISSUE THREAD

**Issue by happywmzzz** [tonsky/FiraCode#576]
os: mac
and same in vs code

I like medium version more, but I could not find the medium in font list. only Fira code
thx~

**Comment by tonsky** [comment]
In VS Code it’s simple: `"editor.fontFamily": "FiraCode-Medium"`. No idea how to do the same in PyCharm.

**Comment by natros** [comment]
AFAIK it's not possible. However, you can disable the Fira Code Light in Font Book

![image](https://user-images.githubusercontent.com/4996289/37909499-feb05cd6-3102-11e8-8d52-069eb21c93c4.png)

**Comment by tanloo** [comment]
I also want to use Fira Code Light in IntelliJ IDEA...But IntelliJ IDEA just can choose default Fira Code font.
Anyone help?

**Comment by phen0menon** [comment]
@happywmzzz, @tanloo, I found an approach. Just unset checkbox "Show only monospaced fonts" in `Settings > Editor > Font` and choose the preferred font.

![123](https://user-images.githubusercontent.com/15520523/54668517-24250580-4b00-11e9-8fce-b59af9ebcfec.png)

**Comment by tonsky** [comment]
You can choose font weights in 2021.1:

![EditorFontWeight](https://user-images.githubusercontent.com/285292/114234880-aac70c80-997f-11eb-8315-47e4d2315478.gif)
