### ISSUE TITLE
Backslashes became very hard to see (almost invisible)

### ISSUE THREAD

**Issue by realnc** [tonsky/FiraCode#577]
After I upgraded to 1.205, all backslashes in my code became very hard to spot. Basically, this:

    auto msg = "Test\nFoo bar.\n";

looks more like this:

    auto msg = "Test nFoo bar. n";

The backslashes are very faint and of the wrong color. This is a problem only when using a black background with light text (which is what I use in my IDE, which is Qt Creator.)

For comparison, this is with DejaVu:

![1](https://user-images.githubusercontent.com/1665903/37833710-b0a5a3fc-2eb4-11e8-842d-573e3b57aeb9.png)

It has good visibility. But with Fira Code it's hard to read:

![2](https://user-images.githubusercontent.com/1665903/37833723-b5ea862a-2eb4-11e8-9ad4-4b33b03a6561.png)

**Comment by j-f1** [comment]
This is an intentional change ([see the changelog](https://github.com/tonsky/FiraCode/blob/master/CHANGELOG.md#1205-february-27-2018), third bullet point)

**Comment by realnc** [comment]
How do I prevent it? This makes the font unusable for me :-/

**Comment by tonsky** [comment]
I plan to change how it works in the next version. For now you can use previous font version (1.204)

**Comment by doughsay** [comment]
For what it's worth, I really like the new thin backslash, and it doesn't look bad at all in my editor.

<img width="240" alt="screen shot 2018-04-04 at 4 42 51 pm" src="https://user-images.githubusercontent.com/221693/38340247-3fbec03e-3827-11e8-9403-413ecce6c052.png">

**Comment by miniBill** [comment]
I think that a lot depends on whether your editor highlights escape code (in which case the thin backslash is good) or not

**Comment by Moulick** [comment]
Yep, the thin backslash is hard to read in Python as well.

**Comment by doughsay** [comment]
:cry:

**Comment by j-f1** [comment]
Would it be possible to bring this back for just `\\`? It makes sequences of slashes much easier to read.

**Comment by tonsky** [comment]
Maybe—please create a separate issue for that

**Comment by j-f1** [comment]
⏩ #720

**Comment by Vampire** [comment]
Very sad this was removed, I really liked seeing an escaping backslash thin, showing that it is an escape sequence. :-(

**Comment by j-f1** [comment]
Could this be a stylistic set @tonsky?
