### ISSUE TITLE
Regex Lookbehind and the `<=<` ligature

### ISSUE THREAD

**Issue by j-f1** [tonsky/FiraCode#578]
I encountered this issue [here](https://github.com/zeit/styled-jsx#atom):

```
(?<=<foo>)
```

<img width="672" alt="screen shot 2018-03-25 at 07 58 28" src="https://user-images.githubusercontent.com/25517624/37874740-bb76d55e-3002-11e8-9955-b352c62a755d.png">

This would look better rendered as

```
(?<=​<foo>)
```

<img width="672" alt="screen shot 2018-03-25 at 07 58 39" src="https://user-images.githubusercontent.com/25517624/37874741-bfa922ee-3002-11e8-9293-a5299c260345.png">

since the `<=` and `<` are separate. It looks like matching `(?<=` separately would do the trick here.

**Comment by tonsky** [comment]
Thanks!

**Comment by long-lazuli** [comment]
Matching `(?<=` would do the trick, but I would rather see a left arrow than a lessOrEqual sign aside the ? ...
