### ISSUE TITLE
Make back slash darker 

### ISSUE THREAD

**Issue by pamu** [tonsky/FiraCode#579]
Back slash appears too light.
<img width="542" alt="screen shot 2018-03-25 at 16 31 31" src="https://user-images.githubusercontent.com/4508686/37875578-060ef334-304a-11e8-9e02-d0e571315270.png">

**Comment by tonsky** [comment]
Is that Haskell? What does backslash mean here?

**Comment by Moulick** [comment]
@tonsky Yeah man, that thin backslash in the latest release is not easily visible.

**Comment by miniBill** [comment]
@tonsky it's Haskell, and `\a -> b` is a function taking `a` as argument and returning `b` as result.

**Comment by leopiccionia** [comment]
Haskell uses `\` as the lambda (anonymous function) operator, supposedly due to similarity between `\` and `λ` (Hasklig considered a `\`->`λ`-like ligature, but rejected it because `λ` is a valid identifier in Haskell).

**Comment by code4t2** [comment]
That looks like it's interpreting them as the escape character(s) in Java/C#/others (` \n \t \r` etc.) This behavior is actually useful in these languages, so I'm not sure this would be a bug.

**Comment by unclechu** [comment]
@tonsky it's "black" slash (not "back").

**Comment by tonsky** [comment]
@unclechu what are you talking about? https://en.wikipedia.org/wiki/Backslash

**Comment by unclechu** [comment]
@tonsky I'm talking about the title of the issue, please read it carefully.

**Comment by tonsky** [comment]
thx, fixed

**Comment by pamu** [comment]
Is anyone working on it?

**Comment by tonsky** [comment]
Should’ve been fixed in 1.206 https://github.com/tonsky/FiraCode/issues/577
