### ISSUE TITLE
Windows: Show nonsense characters

### ISSUE THREAD

**Issue by mtrakal** [tonsky/FiraCode#581]
I tried to install FIra code into windows over chocolatey, but it failed in my case (first time to try chocolatey), so I just move Fira font into Control Panel > Fonts.

But it totally break font.
So I remove all Fira from Fonts again.
But problem is still there :'(. After reboot, or anything I can't return back to working state.

![2018-04-02](https://user-images.githubusercontent.com/1458891/38193177-e9a6b2a4-3670-11e8-8390-60fa5589ffe8.png)

**Comment by tonsky** [comment]
People reported similar problem. If I remember correctly, the solution was to go to c:\windows\fonts with console (not Explorer) and kill everything that has Fira in the name. There are some temprorary copies or something. Let me know if that helps

**Comment by mtrakal** [comment]
Hi, it looks, that really help. Remove just from Control Panel > Fonts > Delete didn't help, but remove from C:/Windows/Fonts helps.
Thank you a lot 👍
