### ISSUE TITLE
Two ligatures not working in VSCode

### ISSUE THREAD

**Issue by lilnayners** [tonsky/FiraCode#582]
I just installed the latest version of Fira Code on my PC, enabled ligatures in VSCode, and changed my font family, I have tested out all of the operators that I use the most just to make sure it's working. The only ones that aren't working properly are <= and &&, really any of the symbols that include the <. I've gone through the troubleshooting section and searched the issues to see if anyone else is having this exact issue, and I haven't been able to figure out how to fix it. Any idea what might be causing just these two to be having problems?

**Comment by tonsky** [comment]
Probably this: https://github.com/tonsky/FiraCode/wiki#some-ligatures-work-while-some-dont

> Atom/VS Code are known to break certain ligatures in certain syntaxes #361 #353 #348 #328 #326 #235

Try setting your syntax to plain text and see if ligatures come back. If they do, report to the syntax highlight author to fix their parsing rules

**Comment by lilnayners** [comment]
Setting to plain text worked! Thanks for the help, I'll close out the issue.
