### ISSUE TITLE
Ligature request: =>= and &&&

### ISSUE THREAD

**Issue by miniBill** [tonsky/FiraCode#584]
This two: [=>=](https://hackage.haskell.org/package/comonad-5.0.3/docs/Control-Comonad.html#v:-61--62--61-) and [&&&](https://hackage.haskell.org/package/base-4.11.0.0/docs/Control-Arrow.html#v:-38--38--38-).

The first one is especially important, because the current ligature for `>=` makes it horrible.

**Comment by tonsky** [comment]
=>= is done in v4

**Comment by tonsky** [comment]
Extracted &&& to #1042

**Comment by miniBill** [comment]
Awesome!!!
