### ISSUE TITLE
Add ẞ U+1E9E Latin Capital Letter Sharp S

### ISSUE THREAD

**Issue by Announcement** [tonsky/FiraCode#587]
in german there is a grapheme known as eszett at code point U+00DF (ß), whilst not technically part of their alphabet, there is a capital variant at code point U+1E9E (ẞ),  and I use this font for IRC and it's literally the first missing character I've had so I figured why not request it and see what happens. addition would be greatly appreciated. or not, whatever, I don't need it to live, lol.

**Comment by tonsky** [comment]
ok, I’ll look if I can borrow it from somewhere
