### ISSUE TITLE
Fraction slash is misaligned

### ISSUE THREAD

**Issue by hipsterjazzbo** [tonsky/FiraCode#588]
The fraction slash character (U+2044) is misaligned:

<img width="64" alt="screen shot 2018-04-16 at 11 23 36 am" src="https://user-images.githubusercontent.com/231361/38784619-a35478c4-4168-11e8-9239-b139a41d353d.png">

P.S. I love Fira Code, thank you!

**Comment by tonsky** [comment]
Thanks for reporting!

**Comment by tonsky** [comment]
Fixed in aa6c914
