### ISSUE TITLE
Not show correctly in Intellij IDEA

### ISSUE THREAD

**Issue by Elia0107** [tonsky/FiraCode#589]
I use currently it on vscode, it's fantastic, and I want to use it on intellij Idea. But when I go to select font, it's displayed like
![screenshot 2](https://user-images.githubusercontent.com/23265980/39174986-745f6cda-47a9-11e8-920e-dfd13fc28c39.png)

Why??

**Comment by tonsky** [comment]
It’s a known issue with Windows/IntelliJ. Added section to wiki: https://github.com/tonsky/FiraCode/wiki#corrupted-font-in-intellij-on-windows

**Comment by nfekete** [comment]
The referred content is available under a new URL: https://github.com/tonsky/FiraCode/wiki/Troubleshooting#corrupted-font-in-intellij-on-windows
