### ISSUE TITLE
Ligature for !==

### ISSUE THREAD

**Issue by ai** [tonsky/FiraCode#59]
Fira code has liagtures for `===` and `!=`, but not for `!==`.

@tonsky I think `!==` it is important, because any JS llinter force you to use it.

**Comment by gusaiani** [comment]
@ai In another thread, it was clarified there already is a ligature for `!==`.
In Atom, for example, the default js language package doesn't map to it, but the jsx package does (it screws up mapping to `=>` in certain situations, though :(

**Comment by ai** [comment]
Maybe we should put a issue somewhere? Do you know a source of issue?

**Comment by gusaiani** [comment]
@ai I don't know at the moment.

**Comment by engelfrost** [comment]
Opened an issue here: https://github.com/atom/language-javascript/issues/259

As a workaround you can switch from *language-javascript* to *language-babel*.

**Comment by ai** [comment]
This issue is already fixed in Atom 1.3-beta

**Comment by ai** [comment]
![krbqfu2](https://cloud.githubusercontent.com/assets/19343/11243094/ad3f0d28-8e0e-11e5-9168-9761ec84d051.png)

**Comment by engelfrost** [comment]
:smile:
