### ISSUE TITLE
Some lowercase letters are serif

### ISSUE THREAD

**Issue by Steven-Harris** [tonsky/FiraCode#590]
This is really knit picking but I didn't see it in any of the other issues...

I noticed that the lowercase "r" and "i" are serif instead of the san-serif like the rest of the font.

**Comment by j-f1** [comment]
So are `l`, `i`, `j`, `I` and `J`.

**Comment by tonsky** [comment]
It comes from Fira Mono. They eventually decided to add serifs, otherwise it was too easy to confuse it for `i` (or `y`? I don’t remember)
