### ISSUE TITLE
Ligatures `{|}` and `[|]` render incorrectly

### ISSUE THREAD

**Issue by blucell** [tonsky/FiraCode#593]
After adding `{|`, `|}`, `[|`, and `|]` at release 1.205, ligatures `{|}` and `[|]` render incorrectly as per the following screenshot.

![screen shot 2018-05-01 at 12 32 15 pm](https://user-images.githubusercontent.com/4368958/39470030-c07b96b0-4d3b-11e8-97b2-a480baf39c8b.png)

**Comment by derekjones** [comment]
This also affects some regex patterns. For example, splitting a string by commas or pipes `/[,|\|]/`

<img width="128" alt="screen shot 2018-06-06 at 5 11 46 pm" src="https://user-images.githubusercontent.com/763613/41071472-ba03371a-69ac-11e8-92a5-b305dcba710b.png">
