### ISSUE TITLE
Choco package for windows

### ISSUE THREAD

**Issue by rloic** [tonsky/FiraCode#597]
Hi, I've installed FiraCode with choco for Windows. But I see that's we cannot choose between the OTF and the TTF format. When I install the fonts with the package manager the fonts are a not well displayed as the TTF format. May you add some options to choose between the two formats or duplicare the package like firacode-ttf.

The font is awesome. Thanks =)

**Comment by tonsky** [comment]
I’m not really maintaining that package. But Windows version should definitely contain ttf, not otf
