### ISSUE TITLE
Ligature request: Compound assignment operators

### ISSUE THREAD

**Issue by ulope** [tonsky/FiraCode#598]
Support for all compound assignment operators would be nice.

For Python those are:
```python
+=   # Addition
-=   # Subtraction
*=   # Multiplication
**=  # Power
/=   # Division
//=  # Integer division
%=   # Modulo
|=   # Or
^=   # Xor
&=   # And
<<=  # Left shift
>>=  # Right shift
@=   # Matrix multiplication (only used in third party packages)
```

**Comment by tonsky** [comment]
Thanks for assembling the list! The problem with most of these is that it’s hard to figure out a good visual representation that makes sense, does not obscure original characters too much and is valuable enough.

I believe we already have `/=` `^=`, `<<=`, `>>=` and `|=`

**Comment by BStudent** [comment]
Block diagram?   
![image](https://user-images.githubusercontent.com/19792522/40246140-81c614ba-5a7c-11e8-9bfb-7e4da9133c7f.png)
where op is an operator, such as:
![image](https://user-images.githubusercontent.com/19792522/40246149-882cb7e6-5a7c-11e8-825b-451c8d069864.png)
or
![image](https://user-images.githubusercontent.com/19792522/40246154-8e26b11a-5a7c-11e8-9fa0-a9874fa26aad.png)
... only not ugly / lame.

**Comment by tonsky** [comment]
heh, thinking out of the box :)

**Comment by BStudent** [comment]
Or plagiarizing my old digital filters textbooks.  Wrong-ly i might add, now that I look at it.
