### ISSUE TITLE
Add support for --> operator

### ISSUE THREAD

**Issue by Lazin** [tonsky/FiraCode#6]
There is a common idiom in C and C++

```c++
for(int i = N; i --> 0;) {
    ...
}
```
This code looks ugly with FiraCode. Maybe it is possible to add corresponding ligature for this?

**Comment by tonsky** [comment]
Oh, that’s not an idiom, it’s more like an ASCII art :) Anyway, I’ll look into it

**Comment by tonsky** [comment]
Added `-->` and `<--` in 0.2

**Comment by tonsky** [comment]
BTW added two more “C” “idioms”: `-~` and `~-`
