### ISSUE TITLE
Can you make the `r` look better?

### ISSUE THREAD

**Issue by pakLebah** [tonsky/FiraCode#601]
Fira Code is the best font for writing code (programming). My only complaint is the `r` looks weird compare to other letters. Can you make the `r` looks better? I mean make it as sans-serif like the other letters, instead of being the only serif letter in the group.

Thank you.

**Comment by tonsky** [comment]
It has its form for legibility reasons. Maybe I’ll return alternative form as a stylistic subset one day, thanks for the reminder!

**Comment by pakLebah** [comment]
IMO, the current `r` is anything but legibility. Just look at the provided codes in the readme. The `r` seems out of place. I even notice it since the first time I tried this font. I love its ligatures though. So, I just ignore it but somehow it still annoys me. I wish I could replace it myself with something from Consolas or something. 😊

**Comment by abductedMind** [comment]
The "r" is not particularly in need of increased legibility. Currently it stands out like a sore thumb. My cooworker when shown Fira said hmm....looks cool...oh wait! Thats what the "r" looks like? Nope not doing it. Nevermind. I'm in the same camp.

**Comment by whenov** [comment]
Noto Sans Mono seems has [the same problem](https://github.com/googlei18n/noto-fonts/issues/1126).

**Comment by brilliantly-insane** [comment]
This issue is the one thing keeping me from using Fira Code as my main font. The lowercase `r` throws off the whole aesthetic. I've never had any problem with `r` being legible, except maybe in handwriting.

We need either a new `r` glyph or an alt-style with a sans-serif `r`.

**Comment by j-f1** [comment]
@brilliantly-insane How about dropping the serif on the left side of the r too?

**Comment by brilliantly-insane** [comment]
@j-f1 Agreed; thought it _might_ fir with the `l` and `J` characters, for example, but it doesn't work for the `r`.

**Comment by pakLebah** [comment]
Yup. I think the `r` should be made completely sans-serif. And please make it the same for every style (italic, bold, light, etc). Thank you. 😊

**Comment by fatjoem** [comment]
The r is keeping me and my colleagues from using this font. I never encountered someone that actually likes the current r in this font.

**Comment by kumarharsh** [comment]
FWIW, the `i` is also in the serif style.

![image](https://user-images.githubusercontent.com/760112/50137335-e1fde500-02c0-11e9-9079-6ffbf4d38ff1.png)

**Comment by abductedMind** [comment]
There are a few other traditional serifs such as the i j L, however the r is unusual for an r. Perhaps it would look right if the curved width was 10% wider or we had been used to seeing it in other fonts. Almost all serifs are horz, the r has the only one vertical. I mean if for the r why not for the c as well? or s or z or 7? The point is that the r stands out. The r is not harmonious.

**Comment by tonsky** [comment]
It isn’t. Originally r didn’t have serifs. Those were added because people complained about low legibility. r without serifs used to look like lowercase i. If you dig deep enough I guess you can find the original r in oldest Fira Mono files

**Comment by tonsky** [comment]
https://github.com/mozilla/Fira/issues/49

**Comment by abductedMind** [comment]
Yes, important link above. Note that people immediately complained about the result in that issue. Its a real SHAME that an "issue" with the r was the resolved this way, when this issue should be an issue for the majority of all semi-serif fonts, yet its not? It wasn't a real issue then, and now we have an ugly r.

**Comment by aNickzz** [comment]
@diplomatic-dev how did you go with that?

**Comment by byoungju94** [comment]
I think fira code is the best font for intellij and windows console!

but i agree "r" looks awkward...

**Comment by Al2Me6** [comment]
Another viewpoint (possibly unpopular):

To me, the `r` is the one glyph that truly sets the font apart. While it is indeed quirky and unconventional, it's also one of the things that make the font instantly recognizable. 

However, that is not to say the glyph looks good from a useability perspective. I feel like removing only the offending serif and keeping the body in the same form as the current `i` would be the best compromise to make.

**Comment by alexdreptu** [comment]
I'm mainly using `Source Code Pro` / `Hasklig` and I tried so many times to use `Fira Code` but couldn't even manage to have it set for a few days. It has many good parts but the `r` makes the code look unpleasant when I scan it with my eyes. This single glyph can make whole lines of code look displeasing.

**Comment by kisarid** [comment]
+1, please add a sans `r`. Fira Code would be my favorite font if it wasn't for that `r`

**Comment by radu-b** [comment]
I stopped seeing it after a week, now it looks just normal. The designers, having looked at it for years, must think: what do these people have against a perfectly normal r?

**Comment by steebchen** [comment]
Am I the only one who likes the r?

**Comment by ollicle** [comment]
@steebchen you are not alone. I don’t believe it needs defending.

**Comment by MartinHaeusler** [comment]
I vote for a truly sans-serif version of Fira Code. It has become my favourite coding font, but the serifs look extremely odd, even more so on a 4k monitor with more pixels available for font rendering. Most notably, `r` and `ì` could use a sans-serif treatment, maybe `l` (lowercase L) too. `g` is also a bit too playful for my taste.

**Comment by Melkster** [comment]
How do I easiest get the version of FiraCode with sans-serif `r`? Is it exclusively through [stylistic sets](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets), or is there an already patched version of the font available somewhere? I'm asking because my editor currently doesn't have built-in support for stylistic sets.

**Comment by alexeyten** [comment]
> How do I easiest get the version of FiraCode with sans-serif `r`?

There's a tool [OpenType Feature Freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer/).

With it you could patch the font yourself.

E.g. `pyftfeatfreeze -f SS01 -S FiraCode-Regular.ttf FiraCodeSS01-Regular.ttf`

**Comment by Melkster** [comment]
@alexeyten Thanks, I'll give that a try!
