### ISSUE TITLE
New request

### ISSUE THREAD

**Issue by RustemB** [tonsky/FiraCode#602]
I know that it may be so hard to realize and not everyone will use it, but can you make italic style?
(sorry for my english if you don't understand what I am write)

**Comment by tonsky** [comment]
Sorry, it’s been asked couple of times, but I’m not really a font designer, I’m just not capable enough pull such a big work off

**Comment by j-f1** [comment]
That’s a fake italic version, usually dynamically generates by skewing the necessary characters before rendering them.

**Comment by BStudent** [comment]
Aha!  Thank you, @j-f1 today I have learned a thing:
Fake italics - _/* good enough for comments */_ - leave @tonsky free to work on ligatures unavailable in any style...  for example, a ligature to replace the monstrous and hideously deformed atrocity that is the R pipe operator (`%>%` - which I believe is already on the list).  
Funny thing is that the R pipe did not start looking like shame and despair incarnate until I started using  fira code, but now the bar is set high.
