### ISSUE TITLE
Bold doesn't work in Sublime, how to make regular and bold single?

### ISSUE THREAD

**Issue by codharma** [tonsky/FiraCode#603]
Hello. I installed both - Regular and Bold. In Sublime I can use both separately by choosing `Fira Code` or `Fira Code Bold`.

But I want Sublime to use Fira Code both. For example for hightlighting text. It works with system fonts. But it is not working for Fira Code, which is very frustrating.

How to make Regular and Bold as a single font?

**Comment by tonsky** [comment]
There’s no special setting. Just install both and Sublime should render
both. Works for me (macOS, Sublime 3.1)

**Comment by codharma** [comment]
@tonsky you are right. I just had to restart OS. Sorry for disturbing!
