### ISSUE TITLE
Jupyter notebook - Simple ligatures >= and <= not rendering in code cells

### ISSUE THREAD

**Issue by shivendra90** [tonsky/FiraCode#604]
I would like to confirm if the >= and <= ligatures are rendering properly in a normal Jupyter notebook. I'm using the latest release of Fira Code in regular format. All ligatures rendering properly in Spyder IDE as well as RStudio but there seems to be some conflict in a Jupyter environment. Any possible fixes?

**Comment by tonsky** [comment]
Please report it to the program authors. Nothing I can fix in font :(
