### ISSUE TITLE
Monospacing Error

### ISSUE THREAD

**Issue by robbitay** [tonsky/FiraCode#607]
I have Fira Code selected as my font in Sublime Text and I ran into a weird scenario today where it seems that mono spacing get's out of sync. The image below is a screenshot from sublime text that shows two lines. One has numbers, one has square brackets. Each square bracket should line up with the number below it but as you get farther down the line the square brackets become more and more offset to the right until by number 46 it is a full character width different. Maybe I am missing something but this seems like a problem with one of the square bracket characters being too wide. Or maybe there is a ligature [] that is more than 2 character widths?
![monospacingerror](https://user-images.githubusercontent.com/20048972/40800411-9788b1bc-64cd-11e8-8bad-6a5a47c254f4.png)

**Comment by tonsky** [comment]
There’s no `[]` ligature in Fira Code. Please report this issue to the Sublime team

**Comment by wopian** [comment]
I can reproduce this in VSCode on font size 12 with v1.205

**Comment by tonsky** [comment]
Ok I can confirm. It’s certainly a bug in Fira Code, should be easy to fix. Thanks!
