### ISSUE TITLE
Combining overline diacritic

### ISSUE THREAD

**Issue by bwiernik** [tonsky/FiraCode#608]
Can you add support for the combining overline diacritic (U+0305)? For example: r̅

I use this character for the mean of a variable when typesetting simple math using Markdown. Currently, Fira Mono and Fira Code seem switch to displaying in Courier (on Windows) when this diacritic is used. The similar combining macron diacritic (U+0304) is supported well already: r̄

**Comment by tonsky** [comment]
Sure, shouldn’t be a problem. Thanks!

**Comment by bwiernik** [comment]
I'm not sure if it's helpful, but the FiraGO version of FiraSans has implemented U+0305 well:
https://github.com/bBoxType/FiraGO

**Comment by Philippus** [comment]
works great for representing big roman numerals (I̅ V̅ X̅ L̅ C̅ D̅ M̅) as well, thanks!
