### ISSUE TITLE
'>>' ligature is rendered lower than '<' in IntelliJ

### ISSUE THREAD

**Issue by riesinger** [tonsky/FiraCode#609]
See this screenshot for reference:

![image](https://user-images.githubusercontent.com/6919894/40965682-b58dd612-68ae-11e8-9b25-1741e31b7d72.png)

This looks really ugly and I don't think this is intended

**Comment by tonsky** [comment]
thx, I’ll look into it

**Comment by tonsky** [comment]
Is this windows? Other letters seem destroyed as well. `>>` has slightly different height, I think aggressive hinting moves it that much down. In the font it’s perfectly centered with `<`

**Comment by riesinger** [comment]
@tonsky Yes, I think this was done on windows, cannot remember for sure anymore, sorry 😅
