### ISSUE TITLE
Wrong ligature for ?:

### ISSUE THREAD

**Issue by lbguilherme** [tonsky/FiraCode#61]
I'm using Atom 1.1 with Fira Code (It's awesome!), but I noticed `?:` renders to a quite odd symbol.

This is the plain text:

```
type U = {
    aaa?: string // ?: means an optional property
    bbb?: number
}

function F(aaa?: string, bbb?: number) {
    // ?: means an optional parameter
}
```

Here is what I see:

![](http://lbguilherme.com/screenshot/7ce4f657dc96e82a22071fff02a0f8eb.png)

This strange ligature symbol makes no sense to me, it would be better to have no ligature at all here.

**Comment by tonsky** [comment]
I know, I’ll remove it in the next version. If you’re curious why it was
there in the first place, `:?` is called [Elvis operator](
https://en.wikipedia.org/wiki/Elvis_operator)

**Comment by kornosaurus** [comment]
:+1:

**Comment by Dervisevic** [comment]
+1

**Comment by MadcapJake** [comment]
`?:` is also used in regex for non-captured groups.

In any case, a ligature for `?:` isn't exactly a bad idea but perhaps maybe just a condensed form like what is used for `?=`.  (Sidenote: what is that symbol and where did it come from? o_0 )

**Comment by mnowak32** [comment]
@MadcapJake The symbol is clearly a portrait of Elvis... ;)

**Comment by tonsky** [comment]
Removed in 1.000
