### ISSUE TITLE
Font works on Alacritty

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tonsky/FiraCode#610]
I've using this great font for months on Alacritty so I was surprised to read in the read me that it doesn't work. Is there anything I could test to prove it works?

**Comment by filipebarros** [comment]
Alacritty doesn't support ligatures, you can use this font in alacritty but you won't see any ligatures

**Comment by tonsky** [comment]
Yes. Works == supports ligatures, which are the main value added by Fira Code

**Comment by Thomasdezeeuw** [comment]
That is good point forgot about that, sorry for the noise.
