### ISSUE TITLE
Blinking rendering issue in PowerShell with certain characters (≡)

### ISSUE THREAD

**Issue by stamminator** [tonsky/FiraCode#612]
In PowerShell, if Fira Code is set as the font, an annoying blinking effect takes place when certain characters are rendered, and the rendered result is incorrect. This is a problem for the commonly-used PowerShell module posh-git

![posh-git fira code render issue](https://user-images.githubusercontent.com/10633170/41246984-a6a8f016-6d7a-11e8-9851-0b79b60a5191.GIF)

> Notice how the `≡` symbol is unable to be rendered, resulting in the blinking effect and the incorrectly rendered symbol.

Note: This is not a problem for built-in typefaces like Consolas or others

**Comment by tonsky** [comment]
Probably should be reported to PowerShell developers. I doubt I can do anything here

**Comment by stamminator** [comment]
Thanks for the quick reply @tonsky. Please re-open this, as it's an issue specific to Fira Code. Other fonts, like the built-in ones, as well as external ones like [Hack](https://sourcefoundry.org/hack/), do not have this issue.

**Comment by tonsky** [comment]
This is an issue _with PowerShell_ that’s specific to Fira Code, sure, still it must be opened there, not here

**Comment by stamminator** [comment]
If anyone else stumbles across this same issue, the problem was solved when I uninstalled the OTF format font and reinstalled using TTF
