### ISSUE TITLE
Bug in with |>= notation used in composer.json

### ISSUE THREAD

**Issue by borisson** [tonsky/FiraCode#615]
For composer, there is possiblity to use different kinds of platfrom requirements.

For example: `"php": "^5.5.9|>=7.0.8"`. In this case, it should be interpreted as `^5.5.9 | >=7.0.8`. The ligature should be on `>=`, currently it is on `|>`.

It would also be fine to ignore the ligature in this case.

![screen shot 2018-06-14 at 11 01 45](https://user-images.githubusercontent.com/1721156/41402339-5c7c38c8-6fc2-11e8-951d-9d6fb477dcd5.png)

**Comment by tonsky** [comment]
thx for reporting!

**Comment by tonsky** [comment]
Should be fixed in 1.206
