### ISSUE TITLE
$, & and @ (and maybe <= and >=)

### ISSUE THREAD

**Issue by Vampire** [tonsky/FiraCode#617]
I just started using Fira Code.
It is really great having those font ligatures.
But I actually dislike how $, & and @ look there.
I found that your work is based on Fira Mono.
Now I have seen that in normal Fira, these look nice and only look unnice in Fira Mono:
![grafik](https://user-images.githubusercontent.com/325196/41925505-0e2394aa-796d-11e8-930e-89f049704fbc.png)
I created an issue for Fira, but now found that the font is not developed any further but got abandoned.

Would it be possible to change the Fira Code ones to look more like the ones in normal Fira?
Or maybe as variants like it is for [Monoid](https://larsenwork.com/monoid/) where you can select different representations for some characters on download?

If such choices get implemented also <= and >= would be candidates, so that the two bottom lines or maybe only the bottom line are horizontal and not angeled. :-) I somehow feel ![grafik](https://user-images.githubusercontent.com/325196/41926016-6e621e9e-796e-11e8-8cab-545e48477a20.png) or ![grafik](https://user-images.githubusercontent.com/325196/41926384-78ffb02c-796f-11e8-85b6-cfc35c8122a7.png) look better than ![grafik](https://user-images.githubusercontent.com/325196/41926495-d2f693a2-796f-11e8-8d19-159bc35b4e08.png), but that is a matter of taste of course.

**Comment by j-f1** [comment]
For the `<=` ligature, I believe it looks the way it does to avoid problems with differentiating between it and the actual `≤` character.

**Comment by tonsky** [comment]
If I ever implement a system that would allow you to pick different variant these would be among the first one yes. Thanks for the suggestion

**Comment by Vampire** [comment]
In what rough timeframe would "ever" be? :grin:

If the tool you use wouldn't cost that much money I'd probably look into how complex it is to change this for me, but if it only works for 30 days, it is not feasible to start this and then not being able to rebase onto new updates.

I never touched any font files, is it hard to do theses changes and if not selectable like for Monoid, maybe with different pre-compiled variants? 

(While I guess it is pre-compiled for Monoid too and the selector just decides which file to download.)

**Comment by Vampire** [comment]
If I could do anything to help you support this (besides buying Glyph2), I might do so maybe.

**Comment by Vampire** [comment]
For anyone interested, here are the 1.205 FiraCode TTF variants with the `$`, `&` and `@` standard glyphs and the `<$`, `<$>`, `$>`, `<=`, `>=` and `&&` ligature glyps replaced.

I think the `$`-based and `=`-based and the `&&` look quite nice even in detail.

For the `&` and `@` I basically took the respective FiraSans versions and made them narrower to fit in the monospace width, so in detail they look a bit shitty, but for normal sizes that are used when writing or reading code the niceness is acceptable. :-)

[FiraCode-TTF-with-replaced-glyphs.zip](https://github.com/tonsky/FiraCode/files/2144743/FiraCode-TTF-with-replaced-glyphs.zip)

**Comment by mickeyl** [comment]
@Vampire Thanks for your contribution, that's great. I'd like to add them to my fork. Could you share your modifications in source form?

**Comment by Vampire** [comment]
Nope, I used a font editor to edit the TTFs by hand, so I don't have any source modifications. All I have is the TTFs.

**Comment by 853419196** [comment]
@Vampire I think this is a great suggestion and I hope that your proposal can be taken seriously and implemented.

**Comment by Vampire** [comment]
Great @tonsky, much thanks.
When can we expect a version with these changes?
I'm eager to have a look. :-)

**Comment by tonsky** [comment]
Hope to get it out there in a few days

**Comment by Vampire** [comment]
Another question, does the "stylistic sets" mean you now did the `system that would allow you to pick different variant` you mentioned, or did you just hard changed the glyphs for all?

**Comment by j-f1** [comment]
I believe it’s the former.

**Comment by Vampire** [comment]
Ah, I see, stylistic sets are a feature of the font files.
I hope these can be selected on download, I see neither in Firefox, nor in IntelliJ IDEA an option to select stylistic sets.
Or I misunderstood how those are used / applied.

**Comment by tonsky** [comment]
Stylistic sets are variants of glyphs embedded into the font under different names. They co-exist with the default glyphs, which I didn’t change. Some apps let you choose which sets you want to enable.

In CSS:

```
font-feature-settings: "ss01", "ss02";
```

In Sublime Text:

```
"font_options": ["ss01", "ss02"]
```

In some Apple apps:

<img width="454" alt="Screenshot 2019-09-03 at 16 49 46" src="https://user-images.githubusercontent.com/285292/64178997-0f98b780-ce6b-11e9-8091-34eab83ca288.png">

In VS Code:

Via editing `ectron-browser/index.html` https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

Adobe apps, MS Word etc:

https://www.macworld.com/article/3052388/how-to-access-advanced-opentype-features-in-a-variety-of-mac-apps.html

Customizing font on download would be a much better solution but it requires much more effort to implement. One day I hope to get there.

**Comment by Vampire** [comment]
Is there maybe some tool that could enable those stylistic sets per default you are aware of or similar?
As I said, neither Firefox, nor IntelliJ IDEA which are the two main tools where I use the font have such a setting as far as I can see.

**Comment by mickeyl** [comment]
„Customizing font on download would be a much better solution“. I disagree – Stylistic Sets are exactly the right Choice for such a feature. For some users, a customizable download may be better, but not in general.

Thanks for implementing this the right way!

**Comment by Vampire** [comment]
I didn't say it is not the right way, I just said it would be nice for usage in software where you cannot enable stylistic sets.
I found https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze which might do what I want.

**Comment by Vampire** [comment]
Actually in Firefox I use a userscript anyway to force FiraCode for websites, so there I could actually use the stylistic sets probably.

**Comment by Vampire** [comment]
@tonsky you missed the `<$`, `<$>` and `$>` ligatures for the `ss04` and shouldn't maybe the `&&` with `ss03` look more like ![grafik](https://user-images.githubusercontent.com/325196/64573571-09737100-d36c-11e9-8960-7034316d5271.png) than like ![grafik](https://user-images.githubusercontent.com/325196/64573599-2b6cf380-d36c-11e9-9395-b3d9fb30d6ef.png)?
