### ISSUE TITLE
Bold 'slash asterisk' glyph has wrong weight

### ISSUE THREAD

**Issue by ewirch** [tonsky/FiraCode#619]
See https://youtrack.jetbrains.com/issue/IDEA-194282 for reference.

The normal weight version of "/*" is rendered like this:

![image](https://user-images.githubusercontent.com/1880345/41956480-0d76864e-79e4-11e8-876a-4304c66061e8.png)

The bold version of the same string is rendered like this:

![image](https://user-images.githubusercontent.com/1880345/41956497-1d4b6544-79e4-11e8-901e-068ef2915c6c.png)

**Comment by tonsky** [comment]
Fira Code `/*` ligature looks fine in all apps and in all widths on macOS. Something with Linux I guess

**Comment by ewirch** [comment]
May be I should have told the font weight which I use. I use "Fira Code Light". This is how Fira Code regular looks in LibreOffice Writer on Linux:
![image](https://user-images.githubusercontent.com/1880345/41971977-9ccde432-7a10-11e8-935a-781b7b30c9af.png)

And this is Fira Code Light in LibreOffice Writer:
![image](https://user-images.githubusercontent.com/1880345/41972049-d4a9d870-7a10-11e8-99d9-9953b6c70966.png)

**Comment by tonsky** [comment]
As it is an issue with generated bold version rather with the font provided by Fira Code, closing this

**Comment by ewirch** [comment]
Could you explain? So the font package does not provide a bold version of itself, and instead the system generates a bold version of the regular Fira Code font?

**Comment by tonsky** [comment]
Well I read the explanation in the IDEA ticket, I haven’t verified it myself. Apparently if you select Light as your main font it has to build bold version based on what it have.

**Comment by ewirch** [comment]
In my comment above I wrote that it also occurs for LibreOffice. Its not a IntelliJ IDEA problem.

My assumption was that 'Fira Code Light' is a bundle and that it provides regular, italic and bold versions. Is this assumption wrong?

**Comment by tonsky** [comment]
As Dmitry Batrak mentioned in Jetbrains tracker, it’s probably FreeType problem.

Fira Code is a package that provides 5 weights: Light, Regular, Retina, Medium and Bold. You seem to only have Light (?) and treat it as Regular, with Bold generated on the fly (again, as per Dmitry’s comment).

How did you install Fira Code btw?

**Comment by ewirch** [comment]
Fira Code is bundled with IntelliJ IDEA. It allows me to select any of the 5 font weights. I simply prefer to read the light version.

To reproduce this with LibreOffice I installed the `otf-fira-code` [Arch Linux package](https://www.archlinux.org/packages/community/any/otf-fira-code/). But, when I try to reproduce this now, there is only one 'Fira Code' font. No 'Light' light version to select any more. Maybe the packaging changed. So, I can't reproduce this with LibreOffice any more due to lack of 'Light' version.

Thanks for the hint with the FreeType project. I'll open a bug report with them.
