### ISSUE TITLE
Ligature for ~> (wavy arrow)

### ISSUE THREAD

**Issue by pmros** [tonsky/FiraCode#62]
It would be nice if FiraCode had a ligrature for ~> (wavy arrow). [LiveScript](http://livescript.net/) use wavy arrows.

Thank you for FiraCode!

**Comment by patmead** [comment]
Also used in the latest version of PHP (just released today!)
https://wiki.php.net/rfc/short_closures

**Comment by tonsky** [comment]
Added in 1.000. Thanks!
