### ISSUE TITLE
<||> rendering incorrectly (haskell)

### ISSUE THREAD

**Issue by emptyflask** [tonsky/FiraCode#621]
Screenshot from Vim:
![image](https://user-images.githubusercontent.com/28287/42197777-05cecd38-7e4a-11e8-806e-297c3df6ee71.png)

TBH I'm not sure what the best ligature for this would be. Double triangles? None at all?

**Comment by tonsky** [comment]
Yeah, thanks. Should be resolvable :)

**Comment by dkasak** [comment]
Probably not double triangles since that would imply the grouping `<|` + `|>` whereas the intended grouping is `<` + `||` + `>`.

**Comment by tonsky** [comment]
Yeah I think I’ll just disable ligaturing for that case specifically
