### ISSUE TITLE
|. operator

### ISSUE THREAD

**Issue by ghivert** [tonsky/FiraCode#623]
Hi !

In elm, in our parser, we got `|.` used with `|=`. While the second is already there, the first is not.

Example:

```elm
test =
  Parser.succeed Constructor
    |= keep oneOrMore isChar
    |. end
```

**Comment by wopian** [comment]
Duplicate of #613

**Comment by ghivert** [comment]
Oh, my bad. I tried the search, but couldn't find it...

**Comment by wopian** [comment]
Yeah GitHub's search is pretty useless for finding operators, as many of the characters are considered wildcards and get ignored.
