### ISSUE TITLE
Regex groups

### ISSUE THREAD

**Issue by whatisaphone** [tonsky/FiraCode#624]
First off, thanks for putting together this font, I've been using it for years and I love it! 😃 

It would be nice if the font worked a little better with regex. Here are a few types of regex groups:

```
(?=
(?!
(?<=
(?<!
```

![](https://i.imgur.com/DgIb4vY.png)

In FiraCode they are rendered very inconsistently. Some have ligatures, some don't. `(?<=` is particularly bad since it groups the `<=` as something semantically unrelated while leaving the `?` out to dry. That one throws me off every time I see it. I'm not even asking for more ligatures 😅 but it would be a definite improvement to force those specific sequences to always stay independent. I hope  `(?` is unique enough that it can always be assumed to be part of a regex.

Here is a hopefully complete list ([Source](https://www.regular-expressions.info/refquick.html)). I've only noticed this issue with syntax that starts with `(?` so those are the only ones I included (and wow, there are way more of them than I thought)

```
(?:
(?<
(?'
(?#
(?|
(?>
(?=
(?!
(?<=
(?<!
(?(?=
(?(
(?(<
(?('
(?(<<<digit>>>
(?(-
(?(+
(?&
(?P<
(?P=
(?P>
(?R)
(?<<<digit>>>
(?-
(?+
```

**Comment by tonsky** [comment]
Thanks for the list! I’ll try disabling ligatures after `(`, that should help

**Comment by johnsoft** [comment]
Did you mean `(?`? Disabling after just `(` won't help the `(?<=` case, and also seems too broad – it would break `16 (0x10)` and `Google (www.google.com)`.

**Comment by tonsky** [comment]
Not all ligatures, only ones that conflict with groups in regexps
