### ISSUE TITLE
Make Microsoft Office have ligatures support

### ISSUE THREAD

**Issue by abc1236762** [tonsky/FiraCode#625]
I set ligatures to all and it still have no ligatures.
![default](https://user-images.githubusercontent.com/11353779/42430823-39854024-8374-11e8-9933-14fd2fc01b32.png)

**Comment by tonsky** [comment]
I’m not sure Word supports ligatures at all. The feature I’m using in Fira Code is called `calt` (contextual alternates), see if you can find it in settings?

**Comment by abc1236762** [comment]
I found [this article](https://msdn.microsoft.com/en-us/vba/word-vba/articles/font-contextualalternates-property-word) and try to do
> Setting this property has the same effect as selecting the check box next to Use Contextual Alternates (in the OpenType Features group, Advanced tab, on the Font dialog in Word).

but it still not working.

**Comment by wopian** [comment]
You need to enable the `Use Contextual Alternatives` checkbox:

![](https://i.imgur.com/VNghtIw.png)

**Comment by atheistray** [comment]
你要勾「使用上下文替代字（contextual ligatures）」，Fira Code的連字是看前後文的，比如說連續出現好幾個=，就會換成其他連字等等。

**Comment by abc1236762** [comment]
@atheistray 我在上則留言就講說我這邊這樣做沒有效果，應該就是我的office有問題
@wopian I think that is my Office's problem.

I tried on Office 2019 preview at the beginning and not worked, but I tried again on Office 2016 and worked, it seems it's a bug on Office 2019 preview not FiraCode's problem.

**Comment by msberends** [comment]
> 你要勾「使用上下文替代字（contextual ligatures）」，Fira Code的連字是看前後文的，比如說連續出現好幾個=，就會換成其他連字等等。

Translation from Chinese: You have to tick the box "Use contextual ligatures", the hyphenation in Fira Code depends on the context, e.g. if several ='s appear in a row, they will be replaced by other hyphens etc.

> @atheistray 我在上則留言就講說我這邊這樣做沒有效果，應該就是我的office有問題

Translation from Chinese: 

@atheistray I said in my last comment that this didn't work for me, so I guess there is something wrong with my Office.

----

Please communicate in English on GitHub, e.g. by using a service such as https://www.deepl.com - you might be able to help others like me with your comments 🙂
