### ISSUE TITLE
horizontal unicode arrow width

### ISSUE THREAD

**Issue by AdmiralSnyder** [tonsky/FiraCode#626]
almost all of the Unicode arrows e.g. here https://unicode-table.com/de/sets/arrows-symbols/ look good with fira code even on normal scaling (size 10, 100%)
but due to the one-character-width - restriction, some arrows don't get painted well. the most prominent example in my opinion is the \mapsto symbol ↦ which remains unreadable unless zooming in ~130%

Could it be considered to make the horizontal arrow slightly wider?

**Comment by tonsky** [comment]
This would be a huge breaking change, as it’ll make Fira Code not a monospaced font anymore. On the other hand, I doubt anyone uses Unicode arrows for real coding, so maybe this change might be ok after all. I’ll think about it

**Comment by tonsky** [comment]
related: https://github.com/tonsky/FiraCode/issues/677
