### ISSUE TITLE
some unicode characters are not displayed in cmd while working in e.g. visual studio or notepad.

### ISSUE THREAD

**Issue by AdmiralSnyder** [tonsky/FiraCode#627]
this should not be a problem with the ligature stuff. the characters problematic for me are
⟦ and ⟧ (square double brackets)
i don't think this is a cmd problem, either, because e.g. SimSun-Ext B displays them correctly (but quite ugly)
Encoding also shouldn't be the reason, copying stuff off of that cmd window works fine.

strangely, Consolas also has this problem, in cmd they don't get displayed property, yet in notepad they do.
any ideas?

**Comment by tonsky** [comment]
These are not in the font. I guess CMD can’t display fallback font in that case
