### ISSUE TITLE
Proposal to add ponys receiver chaining operator

### ISSUE THREAD

**Issue by erazor-de** [tonsky/FiraCode#630]
Hi,
the programming language [Pony](https://www.ponylang.org/) introduces the operator .> which one might call a [chaining operator](https://tutorial.ponylang.org/expressions/methods.html#chaining). Maybe you want to support this with optimized spacing?

**Comment by tonsky** [comment]
Well, `.)` `.]` were not successful due to conflicts (https://github.com/tonsky/FiraCode/issues/264), I’m worried this may cause something like that (although this is different, so I’ll have to think about it)

**Comment by erazor-de** [comment]
You are right, on second thought it's no good idea. One example is C which lets me write a float comparison like 2.>1.
