### ISSUE TITLE
Instructions to enable font in only <code> to be displayed in Fira in browsers

### ISSUE THREAD

**Issue by adityasrini** [tonsky/FiraCode#632]
I see installation instructions to display code for various IDEs but don't see any instructions for doing that in browsers. To be clear, I'm not talking about enabling Fira everywhere, just the code in `<code>` or `<tt>` or `<pre>` tags. I know of a way to do this in Safari but I had to learn the hard way when js scripts constantly rewrite custom stylesheet settings. If I were a newbie, I'd like this to have known this in advance.

Would I be able to do a PR against this with instructions for Safari (for now)?

**Comment by tonsky** [comment]
not sure what are you talking about. Setting default monospace font in browsers?

**Comment by adityasrini** [comment]
Sort of. Default code or pre font in the browsers.

**Comment by tonsky** [comment]
Like this?
<img width="1281" alt="screen shot 2018-09-25 at 00 04 38" src="https://user-images.githubusercontent.com/285292/45979093-a6070b00-c056-11e8-8176-50116e3398ea.png">

**Comment by adityasrini** [comment]
Yeah stuff like that for other browsers as well. There's a section to do this for code editors and although this may seem relatively straightforward, having a guide may help other users navigate install instructions for browsers that don't let you do this in a straightforward way (like Safari)

**Comment by tonsky** [comment]
Ok. Can you create a new wiki page and put it all there? Thanks!
