### ISSUE TITLE
cannot turn off ligatures on Atom

### ISSUE THREAD

**Issue by HaoyangFan** [tonsky/FiraCode#633]
I am using Atom 1.29.0 which enables ligatures by default, but I want to turn off the ligatures
I tried the way described by [wiki](https://github.com/tonsky/FiraCode/wiki/Atom-instructions#ligatures) to modify the stylesheet of atom, but it doesn't work: my Atom stills show ligatures when I write JS files

my stylesheet:
```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */

/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
    // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
    // color: white;
    // background-color: hsl(180, 24%, 12%);
}

// style UI elements inside atom-text-editor
atom-text-editor .cursor {
    // border-color: red;
}

.syntax--todo,
.syntax--fixme,
.syntax--bug,
.syntax--changed,
.syntax--idea,
.syntax--hack,
.syntax--note,
.syntax--review,
.syntax--nb,
.syntax--question,
.syntax--combak,
.syntax--temp,
.syntax--debug,
.syntax--optimize,
.syntax--warning,
.syntax--xxx {
    // color: limeGreen;
    // background-color: lighten(crimson, 0);
}

atom-text-editor.editor .syntax--string.syntax--quoted,
atom-text-editor.editor .syntax--string.syntax--regexp {
    -webkit-font-feature-settings: 'liga' off, 'calt' off;
}

```

as you can see, I already append 
```
atom-text-editor.editor .syntax--string.syntax--quoted,
atom-text-editor.editor .syntax--string.syntax--regexp {
    -webkit-font-feature-settings: 'liga' off, 'calt' off;
}
```
to the bottom

**Comment by tonsky** [comment]
Have you tried turning it off in settings? They should have one if I remember correctly

**Comment by gusbemacbe** [comment]
What OS are you using, @HaoyangFan ?

**Comment by HaoyangFan** [comment]
@gusbemacbe @tonsky  I am using MacOS 10.13.3

**Comment by gusbemacbe** [comment]
@HaoyangFan 

1) Did you try this code?

```css
atom-text-editor.editor .syntax--string.syntax--quoted,
atom-text-editor.editor .syntax--string.syntax--regexp {
    font-variant-ligatures: no-common-ligatures;
}
```

I link you to the tutorial at Mozilla site: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

2. If not, did you try to clean Atom caches? 

3. If not again, if you want to hold packages and settings, make backup of:

* 'your_name/.atom/packages`
* `init.coffee`, `keymap.cson`, `snippets.cson` and `styles.less`

4. Use MacCleaner or [AppCleaner](https://freemacsoft.net/appcleaner/) and drag and drop the app Atom into this app. BUt uncheck only the app ATom, while everything must be checked to be removed. AFter removing, copy the backup you did to `your_name/.atom/`.

See if the ligatures are off.

**Comment by itsnesky** [comment]
To disable font ligatures place this code inside your stylesheet file:
```
atom-text-editor.editor {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```
