### ISSUE TITLE
Provide font variant with lower height

### ISSUE THREAD

**Issue by svenhaag** [tonsky/FiraCode#634]
I am using IntelliJ coding editor with "Monospaced" font and find it perfect, despite the missing ligatures. I feel that FiraCode is just too tall, so having a variant with lower height would be awesome!

**Comment by tonsky** [comment]
I think the height is just right. Having it smaller would hurt readability

**Comment by svenhaag** [comment]
For me its vice-versa. Personal preference, just like bold, italic, regular, ...
