### ISSUE TITLE
{. ligature looks weird

### ISSUE THREAD

**Issue by dieterguendisch** [tonsky/FiraCode#635]
I have a shell script using some jsonpath argument like `jsonpath='{.status.phase}'`.
Using firacode it looks weird: 
<img width="187" alt="ligature" src="https://user-images.githubusercontent.com/30311254/43647056-d2e2fd3a-9736-11e8-9036-eb62c32eb363.png">

**Comment by GULPF** [comment]
This is a ligature for the [Nim programming language](https://nim-lang.org/). It's really nice for Nim because constructs like `{.pragma.}` is common and looks terrible without the ligature.

**Comment by dieterguendisch** [comment]
Wondering generally how firacode treats things that look nice in one language but look bad in other ones?
But anyway, can I undo/disable this one ligature?

**Comment by tonsky** [comment]
> Wondering generally how firacode treats things that look nice in one language but look bad in other ones?

I usually remove such ligatures is conflict is too commonplace

> But anyway, can I undo/disable this one ligature?

I’m afraid not

**Comment by tkerber** [comment]
Somewhat related, the `.}` ligature looks quite odd in TeX, as often sentences are enclosed by curly braces.

**Comment by krux02** [comment]
I am sad :( I want ``{. .}`` back. I am a Nim developer.
