### ISSUE TITLE
... in vuejs

### ISSUE THREAD

**Issue by corbosman** [tonsky/FiraCode#636]
In Vuejs it's common to make this construct:

```
computed: {
  ...mapGetters(['some_method'],
}
```
The three dots don't look right in fira. They get spaced apart in 2 dots and then a single dot.

**Comment by jdreesen** [comment]
They shouldn't. It sounds like an editor problem. Which one do you use?

**Comment by corbosman** [comment]
PHPStorm,  here is a screenshot:

[http://shot.ter.net/img/201808071336-7eb141b14847b1d907a049240c22089e.png](url)

But I just checked the latest early access version and there it seems fixed, so you're right, seems like an editor bug.

**Comment by jdreesen** [comment]
Strange. This is how it looks for me with FiraCode 1.205 in PhpStorm 2018.2:

![grafik](https://user-images.githubusercontent.com/424602/43776034-ef76ce52-9a4e-11e8-8d59-e50ac344b00b.png)
