### ISSUE TITLE
Ligatures for Quadruple Dash

### ISSUE THREAD

**Issue by iFailatGitHub** [tonsky/FiraCode#640]
Quadruple dashes in comments `# ---- name ----` are used in comments to define a chunk in R. So far `--` and `---` both have ligatures, and I find it kind of strange that `----` doesn't form a ligature.

![image](https://user-images.githubusercontent.com/16273400/44375393-0ff73680-a526-11e8-8662-9589fd9364e0.png)

It would be nice if a ligature would be implemented, if possible.

**Comment by tonsky** [comment]
Thanks for the idea! Although, at this length there’ll be not much difference between ligature and non-ligature version, so as a rule of thumb I decided non to implement quadruple+ -length ligatures
