### ISSUE TITLE
Add #: for Clojure.

### ISSUE THREAD

**Issue by midnio** [tonsky/FiraCode#642]

**Comment by tonsky** [comment]
What does it do?

**Comment by midnio** [comment]
An easier way to declare object-like maps. An example is here:
```clojure
#:person{:first "Han"
         :last "Solo"
         :ship #:ship{:name "Millennium Falcon"
                      :model "YT-1300f light freighter"}}
```
is read as:
```clojure
{:person/first "Han"
 :person/last "Solo"
 :person/ship {:ship/name "Millennium Falcon"
               :ship/model "YT-1300f light freighter"}}
```
More info about #: charatcher: https://clojure.org/guides/weird_characters#__code_code_and_code_code_namespace_map_syntax

**Comment by tonsky** [comment]
Oh, right, namespaced maps. I forgot about that. Thanks, I’ll see what I can do

**Comment by midnio** [comment]
Thanks :p
