### ISSUE TITLE
Ligatures do not work Eclipse

### ISSUE THREAD

**Issue by egold555** [tonsky/FiraCode#647]
None of ligatures work for me in eclipse oxygen 4.7.3a (Most up to date version when writing this)

**Comment by FreHu** [comment]
This is a known issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=398656

However, Oxygen is not the latest release, Photon is. The font does appear to work in Photon, though sometimes the ligatures don't show. I haven't been able to find out why yet.

**Comment by egold555** [comment]
Alright. Thanks.
