### ISSUE TITLE
can't get Fira Code from Ubuntu universe apt repository

### ISSUE THREAD

**Issue by PiotrKieltyka** [tonsky/FiraCode#648]
![screenshot from 2018-08-28 08-41-49](https://user-images.githubusercontent.com/8939646/44705416-d9c63380-aa9e-11e8-96c9-f01acc82817e.png)

**Comment by revast** [comment]
https://packages.debian.org/sid/fonts-firacode

**Comment by karchingla** [comment]
Or 16.04?
