### ISSUE TITLE
Support for ABAP language specifics

### ISSUE THREAD

**Issue by FreHu** [tonsky/FiraCode#649]
At SAP, we have a proprietary language called ABAP. Fira Code does pretty it up a bit, but the language requires spaces after braces which in my opinion add too much clutter.

Sample code from some unit tests I'm writing:

![eclipse_2018-08-28_12-35-24](https://user-images.githubusercontent.com/5097067/44718055-26ba0200-aabf-11e8-829a-aab4af8841f4.png)

Would it be possible to make a font variant with condensed spaces?

Some other ligatures which would be nice to have:
- Builder pattern - having the brace on the previous line is not valid ABAP.
![eclipse_2018-08-28_12-43-00](https://user-images.githubusercontent.com/5097067/44718316-fb83e280-aabf-11e8-95b3-3299899532f3.png)
- A ligature for 

```abap 
). 
```

would be cool as well.

**Comment by tonsky** [comment]
Condensed spaces — I don’t think it’s a good idea
`)->` prob shouldn’t be a sinlge glyph, it’s two different things and the way they are rendered right now reflects it pretty good
`).` is just fine as it is, I don’t see how it can be improved

**Comment by spixi** [comment]
@tonsky 

ABAP uses `\` for path expressions and it is a convention to always begin associations with `_`.

It would be useful to have a `\_` ligature.

Example:

```
    SELECT FROM i_salesorder
      FIELDS
        SalesOrder,
        \_Item-SalesOrderItem,
        \_Item-Product,
        \_Item\_Product\_Text[ Language = @sy-langu ]-ProductName,
        \_SoldToParty-CustomerName
      INTO TABLE @DATA(lt_result)
      UP TO 100 ROWS.
```
