### ISSUE TITLE
`<!--` and `-->` don't have the same width as their ligature version

### ISSUE THREAD

**Issue by lbguilherme** [tonsky/FiraCode#65]
I think the image is self explanatory:

![](http://lbguilherme.com/screenshot/50051da270d10d7674d2363c19cd6600.png)

This breaks the expectation of seeing everything monospaced.
I didn't see it happening with any other ligature yet.

**Comment by curio** [comment]
For me, they do line up, i.e., have the same width as the original sequence of characters (in Atom 1.1).

**Comment by tonsky** [comment]
@lbguilherme does it still holds on FiraCode 1.100? If yes, what editor/OS you use?

**Comment by lbguilherme** [comment]
It is now fixed. Thanks!
(Tested on Atom)
