### ISSUE TITLE
XML comments don't work

### ISSUE THREAD

**Issue by YYProbe** [tonsky/FiraCode#652]
In MS VS 2015 XML comments do not work as told in README.
<img width="299" alt="xml-comment-bug" src="https://user-images.githubusercontent.com/14873892/45086810-c5241400-b10c-11e8-827e-4a546f901704.PNG">

**Comment by tonsky** [comment]
I see `</` is rendered correctly though. It’s a problem with Visual Studio, not the font. Nothing I can do
