### ISSUE TITLE
Adding new ligature: *= and+=

### ISSUE THREAD

**Issue by Geolim4** [tonsky/FiraCode#654]
Hello,

I think it would be great to add the following ligature:
`+=` to `⩲`
`*=` to `≛`

And maybe `-=` to some equivalent if it exists. I did not found atm in math books.

**Comment by tonsky** [comment]
Might be too confusing if we render them like that. Also they need to stay 2× wide

**Comment by Geolim4** [comment]
I'm not sure that it would be more "confusing" that actually ligatures such as "==" and "===" or ">=" ?
On what your apprehensiveness's based on ?

**Comment by kiprobinson** [comment]
I don't like the ligatures suggested here, but could you make it so `+=`, `-=`, and `*=` have the symbol and the equals sign vertically centered? Right now the +, -, and * sit a little bit off-center of the equals sign.

**Comment by Geolim4** [comment]
Okay I get it, it's just weird to have operators ligated in common languages and some not, visually it was about having consistency in ligaturing. But I agree completely with @kiprobinson Off-centered chars are a bit disturbing.

**Comment by tonsky** [comment]
Will fix +=, -=, and *=, thx!
