### ISSUE TITLE
Installing FiraCode-NF actually installs as FuraCode NF

### ISSUE THREAD

**Issue by schallm** [tonsky/FiraCode#658]
When running the following statement at the command line:

```cmd
scoop install FiraCode-NF
```
with output 

```cmd
Installing 'FiraCode-NF' (2.0.0) [64bit]
Loading FiraCode.zip from cache
Checking hash of FiraCode.zip ... ok.
Extracting FiraCode.zip ... done.
Running installer script...
Linking ~\scoop\apps\FiraCode-NF\current => ~\scoop\apps\FiraCode-NF\2.0.0
'FiraCode-NF' (2.0.0) was installed successfully!
```

I try to use within VS 2017 and it shows as FuraCode NF

![image](https://user-images.githubusercontent.com/331167/45959572-d790bf80-bfdf-11e8-80c7-9245f8247094.png)

**Comment by tonsky** [comment]
I have no idea what scoop and FiraCode-NF are

**Comment by schallm** [comment]
Sorry... Meant to open an issue on scoop's GitHub page...

If you are interested, scoop is a windows "package manager" available here: https://scoop.sh/
