### ISSUE TITLE
R pipe %>% ligature

### ISSUE THREAD

**Issue by belg4mit** [tonsky/FiraCode#659]
Not sure what it should be, a form of pipe, or simply condensed symbols (with angle nestled into gap under upper o of right %), but having a mix of ligatured and unligatured operators is a bit odd. Although, understandably, it is not possible to capture all possible symbols since what may be an operator in one language might be two separate syntactic elements in another; although I'm not aware of anywhere else this would be legal.

**Comment by yeedle** [comment]
Duplicate https://github.com/tonsky/FiraCode/issues/473
