### ISSUE TITLE
Erlang/Oz/Prolog less-than-or-equal-to operator

### ISSUE THREAD

**Issue by MadcapJake** [tonsky/FiraCode#66]
Erlang, Prolog and Oz/Mozart use `=<` to indicate the less-than-or-equal-to operator and unless I'm mistaken, there aren't any other use-cases for `=<` that would contraindicate using the `≤` ligature for `=<` as well.

**Comment by tonsky** [comment]
Added in 1.000

**Comment by afhole** [comment]
I am still getting `=<` on the latest version (v1.206/TTF/macOS 10.14.5). Is it working for anyone?

**Comment by tonsky** [comment]
It was removed in 1.205 https://github.com/tonsky/FiraCode/blob/master/CHANGELOG.md#1205-february-27-2018
