### ISSUE TITLE
>= ligature inconsistently being rendered

### ISSUE THREAD

**Issue by sg-s** [tonsky/FiraCode#661]
as shown here:

![screenshot 2018-09-25 at 11 19 40 am](https://user-images.githubusercontent.com/6005346/46024530-fe6cf580-c0b4-11e8-8dee-945f0e731ff0.png)

using Sublime Text 3

update: 

this appears to be language dependent. when using C++ syntax, this works, but when using MATLAB syntax it doesn't. not sure why it doesn't always replace it with the ligature

**Comment by tonsky** [comment]
yeah. Please report it to Sublime instead. This is a bug in how their language parser tokenizes `>=`
