### ISSUE TITLE
Characters for C0 and C1

### ISSUE THREAD

**Issue by mickeyl** [tonsky/FiraCode#662]
Could you consider applying the pull request for adding the control characters C0 and C1? It's at https://github.com/mozilla/Fira/pull/83

**Comment by mickeyl** [comment]
C0 and C1 are the control points that cover the Unicode code points U+0000 – U+001F and U+007F (C0), and U+0080 bis U+009F (C1). These areas are pretty important for people who want to build terminal emulators or hex editors, since they contain representations for the so-called "unprintable characters", i.e. NUL, STX, DC1, DC2, etc. With fonts that do not contain these points, you have to substitute the bytes with a dot or something like that. Since FiraCode is a great monospace font, it would be beneficial to add these code points. The patch from 
https://github.com/mozilla/Fira/pull/83 adds those, hence I would love to see it being merged. Please consider this request.

**Comment by tonsky** [comment]
So basically you need those for debug?

**Comment by mickeyl** [comment]
Depends on whether you call working with terminal emulators, hex editors, and similar technical applications, "debugging". At the end of the day, it's for visualizing data that contains characters within these code points.

**Comment by tonsky** [comment]
Maybe this is a better approach? https://github.com/tonsky/FiraCode/issues/764

**Comment by mickeyl** [comment]
Not understanding why you’re reluctant to just add glyphs where there are none, but I take everything I can get, so while I don‘t think it‘s necessarily a „better“ approach, it‘s a step into the right direction.

**Comment by Ryan1729** [comment]
> Not understanding why you’re reluctant to just add glyphs where there are none...

Well you certainly would not want to (by default) add characters for U+0009, U+000A, and U+000D since those are the tab, line feed and carriage return respectively. Saying those characters are widely used would be an understatement. I would be surprised if there were not widely used programs out there that render those characters if they have visible glyphs, which people would then complain about Fira Code "breaking".

**Comment by mickeyl** [comment]
I agree. For most usages, it's probably better to populate the control pictures block as described in #764. I will close this here and hope that @tonsky will consider doing this. https://github.com/mozilla/Fira/pull/83 might still be useful.
