### ISSUE TITLE
Mac OS Mojave font is rendered badly

### ISSUE THREAD

**Issue by hazratgs** [tonsky/FiraCode#663]
![image](https://user-images.githubusercontent.com/4028580/46256440-cbab6e80-c4b3-11e8-965a-676133fe6fcc.png)

**Comment by hazratgs** [comment]
![image](https://user-images.githubusercontent.com/4028580/46257263-71180f80-c4bf-11e8-88d0-e1730643b37d.png)
before

**Comment by hazratgs** [comment]
the font became thin

**Comment by tonsky** [comment]
Try turning on “Use font smoothing” in General setting in your macOS. They also have removed subpixel antialiasing in Mojave, that might be your issue as well

**Comment by mickeyl** [comment]
This is not a bug in FiraCode, use

```
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

to restore the old behavior.
