### ISSUE TITLE
Put “How to install.txt” to zip

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#664]

**Comment by TangibleDream** [comment]
You would like to see install.txt zipped and placed in the root directory?

**Comment by TangibleToofa** [comment]
Can I have access to submit a pr for this?

**Comment by tonsky** [comment]
You don’t need any special access to submit a PR

**Comment by TangibleToofa** [comment]
I'm seeing this...
```
$ git push origin 664
fatal: unable to access 'https://github.com/tonsky/FiraCode.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsvl alert protocol version
```

**Comment by j-f1** [comment]
@TangibleToofa You should be able to [fork](https://github.com/tonsky/FiraCode/fork) this repo, then make your changes in the fork and open a pull request.

You can take a look at [this video series](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) or [this short description](https://opensource.guide/how-to-contribute/#opening-a-pull-request) if you need more help.

**Comment by TangibleDream** [comment]
Added a pull request for this issue

**Comment by TangibleDream** [comment]
This was my first contribution.  Thanks :)

**Comment by TangibleDream** [comment]
Is there a reason for leaving the issue open?
