### ISSUE TITLE
Character exchange.

### ISSUE THREAD

**Issue by Jhynn** [tonsky/FiraCode#665]
Change "/" to "÷".

Thank you very much, this is the best font for programming.
Add it to Google Fonts.

**Comment by tonsky** [comment]
Hi! Thanks @Jhynn. Google Fonts is pending https://github.com/google/fonts/issues/1460
Changing `/` would break a lot of valid use-cases (e.g. paths, URLs, regexps, comments etc) so I can’t do that. Sorry

**Comment by Jhynn** [comment]
Ok @tonsky thank you. What do you think of adding curves in quotation marks and apostrophes?

![aspas](https://user-images.githubusercontent.com/31378090/46574878-1e3bcd80-c981-11e8-82d5-b7d7fda2e8e3.png)

**Comment by tonsky** [comment]
They are curved as long as you use proper characters (`“”`). This `"` is meant to be “straight double quote” that also serves as inch sign and angle second. It can’t be made curly

<img width="772" alt="screenshot 2018-10-06 at 22 33 57" src="https://user-images.githubusercontent.com/285292/46575117-ef8d1980-c9b7-11e8-8628-ce25bbe92472.png">

**Comment by Jhynn** [comment]
Ok, thanks!
