### ISSUE TITLE
Arrows in F# with Visual Studio 2017

### ISSUE THREAD

**Issue by bslatner** [tonsky/FiraCode#667]
In F#, the ligatures for -> and <- display just fine in VS Code. 

In Visual Studio 2017, the other ligatures display properly, but not these. They always display as individual characters.

Any idea what might cause this? Or if it's known/intended?

**Comment by tonsky** [comment]
It’s an editor problem. Seems like it parses `<` (`>`) and `-` as two different tokens. Not much I can to on my side

**Comment by bslatner** [comment]
I figured it was something like that. Thanks for looking into it.
