### ISSUE TITLE
Add ligature for Jinja2 braces

### ISSUE THREAD

**Issue by pepoluan** [tonsky/FiraCode#668]
Jinja2 employs braces for its embedded templating. It would be nice if there are ligatures for them. Especially since Jinja2 is not only used as native templating of the Django platform, but also as the "embedded templating" for SaltStack and Ansible.

**Most needed ligature**
* Double braces: `{{ some_var }}`
    The repetition looks... for lack of better word, "messy". My thought: _Maybe_ make the outer braces larger and "encompassing" the inner braces somewhat?

**Lest needed ligature**
* Brace-percent (embedded code): `{% for n in some_var %}`
* Brace-dash (embedded comment): `{# This is a comment #}`

**Comment by jdreesen** [comment]
See #616 for a discussion about `{{` and `}}` ligatures.

**Comment by pepoluan** [comment]
@jdreesen Ah, thanks! Please mark this as duplicate & close it then...

**Comment by pepoluan** [comment]
Duplicate of #616
