### ISSUE TITLE
FR: Add ∴ Therefore and ∵ Because 

### ISSUE THREAD

**Issue by cceckman** [tonsky/FiraCode#669]
Just ∵ they're aesthetically pleasing, ∴ I like to use them. :-)

**Comment by tonsky** [comment]
ok :)

**Comment by ice1000** [comment]
What's the current status?

**Comment by tonsky** [comment]
Once I get time to work on next release, I’ll most likely include those

**Comment by tonsky** [comment]
Therefore U+2234
Because U+2235

**Comment by cceckman** [comment]
Exciting- thanks!
