### ISSUE TITLE
Disable selected ligatures

### ISSUE THREAD

**Issue by DNF2** [tonsky/FiraCode#670]
Julia uses dotted operators extensively to broadcast operations (basically vectorizing them.) Any operator can have a dot added to it, and this includes all unicode operators as well.

Fira Code has ligatures for a small number of dotted operators, namely `.-` and `.=` (as far as I know). In code that looks inconsistent:
<img width="62" alt="screenshot 2018-10-10 at 14 05 50" src="https://user-images.githubusercontent.com/7106412/46735148-b09be400-cc95-11e8-994d-931e96267563.png">

Since there is no realistic way that ligatures can be added for _all_ allowable operators, is it possible to disable the ligatures for `.=` and `.-`?

**Comment by tonsky** [comment]
thanks, I’ll consider this

**Comment by curran** [comment]
FWIW, I've managed to disable selected ligatures by running https://github.com/ToxicFrog/Ligaturizer on the original Fira Mono, with custom configuration.

**Comment by marius311** [comment]
@curran any chance you could share more on how you did this? 

This is such a beautiful font for Julia except for this issue unforuntatley, as broadcasting is ubiquitous.

**Comment by curran** [comment]
@marius311 You can comment out certain ligatures in this file https://github.com/ToxicFrog/Ligaturizer/blob/master/ligatures.py , then run the build process to generate the font with commented out ligatures not present.

This is also mentioned in the README https://github.com/ToxicFrog/Ligaturizer#automatic

**Comment by pag** [comment]
Another straightforward way to remove the ligatures of your choice:
- Clone this repo
- Install the prerequisites for running the font build script (`sh scripts/bootstrap_macos.sh` or `bootstrap_linux.sh`)
- Confirm that you can generate the font files that you want (e.g. `sh scripts/build_ttf.sh`)
- Open FiraCode.glyphs in a text editor, find the line `name = calt;`, then in the long line above that delete the ligatures that you want. For example, to remove the ligature ~>  ⇝ (which makes my shell prompt look silly and ruins the highlighting there), find the part in that line starting from `lookup asciitilde_greater` and delete to the end of the block, i.e. the end of the next `\012\012` section.
- Generate the font files.

**Comment by jhpratt** [comment]
Hi @tonsky, could you check that `.=` is correct? After upgrading to v6, all ligatures/variants work as expected except this one, which seems to be always enabled. I've checked both in VS Code (without it explicitly enabled) and in gedit, which as far as I can tell doesn't have an option to change the default ligatures.

**Comment by tonsky** [comment]
<img width="325" alt="Screenshot 2021-11-30 at 10 49 25" src="https://user-images.githubusercontent.com/285292/144024435-45e69871-e1f0-48d2-bfe6-240927f8e207.png">

<img width="332" alt="Screenshot 2021-11-30 at 10 49 34" src="https://user-images.githubusercontent.com/285292/144024458-2f1292c8-a620-4623-8814-e2592faf0452.png">

**Comment by jhpratt** [comment]
Hm. Glad to see that it's working as expected, but now I'm wondering why mine isn't doing what I had hoped. Fortunately I rarely have those two characters together, so I don't care enough to dig further as it's just me.

Thanks for the response! :)
