### ISSUE TITLE
mac os x Mojave font issue

### ISSUE THREAD

**Issue by Gormartsen** [tonsky/FiraCode#672]
I have strange problem with this font on  osx Mojave.

At some point font disappear from vscode (rollback to default) and if I open fontbook - i don't see this font.

Clearing font cache and restart fontd (via killing in taskmanager and start fontbook again) - helps.

Is anybody else expirience the same issue?

**Comment by guilhermeprates** [comment]
I had the same issue with Xcode.  I just reinstall FiraCode with brew:
`  brew cask reinstall font-fira-code `
