### ISSUE TITLE
NPM Package is out of date

### ISSUE THREAD

**Issue by napei** [tonsky/FiraCode#674]
@MasseGuillaume the NPM package you added for FiraCode is out of date. Currently v1.205

[https://www.npmjs.com/package/firacode](https://www.npmjs.com/package/firacode)

**Comment by dsvensson** [comment]
@MasseGuillaume @tonsky seems like this has fallen between the chairs. Any chance you two could get this resolved?

**Comment by MasseGuillaume** [comment]
@tonsky I sent you an invite, sorry your notification felt in the cracks. I also published 1.206.0 https://www.npmjs.com/package/firacode/v/1.206.0

**Comment by akshaybabloo** [comment]
Could someone update the NPM for the new release, please?

**Comment by tonsky** [comment]
@akshaybabloo pushed
