### ISSUE TITLE
The “⟶” glyph has an interesting width

### ISSUE THREAD

**Issue by lensbart** [tonsky/FiraCode#677]
It’s wider than expected

**Comment by tonsky** [comment]
It’s not in a font

**Comment by lensbart** [comment]
Perhaps the glyph could be added so that it doesn’t appear with a different width? If it’s currently not present, the behaviour will be the same for everyone.

**Comment by tonsky** [comment]
Where are you getting it? Anything else you need in relation to this?

http://www.fileformat.info/info/unicode/block/supplemental_arrows_a/utf8test.htm

**Comment by lensbart** [comment]
Nope, that’s it. I noticed it in Visual Studio Code. (The issue is not urgent or important for me, so feel free to close if outside of the scope of Fira Code.)

Thanks!
