### ISSUE TITLE
Add ligature for <> (This is same as != )

### ISSUE THREAD

**Issue by praneeshc** [tonsky/FiraCode#679]
Add ligature for <> (This is same as != )

**Comment by tonsky** [comment]
I prefer not to render different combinations with the same ligature, as this would lead to confusion. Also, where possible, I use ligature that looks similar to the original characters. There is a ligature for `<>` already and I think it’s quite good. The fact that it means “not equal” in some languages (SQL, is it?) can’t be communicated through ligature alone. Also I’m afraid it might conflict with some other languages. But thanks for the suggestion!
