### ISSUE TITLE
Display errors in pycharm 2018.3

### ISSUE THREAD

**Issue by Whisht** [tonsky/FiraCode#684]
## Error
The visual effect of Fira Code is weird in PyCharm, with some unreadable character. Especially the ligature.
Looks like this.
![snipaste_2018-11-30_16-55-29](https://user-images.githubusercontent.com/16497652/49278916-169c2f00-f4c1-11e8-86a8-a28f52385c9d.png)

***
**But it works well in visual code**
![image](https://user-images.githubusercontent.com/16497652/49279065-6e3a9a80-f4c1-11e8-9bdb-4ea3fc6a48d3.png)

***
## Configs in Pycharm
* Version: Pycharm 2018.3
* Font: Fira Code
* Enable font ligatures: True
* OS: Windows 10,1809,17763.134

**Comment by tonsky** [comment]
- Try cleaning up c:\Windows\Fonts, as instructed here https://github.com/tonsky/FiraCode/wiki#corrupted-font-in-intellij-on-windows
- Try reporting to PyCharm

**Comment by Whisht** [comment]
I have done this as @tonsky told. And then I reinstall FiraCode. Well, a more wired problem happened.
I cannot find the FiraCode in Pychram font setting. Although it could found in system font setting.
![image](https://user-images.githubusercontent.com/16497652/49286913-87017b00-f4d6-11e8-880c-242156607d6c.png)

![image](https://user-images.githubusercontent.com/16497652/49286884-794bf580-f4d6-11e8-9c5e-e9c9d6bd90be.png)
***
I have noticed that FiraCode is not be installed in ` C:\Windows\Fonts `. (It caused by in the new version of Windows, the font file is install for current user(which is installed in `C:\Users\user_name\AppData\Local\Microsoft\Fonts`) not all user (whereas `C:\Windows\Fonts`) as default).
***
**So, in win10 1809, removing all `Fira\*` in `C:\Windows\Fonts` and using the option in right  click install for all  users could figure this out**
