### ISSUE TITLE
Some ligatures not rendered in Mintty

### ISSUE THREAD

**Issue by roastduck** [tonsky/FiraCode#685]
**[This seems NOT the same with issue #259]**

Some ligatures are rendered correctly in Mintty but others are not, as shown below:

![image](https://user-images.githubusercontent.com/6522983/49337772-935f1280-f653-11e8-8c3a-1458cdb41d6b.png)

I didn't figure out anything common among those failing ligatures.

Tested with Mintty 2.9.2 in Cygwin.

**Comment by tonsky** [comment]
Yeah, strange. Try reporting to Mintty?
