### ISSUE TITLE
Fira Code Retina

### ISSUE THREAD

**Issue by Ashkaan** [tonsky/FiraCode#688]
Fira Code Retina does not seem to work or at the least the instructions are incorrect.

https://github.com/tonsky/FiraCode/wiki/VS-Code-Instructions

Adding a weight of 600 simply gives you Bold.  Bold and Retina don't look anything like each other as viewed with any other program, like Sublime.

How can we get this font as our default?

**Comment by tonsky** [comment]
addressed. Thanks!
