### ISSUE TITLE
Inconsistent vertical alignment for "{::"

### ISSUE THREAD

**Issue by weavejester** [tonsky/FiraCode#689]
I believe this is a regression introduced by #486. If you have some code like:

```clojure
{::foo :bar}
```

Firacode will render the `:` with inconsistent vertical alignment.

<img width="93" alt="screenshot 2018-12-06 at 17 28 11" src="https://user-images.githubusercontent.com/8780/49600919-5741ef80-f97c-11e8-92e4-0c704c31f54f.png">

Ideally the `{:` ligature shouldn't occur if the `:` is followed by another `:` or an alphanumeric.

**Comment by weavejester** [comment]
Emacs 26.1, the latest [railwaycat build](https://github.com/railwaycat/homebrew-emacsmacport) for MacOS. Sorry, I should have tested this on other editors; in Atom it behaves as I'd expect.

Emacs seems to mis-render the ligature regardless of major mode, so it doesn't appear to have anything to do with syntax highlighting or anything specific to clojure-mode.

**Comment by tonsky** [comment]
BTW, it’s not related to `{:` ligature, there isn’t one. Instead it applies vertical offset to first `:` next to uppercase `{`. In other editors ligatures are applied first, so this rule is skipped afterwards

**Comment by weavejester** [comment]
Thanks for the explanation! I might have to live with the visual glitch in Emacs then, or I might roll back to an earlier version of FiraCode.

Also, thank you for making FiraCode in the first place, and putting time and effort in to answer issues like this.

**Comment by tonsky** [comment]
Thanks, glad you liked it! Hope to have better Emacs support soon
