### ISSUE TITLE
Atom 1.2.0 , OSX 10.11, Only limited ligatures working

### ISSUE THREAD

**Issue by benjamin-rood** [tonsky/FiraCode#69]
`atom-text-editor { text-rendering:optimizeLegibility }` makes no difference.

Working:
`!= <= >=  /= ==  ^=  >>= <<= ===`
` ... (...) `

Not Working:
`-> =>` (all lengths)
`->>`
`!==` maps to `!= =`
`>>>`  (and reverse)
`-<<` (and reverse)
`***`
(all arrows)

It would be safe to assume that most of the rest are not working, but those are the ones I had a chance to try.

It may be that I am typing the wrong keys? But since some of the ligatures are working, I must be doing something correct?

(One other suggestion: Why not have a plaintext version of all symbol combinations in the README.md which produce ligatures. Then someone can just copy and paste the whole set into Atom, see which ones convert or not.)

**Comment by weavejester** [comment]
Take a look at issue #63.

**Comment by benjamin-rood** [comment]
Hi weavejester, yes that is indeed the problem and an identical issue. When I try to enter a ligature in a comment line, they all seem to work fine. Thank you very much for correctly spotting the most likely candidate.
Okay, so, is there a list of the syntax definitions which are compatible / partially compatible / no functionality?

**Comment by tonsky** [comment]
Here’s text version of most of the ligatures:

```
a == b    a := b   a >= b
a != b    a |= b   a <= b
a === b   a ||=b   a <> b
a !== b   a .= b   a && b
a =:= b   a ~= b   a || b
a =/= b   a =~ b   a ?: b
a <=> b   a ~~ b   a >> b
a ..< b   a ?= b   b << a
a ... b   a /= b   s |> p
a ** b    a ^= b   p <| s
a :: b    a .. b

x ->  _  <- x   #(...)    /* ... */
x ->> _ <<- x   #[...]   /** ... */
x --> _ <-- x   #{...}    // ...
x =>  _  <= x   #_(...)  /// ...
x ==> _ <== x   #?(...)   ;; ...
x =>> _ <<= x   ~@(...)   {- ... -}
     a!!                 <!--...-->
     a??                    <.../>
     a++                   </...>
     a--                 
 
f >>= g   f +++ g
f =<< g   f --- g
f <=< g   f <+> g
f >=> g   f <*> g
f *** g   f <$> g
f &&& g   f <|> g
f ||| g   f -<< g
f >>> g   f >>- g
f <<< g   f >- g
          f -< g
```

**Comment by mik01aj** [comment]
Seems to be fixed in https://github.com/atom/language-javascript/issues/259.

Just to note, there are multiple highlighting modes for JS and JSX, "Javascript (JSX)" seems to work best for me.

**Comment by DJgamer98** [comment]
PHP still seems to have issues with it.
