### ISSUE TITLE
Ligature/symbol for Javascript "function"

### ISSUE THREAD

**Issue by oqx** [tonsky/FiraCode#691]
Excellent project! I've been using concealers in Vim and recently discovered Fira Code when I was looking around for a VS Code concealer implementation.

It would be great if the `function` keyword could be replaced with its corresponding symbol:
![image](https://user-images.githubusercontent.com/13574166/49962530-121d4080-fedb-11e8-82c6-157ce2a5e66a.png)

Here's a before and after:
![image](https://user-images.githubusercontent.com/13574166/49962449-e26e3880-feda-11e8-8bd3-c3e9f291457d.png)

![image](https://user-images.githubusercontent.com/13574166/49962558-23664d00-fedb-11e8-87a9-e54105985560.png)

**Comment by tonsky** [comment]
Not in Fira Code — we have a rule that replacement ligature must take exactly the same amount of space as character it has replaces.

**Comment by oqx** [comment]
Ah! Gotcha. Thanks for the swift reponse, mate.
