### ISSUE TITLE
Issues with <= glyph

### ISSUE THREAD

**Issue by drom** [tonsky/FiraCode#696]
In SystemVerilog language there are two usages for operator `<=`

  1) traditional less-or-equal
  2) non-blocking assignment http://www.asic-world.com/tidbits/blocking.html more like left fat arrow.

Less-or-equal glyph looks wired as fat-arrow. Is any way to disable particular glyph? or switch depend on context?
I am using Atom

**Comment by tonsky** [comment]
No way do disable single ligature unfortunately

**Comment by tonsky** [comment]
Will be in v6 as `cv20`-`cv22`
