### ISSUE TITLE
Dotted zero header

### ISSUE THREAD

**Issue by tpow** [tonsky/FiraCode#699]
I was very excited to try Fira Code after reading about the Ligature support. The header for Fira Code shows the nice dotted zero and example ligatures, but when I tried the font, I'm seeing a slashed zero. It looks like that was changed rather recently in #342.

I prefer the dotted zero and have found it less easily confused with 8 than the slashed zero, but it looks like the slashed zero is now the default. This saddens me, but if true, you should change the header so it isn't misleading.

**Comment by j-f1** [comment]
If you’re able to enable the OpenType feature `zero`, you should get the dotted zero back.

**Comment by IsaacLf** [comment]
Yes, that's ok that we can modify the font, but how? is there any guide to bring the dotted zero back? im on windows and i have to use v1.204 because of the zeros, plus I use this font on VSCode so i can't really just use the css config as in atom or sublime (idk if this last one can actually).

**Comment by j-f1** [comment]
There are VS Code plugins to add custom CSS.

**Comment by tonsky** [comment]
You are right, I should change the picture. I hope eventually Fira Code will have a customizable builder so that everyone would be able to build their own font from the features they like.

**Comment by Valtarr** [comment]
Maybe dotted version can be included into package (aka `FiraCode-DottedZero-Regular.ttf`)?
Dotted zero is so nice and lamp.

**Comment by j-f1** [comment]
@Valtarr It’s already included in the font; it just needs to be enabled using OpenType features.

**Comment by Valtarr** [comment]
@j-f1 But how to use it in windows?
* Commandline
* Notepad++
* Visual Studio
* Visual Studio Code
* GitExtensions
* Other Editors/Viewers...

Don't think there is some setting to enable it over the OS or for each program.

**Comment by ParkerPy** [comment]
The Stylistic sets wiki says to use the Custom CSS extension for VS Code (Found Here: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css&ssr=false#overview)  in order to enable these changes.  It requires the following code in the settings.json with a provided css url.

![image](https://user-images.githubusercontent.com/49846618/65363359-06c91500-dbd1-11e9-9ae8-ca2b90aa4287.png)

Is this css url for FiraCode provided somewhere? I know there is a css file in the installation folder but it doesn't include anything dealing with these stylistic changes like this dotted zero.

**Comment by j-f1** [comment]
I think what you have to do is create a CSS file somewhere on your computer, then put the URL to it into the VS Code setting.

**Comment by ParkerPy** [comment]
It had taken me a while, but I believe I figured it out. May I suggest the following link be added to the VS Code stylistic wiki on how to change your style: https://medium.com/@rzvdaniel_71068/customize-visual-studio-code-for-multiple-fonts-and-styles-96f83562af58

The key is using the developer tool to find the style key being used for a given text type. This screenshot, for example, resolves this dotted zero issue. (I just had to change the whole font to one that had dotted zeroes, though you may be able to narrow this to just numbers.) I used the "Fira Mono" from google fronts.
![image](https://user-images.githubusercontent.com/49846618/65834018-680d7a00-e29c-11e9-8007-4b9804817c9e.png)

**Comment by ginkcode** [comment]
After a lot of trying, I decide to choose Fira Mono. These ligatures are not worth compared to a beautiful zero eventually 😆
