### ISSUE TITLE
Suggestion: Add boolean logic symbols

### ISSUE THREAD

**Issue by turbohz** [tonsky/FiraCode#7]
As the title says, I wonder if boolean logic symbols could be added, such as ¬ (negation), ∧(conjuction), ∨(disjunction).

http://en.wikipedia.org/wiki/List_of_logic_symbols

**Comment by tonsky** [comment]
Probably. `∧` and `∨` could be bound to `&&` and `||` for C-like languages. Looks like these combinations are not used anywhere else. But I cannot render `!` as `¬`, obviously

**Comment by turbohz** [comment]
oh, too bad ligatures are not AST aware...

**Comment by tonsky** [comment]
I have this for Clojure: https://github.com/tonsky/clojure.unicode
There’s Unicode plugin for Haskell around
I guess C can get away with DEFINE
Don’t know the situation in another langs

**Comment by tonsky** [comment]
Added `&&` and `||` in 0.2

**Comment by gamis** [comment]
I find the &&->∧ binding to be really confusing. It makes sense mathematically, but it's too easy to confuse with ^.

Is there any way to turn off particular bindings for myself?

Otherwise, this font is awesome. Thanks so much for your efforts.
