### ISSUE TITLE
Add textadept to the working editors

### ISSUE THREAD

**Issue by bitwave** [tonsky/FiraCode#70]
http://foicica.com/textadept/

**Comment by bawr** [comment]
What OS does it work on? I just tested on Windows 10, and ligatures are not applied, sadly.

**Comment by tonsky** [comment]
Just checked on Mac, confirmed. @bitwave if you confirm Linux, I’ll add that as well

**Comment by MadcapJake** [comment]
I can confirm that it works on Linux.  Unlike Atom it actually shows the cursor inside the ligature too, which is nice!
