### ISSUE TITLE
Add a ligature for (<>)

### ISSUE THREAD

**Issue by pinktrink** [tonsky/FiraCode#700]
This is only a stylistic issue, however in Haskell, a common idiom is `(<>)`. However, sometimes the tracking between `(<` and `>)` appears off, making the whitespace one side appear larger than the other. A ligature supporting and centering all of that would be great.

**Comment by tonsky** [comment]
screenshot please? jfyi there already is a `<>` ligature

**Comment by Fresheyeball** [comment]
![img_20190115_065822](https://user-images.githubusercontent.com/609279/51185005-3631c000-1893-11e9-99e6-d5297d831d49.jpg)

![img_20190115_065830](https://user-images.githubusercontent.com/609279/51185016-42b61880-1893-11e9-92cb-43724b41d1e6.jpg)

**Comment by pinktrink** [comment]
Oops that's exactly what it is. @Fresheyeball and I noticed it while working together in a console, I'll close this.
