### ISSUE TITLE
(Visual Studio Community) "Bold" style is missing in options

### ISSUE THREAD

**Issue by iozsaygi** [tonsky/FiraCode#704]
Hey
I've installed all the types (regular , light , medium , bold and retina) of fira code.
But "Bold" style is missing in options section of **Visual Studio Community**.
**Other styles working fine**

![screenshot](https://user-images.githubusercontent.com/36489581/51270138-d9d2bb80-19cc-11e9-9b0c-af7c091ed5b5.png)

Am i missing some detail ? Thanks for any help.

**Comment by tonsky** [comment]
No idea, sorry.
