### ISSUE TITLE
VS Code Instructions "FiraCode-Retina" should be "Fira Code Retina"

### ISSUE THREAD

**Issue by zhouyifan0904** [tonsky/FiraCode#706]
The VS Code instructions seem to be outdated. Setting font name to "FiraCode-Retina" didn't work but "Fira Code Retina" did it for me.

**Comment by tonsky** [comment]
Are you on Windows?

**Comment by zhouyifan0904** [comment]
Yes.

**Comment by tonsky** [comment]
Thanks! Updated
