### ISSUE TITLE
Hexagonal asterisk (*)

### ISSUE THREAD

**Issue by Photonico** [tonsky/FiraCode#708]
This font makes me addicted to programming, it has become my favorite font! 

However, I hope that the star symbol * become hexagonal.

Could you release some specialized versions to match more people's preferences？
or offer the font tools like: http://input.fontbureau.com/ ?

**Comment by ConAntares** [comment]
Great! I'm looking forward to it very much.

**Comment by tonsky** [comment]
Will be in v6 as `cv16`
