### ISSUE TITLE
Request for Logic Ligatures: ⊩ (Forces)

### ISSUE THREAD

**Issue by asvarga** [tonsky/FiraCode#709]
The symbol ⊩ is used in modal logic (read as "forces"). ⊢, ⊨, and ⊫ are supported, so ⊩ (U+22A9) seems like a natural addition.

Additionally, negated versions would be useful: ⊬ ⊭ ⊮ ⊯ (U+22AC, U+22AD, U+22AE, U+22AF).

**Comment by tonsky** [comment]
Ok thanks I’ll take a look

**Comment by tonsky** [comment]
Do you mean them as ligatures or just as unicode symbols?

**Comment by asvarga** [comment]
As ligatures. Ligatures for ⊢, ⊨, and ⊫ are supported as `|-`, `|=`, and `||=`, but there is no ligature for ⊩.
