### ISSUE TITLE
Workaround for JavaScript ligatures in Atom

### ISSUE THREAD

**Issue by engelfrost** [tonsky/FiraCode#71]
As pointed out (#69, #59) some ligatures (e.g. `!==`) don't work well in Atom for JavaScript. 

Using [language-babel](https://atom.io/packages/language-babel) or [language-javascript-jsx](https://atom.io/packages/language-javascript-jsx) instead of the standard [language-javascript](https://atom.io/packages/language-javascript) package seems to fix this.

**Comment by lbguilherme** [comment]
The problem is that *language-js* expands ` a !== b` into:

```html
<span class="source js">
    a
    <span class="keyword operator js">!=</span>
    <span class="keyword operator js">=</span>
    b
</span>
```

instead of:

```html
<span class="source js">
    a
    <span class="keyword operator js">!==</span>
    b
</span>
```

And ligatures do not work across spans. This isn't fixable on FiraCode's side.

**Comment by engelfrost** [comment]
I know, but it's fixable on Atom's side, hence workaround. 

My experience is that the following language packages work for JavaScript: 

* language-javascript-jsx
* language-babel

You already need some fiddling with the Atom stylesheet to make ligatures work, so mentioning *language-javascript* as an issue as well seems appropriate.

PR: https://github.com/tonsky/FiraCode/pull/72

**Comment by engelfrost** [comment]
The real issue will apparently be [fixed upstream](https://github.com/atom/language-javascript/issues/259) soon

**Comment by flying-sheep** [comment]
it’s fixed there now, so this can be closed

**Comment by anthonybrown** [comment]
My arrow ligature only works inside a div.
<img width="555" alt="screen shot 2017-05-08 at 2 24 32 pm" src="https://cloud.githubusercontent.com/assets/1719818/25818911/299f3ed2-33fa-11e7-9163-e73e2373c0cc.png">

**Comment by tyler-barnes** [comment]
In case anyone else is still having this problem, I fixed it by switching out language-javascript-jsx. I replaced it with language-babel and everything is working perfectly.
