### ISSUE TITLE
Add hhea customParameters to each master

### ISSUE THREAD

**Issue by m4rc1e** [tonsky/FiraCode#711]
In https://github.com/googlei18n/fontmake/issues/519 we discovered that fontmake will generate the font with different vertical metrics. This happens because the source file doesn't contain any hhea metrics vals. If we add them, Glyphsapp and Fontmake will gen fonts which have the same vert metics. Add the following customParameters to each master:

```
(
        {
        hheaAscender = 935;
    },
        {
        hheaDescender = "-265";
    },
        {
        hheaLineGap = 0;
    }
)
```

**Comment by tonsky** [comment]
Added
