### ISSUE TITLE
Do not use |- ligature when part of |-|

### ISSUE THREAD

**Issue by ooa113y** [tonsky/FiraCode#713]
The `|-|` sequence of characters is used in Markdown tables to separate the header of the table from the contents, e.g.:
```markdown
|Column 1|Column 2|
|-|-|
|R1C1|R1C2|
|R2C1|R2C2|
```
Currently, Fira code applies the `|-` ligature here, resulting in this, which looks entirely wrong:
![image](https://user-images.githubusercontent.com/462484/52637168-8f673080-2edf-11e9-8e2e-cae2c3719de5.png)

**Comment by tonsky** [comment]
thanks, will adjust!

**Comment by AnandChowdhary** [comment]
@tonsky, this could be an interesting exploration of Fira Code ligatures for markdown. Also curious about your thoughts, @ooa113y.

Current behavior:

![Screen Shot 2020-11-23 at 14 48 21](https://user-images.githubusercontent.com/2841780/99945619-f2ffdc80-2d9a-11eb-8e3a-03fa37b6c615.png)

With proposal ligatures:

![Group 55](https://user-images.githubusercontent.com/2841780/99946182-f2b41100-2d9b-11eb-8f8e-de68ac5a9cfe.png)


I understand that multi-line ligatures might be impossible, but maybe something like this?

![Group 56](https://user-images.githubusercontent.com/2841780/99946201-fba4e280-2d9b-11eb-970c-e944a4cc1994.png)

This can be ligatures for `| -` and `- |`, for example. Also, `- | -` could render to something similar to a wider `+`.

If this is something you'd consider, I can open another issues to discuss it further.

**Comment by wopian** [comment]
> @AnandChowdhary: I understand that multi-line ligatures might be impossible, but maybe something like this?

I don't think this is a good idea for a ligature. I would have no idea if I typed `| -- | -- |` or `|----|----|`, which could lead to people committing something like `| -- |--- | ---|` unintentionally.

**Comment by tonsky** [comment]
Current Fira Code should render like this:

<img width="260" alt="Screen Shot 2020-11-23 at 13 38 20" src="https://user-images.githubusercontent.com/285292/99962853-2b9ab880-2d91-11eb-9422-c5fab2ab0a0a.png">
