### ISSUE TITLE
'-' is not placed in the vertical center

### ISSUE THREAD

**Issue by NDelt** [tonsky/FiraCode#717]
![hypoon](https://user-images.githubusercontent.com/46282492/52912212-ab107380-32f1-11e9-9476-9c359f6b84f7.PNG)
![hypoon2](https://user-images.githubusercontent.com/46282492/52912214-ad72cd80-32f1-11e9-84a9-b121709fab85.png)
`-` is positioned slightly above the baseline when ligature is disabled. Is it possible to move it to the center?

_Environment:_
- Windows 10
- IntelliJ IDEA(+ JetBrains IDEs), Visual Studio Code

I'm using the font with 12~16pt size.

**Comment by tonsky** [comment]
that’s why I made ligatures. Just turn them on
