### ISSUE TITLE
Archlinux VScode ligature not working

### ISSUE THREAD

**Issue by CanftIn** [tonsky/FiraCode#719]
I work in ArchLinux and try to add FiraCode in VScode by wiki guide.
After `pacman -S otf-fira-code`:
![1](https://user-images.githubusercontent.com/26135447/52996290-1e33fa00-3458-11e9-8140-30a50bb11c24.png)
Then the setting is that:
![2](https://user-images.githubusercontent.com/26135447/52996448-9f8b8c80-3458-11e9-9c05-7a46636a34b7.png)
but it seems not working:
![3](https://user-images.githubusercontent.com/26135447/52996461-aca87b80-3458-11e9-8b9a-aa1bad68ea3f.png)

**Comment by tonsky** [comment]
I have no idea what causes that but here are two ideas to try anyway:

- try putting "Fira Code" instead of "FiraCode-Regular" as a font
- try installing TTF instead of otf

**Comment by CanftIn** [comment]
@tonsky I'v tried these two ways and still not solving the problem. But in my Windows10, the font works well.

**Comment by CanftIn** [comment]
@tonsky Hi Boss, I'm very sorry. Today I test input `'Fira Code'` and it works.It matters me missing character. Thanks for your suggest.Now I close this issue.
