### ISSUE TITLE
Ligature Suggestion | Coroutines

### ISSUE THREAD

**Issue by kadsor** [tonsky/FiraCode#722]
Hi!

This might be the wrong place to ask for this kind of stuff considering it's very specific and thus likely not desirable to have in a general purpose font, but could you add support for C++ coroutine ligatures?
The `co_` prefix on the new keywords `co_await`, `co_return` and `co_yield` is very off putting and would be well replaced with an arrow to the left indicating propagation of a value from out of the coroutine.
I'd honestly rather implement this myself, however I've never worked on a font before and Fira just seems too huge for me to start.

Maybe you can point me in a direction to add this myself if you don't want to implement it.

Thanks!

**Comment by tonsky** [comment]
Sorry, I don’t see it as a ligature in Fira Code. Possibility for conflicts is very high. Also I don’t think text in that case needs to be replaced by graphics, it will only confuse people reading code set in Fira Code
