### ISSUE TITLE
IntelliJ Idea and Fira Code problem while pasting fast 

### ISSUE THREAD

**Issue by smartfin** [tonsky/FiraCode#723]
OS: MacOS Mojave 10.14.3
Editor: IntelliJ IDEA 2018.3.4

Reproduce steps:
1) copy some text inside editor
2) Hit hotkey to "Search in directory" - CMD+Shift+F
3) Text is filled as `6F4B 288F 1F5D 13DA 26A7 C315 2332 50F6 1C9B 3778` (or similiar) instead of actual text

If you paste your selection at this point - everything would be fine. 

<img width="697" alt="firacode_idea" src="https://user-images.githubusercontent.com/917717/53652627-5afdaf00-3c17-11e9-8d5f-87773b43a5ab.png">

**Comment by j-f1** [comment]
Seems like this is a problem with the editor rather than the font?

**Comment by tonsky** [comment]
Report it to JebBrains please

**Comment by smartfin** [comment]
Thank, just for future sources - it's issue with GPG Tools, https://gpgtools.tenderapp.com/discussions/problems/88493-a-strange-behaviour
