### ISSUE TITLE
<中文> 这个字体中，`@` 符号都是半边的吗？    求大佬翻译

### ISSUE THREAD

**Issue by zsio** [tonsky/FiraCode#726]
@haojunsui 求助大佬，帮我翻译翻译。  万谢

在`VS Code` 和 `Chrome` 中，`@` 符号都是半边的，不知道是不是字体本身就是这样呢？ 

![image](https://user-images.githubusercontent.com/16083606/54328025-54bff780-4647-11e9-887c-ef9a1813c858.png)
![image](https://user-images.githubusercontent.com/16083606/54328035-5f7a8c80-4647-11e9-9e56-ec246464a7da.png)

**Comment by Sinderella** [comment]
I am not sure what he's saying but looking from the screenshot, I think I am having the same issue with '@' sign on both Alacritty and Kitty. Maybe there's something wrong with my settings?

Alacritty
![image](https://user-images.githubusercontent.com/1926450/54372103-95813600-4672-11e9-88ff-372cd7f0f8d6.png)

Kitty
![image](https://user-images.githubusercontent.com/1926450/54372130-a29e2500-4672-11e9-9af2-a57e592bc609.png)

**Comment by zsio** [comment]
@Sinderella   Yes, I mean this.  😊😝

**Comment by j-f1** [comment]
This is intentional behavior, and it’s how the font is designed. See #352.

**Comment by Sinderella** [comment]
> This is intentional behavior, and it’s how the font is designed. See #352.

Ahh, I just saw it here too. If it's intentional, then I am happy.

https://github.com/tonsky/FiraCode/wiki#troubleshooting

Thank you!

**Comment by tonsky** [comment]
:)
