### ISSUE TITLE
New Ligature suggestion: \/ and /\

### ISSUE THREAD

**Issue by advAdder** [tonsky/FiraCode#728]
'\\/' for logical disjunction '∨' and '/\\' for logical conjunction '∧'.

**Comment by tonsky** [comment]
It was already suggested and, as far as I can remembered, implemented but rolled back later. The problem is that they conflict a lot with regexpes/escapes sequences. Second, nobody really uses those combinations to represent those logical operations.

**Comment by nunocastromartins** [comment]
Sorry to comment on this closed issue, but the suggested (and rejected) ligatures seem to have made its way to v2. As @tonsky mentioned, I see these ligatures conflicting with escapes in regexps.

Why the change of heart that made this go forward?

**Comment by tonsky** [comment]
In v2 they should only work if surrounded by space

**Comment by nunocastromartins** [comment]
Using VS Code:
![image](https://user-images.githubusercontent.com/8314616/65258955-bf248980-dafb-11e9-92f7-945589aee135.png)

The language mode is set to JavaScript; interestingly it seems to work as expected with it set to plain text.

I now believe that it may be a bug in VS Code, in how ligatures interact with syntax highlighting. @tonsky, should I open a new issue here? Can you confirm that it is indeed an issue with the editor?
