### ISSUE TITLE
'<->' and '<-->' looks weird

### ISSUE THREAD

**Issue by lexrus** [tonsky/FiraCode#73]
Some two-way binding defined `<->` as the operator.

<img width="129" alt="screen shot 2015-11-20 at 2 06 25 pm" src="https://cloud.githubusercontent.com/assets/219689/11292957/e873de8c-8f8f-11e5-922e-5c6f63958a2b.png">

**Comment by Zhigalin** [comment]
Well, actually there is no '<->' ligature, just a '<-' ligature and '>', closing angular parentesis.07:09, 20 novembre 2015, Lex Tang <notifications@github.com>:Some two-way binding defined <-> as the operator.  —Reply to this email directly or view it on GitHub.     -- Alexander Zhigalin - DevOps

**Comment by tonsky** [comment]
I think it makes sense to add `<->` ligature. Thanks for the idea!

About `<-->`, though, do you have real-world example where such combination
is used? I don’t want to add something that’s unlikely to be seen in the
wild.

**Comment by tonsky** [comment]
// comment to self: never reply to github issues via email.

About `<-->`, @lexrus, do you have real-world example where such combination is used? I don’t want to add something that’s unlikely to be seen in the wild.

**Comment by lexrus** [comment]
@tonsky Yes, rarely used.
