### ISSUE TITLE
Char width issue in cLion

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#732]
Hi @tonsky , I was just about to create a new issue when I found this one. 
I found out that depending on line content the spacing is sometimes is inconsistent. I am working on cLion on macOS Mojave with ligatures on.
Though I'm not sure if this has to do with Fira code or Fira in particular.
Please, let me know if I should to ask for help on Mozilla's GitHub or could it be related to your font only?

improper:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/25040959/54884639-c08a3780-4e73-11e9-9f23-3da628160ee3.png">
proper:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/25040959/54884722-866d6580-4e74-11e9-8e16-831bc67cd476.png">

P.S. I love this font, your ligatures made my life easier. ❤️

_Originally posted by @waszqba in https://github.com/tonsky/FiraCode/issues/459#issuecomment-475992336_

**Comment by tonsky** [comment]
@waszqba which version of cLion do you use? And which version of Fira Code? I assume built-in one? Also what syntax is this? I can’t repro this:

<img width="312" alt="Screenshot 2019-03-27 at 20 12 47" src="https://user-images.githubusercontent.com/285292/55097368-bf077c00-50cc-11e9-804f-ec507addbec7.png">

Could you screenshot full line, starting from the very left? Would be great if you turn “invisble chars” on too. Are there tabs in play here?

Also please screenshot Editor → Font window in settings.

Thanks!

**Comment by waszqba** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/25040959/55178776-58df2f80-5186-11e9-994a-c8272c911e05.png">
cLion 2018.3.4, I don't remember if I downloaded the font or it was built in.
What tabs do you mean?
<img width="758" alt="image" src="https://user-images.githubusercontent.com/25040959/55178914-a78cc980-5186-11e9-981a-8e2342bc6def.png">

**Comment by waszqba** [comment]
@tonsky bump

**Comment by tonsky** [comment]
I reproduced the bug. I also verified it is with the built-in version of Fira Code. Using a version from my machine does not display this error. Please open an issue at https://youtrack.jetbrains.net/issues/IDEA and ping Dmitry Batrak to update Fira Code to the latest version
