### ISSUE TITLE
FiraCode v1.206 breaks many Dialogs in IntelliJ - Wrong Encoding

### ISSUE THREAD

**Issue by TobseF** [tonsky/FiraCode#734]
After an update from FiraCode v1.204 to v1.206 many dalogs are broken. The show unreadable Strings - which looks like a wrong encoding.

![2019-03-28_15h55_46](https://user-images.githubusercontent.com/1190109/55167812-f419da00-5171-11e9-9960-32ba44b28121.png)

This is already addressed by Jetbrains: https://youtrack.jetbrains.com/issue/IDEA-159901

 ### What steps will reproduce the issue?
Install current FiraCode https://github.com/tonsky/FiraCode and choose it as Editor > Font

**Wrong JavaDoc dialog:**
1. Open a Java Class
2. Click on a Class adn press crl + q to show the JDoc overlay
3. Try to read it

**Wrong Change Signature dialog;**
1. Open a Java Class
2. Click on a method press crl + F6 to open the Change Signature dialog
3. Try to read it
What is the expected result?
We see readable and formatted text.

What happens instead?
Most of the formatted Strings like headings, links or code are not readable. Instead we see strange characters.

## System
IntelliJ Ultimate 2019.1 - win 10 x64 - DE
Font: FiraCode v1.206 - ttf

Changing the font back to 1.204 resolves this issue

###  Screenshots
![2019-03-28_09h59_56](https://user-images.githubusercontent.com/1190109/55168020-54a91700-5172-11e9-85eb-801659a10c6b.png)
![2019-03-28_11h36_10](https://user-images.githubusercontent.com/1190109/55168025-57a40780-5172-11e9-9eea-637a389ca4da.png)
![2019-03-28_11h49_46](https://user-images.githubusercontent.com/1190109/55168044-5c68bb80-5172-11e9-925d-bf5d62e1e56b.png)

**Comment by tonsky** [comment]
This is a known problem. See https://youtrack.jetbrains.com/issue/IDEA-159901 and https://github.com/tonsky/FiraCode/wiki#corrupted-font-in-intellij-on-windows
