### ISSUE TITLE
Ligatures /\ and \/ for Coq

### ISSUE THREAD

**Issue by debilausaure** [tonsky/FiraCode#738]
I'm using [Coq](https://coq.inria.fr/) on a daily basis.
Ligatures (such as =>, ->, <->, =?, :=, !=, etc.) are really helping, they make a huge difference in proof readability.

I wish there were ligatures for 'logical and' symbol (u+2227, written /\ in Coq) and 'logical or' symbol (u+2228, written \\/ in Coq). Is that something you've considered to add ?

Nevertheless, I can see cases where you would want to write /\  or \\/ without triggering the ligatures though, so they could be deactivated by default, so one would have to rebuild the font to use them? Or could it be done through specific rules such as requiring spaces around the symbols ?

Once again, thank you.

**Comment by debilausaure** [comment]
(Also, I'm not sure if you're aware, but CoqIDE seem to display ligatures just fine without any additional configurations).

**Comment by tonsky** [comment]
I used to have those but they indeed conflicted with regexps in particular. We could require whitespaces around, that should solve most of the issues I believe. Would that work? What other characters might surroud those? E.g. brackets, parens, newline etc?

**Comment by debilausaure** [comment]
Yes absolutely !
I'm quite sure brackets are not meant to be directly around, but parenthesis - like this ")_/\\_(" - or newlines might indeed surround them.
