### ISSUE TITLE
How to remove a ligature when building locally 

### ISSUE THREAD

**Issue by maxkorp** [tonsky/FiraCode#744]
So I assume this is not specific to any specific ligature, but for example I am looking at `[|` and `|]`. I know work has been done on both but I don't like the current solution and I'm not about to buy glyphs to try coming up with something new. I'd be satisfied just disabling those particular ligatures and otherwise leaving things alone. How would I go about doing this when building locally? Or is that actually done with glyphs as well?

**Comment by tonsky** [comment]
Find bracketleft_bar.liga and bracketright_bar.liga in a glyphs file (it’s a text format) and kill them there. Then rebuild the font. Rebuilding does not require Glyphs anymore if you use scripts from master
