### ISSUE TITLE
Fira Code is too good

### ISSUE THREAD

**Issue by Bloo9** [tonsky/FiraCode#747]
So the problem is that I used to enjoy looking around for new fonts, trying to see if any of them could top the current font I was using. I would search for suggestions and would always get recommended fonts like Hasklig, Menlo, Monoid, Deja Vu Code, Dank Mono, etc.. which were fine but then, after finding Fira Code, it put an end to my search for the perfect font!
Now, I'm getting too much work done and finishing projects faster, causing me to start new projects which just forces me to waste more of my time programming!

Can this be fixed in the next update? Maybe make the font worse somehow, such as stripping out the ligatures, or only including Cyrillic script?
For now, the only way to get around this bug is to set your font to something like Comic Sans and use that for a couple minutes, then switch back to Fira Code and repeat ad infinitum. But as you can imagine, this is a hassle and wastes a lot of precious time.

**Comment by tonsky** [comment]
🥰
