### ISSUE TITLE
Can you replace '@' symbol? 

### ISSUE THREAD

**Issue by Joysus1** [tonsky/FiraCode#748]
I want the full '@' symbol xD
Pls, place the new version here.

**Comment by tonsky** [comment]
Hi! Thanks for the suggestion. I don’t want to alter it in default version, but if I ever develop alternatives it will be there. Thanks!

**Comment by Joysus1337** [comment]
It was just a suggestion, I don't tell you to change the default version cus you can edit it and share the replaced '@' symbol here.

**Comment by dnedrow** [comment]
@joysus1337, what do you mean about the “commercial at” symbol (@) needing to be full?

**Comment by Joysus1337** [comment]
> @Joysus1337, what do you mean about the “commercial at” symbol (@) needing to be full?

I mean I need '@' like in Consolas font, because in Fira Code it looks like http://joxi.ru/KAgxOQpUEEoBVr

**Comment by Joysus1** [comment]
@tonsky ?
