### ISSUE TITLE
Why don't my F# lambdas use ligatures?

### ISSUE THREAD

**Issue by rlundy** [tonsky/FiraCode#749]
Using Fira Code with Visual Studio 2019 in an F# project, my lambda expressions don't use the Fira Code ligatures.  For example:

![image](https://user-images.githubusercontent.com/651545/56668434-ce6bec00-66af-11e9-9623-58d29b63721d.png)

Fira Code is enabled (replacing `|>` with the triangles), but the `->` doesn't get the arrow ligature, even though this ligature exists and works in e.g. Java lambdas (albeit this is in VS Code):

![image](https://user-images.githubusercontent.com/651545/56668691-42a68f80-66b0-11e9-9aa7-13983b5fcdad.png)

Any ideas why?

**Comment by tonsky** [comment]
Yes https://github.com/tonsky/FiraCode/wiki#some-ligatures-work-while-some-dont
