### ISSUE TITLE
Semantic versioning for jsDelivr auto-update 

### ISSUE THREAD

**Issue by ignatiusmb** [tonsky/FiraCode#754]
jsDelivr uses [semantic versioning](https://semver.org) for their delivery and I usually just put the major version in my cdn import from jsDelivr so that it will auto-update when a new version comes in. But what I notice from the link provided
```
https://cdn.jsdelivr.net/gh/tonsky/FiraCode@1.206/distr/fira_code.css
```
is that if you removed `.206`, it will fail to fetch the data because it's not semantically versioned and if we try to use `@latest`, it would return either the `0.6` version or a 504 error.

My suggestion, since 206 probably means MINOR version 2 with PATCH version 6 is to just tag it to the next minor version -> `1.3.0` or bump the major version and start at version -> `2.0.0`

Another minor one is probably to remove the underscore in `fira_code.css`, it is not as appealing as a simple dash on a URL. `fira-code.css` or just `firacode.css` is much nicer imo.

**Comment by tonsky** [comment]
1.206 should be fine as MAJOR=1 and MINOR=206, no?

**Comment by ignatiusmb** [comment]
It still works as an exact version/tag for the url but it doesn't seem to support automatic updates with version range, it is also stated in its [docs](https://github.com/jsdelivr/jsdelivr#publishing-packages) to use semver, in which I think is why it won't work without the additional dot for the PATCH versions.

It's not really an issue though, just thought it would be nice to have it auto update.
