### ISSUE TITLE
Ligature "===" weird displayed in PhpStorm 2019.1

### ISSUE THREAD

**Issue by gremo** [tonsky/FiraCode#755]
Ligature "===" weird displayed in PhpStorm 2019.1:

![fira](https://user-images.githubusercontent.com/1532616/57220948-80cf7780-6ffd-11e9-9658-bde2cf37f809.PNG)

My settings: Fira Code Retina, size 12, line spacing 1.0. Happens with all Fira fonts.

I really love this font but having ligatures not correclty displayed is bad

**Comment by tonsky** [comment]
It’s a known issue with no fix for now (other than changing font size) https://github.com/tonsky/FiraCode/wiki#hinting-issues. I’ll close this one as there are other duplicates open

**Comment by gremo** [comment]
Ok, thanks, sorry for bother :)
