### ISSUE TITLE
`..` and `..=` are looking very different

### ISSUE THREAD

**Issue by upsuper** [tonsky/FiraCode#757]
It seems that currently the ligature for `..` and `..=` are looking very different (the dots of the latter are much bigger and in the middle vertically). Is there any reason `..=` is designed that way?

This ligature looks unfortunate for Rust, because in Rust [`..`](https://doc.rust-lang.org/std/ops/struct.Range.html) is exclusive range, and [`..=`](https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html) is inclusive range, they have very similar semantics.

It would be great if `..=` can look similar to `..`.

**Comment by tonsky** [comment]
I don’t remember where it comes from but I believe it is an operator in some language. I agree that maybe rendering it that way was not the greatest idea, along with `.=` and `.-`

**Comment by upsuper** [comment]
It might be a good idea to have a table to record where each combination is from, and what conflicting cases are. That would probably be helpful when this kind of issues are raised.

If you can dump a list of current ligatures in a wiki page with some examples, people may start filling it with usecases I believe, maybe something like:
* `=<`
  * less than or equal to: [Erlang](http://erlang.org/doc/reference_manual/expressions.html#term-comparisons)
  * not a syntax: [docopt](http://docopt.org/)
* `..=`
  * (Unknown)
  * range inclusive: [Rust](https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html)

**Comment by tonsky** [comment]
There is one https://docs.google.com/spreadsheets/d/1T19dtqd5pqzmUX3epbaGwuVvPIiReCwsd_XDfVhTqW0/edit?usp=sharing

**Comment by upsuper** [comment]
Hmmm... So it was added for Rust, but it doesn't work well in Rust... That's interesting :D

**Comment by tonsky** [comment]
I can see why it doesn’t work well now though. I’ll see what I can do.

**Comment by upsuper** [comment]
Thanks!

**Comment by upsuper** [comment]
Ping on this. So actually given the spreadsheets, there isn't really a conflict. The ligature doesn't work well in the language it meant to benefit. Could you probably remove such ligature or make it align with `..`?

**Comment by tonsky** [comment]
Yes I’ll remove it
