### ISSUE TITLE
How to build in Linux?

### ISSUE THREAD

**Issue by Fenzland** [tonsky/FiraCode#758]
In README, we can find the way to build on MacOS.
But how to build on Linux?

**Comment by tonsky** [comment]
Same way, I guess? Install same packages, run same commands. Let me know if that doesn’t work

**Comment by Fenzland** [comment]
I mean, can you add some guilds into README about that? Maybe as will as Windows if it's not a big job. Thanks. Mac is really expensive in my country.

**Comment by j-f1** [comment]
In most cases, you shouldn’t need to build the font yourself. There’s already pre-built versions in several formats in the `distr/` directory.

**Comment by tonsky** [comment]
Sorry @Fenzland, I don’t have Linux. If you can contribute the instructions for your distro that would be great though
