### ISSUE TITLE
Ligature <-<--< interpreted as =<<-<<

### ISSUE THREAD

**Issue by Edhebi** [tonsky/FiraCode#759]
Not gonna lie, I found this on by randomly mashing keyboard ...

The characters `<-<-<<` are interpreted as `(=<<)(-<<)`. Fun fact, the characters `=<<-<<` are actually interpreted as `=(<<-)(<<)`.

Tested on kitty terminal and vscode, both on archlinux.

To be fair here, I'm not sure it has anything to do with the font, I'd suspect a parsing error os-side...

**Comment by tonsky** [comment]
Well what concerns me here is that `<-<` is rendered as `=<<`. I’ll look into it. Thanks!

**Comment by Edhebi** [comment]
Also confirmed on windows 10 (notepad, vscode)

**Comment by Kryptos-FR** [comment]
I'm seeing inconsistent behavior between different editors.

Issue in VS Code:
![image](https://user-images.githubusercontent.com/3006525/58672838-c9bbe700-8383-11e9-8c30-d8ed74b7b119.png)

No issue in Visual Studio:
![image](https://user-images.githubusercontent.com/3006525/58672821-b9a40780-8383-11e9-83a7-ed75b9cfe64e.png)

Characters typed:
```cs
var s = "<-<-<<";
s = "(=<<)(-<<)";
s = "=<<-<<";
s = "=(<<-)(<<)";
```

**Comment by tonsky** [comment]
Should not be a problem since at least v5
