### ISSUE TITLE
Cask 'font-fira-code' is unavailable: No Cask with this name exists.

### ISSUE THREAD

**Issue by GandalfSaxe** [tonsky/FiraCode#760]
When I run `brew cask reinstall font-fira-code` I get error:

```
Error: Cask 'font-fira-code' is unavailable: No Cask with this name exists.
```

**Comment by tonsky** [comment]
Works for me

```
$ brew tap homebrew/cask-fonts
Updating Homebrew...
...
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts'...
remote: Enumerating objects: 1216, done.
remote: Counting objects: 100% (1216/1216), done.
remote: Compressing objects: 100% (466/466), done.
remote: Total 1216 (delta 800), reused 933 (delta 745), pack-reused 0
Receiving objects: 100% (1216/1216), 232.37 KiB | 479.00 KiB/s, done.
Resolving deltas: 100% (800/800), done.
Tapped 1184 casks (1,232 files, 1.1MB).

$ brew cask install font-fira-code
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 4123, done.
remote: Counting objects: 100% (4123/4123), done.
remote: Compressing objects: 100% (4114/4114), done.
remote: Total 4123 (delta 27), reused 731 (delta 7), pack-reused 0
Receiving objects: 100% (4123/4123), 1.32 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (27/27), done.
Tapped 1 command and 4016 casks (4,129 files, 4.2MB).
==> Satisfying dependencies
==> Downloading https://github.com/tonsky/FiraCode/releases/download/1.206/FiraCode_1.206.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/26500787/093fe400-c514-11e8-9b03-dfaaf2915a4c?X-Amz-Algorithm=AWS4-HMAC-S
##################################################                        70.1%^C
```

**Comment by tonsky** [comment]
And it certainly exists https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-fira-code.rb

**Comment by j-f1** [comment]
Try `brew update` maybe?

**Comment by GandalfSaxe** [comment]
Thanks it ended up working. Not sure what it was.

**Comment by GandalfSaxe** [comment]
Seems like I somehow got it installed twice:

```
Error: Cask font-fira-code exists in multiple taps:
  homebrew/cask-fonts/font-fira-code
  caskroom/fonts/font-fira-code
```

I managed to remove one of them by running `brew untap caskroom/fonts` (found in https://github.com/Homebrew/homebrew-cask/issues/59227). What does brew `brew tap homebrew/cask-fonts` do vs. usually `brew install...` and `brew cask install...`?

**Comment by mhulse** [comment]
This worked for me:

```bash
$ brew tap caskroom/fonts && brew cask install font-fira-code
```

Just in case anyone coming here from Google wants a clear single-liner.

**Comment by jtbrough** [comment]
Using the suggested one-liner above I still faced an error:
> Error: caskroom/fonts was moved. Tap homebrew/cask-fonts instead.

Thus:
`brew tap homebrew/cask-fonts && brew cask install font-fira-code`

**Comment by nxqbao** [comment]
As of 2021, I think this might change to 

```
brew tap homebrew/cask-fonts && brew  install --cask font-fira-code
```

**Comment by tonsky** [comment]
thanks @nxqbao, update the distr

**Comment by michaelyaacoub** [comment]
`$ brew tap epk/epk` solved it for me!

**Comment by michaelyaacoub** [comment]
[$ brew tap epk/epk](url) solved it for me!

**Comment by michaelyaacoub** [comment]
I ran these and and it solved it for me - make sure to run the brew tap epk/epk package first.
/
$ brew cask install font-fira-code/

**Comment by michaelyaacoub** [comment]
I ran these and it solved it for me - make sure to run the 

$ brew tap epk/epk package first.

$ brew cask install font-fira-code/

**Comment by michaelyaacoub** [comment]
I ran these and it solved it for me - make sure to run the 
$ `brew tap epk/epk package` first.
$ `brew cask install font-fira-code`

**Comment by wopian** [comment]
⚠️ You do not need the 3rd-party epk/epk cask. It **DOES NOT** include the fira code cask:

- https://github.com/epk/homebrew-epk/tree/master/Casks

`font-fira-code` cask comes from `brew tap homebrew/cask-fonts`
