### ISSUE TITLE
No ligatures in javascript template strings

### ISSUE THREAD

**Issue by kWeb24** [tonsky/FiraCode#762]
Hey,

There's issue with rendering ligatures in template strings in javascript. For example, simple condition:

![no-ligatures](https://user-images.githubusercontent.com/3027308/57928688-c6b7f580-78b1-11e9-9601-75234b74407b.png)

The same is for each available ligatures. Template strings are probably treated like regular strings. 

I'm using [FiraCode 0.3.0](https://atom.io/packages/firacode) package for Atom

**Comment by tonsky** [comment]
From their readme

> Ligatures are disabled in strings.
