### ISSUE TITLE
Could you add the bracket symbols: ⟨ and ⟩?

### ISSUE THREAD

**Issue by ConAntares** [tonsky/FiraCode#763]
I have two requests.

One is that ⟨ and ⟩ are frequently used in Quantum Mechanics.
I hope that you can support it.

And, could you release another vision that Symbol: 0 with dot symbol: · , not /?

Sincerely,
Lu

**Comment by tonsky** [comment]
I’ll add ⟨ and ⟩.

> could you release another vision that Symbol: 0 with dot symbol: · , not /?

Fira Code does not support customization at the moment, and I don’t want to maintain multiple versions. But if you are using web-based editor (Atom, VS Code) dotted zero can be enabled via CSS `font-feature-settings: 'zero' 1;`

**Comment by j-f1** [comment]
Similarly, some other programs will allow you to set OpenType features, and enabling the “slashed zero” option will (counter-intuitively) enable the dotted zero.

**Comment by ConAntares** [comment]
> 
> 
> I’ll add ⟨ and ⟩.
> 
> > could you release another vision that Symbol: 0 with dot symbol: · , not /?
> 
> Fira Code does not support customization at the moment, and I don’t want to maintain multiple versions. But if you are using web-based editor (Atom, VS Code) dotted zero can be enabled via CSS `font-feature-settings: 'zero' 1;`

Thank you very very much for your support on  "⟨" and "⟩".
But I don't know how to change slashed zero to dotted zero in VS Code.
I only focus on computational physics with Python and Julia. I have no experience with CSS.

**Comment by j-f1** [comment]
Unfortunately it looks like VS Code doesn’t support custom CSS to change this at the moment.

There’s [an extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) that looks like it would do the trick, but it seems like it might be a little difficult to install. If you end up using that, you’ll need to create a CSS file with the following content and enable it by adding <code>"vscode_custom_css.imports": ["*the full path to the CSS file*"],</code> to your `settings.json`.

```css
// Enable Fira Code dotted zero
.monaco-editor {
  font-feature-settings: "zero";
}
```

**Comment by tonsky** [comment]
And this is the issue to track https://github.com/microsoft/vscode/issues/10435

On Thu, May 23, 2019, at 19:32, Jed Fox wrote:
> Unfortunately it looks like VS Code doesn’t support custom CSS to change this at the moment.

> There’s an extension <https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css> that looks like it would do the trick, but it seems like it might be a little difficult to install. If you end up using that, you’ll need to create a CSS file with the following content and enable it by adding `"vscode_custom_css.imports": ["*the full path to the CSS file*"],` to your `settings.json`.

> // Enable Fira Code dotted zero
> .monaco-editor {
  font-feature-settings: "zero";
}

**Comment by ConAntares** [comment]
> 
> 
> Unfortunately it looks like VS Code doesn’t support custom CSS to change this at the moment.
> 
> There’s [an extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) that looks like it would do the trick, but it seems like it might be a little difficult to install. If you end up using that, you’ll need to create a CSS file with the following content and enable it by adding `"vscode_custom_css.imports": ["_the full path to the CSS file_"],` to your `settings.json`.
> 
> ```css
> /* Enable Fira Code dotted zero */
> .monaco-editor {
>   font-feature-settings: "zero";
> }
> ```

Thanks a lot for your response. I think it is not convenient for me. I have to give up change slashed zero.
But I sincerely hope that you can release the version with dotted zero.

**Comment by ConAntares** [comment]
Could you add "‖"?
It means the norm of a Matrix in Linear Algebra.
