### ISSUE TITLE
missing `⎈` character - need this for any text that has to do with kubernetes.

### ISSUE THREAD

**Issue by tigerinus** [tonsky/FiraCode#766]
Need this char for kubernetes status in powerline + tmux.

Thanks!!!!

**Comment by tonsky** [comment]
sure :)

**Comment by tigerinus** [comment]
Is it quick for you to also include `` additionally? thx!

**Comment by tonsky** [comment]
What’s that for?

**Comment by tigerinus** [comment]
> What’s that for?

That's the powerline right arrow char...using Fira Code, it shows me a `?` in box.

**Comment by tonsky** [comment]
I’m pretty sure it’s in the font 
<img width="53" alt="Screenshot 2019-05-23 at 13 28 39" src="https://user-images.githubusercontent.com/285292/58245990-b1821180-7d5e-11e9-96b4-b66c9298be40.png">

**Comment by butuzov** [comment]
I am really not sure if this is kubernetes icon =)

⎈ vs logo 

![image](https://user-images.githubusercontent.com/651824/61686434-505bc780-ad28-11e9-817f-f726929af10a.png)

**Comment by tonsky** [comment]
pretty much the same :)
