### ISSUE TITLE
Permission for Nerd Fonts

### ISSUE THREAD

**Issue by ShalokShalom** [tonsky/FiraCode#767]
Would you give permission for this?

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode

**Comment by tonsky** [comment]
Like, you want to change it from Fura Code to Fira Code?

**Comment by ShalokShalom** [comment]
Yes. Its not my project, while yes. :D

**Comment by tonsky** [comment]
I’m happy as long as full font name is `Fira Code <Something>`. Like, `Fira Code Nerd` is fine by me
