### ISSUE TITLE
Error: The requested file is not a valid font file

### ISSUE THREAD

**Issue by jonny2plates** [tonsky/FiraCode#768]
As of 23/05/2019 - this prompt shows on install

**Comment by jonny2plates** [comment]
Occurred only when downloading via right click on the individual font file. The font opens fine when you pull the master/ download and install the font file contained in the folder.

**Comment by tonsky** [comment]
which link exactly have you tried to download?

**Comment by jonny2plates** [comment]
Please ignore it was the font files I was download Firacode.ttf
