### ISSUE TITLE
Dank Mono Font Ligatures

### ISSUE THREAD

**Issue by fourcolors** [tonsky/FiraCode#769]
Hi,
Here is a screenshot from iTerm2
<img width="229" alt="image" src="https://user-images.githubusercontent.com/51751/58353737-8e259800-7e2c-11e9-91c3-1fa5f4e5191d.png">

And this one is of kitty
<img width="229" alt="image" src="https://user-images.githubusercontent.com/51751/58353780-9ed60e00-7e2c-11e9-9ffb-6bc33b494657.png">

I'm not sure if the ligatures issue is a problem with the font or kitty? The font is DankMono. 

Would this be an issue with Kitty? Maybe something I have configured wrong?

**Comment by tonsky** [comment]
Maybe. Probably terminal. Try talking to kitty or Dank Mono folks

**Comment by fourcolors** [comment]
omg so sorry, I thought I was on the Kitty repo asking this 🤣
