### ISSUE TITLE
VF doesn't list weight instances correctly built from script (Win10, others?)

### ISSUE THREAD

**Issue by apollolux** [tonsky/FiraCode#770]
Hello! Fira Code is a great addition to my dev workflow, especially with its variable weight reducing the need for multiple files. The Fonts listing in Windows 10, however, shows its five defined weight instances as Regular even though they are at different weight values (300, 400, 450, 500, 700). If it's possible to edit the Metadata for the stored instances to reflect their correct names (or at least different ones) please do so, as I have little doubt it's like this in other programs as well.

Fira Code VF 1.207 on Windows 10 Pro (1809) 64-bit

**Comment by tonsky** [comment]
wait, VF is a variable font from https://github.com/tonsky/FiraCode/tree/master/distr/variable_ttf right? And it is listed as five separate weights, is that what you are saying? Do you have those weights installed as well? Or just that single TTF?

**Comment by apollolux** [comment]
I only have the single TTF (FiraCode-VF.ttf) from that variable_ttf folder installed. When I get back to that comp I'll put up a screenshot.

For what it's worth, I'm pleasantly surprised that Win10 has any support at all for variable fonts, and its pre-installed Bahnschrift variable font does show the correct names for pre-defined weight and width instances.

**Comment by tonsky** [comment]
Hmm I don’t see it. Maybe it’s specific to software you are using?

![IMG_2669](https://user-images.githubusercontent.com/285292/58633686-da238180-82f1-11e9-8df8-bbd3591599fb.jpg)

**Comment by apollolux** [comment]
The normal Win10 Fonts listing, finally got screens:

<img width="960" alt="fira-1" src="https://user-images.githubusercontent.com/493607/58752040-17188100-8476-11e9-8263-f334698fba95.PNG">
<img width="960" alt="fira-2" src="https://user-images.githubusercontent.com/493607/58752041-17188100-8476-11e9-887e-5d1a85257363.PNG">

**Comment by apollolux** [comment]
Bahnschrift's listing for comparison:

<img width="960" alt="bahnschrift" src="https://user-images.githubusercontent.com/493607/58752054-547d0e80-8476-11e9-92b2-225e5291c8ba.PNG">

**Comment by tonsky** [comment]
Ok I might take a look but can’t guarantee anything. Is Bahnschrift a variable font as well?

**Comment by apollolux** [comment]
Bahnschrift is indeed a variable font, yes.

**Comment by apollolux** [comment]
Hi! I just installed v2.000 of the variable Fira Code on a different Windows 10 install and am unfortunately still getting the weights all incorrectly listed as "Regular" in the font info window. Is there a setting in Glyphs where this would be editable? I'm only familiar with FontLab and I don't want to break anything that works by importing and exporting to a potentially wildly different glyphs or ufo file.

**Comment by tonsky** [comment]
VF is exported through bash scripts https://github.com/tonsky/FiraCode/tree/master/script. Maybe there’s a setting there

**Comment by tonsky** [comment]
Can you try this file? It was exported from Glyphs directly

[FiraCodeGX.ttf.zip](https://github.com/tonsky/FiraCode/files/3905796/FiraCodeGX.ttf.zip)

**Comment by apollolux** [comment]
![fonts-20191203](https://user-images.githubusercontent.com/493607/70066798-4b066780-15bb-11ea-8818-2dd3770e0cb2.png)

The direct-from-Glyphs version does indeed retain the discrete weight instances. For the record, the screenshot shows the 5 correct ones AND the 5 incorrect "Regular" ones because I have both the original VF and the GX versions installed at the same time.

Seems there's something missing in the [build](https://github.com/tonsky/FiraCode/blob/master/script/build) script indeed, as it's the only one I see with any reference to building the variable version. Maybe need an updated fontmake or gftools or there's a command line argument to properly reference the instance names?

**Comment by apollolux** [comment]
For what it's worth, Inter (formerly Inter UI) seems to have the same build issue - rsms/inter#142 .

**Comment by tonsky** [comment]
Should be solved in d413865
