### ISSUE TITLE
Add support for ligatures with old-style numbers

### ISSUE THREAD

**Issue by j-f1** [tonsky/FiraCode#771]
I’m a big fan of old-style numbers (the kind where some numbers go below the baseline; [here’s an example font that does this by default](https://fonts.google.com/specimen/Merriweather)) and I was delighted to see that Fira Code supports them. However, when old-style numbers are enabled, ligatures no longer work. Would it be possible to fix this?

**Comment by tonsky** [comment]
Yes, I’ll take a look. See #561

**Comment by j-f1** [comment]
Sorry, didn’t see the duplicate when I searched.
