### ISSUE TITLE
Make the difference between a short dash, en dash and em dash more visible

### ISSUE THREAD

**Issue by xgouchet** [tonsky/FiraCode#772]
In some document I write, I'm using three types of dashes : 
- A simple dash `-` (2D)
- An en dash `–` (E2 80 93)
- An em dash `—` (E2 80 94)

When using Fira Code, it's very hard to know at a glance which one is which. It would be nice to have more difference between those to help readability.

**Comment by tonsky** [comment]
I’d be happy to help but this is a monospaced font, not much I can do. See also https://github.com/tonsky/FiraCode/issues/428
