### ISSUE TITLE
Embedding Fira Code in Tiddlywiki

### ISSUE THREAD

**Issue by CrossEye** [tonsky/FiraCode#775]
I recently wrote a plugin for TiddlyWiki to embed Fira Code, and I'd like to make sure it's not running afoul of any rules or conventions here.

[TiddlyWiki][tw]  is a tool to create portable single-file wikis.  All text content, stylesheets, scripts, images, etc. are stored in a single HTML file and viewed and edited in the browser. I use it for my own note-taking and for software documentation.  Obviously Fira Code is a good fit for such documentation.  So I created a plugin to make it easier to embed.  The plugin is hosted at http://scott.sauyet.com/tiddlywiki/plugins/FiraCode.html.  (Note that I have [one report][re] of a problem on Windows computers.  If I can replicate it, this plugin may have to change, but I would expect it to be substantially the same.)

I guess the biggest question is whether my including the `all_ligatures.png` image from the Fira Code README is all right.  But if there are any other concerns, please let me know.

  [re]: https://groups.google.com/d/msg/tiddlywiki/9Ro-EDpTB7Y/RFVdjOVRBAAJ 
  [tw]: https://tiddlywiki.com/

**Comment by tonsky** [comment]
Feel free to include images and the font. Glad you chose Fira Code!
