### ISSUE TITLE
KDevelop 5 has support for font ligatures.

### ISSUE THREAD

**Issue by Dracovian** [tonsky/FiraCode#776]
If you're running with the latest builds of KDevelop then you can see font ligature support:

![Font Ligatures in KDevelop 5](https://i.imgur.com/P9A462K.png)

Here's the full set of font ligatures as seen in the README.md:

![All Font Ligatures in KDevelop 5](https://i.imgur.com/7bNpqqS.png)

So I suppose it's time to add KDevelop 5 to the working editor support table in the README.md.

**Comment by tonsky** [comment]
Thanks!
