### ISSUE TITLE
Fira Code Bold not appearing in Android Studio

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [tonsky/FiraCode#777]
I have it installed and all Fira Code are appearing except Bold. I installed Fira Mono Bold and it is appearing.

Is there any way to use Fira Code Medium slightly thicker? In Windows it seems too thin.

**Comment by vctrlt** [comment]
The same issue happens (Fira Code Bold not appearing) in PhpStorm 2019.1.3 / macOS 10.14.5.

**Comment by tonsky** [comment]
Normally individual font weights should not appear at all, because they all share same font family. Maybe there’s an exception for Fira Code. Consider asking about details in https://youtrack.jetbrains.net/
