### ISSUE TITLE
Typing << Appears Blank

### ISSUE THREAD

**Issue by Mario253** [tonsky/FiraCode#778]
I only recently installed Fira Code, and it looked amazing. However, I was forced to use the Fira Mono for Powerline font instead, because typing << in the terminal appeared as simply two blank spaces, which made it hard to read my zshrc (I use antigen). Is there any way to disable this?

W/O FiraCode (Fira Mono for Powerline Regular):
![Screenshot 2019-06-08 at 13 57 27](https://user-images.githubusercontent.com/32368758/59151262-a7fed780-89f5-11e9-8199-80682e6630d5.png)

W/ FiraCode:
![Screenshot 2019-06-08 at 13 57 52](https://user-images.githubusercontent.com/32368758/59151263-b0efa900-89f5-11e9-8e72-2f909269d9e1.png)

**Comment by tonsky** [comment]
Thanks! Added xterm to unsupported list
