### ISSUE TITLE
Stop imposing your religion on me.

### ISSUE THREAD

**Issue by EvanCarroll** [tonsky/FiraCode#784]
I realize that Joseph Smith was not a fan of alcohol. But, as a non-mormon, it is a great disappointment to me that the Beer Mug is not officially supported by this font. The temperance movement has failed. We're not all teetotalers, and I would like to suggest that 

* [🍺 U+1f37a Beer mug](https://www.fileformat.info/info/unicode/char/1f37a/index.htm)

be supported in a future revision of Fira Code. Perhaps we may also want to support 1f37a,

* [Unicode Character 'CLINKING BEER MUGS' (U+1F37B)](https://www.fileformat.info/info/unicode/char/1f37b/index.htm)

Thanks!

**Comment by tonsky** [comment]
Emoji is a huge block that would require impossible amount of effort to implement. I don’t see a point in adding just one or two emojis. Thanks for the idea though
