### ISSUE TITLE
Request for ligature for :-

### ISSUE THREAD

**Issue by quantumfrost** [tonsky/FiraCode#790]
`:-` is used to separate the head and body of a rule in AnsProlog:
`foo :- bar(X), baz(X).`

Thanks!

**Comment by tonsky** [comment]
Thanks for the suggestion! I think this only can be added with space right after `-`. Otherwise it will conflict with stuff like `{x:-1}`

**Comment by quantumfrost** [comment]
That's alright, since most people would put a space after the `-` anyway. Thanks!

**Comment by tonsky** [comment]
Will be in v6 as `cv26`
