### ISSUE TITLE
Logical symbols

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#794]
Support for `\/` (`∨`), `/\` (`∧`), `^\/` (`⊻`), `!/\` (`⊼`), `!\/` (`⊽`), maybe `~` (`¬`) because `!` is too false-positivey.

I really use fira code for logic as of the natural `->` and `=>`, as well as `===`

**Comment by RubenVerg** [comment]
Ik most were posted, please link them .~.

**Comment by RubenVerg** [comment]
#738 found

**Comment by RubenVerg** [comment]
Oh yeah regexp mess... Well actually not cuz if they are just joined ( /\ instead of / \ ) you can still read as / \ easily.

**Comment by tonsky** [comment]
Duplicate of #738
