### ISSUE TITLE
Add fl/fi ligatures

### ISSUE THREAD

**Issue by sahil48** [tonsky/FiraCode#795]
Right now it feels that there is too little spacing between the f and l characters when they are next to each other. I feel that the font would look better if they would be replaced with an fl ligature, or the top half-serif on the l could be shortened.

![image](https://user-images.githubusercontent.com/6100774/61375083-f3659a80-a86b-11e9-9bf5-9c3c33895d4f.png)

**Comment by lengthmin** [comment]
![image](https://user-images.githubusercontent.com/13938334/65026400-11827080-d96b-11e9-8849-7eb6fbb2042c.png)
It made me very uncomfortable...
feel bad.

**Comment by awmottaz** [comment]
I agree, not a big fan of how this turned out

**Comment by sahil48** [comment]
Referring to the initial example, perhaps instead, the fl ligature could be created where there is more separation between the "f" and "l" rather than fusing them together.

**Comment by Avi-D-coder** [comment]
Fira Mono does not have these ligatures, if we must have them can they at least be consistent with Fira sans?

Currently they are jarring. Where as I hardly notice Fira sans `fl` and `fj` ligatures.

**Comment by adah1972** [comment]
I agree with many commenters that these ligatures look pretty bad. I would advocate these changes should be reverted.

I do not think such ligatures should be enabled in a monospace font.

**Comment by Avi-D-coder** [comment]
I removed these ligatures and built [otf](https://github.com/Avi-D-coder/FiraCode/tree/master/distr/otf)

**Comment by adah1972** [comment]
@Avi-D-coder Thanks. Did you make a pull request to this master project?

**Comment by VideoPlayerCode** [comment]
@tonsky Hi Nikita. Have you seen the discussion here? Many people (including me) strongly dislike these ligatures. They look jarring in a monospace font. And worst of all, `Tl` looks like `π` (pi). Wtf. Hehe. Please make these ligatures optional via `ss` setting... :-(
