### ISSUE TITLE
Font width matters!

### ISSUE THREAD

**Issue by archtaurus** [tonsky/FiraCode#796]
I noiced in an old issue, author said change the charact width is difficult and ....
But I wish you consider this issue agian, please. See below tow pics which compare Fira Code with Ubuntu Mono ... Ubuntu Mono 's font is always twice wider of Chinese char, that would be very nice!
Do you think so?

![1](https://user-images.githubusercontent.com/1265068/61454404-69b0ec80-a993-11e9-982d-1eb15f884db3.png)

![2](https://user-images.githubusercontent.com/1265068/61454408-6d447380-a993-11e9-9680-65a2b2ed5f55.png)

At least Chinese and Japanese users will thank your later hard work :)

**Comment by archtaurus** [comment]
Oh, sorry to say thanks for your font!!!

**Comment by tonsky** [comment]
Thing is, it’s not about my font. As you can see on both screenshots, asian glyphs are rendered with the same font in both cases, a fallback font that actually has those characters. Fira Code doens’t have them, nor does Ubuntu Mono. I have no idea why those render different spacing in that case, really strange

**Comment by archtaurus** [comment]
OK，I see. Wish everything would be perfect tomorrow.发自我的华为手机-------- 原始邮件 --------主题：Re: [tonsky/FiraCode] Font width matters! (#796)发件人：Nikita Prokopov 收件人：tonsky/FiraCode 抄送：Zhao Xin <7176466@qq.com>,Author Thing is, it’s not about my font. As you can see on both screenshots, asian glyphs are rendered with the same font in both cases, a fallback font that actually has those characters. Fira Code doens’t have them, nor does Ubuntu Mono. I have no idea why those render different spacing in that case, really strange



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/tonsky/FiraCode/issues/796?email_source=notifications\u0026email_token=AAJU3LACL56S4EUEHKG3ZGTQABVYPA5CNFSM4IEZZQY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2IPC3I#issuecomment-512815469",

"url": "https://github.com/tonsky/FiraCode/issues/796?email_source=notifications\u0026email_token=AAJU3LACL56S4EUEHKG3ZGTQABVYPA5CNFSM4IEZZQY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2IPC3I#issuecomment-512815469",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by lonre** [comment]
the same issue here
