### ISSUE TITLE
WebStorm 2019.1.3 ligatures problem

### ISSUE THREAD

**Issue by MacOSO** [tonsky/FiraCode#797]
An extra element appeared near each ligature.
![image](https://user-images.githubusercontent.com/8469236/61606101-dc131c80-ac72-11e9-85e7-3f2626ae0105.png)

**Comment by tonsky** [comment]
Report to webstorm? https://youtrack.jetbrains.net/issues?q=%23WebStorm%20

**Comment by tonsky** [comment]
To myself:

See if this might be the reason: https://github.com/tonsky/FiraCode/commit/2202877946b191b88f41a01b018958015fbfe64c

(some precision loss in dotaccentcomb due to downgraded version of Glyphs)
