### ISSUE TITLE
Add macOS keyboard symbols ⌘ ⌥ etc

### ISSUE THREAD

**Issue by butuzov** [tonsky/FiraCode#799]
Found that some of the glyphs isn't monospaced on mac `⌘` (Cmd), `⌥` (Alt)

FontFace - `Fira Code`

![image](https://user-images.githubusercontent.com/651824/61685379-3d93c380-ad25-11e9-85ce-c7dbc22fac40.png)

**Comment by butuzov** [comment]
Guess other icons should be added

![image](https://user-images.githubusercontent.com/651824/61687187-6e2a2c00-ad2a-11e9-94f2-6ac69d6352f3.png)

**Comment by tonsky** [comment]
Thanks! They are not non-monospaced, they are simply not in the font, so what you see is taken from a fallback font instead

**Comment by butuzov** [comment]
Got it. Damn, I used to find everything in your font. 
Any plans on adding these glyphs?

**Comment by tonsky** [comment]
Added them to the queue

**Comment by butuzov** [comment]
Wonderful news! thank you.
