### ISSUE TITLE
Some symbols are bold with Retina font

### ISSUE THREAD

**Issue by svipas** [tonsky/FiraCode#800]
Hi @tonsky,

I don't know if this problem existed in the 
previous version, but in 1.207 with `FiraCode-Retina` in `VS Code` I see some symbols bold, but with `Fira Code` (without Retina) everything is OK.

**`FiraCode-Retina`**
<img width="48" alt="Screen Shot 2019-07-23 at 17 17 18" src="https://user-images.githubusercontent.com/10441177/61719617-efef7900-ad6d-11e9-8f80-3854403da4c9.png">

**`Fira Code`**
<img width="48" alt="Screen Shot 2019-07-23 at 17 17 29" src="https://user-images.githubusercontent.com/10441177/61719644-fed62b80-ad6d-11e9-931d-af5674ed4e32.png">

**Comment by tonsky** [comment]
Maybe it’s your syntax highlighting? Try switching that file to plaintext?

From the closer examination, that dollar sign does not seem to come from Fira Code at all. Not sure abount Euro/Pound.

<img width="874" alt="Screenshot 2019-07-23 at 18 33 48" src="https://user-images.githubusercontent.com/285292/61725468-82951580-ad78-11e9-8f18-4882a621acac.png">

**Comment by svipas** [comment]
@tonsky My bad, seems it's like the custom symbol I tried to copy-paste from Wikipedia dollar sign and it works as expected (not bold). But out of curiosity, why it's not bold in `Fira Code`, but bold in `FiraCode-Retina`? Because `Retina` it's a little bit heavier?

<img width="697" alt="Screen Shot 2019-07-23 at 20 31 56" src="https://user-images.githubusercontent.com/10441177/61733653-ed4e4d00-ad88-11e9-94ab-ebafbc75e976.png">

Since it looks like not Fira Code problem I believe this can be closed?

**Comment by alexeyten** [comment]
https://emojipedia.org/heavy-dollar-sign/ I guess

**Comment by tonsky** [comment]
> why it's not bold in Fira Code, but bold in FiraCode-Retina?

both of them are not from Fira Code, but from a fallback font. I guess system tries to match weight of fallback font to the weight of font you are using as close as it can. That’s regular for 400 and bold for everything after 400 (fallback font prob only have two weights)
