### ISSUE TITLE
Font is broken in recently released IntelliJ IDEA 2019.2 in MacOS

### ISSUE THREAD

**Issue by stanislav-bios-baranov** [tonsky/FiraCode#802]
![image](https://user-images.githubusercontent.com/13099551/61939020-a5027b00-af92-11e9-86d7-cee5e5f55fa1.png)

![image](https://user-images.githubusercontent.com/13099551/61939066-b9467800-af92-11e9-9aab-401b255cdbee.png)

![image](https://user-images.githubusercontent.com/13099551/61939092-c8c5c100-af92-11e9-8229-5d1f9c22fb3f.png)

**Comment by tonsky** [comment]
Please report it to IntelliJ Idea

Best,
Nikita

**Comment by stanislav-bios-baranov** [comment]
> Please report it to IntelliJ Idea

https://youtrack.jetbrains.com/issue/IDEA-219154

**Comment by stanislav-bios-baranov** [comment]
Appeared it would be fixed in IDEA 2019.2.2 or 2019.2.3

https://youtrack.jetbrains.com/issue/JBR-1624
