### ISSUE TITLE
U+2215 division slash is misaligned

### ISSUE THREAD

**Issue by andrewarchi** [tonsky/FiraCode#805]
The division slash does not render correctly for me on the current version of Fira Code. Division slash 0x2215 is commonly used in Go assembly code, along with 0xB7 middle dot.

With Fira Code:
![Screen Shot 2019-07-31 at 14 15 27](https://user-images.githubusercontent.com/8071784/62249281-e2a24200-b39e-11e9-85bb-32a737054aa3.png)

Without Fira Code:
![Screen Shot 2019-07-31 at 14 15 46](https://user-images.githubusercontent.com/8071784/62249293-e930b980-b39e-11e9-9e18-354a40b97f41.png)

https://github.com/tonsky/FiraCode/issues/588 is similar, but for a separate glyph.

**Comment by tonsky** [comment]
Thanks! I’ll take a look

**Comment by tonsky** [comment]
Fixed in aa6c914
