### ISSUE TITLE
the Chinese characters are quite ugly

### ISSUE THREAD

**Issue by TianLiPa** [tonsky/FiraCode#812]
![image](https://user-images.githubusercontent.com/36751442/62997692-a8a36680-be9b-11e9-803c-7f3722a73d32.png)
using sublime text 3.

**Comment by tonsky** [comment]
There are no Chinese glyphs in Fira Code. What you see is a fallback font chosen by your system. See https://github.com/tonsky/FiraCode/wiki#4-characters-look-weird-not-monospaced-not-rendered-at-all
