### ISSUE TITLE
Notepad++ Fira Code Retina some letters display bug

### ISSUE THREAD

**Issue by Dmitresso** [tonsky/FiraCode#813]
Windows 7 (64-bit) SP1, [gdipp](https://github.com/CoolOppo/GDIPP), [FiraCode 1.207](https://github.com/tonsky/FiraCode), [Notepad++ v7.7.1 (64-bit)](https://github.com/notepad-plus-plus/notepad-plus-plus)
Bug reproduces with **only** regular FiraCode Retina, 9pt.
If enable bold/italic, bug doesn't reproduces.
"Magic" character must be standalone. I don't tknow how I made 1-st screenshot where "magic" "F" prefixed by dash symbol, I can't reproduce this bahavior.
Look at screenshots:

**Comment by Dmitresso** [comment]
Can't reproduce.

**Comment by alexeyten** [comment]
I’ve seen this bug when replaced font file while application use it. Restarting app helped
