### ISSUE TITLE
Python ligature request: //=

### ISSUE THREAD

**Issue by jthistle** [tonsky/FiraCode#816]
This is an operator in Python similar to `/=`. Since `//` is integer division (divide by and discard any remainder), `//=` is used to do this in place. This might not be very common to see, but would be nice for completeness. Thanks!

**Comment by j-f1** [comment]
It’s also used (for a completely different purpose) in a Rails/JavaScript environment, like so:

```js
//= require foo
```

**Comment by tonsky** [comment]
Ok thanks I’ll try

**Comment by jthistle** [comment]
Thank you!
