### ISSUE TITLE
Atom 1.3.1/OS X 10.11: No fancy symbols.

### ISSUE THREAD

**Issue by IngwiePhoenix** [tonsky/FiraCode#82]
So I just found this project randomly and I am all over this. This just looks amazing - period. So I downloaded a ZIP using the Github "Download ZIP" button, and went ahead and installed all the font files on the root level.

So far, so good.

So I opened atom and entered the snippet suggested into my "user stylesheet". Then, I went into settings and in font family, I wrote "Fira Code".

But after reloading, I saw no fancy things. To test this, I put a whole bunch of the symbols I frequently use in a comment in the same style sheet. But, unfortunately, to no avail.

Is there something I did wrong?

**Comment by tonsky** [comment]
What language syntax did you use when you checked for ligatures? Some of them don’t work in some syntaxes, e.g. `->` and `=>` in js or ruby (tokenization issue, see #63 and #69).

Try setting it to “Plaint text” and see if you can get something working.

Otherwise, can you post a content of your style.less so I can see if there’re some typos there?

**Comment by IngwiePhoenix** [comment]
I was using LESS, since I just punched the signs into a comment line.

Anyway, this screenshot should explain everything:
https://www.dropbox.com/s/zg7sr9aesrwtmw2/Screenshot%202015-12-20%2020.08.16.png?dl=0

**Comment by MadcapJake** [comment]
That's definitely not Fira Code.  The font didn't get set properly.

**Comment by MadcapJake** [comment]
In your font box you have `Fira Coda` but it's actually `Fira Code`

**Comment by IngwiePhoenix** [comment]
Oh! and magically everything works.

... Oops :). Well thanks for your help! (I oversaw that, because I am nearly blind. So that kinda slipped me good.)
