### ISSUE TITLE
Add set operations

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#822]
U+222A ∪
U+2200 ∀
U+2203 ∃
U+2204 ∄
U+2205 ∅
U+2207 ∇
U+2282 ⊂
U+2283 ⊃
U+2284 ⊄
U+2285 ⊅
U+2208 ∈
U+2209 ∉
U+220A ∊
U+220B ∋
U+220C ∌
U+220D ∍

**Comment by rodolphito** [comment]
Awesome! If you're gonna add union ∪, you should also get intersection ∩. Also ⊆ ⊇ to complete ⊂ and ⊃.
