### ISSUE TITLE
beautiful

### ISSUE THREAD

**Issue by anyanqi** [tonsky/FiraCode#824]
Is it possible to design a symbol like <!xxxx> more beautiful?

**Comment by tonsky** [comment]
what’s <!xxxx>?

**Comment by anyanqi** [comment]
For example, the comment of the xml file feels different from other angle brackets.

**Comment by tonsky** [comment]
What do you mean? That’s the idea of the font, make certain combinations of symbols look like a whole, not like sum of their parts

**Comment by anyanqi** [comment]
Ok, thanks for the reply, it’s very good.
