### ISSUE TITLE
Visual Studio Code support?

### ISSUE THREAD

**Issue by faizaanceg** [tonsky/FiraCode#83]
The README mentions only Visual Studio. Is there support for VSCode ?

**Comment by faizaanceg** [comment]
Just checked. Doesn't work.

**Comment by tonsky** [comment]
Yep, they’re probably on an old Electron. Added that to README

**Comment by faizaanceg** [comment]
So I did some digging (should have done it earlier :/ ) https://github.com/Microsoft/vscode/issues/192#issuecomment-164914391

They do support it, the same way Atom does but they have some of the bugs mentioned in https://github.com/atom/atom/issues/3821 . So I wouldn't call it works but almost-working fits the bill.
