### ISSUE TITLE
Update && for ss03

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#831]
@tonsky you missed the `<$`, `<$>` and `$>` ligatures for the `ss04` and shouldn't maybe the `&&` with `ss03` look more like ![grafik](https://user-images.githubusercontent.com/325196/64573571-09737100-d36c-11e9-8960-7034316d5271.png) than like ![grafik](https://user-images.githubusercontent.com/325196/64573599-2b6cf380-d36c-11e9-9395-b3d9fb30d6ef.png)?

_Originally posted by @Vampire in https://github.com/tonsky/FiraCode/issues/617#issuecomment-529708534_

**Comment by Coder-256** [comment]
IMHO I'm not a huge fan of a ligature for `&&` with `ss03`, but on the other hand `&=` might be worth considering (bitwise AND and assignment, in many languages). I am interested to hear what other people think.

**Comment by tonsky** [comment]
I tried couple of times but can’t figure out how to make that connection look good. Sorry

**Comment by Vampire** [comment]
You don't like my suggestion? :-(

**Comment by tonsky** [comment]
They are quite apart to be joined like that. And extending the tails didn’t do the job

**Comment by Vampire** [comment]
Hm, I don't understand what you mean.
Many ligatures are much narrower than their single chars.
The ligature of `<=` is half the size of the single characters.
So where do you see the problem in joining them like I depicted?
I also don't think extending the tails would be looking decent.

**Comment by Vampire** [comment]
I'm just wondering.
I have it like that in my manipulated FiraCode since years and it is looking quite good imho.

**Comment by tonsky** [comment]
The strokes have direction and logic. In your version it looks like one glyph was just moved behind the other. Which is one way to do it, I just don’t like it.

Re: distance, these are pretty complex characters, so I feel that moving them close together will make them harder to read and will create more of a mess.

**Comment by tonsky** [comment]
I looked at what other fonts with an ampersand like that do. Some just remove one of the tails inside. Would that work?
<img width="536" alt="Screenshot 2020-04-06 at 09 44 08" src="https://user-images.githubusercontent.com/285292/78534752-3f39e480-77eb-11ea-87da-fad9948ec9f3.png">

**Comment by Vampire** [comment]
I don't know.
That looks strange, but it might just be so because of it being so big to look at.
I can only say that I work with the joined version I suggested for years and like it.
If you think it is not good and too hard to read, then not, that's ok.
I was just curious what your reason was. :-)
