### ISSUE TITLE
SCSS #{ bug?

### ISSUE THREAD

**Issue by burtek** [tonsky/FiraCode#832]
In VSCode, `#{` inside a string preceded by a valid scss @at-command is rendered differently...

![image](https://user-images.githubusercontent.com/2940958/64612785-efba4400-d3d4-11e9-8306-2b851561ea9e.png)

**Comment by burtek** [comment]
Not sure if #417 is same...

**Comment by j-f1** [comment]
This is because in the second case, the `#` and the `{` are different colors, so Fira Code is not able to apply the ligature.

**Comment by burtek** [comment]
So `#{` is a real ligature? 🤔

**Comment by tonsky** [comment]
Yes, `#{` is a ligatures, and as @j-f1 mentioned it is broken up by tokenizer in the second case. Wiki entry https://github.com/tonsky/FiraCode/wiki#some-ligatures-work-while-some-dont

**Comment by burtek** [comment]
Got that, thanks!
