### ISSUE TITLE
Ligature Request: /->

### ISSUE THREAD

**Issue by shamansir** [tonsky/FiraCode#835]
Fira Code 2 is just awesome and has almost all the things I use, special thanks for the `/\`, I use it for Tuples in PureScript / Haskell.

However, I also use the made up type operator for Maps as well, and it is `/->`. I've seen it somewhere some time ago and decided to use it, and still use for more than a year or so.

It looks good in the Haskell-like type definitions:

```Haskell
empty :: forall k v. k /-> v

isEmpty :: forall k v. (k /-> v) -> Boolean

singleton :: forall k v. k -> v -> (k /-> v)

lookup :: forall k v. Ord k => k -> (k /-> v) -> Maybe v
```

Since the `Map` type is approximately isomorphic to the function of type `k -> Maybe v`, `k /-> v` represents this fact, i.e. `/` slash is intended to represent the uncertainness of `Maybe`.

**Comment by cblp** [comment]
Motivation is too specific

**Comment by shamansir** [comment]
@cblp I suppose the ligature may be used in any other meanings too, the motivation was just an example of why it may has sense to add it to the font.

**Comment by tonsky** [comment]
I try to add well-established combinations only. If it was in a popular package. Would `|->` work for you? It’s already in the font :)

**Comment by shamansir** [comment]
Yeah, that could work, and I can live quite ok w/o `/->` as a ligature as well :). If there are no more request for it, let's close it then.
