### ISSUE TITLE
Firacode font in ChromeOS causes cursor to get off

### ISSUE THREAD

**Issue by superm1** [tonsky/FiraCode#837]
I have found that by using the instructions available here: https://github.com/tonsky/FiraCode/wiki/ChromeOS-Terminal cause the cursor to get off in crostini (using ChromeOS terminal).

![Screenshot 2019-09-11 at 13 23 34](https://user-images.githubusercontent.com/494526/64696929-99620980-d497-11e9-8769-d8fc6f66f7d7.png)

**Comment by tonsky** [comment]
I’m sorry to see that. You should probably report it to the crostini or CromeOS-Terminal though

**Comment by superm1** [comment]
OK thanks!
