### ISSUE TITLE
IntelliJ problem

### ISSUE THREAD

**Issue by MrIvanPlays** [tonsky/FiraCode#839]
I have installed v2 on my windows pc, however intellij is overriding the font with an older version in the program. How could I fix this?

**Comment by deae** [comment]
the idea embed font is in the **/jrb/lib/fonts** folder, just replace with the fira code font v2.

**Comment by MrIvanPlays** [comment]
Thanks

**Comment by tonsky** [comment]
As far as I know, that was a regression and Jetbrains promised to fix that in 2019.3

**Comment by gmr458** [comment]
2022 and still not fixed
