### ISSUE TITLE
Add common set/type symbols

### ISSUE THREAD

**Issue by zoickx** [tonsky/FiraCode#841]
U+2115 ℕ (nat)
U+2119 ℙ (prop)
U+2124 ℤ (int)
U+1D539 𝔹 (bool)

These would be very useful for (among many others) anyone working with the [Coq proof assistant](https://coq.inria.fr/).

**Comment by zoickx** [comment]
Seems like a good addition to #822

**Comment by tonsky** [comment]
Thanks! I agree
