### ISSUE TITLE
Can we get the alternative stylistic set in a different binay 

### ISSUE THREAD

**Issue by vikky49** [tonsky/FiraCode#842]
Can we get the alternative stylistic set in a different binary .. For most us who use IDE like Intelli J or Android Stuido its not possible enable them . I kind of like the new "r" and the regular & symbols but unfortunately my IDE's limit me from not being able to use them

**Comment by marcin-kozinski** [comment]
Hi :)

Came here wondering a very similar thing—would love to use stylistic sets in JetBrains IDEs. The right approach is obviously for JetBrains to add support for that and everyone interested should thumbs up this feature request: https://youtrack.jetbrains.com/issue/IDEA-221886

However, in the meantime I was wondering about a separate binary with some stylistic sets tweaked. Obviously it's not scalable to release alternative binaries as part of the library. Currently there are 8 stylistic sets, which means 256 binaries for all combinations anyone might want to get.

But do you think it's possible and do you have any pointers for motivated power users to build their own binaries with stylistic sets tweaked? Would I do that by editing the `FiraCode.glyphs` file? Do I need the Glyphs app for that?

**Comment by tonsky** [comment]
I’d love to have scripts to bake in some SS into binary. Fira Code can be built using open-source scripts (see https://github.com/tonsky/FiraCode/#building-fira-code-locally). Altering glyphs requires Glyphs app though (but there are open editors that can edit OTF/TTF directly)

**Comment by marcin-kozinski** [comment]
Thanks, will check out the TTF editors!

**Comment by djensen47** [comment]
Same goes for VS Code. It should just be built in; that recommended plugin is definitely a work-around at best. Thanks for the great font!

**Comment by alvinhochun** [comment]
I just spent an afternoon to set up a build environment to hack my stylistic set preferences into the font.

As an example, this is what I changed in order to bake in ss01, ss03 and ss05:

```diff
diff --git a/FiraCode.glyphs b/FiraCode.glyphs
index 68a7f1c..89914f6 100644
--- a/FiraCode.glyphs
+++ b/FiraCode.glyphs
@@ -12465,8 +12465,8 @@ width = 1200;
 unicode = 0071;
 },
 {
-color = 4;
-glyphname = r;
+color = 6;
+glyphname = r.ss01;
 lastChange = "2019-03-25 21:13:22 +0000";
 layers = (
 {
@@ -12580,7 +12580,6 @@ nodes = (
 width = 1200;
 }
 );
-unicode = 0072;
 },
 {
 color = 7;
@@ -14920,8 +14919,8 @@ width = 1200;
 );
 },
 {
-color = 6;
-glyphname = r.ss01;
+color = 4;
+glyphname = r;
 lastChange = "2019-09-02 12:20:31 +0000";
 layers = (
 {
@@ -15015,6 +15014,7 @@ nodes = (
 width = 1200;
 }
 );
+unicode = 0072;
 },
 {
 color = 9;
@@ -93398,8 +93398,8 @@ width = 1200;
 unicode = 2408;
 },
 {
-color = 4;
-glyphname = at;
+color = 6;
+glyphname = at.ss06;
 lastChange = "2019-03-25 21:13:22 +0000";
 layers = (
 {
@@ -93539,11 +93539,10 @@ nodes = (
 width = 1200;
 }
 );
-unicode = 0040;
 },
 {
-color = 4;
-glyphname = ampersand;
+color = 6;
+glyphname = ampersand.ss03;
 lastChange = "2019-03-25 21:13:22 +0000";
 layers = (
 {
@@ -93667,7 +93666,6 @@ nodes = (
 width = 1200;
 }
 );
-unicode = 0026;
 },
 {
 color = 4;
@@ -99138,8 +99136,8 @@ width = 1200;
 unicode = 240B;
 },
 {
-color = 6;
-glyphname = ampersand.ss03;
+color = 4;
+glyphname = ampersand;
 lastChange = "2019-09-02 16:14:17 +0000";
 layers = (
 {
@@ -99293,10 +99291,11 @@ nodes = (
 width = 1200;
 }
 );
+unicode = 0026;
 },
 {
-color = 6;
-glyphname = at.ss06;
+color = 4;
+glyphname = at;
 lastChange = "2019-09-09 16:35:06 +0000";
 layers = (
 {
@@ -99460,6 +99459,7 @@ nodes = (
 width = 1200;
 }
 );
+unicode = 0040;
 },
 {
 color = 4;
```

I did it rather blindly. I just searched for the original glyph and the alternative glyph and swap their identifications. I don't even know what the `color` attribute means but I figured I'd swap them as well. It works for me.

**Comment by hkbakke** [comment]
I am also looking for a way to pre-bake the ss-preferences into the binary. There is no hype that stylistic sets is getting global application support, so this is pretty much the only way to fix the defaults for '@', '&' and 'r'

**Comment by tonsky** [comment]
color doesn’t mean anything, really. Font designers use it to mark glyphs for their own purposes, much like dev tags

**Comment by dustin-tridius** [comment]
> I did it rather blindly. I just searched for the original glyph and the alternative glyph and swap their identifications. I don't even know what the `color` attribute means but I figured I'd swap them as well. It works for me.

Works great!  Thanks for this.  Made the changes to FiraCode.glyphs and executed ./script/build_ttf.  No more weird r's!

**Comment by dustin-tridius** [comment]
@alvinhochun
Works great! Thanks for this. Made the changes to FiraCode.glyphs and executed ./script/build_ttf. No more weird r's!

**Comment by vikky49** [comment]
@alvinhochun  Would you be able to make the patch of your change and upload here .When i tried making the same changes i am getting an error .. i guess i must have messed up some thing

**Comment by alvinhochun** [comment]
@vikky49 I've already included the patch in my previous reply. If you copy the text inside the code block verbatim it should work.

**Comment by dok42** [comment]
> 
> 
> @vikky49 I've already included the patch in my previous reply. If you copy the text inside the code block verbatim it should work.

Hi, could you explain how to do that? 
I'm editing the file by hands, but I'm looking to automate as much as possible this task for future releases.

**Comment by jjqtony** [comment]
> 
Could you upload your glyphs file?
