### ISSUE TITLE
Make pipe | shorter

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#843]
Thanks for the good work. But in my personal opinion, the new `|` seems too tall in normal code. Now the `||` is way taller than `&&`, which seems inconsistent. Also, some related ligatures is inconsistent to this taller `|`, like `|=`

![2019-09-15_11-24-04](https://user-images.githubusercontent.com/1308450/64916186-5fe91100-d7ab-11e9-8c11-2c1dfe5329b2.png)

---

EDIT: I'm talking about the ASCII symbol `|` (U+007C) instead of the BOX DRAWINGS LIGHT VERTICAL `│` (U+2502). In v2.0, the `|` (U+007C) becomes taller, which I think is a mistake.

_Originally posted by @blahgeek in https://github.com/tonsky/FiraCode/issues/449#issuecomment-531531138_

**Comment by tonsky** [comment]
It became taller to match full block height in progressbar:

```
     |████████████████████████████████| 102kB 4.6MB/s 
```

Maybe it’s not such a good idea.

**Comment by tonsky** [comment]
Actually now I’m thinking that I can detect that specific case and alter the height in that case only

**Comment by blahgeek** [comment]
I think a proper progress bar should use U+2502 instead of U+007C anyway

**Comment by tonsky** [comment]
Tell that to pip authors :)

**Comment by j-f1** [comment]
> Actually now I’m thinking that I can detect that specific case and alter the height in that case only

What about when the bar isn’t all the way full?

     |████████████████████████        | 102kB 4.6MB/s

**Comment by tonsky** [comment]
Yeah, bad idea. Shame :(

**Comment by JakobBruenker** [comment]
I actually quite liked it last time I used a font with vertical bars this long, specifically for haskell's guards, and I like it here as well:

(github file attachment doesn't seem to work for me at the moment, so here's an imgur link)
https://i.imgur.com/KxQWNOU.png

If you end up removing it, maybe consider leaving it in as a stylistic set, I would appreciate it.

**Comment by tonsky** [comment]
Looks great in your screenshot. Thanks for that use-case!

**Comment by carlsmith** [comment]
Another vote for keeping the bar full-height.

**Comment by rumpelsepp** [comment]
`htop` is a bit hard to read with these long pipes:

![latest](https://user-images.githubusercontent.com/1961699/94140856-31951b80-fe6c-11ea-8517-4da739ac49eb.png)

vs. `Hack`

![latest](https://user-images.githubusercontent.com/1961699/94140900-45408200-fe6c-11ea-8f90-101bb7e97a5b.png)

**Comment by gyzerok** [comment]
Actually long bar was looking weird in Rust lambdas - `.filter(|x| { x == x })`, so the change is very nice. Thank you!
