### ISSUE TITLE
Arrow ligatures (`->`, `<-`)  not showing in F# code [Fira Code v2]

### ISSUE THREAD

**Issue by SteveGilham** [tonsky/FiraCode#846]
![Untitled1](https://user-images.githubusercontent.com/7460854/65228193-f4ac8100-dac1-11e9-860d-94b12637d433.png)

Note the `[|`, `|]` and `|>` ligatures (even if the former pair are now difficult to distinguish), but non-ligature `->` and `<-` pairs.

**Comment by tonsky** [comment]
See https://github.com/tonsky/FiraCode/wiki/Troubleshooting#some-ligatures-work-while-some-dont. I suggest opening an issue about it in F# syntax repo for your editor
