### ISSUE TITLE
MacVim is supported

### ISSUE THREAD

**Issue by greenboxal** [tonsky/FiraCode#85]
Rather than what is stated in the README, MacVim has support to font ligatures. You can turn it on with `set macligatures`.

I use the following in my .gvimrc on MacVim 7.4:

```vim
set macligatures
set guifont=Fira\ Code:h12
```

**Comment by tonsky** [comment]
Thanks for the heads-up! Added that to README and Wiki: https://github.com/tonsky/FiraCode/wiki/MacVim-instructions
