### ISSUE TITLE
<?= in PHP triggers the ?= ligature, looking weird

### ISSUE THREAD

**Issue by tabatkins** [tonsky/FiraCode#850]
`<?= $foo ?>` will immediately output the expression in the tags in PHP (it's a shorthand for `<?php echo($foo) ?>`).

Unfortunately, the `?=` ligature fires here, making the opener look a little weird.

Could we either disable the ?= ligature when it's immediately preceded by <, or add ligatures for PHP's `<?`/`<?php`/`<?=`/`?>`?

(Thanks so much for this font, btw!)

**Comment by tonsky** [comment]
Thanks! That’s the valid concern, I’ll try to fix it!
