### ISSUE TITLE
Firacode 2 does not work on Netbeans

### ISSUE THREAD

**Issue by emilime** [tonsky/FiraCode#851]
Hello,
I've used Firacode 1 with NetBeans without any problem, I just installed v2 and I discovered that it is no longer compatible with it, this is the result using Firacode v2:

![ScreenClip  12](https://user-images.githubusercontent.com/47943/65582853-76972100-df7e-11e9-8c4d-e1e3b0274756.png)

all characters are messed up :(

Is it possible to fix it?

**Comment by tonsky** [comment]
Try this https://github.com/tonsky/FiraCode/wiki/Troubleshooting#corrupted-font-in-intellij-on-windows

**Comment by emilime** [comment]
@tonsky it works! thanks
