### ISSUE TITLE
Adding the ligatures to a proportional font (like Fira Sans)

### ISSUE THREAD

**Issue by Qqwy** [tonsky/FiraCode#852]
It would be great if the wonderful operators present in Fira Code could be used in contexts where, for one reason or another, proportional fonts are being used.

A long time ago, Issue #21 was created, which asked to modify Fira Sans with Fira Code's ligatures.
Obviously this is probably out of scope for Fira Code itself. However, I would really like it to add Fira Code's ligatures to another font, such as that one.

What would be the most clever way to extract Fira Code's ligatures and add them to a different font at this time?

**Comment by tonsky** [comment]
Use font editor? Fira Code and Fira Sans sources are in Glyphs format but most editors can open ttf/otf font files directly too
