### ISSUE TITLE
Open question: should ligatures technically use 'dlig' rather than 'calt'?

### ISSUE THREAD

**Issue by thundernixon** [tonsky/FiraCode#854]
Hey Nikita, I am looking into implementing code ligatures in a font of my own, and as I'm thinking through it, I've come to a question: might it make more sense (and fit the OpenType spec better) for code ligatures to use discretionary ligatures (`dlig`) rather than contextual alternates (`calt`)?

I imagine you probably have a good reason for using `calt`, but I wanted to clarify my understanding of why. I've searched around the issues here, but couldn't find documented reasoning around this. If it is documented, please feel free to send a link! If not, I'm hoping you'd be willing to share your perspective and insights on this.

## The issue with using `calt`

A main issue with using `calt` is that in many contexts it that is enabled by default, including in general text editing on Mac (Keynote, Text Edit, Sketch, etc), Windows (Notepad), and web browsers (both Mac & Windows). While this may be nice in Fira Code, which has a fairly specific purpose, it makes code ligatures difficult to support in any more general-purpose fonts.

<details><summary><b>Screenshots of apps with Fira Code, no default settings changed</b> (Click to expand)</summary>

### Microsoft Notepad, Windows

![image](https://user-images.githubusercontent.com/7355414/66075408-8cca5180-e529-11e9-9129-c42022530d5a.png)

### Microsoft Edge, Windows

https://codepen.io/thundernixon/pen/yLBWzMd

![image](https://user-images.githubusercontent.com/7355414/66075441-9ce23100-e529-11e9-91fb-6015d6c808e6.png)

### Keynote, macOS

![image](https://user-images.githubusercontent.com/7355414/66075454-a7042f80-e529-11e9-861b-5c9712bedc91.png)

</details>

I definitely think code ligatures are really nice for those who want them (part of why I helped get Fira Code onto Google Fonts 🙂), but I also think they don't quite fall into the stated purpose of `calt` – better joining for connected scripts, and I don't think they should be on by default for two primary reasons:

1. Even if 20%+ of coders love them, anyone who is unfamiliar with them may find the more-complex ligatures confusing (`>=`, `!==`, etc). Therefore, they should probably require deliberate action to enable – similar to discretionary ligatures like the decorative "ct" connection in fonts like Adobe Caslon.

![image](https://user-images.githubusercontent.com/7355414/66075713-34478400-e52a-11e9-8dc6-7370378cdbea.png)

2. If all code ligatures on by default, it prevents a font from having some ligatures which are more subtle (for instance, a joined `&&` or a respaced `||`) and others which are more complex – but still useful for the iniated (like the `>=`).

![image](https://user-images.githubusercontent.com/7355414/66076965-ea13d200-e52c-11e9-8eac-e8f5671e53d7.png)

## What the OpenType spec says

From the OpenType spec:

> **[contextual alternates](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-calt)**
>
> **Function:** In specified situations, replaces default glyphs with alternate forms which provide better joining behavior. Used in script typefaces which are designed to have some or all of their glyphs join.
>
> **Example:** In Caflisch Script, o is replaced by o.alt2 when followed by an ascending letterform.
>
> **UI suggestion:** This feature should be active by default.

> **[discretionary ligatures](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-dlig)**
>
> **Function:** Replaces a sequence of glyphs with a single glyph which is preferred for typographic purposes. This feature covers those ligatures which may be used for special effect, at the user’s preference.
> 
> **Example:** The glyph for ct replaces the sequence of glyphs c t, or U+322E (Kanji ligature for “Friday”) replaces the sequence U+91D1 U+66DC U+65E5.
> 
> **UI suggestion:** This feature should be off by default.

## My question

I'm making Recursive, a variable font for code & UI. Because it is a somewhat general-purpose font, I can't have code ligatures on by default. However, because I'm working on this specifically for Google Fonts, they have asked me to not make two separate versions of the family (e.g. _Recursive_ without ligatures and _Recursive Code_ with ligatures).

Now, of course I don't necessarily need Fira Code to make a change in order to implement this in my own way, in a different font. However, I realize that you may have information that I'm missing, which may influence my approach. 

Also, of course, Fira Code is by far the most popular font with code ligatures, so what Fira Code does will strongly influence how apps like VS Code implement OpenType features and code ligature support. So, before I try to ask those apps to change their approach to better follow the spec (as I understand it, at least), I'm hoping to discuss what might be the best way to standardize things.

Thanks so much for any perspective / insights on this!

**Comment by j-f1** [comment]
One reason I feel that it makes sense for Fira Code to enable ligatures by default is that if you disable ligatures, you’re pretty much just using Fira Mono but with a larger download size.

**Comment by tonsky** [comment]
I don’t remember exactly but one reason why I put them into calt instead of liga/dlig is because lookups or subs I use didn’t work in liga/dlig. Are they working ok for you?

**Comment by arrowtype** [comment]
> One reason I feel that it makes sense for Fira Code to enable ligatures by default is that if you disable ligatures, you’re pretty much just using Fira Mono but with a larger download size.

@j-f1 True! for Fira Code, its main purpose _is_ to have code ligatures, so I agree with this. 

Still, it probably also has an extended glyph set, at this point, right? If so, it may serve purposes beyond Fira Mono, outside of just code ligatures.

**Comment by arrowtype** [comment]
@tonsky thanks for the helpful reply! Honestly, I still need to do some tests, but I'll update this when I find out.

**Comment by arrowtype** [comment]
I ran a test on this, swapping the `calt` code to the `dlig` feature in the `FiraCode.glyphs` source.

Here's the latest commit in that `dlig-test` branch: https://github.com/thundernixon/FiraCode/tree/58e1c17c3069e380a3600f8eeec639040433545a

(Light and Bold fonts were generated with FontMake, and [OTFs are here](https://github.com/thundernixon/FiraCode/tree/58e1c17c3069e380a3600f8eeec639040433545a/master_otf))

Here's a screenshot from Sketch app, with "rare ligatures" turned on (which seems the macOS name for `dlig` ligatures). I got this panel by `View > Show Fonts > [gear icon] > Typography...`.

![image](https://user-images.githubusercontent.com/45946693/66324860-43488080-e8f4-11e9-8f3f-29d763837899.png)

Here's another shot showing that the contextual lookups seem to be working as well as before (the `======` doesn't get ligatures at the beginning, as would happen without lookups):

![image](https://user-images.githubusercontent.com/45946693/66325661-a2f35b80-e8f5-11e9-979b-651fa1b326a1.png)

I'm not suggesting that Fira Code should be changed to `dlig` – obviously, that would be a breaking change for users, and as mentioned above, code ligatures are _the_ purpose of Fira Code. However, maaaybe version 3.0 could consider making the change.

One extra question for @tonsky: would you be willing to share why you use `LIG` quite often in the `calt` lookups? Is that referring to a class or something similar? Was it somehow partially generated by Glyphs, or another system? This is stumping me, so far... Thanks for any insight!

```
lookup less_equal_equal_greater {
  ignore sub less less' equal equal greater;
  ignore sub less' equal equal greater greater;
  sub LIG LIG LIG greater' by less_equal_equal_greater.liga;
  sub LIG LIG  equal' greater  by LIG;
  sub LIG  equal'  equal  greater  by LIG;
  sub less'   equal   equal  greater  by LIG;
} less_equal_equal_greater;
```

**Comment by tonsky** [comment]
LIG is just an empty glyph, I inventend name for it myself. Why I need it is explained here https://www.patreon.com/posts/fira-code-inside-28074541. If I could write

```
sub less equal equal greater by LIG LIG LIG less_equal_equal_greater.liga;
```

(in one substitution) that would be much simpler but for some reason it didn’t worked in `calt` or in `sub` (don’t remember). Also, in that case I could’ve just used `space` instead of `LIG`:

```
sub less equal equal greater by space space space less_equal_equal_greater.liga;
```

But because substitution is broken into multiple steps, `space` could’ve been confused with a regular whitespace in a text, so that wouldn’t work.

I agree with @j-f1 that the whole point of Fira Code is to have ligatures, so it wouldn’t make sense to hide them behind the toggle that many editors just don’t have. It might have sense for a new font though.

**Comment by tonsky** [comment]
Just tested Sublime Text 3, Intellij Idea, Text Edit, VS Code and Atom on macOS. Everyone except Atom can step inside ligatures, none needs caret instructions to do so. Atom ignores caret and can’t step into ligatures.

**Comment by tonsky** [comment]
I has checked simple N->1 substitution, e.g. `sub X X X by X_X_X.liga`. Where `X_X_X.liga` might or might not contain caret stops.

**Comment by arrowtype** [comment]
Awesome, thanks! That's really helpful to know. :)
