### ISSUE TITLE
The '⎈' character is clipped in mintty

### ISSUE THREAD

**Issue by antoineco** [tonsky/FiraCode#856]
The character `\u2388` (⎈) is clipped when using the mintty terminal emulator together with Fira Code (v2), while the same character is rendered properly with most other fonts.

![image](https://user-images.githubusercontent.com/3299086/66254526-b1b40400-e777-11e9-822c-db49de73f8aa.png) Fira Code (v2)
![image](https://user-images.githubusercontent.com/3299086/66258433-86e0a480-e7a5-11e9-8686-8b1066995330.png) Deja Vu Sans Mono

I figured I could report that here in case something is actually wrongly defined in the font itself.

Cross-referencing mintty/mintty#927

**Comment by tonsky** [comment]
I decided to make helm symbol double-width. Probably mintty doesn’t support that
