### ISSUE TITLE
Add ☰

### ISSUE THREAD

**Issue by rossjrw** [tonsky/FiraCode#859]
This symbol is used in [vim-airline](https://github.com/vim-airline/vim-airline) as the line number marker. In Fira Code, it does not appear to be monospaced (or is not defined) and on my terminal (which is HTML-based, thank ChromeOS), it pushes the rest of the line to the right.

**Comment by tonsky** [comment]
Ok

**Comment by tonsky** [comment]
'TRIGRAM FOR HEAVEN' (U+2630)
Might be the same as 'IDENTICAL TO' (U+2261)

**Comment by rossjrw** [comment]
Also requesting ☲ 'TRIGRAM FOR FIRE' (U+2632) for identical reasons

**Comment by qrqiuren** [comment]
> 
> 
> 'TRIGRAM FOR HEAVEN' (U+2630)
> Might be the same as 'IDENTICAL TO' (U+2261)

They are different. The eight trigrams are symbols of Taoism: https://en.wikipedia.org/wiki/Bagua
And 'IDENTICAL TO' (U+2261) should be a math symbol.

**Comment by chharvey** [comment]
@qrqiuren  You're right, they are different, especially when screen-reading software reads the names of some Unicode characters aloud.
