### ISSUE TITLE
Plus symbol is too small

### ISSUE THREAD

**Issue by VioletTape** [tonsky/FiraCode#86]
I've just installed fonts and set it up for VS2015. The + is very very small and hard to recognize. From the first sight it looks like * . For instance <+> looks very good, nice and big + sumbol.

**Comment by tonsky** [comment]
I actually was thinking about it as well. I’ll see what I can do

**Comment by nerbrume** [comment]
I think the same goes for ++ (I didn't even recognized the glyph at first...), and maybe also += (this one might be tricky, as we must keep the symmetry)
PS: for all it matters, all this is on VS2013, size 10

**Comment by AndreasDahl** [comment]
Just an opinion. But i also think that the `=` is too small.

**Comment by mik01aj** [comment]
yes yes, just wanted to report the same thing. Look at this:

![image](https://cloud.githubusercontent.com/assets/3027415/13883779/5db13fc0-ed2b-11e5-8014-31fb99875cf1.png)

I can barely see that it's a `+`.

**Comment by tomByrer** [comment]
Good demo @mik01aj

**Comment by tomByrer** [comment]
ty

**Comment by mik01aj** [comment]
I upgraded and the `+` is still tiny:

![image](https://cloud.githubusercontent.com/assets/3027415/17514624/f1999114-5e33-11e6-9a46-f47881eff3d7.png)

My font size is 13px.

**Comment by tonsky** [comment]
@mik01aj Just remove old version first 

<img width="206" alt="screen shot 2016-08-09 at 19 30 17" src="https://cloud.githubusercontent.com/assets/285292/17516317/340e0bc4-5e70-11e6-8427-35a58cc9f355.png">

**Comment by mik01aj** [comment]
yes, I removed the old one and it's good now. Thanks! 👍
