### ISSUE TITLE
Could you add a stylistic set option to turn off the .- ligature?

### ISSUE THREAD

**Issue by BrainFRZ** [tonsky/FiraCode#860]
Could you set ss07 or something to make `.-` look more like a regular Fira Mono .- rather than the ligature?

**Comment by tonsky** [comment]
Yes, maybe. Where does it bother you?

**Comment by BrainFRZ** [comment]
That would be great! I'm writing a Datalog interpreter, and I ran into issues when using hyphens to replace spaces in names with titles. For example, "Mr.-Smith" would end up with the ligature. I think this kind of thing could also happen in Node Express routes, since it's common to replace spaces with hyphens in URLs. Either way, thanks for making this font and your continued support. :)

**Comment by tonsky** [comment]
Will be disabled in v6 by default
