### ISSUE TITLE
Font is corrupted in Android Studio 3.5.1

### ISSUE THREAD

**Issue by Atulin** [tonsky/FiraCode#863]
Possibly has to do with #246, but FiraCode works perfectly with every single IntelliJ IDE I use except Android Studio. Which is not entirely a Jetbrains product, more of a Google product now, so I believe a separate issue is in order.
![image](https://user-images.githubusercontent.com/11233299/66964297-79b19880-f076-11e9-81d3-c1fd29614c32.png)
![image](https://user-images.githubusercontent.com/11233299/66964300-7cac8900-f076-11e9-999d-43fa51486897.png)

**Comment by tonsky** [comment]
Hi!

1. Try https://github.com/tonsky/FiraCode/wiki/Troubleshooting#corrupted-font-in-intellij-on-windows
2. Report to Android Studio

Thanks!

**Comment by Atulin** [comment]
Yeah, that seems to have fixed the issue, although the text looks blurry and neon-like now... That's certainly not FiraCode at fault, though.
