### ISSUE TITLE
Triple equals not rendering well in intellij "===" (Ubuntu 18.04 and windows 10)

### ISSUE THREAD

**Issue by Dazag** [tonsky/FiraCode#864]
Hi everyone, I haven't found the issue, but it seems like is not rendering very well the triple equals ligature in Intellij (PHPStorm) running in Ubuntu 18.04 and I got reports from a friend with windows 10 too. 
![image](https://user-images.githubusercontent.com/1424832/67001679-941d5d80-f0da-11e9-94c6-99937f132e88.png)
As you can see, the top line is more separated from the other two, so it doesn't seem symmetrical.
I've been thinking, this could be a Intellij error, but I tried out 'Victor Mono' font, and seems to work properly as the 3 horizontal lines are symmetrical. 
I hope it helps

**Comment by tonsky** [comment]
It’s a hinting issue, no easy way to fix unfortunately https://github.com/tonsky/FiraCode/wiki/Troubleshooting#hinting-issues
