### ISSUE TITLE
ss02 cannot be baked in

### ISSUE THREAD

**Issue by tessus** [tonsky/FiraCode#869]
According to the wiki page the following can be used to create a font that uses style sets permanently:

```
Baking in stylistic sets into the font file

This might be an option if your editor does not let you choose stylistic sets on the fly https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze
```

This works great for all style sets but ss02. Since it works with all but ss02 I do not think it is an issue with the `pyftfeatfreeze` script. I did not find a forum for Fira Code, so I'm posting it here.
Even if this is not a bug with the font, maybe somebody knows how to fix this.

As you can see from the output, the script remapped also ss02:

```
$ pyftfeatfreeze.py -n -v -f 'ss02,ss03,ss04,ss05' FiraCode-Regular.otf out/FiraCode-Regular.otf
[featfreeze][info] [RemapByOTL] Running with options: Namespace(features='ss02,ss03,ss04,ss05', info=False, inpath='FiraCode-Regular.otf', lang=None, names=True, outpath='out/FiraCode-Regular.otf', rename=False, replacenames=u'', report=False, script='latn', usesuffix=u'', verbose=True, zapnames=False)
/Users/tessus/bin/pyftfeatfreeze.py:140: UserWarning: 'verbose' is deprecated; configure logging instead
  self.inpath, 0, verbose=False, recalcBBoxes=False)
[featfreeze][info] [openFont] Opened font: FiraCode-Regular.otf
[featfreeze][info] [filterFeatureIndex] FeatureIndex: [3, 19, 35, 51, 67, 93, 109, 125, 141, 157, 173, 189, 205, 221, 237, 253, 269, 285, 301, 317, 333]
[featfreeze][info] [filterLookupList] Features to apply: [u'ss02', u'ss03', u'ss04', u'ss05']
[featfreeze][info] [filterLookupList] Lookups: [174, 175, 176, 177, 178, 179]
[featfreeze][info] [applySubstitutions] Remap: 'dollar' -> 'dollar.ss05'
[featfreeze][info] [applySubstitutions] Remap: 'at' -> 'at.ss06'
[featfreeze][info] [applySubstitutions] Remap: 'ampersand' -> 'ampersand.ss03'
[featfreeze][info] [applySubstitutions] Remap: 'ampersand_ampersand.liga' -> 'ampersand.ss03'
[featfreeze][info] [applySubstitutions] Remap: 'greater_equal.liga' -> 'greater_equal.ss02'
[featfreeze][info] [applySubstitutions] Remap: 'less_equal.liga' -> 'less_equal.ss02'
dollar.ss05 at.ss06 ampersand.ss03 ampersand.ss03 greater_equal.ss02 less_equal.ss02
[featfreeze][info] [saveFont] Saved font: out/FiraCode-Regular.otf
[featfreeze][good] Finished processing.
```

(There are certain apps where I can't use style sets, thus I have to use the pyftfeatfreeze workaround.)

I've also opened an issue with pyftfeatfreeze, but maybe someone has encountered this issue as well and knows a fix.

**Comment by tonsky** [comment]
Can you attach resulting file?

**Comment by tessus** [comment]
@tonsky sure, thanks for looking into this.

[FiraCode-Regular.otf.zip](https://github.com/tonsky/FiraCode/files/3748315/FiraCode-Regular.otf.zip)

**Comment by tonsky** [comment]
Yeah this looks bad. No idea why it can’t be baked, the SS itself is pretty trivial

**Comment by tessus** [comment]
Ok, so what does that mean? Is the script screwing something up? The strange thing is that the other style sets I specified work perfectly. This is really weird, especially since I don't underatand what the issue is.

**Comment by tonsky** [comment]
Probably

**Comment by tessus** [comment]
@tonsky I have received a reply from the pyftfeatfreeze dev, but I don't understand what it means (I guess you do):

_pyftfeafreeze only affects 1:1 substitutions where the source glyph has a Unicode codepoint. But if the source glyphs are results of a ligature substitutions, pyftfeafreeze won't have an effect._

/ref https://github.com/twardoch/fonttools-utils/issues/12

**Comment by madig** [comment]
It means ss02 substitutes one glyph without a unicode value for another without a unicode value. The way to fix it would be to assign e.g. a PUA unicode value to greater_equal.liga and the other one.

**Comment by tonsky** [comment]
There is probably a simpler approach to patching the font, just concat whatever code there is in ssXX and add it to the end of calt feature. That should work on the current version of the font, but you’ll need to do your own research on which scripts to use for that

**Comment by tessus** [comment]
I very much doubt that it is simpler because I did not understand a word of what you said.

As long as there are no fonts to download that include the substitutions, the only way to get around issues with apps that can't use font styles, is to use the script that you referenced. And if that does not work, we basically can't use the font. At least not the way, we would like to use it.
So I guess I'm stuck with the weird lesser and greater than equal signs.

**Comment by madig** [comment]
You'll have to peer into the .glyphs file, find `feature ss02 { ... } ss02;` and copy

```
sub greater_equal.liga by greater_equal.ss02;
sub less_equal.liga by less_equal.ss02;
```

and insert it somewhere near the end of `feature calt { ... } calt;`, maybe after `.multiply` substitutions. Then build the font.

**Comment by tonsky** [comment]
@madig exactly. I just suggested that there might exist a python script that can parse otf/ttf file, apply those modifications in memory, and write it back. I’m pretty sure Input font uses something like that on their site

**Comment by tessus** [comment]
I still have the problem with not being able to bake in ss02. I just tried with 3.1 and I see the same issue. All other ssXX can be baked in and work as expected.

I will try to build the font myself on the weekend (using the hints by madig), but I had a hard time installing the pre-reqs.

**Comment by tonsky** [comment]
Try #1387
