### ISSUE TITLE
'FiraCode' or 'Fira Code' ?

### ISSUE THREAD

**Issue by xianxingg** [tonsky/FiraCode#87]
On mac, both 'FiraCode' and 'Fira Code' work for the font-family setting. but on win10, only 'Fira Code' works.

Technically this may not be a issue or problem ...

**Comment by tonsky** [comment]
Well, font family name is `Fira Code` with a space. OS X let you sometimes reference font by file name as well (e.g. you can use `FiraCode-Medium` where you  expect a font name). This is not an issue though. Just use `Fira Code` everywhere
