### ISSUE TITLE
[bug] www ligature not rendering in iTerm 3.3.6

### ISSUE THREAD

**Issue by kryzar** [tonsky/FiraCode#870]
**FiraCode version**: v2, latest release
**Computer specs**: MacBook Pro 2015, macOS 10.14.6
**iTerm 2 version**: 3.3.6

When using the terminal iTerm 2, the ligature of `www` is not rendered:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/31312212/67160349-119dd380-f350-11e9-8350-4de199efaf96.png">
However, other ligatures are well rendered, for example: 

<img width="590" alt="image" src="https://user-images.githubusercontent.com/31312212/67160369-4f9af780-f350-11e9-9a73-87dc1f92e8c5.png">

Note that the `www` ligature is rendered well on Terminal.app.

Thanks a lot Tonsky for your great work, peace!

**Comment by tonsky** [comment]
Please report that to the iTerm team. Thanks!
