### ISSUE TITLE
Full Font Set Support

### ISSUE THREAD

**Issue by shoober420** [tonsky/FiraCode#871]
I pretty much use FiraCode system wide. In my terminal, all my GTK programs, even Steam itself. Almost all Steam games support FiraCode, except one. That game is SvenCoop.

FiraCode works in traditional GoldSrc games like CS1.6, TFC, and HL1. But, it doesn’t work in the GoldSrc engine mod and stand alone game SvenCoop.

I delve deeper into the matter, since it’s the only game with issues, and found that SvenCoop uses a special codepath that uses a “DroidSansMono” font. This font is found in the “ttf-droid” package in the Arch repositories.

I propose that big possible, please create a working alternative to “ttf-droid” fonts, and even support all font compatibility to be used as a full fledge font set, like “ttf-dejavu”, “ttf-croscore”, and “ttf-liberation”.

That way, for people who use FiraCode in everything, it can be used as an full fledged alternative font set and be used system wide for any program scenario.

Here’s a pic of the font set list to clarify what font sets I’m talking about.
![6488C98E-D420-4D54-970D-7A5B3F5F793C](https://user-images.githubusercontent.com/5150898/67169329-d368da00-f378-11e9-8d68-0a23f5af787f.png)

**Comment by tonsky** [comment]
Hi! Feel free to create whatever packages you need for yourself.

**Comment by shoober420** [comment]
I don’t think you understand what I was asking.

Could you please make FiraCode have full font set support like the mentioned font sets?

**Comment by tonsky** [comment]
I still don’t understand :) What’s full font set support?

**Comment by shoober420** [comment]
I’m sorry, I didn’t know the correct terminology at the time. What I meant to say was, “Font Family”.

So those font packages in that picture are font family packages that are meant to be used system wide, for all Linux apps, like GTK apps for example.

What I mean is, could you make FiraCode font family compatible so it can be used system wide for any application?

I thought it already was, because I use it in just about every program, but I recently found one game where it isn’t supported, and that’s SvenCoop.

SvenCoop uses DroidSansMono, and FiraCode doesn’t seem to have support for apps that use a Droid family font.

In the end, I’m asking, if possible, that FiraCode be compatible with being used in situations when a program calls for a Droid family font. FiraCode works in all other scenarios, except when Droid fonts are expected.

**Comment by tonsky** [comment]
What makes Fira Code font family incompatible?

> FiraCode doesn’t seem to have support for apps that use the Droid family font.

This sentence doesn’t even make sense. Of course Fira Code doesn’t support Droid family. It’s a different font.

**Comment by shoober420** [comment]
I’ll use the DejaVu font family as an example, since it includes  “Sans Mono” compatible set.

https://en.m.wikipedia.org/wiki/DejaVu_fonts

DejaVu, and most of those other font family packages picture in the first post, have metrically compatible “Arial”, “New Times Roman”, and “Courier New” font substitutes.

Can you make FiraCode metrically compatible like the font family sets mentioned to ensure system wide use for every scenario a certain font is called?

**Comment by tonsky** [comment]
You can’t make Fira Code metrics compatible with Arial / Times New Roman. Those are proportional fonts, Fira Code is monospaced. Maybe Fira Sans will work for you?

**Comment by shoober420** [comment]
So here something weird. When I installed the original ttf-fira-mono font, it worked in game. So for what ever reason, FiraCode is not seen as a mono spaced font.

**Comment by shoober420** [comment]
Is there a particular reason SvenCoop uses FiraMono in game, but doesn’t treat FiraCode the same way, and doesn’t use it?

**Comment by j-f1** [comment]
I wonder if it’s because the way Fira Code’s ligatures work involves characters that are wider than a normal character, so the game thinks it’s not a monospace font.

**Comment by shoober420** [comment]
I’m not sure, but I do know certain font family’s don’t work either. Here’s a list of the fonts and font family’s that work and don’t work.

WORK:  ttf-fira-mono,  ttf-dejavu, ttf-droid, ttf-bitstream-vera, gnu-free-fonts

BROKE: ttf-fira-code, ttf-croscore, ttf-liberation, noto-fonts, ttf-roboto

**Comment by shoober420** [comment]
Another interesting thing I should note, is I’ve recently switched my font to IBM Plex Mono. This font works in SvenCoop, and also works system wide, in every program and game. Maybe a look at the family tree structure can diagnose why FiraCode isn’t compatible with SvenCoop. 

https://github.com/IBM/plex

**Comment by shoober420** [comment]
In particular, this font family tree structure notes from the IBM Plex Github.

font-family: 'IBM Plex Mono', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', Courier, monospace;
font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;
font-family: 'IBM Plex Sans Condensed', 'Helvetica Neue', Arial, sans-serif;
font-family: 'IBM Plex Serif', 'Georgia', Times, serif;
