### ISSUE TITLE
Request: ..= ligature

### ISSUE THREAD

**Issue by testpost** [tonsky/FiraCode#874]
In Rust 1.26 and later, `..=` stands for an inclusive range, so `1..=10` is an iterator that includes the number `10`. Since this is based on the `..` exclusive range syntax, I'd recommend keeping the dots on the baseline and only adjusting the kerning.

**Comment by Kharacternyk** [comment]
It was there, but has been removed recently. I use v1.207 and I have it.

**Comment by tonsky** [comment]
Yeah. See #757

**Comment by testpost** [comment]
I still don't understand why it was removed instead of being redesigned, if nobody has found a use for it that conflicts with the Rust inclusive range syntax.

**Comment by tonsky** [comment]
Well redesigned how? It would be just two dots followed by the equality sign. How do you improve on that?

**Comment by testpost** [comment]
By kerning the equal sign closer to the two dots, the same way `..<` is handled
