### ISSUE TITLE
Add 🔒 (U+1F512) Lock sign

### ISSUE THREAD

**Issue by pellea** [tonsky/FiraCode#880]
The 🔒 (U+1F512) sign is not working on Windows. 

Is it the same as the one in the screenshot for powerline?
![image](https://user-images.githubusercontent.com/395982/67982503-17829700-fc23-11e9-9b91-c4ffe1a0ffb0.png)

Using the new Windows Terminal with Ubuntu WSL (with zsh and p10k theme, this is the only icon I cannot get properly).

In Windows 10 Fonts settings, the lock sign is not display either.

![image](https://user-images.githubusercontent.com/395982/67982336-cb375700-fc22-11e9-99e7-52a6d08cbf2f.png)

**Comment by tonsky** [comment]
U+1F512 is from Emoji. The lock on the picture is from private area defined by powerline. I guess I can reuse the same glyph for both. Thanks!

**Comment by tonsky** [comment]
After more consideration, I think it might be not that good of an idea to start putting Emoji symbols into Fira Code. Most of them are supposed to be rendered by fallback font, in bigger width and full color.

If possible, consider using Powerline lock symbol U+E0A2 `` instead.

Thanks!
