### ISSUE TITLE
Font's not working inside JetBrains terminal(WSL)

### ISSUE THREAD

**Issue by maxthyron** [tonsky/FiraCode#882]
Today for some reason Fira Code suddenly stopped working with my WSL terminal inside any JetBrains IDE(WebStorm, CLion, PyCharm), even though it continues to work in my Windows Terminal.

#### How it looks inside CLion terminal:

![image](https://user-images.githubusercontent.com/25431453/68148427-09978380-ff4d-11e9-9666-05f32957de1b.png)

#### How it looks in WT:

![image](https://user-images.githubusercontent.com/25431453/68148753-a823e480-ff4d-11e9-811e-172c61e44491.png)

#### How it looks inside CLion editor:

![image](https://user-images.githubusercontent.com/25431453/68149179-76f7e400-ff4e-11e9-91ea-9152861ebbc2.png)

### This is my CLion setting:

* Editor -> Font

![image](https://user-images.githubusercontent.com/25431453/68148658-7ad73680-ff4d-11e9-909d-e5a5d66d31c5.png)

* Editor -> Color Scheme -> Color Scheme Font

*I'm using custom theme, but switching it to default changes nothing.*

![image](https://user-images.githubusercontent.com/25431453/68148262-aa397380-ff4c-11e9-80be-64f6180cec0a.png)

* Editor -> Color Scheme -> Console Font

*For some reason I can't write inside this testing field as I did previously.*

![image](https://user-images.githubusercontent.com/25431453/68149016-2bddd100-ff4e-11e9-9cbb-0f869374a0f0.png)

### My environment:

* Windows 10
* Any JetBrains IDE
* WSL - both Ubuntu 16.04 and Ubuntu 18.04 as my terminal application in CLion
* WT - Windows Terminal
* Installed Fira Code Fonts inside Windows (*found that it's pointless to install inside Ubuntu*)

*P.S I have no clue what happened just in one day, but I already tried reinstalling font, Ubuntu and WT, toggling "Enable font ligatures", changing default scheme and theme in CLion. At this point I think that I just imagined that it worked properly.*

**Comment by tonsky** [comment]
I’m sorry to hear that. Can you report the issue to the CLion team please?
