### ISSUE TITLE
Stylistic set not followed in dollar sign ligature

### ISSUE THREAD

**Issue by jhpratt** [tonsky/FiraCode#884]
When using `ss04`, I have some code that has `Mul<$type>`. It looks like the `<$` is a ligature, and the stylistic option isn't followed there. Inserting a space between the two renders it as expected (with an added space, obviously).

**Comment by tonsky** [comment]
Thanks! I’ll update it

**Comment by jhpratt** [comment]
After looking at other issues, it looks like this is actually a duplicate of #830. Closing.
