### ISSUE TITLE
Non-monospaced Fira Code

### ISSUE THREAD

**Issue by lcswillems** [tonsky/FiraCode#885]
This may be a stupid suggestion, but would it be possible to have a non-monospaced Fira Code version (with ligatures), for web use?

For example, in my website, I may want to have a beautifully displayed "<=" ?

**Comment by j-f1** [comment]
Check out [Ligaturizer](https://github.com/ToxicFrog/Ligaturizer) and [Fira Sans](http://mozilla.github.io/Fira/).

**Comment by tonsky** [comment]
Fira Sans probably has <= as Unicode character

**Comment by tonsky** [comment]
I’m not doing it, but you can borrow the ligatures and do it yourself if you want

**Comment by BornForFever** [comment]
You can try Fira Sans!

**Comment by tonsky** [comment]
Fira Sans + Unicode characters. E.g. ≥
