### ISSUE TITLE
Support cursive italics

### ISSUE THREAD

**Issue by TheSETJ** [tonsky/FiraCode#887]
Can you please add cursive italics to your font? Something like what [Victor Mono](https://github.com/rubjo/victor-mono) or [CMU Typewriter Text (italic)](https://fontlibrary.org/en/font/cmu-typewriter#CMU%20Typewriter%20Text-Italic) did.

![image](https://user-images.githubusercontent.com/10893088/68582805-e01cb180-0490-11ea-8569-31c0fe7c3a32.png)
CMU Typewriter Text (italic)

![image](https://user-images.githubusercontent.com/10893088/68582865-ffb3da00-0490-11ea-9a18-77b8cd20c0d1.png)
Victor Mono

**Comment by tonsky** [comment]
Sorry, it’s just too much work
