### ISSUE TITLE
refined hexadecimal x with stylistic set zero

### ISSUE THREAD

**Issue by stefanwimmer128** [tonsky/FiraCode#888]
When using stylistic set zero but not onum the refined hexadecimal x is not working
![grafik](https://user-images.githubusercontent.com/16803954/68589369-fecc7980-048b-11ea-8f31-13e0c682dccd.png) instead of ![grafik](https://user-images.githubusercontent.com/16803954/68589439-27547380-048c-11ea-9a76-cdf75724e558.png)

**Comment by tonsky** [comment]
Thanks! I’ll fix it
