### ISSUE TITLE
VS Code doesn't recognizes Fira Code

### ISSUE THREAD

**Issue by vnaka1** [tonsky/FiraCode#889]
I installed the font in my system and added the command lines to settings.json

`"editor.fontFamily": "Fira Code",`
`"editor.fontSize: 12,`
`"editor.fontLigatures": true`

but it simply doesn't show it and I can't find what's the problem.

**Comment by hesselmonk** [comment]
Probably a missing ` "` after `"editor.fontSize` ?

**Comment by vnaka1** [comment]
No, I typed it wrong here, but in VS Code, it's `"editor.fontSize": 14,`. That's why I can't find the error, the command lines are exactly the same as instructed.

**Comment by vnaka1** [comment]
I also tried `"editor.fontFamily": "'Fira Code'"`, but it didn't work out.

**Comment by tonsky** [comment]
Can you screenshot your config, the installed font, and what you see in the editor please?

**Comment by vnaka1** [comment]
It worked. I restarted the system and entered the command line again, now it's working.

Thanks for the attention and help, guys!

**Comment by dzhavat** [comment]
I'm experiencing this issue now as well!

When I install the font and set it in VS Code, everything works. However, after a couple of days Windows somehow stops recognizing the font and renders something else instead. When I try to search for the font in the Windows' "Font settings", it is doesn't appear in the list. But when I try to install it again, Windows tells me that it's already installed.

**Comment by ropaolle** [comment]
See the installation documentation https://github.com/tonsky/FiraCode/wiki/Installing#windows.

"On some systems (especially Windows 10), you may need to "Unblock" each font file before installing. To do so, right-click each font file, click Properties, then check Unblock next to Security at the bottom of the General tab. Click OK, and then install. Note: Skipping this step may cause the Fira Code fonts to intermittently stop working in VS Code, even though the fonts still appear in other programs."

**Comment by gradientus** [comment]
> This is not the solution.  Have you tried that solution?  Unblocking isn't an option.  
The problem is that Chromium isn't recognizing the font when it is installed and available for all profiles.  
Maybe VSCode shouldn't be utilizing Chromium for this sort of functionality.  
You can change it here  chrome://settings/font  
Change the standard font to Fira Code.  It will work perfectly until you close VSCode.

**Comment by Hidrosoe1** [comment]
Hey, I have the same problem. I installed Fira Code and VS code just isn't showing it. this is my settings.json:

```
{
  "editor.fontSize": 15,
  "files.autoSave": "afterDelay",
  "editor.formatOnSave": true,
  "editor.suggestSelection": "first",
  "terminal.integrated.fontFamily": "Fira Code",
  "terminal.integrated.fontSize": 16,
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "workbench.colorTheme": "2077",
  "files.autoSaveDelay": 500
  }
```

**Comment by dividedby-0** [comment]
I had the same problem, and restarting the system after installing the font fixed it.

**Comment by ehsanaslanigitfront** [comment]
Install "FiraCode font - Professional Font for Developers" from "SeyyedKhandon" and fix your problem.

**Comment by m-usmananwar** [comment]
Hi @tonsky , I installed Fira code on my system by following the instructions given in ReadMe.txt file. But in my VS code Fira Code is not working 
`{
    "workbench.colorTheme": "Cobalt2",
    "workbench.iconTheme": "material-icon-theme",
    "files.autoSaveWhenNoErrors": true,
    "files.autoSaveDelay": 7000,
    "files.autoSave": "afterDelay",
    "explorer.compactFolders": false,
    "editor.fontLigatures": true,
    "editor.fontFamily": "Fira Code",
    "launch": {
        "configurations": [],
        "compounds": []
    }
}`
Here is my settings.json file. Could you please help me to resolve the issue. Thank you

**Comment by thisisamir256** [comment]
Hi
I use Fira Code in json settings. after save show me vscode support mnospace font only in terminal.
