### ISSUE TITLE
Stylistics sets not working properly in Visual Studio Code

### ISSUE THREAD

**Issue by pierredarrieutort** [tonsky/FiraCode#892]
Hi,

I currently using the last version of Visual Studio Code (1.40.1) and when i use the ligatures codes starting by "ss" the ligatures are not considered.
Only the stylistics sets like "zero" or "onum" working.

And when we push another value than 'true' to 'editor.fontLigatures' in settings no one ligatures work.

ref: https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets#vs-code

**Comment by nkempe** [comment]
Same here.

OS: Ubuntu 18.04
VScode 1.40.1
fonts-firacode version: 1.204-2 installed from ubuntu universe repository

**Comment by tonsky** [comment]
It’s the other way around for me `¯\_(ツ)_/¯`

<img width="659" alt="Screenshot 2019-11-15 at 13 42 04" src="https://user-images.githubusercontent.com/285292/68944265-bd9ad900-07ad-11ea-89a4-6136cdaa2aaf.png">

Please report it to VS Code repo

**Comment by ArturoDent** [comment]
@tonsky At a minimum use the single quotes version:

 ` "editor.fontLigatures":"'zero', 'ss02', 'ss03', 'ss04', 'ss05', 'calt'",`

and add `'calt'` it worked for me.
