### ISSUE TITLE
FiraCode 2 has become wider than 1.2xx versions

### ISSUE THREAD

**Issue by sabi0** [tonsky/FiraCode#894]
IntelliJ IDEA still ships with FiraCode 1.206.
I tried to replace the font files with FiraCode 2 ones. And discovered that spacing between letters has increased noticeably.
Check the screenshots here: https://youtrack.jetbrains.com/issue/IDEA-164888#focus=streamItem-27-3791892.0-0

Is it because of some change in the font? (I didn't find any mention of this on the releases page)
Or is it something about how IntelliJ IDEA sets up the rendering?

P.S. I like the capitals spacing in ABCDEF... better with FiraCode 2. But too large intervals between lowercase letters ruin it for me.
I understand you could either have less crammed capitals or more dense lowercase letters. And I personally would go for the latter since the text I work with is mostly lowercase.

**Comment by alexleduc76** [comment]
I have the same issue in VS Code. I had to change the font to Fira Code Light for it to look like 1.2xx version.

**Comment by tonsky** [comment]
Yes metrics were changed but very slightly:

- Tuned metrics (1870,-530 -> 1800,-600, upm 2000 -> 1950, hopefully fix #241 #252 #459 #552 #798)

The percieved change in character width should be less that 3%. On the upside it should be perfectly pixel-aligned at 13px font size

**Comment by tulir** [comment]
I manually reverted the metric and upm changes and now FiraCode 5.2 works properly in JetBrains IDEs :partying_face: (screenshots for reference: [1.x version that worked fine](https://mau.photos/rMRL3.png), [stock 5.2](https://mau.photos/F1x4e.png), [patched 5.2](https://mau.photos/6dbLy.png))

**Comment by dima-f1** [comment]
> I manually reverted the metric and upm changes and now the latest Fira Code version works properly in JetBrains IDEs 🥳 (screenshots for reference: [old 1.x version that worked fine](https://mau.photos/rMRL3.png), [stock 5.2](https://mau.photos/F1x4e.png), [patched master](https://mau.photos/6dbLy.png))

Can you share the build of patched fonts?

**Comment by tulir** [comment]
https://github.com/tulir/FiraCode/tree/master/distr/ttf

**Comment by ristomatti** [comment]
@tulir Thank you! With the IDE bundled font removed to allow your patched font to take over fixed the issues I was having. There's another workaround involving custom VM options you might want to check. I yesterday posted quite a lengthy analysis/thoughts on my personal findings regarding this issue https://youtrack.jetbrains.com/issue/JBR-2910.

**Comment by napsterv** [comment]
> https://github.com/tulir/FiraCode/tree/master/distr/ttf

Just the TTF is patched or OTF is patched too?
