### ISSUE TITLE
Add >>>= Javascript unsigned right shift assignment operator

### ISSUE THREAD

**Issue by JoelHernandez343** [tonsky/FiraCode#895]
The `>>>=` is a bitwise [unsigned right shift assignment operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators#Unsigned_right_shift_assignment) in Javascript and it would be really nice to have a ligature for.

**Comment by tonsky** [comment]
Sure, thanks!

**Comment by tonsky** [comment]
I think the way it looks now (`>>>` + `=`) is actually perfect. People has been asking to remove `>>=` as a single ligature. Let’s leave it as it is. Thanks!
