### ISSUE TITLE
Stylistic sets in Visual Studio

### ISSUE THREAD

**Issue by Gliptal** [tonsky/FiraCode#896]
I guess there is no way to specify stylistic sets in Visual Studio (like you can do in Visual Studio Code)?

**Comment by tonsky** [comment]
No idea

**Comment by alexeyten** [comment]
https://developercommunity.visualstudio.com/idea/536053/how-to-completely-disable-font-ligatures-feature-o.html

I guess it’s not possible for now

**Comment by apollolux** [comment]
For what it's worth, the only way that comes to mind for me at least is to have the [Custom CSS & JS Loader extension](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) installed and add some stylistic set(s) CSS to a given selector. [This Adobe page](https://helpx.adobe.com/fonts/using/open-type-syntax.html) outlines the available CSS OpenType values for `font-feature-settings` quite handily.

**Comment by icorbrey** [comment]
Does anyone have a workaround for this? I use both Visual Studio and VSCode and it would be very nice to be able to have the same variants in Visual Studio that I have active in VSCode

**Comment by MuTsunTsai** [comment]
This is another related issue.
https://developercommunity.visualstudio.com/t/add-ability-to-change-properties-of-a-fonts-typogr/1000588

**Comment by tonsky** [comment]
Try #1387
