### ISSUE TITLE
Stylistic set for lowercase "L"

### ISSUE THREAD

**Issue by maxloh** [tonsky/FiraCode#899]
Can you add stylistic set for "l" (lowercase L), like the one in Consolas or Roboto Mono?

Consolas 
![image](https://user-images.githubusercontent.com/35831069/69361524-9ff6d380-0cc7-11ea-88f8-44cf1c92f7e1.png)

Roboto Mono
![image](https://user-images.githubusercontent.com/35831069/69361475-881f4f80-0cc7-11ea-8178-5249c2fcee27.png)

**Comment by tonsky** [comment]
Should be possible, thanks!

**Comment by apollolux** [comment]
I'd like to suggest that this alternate 'l' have some tweak in the lengths of one or more of its bars to better distinguish it from '1' when used, or possibly make the angle of the 1's top bar more severe to compensate (either the base glyph or as an alternate in the same set as the suggested 'l').

**Comment by just-Addict** [comment]
I knew there was something that keeps me reverting back to Consolas, beside the fact it has a slightly narrower character width, making more text fit into the same physical line length.

**Comment by tonsky** [comment]
Will be in v6 as `cv07`-`cv10`
