### ISSUE TITLE
Questions regarding OFL 1.1

### ISSUE THREAD

**Issue by ImportTaste** [tonsky/FiraCode#901]
My apologies for asking here, but it is very difficult to get accurate responses to licensing questions because people like to pretend they know what they're talking about. I figure, if anyone knows the answer, it's the creators of a popular font on a site that deals with licensing issues a lot.

I would like to know if you have to include the license in some way or another if the font is used in artwork, and whether it matters if the artwork is for-profit or not. Assuming the answer is yes, do you have to embed it in the metadata somehow? What if the site you upload it to strips the metadata? Is it enough to just include it in the description of the submission?

Thank you for your time.

**Comment by tonsky** [comment]
I have no idea, sorry :)
