### ISSUE TITLE
Remove fi/fl

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#902]
@tonsky Hi Nikita. Have you seen the discussion here? Many people (including me) strongly dislike these ligatures. They look jarring in a monospace font (everything is spaced out, but then suddenly f and l are fused!?). And worst of all, `Tl` with the new ligatures looks like `π` (pi). Wtf. Hehe. Please make these ligatures optional via `ss` setting... :-( The first feeling after installing the font today was "wow this font is beautiful, but... ewwww that ligature... can I turn it off somehow?"... Sad that I can't. :-( I'd much prefer the original in the OP's post above. :-S

Edit: Ehm... my love for Fira Code was short lived (about 15 minutes). The "Fl / Tl" was so painful to look at that I started looking for other fonts. Found IBM Plex Mono at https://www.ibm.com/plex/ (https://github.com/IBM/plex/releases) which was designed by IBM for their programmers, to be looked at day in and day out. They used pixel-precise angles to ensure sharp rendering. It is incredibly crisp, extremely easy to read, and expertly designed. The italics are a work of art (which my editor uses for comments). There are no ligatures for stuff like `!=`, but the font puts those characters super close to each other (which looks great), so I don't miss ligatures. There is a modded version at https://github.com/IBM/plex/issues/63#issuecomment-552940293 which adds ligatures if someone _really_ wants that in the IBM Plex font... :-) Anyway, if Fira Code ever improves the "Pi"-like "Tl" situation, I may revisit this font too... but I'm off to IBM land now...

_Originally posted by @VideoPlayerCode in https://github.com/tonsky/FiraCode/issues/795#issuecomment-558014882_

**Comment by bkDJ** [comment]
+1. I recently got 2.0 (from 1.2) for a few of the nice new stylistic sets but was surprised the new `Tl`, `Fl` and `fl` could not be disabled.

**Comment by VideoPlayerCode** [comment]
I do think that Fira Code is beautiful too and would happily revisit this font, but the fi, fl, Tl situation is too jarring to look at.

Thanks a lot for opening this issue, @tonsky! All would be well if fi, fl, Tl ligatures are optional via 'ssXX' toggles. :-)

**Comment by nre-ableton** [comment]
Another +1 here. I'm _sure_ I'm not the only programmer using Fira Code who is annoyed by my editor constantly shifting text around when ligatures are updated every time I type `file` or `flex` or some other such thing. I love Fira's other ligatures, but this one seems to be very out of place.

**Comment by tonsky** [comment]
> constantly shifting text around

hmm this shouldn’t happen. Even in ligatures, letters have exactly the same dimensions and position

**Comment by joshkpeterson** [comment]
There's no logical reason that these characters should be fused. Gonna keep shopping around for other fonts. +1 for reverting.

**Comment by Coder-256** [comment]
@tonsky This is still an issue for me in v2, is there a fix planned for this?

**Comment by nre-ableton** [comment]
I'm jumping ship to [JetBrains Mono](https://www.jetbrains.com/lp/mono), which supports sensible ligatures but didn't go overboard with them.

**Comment by Mazwak** [comment]
For the record, I do not have this problem.

Windows 10,
VScodium or powershell
FiraCode 2.000

**Comment by UtkarshKunwar** [comment]
I've created a patched `.otf` for this Fl/Tl/fl issue [at my repo here](https://github.com/UtkarshKunwar/FiraCodeStyle-NerdFont) until we get an official stylistic set.
However, I enabled some stylistic sets which I liked (except ss06 and onum/ss20) for code readability and to get them to work with Konsole because I use NeoVim as my primary editor.

**Comment by BornForFever** [comment]
I agree. They look like one letter, which is confusing.

**Comment by tweakimp** [comment]
Is there any reason against making this a setting?

**Comment by tonsky** [comment]
@tweakimp the amount of stylistic sets is limited to 20. So I have to choose carefully what most important 20 settings are. If I could, I would make everything a setting, of course.

**Comment by tweakimp** [comment]
Thank you for your answer. How likely is this going to be optional? :)

**Comment by tonsky** [comment]
I’ll tell when I set down planning v3. I’ll either remove it or move it to a stylistic set

**Comment by RubenVerg** [comment]
aren't there two types of stylistic sets with 20 each?

**Comment by RubenVerg** [comment]
(and 21 anyway, I guess. ss00-ss20)

**Comment by nre-ableton** [comment]
Thanks so much for listening to the community feedback and removing these ligatures!
