### ISSUE TITLE
Linux installation package fonts-firacode is at v1.204

### ISSUE THREAD

**Issue by jack828** [tonsky/FiraCode#903]
Hey, first of all, thank you for arguably the best font out there :smile: 

I've been trying to update to v2 fonts since I spotted the update had been released, however I noticed during this that the `fonts-firacode` package on the [linux installation instructions](https://github.com/tonsky/FiraCode/wiki/Linux-instructions#installing-with-a-package-manager) is still pulling an old version of the package (v1.204).

I'm sure this is already on your todo list, but I wanted to ask just in case :grin: 

EDIT: I am also having trouble setting up v2 with kitty if I manually place the otf/ttf/woff/woff2 files in `/usr/share/fonts`, my kitty conf is setup to use Fira Code as:
```
font_family      Fira Code
```
This used to work in v1.2 but does not now.

FiraCode does not show in `kitty list-fonts`.

I appreciate this could be becoming a kitty issue...

EDIT2: Ha, I was using an old version of kitty!

**Comment by tonsky** [comment]
Seems like Debian has the latest version https://tracker.debian.org/pkg/fonts-firacode although Ubuntu does not https://packages.ubuntu.com/eoan/fonts/fonts-firacode. I'm not maintaining those packages, could you please notify the maintainers?
