### ISSUE TITLE
[Request] A new style for ligature ==

### ISSUE THREAD

**Issue by Gang-Yang** [tonsky/FiraCode#904]
The ligature of == is too similar with single =. How do think to re-design a new style for the ligture of == as PragmataPro or Iosevka?
The following are ligatures of "==", "===" and "/==" in PragmataPro.
![1](https://user-images.githubusercontent.com/29451722/69639160-0482ab80-1097-11ea-878d-2ba7994c191d.JPG)
![2](https://user-images.githubusercontent.com/29451722/69639162-064c6f00-1097-11ea-9ff6-ec93f0861a0a.JPG)
![3](https://user-images.githubusercontent.com/29451722/69639165-077d9c00-1097-11ea-9217-a6176b2d396e.JPG)
The following are some ligatures of "==" and "===" in Iosevka.
![5](https://user-images.githubusercontent.com/29451722/69639873-5c6de200-1098-11ea-9096-2ff064e92ac1.JPG)
![6](https://user-images.githubusercontent.com/29451722/69639874-5d067880-1098-11ea-9239-e7d641b1d175.JPG)

**Comment by tonsky** [comment]
I do not like it but a few people has been proposing it for quite some time, so I think it should be added as a stylistic set. Thanks!

**Comment by BornForFever** [comment]
Why? It's no good but adds to confusion.

**Comment by tonsky** [comment]
Will be handled in #383
