### ISSUE TITLE
terminal rendering issue

### ISSUE THREAD

**Issue by CodeDotJS** [tonsky/FiraCode#905]
There are some rendering issues within Terminal when I'm using FiraCode. 

__Problem 1:__ 

- Unable to render/display <kbd><strong>=</strong></kbd>

This issue exists while using both `zsh` and `bash`

![issue2](https://user-images.githubusercontent.com/9411252/69973455-88321180-1549-11ea-9413-e11a3567b6c4.png)

__Problem 2:__

- Typing __`>`__ directly gets changed into - 

![Screenshot from 2019-12-02 21-39-01](https://user-images.githubusercontent.com/9411252/69974929-38a11500-154c-11ea-8db3-93d36bb0443e.png)

and anything followed by <kbd>></kbd> gets changed into - 

![Screenshot from 2019-12-02 21-50-25](https://user-images.githubusercontent.com/9411252/69975748-c6c9cb00-154d-11ea-80d8-5b17e1cca1ae.png)

![Screenshot from 2019-12-02 22-00-05](https://user-images.githubusercontent.com/9411252/69976544-27a5d300-154f-11ea-8bca-aa28274e0889.png)

I'm not sure what's the reason for this problem, but I wonder if there's any way it can be fixed?

**Comment by alexeyten** [comment]
What terminal is it?
Does it work with any other font with ligatures?

**Comment by CodeDotJS** [comment]
> What terminal is it?

Gnome Terminal (Ubuntu 16.04 LTS)

> Does it work with any other font with ligatures?

I'm not entirely sure. I've haven't tested yet.

**Comment by alexeyten** [comment]
AFAIK Gnome terminal (or any other based on libvte) doesn’t support ligatures (yet?)

**Comment by alexeyten** [comment]
Oh, and of course you could switch to terminal that support ligatures. See README

**Comment by CodeDotJS** [comment]
> disable ligatures (I will try to give an example later)

@alexeyten sure

**Comment by alexeyten** [comment]
Put this into `~/.fonts.conf` (or any other suitable place. see `man fonts-conf`).
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="pattern">
        <test name="family" compare="eq">
            <string>Fira Code</string>
        </test>
        <test name="prgname" compare="eq">
            <string>gnome-terminal</string><!-- replace with program name -->
        </test>
        <edit name="fontfeatures" mode="assign_replace">
            <string>calt off</string>
        </edit>
    </match>
</fontconfig>
```

**Comment by agriffis** [comment]
The snippet above needs a small tweak to recognize GNOME Terminal: `compare="contains"` instead of `compare="eq"`

This is because the GNOME Terminal `prgname` is actually "gnome-terminal-server"

Slightly longer writeup at https://arongriffis.com/2020/02/09/gnome-terminal-ligatures
