### ISSUE TITLE
Make [: and :] independent ligatures

### ISSUE THREAD

**Issue by TheOnlyMrCat** [tonsky/FiraCode#906]
When working in flex, tokens such as `[:alnum:]` are used. I noticed that the ligature `[:]` is only activated when literal `[:]` is typed. I think it would be a good idea to have similar ligatures for `[:` and `:]`, at least as a stylistic set option.

**Comment by tonsky** [comment]
So the way it works is `:` is aligned to lower-case by default, but if it is surrounded by upper-case character it is realigned. In your case `[:a` here `[` is uppercase and `a` is lowercase so lower case takes precedence. If you type `[:ALNUM:]` you’ll see `:` would be aligned differently. This might be open for discussion, but e.g. in Clojure colon is part of the keyword, so e.g. in `[:kw]` colon should be aligned same as `kw`, now same as `[`. I realise that in some languages it’s the other way around, well, can’t satisfy everyone, sorry.

<img width="532" alt="Screenshot 2019-12-05 at 13 11 09" src="https://user-images.githubusercontent.com/285292/70234532-20561380-1761-11ea-8807-2ac31db8fe8a.png">
