### ISSUE TITLE
Add Wolfram RuleDelayed Operator `:>`

### ISSUE THREAD

**Issue by GalAster** [tonsky/FiraCode#909]
`:>` used in wolfram lang as **Delayed Rule**, related with **Instance Rule** `->`.

![](https://user-images.githubusercontent.com/17541209/70210844-a9277c00-176e-11ea-9fcb-bbff6ce64efe.png)

**Comment by tonsky** [comment]
It is already ligaturized. But I can’t draw arrow there because it might appear in other languages where you don’t expect it. Thankf for the idea!
