### ISSUE TITLE
Kerning changed in 2.0

### ISSUE THREAD

**Issue by klaasgeldof** [tonsky/FiraCode#910]
What happened to the kerning in version 2? I've been using version 1 for a long time. Now I installed a new MacBook Pro with Fira Code 2 and I immediately noticed a huge difference in the look of the font in my editor. It looked **way worse**. At first I didn't know what caused the look, but then I realized it was the kerning which is way looser in version 2.

I was surprised I didn't find any issue about this. Is this intended?

Here you can see a screenshot (both font size 14px):

![Screen Shot 2019-12-10 at 09 14 46](https://user-images.githubusercontent.com/35819/70508090-f79d9780-1b2d-11ea-87d0-6ec8b37ebba0.png)

**Comment by jdreesen** [comment]
Related: #833

**Comment by tonsky** [comment]
Yes, it was intended. It shouldn’t have been that dramatic, your editor probably rounds the coordinates to the nearest pixel and it triggered some sort of threshold. Actual change was less that 3% and shouldn’t in theory been noticeable at all.

**Comment by klaasgeldof** [comment]
Thanks for your reply. Unfortunately it is very noticeable in Sublime Text, an editor used by millions of people, as well as in all other places I use it for (like iTerm for example).

Will use version 1 for the rest of my life then... :(
