### ISSUE TITLE
Sans serif lowercase r is smaller than other symbols in JetBrains IDE

### ISSUE THREAD

**Issue by aplab** [tonsky/FiraCode#911]
See attachements for details

![Screenshot_3](https://user-images.githubusercontent.com/4007240/70519460-c8068380-1b5d-11ea-8224-481fdd9c21b9.png)
![Screenshot_4](https://user-images.githubusercontent.com/4007240/70519469-cb017400-1b5d-11ea-9ad9-c4d1a6344d1e.png)

Operating system Windows 10;
Font files installed in the IDE locally: (jbr/lib/fonts)

**Comment by tonsky** [comment]
Please report to JetBrains
