### ISSUE TITLE
Bold font floats up in Sublime Text

### ISSUE THREAD

**Issue by Asuza** [tonsky/FiraCode#912]
The bold style of the font seems to go up nearly a whole line compared to the normal style, and affects every line whether it has a bold font or not.
![image](https://user-images.githubusercontent.com/658248/70629484-af46ae00-1bef-11ea-9bae-3d2a4d4714a2.png)

This is happening on Windows 10, when using the following setting:
```
	"font_face": "Fira Code",
```

Using a more specific font face fixes the problem:
```
	"font_face": "Fira Code Regular",
```
The [wiki page](https://github.com/tonsky/FiraCode/wiki/Sublimetext-Instructions) does not suggest using anything other than `Fira Code` so I'm not sure if the problem is in the font itself, in Sublime Text, or the Wiki instructions.

**Comment by tonsky** [comment]
Try reporting this to the Sublime Text authors?
