### ISSUE TITLE
`#` symbol is automatically replaced with `£` symbol

### ISSUE THREAD

**Issue by thomasbabuj** [tonsky/FiraCode#914]
Whenever I type `#` character, it is automatically replaced with `£` in visual studio code mac. May I know how to fix this problem.

**Comment by tonsky** [comment]
Check your plugins. I doubt my font is the real reason

<img width="186" alt="Screenshot 2019-12-13 at 15 18 45" src="https://user-images.githubusercontent.com/285292/70806539-de117f80-1dbb-11ea-864a-81822003f444.png">

**Comment by thomasbabuj** [comment]
Hi @tonsky,

Thanks for your response. I am having this issue on my macOS Catalina (Chrome browser, Spotlight etc..)

![Screenshot 2019-12-25 at 6 00 08 PM](https://user-images.githubusercontent.com/511290/71442450-f29d3280-2740-11ea-99d6-49cb39b902be.png)

**Comment by alexeyten** [comment]
Check you keyboard settings. Prabably you use English UK layout

**Comment by thomasbabuj** [comment]
Hi @alexeyten, Thanks for the input. Yes i am using English UK layout as my keyboard input source. After changing it to the American layout, i am able to use `#`now.
