### ISSUE TITLE
Supports of FiraCode on Vim8 for Linux

### ISSUE THREAD

**Issue by Lyokolux** [tonsky/FiraCode#915]
I am searching on the internet about an answer but I didn't see any response for vim.
I have seen there are workarounds for gvim on Windows.

If any, please add vim8 and other versions in the column "not supported" in the README (distinct from gvim on windows).

Ty

**Comment by tonsky** [comment]
what’s vim (8)?

**Comment by Lyokolux** [comment]
I mean [Vim8](https://vim8.org/) (the version 8) and older versions.

**Comment by tonsky** [comment]
the one that works in terminal?

Best,
Nikita

**Comment by Lyokolux** [comment]
Yes :)
Run from shell with the `vim` command

**Comment by tonsky** [comment]
Then look for terminal compatibility, not vim. If terminal renders the font vim has nothing to do with it
