### ISSUE TITLE
Feature Request: Support for Gnome terminal

### ISSUE THREAD

**Issue by PranavBhattarai** [tonsky/FiraCode#916]
We all know, usually almost every distro ship with GNOME desktop edition by default.
This brings us to the GNOME terminal.

I think FireCode should be supported in the GNOME terminal. too

It was amazing to install FireCode using an **apt** command. **Thanks for that.**
I wonder why no GNOME Terminal support? Which is a bit weird and sad (disappointing).

Meanwhile, I am using Microsoft's **Cascade Code** which looks very interesting.

_But I want FiraCode. And there are a lot of users who want to switch to FiraCode._ 

![Distro: Ubuntu 19.10](https://user-images.githubusercontent.com/32763112/70844866-6735be80-1e6f-11ea-8b40-a33072ce997d.png)
`Distro: Ubuntu 19.10`

**Comment by tonsky** [comment]
You should talk to Gnome terminal developers. It’s up to them to support ligatures or not.

**Comment by PranavBhattarai** [comment]
> You should talk to Gnome terminal developers. It’s up to them to support ligatures or not.

Oh, that's bummer. So they do not support **ligatures**. Let me ask in [them](https://www.reddit.com/r/gnome/comments/eatz1q/is_there_any_reason_why_gnome_terminal_doesnt/).
