### ISSUE TITLE
[VSCode] Spacing is too small in editor, and too large in terminal

### ISSUE THREAD

**Issue by tbenst** [tonsky/FiraCode#920]
When I enable Fira Code, two spaces now renders as 1 in editor, but 1 space becomes two spaces in terminal. On Ubuntu 18.04. Let me know if I can help debug? Thanks!

![image](https://user-images.githubusercontent.com/863327/71291213-c8093f00-2326-11ea-87ce-1720addd01c8.png)

![image](https://user-images.githubusercontent.com/863327/71291273-f555ed00-2326-11ea-95ff-f82f2bcbde81.png)

**Comment by tonsky** [comment]
this is not Fira Code you are seeing. On both screenshots. Have you installed the font? Consult our Readme and Wiki

Best,
Nikita

**Comment by tbenst** [comment]
Thanks, tonsky! I was confused as the font changed so assumed was Fira-code...
For nixpks or NixOS users out there, solution was to add an overlay to VSCode:
```
self: super: {
  vscode = super.vscode.overrideAttrs (oldAttrs: rec {
    FONTCONFIG_FILE = super.makeFontsConf { fontDirectories = [ super.fira-code-symbols super.fira-code]; };
}
```
