### ISSUE TITLE
Request: setting 'meme'

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#925]
How about adding a ligature for the popular meme 'i-=-1'?

(this is a joke but I would love it implemented)
(actually 2 different ideas)
(idea for -= and += ligatures too xD)
![i-=-1](https://user-images.githubusercontent.com/52597868/71770631-145f9c00-2f2f-11ea-9c3c-1df606a89948.png)

**Comment by tonsky** [comment]
Fun, but I probably wouldn’t implement it for real, it’s too specific

Best,
Nikita

**Comment by RubenVerg** [comment]
ok! is there any way I can understand how to use Glyphs and make it my own version?

**Comment by RubenVerg** [comment]
:)
