### ISSUE TITLE
Fira Code Medium, Size 10 looks really bad in VS2019

### ISSUE THREAD

**Issue by redstripes89** [tonsky/FiraCode#928]
I was using v1.206 till I just realized that there's v2 already for a while. So I updated.
But after I restarted VS 2019, the code looks really bad in my configuration.
Using Fira Code Medium and font size 10. See picture for comparison. The font seems to be vertically stretched.
Fira Code Regular in size 10 works and so does Fira Code Medium in size 9 and 11. But I don't like increasing font size.

Was there some kind of breaking change that made the medium font not work anymore in size 10? 

Left: v1.206, size 10     //     Right: v2, size 10
![Image 002 - Copy](https://user-images.githubusercontent.com/31924564/71985582-1ffedb80-322b-11ea-967f-953b766d7e65.png)

**Comment by tonsky** [comment]
Yes, metrics were slightly changed (~3%) to better fit pixel grid on 13px size. The reason you are seeing such a big difference is probably because some rounding up is happening in your editor

**Comment by redstripes89** [comment]
So I have to stick with the old version or adjust my font size to avoid these effects?

**Comment by tonsky** [comment]
Yes

**Comment by redstripes89** [comment]
Ok, thanks for the information

**Comment by tonsky** [comment]
Sorry you have to deal with it, there was a few other issues with bold weight that were fixed this way but the downside was that metrics changed. I tried to make it as small as possible
