### ISSUE TITLE
"╱╲╳" look very dodgy in Fira Code

### ISSUE THREAD

**Issue by tecosaur** [tonsky/FiraCode#929]
I recently tried to create a tree diagram using box drawing characters. Everything seemed fine, except for three characters which were misbehaving :disappointed:. `U+257{1,2,3}` specifically. They _should_ stretch from the corners of the 'box'. In fira code they look ... stunted.

Below I have a screenshot of the same diagram, first with Souce Code Pro, then with Fira Code.

![image](https://user-images.githubusercontent.com/20903656/71986602-b5b85c00-3267-11ea-8518-96facd8ecfa2.png) ![image](https://user-images.githubusercontent.com/20903656/71986612-b8b34c80-3267-11ea-9fcf-05a1a058d2ab.png)

If this could be rectified, that would be great!

**Comment by tonsky** [comment]
Thanks, I’ll look into it!

**Comment by tonsky** [comment]
Will be fixed in v5

<img width="53" alt="Screenshot 2020-06-05 at 16 36 33" src="https://user-images.githubusercontent.com/285292/83889225-28603180-a74b-11ea-89e2-b44f309f13fe.png">

**Comment by tecosaur** [comment]
Nice! Thanks for sorting this out :)
