### ISSUE TITLE
..= in Rust

### ISSUE THREAD

**Issue by ropewalker** [tonsky/FiraCode#932]
Closed ranges in Rust look like this: `a..=b`, while half-closed ones are just `a..b` (see [examples](https://doc.rust-lang.org/rust-by-example/flow_control/for.html)), so displaying `..=` as  `••=` creates inconsistency. It would be nice to remove the ligature or create a stylistic set for it, depending on whether it is used in other languages.

**Comment by tonsky** [comment]
It was removed in v2, see #757 #874

**Comment by Coder-256** [comment]
This still has strange kerning for me:

<img width="78" alt="Screen Shot 2020-01-18 at 4 14 27 PM" src="https://user-images.githubusercontent.com/10134823/72670638-ad9db080-3a0d-11ea-91f9-387f96f44976.png">

**Comment by tonsky** [comment]
@Coder-256 well it’s a weird character combination
