### ISSUE TITLE
Tune spacing / disable `..` ligature in `..=`

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#934]
This still has strange kerning for me:

<img width="78" alt="Screen Shot 2020-01-18 at 4 14 27 PM" src="https://user-images.githubusercontent.com/10134823/72670638-ad9db080-3a0d-11ea-91f9-387f96f44976.png">

_Originally posted by @Coder-256 in https://github.com/tonsky/FiraCode/issues/932#issuecomment-575939084_

**Comment by rediffusion** [comment]
@tonsky 
Do you fix it? Should I download the font and install it again?

**Comment by tonsky** [comment]
No, I’ll probably take a look when I sit down to make next version
