### ISSUE TITLE
retina font and ligatures not working in visual studio for mac

### ISSUE THREAD

**Issue by catalintomescu** [tonsky/FiraCode#938]
I'm using the latest build of VS for mac. After setting the "fira code retina" as current font in editor settings I don't see any changes. On the other hand if I set the current font to "fira code regular" it seems to be working fine. I have a 2018 MBP with retina display. For what is worth all is good in VSCode, I can use "Fira Code Retina" w/o issues. I'm not sure if this is FIraCode font issue or VS issue. I tend to think it's VS related but wanted to check first.

**Comment by tonsky** [comment]
Can’t help there, probabaly VS issue. Font is just font, Retina name is non-standart so some editors might have an issue with it
