### ISSUE TITLE
Remove OTF from distr to avoid confusion

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#939]
> TTF has hinting, OTF has not. If your OS relies on it, use TTF (Windows, Linux probably too). On macOS hinting is ignored, so both TTF and OTF should work the same.

@tonsky  --- I just did a fresh install of linux and was struggling to get the font rendering right in vscode. After several hours of meddling with system, searching in my linux forms, I finally found the above point. And this resolved the issue --- I had installed OTF version.

So, I would suggest putting this point (TTF for linux, windows and OTF for macOS) somewhere in the home page or help section so that users can easily find it. 

And thanks for this beautiful font!

_Originally posted by @werunom in https://github.com/tonsky/FiraCode/issues/798#issuecomment-579094899_

**Comment by werunom** [comment]
Great! I have pointed this out to my linux distribution so that suitable message can be provided at the repository level as well. See [here](https://forum.manjaro.org/t/fira-code-font-issues-with-otf/121775).

Thanks!

**Comment by bmdixon** [comment]
FYI the install instructions for using chocolatey on [windows](https://github.com/tonsky/FiraCode/wiki/Installing#windows) say to install [firacode](https://chocolatey.org/packages/firacode). This has a note to say it will install the OTF fonts, for TTF you need the [firacode-ttf](https://chocolatey.org/packages/firacode-ttf) package.

**Comment by tonsky** [comment]
thx @bmdixon, fixed!

**Comment by salim-b** [comment]
The DEB package provided in the Ubuntu repositories also installs the OTF version of FiraCode which results in a blurry view.

The files in the `fonts-firacode` package from Ubuntu 20.04's `universe` repository:

```sh
$ apt-file list fonts-firacode
fonts-firacode: /usr/share/doc/fonts-firacode/README.md.gz
fonts-firacode: /usr/share/doc/fonts-firacode/changelog.Debian.gz
fonts-firacode: /usr/share/doc/fonts-firacode/copyright
fonts-firacode: /usr/share/doc/fonts-firacode/examples/fira_code.css
fonts-firacode: /usr/share/fonts-firacode/woff/FiraCode-Bold.woff
fonts-firacode: /usr/share/fonts-firacode/woff/FiraCode-Light.woff
fonts-firacode: /usr/share/fonts-firacode/woff/FiraCode-Medium.woff
fonts-firacode: /usr/share/fonts-firacode/woff/FiraCode-Regular.woff
fonts-firacode: /usr/share/fonts-firacode/woff/FiraCode-Retina.woff
fonts-firacode: /usr/share/fonts-firacode/woff2/FiraCode-Bold.woff2
fonts-firacode: /usr/share/fonts-firacode/woff2/FiraCode-Light.woff2
fonts-firacode: /usr/share/fonts-firacode/woff2/FiraCode-Medium.woff2
fonts-firacode: /usr/share/fonts-firacode/woff2/FiraCode-Regular.woff2
fonts-firacode: /usr/share/fonts-firacode/woff2/FiraCode-Retina.woff2
fonts-firacode: /usr/share/fonts/opentype/firacode/FiraCode-Bold.otf
fonts-firacode: /usr/share/fonts/opentype/firacode/FiraCode-Light.otf
fonts-firacode: /usr/share/fonts/opentype/firacode/FiraCode-Medium.otf
fonts-firacode: /usr/share/fonts/opentype/firacode/FiraCode-Regular.otf
fonts-firacode: /usr/share/fonts/opentype/firacode/FiraCode-Retina.otf
```

Maybe someone could inform the corresponding Debian package maintainer?

**Comment by FredHappyface** [comment]
I always thought that otf was the superior format (clearly I was wrong). So I guess my question is what is the benefit of using otf (is it for compatibility or something)?

**Comment by tonsky** [comment]
I think at some point OTF was superior to TTF, but now they are mostly the same. The difference between OTF and TTF is that TTF can embed hinting instructions, which are essential for rendering on low-res displays.

**Comment by FredHappyface** [comment]
Thanks for clearing that up 😄

**Comment by salim-b** [comment]
> Maybe someone could inform the corresponding Debian package maintainer?

I asked the Debian package maintainers to ship the TTF instead of the OTF version: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962478

**Comment by jsejcksn** [comment]
> TTF has hinting, OTF has not
> ([link](https://github.com/tonsky/FiraCode/issues/939#issue-557484122))

> I always thought that otf was the superior format (clearly I was wrong)
> ([link](https://github.com/tonsky/FiraCode/issues/939#issuecomment-640656439))

> I think at some point OTF was superior to TTF, but now they are mostly the same. The difference between OTF and TTF is that TTF can embed hinting instructions, which are essential for rendering on low-res displays.
> ([link](https://github.com/tonsky/FiraCode/issues/939#issuecomment-640665878))

I want to make sure there is no misinformation here, since there seems to be some confusion regarding _font format_ and _file extension_.

[The most recent release (v5) includes **OpenType** format fonts, using TrueType outlines and the `.ttf` extension](https://github.com/tonsky/FiraCode/releases/tag/5).

---

OpenType is a superior format to TrueType: it's a newer format based on TrueType, and improves it by several important features, such as:

  - Unicode character encoding
  - Expressive typographic features like small caps, old style figures, **ligatures**, etc.
  - Variable fonts (as of OpenType 1.8)

OpenType supports using either TrueType (TT) or PostScript (PS/CFF) outlines (TrueType uses embedded hinting, PostScript relies on the rasterizer).

Here are a few links regarding OpenType formats:

  - https://en.wikipedia.org/wiki/OpenType
  - https://en.wikipedia.org/wiki/Variable_fonts
  - https://www.adobe.com/products/type/adobe-type-references-tips/font-formats.html
  - https://blog.typekit.com/2010/12/02/the-benefits-of-opentypecff-over-truetype/
  - https://www.myfonts.com/info/opentype-flavors-ps-tt/

**Comment by tonsky** [comment]
Thanks @jsejcksn that clears out a lot of things!

**Comment by jsejcksn** [comment]
@tonsky After reading some more issues like #1057, I suggest that you publish a patch update with the same TTF files from version 5, but using the `.otf` extension. I don't think file extensions should be primary signals in modern software, but it seems like there are some workflows which still use them.

**Comment by darthoctopus** [comment]
I think it's important to point out that in particular Fira Code is a programming fonts with [programming ligatures](https://betterwebtype.com/articles/2020/02/13/5-monospaced-fonts-with-cool-coding-ligatures/). These cease to work when the TTF version is installed in lieu of the OTF version (as I found out today).
