### ISSUE TITLE
Add U+FF62 ｢ and U+FF63 ｣ halfwidth corner brackets for Perl 6 REPL display

### ISSUE THREAD

**Issue by hsmyers** [tonsky/FiraCode#940]
Needed are:

```
            Unicode character               Oct     Dec     Hex     HTML
    ⏏      eject symbol                    021717  9167    0x23CF  &#9167
    ｢       halfwidth left corner bracket   0177542 65378   0xFF62  &#65378;
    ｣       halfwidth right corner bracket  0177543 65379   0xFF63  &#65379;

```
These are similar to 0x2302, 0x2320, an 0x2321

**Comment by tonsky** [comment]
U+23CF is in the font since 2.0
U+FF62 and U+FF63 should be no problem

Can you paste an excerpt from the REPL session (as a text, preferably) so I can get a feeling how those are used?

Thanks!

**Comment by hsmyers** [comment]
An example…
------> a ~~⏏ /\w/;
> 'a' ~~ /\w/;
｢a｣
