### ISSUE TITLE
Alignment issues with multi-line utf8 parens

### ISSUE THREAD

**Issue by miniBill** [tonsky/FiraCode#942]
It looks like characters in the U+239B-U+23AE range have a different width than the rest of the Font.

![alignment](https://user-images.githubusercontent.com/191825/73667108-0fb01400-46a4-11ea-8aa1-ec8bbcbfac70.png)

OS: Windows (happens on Debian Linux too)
Font: Fira Code 2.0

**Comment by tonsky** [comment]
I don’t think they do

<img width="90" alt="Screenshot 2020-02-03 at 22 45 29" src="https://user-images.githubusercontent.com/285292/73693666-e65cab80-46d6-11ea-82ac-87d7d7d8e315.png">

either you are lookung at a different font, or at a different version of Fira Code. Also there’s no U+23AE in Fira Code, but it doesn’t seem like you are looking at it at this screenshot

**Comment by miniBill** [comment]
I can't seem to reproduce it anymore o.O
Sorry for your time
