### ISSUE TITLE
Add Unicode whitespace variations (em, en, figure, thin, hair etc)

### ISSUE THREAD

**Issue by jsumners** [tonsky/FiraCode#945]
According to https://en.wikipedia.org/wiki/Whitespace_character#Unicode there are several whitespace characters of varying widths. This is an odd request for a monospace font, but could support be added for explicit unicode spaces?

I have a very specific use case for this. I'd like to set my prompt like so:

```sh
PROMPT=$(echo -e '\u276F\u200A')
```

If this is too ridiculous, feel free to close.

**Comment by tonsky** [comment]
Thanks, that makes sense. If you are using non-default space, even in a monospaced font, it means you want to do something special. I’ll think about adding it.

**Comment by jsumners** [comment]
Awesome. Thank you.

**Comment by tonsky** [comment]
Recent experiments in #1000 showed that the existence of less-than-one width chars makes font not be detected as monospaced. Multi-width are fine, but less-than-one is no go. I’m afraid because of that I can’t satisfy your request. Sorry

**Comment by jsumners** [comment]
Oh well. Thank you for trying.
