### ISSUE TITLE
Request to add Dafny's <==> operator 

### ISSUE THREAD

**Issue by TijmenW** [tonsky/FiraCode#946]
Dafny's iff operator looks like this: `<==>`. However, in Firacode, it either looks like `≤>` or `<⟹`, depending on the IDE. Is it possible to add an operator?

**Comment by TijmenW** [comment]
I see I overlooked #346, so feel free to close this one.

**Comment by tonsky** [comment]
This one would be faster to add. Where is it used?

**Comment by TijmenW** [comment]
It's an operator in [Dafny](https://github.com/dafny-lang/dafny) that is almost the same as `==`, but only works with booleans, like this: 

```dafny
method testMethod() {
    assert true <==> true;
}
```

**Comment by tonsky** [comment]
Oh, I see. I thought that it was the name of the operator :)

**Comment by tonsky** [comment]
It seems that this is already in the font since 1.206 (see #392). Check your font version
