### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ackvf** [tonsky/FiraCode#947]
Hi, I am little confused, is your project related to https://github.com/bBoxType/FiraSans and how it differs?

I have noticed, there is a Fira Code version 3.206 and they also handled a similar bug

https://github.com/bBoxType/FiraSans#fira-code-3206
`- fixed bug #156 (swapped /BoxLightDown /BoxLightUp)`
which looks like https://github.com/tonsky/FiraCode/issues/595

---
I was using Fira Sans and while I was reporting a FiraCode issue here, I found out that it was already sovled (#595) and that I was using an older version, after that I realised all my Fira fonts were outdated so in search for new Fira Sans, I discovered that repo and now I am confused.

Wiki also mentions Fira Code, but there is no mention of you or your repo there?
https://en.wikipedia.org/wiki/Fira_Sans

**Comment by tonsky** [comment]
Fira is a family of typefaces developed by @bBoxType for Mozilla. It includes Fira Sans and Fira Mono.

Fira Code is this project which I based on Fira Mono and added 150+ new ligatures.

Two years after Fira Code was created @bBoxType updated Fira repo and introduced their own Fira Code font, which has no relation to this repo, has no ligatures etc. Their Fira Code is just a Fira Mono with different line height.

Although we share common source, two projects develop independently. I’d say Fira Code is more actively developed and supported.

**Comment by ackvf** [comment]
Thank you
