### ISSUE TITLE
Lua long strings/comments [[ [=[ [==[ etc

### ISSUE THREAD

**Issue by justarandomgeek** [tonsky/FiraCode#948]
Lua uses double brackets `[[` `]]` and extended double brackets with any number of `=` in them `[=[` `[==[` `[===[` `[====[` `]====]` ` ]===]` `]==]` `]=]` etc to designate multiline strings, and the same open bracket preceded immediately by `--` (like `--[[` `--[=[` etc) for multi-line comments. I assume you can't do an infinitely-long bracket ligature, but maybe some reasonable sized set of them (up to four, perhaps?) could be joined up?

**Comment by tonsky** [comment]
Thanks, I’ll see what I can do. Practice shows that joining brackets is not a good idea. But maybe brackets with equal sign could be safe. I haven’t seen this syntax anywhere else

**Comment by justarandomgeek** [comment]
Yeah, Lua has some... interesting quirks in the language. The long brackets are quite nice though, because they allow you to correctly quote anything without escaping, by simply using the next longer one than any close-bracket-like text in the string being quoted (or commented)! I've seen them up to six equals long in the wild, but rarely. Zero and one equals is probably 99% of all of them.

**Comment by tonsky** [comment]
Should be better in v4
