### ISSUE TITLE
Unicode math symbols

### ISSUE THREAD

**Issue by bergwerf** [tonsky/FiraCode#950]
I use FiraCode with Coq and to me the ligatures are superior to using just unicode (for example a unicode implication arrow is tiny, whereas `->` with ligatures takes up exactly the amount of space I like). However some unicode math symbols (particularly those reachable as LaTeX commands) are quite poor. For example calligraphic letters (`\mathcal{N}`) or symbols (like `\in`). Also white spaces are broken (no longer the same size) after those symbols. Perhaps this is a fallback font? If I can configure a different fallback font perhaps I can find a good compromise.

![image](https://user-images.githubusercontent.com/4458965/75474375-2c83f280-5997-11ea-869a-0e838a852687.png)

It would be awesome if a bunch of mathematical symbols could be added to FiraCode! (I can imagine symbols like `\in` being very useful in other programming languages as infix operator).

**Comment by tonsky** [comment]
Probably a fallback font. If you give me a list of what you need I’ll start putting them in

**Comment by bergwerf** [comment]
Awesome, thank you! I will try to create a more comprehensive list later
(sorted by priority).
Some really common symbols that I would like to use a lot are U+2208,
U+2200, U+2203

Then a lot of the binary operators in the Mathematical Operators Unicode
block could come in handy here and there, maybe there is some existing
mathematical monospace font that could be used as basis to have basic
support for such characters (I looked for one but couldn't find it). In Coq
you can create custom notations with any sort of unicode characters you
like, which is much more readable. Being able to use somewhat obscure
symbols that are available as LaTeX commands can be really useful (the IDE
allows you to type those inline). A list of such symbols is here:
https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols

**Comment by tonsky** [comment]
Will be handled in #822
