### ISSUE TITLE
A displaying defect on ZSH with theme: powerlevel10k

### ISSUE THREAD

**Issue by Photonico** [tonsky/FiraCode#959]
On Terminal Emulator (Konsole):
![Terminal Emulator](https://raw.githubusercontent.com/Photonico/Problems/master/2020/20200228a.png)

On VSCode:
![VSCode](https://raw.githubusercontent.com/Photonico/Problems/master/2020/20200228b.png)

As shown in pictures, the diamond is not perfect.

And cannot show this character : [](https://fontawesome.com/icons/lock)
![Character](https://raw.githubusercontent.com/Photonico/Problems/master/2020/20200228c.png)

Powerlevel10K: https://github.com/romkatv/powerlevel10k

**Comment by tonsky** [comment]
Can you clarify? What diamond? What’s wrong?

As for the lock, font awesome is an icon font which replaces letters with icons. Fira Code is not supposed to show its icons.

**Comment by Photonico** [comment]
> Can you clarify? What diamond? What’s wrong?
> 
> As for the lock, font awesome is an icon font which replaces letters with icons. Fira Code is not supposed to show its icons.

Diamond means the rhombus, 

The effect is not perfect: there is a small gap. 

![a](https://raw.githubusercontent.com/Photonico/Problems/master/2020/20200228d.png)
![b](https://raw.githubusercontent.com/Photonico/Problems/master/2020/20200228e.png)

**Comment by j-f1** [comment]
I think that issue is caused by the line height of your terminal.

**Comment by tonsky** [comment]
This is a known problem that, unfortunately, can’t be solved once for every terminal, os and font size. Font rendering is varies hugely between apps, so no matter what I do something will always remain brocken.

**Comment by Photonico** [comment]
> This is a known problem that, unfortunately, can’t be solved once for every terminal, os and font size. Font rendering is varies hugely between apps, so no matter what I do something will always remain brocken.

I have tried some terminal emulators, all they has this problem.

I think if the triangles was a bit larger, this problem may be solved.

**Comment by j-f1** [comment]
Looks fine for me:

<img width="22" alt="Screenshot_2020-02-28 11 16 35" src="https://user-images.githubusercontent.com/25517624/75565372-d2794080-5a1b-11ea-962f-69c9c7a417e9.png">

**Comment by Photonico** [comment]
> Looks fine for me:
> 
> <img alt="Screenshot_2020-02-28 11 16 35" width="22" src="https://user-images.githubusercontent.com/25517624/75565372-d2794080-5a1b-11ea-962f-69c9c7a417e9.png">

If you zoom in your picture, u also can find the gap.

The dark background can make this gap more obvious.

**Comment by tonsky** [comment]
SublimeText, macOS:

<img width="124" alt="Screenshot 2020-02-28 at 19 08 55" src="https://user-images.githubusercontent.com/285292/75573944-2a389b80-5a5e-11ea-8595-df51a0813759.png">
<img width="121" alt="Screenshot 2020-02-28 at 19 08 49" src="https://user-images.githubusercontent.com/285292/75573959-31f84000-5a5e-11ea-93f0-bf4294133ed8.png">
<img width="129" alt="Screenshot 2020-02-28 at 19 08 59" src="https://user-images.githubusercontent.com/285292/75573966-34f33080-5a5e-11ea-992e-7b57bbc2d9df.png">

Terminal.app, macOS:

<img width="127" alt="Screenshot 2020-02-28 at 19 09 53" src="https://user-images.githubusercontent.com/285292/75574019-42101f80-5a5e-11ea-9e15-9bd8fe4d5aa8.png">
<img width="115" alt="Screenshot 2020-02-28 at 19 09 20" src="https://user-images.githubusercontent.com/285292/75574021-43414c80-5a5e-11ea-8d35-ee91cd644670.png">
<img width="177" alt="Screenshot 2020-02-28 at 19 11 04" src="https://user-images.githubusercontent.com/285292/75574024-44727980-5a5e-11ea-9fda-1425ea48d3c3.png">

Fira Code dimentions are set so that at 13px it might fit into the pixel grid, so that’s the recommended size if this kind of thing bothers you

**Comment by tonsky** [comment]
We have a lock symbol at U+E0A2, same as all the others powerline fonts https://github.com/powerline/fonts

**Comment by Photonico** [comment]
> SublimeText, macOS:
> 
> <img alt="Screenshot 2020-02-28 at 19 08 55" width="124" src="https://user-images.githubusercontent.com/285292/75573944-2a389b80-5a5e-11ea-8595-df51a0813759.png">
> 
> <img alt="Screenshot 2020-02-28 at 19 08 49" width="121" src="https://user-images.githubusercontent.com/285292/75573959-31f84000-5a5e-11ea-93f0-bf4294133ed8.png">
> 
> <img alt="Screenshot 2020-02-28 at 19 08 59" width="129" src="https://user-images.githubusercontent.com/285292/75573966-34f33080-5a5e-11ea-992e-7b57bbc2d9df.png">
> 
> Terminal.app, macOS:
> 
> <img alt="Screenshot 2020-02-28 at 19 09 53" width="127" src="https://user-images.githubusercontent.com/285292/75574019-42101f80-5a5e-11ea-9e15-9bd8fe4d5aa8.png">
> 
> <img alt="Screenshot 2020-02-28 at 19 09 20" width="115" src="https://user-images.githubusercontent.com/285292/75574021-43414c80-5a5e-11ea-8d35-ee91cd644670.png">
> 
> <img alt="Screenshot 2020-02-28 at 19 11 04" width="177" src="https://user-images.githubusercontent.com/285292/75574024-44727980-5a5e-11ea-9fda-1425ea48d3c3.png">
> 
> Fira Code dimensions are set so that at 13px it might fit into the pixel grid, so that’s the recommended size if this kind of thing bothers you

Thank you for your recommendation.

For my computer (Solus KDE, Resolution: 1920x1080), 
The gap is also obvious in 13px. This problem can be solved if I use the fontsize >= 72px.

**Comment by alexeyten** [comment]
You could try to tune font antialiasing settings

**Comment by Photonico** [comment]
> You could try to tune font antialiasing settings

I have tried to cancel the antialiasing option. it can solve this small problem but the effect is terrible-looking.

**Comment by Photonico** [comment]
I have modified these two characters(E0B2, E0B0) and some other characters to meet my expectations.

Can I publish my customized font on my Github?

**Comment by tonsky** [comment]
> Can I publish my customized font on my Github?

Yes!
