### ISSUE TITLE
Stylistic sets seem to be an overkill usage of typographic features

### ISSUE THREAD

**Issue by baco** [tonsky/FiraCode#962]
Most of the changes achieved through the _Stylistic Sets_ (if not all) only change one character at a time instead of a set of them.  According to the list of typographic features that can be used in OpenType standard, _Character Variant_ (`cv00`-`cv99`) feature seem to be more suitable for the situation instead of wasting stylistic sets.

**Comment by tonsky** [comment]
That is true! I at the very least should copy what I do with ss to cv too. My motivation was that in software I’m around SS are sometimes present, cv I see very rarely. E.g. Sublime Text only supports ss00-ss10 for some internal reason. But for sure, cv-s are the way to go. Thank you for reminding me of this!

**Comment by tonsky** [comment]
I’ll keep already used sets for compatibility, but new character variations will be in `cv**` starting from v6. Thanks!
