### ISSUE TITLE
Ligature request: "this." into 1 character for javascript

### ISSUE THREAD

**Issue by isral** [tonsky/FiraCode#963]
In JavaScript, I forced to write "this." (5 characters including dot) to access object members.
It takes a lot of screen spaces especially when I view 2 files side by side.
Shorten "this." to just 1 character will help.
Thanks.

**Comment by tonsky** [comment]
This is possible, but too controvertial I think. Maybe consider configuring your editor to do the substitution?

**Comment by shnizmuffin** [comment]
Oh my god, have the ligature for "this" spell "that"

Dom Bonanni
