### ISSUE TITLE
Will Fira Code Symbol be updated for supporting more ligature characters?

### ISSUE THREAD

**Issue by CanftIn** [tonsky/FiraCode#965]
Hi,
I have used **Fira-Code-Symbol** in emacs. And it seems the only way working on emacs by the ligature symbols font with unicode.
I find that the symbols font has been a long time(4 years ago) for only include [124 ligature symbols](https://github.com/tonsky/FiraCode/issues/211#issuecomment-239058632) .

But the **Fira Code v2** have already released. 
A lot of new ligatures not including in **Fira Code Symbol** such as `|-`, `-|`,  `|=>`, `|->`, `|}` and so on.

So just a wish, whether **Fira Code Symbol** will be updated, or is there anyway that we can build new symbols font by ourselves? If there's a way, I will be pleased to build a new symbols font.

And thanks for the excellent font and your work.
![image](https://user-images.githubusercontent.com/26135447/76144697-fc86ce80-60bd-11ea-9a66-c25bb7b6f6c1.png)

**Comment by tonsky** [comment]
Yes, I have a plan of making this happening. Let’s track it in #211
