### ISSUE TITLE
Fl/fl ligature looks very weird in most words

### ISSUE THREAD

**Issue by drhumlen** [tonsky/FiraCode#966]
I see this all the time in my codebase since f & l are adjacent all the time. This ligature does more harm than good. In general, I think we should avoid having ordinary letters and words ligatures and stick to ligatures only for symbols.

<img width="86" alt="Screenshot 2020-03-09 at 10 01 49" src="https://user-images.githubusercontent.com/4758115/76197771-0f4bf100-61ed-11ea-80de-21ec8e7fd033.png">

**Comment by tonsky** [comment]
I hear you. Will resolve, track #902
