### ISSUE TITLE
Disable ligatures in progress bars

### ISSUE THREAD

**Issue by tonsky** [tonsky/FiraCode#968]
https://github.com/JetBrains/JetBrainsMono/issues/151

![](https://user-images.githubusercontent.com/1784740/74747980-b3cabb00-525f-11ea-88d3-50e103d7b209.png)

**Comment by nilp0inter** [comment]
This still happens on progress bars of some command-line programs. Can it be fixed in any way?

For example this is a progress bar that appears when loading a docker image with `docker load`:

![image](https://user-images.githubusercontent.com/1224006/83395919-68e24700-a3fb-11ea-8935-858ddbaa8da2.png)

**Comment by j-f1** [comment]
Do you have the latest version of Fira Code installed?

**Comment by nilp0inter** [comment]
I use Arch and have the latest available version which is `4-1`. AFAIK is the latest.

```
Name            : otf-fira-code
Version         : 4-1
Description     : Monospaced font with programming ligatures
Architecture    : any
URL             : https://github.com/tonsky/FiraCode
Licenses        : custom:OFL
Groups          : None
Provides        : None
Depends On      : None
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 939.14 KiB
Packager        : Jiachen YANG <farseerfc@archlinux.org>
Build Date      : Mon 18 May 2020 07:51:12 AM CEST
Install Date    : Mon 01 Jun 2020 10:15:47 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by mfocko** [comment]
Try ttf?

**Comment by tonsky** [comment]
@nilp0inter which terminal are you using?

**Comment by nilp0inter** [comment]
@tonsky , I am using QTerminal.

**Comment by nilp0inter** [comment]
@mfocko , already tried ttf, same results.

**Comment by tonsky** [comment]
Might be an issue with a terminal. Can you try it in any of the supported editors? Just to make sure?

**Comment by nilp0inter** [comment]
I tested using `Konsole`, exact same result:

![image](https://user-images.githubusercontent.com/1224006/83613056-89d5a400-a583-11ea-9469-fd0b49e5342d.png)

This is the raw console text it is trying to render:

```console
$ docker load < result                                      
4ce9f247a3c6: Loading layer [==================================================>]  49.66MB/49.66MB
```

And these are the hashes of the fonts, just in case:

```console
$ pacman -Ql ttf-fira-code | grep '\.ttf' | awk '{print $2}' | xargs md5sum
68e73b469a459295f740f1fc45623996  /usr/share/fonts/TTF/FiraCode-Bold.ttf
cda568e562b21e881c56bfca996a354e  /usr/share/fonts/TTF/FiraCode-Light.ttf
d81ebfe1fe1b9bc96e5c160965b36a4e  /usr/share/fonts/TTF/FiraCode-Medium.ttf
93277bd1b9b89d277b66a3d2147d31d9  /usr/share/fonts/TTF/FiraCode-Regular.ttf
acf90150560a6ec8dfa823bb8ac27d81  /usr/share/fonts/TTF/FiraCode-Retina.ttf
0a3633106a704cd28b1648faa53cfbf3  /usr/share/fonts/TTF/FiraCode-SemiBold.ttf
```

I will try some more terminals.

**Comment by tonsky** [comment]
Seems to be correct md5. What about e.g. Sublime Text or VS Code, which are known to work? Can you try there?

This is what I see in Apple Terminal:

<img width="568" alt="Screenshot 2020-06-03 at 13 49 45" src="https://user-images.githubusercontent.com/285292/83633502-5bff5800-a5a1-11ea-8d72-91d4ebbdd5c6.png">

**Comment by tonsky** [comment]
@nilp0inter pls move the discussion to #1064
