### ISSUE TITLE
Disable Elvis ligature (?:) for optional TypeScript properties

### ISSUE THREAD

**Issue by Peeja** [tonsky/FiraCode#970]
I don't know languages where `?:` is used as an operator well, but in TypeScript the sequence comes up a lot in interfaces, denoting optional properties in an interface:

![image](https://user-images.githubusercontent.com/2407/76460724-ee35fc80-63b4-11ea-9b80-5fbbda65b738.png)

The two characters don't form an operator here, they just happen to be next to each other, so the ligature is odd. Is `?:` always (or at least usually) surrounded by spaces when it's used as an operator? Maybe it would work to only apply the ligature to ` :?`, with the preceding space? (I don't have much experience with ligatures like this, so I have no idea if I'm asking for something reasonable.)

**Comment by tonsky** [comment]
Interesting! I’ll mark it as a conflict but I’m not sure what can I do, except removing ligature altogether

**Comment by jdreesen** [comment]
It's used as ternary if operator in PHP. Spaces are not required.

**Comment by Peeja** [comment]
@jdreesen Wouldn't that be `foo ? bar : baz`? That's not going to use the `?:` ligature.

**Comment by j-f1** [comment]
I know some languages (C?) use `a ?: b` as shorthand for `a ? a : b` or how `a || b` works in some languages.

**Comment by jdreesen** [comment]
> @jdreesen Wouldn't that be `foo ? bar : baz`? That's not going to use the `?:` ligature.

Right, but you can do `$foo ?: $baz`, too, which returns `$foo` if `$foo` evaluates to `true`, and `$baz` otherwise. Example: https://3v4l.org/8H95j

**Comment by BenLeggiero** [comment]
Sad to see this go, but I understand why it did

**Comment by a-p-o** [comment]
[Kotlin uses ?: (elvis operator)][1]. It is conventionally surrounded by spaces. This is an unfortunate change for Kotlin users 😢

[1]: https://kotlinlang.org/docs/reference/null-safety.html#elvis-operator
