### ISSUE TITLE
Make "there exists" ∃ monospaced

### ISSUE THREAD

**Issue by rodolphito** [tonsky/FiraCode#973]
The forall symbol has the correct spacing, but the exists symbol does not. Also they could both use a little love, they are useful in theorem proving languages with Unicode support.
```
∃ exists
∀ forall
```

<img width="85" alt="Screen Shot 2020-03-13 at 12 19 37 AM" src="https://user-images.githubusercontent.com/11307157/76598575-61786500-64c0-11ea-82de-952c74cb88cd.png">

Thanks for this awesome font!

**Comment by tonsky** [comment]
Thank, will add!

**Comment by tonsky** [comment]
Covered by #822
