### ISSUE TITLE
Add a option to desactivate <<= and >>= ligatures

### ISSUE THREAD

**Issue by GrayJack** [tonsky/FiraCode#974]
Some languages uses `<<=` and `>>=` as bitshift assign operators, like Rust and Zig, and the ligatures look weird in those contexts, so I propose creating a new stylistic set that deactivate the ligatures for those or change the ligatures to better represent bitshift assign operators.

What are your thoughts?

**Comment by tonsky** [comment]
I’m not agains, but there is a limited amount of stylistic sets. I’ll see how it aligns with the others. Thanks!

**Comment by wundrweapon** [comment]
If this gets implemented I would argue the stylistic set would change how `>>=`, `>>>=`, and `<<=` only are rendered. They deserve ligatures, and the usual arrow behavior is lovely, but I can see why those three in particular look a bit… *bleugh* in bitwise code
