### ISSUE TITLE
Line height in FiraCode 2

### ISSUE THREAD

**Issue by Thaoden** [tonsky/FiraCode#976]
I recently installed FiraCode 2 and want to use it in Visual Studio 2019, however, once I set the font to anything FiraCode, the line height (or line spacing, not sure) is almost doubled. Is this intended behaviour?

![FC](https://user-images.githubusercontent.com/3832723/76778600-6718c800-67aa-11ea-928f-a45e2232c4f9.jpg)

**Comment by tonsky** [comment]
This seems way too much. This is the default line height in Sublime Text on macOS:

<img width="675" alt="Screenshot 2020-03-16 at 18 48 56" src="https://user-images.githubusercontent.com/285292/76786088-ddbbc280-67b6-11ea-8357-f26dbe3fcd68.png">

**Comment by Thaoden** [comment]
That's the line height I know when using the default font (Consolas). Any idea how this happened and what I can do to revert it (save using a different font).

**Comment by tonsky** [comment]
No idea, sorry

**Comment by Thaoden** [comment]
Restarting VS2019 several times, at one point, the line height adjusted.

Sorry for the noise.
