### ISSUE TITLE
Alignment of glyphs and square brackets

### ISSUE THREAD

**Issue by xcambar** [tonsky/FiraCode#98]
As per the following screenshot, some glyphs are leaning towards the closing square bracket (especially ✭ and ✹)

<img width="180" alt="screen shot 2015-12-30 at 14 09 04" src="https://cloud.githubusercontent.com/assets/657654/12051108/fdb6b95c-aefe-11e5-949f-8e59efed866c.png">

Hope this helps making Fira Code even better,

**Comment by tonsky** [comment]
These glyphs are not in Fira Code. Your editor is using some other font,
maybe not even monospaced, to show them.

**Comment by xcambar** [comment]
A bit of context:

* I'm using iTerm2 (beta)
* Settings point to Fira Code (both ASCII and non-ASCII)

I know nothing about how OSX or iTerm renders fonts, so I may be plain wrong, but apparently, for such glyphs, the Apple Emoji Font is used as a fallback (see https://gitlab.com/gnachman/iterm2/issues/3384). So it originates either from OSX itself or iTerm2. Surely @gnachman can distill knowledge here :)

I'm just going to work around this issue and configure the vim plugin I'm using to display glyphs that Fira Code implements.

Thanks for helping.

**Comment by gnachman** [comment]
It's just the combination of fonts, I think. Everything is monospaced in iTerm2, but some combos of symbols don't look good. I haven't added support for custom kerning yet :)
