### ISSUE TITLE
Please add a semi bold option.

### ISSUE THREAD

**Issue by das-code** [tonsky/FiraCode#987]
I would like to have one more degree between **Medium** and **Bold**. Like a **Retina** option, between **Regular** and **Medium**.
![Screenshot from 2020-03-29 11 12 53](https://user-images.githubusercontent.com/26780549/77851348-2314c280-71af-11ea-93f6-df7f3b676f98.png)
![Screenshot from 2020-03-29 11 14 03](https://user-images.githubusercontent.com/26780549/77851350-23ad5900-71af-11ea-8617-2c5971edb586.png)

**Comment by tonsky** [comment]
Shouldn’t be too hard, sure

**Comment by j-f1** [comment]
Isn’t this supported by the Variable Font version?

**Comment by tonsky** [comment]
Sure, but how many editors support variable fonts?

**Comment by j-f1** [comment]
At least the web-based/Electron ones, probably.
