### ISSUE TITLE
Font ligatures not working in Windows Terminal

### ISSUE THREAD

**Issue by alexanderbittner** [tonsky/FiraCode#989]
Font ligatures do not render properly in the new Windows Terminal.
Cascadia Code ligatures work fine in the Terminal, so I assume this is an issue with Fira Code.
I can provide more info if needed, a screenshot is attached below:
![image](https://user-images.githubusercontent.com/7916327/78486795-95554c00-7747-11ea-9145-d08080967309.png)

Windows Terminal Version: 0.10.781.0

**Comment by alexanderbittner** [comment]
To compare, this is how cascadia code looks in the same environment:
![image](https://user-images.githubusercontent.com/7916327/78491623-f2053680-7748-11ea-81c4-7363ddad00eb.png)

**Comment by tonsky** [comment]
I‘d say it‘s a problem with Windows Terminal and best reported there. Thanks!

**Comment by subodhpareek18** [comment]
I think it could be ttf vs otf or a versioning issue. I uninstalled everything and installed ttfs of the latest build again and everything is working great now.

**Comment by RubenVerg** [comment]
Always worked for me with OTF

________________________________
