### ISSUE TITLE
Ligature for "->" Doesn't Work Properly

### ISSUE THREAD

**Issue by Tyleo** [tonsky/FiraCode#99]
I have tried to get the "->" ligature to display for two separate programming languages (C++ and Rust), with two separate editors (Atom and Visual Studio 2015), and on two separate computers (both Windows 10). Unfortunately, the symbol does not seem to be appearing. All other ligatures appear to work properly.

I suspect that it is the ligature which is broken rather than the editors.

**Comment by Tyleo** [comment]
This gets it to work in Atom:

```
atom-text-editor {
  text-rendering: optimizeLegibility;
}
```

Appears to be a problem with the editors after-all.

**Comment by vidoardes** [comment]
Is there any way to correct this in VS2015?
