### ISSUE TITLE
Optional http/https/ftp/git/file

### ISSUE THREAD

**Issue by RubenVerg** [tonsky/FiraCode#991]
Contrarily to a lot of coders here, I really like the www ligature, and think that should be integrated in a set that also contains ligatures for http, https, ftp, git and file (if there are other protocols really used, add them too I guess).
![suggestion](https://raw.githubusercontent.com/RubenVerg/Storage/master/liga.png)

**Comment by RubenVerg** [comment]
(the squares are for boxing.)

**Comment by tonsky** [comment]
Thanks for the suggestion! I already have fi/fl ligatures but many people seem to dislike them. As for full http/https/etc, the intention is good, but I’d prefer more natural connections. WWW exists mostly because I figured out a way to nicely draw it

**Comment by RubenVerg** [comment]
hehe

**Comment by RubenVerg** [comment]
I don't really realize why people don't like www, but -second suggestion- maybe should only render when the adjacent characters are not alphabetic (like not in ewww).
