### ISSUE TITLE
The FiraCode font does not look like it shoule be

### ISSUE THREAD

**Issue by hongquangraem** [tonsky/FiraCode#992]
I have installed FiraCode font before with command `sudo apt install fonts-firacode`, then config in font text editor, but the font does not look I expect
[Image](https://res.cloudinary.com/hongquangraem/image/upload/v1586429540/Screenshot_from_2020-04-09_17-51-55_ftf5lw.png)

**Comment by j-f1** [comment]
That looks right to me. What looks wrong to you?

**Comment by tonsky** [comment]
@hongquangraem what did you expect?

**Comment by hongquangraem** [comment]
[image](https://res.cloudinary.com/hongquangraem/image/upload/v1586524612/Screenshot_from_2020-04-10_20-15-28_mcqkh6.png)
The icon does not change, the is not the Fira Code font I guess

**Comment by tonsky** [comment]
text looks like perfectly fine fira code to me. If you wanted to change icons, you need something else

**Comment by j-f1** [comment]
Oh I see @hongquangraem. Try enabling “font ligatures” in your settings.

**Comment by hongquangraem** [comment]
@j-f1 I enabled it before in the setting.json file, like you can see in the first picture I attached

**Comment by tonsky** [comment]
I see the problem now, sorry. I have no specific advice, but maybe some extensions installed conflict with ligatures? What OS is that? Do ligatures work in other apps?

**Comment by hongquangraem** [comment]
I don't know why, but I tried to set up again and it works now. Thanks you guys two to support me!
