### ISSUE TITLE
Font variants for different purposes

### ISSUE THREAD

**Issue by ghost** [tonsky/FiraCode#994]
Some ligatures are good for one language/use-case but are not wanted in another.
At the moment, those ligatures get remove to not annoy anyone.

Maybe it would be a good idea to make 2 or 3 variants of FiraCode where each contains some of the conflicting ligatures split to some use-cases/languages.
Maybe a base variant with less ligatures, and some variants which contains the conflicting ones?

Otherwise, maybe more [stylistic sets](https://github.com/tonsky/FiraCode/wiki/How-to-enable-stylistic-sets) would be great

(Also fine to leave it as it is - I am not missing something particular :)

**Comment by tonsky** [comment]
I’m taking stylistic sets approach for now. Maintaining multiple version would be too cumbersome. Eventually we might end up using locl and language tags but apply them to programming languages. I think some fonts are already doing it, don’t remember who. Also editor support is probably lacking https://github.com/tonsky/FiraCode/issues/76

**Comment by adah1972** [comment]
I see that releasing multiple versions can be very cumbersome for you. Are there any tools that can help in this? Maybe switching on different style sets by default?

With more and more ligatures coming into this font, conflicts are more and more likely. Unwanted ligatures are annoying. Regretfully, program editors are not typesetting programs, and they are often lacking in supporting advanced features like style sets. It seems Vim does not support it so far.

**Comment by tonsky** [comment]
Resolved via #1387
