### ISSUE TITLE
Misplaced descenders on Cyrillic letters U+04B3 and U+04CB

### ISSUE THREAD

**Issue by dscorbett** [tonsky/FiraCode#995]
The descenders of U+04B3 CYRILLIC SMALL LETTER HA WITH DESCENDER and U+04CB CYRILLIC CAPITAL LETTER KHAKASSIAN CHE are misplaced. Their capital and small counterparts respectively are correct.
![ҲҳӋӌ](https://user-images.githubusercontent.com/1124347/79007650-9ca29e00-7b29-11ea-87d1-d4eb5ee20d22.png)

**Comment by llathasa-veleth** [comment]
And that's how they suppose to look normally.
![Screenshot_20200410_205631](https://user-images.githubusercontent.com/61933599/79011891-c1b90000-7b6d-11ea-89d6-080cb35f51bd.png)
![Screenshot_20200410_205654](https://user-images.githubusercontent.com/61933599/79011920-cf6e8580-7b6d-11ea-82a4-88b9f6215f18.png)

**Comment by dscorbett** [comment]
The lower image is not relevant to this bug report: it depicts <U+04B6 CYRILLIC CAPITAL LETTER CHE WITH DESCENDER, U+04B7 CYRILLIC SMALL LETTER CHE WITH DESCENDER>, where the descender is on the right. Fira Code gets those glyphs right. In U+04CB, the descender is on the left.

**Comment by tonsky** [comment]
Thanks! Will take a look in the next version
