### ISSUE TITLE
Wrong glyph for U+03F4 GREEK CAPITAL THETA SYMBOL

### ISSUE THREAD

**Issue by dscorbett** [tonsky/FiraCode#996]
The crossbar U+03F4 GREEK CAPITAL THETA SYMBOL should reach all the way to the edges. Currently, it looks identical to U+0398 GREEK CAPITAL LETTER THETA.
![ϴΘ](https://user-images.githubusercontent.com/1124347/79049901-59613180-7bf4-11ea-9712-376bbef74840.png)

**Comment by tonsky** [comment]
Thank you, will fix!
