### ISSUE TITLE
Wrong glyph for U+0314 COMBINING REVERSED COMMA ABOVE

### ISSUE THREAD

**Issue by dscorbett** [tonsky/FiraCode#997]
The glyph of U+0314 COMBINING REVERSED COMMA ABOVE is upside-down: it looks like U+0312 COMBINING TURNED COMMA ABOVE should.
![t̔](https://user-images.githubusercontent.com/1124347/79073920-495e5600-7cb7-11ea-9f70-6cf4ba6768e4.png)

**Comment by tonsky** [comment]
Thank for this too — will fix in the next version
